### ISSUE TITLE
Function call in SELECT causes ParseError

### ISSUE THREAD

**Issue by edt-andrew** [tobymao/sqlglot#1016]
Using a function call in a SELECT statement causes a parse error:

ParseError: Expected AS after CAST. Line 1, Col: 49.
  SELECT 'CONSTANT' AS a1, cast('text', c2) AS a2, 
 c3 AS a3 [....]

The error message highlights the comma after the 'text' parameter in the CAST function call.

**Comment by GeorgeSittas** [comment]
Hey, thanks for the report. This happens because SQLGlot tries to parse the standard syntax: `CAST(x AS foo)`.

Can you provide some more information, like what dialect this is used in, docs, etc?

**Comment by GeorgeSittas** [comment]
This seems like non-standard syntax, so I'm closing this temporarily.

**Comment by edt-andrew** [comment]
This is Denodo syntax. Denodo is a data virtualisation platform increasingly in use in large organisations.

https://community.denodo.com/docs/html/browse/8.0/en/vdp/vql/functions/conversion_functions/conversion_functions#cast
