### ISSUE TITLE
end is not allowed in Databricks, tough it should be ok

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#1026]
```python
import sqlglot as sg
sg.parse("SELECT end from a", "databricks")
```

end is not a keyword in databricks. However the above fails never the less

**Comment by aersam** [comment]
Might be a bit complicated as Case is supported in Databricks. Low Prio for me

**Comment by GeorgeSittas** [comment]
I think we can just add `TokenType.END` to `ID_VAR_TOKENS` in the base parser. I'll take a look soon.
