### ISSUE TITLE
Support for QUALIFY 

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#1027]
the following is not recognized:

```python
import sqlglot as sg 

sg.parse("""
select id from b.a a
        qualify row_number() over (partition by br order by sadf desc) = 1
""", "databricks")
```

QUALIFY is supported by databricks and a number of other cool databases (such as duckdb)

**Comment by GeorgeSittas** [comment]
I can look at this soon.

**Comment by aersam** [comment]
Thanks a lot! Will be pleased to use 10.5.8 :)
