### ISSUE TITLE
Thousand separators

### ISSUE THREAD

**Issue by alippai** [tobymao/sqlglot#1034]
Is there a way to allow numeric literals with thousand separators in custom driver? Eg 10_000_000 == 10000000

**Comment by tobymao** [comment]
yes. you just need to override your custom tozkenizer to parse numerics and allow _

https://github.com/tobymao/sqlglot/blob/91ada8b37a33cc6252a7c64dbd6db890ecf79aa5/sqlglot/tokens.py#L960

**Comment by alippai** [comment]
Thanks!
