### ISSUE TITLE
Cannot Translate now() from presto to Hive

### ISSUE THREAD

**Issue by junchenfeng** [tobymao/sqlglot#1036]
Case in point:
`select a	from tbl where data_dt = if(hour(now()) between 0 and 6 ,date_format(current_date - interval '1' day, '%Y-%m-%d') ,date_format(current_date - interval '0' day, '%Y-%m-%d')) `
					
translates into 
`SELECT a FROM tbl WHERE data_dt = IF(HOUR(NOW()) BETWEEN 0 AND 6, DATE_FORMAT(CURRENT_DATE - INTERVAL '1' day, 'yyyy-MM-dd'), DATE_FORMAT(CURRENT_DATE - INTERVAL '0' day, 'yyyy-MM-dd'))`

If someone can point me to the right part of code, I am happy to try to fix it myself and submit a pull request

**Comment by tobymao** [comment]
what is now supposed to translate into?

**Comment by tobymao** [comment]
i guess just current_timestamp?

**Comment by tobymao** [comment]
@junchenfeng you can see 93c17b5, and use that as an example for future prs.

**Comment by junchenfeng** [comment]
Thanks very much.
