### ISSUE TITLE
AST + parsing support for `MATCH_RECOGNIZE`

### ISSUE THREAD

**Issue by voberoi** [tobymao/sqlglot#1038]
Snowflake implements `MATCH_RECOGNIZE`, which sqlglot doesn't seem to currently parse. I believe Oracle also implements `MATCH_RECOGNIZE`.

https://docs.snowflake.com/en/sql-reference/constructs/match_recognize.html

I'd be happy to provide a PR for this, but won't be able to get to it for a few weeks.

**Comment by tobymao** [comment]
@voberoi i've added support for match_recognize but the pattern section is difficult because it's regex, this may need to be done at the tokenizer level
