### ISSUE TITLE
Databricks: CREATE TABLE SELECT Fails to Parse

### ISSUE THREAD

**Issue by pahunter90** [tobymao/sqlglot#1048]
Thank you for the sqlglot library. We are excited about using it to parse Databricks notebooks.

We have come across a parsing issue during our exploration, namely Databricks allows for queries such as:
`CREATE TABLE TBL_1 SELECT 1`
or
`WITH ALIAS_1 (SELECT 1) SELECT * FROM ALIAS_1`
(i.e. the `AS` is not required.)

Both of these statements fail to parse (seems to be looking for a column definition rather than a select statement).

Any advice on how to parse these statements?

Above example:
**Databricks**
![image](https://user-images.githubusercontent.com/32236862/215545980-5d535c67-42d2-42bf-925e-c1513fad1349.png)

**sqlglot**
![image](https://user-images.githubusercontent.com/32236862/215547602-6cbafe83-985b-4c9d-b5e6-b65ae344256c.png)
![image](https://user-images.githubusercontent.com/32236862/215547634-702c7a2a-e5a8-4c1b-88af-bc4e38691b8c.png)

**Comment by tobymao** [comment]
this has been added, but i suggest your team uses standard sql constructs by including the AS statement.

**Comment by pahunter90** [comment]
Thanks and agree. We try, but are dealing with a large ecosystem of analysts and devs with varying skills.
