### ISSUE TITLE
snowflake to trino qualify does not convert

### ISSUE THREAD

**Issue by alaturqua** [tobymao/sqlglot#1051]
Converting qualify from snowflake to trino does not work. Trino does not have qualify.

input:
```
select *
from product_sales
qualify count(*) over (partition by product_id) > 1
```

code:
```
import sqlglot
from sqlglot.optimizer import optimize

with open('./test.sql', 'r') as f:
    sql = f.read()
    print(sqlglot.transpile(sql, read='snowflake', write='trino', pretty=True)[0])
    
```

output:
```
SELECT
  *
FROM product_sales
QUALIFY
  COUNT(*) OVER (PARTITION BY product_id) > 1
```

**Comment by tobymao** [comment]
transpilation is best effort, not everything is possible to transpile. something like qualify to a system without qualify is out of scope for now, but happy to discuss an approach if you have one

closing as won't fix but not opposed to a solution if it's possible

**Comment by tobymao** [comment]
this has been implemented https://github.com/tobymao/sqlglot/pull/1288

@GeorgeSittas can you add eliminate_qualify to presto/hive/spark but not databricks?

**Comment by alaturqua** [comment]
> this has been implemented #1288
> 
> @GeorgeSittas can you add eliminate_qualify to presto/hive/spark but not databricks?

@tobymao 

that is great!

But it works currently only with snowflake to sqlite.

If I put trino as write="trino". It keeps qualify in the result.

**Comment by GeorgeSittas** [comment]
Yep, I can add it for said dialects too.

**Comment by GeorgeSittas** [comment]
https://github.com/tobymao/sqlglot/pull/1302
