### ISSUE TITLE
Hive Dialect for 'insert ... partition' error

### ISSUE THREAD

**Issue by ruichengnew** [tobymao/sqlglot#1057]
Here is a good case, the partition state is string '0'. If we change it to int 0, then there is a error.
![image](https://user-images.githubusercontent.com/34465781/215731767-5c164d0f-f83b-41c1-ae05-6d96daf04247.png)

Int 0
![image](https://user-images.githubusercontent.com/34465781/215732091-7a88a752-f850-412e-b193-8fd00600152c.png)
![image](https://user-images.githubusercontent.com/34465781/215732141-f0523e5b-7592-402e-a47e-ed4a3697d857.png)

**Comment by GeorgeSittas** [comment]
I posted a PR for this, but I couldn't find any documented example where the partition is used without strings in the right hand side. Are you sure this is correct Hive SQL?
