### ISSUE TITLE
Hive Dialect for 'select ...' error

### ISSUE THREAD

**Issue by ruichengnew** [tobymao/sqlglot#1058]
When the field name is a built-in word like 'desc', there will be a error

![image](https://user-images.githubusercontent.com/34465781/215733416-681a0464-080b-4549-bc11-40af5f18f63b.png)
![image](https://user-images.githubusercontent.com/34465781/215733763-12e17069-49ee-4e8d-a91f-91824104e2a6.png)

Actually, there is a field named 'desc' in this table 'a'

**Comment by GeorgeSittas** [comment]
I would just add `DESC` to `ID_VAR_TOKENS` to solve this, but it breaks other tests that are tricky to solve.

Closing this as not planned. Related discussion: https://github.com/tobymao/sqlglot/discussions/1049.
