### ISSUE TITLE
Hive Dialect for 'drop partition' error

### ISSUE THREAD

**Issue by ruichengnew** [tobymao/sqlglot#1059]
sqlglot cannot parse 'Alter table drop partition'
![image](https://user-images.githubusercontent.com/34465781/215734164-d096ccd4-206d-4873-8ed0-5a0736d0e3a8.png)
![image](https://user-images.githubusercontent.com/34465781/215734331-abf34b7e-605e-476c-863f-a086e88bdce5.png)

**Comment by GeorgeSittas** [comment]
Make sure to use text instead of images for any next issues, because it's easier to copy-paste that way.
