### ISSUE TITLE
Does sqlglot support python2?

### ISSUE THREAD

**Issue by xeniogd** [tobymao/sqlglot#1071]
My project is currently running on python2. An error is reported after installing sqlglot10.5.10. Does sqlglot support python2?
![image](https://user-images.githubusercontent.com/42986720/216218010-7953fbf2-773a-4e4f-bb72-7b3f050bd1f4.png)

**Comment by barakalon** [comment]
No.

[The Python Software Foundation sunset Python 2 on January 1, 2020](https://www.python.org/doc/sunset-python-2/).

SQLGlot supports Python 3.7 and up.
