### ISSUE TITLE
SQL Server vs Databricks Meaning / Transpiling Issue

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#1073]
In SQL Server, the following codes means something different than in databricks:

```sql
SELECT   OrderNo_Sales= 123 FROM current.sales
```
In SQL Server, this outputs a column called OrderNo_Sales with value set to 123.

In Databricks however it's a logical comparision, meaning it will return a boolean column. 

This breaks transpiling. I Propose to rewrite SQL Server's Syntax to standard "AS"

**Comment by aersam** [comment]
SQL Server does not otherwise support something like boolean expressions in Select, in needs to use things like "CASE WHEN" to use booleans

**Comment by tobymao** [comment]
@aersam you wrote a stored procedure

```

                         DECLARE @SalesAmountBefore float
                         SELECT @SalesAmountBefore=SUM(SalesAmount) FROM TRANSF.[Pre_Merge_Sales_Real] S
```
this will be rewritten to select @salesamountbefore = sum(salesamount) as _col

is that ok?

**Comment by tobymao** [comment]
after looking at it, it's not safe to transform tsql select x = 1 to select x = 1 AS _col because it's not the same. TSQL supports this syntax which is not supported in databricks, so this is a won't fix. 

if you want to tsql to work in databricks, you should write equivalent code which is

select x = 1 AS x

**Comment by aersam** [comment]
Not sure I agree. I'll try to fix it with a transpiler and share to code if it works

**Comment by tobymao** [comment]
@aersam do you want to rewrite your procedure?

**Comment by tobymao** [comment]
are you ok with select @sales = sum(y) AS _col?

**Comment by tobymao** [comment]
@aersam i already have a fix for this, but i scrapped it because it breaks the create procedure i added for you

**Comment by aersam** [comment]
Ok, that topic is a bit strange. So here are my thoughts:

in t-sql this: 
```sql 
SELECT   Margin=Sales - SomeCosts FROM current.sales
```
is an exotic way of writing it like this:
```sql
SELECT   Sales - SomeCosts  AS Margin FROM current.sales
```
When seeing something like the above, one should always transpile to `AS` if you ask me - even for MS SQL. Nobody should use such a strange, proprietary syntax if every other dialect just supports `AS`.

The thing with the variable assignment is a bit different. It's syntactically the same, but you cannot meaningfully rewrite this with as. It should remain as it is

**Comment by mpf82** [comment]
> When seeing something like the above, one should always transpile to AS if you ask me

I disagree, as tobymao already said, it's a valid boolean expression.

Consider ``SELECT 0 = 1-1;`` vs ``SELECT 1-1 AS 0;``

**Comment by tobymao** [comment]
select 0 = 1 - 1 would be converted to select 0 = 1 - 1 AS _col

**Comment by aersam** [comment]
Well I understand you, but it's exactely what MS SQL does :) So I'll implement it in a transpiler

**Comment by aersam** [comment]
See also https://stackoverflow.com/questions/1503295/t-sql-aliasing-using-versus-as

**Comment by tobymao** [comment]
if there were no difference between variable assignment and the boolean to as, i would do it, but it’s not easy to distinguish between the two

**Comment by aersam** [comment]
Yeah, that's true. You would have to look for the @ which is a requirement for a variable in t-sql. Probably this allows them to use such strange things like that alias form

**Comment by aersam** [comment]
I really dislike that the syntax is valid in multiple dialects but means something different. These things make transpiling sql so hard - however this project is the best I've seen so far
