### ISSUE TITLE
Unable to use Dialect instances as a read/write arguments when transpiling

### ISSUE THREAD

**Issue by ibestvina** [tobymao/sqlglot#1082]
Although typing indicates that functions like `transpile` accept instances of `Dialect` as `read` and `write` arguments, it doesn't seem to work. I'd be happy to submit a merge request to fix this, but it seems like this issue goes deeper, with `Dialect.get_or_raise` actually being the root problem, as it seems to be used both to access a certain Dialect class, as well as generate Dialect objects. Defining typing for that method would probably highlight this issue well.

Since I need transpiling to work with my custom dialects, I'd be happy to work on this, but I don't want to mess something up before someone maintaining the package confirms that this is indeed an issue and that I'm on the right track.

p.s. awesome package!

**Comment by GeorgeSittas** [comment]
I can confirm that this is an issue. I'll post a fix soon, unless you want to play around with the project and submit a PR.

Thanks for the report! It's interesting that we haven't tested that properly yet.

**Comment by ibestvina** [comment]
Thank you, if it's a quick fix I would of course be happier if you do it, since I see there are a lot of places where this `get_or_raise` is used. But I will definitely be contributing to this project in the future, it fits my needs perfectly and I want to help with it :) Great work!

**Comment by GeorgeSittas** [comment]
Should be good now. Let me know if you encounter any other issues.
