### ISSUE TITLE
Unable to parse mysql8 create view 

### ISSUE THREAD

**Issue by Karl-Wu** [tobymao/sqlglot#1091]
I am working on column level lineage parser with sqlglot. Things were going well but trying to parse the following statement.

CREATE ALGORITHM=UNDEFINED DEFINER=`dbt`@`%` SQL SECURITY DEFINER VIEW `stg_payments` AS with `source` as (select `raw_payments`.`id` AS `id`,`raw_payments`.`order_id` AS `order_id`,`raw_payments`.`payment_method` AS `payment_method`,`raw_payments`.`amount` AS `amount` from `raw_payments`), `renamed` as (select `source`.`id` AS `payment_id`,`source`.`order_id` AS `order_id`,`source`.`payment_method` AS `payment_method`,(`source`.`amount` / 100) AS `amount` from `source`) select `renamed`.`payment_id` AS `payment_id`,`renamed`.`order_id` AS `order_id`,`renamed`.`payment_method` AS `payment_method`,`renamed`.`amount` AS `amount` from `renamed`

Above sql was generated by dbt and it is critical in our case.
https://dev.mysql.com/doc/refman/8.0/en/create-view.html

**Comment by tobymao** [comment]
i think we should leverage the properties that @treysp created here with a pre kind

**Comment by treysp** [comment]
Agreed - I'll add these as properties

**Comment by treysp** [comment]
will do!

**Comment by tobymao** [comment]
feel free to join our slack if you wanna chat at any time https://join.slack.com/t/tobiko-data/shared_invite/zt-1ma66d79v-a4dbf4DUpLAQJ8ptQrJygg

**Comment by GeorgeSittas** [comment]
Fixed in https://github.com/tobymao/sqlglot/commit/12bd655654d3264616b8e5e3c92e2ff23d6a070c
