### ISSUE TITLE
Unquoted postgres identifiers must not be keywords

### ISSUE THREAD

**Issue by jmo-qap** [tobymao/sqlglot#1109]
**quick summary and/or background**
Some syntaxes allow keywords as identifiers (e.g., sqlite) but Postgres (and perhaps others), do not. Parsing should fail when keywords are used as unquoted identifiers and transpilation should fail when the generated SQL is syntactically invalid.

**Steps to reproduce**
Transpile a valid `CREATE TABLE` statement from sqlite to postgres
```python
>>> import sqlglot
>>> sqlglot.transpile('CREATE TABLE foo (desc text);',read='sqlite', write='postgres')
['CREATE TABLE foo (desc TEXT)']
```
In postgres, however, that generated SQL is invalid:
```terminal
psql (14.6 (Homebrew))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_128_GCM_SHA256, bits: 128, compression: off)
Type "help" for help.
test=# CREATE TABLE foo (desc TEXT);
ERROR:  syntax error at or near "desc"
```
Arguably, parsing postgres sql should also fail
```python
>>> import sqlglot
>>> sqlglot.transpile('CREATE TABLE foo (desc text);',read='postgres', write='postgres')
['CREATE TABLE foo (desc TEXT)']
```
**What you expected would happen**
A parse error is raised (when source is Postgres) and/or a transpile error is raised (when source is sqlite)

**What actually happens**
Syntactically invalid Postgres SQL Syntax is parsed and is generated without error

**Notes** 
Suggested options:
- For target languages that don't allow unquoted identifiers be a keyword, error during translation
- Enforce on parse that unquoted identifier cannot be a keyword. Check that generated SQL parses correctly.
- Use [pglast](https://github.com/lelit/pglast) to verify postgres syntax is valid at parse and at transpile
- Quote identifier if it's a keyword, even if unquoted in source syntax.

**References** 
https://www.postgresql.org/docs/current/sql-keywords-appendix.html
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by tobymao** [comment]
sqlglot is not a validation engine. you should rely on the target engine to validate.

to avoid these kind of issues, you should use the keyword identify=True to force all column references to be quoted.

**Comment by jmo-qap** [comment]
Okay, sorry for the issue, I misunderstood this parser to catch syntax errors
