### ISSUE TITLE
percentile_cont (postgresql) -> approx_percentile (trino)

### ISSUE THREAD

**Issue by andrewhong5297** [tobymao/sqlglot#1111]
```
PERCENTILE_CONT(0.5) WITHIN GROUP (
    ORDER BY
    rolling_balance_final
) AS "50th_percentile_holdings"
```

from postgres should become this in trino

```
approx_percentile(rolling_balance_final, 0.5)
```

**Comment by tobymao** [comment]
duplicate https://github.com/tobymao/sqlglot/issues/996 

given that the semantics are different with the within group, i don't think the transpilation is as simple
