### ISSUE TITLE
Query parsing is successful even if the query is logically incorrect

### ISSUE THREAD

**Issue by harshith-bolar-rapido** [tobymao/sqlglot#1119]
Query:

```
SELECT *, group_name 
FROM table
where status='done'
group by group_name
```

The parsing for the above query passes even if there is no aggregate function in the SELECT statement.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/117074080/217500529-bee9383c-9734-49d1-8f76-af70db436b25.png">

**Comment by tobymao** [comment]
sqlglot is not a validator.
