### ISSUE TITLE
Databricks: Support for CREATE FUNCTION

### ISSUE THREAD

**Issue by pahunter90** [tobymao/sqlglot#1126]
Databricks uses the following syntax to define a function. This syntax is currently not supported in sqlglot:
[https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-create-sql-function.html](url)

```
CREATE [OR REPLACE] [TEMPORARY] FUNCTION [IF NOT EXISTS]
    function_name ( [ function_parameter [, ...] ] )
    RETURNS { data_type | TABLE ( column_spec [, ...])
    [ characteristic [...] ]
    RETURN { expression | query }

function_parameter
    parameter_name data_type [DEFAULT default_expression] [COMMENT parameter_comment]

column_spec
    column_name data_type [COMMENT column_comment]

characteristic
  { LANGUAGE SQL |
    [NOT] DETERMINISTIC |
    COMMENT function_comment |
    [CONTAINS SQL | READS SQL DATA] |
    SQL SECURITY DEFINER }
```

Functions can be attached to specific databases. Here is an example and the ParseError thrown:
![image](https://user-images.githubusercontent.com/32236862/217673618-e8fd4d41-2c3c-43d8-b6c6-b8535f6180aa.png)

**Comment by pahunter90** [comment]
Thank you for the solution to CREATE FUNCTION. One follow-up: while the statements now parse, when printed an "AS" is being inserted between RETURNS and RETURN, which is not allowed in Databricks (using `.sql(pretty=True, dialect='databricks')` to generate).
![image](https://user-images.githubusercontent.com/32236862/217878396-ad6c9eba-3ff3-4479-b97a-fb0d4a79cbb2.png)

**Comment by tobymao** [comment]
does it crash? what's the error

**Comment by pahunter90** [comment]
It does not crash in sqlglot, but putting the AS in Databricks does crash:
![image](https://user-images.githubusercontent.com/32236862/217886702-bad74aba-1926-407a-a1de-8a595e18b0b9.png)

**Comment by tobymao** [comment]
c0ebc869

**Comment by pahunter90** [comment]
That's awesome. Thank you.
