### ISSUE TITLE
snowflake: parsing SELECT IFF(TRUE, LEFT(REGEXP_REPLACE('target','pattern','\n'), 19), 'B') adds an extra backslash before \n

### ISSUE THREAD

**Issue by mvashishtha** [tobymao/sqlglot#1133]
I have a sql query with a fragment like `SELECT IFF(TRUE, LEFT(REGEXP_REPLACE('target','pattern','\n'), 19), 'B')`. I can run that fragment in snowflake. sqlglot adds an extra backslash before the `\n`. The extra backslash changes the semantics of my query. I only get the bug when read/write is `"snowflake"`.

```python
import sqlglot

original_query = "SELECT IFF(TRUE, LEFT(REGEXP_REPLACE('target','pattern','\\n'), 19), 'B')"
# default transpile gives SELECT IFF(TRUE, LEFT(REGEXP_REPLACE('target', 'pattern', '\n'), 19), 'B')
print(sqlglot.transpile(original_query)[0])
# snowflake transpile gives SELECT IFF(TRUE, LEFT(REGEXP_REPLACE('target', 'pattern', '\\n'), 19), 'B')
print(sqlglot.transpile(original_query, "snowflake")[0])
```

Versions: sqlglot 11.0.0, python 3.10.4

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/d2377e04eacdb1e9793d77629baa9c0a751fd50c
