### ISSUE TITLE
Databricks: Widget references not parsing with braces, and no WIDGET keyword support

### ISSUE THREAD

**Issue by pahunter90** [tobymao/sqlglot#1138]
Databricks allows the use of widgets, which are variables that can be passed between notebook jobs. They are referenced using a $ with or without braces. The following is an example of usage from the Databricks documentation:
[https://docs.databricks.com/notebooks/widgets.html#language-sql](url)

![image](https://user-images.githubusercontent.com/32236862/217921960-5ca8a58d-fee7-44a8-9850-7074caabf0a2.png)

Trying to parse this statement in sqlglot gives a ParseError:

![image](https://user-images.githubusercontent.com/32236862/217922115-77cba829-74d8-4001-93ee-f849bf2ea43e.png)

To be clear, without braces the $ works as intended:

![image](https://user-images.githubusercontent.com/32236862/217925244-2d35e7be-8781-454b-a980-2e5397a23ec0.png)

Furthermore, the WIDGET keyword is not listed. I have gotten around this by extending the Spark tokenizer class with specific widget commands. I can continue to do this, but support for the WIDGET keyword would help.

![image](https://user-images.githubusercontent.com/32236862/217922643-a87cc628-23fd-4051-b262-72076cea0ac8.png)

**Comment by tobymao** [comment]
are these preprocessing or actual sql tokens?

can you use these for any token? like ${SELECT} * FROM ...

**Comment by tobymao** [comment]
sqlglot will not support this because this is a macro prepocessor. 

if you want i can just support ${} as a stand-alone unit. but doing string replacement is out of scope and impossible to parse into an ast

**Comment by pahunter90** [comment]
Understood. It would be helpful if ${} parsed the same way as $,
