### ISSUE TITLE
snowflake: transpiling "COPY INTO" raises ParseError

### ISSUE THREAD

**Issue by mvashishtha** [tobymao/sqlglot#1141]
In snowflake I can do `COPY INTO NEW_TABLE ( "foo", "bar")  FROM ( SELECT $1, $2, $3, $4 FROM @%old_table)`.  In sqlglot I get `ParseError`:

```python
import sqlglot

print(sqlglot.transpile('COPY INTO NEW_TABLE ( "foo", "bar")  FROM ( SELECT $1, $2, $3, $4 FROM @%old_table)', 'snowflake'))
```

I'm on sqlglot 11.0.0, python 3.10.4.

**Comment by GeorgeSittas** [comment]
I can take a look at this soon.
