### ISSUE TITLE
Aws Redshift Datepart names for datetime functions are not recognized in qualify_columns optimization

### ISSUE THREAD

**Issue by saadhashmi91** [tobymao/sqlglot#1148]
This is to inform that valid **[datepart](https://docs.aws.amazon.com/redshift/latest/dg/r_Dateparts_for_datetime_functions.html)** abbreviations and names for AWS Redshift datetime functions are considered ambiguous columns in the qualify_columns optimization step. For example the [function](https://docs.aws.amazon.com/redshift/latest/dg/r_DATEDIFF_function.html) `DATEDIFF(d, CAST(... AS DATE))` returns the following runtime error: _`Ambiguous column: d`_

![image](https://user-images.githubusercontent.com/9041491/218141502-a31ee667-d5f2-4a79-8a15-360ad8f3b8b9.png)

**Comment by barakalon** [comment]
_Note for core team:_
This is a parser issue - "d" should be parsed as a Var, not a Column

**Comment by saadhashmi91** [comment]
Thanks, can it be replicated for [DATEADD](https://docs.aws.amazon.com/redshift/latest/dg/r_DATEADD_function.html), [DATE_PART](https://docs.aws.amazon.com/redshift/latest/dg/r_DATE_PART_function.html) and [EXTRACT](https://docs.aws.amazon.com/redshift/latest/dg/r_EXTRACT_function.html) functions aswell?
