### ISSUE TITLE
ROW_NUMBER Function is caught having no table in validate_qualify_columns method of qualify_columns

### ISSUE THREAD

**Issue by saadhashmi91** [tobymao/sqlglot#1153]
The ROW_NUMBER function is not validated in the validate_qualify_columns method during the qualify_columns optimization step. The error message: _**Unknown Table**_

![image](https://user-images.githubusercontent.com/9041491/218332096-55d4ff7e-3b36-4c8d-9f6c-d6b18cfca483.png)
![image](https://user-images.githubusercontent.com/9041491/218332299-970f1a22-1583-4777-8fb7-442b0519a262.png)

**Comment by barakalon** [comment]
Can you post some code that reproduces the error?

**Comment by saadhashmi91** [comment]
Sure,
The following is a valid Aws Redshift SQL. The ROW_NUMBER function has the default column name as ROW_NUMBER in output.

```import sqlglot as gt
from sqlglot.optimizer.optimizer import optimize

test_schema = {'ods': {'interim_ref_missing_info': {'missing_info_id': 'double precision', 'lh_patient_id': 'character varying(255)', 'patient_record_id': 'character varying(255)', 'program_name': 'character varying(255)', 'max_rec': 'date', 'min_miss': 'date', 'diff': 'bigint', 'product_name': 'character varying(255)', 'missing_info_cd': 'character varying(255)', 'missing_info': 'character varying(255)', 'date_missing': 'date', 'date_received': 'date', 'new_date_received': 'date', 'diffdt': 'bigint'}}}
T6 = """SELECT  *  FROM  (
                                SELECT
                                  (new_date_received) MIN_MISS_DT,
                                  interim_ref_missing_info.lh_patient_id,
                                  interim_ref_missing_info.DATE_MISSING,
                                  ROW_NUMBER () OVER (
                                    PARTITION BY interim_ref_missing_info.LH_PATIENT_ID
                                    ORDER BY
                                      new_date_received DESC
                                  )
                                FROM
                                  ODS.interim_ref_missing_info )
                            WHERE
                              ROW_NUMBER = 1"""

parsed = gt.parse(T6,read='redshift')
optimized = optimize(parsed[0],schema = test_schema)
```

**Comment by barakalon** [comment]
This has to do with the output column names that an engine chooses when there is no alias.

It seems like Redshift chooses the name `ROW_NUMBER` for 
```
ROW_NUMBER () OVER (
  PARTITION BY interim_ref_missing_info.LH_PATIENT_ID
  ORDER BY
    new_date_received DESC
)
```

AFAIK, there is no standard behavior for this. So I don't think we should handle this within the optimizer, which is dialect agnostic.

If you have control over the generation of these queries, I'd add an alias:
```
ROW_NUMBER () OVER (
  PARTITION BY interim_ref_missing_info.LH_PATIENT_ID
  ORDER BY
    new_date_received DESC
) AS ROW_NUMBER
```

That's more standard.

If that's not an option, you can write a transformer that determines Redshift's output column names and wraps these expressions with an alias.

I think it'd make sense to add such a transformer to Redshift's parser. Or you can add it as a rule when calling `optimize`. Or you can just call it before calling `optimizer`.

Closing this issue as "won't fix" for now. But I'm happy to keep chatting about solutions.

**Comment by saadhashmi91** [comment]
Is the following the right way? Its giving an error
![image](https://user-images.githubusercontent.com/9041491/218337247-22c7ff7c-29b5-47b8-9360-0bdebad78eef.png)

![image](https://user-images.githubusercontent.com/9041491/218337291-2a00dc09-dff0-450f-86f7-908e27de61c8.png)

**Comment by barakalon** [comment]
No.

First - do you know what the rules are for picking output column names? Is this only relevant for ROW_NUMBER?

**Comment by saadhashmi91** [comment]
Yes, its only for ROW_NUMBER

**Comment by tobymao** [comment]
it's best practice to explicitly alias your columns. defaults are engine specific

**Comment by barakalon** [comment]
The transform should look something like this:

```python
def alias_row_number(expression: exp.Expression) -> exp.Expression:
    if (
        isinstance(expression, exp.Window)
        and isinstance(expression.this, exp.RowNumber) 
        and isinstance(expression.parent, exp.Select)
        and expression.arg_key == "expressions"
    ):
        return exp.alias(window.copy(), window.this.name)

ast = parse_one("SELECT ...")
ast = ast.transform(alias_row_number)
```
_i haven't tested this_

I confused generator transforms with parser transforms, which don't exist. So I don't think this can be added to the parser easily.

But you just call that function before calling `optimize`?

You can also add it as a "rule":

```python
def alias_row_number_rule(expression: exp.Expression) -> exp.Expression:
    return expression.transform(alias_row_number, copy=False)

from sqlglot.optimizer import optimize, RULES

CUSTOM_RULES = (alias_row_number_rule,) + RULES

optimize(ast, rules=CUSTOM_RULES)
```

**Comment by saadhashmi91** [comment]
Thanks alot,
Actually my use-case is building a column-lineage of our client's data warehouse across multiple redshift schemas. Thanks for the timely help.
