### ISSUE TITLE
More About Presto Group by 

### ISSUE THREAD

**Issue by ruichengnew** [tobymao/sqlglot#1166]
In #1079 , we have solved the order problem about four types. 

However, in Presto, there can be multiple keywords like `group by rollup(field_a), rollup(field_b), rollup(field_c)`, which is equivalent to `rollup(field_a, field_b, field_c)`. So it is still a problem.

```python
sqlglot.parse_one(
"""
select a
from t
group by a, rollup(b), rollup(c), rollup(d)
"""
)
```

**Comment by GeorgeSittas** [comment]
@ruichengnew you can take a look at my PR if you want. I made it so that `rollup(b), rollup(c), rollup(d)` always transpiles to `rollup(b, c, d)`, based on what you said. If you spot something weird in the tests I updated please let me know and I'll fix them.

**Comment by ruichengnew** [comment]
Thanks for fixing so fast.  Hah, what I hacked in my code is definitely same as the PR. 

I will continually work on Presto for a while, so whatever wield I find , I will post here.

**Comment by GeorgeSittas** [comment]
Cool, feel free to open a PR.
