### ISSUE TITLE
Optimize Trick about expand group by column 

### ISSUE THREAD

**Issue by ruichengnew** [tobymao/sqlglot#1167]
```python
optimize(
    sqlglot.parse_one(
        """
select tbl.*, count(1)
from tbl
group by 1, 2, 3
"""
    ),
    schema={"tbl": {"a": "str", "b": "str", "c": "str"}},
).sql()
```

In the example, we have table `tbl`'s schema, so we can expand the Star, and then expand the `1, 2, 3` column. But sqlglot give an error about this.

**Comment by barakalon** [comment]
That's a bonkers thing to do lol

But here: https://github.com/tobymao/sqlglot/pull/1169
