### ISSUE TITLE
AST representation of column expression does not contain column name for schema.table.column

### ISSUE THREAD

**Issue by paulgrow-octane** [tobymao/sqlglot#1172]
Let me start by thanking you for creating such a wonderful tool and library-- it's been a pleasure to use thus far!

## Summary

For the given the query:

```sql
-- tmp.sql
SELECT
  schema1.table1.column1
FROM schema1.table1
```

The AST representation is:

```
(SELECT expressions:
  (DOT this:
    (COLUMN this:
      (IDENTIFIER this: table1, quoted: False), table:
      (IDENTIFIER this: schema1, quoted: False)), expression:
    (IDENTIFIER this: column1, quoted: False)), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: table1, quoted: False), db:
      (IDENTIFIER this: schema1, quoted: False))))
```

I expected the Column expression to contain the table and column names, i.e.:

```
(COLUMN this:
      (IDENTIFIER this: column1, quoted: False), table:
      (IDENTIFIER this: table1, quoted: False))
```

Is this the expected behavior? Note that this was tested against `sqlglot v11.1.1`.

## Related Work

I did do a bit of searching to see if this had come up previously but perhaps I didn't use the right keyword. What I found is below:

*  https://github.com/tobymao/sqlglot/pull/664

**Comment by barakalon** [comment]
Have you tried that query on an a particular engine? I don't think it's valid.

Closing for now. Will reopen if this is valid syntax somewhere.

**Comment by paulgrow-octane** [comment]
>I don't think it's valid

Just tested in Postgres, Athena, and Redshift. Works for all three.
