### ISSUE TITLE
`REGEXP_EXTRACT` bigquery function does not extract matching group in duckdb

### ISSUE THREAD

**Issue by nsfinkelstein** [tobymao/sqlglot#1182]
Instead, the function extracts a pattern that matches the full regex.

To reproduce:

```py
import duckdb
import sqlglot
import pandas as pd

df = pd.DataFrame({'col': ['10', '11', '12', '13', '14', '15']})
original = "select regexp_extract(col, '1(\d)') as extracted from df"
transpiled = sqlglot.transpile(original, read='bigquery', write='duckdb')[0]
duckdb.connect().execute(transpiled).df()
#   extracted
# 0        10
# 1        11
# 2        12
# 3        13
# 4        14
# 5        15
```

The result should instead be:

```py
#   extracted
# 0        0
# 1        1
# 2        2
# 3        3
# 4        4
# 5        5
```

**Comment by tobymao** [comment]
@nsfinkelstein is the behavior of bigquery that it returns the first match group? seems like duckdb needs to add the index 1

**Comment by nsfinkelstein** [comment]
Thanks for the quick response. Yes, the default behavior is that bigquery returns the first match group (at least when there is only one match group, I haven't verified for when there is more than one). This is also reflected in the second example in their docs (https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_extract).

**Comment by tobymao** [comment]
how would you translate bigquery regexp_extract into duckdb? i need help on this

**Comment by tobymao** [comment]
yes, but that's not correct, you should only do this if the regex has a match group.

**Comment by tobymao** [comment]
i don't think this is possible to do correctly. bigquery returns an error if there is more than one capture group, so it doesn't support match groups as duckdb does.

i'm going to close this for now as not planned. this is something that you can build a custom transform for. basically, you take your bigquery regexp, and then adding an arg of 1 to it before generating duckdb.

**Comment by nsfinkelstein** [comment]
I would think it is possible to do correctly in the direction of transpiling bigquery to duckdb, because as you say duckdb allows more general matches. I suspect this is by far the more common direction of transpilation, as people use duckdb to unit test production systems (which is my use case as well).

It's not possible in the other direction only if the regex in duckdb SQL has more than one match group. In this case I'd expect sqlglot to raise an error.

If you point me in the right direction, I can put in a pull request to address both these points.

**Comment by tobymao** [comment]
@nsfinkelstein 

1. Create a new class
```python
RegexpExtract(Func):
    arg_types = {"this": True, "expression": True, position: False, occurrence: False, group: False}
```
4. In BigQuery, create a custom Function Parser that calculates the number of groups

```python
re.compile(regex).groups
```

if groups == 1, set group in RegexpExtract to be 1.

5. In Duckdb, in the generation of RegexpExtract, add unsupported errors if position or occurrence is set.

add unit tests

**Comment by tobymao** [comment]
since you’re looking to make a pr. i’ll reopen this
