### ISSUE TITLE
Quoting support in DataFrame 

### ISSUE THREAD

**Issue by kgdiem** [tobymao/sqlglot#1188]
SQLGlot’s DataFrame API doesn’t seem support quoting entity names. This might be an oversight as the option is available through the expressions API. 

Given the following code, the `optimizer` will lowercase the table name:

```
import sqlglot
from sqlglot.dataframe.sql.functions import col
from sqlglot.dataframe.sql.session import SparkSession

sqlglot.schema.add_table('TEST', dict(
  name='VARCHAR'
))

df = SparkSession().table('TEST').select(col('name'))

print(df.sql(dialect='snowflake', optimize=True)[0])
print(df.sql(dialect='snowflake', optimize=False)[0])
```

```
SELECT "test"."name" AS "name" FROM "test" AS "test"
WITH t21533 AS (SELECT TEST.name AS name FROM TEST) SELECT t21533.name AS name FROM t21533
```

This behavior isn't necessarily problematic in and of itself but it can wind up being in conflict with Snowflake's [identifier syntax](https://docs.snowflake.com/en/sql-reference/identifiers-syntax) when a double-quoted identifier is used: 
> If an object is created using a double-quoted identifier, when referenced in a query or any other SQL statement, the identifier must be specified exactly as created, including the double quotes. Failure to include the quotes might result in an Object does not exist error (or similar type of error). 

Under the current conditions, `camelCase` or `CapitalCase`'d table name would also run afoul in Snowflake, Postgres, etc.

Columns encounter the same issue, `sqlglot.dataframe.sql.functions.col` doesn't accept `quoted` as a `kwarg`. However, `col` accepts an `Expression` as an argument so I believe this can be worked around by using `sqlglot.expressions.Column` as an argument to `col` to construct a `sqlglot.dataframe.sql.Column`

The issue with the table is a bit more tricky though as `SparkSession.table` and `DataFrameReader.table` only accept a `str` as an argument without any way to signify the table name's casing / quoting is preserved.

There is no way to provide `sqlglot.dataframe.sql.DataFrame` with any custom `Optimizer` rules to omit the `lower_identities` rule. 

Given the goal of Spark compatibility would it be possible to add an option for quoted when constructing a table or to the `col` helper? 

In researching this issue I discovered I could likely extend `SparkSession` and `DataFrameReader` to fulfill my needs but thought I'd check about first party support first.

**Comment by tobymao** [comment]
you can force quote your tables and thus preserve the casing by passing a quoted string into table

```


df = SparkSession().table('"TEST"').select(col('name'))
```

**Comment by tobymao** [comment]
i believe this should solve your issue, but if it doesn't let us know and we can chat more about what you need

**Comment by kgdiem** [comment]
The following will produce invalid output for both optimized and unoptimized SQL:

```
    import sqlglot
    from sqlglot.dataframe.sql.functions import col
    from sqlglot.dataframe.sql.session import SparkSession

    sqlglot.schema.add_table('TEST', dict(
        name='VARCHAR'
    ))

    df = SparkSession()\
        .table('"TEST"')\
        .select(col('name'))\
        .filter(col('name').__eq__(1))

    print(df.sql(dialect='snowflake', optimize=True)[0])
    print(df.sql(dialect='snowflake', optimize=False)[0])
```
outputs:
```
SELECT "rd4635a08de7e49cfb0c26f21e2fe3d2e"."name" AS "name" FROM "TEST" AS "TEST" WHERE "rd4635a08de7e49cfb0c26f21e2fe3d2e"."name" = 1

WITH t11996 AS (SELECT FROM "TEST"), t94950 AS (SELECT t11996.name AS name FROM t11996) SELECT name FROM t94950 WHERE name = 1
```

so it seems like there is a cache miss somewhere, likely from `DataFrameReader.table` calling `.add_table()`;

The following throws on optimize but prints seemingly correct unoptimized SQL so I flipped the `print` statements:
```
    import sqlglot
    from sqlglot.dataframe.sql.functions import col
    from sqlglot.dataframe.sql.session import SparkSession

    sqlglot.schema.add_table('"TEST"', dict(
        name='VARCHAR'
    ))

    df = SparkSession()\
        .table('"TEST"')\
        .select(col('name'))\
        .filter(col('name').__eq__(1))

    print(df.sql(dialect='snowflake', optimize=False)[0])
    print(df.sql(dialect='snowflake', optimize=True)[0])
```

unoptimized output:
```
WITH t52626 AS (SELECT TEST.name AS name FROM "TEST"), t17392 AS (SELECT t52626.name AS name FROM t52626) SELECT name FROM t17392 WHERE name = 1
```

error message: 
```
---------------------------------------------------------------------------
OptimizeError                             Traceback (most recent call last)
<ipython-input-2-d80d777bd86d> in <module>
     13 
     14 print(df.sql(dialect='snowflake', optimize=False)[0])
---> 15 print(df.sql(dialect='snowflake', optimize=True)[0])

/usr/local/lib/python3.7/site-packages/sqlglot/dataframe/sql/dataframe.py in sql(self, dialect, optimize, **kwargs)
    301             select_expression = select_expression.transform(replace_id_value, replacement_mapping)
    302             if optimize:
--> 303                 select_expression = optimize_func(select_expression)
    304             select_expression = df._replace_cte_names_with_hashes(select_expression)
    305             expression: t.Union[exp.Select, exp.Cache, exp.Drop]

/usr/local/lib/python3.7/site-packages/sqlglot/optimizer/optimizer.py in optimize(expression, schema, db, catalog, rules, **kwargs)
     73             param: possible_kwargs[param] for param in rule_params if param in possible_kwargs
     74         }
---> 75         expression = rule(expression, **rule_kwargs)
     76     return expression

/usr/local/lib/python3.7/site-packages/sqlglot/optimizer/qualify_columns.py in validate_qualify_columns(expression)
     48             unqualified_columns.extend(scope.unqualified_columns)
     49             if scope.external_columns and not scope.is_correlated_subquery:
---> 50                 raise OptimizeError(f"Unknown table: {scope.external_columns[0].table}")
     51 
     52     if unqualified_columns:

OptimizeError: Unknown table: test
```

**Comment by kgdiem** [comment]
btw I am open to adding a solution myself with some guidance; I can either research Spark's handling of this case or just add  support via kwargs to only `SparkSession` / `DataFrameReader` or those classes and `sqlglot.dataframe.sql.Column`

**Comment by tobymao** [comment]
i think spark is not case sensitive, i'm happy to guide you through this, but it may be a bit tough. can you join the slack as there is going to be a lot of back and forth.
