### ISSUE TITLE
Bug in SQLglot's schema mapping

### ISSUE THREAD

**Issue by ericzhou571** [tobymao/sqlglot#1192]
The mapping in sqlglot's schema is lower cased.  However **[optimize](https://github.com/tobymao/sqlglot/blob/294a4cb89761ed8016bc794acdeb1f70fc3933b3/sqlglot/optimizer/optimizer.py)** or  **[qualify_columns](https://github.com/tobymao/sqlglot/blob/294a4cb89761ed8016bc794acdeb1f70fc3933b3/sqlglot/optimizer/qualify_columns.py)**
seem to not aware of this point.

The latest master branch 294a4cb is affected by this issue

For instance, without pre-lower casing the whole SQL, certain functions in qualify_columns may fail. For example, the function to expand a star with the help of schema will not work correctly.

The mapping in the schema module of sqlLGlot will be lower-cased, as shown in this code block:

https://github.com/tobymao/sqlglot/blob/294a4cb89761ed8016bc794acdeb1f70fc3933b3/sqlglot/schema.py#L233-L244

Meanwhile, this block of code will return the original table directly from SQL, without performing any further case operations:

https://github.com/tobymao/sqlglot/blob/294a4cb89761ed8016bc794acdeb1f70fc3933b3/sqlglot/optimizer/scope.py#L276-L300

However, there are no obvious cases where the entire SQL statement is lower-cased in these two blocks of code:

https://github.com/tobymao/sqlglot/blob/294a4cb89761ed8016bc794acdeb1f70fc3933b3/sqlglot/optimizer/qualify_columns.py#L10-L40

https://github.com/tobymao/sqlglot/blob/294a4cb89761ed8016bc794acdeb1f70fc3933b3/sqlglot/optimizer/optimizer.py#L83

Without pre-lower-casing the entire SQL statement, this can lead to some functions failing in the qualify_columns module, such as expanding the star with the help of schema.

The latest master branch 294a4cb is affected by this issue. Here is an example:

To illustrate this issue, consider the following example:

```
from sqlglot import Schema, exp

test_sql = """    
select
    *
    from(
        select * , sncode+creationtime as ranktime from allData
    ) a
    where a.ranktime = 1 """
    
expression = exp.maybe_parse(test_sql, dialect='spark', copy=True)
expression = qualify_columns(expression, schema)
print(expression)
```
When the test_sql is parsed with SQLglot, the output of the above code is:

> SELECT * FROM (SELECT *, allData.sncode + allData.creationtime AS ranktime FROM allData) AS a WHERE a.ranktime = 1

However, if the test_sql is lower-cased before parsing, the output of the same code is:
```
test_sql = test_sql.lower()
expression = exp.maybe_parse(test_sql, dialect='spark', copy=True)
expression = qualify_columns(expression, schema)
print(expression)
```

> SELECT a.sncode AS sncode, a.creationtime AS creationtime, a.hello AS hello, a.ranktime AS ranktime FROM (SELECT alldata.sncode AS sncode, alldata.creationtime AS creationtime, alldata.hello AS hello, alldata.sncode + alldata.creationtime AS ranktime FROM alldata) AS a WHERE a.ranktime = 1

This is because, when a function is run on a lower-cased SQL, the mapping is not performed correctly, leading to incorrect results.

To fix this issue, we suggest to apply a force lower case inside function **[optimize](https://github.com/tobymao/sqlglot/blob/294a4cb89761ed8016bc794acdeb1f70fc3933b3/sqlglot/optimizer/optimizer.py)** or inside **[qualify_columns](https://github.com/tobymao/sqlglot/blob/294a4cb89761ed8016bc794acdeb1f70fc3933b3/sqlglot/optimizer/qualify_columns.py)**
**But I do not check other functions, I'm not sure if we will cause any other butterfly effect to other functions**

Here is suppliments

**Comment by tobymao** [comment]
you cannot run optimizer steps in isolation unless you know what you're doing.

qualify_columns depends on lower_identities and qualify_tables. lower_identities is what you're looking for.

**Comment by ericzhou571** [comment]
> you cannot run optimizer steps in isolation unless you know what you're doing.
> 
> qualify_columns depends on lower_identities and qualify_tables. lower_identities is what you're looking for.

Thanks for quick reply!

I'm looking for **expand star in a sql** query such as (select * from (select a.* , xxx from a left join b)). 
I only find out that there is a hidden fucntion _expand_star in qualiy_columns. 

It would be nice if you give me more suggestion, which function or functions I should use?

**Comment by tobymao** [comment]
at a minimum you need 

optimize(..., rules=(lower_identities, qualify_tables, qualify_columns)

you may also want expand_laterals and pushdown_projections
