### ISSUE TITLE
TS_OR_DS_TO_DATE function in transpiled sql

### ISSUE THREAD

**Issue by AdeelK93** [tobymao/sqlglot#1195]
Hi! This repo is great, very easy to use. Seeing some weird date function behavior with bigquery - here's an example:

```py
import sqlglot

sql = "SELECT to_date(my_timestamp_column) <= current_date()"
bq_sql = sqlglot.transpile(sql, read="spark", write="bigquery")[0]
print(bq_sql)
```
which returns: `SELECT TS_OR_DS_TO_DATE(my_timestamp_column) <= CURRENT_DATE`

this `TS_OR_DS_TO_DATE` is not a valid function, and I can't find where in the code it's coming from.
if i write to duckdb instead, now i get valid sql: `SELECT CAST(my_timestamp_column AS DATE) <= CURRENT_DATE`

thank you!

**Comment by tobymao** [comment]
spark's to_date function is weird because it it works on strings and dates, and so it becomes the internal TS_OR_DS_TO_DATE, the bigquery generator of this does not exist yet

**Comment by AdeelK93** [comment]
Ah okay - perhaps there could be a warning about the generator not existing? Thanks!
