### ISSUE TITLE
Snowflake udf fails when the imput contains arrays

### ISSUE THREAD

**Issue by shiramax** [tobymao/sqlglot#1201]
Hi there,

We are building an internal udf which currently fails the sqlglot parser.

sqlglot.__version__
>> '10.6.4'

Given the following query (where xxx is a udf and expected to be parsed as an anonymous function)

from sqlglot import parse_one

query = """
SELECT *
FROM X
WHERE  xxx(['a', ['b', 'c', 'd']])
"""

parse_one(query) wraps the Array in Array()

parse_one(query).sql(): 
"SELECT * FROM X WHERE XXX(ARRAY('a', ARRAY('b', 'c', 'd')))"

Which makes the udf not work since the udf is not expecting the ARRAY()

I know there is a workaround, I can use parse_json in my query, but I prefer not to do it, since it makes my query longer.

Thanks in advanced!

**Comment by tobymao** [comment]
is there a difference between array and []?

**Comment by shaiv-syg** [comment]
When using snowflake js udf this makes a difference:

For example
Given the following UDF
```
CREATE OR REPLACE FUNCTION TEST_OVERLOAD("arr" ARRAY)
RETURNS BOOLEAN
LANGUAGE JAVASCRIPT
AS '
    return arr.length === 3
';
```

```
SELECT TEST_OVERLOAD(['a', 'b', 'c']);
```
>> `True`
```
SELECT TEST_OVERLOAD(ARRAY('a', 'b'));
```
>> `Unknown function ARRAY`

**Comment by shaiv-syg** [comment]
On a second thought I think the function `Array` is unsupported altogether in Snowflake

**Comment by tobymao** [comment]
this is working as expected, you need to specify dialect="snowflake" in sql. this is because by default sqlglot uses the sqlglot dialect

**Comment by shaiv-syg** [comment]
@tobymao I think it's worth to add a comment in the README under the section of Build and modify SQL to clarify that once you parse a specific dialect you should run sql with the same dialect flag.
I'll be happy to open a pr if you want :)
