### ISSUE TITLE
Dialect not exported explicitly

### ISSUE THREAD

**Issue by dmoklaf** [tobymao/sqlglot#1203]
Using `sqlglot.Dialect.get_or_raise("sqlite")` with the current version (sqlglot 11.2.0) raises the following error in the mypy linter:
`attr-defined "Module sqlglot" does not explicitly export attribute "Dialect"`

To fix this, sqlglot shall declare reexported classes in a `__all__` field in its `__init__.py` file.

**Comment by GeorgeSittas** [comment]
I can't reproduce what this issue locally:

```
➜ cat test.py
import sqlglot
sqlglot.Dialect.get_or_raise("sqlite")
➜ mypy test.py
Success: no issues found in 1 source file
```

Is this what you meant? I have SQLGlot v11.2.0 and mypy v.1.0.0 in the above example.

**Comment by dmoklaf** [comment]
Thx, it seems to come from the strict mode of mypy:

```
% mypy test.py
Success: no issues found in 1 source file

% mypy --strict test.py
test.py:2: error: "Module sqlglot" does not explicitly export attribute "Dialect"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by GeorgeSittas** [comment]
I see... I don't have an opinion on this either, let's wait for @tobymao's response.

**Comment by GeorgeSittas** [comment]
Checks activated with `--strict` for future reference: https://emplocity.com/en/about-us/blog/mypy_not_enough/.

**Comment by tobymao** [comment]
sure

**Comment by GeorgeSittas** [comment]
@dmoklaf I'll try to resolve the dialect issue in `__init__.py`, because making SQLGlot work with `--strict` is going to take more time and it's not a high priority issue.

**Comment by barakalon** [comment]
`from sqlglot.dialects.dialect import Dialect` ?

**Comment by GeorgeSittas** [comment]
This doesn't seem to work for me..? On the other hand, if I do `__all__ = ["Dialect"]` inside `__init__.py` it does work, but that approach would require including all exported names in this list, which isn't great..

**Comment by tobymao** [comment]
isn't that the point of this mypy check?

**Comment by barakalon** [comment]
Not for you - for @dmoklaf 

sqlglot doesn't promise that Dialect is part of the main module.

See the readme: https://github.com/tobymao/sqlglot#custom-dialects

**Comment by GeorgeSittas** [comment]
I'm a bit confused. So what I meant is that with this script:

```python
# test.py
import sqlglot
sqlglot.Dialect.get_or_raise("sqlite")
```

Running `mypy test.py --strict` resulted in `error: Module sqlglot does not explicitly export attribute Dialect [attr-defined]`. Even after making the change Barak suggested, I `pip install -e .` and still didn't work.

The fix I just tried and actually got mypy to stop yelling is:

```python
from sqlglot.dialects.dialect import Dialect as Dialect
```

**Comment by GeorgeSittas** [comment]
Ah, I think see what you meant @barakalon. However, I think the intent is for us to export most of these helper functions in `__init__.py`, since they're not even used in that file.
