### ISSUE TITLE
The order of “NOT IN“ is not preserved after "parse_one" and "sql" function.

### ISSUE THREAD

**Issue by CBQu** [tobymao/sqlglot#1209]
The code example is as follows:
```
test_tree = parse_one('''SELECT * FROM tbl_a WHERE col_a NOT IN (SELECT col_a FROM tbl_b);''')
test_tree.sql()
```
Output:
`'SELECT * FROM tbl_a WHERE NOT col_a IN (SELECT col_a FROM tbl_b)'`

Output expected:
`'SELECT * FROM tbl_a WHERE col_a NOT IN (SELECT col_a FROM tbl_b)'`

I am using the latest version (10.6.4) of sqlglot.

**Comment by tobymao** [comment]
10.6.4 is not the latest version, but this is expected behavior. 

sqlglot chooses to do this because it's a more "consistent" form of representing booleans

**Comment by GeorgeSittas** [comment]
https://github.com/tobymao/sqlglot/discussions/274

**Comment by CBQu** [comment]
Got it. Thanks.
