### ISSUE TITLE
Extending Support For Qlik Scripting

### ISSUE THREAD

**Issue by tim-wright** [tobymao/sqlglot#1215]
@tobymao , first off this package looks amazing - thank you and everyone else for the hard work on it. I am in the process of migrating some logic out of Qlik (BI tool) and trying to port it to SQL (dialect unclear/unimportant atm). The backend logic for Qlik is "Qlik Scripting" - which in some ways looks like SQL, but has some other custom functionality and a fair amount of procedural logic. 

I appologize for the naive question, but do you think it's possible to extend this library to support that language (not asking you or anyone else to do it, trying to understand the feasibility of trying to contribute that piece)? It is not a SQL dialect so I'm not sure I could ever expect 1:1 parity with your transpiler but am thinking it might be able to provide _some_ support to help automate parts of the logic conversion. Based on your knowledge of the package - does this seem like a feasible option? Would love to leverage/build upon your work if I can. Thanks.

**Comment by tobymao** [comment]
If QLIK can be expressed as SQL, then it would be possible to use the SQLGlot infrastructure.

For example SQLGlot implements the PySpark API, meaning you can write pyspark code and it translates into SQL. I don't know enough about Qlik to tell you more than that.

Happy to chat more in this thread or on Slack.
