### ISSUE TITLE
SET commands not decomposed

### ISSUE THREAD

**Issue by joocer** [tobymao/sqlglot#1225]
Parsing a `SET` command such as 

~~~sql
SET @q = 4;
~~~

results in this:
_(note, the equals expression is just presented as a string literal)_

~~~
(COMMAND this: SET, expression: 
  (LITERAL this: @q = 4, is_string: True))
~~~

I had expected the statement to be decomposed into something like this:
_(note, the identifier and literal are different nodes in the tree)_
~~~
(COMMAND this: SET, expression: 
  ((IDENTIFIER this: @q, quoted: False)
  (LITERAL this: 4, is_string: False)))
~~~

**Comment by tobymao** [comment]
many command in SQL haven't been high priority and so are parsed in the catchall "command" node.

basic parsing of set should be easy with just doing parse_conjunction(), but i'm not sure how SET is used in all dialects.

**Comment by joocer** [comment]
Thanks @tobymao,

Looking at another non-SELECT example
~~~sql
SHOW FULL COLUMNS FROM $astronauts"
~~~

I get a similar, COMMAND node with the first keyword and then the rest of the statement as a single literal. I'm guessing from the name only that `parse_conjuction()` is extracting predicate expressions (which `@q = 4` looks like) but won't parse `SHOW` statements?

**Comment by tobymao** [comment]
show is an entirely different command with it's own syntax

**Comment by tobymao** [comment]
1. remove TokenType.SET from Tokenizer.COMMANDS
2. add it to Parser.STATEMENT_PARSERS
3. parser func create parse_set
4. create a SetStatement node in expression.py
5. return a self.expression(exp.SetStatement, this=self._parse_conjunction())
6. write unit tests

please do some research on various major dialects to see what is possible

spark, snowflake, bigquery, mysql, postgres

have an understanding of what needs to be supported in the SET command, this will dictate what step 5 actually does.

**Comment by joocer** [comment]
Initial reconnaissance of documentation:

[spark](https://spark.apache.org/docs/latest/sql-ref-syntax-aux-conf-mgmt-set.html)
[snowflake](https://docs.snowflake.com/en/sql-reference/sql/set)
[bigquery](https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#set)
[MySQL](https://dev.mysql.com/doc/refman/8.0/en/set-statement.html)
[postgres](https://www.postgresql.org/docs/current/sql-set.html)
[trino](https://trino.io/docs/current/sql.html)

Initial Observations:
- Spark supports `SET;` as a valid command which returns all values
- BigQuery appears to require a `DECLARE` statement creating the variable before it can be set
- Snowflake and BigQuery appear to support multiple variable assignments in one statement
- Postgres appears to have the most modifiers in its syntax
- Trino only accepts `SET` in combination with one of a small set of following keywords
- DuckDB appears to have no `SET` command

**Comment by joocer** [comment]
Identified variations

**Spark**
~~~
SET variable = value;
SET -v;
SET;
SET variable;
~~~

**Snowflake**
~~~
SET variable = value;
SET ( variable [, variable ... ]) = ( value [, value ... ]);
~~~

**BigQuery**
~~~
SET variable = value;
SET ( variable [, variable ... ]) = ( value [, value ... ]);
~~~

**MySQL**
~~~
SET [[@@]GLOBAL|[@@]SESSION|[@@]PERSIST|[@@]PERSIST_ONLY] variable = value;
SET [@@]variable = value;
SET [[@@]GLOBAL|[@@]SESSION|[@@]PERSIST|[@@]PERSIST_ONLY].variable = value;
SET <CHARACTER SET | CHARSET> <name | DEFAULT>;
SET NAMES <charset_name> < COLLATE 'collation_name' | DEFAULT >;
SET DEFAULT ROLE <NONE | ALL | role [, role ... ]> TO user [, user ...];
SET ROLE <DEFAULT | NONE | ALL | ALL EXCEPT role [, role ...] | role [, role ...]>;
SET PASSWORD [FOR user] auth_option [REPLACE 'current_auth_string'] [RETAIN CURRENT PASSWORD];
SET RESOURCE GROUP group_name [FOR thread_id [, thread_id ...] ];
SET [GLOBAL | SESSION] TRANSACTION <ISOLATION LEVEL < REPEATABLE READ | READ COMMITTED | READ UNCOMMITTED | SERIALIZABLE > | < READ WRITE | READ ONLY >, ... >
~~~

**Postgres**
~~~
SET [ SESSION | LOCAL ] configuration_parameter < TO | = > < value | 'value' | DEFAULT >
SET [ SESSION | LOCAL ] TIME ZONE < value | 'value' | LOCAL | DEFAULT >
~~~
_postgres documentation refers to other variations as 'special case'_

**Trino**
~~~
SET ROLE ( role | ALL | NONE ) [ IN catalog ];
SET SESSION variable = value;
SET TIME ZONE [ LOCAL | expression ];
~~~

**Comment by mpf82** [comment]
Please don't forget Oracle and Microsoft SQL Server when talking about major dialects. Even though the Open Source community rarely uses them, they are still very big players in productive environments.

https://docs.oracle.com/en/database/oracle/oracle-database/19/sqpug/SET-system-variable-summary.html

https://learn.microsoft.com/en-us/sql/t-sql/statements/set-statements-transact-sql?view=sql-server-ver16

Most commonly used SQL dialects, according to the StackOverflow survey 2020: https://insights.stackoverflow.com/survey/2020#technology-databases-all-respondents4

**Comment by joocer** [comment]
The most universal format appears to be:
~~~
SET [ SESSION | GLOBAL | LOCAL ] variable [=|TO] value;
~~~

This is a mixed syntax that covers the syntax supported by Spark, Snowflake, BigQuery, MySQL, Trino, Postgres, Oracle and TSQL.

An outline of logic to parse this would be something like this (assuming we're working with a queue of tokens):

~~~python
pop the first token
if the first token in ("SESSION", "GLOBAL", "LOCAL"):
    it's a modifier, save it and pop the next token
this token is our variable name, save it
pop the next token
if this token is in ("TO", "="):
   it's punctuation, discard it and pop the next token
this token is our value, save it
if we have more tokens, revert to the command response and return
build the node, with the modifier, variable and value as the attributes
~~~

**Comment by tekumara** [comment]
FYI duckdb has a SET command, see [Configuration](https://duckdb.org/docs/sql/configuration.html), eg:
```
-- set the memory limit of the system to 10GB
SET memory_limit='10GB';
-- configure the system to use 1 thread
SET threads TO 1;
```

**Comment by joocer** [comment]
Thanks @tekumara, it looks like the format for DuckDB would be covered by the proposed format above.

**Comment by tobymao** [comment]
@joocer how's your progress on this? do you need any assistance?

**Comment by joocer** [comment]
Hi @tobymao , thanks for checking in. 

Using the MySQL `SET` parser as a reference I have it working for good inputs, but not failing correctly on bad inputs.

There are three things I could do with pointers on:

- Why do I keep getting this error: `AttributeError: module 'sqlglot.expressions' has no attribute 'ExternalProperty'. Did you mean: 'JournalProperty'?` - it looks like it's a pre-existing problem but I only get it when I touch the expression object when trying to reformat the AST back to SQL
- I've not been able to identify any function to tell if I've consumed all of the tokens, I could probably work it out from the index and the number of tokens, but I would have thought this would be a typical check and I just can't find the method for it
- I will definitely need help on how to fall back to the command syntax.

**Comment by joocer** [comment]
> ```python
> if we have more tokens, revert to the command response and return
> ```

more or less as per the above - this is what I currently have (supporting changes not included)

~~~python
    def _parse_set(self):
        local = self._match(TokenType.LOCAL) is not None
        global_ = self._match(TokenType.GLOBAL) is not None
        session = self._match(TokenType.SESSION) is not None

        left = self._parse_primary() or self._parse_id_var()
        
        asignment_operator = ""
        if self._match(TokenType.EQ) is not None:
            asignment_operator = "="
        elif self._match(TokenType.TO) is not None:
            asignment_operator = "TO"

        right = self._parse_statement() or self._parse_id_var()

        if self._next is not None:
            self.raise_error("SHOULD BE THE END")

        this = self.expression(
            exp.EQ,
            this=left,
            expression=right,
        )

        return self.expression(
            exp.SetItem,
            this=this,
            local=local,
            global_=global_,
            session=session,
            asignment_operator=asignment_operator
        )
~~~

**Comment by tobymao** [comment]
can you explain more about 

```Why do I keep getting this error: AttributeError: module 'sqlglot.expressions' has no attribute 'ExternalProperty'. Did you mean: 'JournalProperty'? - it looks like it's a pre-existing problem but I only get it when I touch the expression object when trying to reformat the AST back to SQL```

**Comment by tobymao** [comment]
```I've not been able to identify any function to tell if I've consumed all of the tokens, I could probably work it out from the index and the number of tokens, but I would have thought this would be a typical check and I just can't find the method for it```

if self._curr is None then you're at the end

**Comment by tobymao** [comment]
```I will definitely need help on how to fall back to the command syntax.```

look at usage of self._parse_as_command

**Comment by GeorgeSittas** [comment]
@joocer we already have some logic for parsing a subset of the `SET` statement syntax, implemented by Barak a while ago. I created a new [PR](https://github.com/tobymao/sqlglot/pull/1292) to try and reuse it, instead of duplicating code. It should now capture various inputs, e.g. `SET @q = 4`, with finer granularity.
