### ISSUE TITLE
[DuckDB Dialect] EXCLUDE and REPLACE not supported in SELECT

### ISSUE THREAD

**Issue by BTheunissen** [tobymao/sqlglot#1235]
Big fan of the library, we've been doing a lot more work with DuckDB data pipelining and validation with SQLGlot has been a big help.

The `EXCLUDE` and `REPLACE` operations come up often in our queries, as they are handy for operating with large tables without requiring to redefine all columns names between table expressions.

```
-- select all columns except the city column from the addresses table
SELECT * EXCLUDE (city) FROM addresses;
-- select all columns from the addresses table, but replace city with LOWER(city)
SELECT * REPLACE (LOWER(city) AS city) FROM addresses;
```

Source: https://duckdb.org/docs/sql/query_syntax/select.html

I see that BigQuery and Snowflake already have support for EXCLUDE, but REPLACE seems relatively unique to DuckDB.

**Comment by tobymao** [comment]
will look soon.

keep in my sqlglot is not meant for validation. it accepts invalid sql but tries to input valid sql.

**Comment by BTheunissen** [comment]
Thank you for the fast turn-around!
