### ISSUE TITLE
Snowflake date function parsing issues not fully resolved

### ISSUE THREAD

**Issue by homebase3** [tobymao/sqlglot#1254]
Opening a new issue since the old one was closed. The inverse transpile for Snowflake date is still not working. I.e.

Input:

`sqlglot.transpile("""SELECT DATEADD(DAY, 5, CAST('2008-12-25' AS DATE)) AS date_day""", read="snowflake", write="bigquery")[0]`

Actual output:

`SELECT DATEADD(DAY, 5, CAST('2008-12-25' AS DATE)) AS date_day`

Expected output:

`SELECT DATE_ADD(DATE "2008-12-25", INTERVAL 5 DAY) AS date_day`

_Originally posted by @homebase3 in https://github.com/tobymao/sqlglot/issues/1241#issuecomment-1456605425_

**Comment by tobymao** [comment]
fixed now. your original issue didn't show the inverse which is why i didn't think to fix it. 

thanks for the report

**Comment by homebase3** [comment]
Ok thank you! Didn't realize it until I tried the inverse.
