### ISSUE TITLE
Number of improvements can be made to Snowflake parsing

### ISSUE THREAD

**Issue by cillianod-wf** [tobymao/sqlglot#1259]
I've been playing around with the transpiling of Snowflake to SQLite and have noticed a number of features which are missing. I've split them up into different categories:

**Datetime functions**
- [x] [datediff()](https://docs.snowflake.com/en/sql-reference/functions/datediff) https://github.com/tobymao/sqlglot/commit/313f22486949ad806e2ce72941c4c2514e5ff6ce
- [x] [current_date()](https://docs.snowflake.com/en/sql-reference/functions/current_date) https://github.com/tobymao/sqlglot/commit/3871647e60a33212b565245cbd73e8963e377d71
- [x] `cast(datetime as date)`, when this gets transpiled it remains as is, the behaviour between Snowflake and SQLite is different however, it returns as follows - Snowflake=`yyyy-mm-dd`, SQLite=`yyyy` 

**Transformations**
- [x] [least()](https://docs.snowflake.com/en/sql-reference/functions/least) https://github.com/tobymao/sqlglot/commit/1e5ce4629bd49f43c45133fe1f755a49460f4f5a
- [x] [square()](https://docs.snowflake.com/en/sql-reference/functions/square) https://github.com/tobymao/sqlglot/commit/9f5c943fab01ddd50c4e0f07e25ca3a244efef65
- [x] [to_char()/to_varchar()](https://docs.snowflake.com/en/sql-reference/functions/to_char) https://github.com/tobymao/sqlglot/commit/8905eaa9658a73dccb088f65e5585d95bd1abcae (transpiling "format" for dialects that don't support this function not planned)
- [x] [nullifzero()](https://docs.snowflake.com/en/sql-reference/functions/nullifzero) https://github.com/tobymao/sqlglot/commit/7480d8abd7ec23a9552e5066fbcaaf2ebbcb1082

**Aggregations**
- [x] [boolor_agg()](https://docs.snowflake.com/en/sql-reference/functions/boolor_agg) https://github.com/tobymao/sqlglot/commit/662feeed1c6b68558c92b0d2bb9df34fa70413ac
- [x] [count_if()](https://docs.snowflake.com/en/sql-reference/functions/count_if) https://github.com/tobymao/sqlglot/commit/978741651a84b1aa5fb2615c1d232afe6856f305

**SQL Statements**
- [x] [qualify](https://docs.snowflake.com/en/sql-reference/constructs/qualify), this is not a feature in SQLite so not sure if there's something this can be transpiled to

I realise this is a very long list and some may not feasible in some SQL dialects but just wanted to raise all the ones I've come across. Might be able to help out on some of the easier ones like `nullifzero()` too

**Not planned**

The following are not supported in SQLite or require loading of external UDFs to work. Additional comments are OP's.

- [MD5()](https://docs.snowflake.com/en/sql-reference/functions/md5)
- [rlike()](https://docs.snowflake.com/en/sql-reference/functions/rlike), this seems to transpile to `regexp_like()` for SQLite but I don't think this is a function available in SQLite.
- exclude, this is a parameter that can be added to a [select](https://docs.snowflake.com/en/sql-reference/sql/select) statement to remove some columns from being selected
- [date_trunc()](https://docs.snowflake.com/en/sql-reference/functions/date_trunc)
- [lateral join](https://docs.snowflake.com/en/sql-reference/constructs/join-lateral)
- [last_day()](https://docs.snowflake.com/en/sql-reference/functions/last_day)
- [try_to_date()](https://docs.snowflake.com/en/sql-reference/functions/try_to_date)
- [to_date()](https://docs.snowflake.com/en/sql-reference/functions/to_date)
- [day()/month()/quarter()/year()](https://docs.snowflake.com/en/sql-reference/functions/year)
- [convert_timezone()](https://docs.snowflake.com/en/sql-reference/functions/convert_timezone)

**Comment by GeorgeSittas** [comment]
Thanks for the great report, I'll take a look soon. Feel free to contribute & let me know if you need any help.

**Comment by GeorgeSittas** [comment]
A bit of a followup on this:

- I'll not prioritize the datetime functions, because they're tricky to handle correctly. If some of them end up being too involved to implement later on, I'll just mark them as not planned but we'll happily accept a PR.

- Regarding `LEAST`, seems like SQLite doesn't have an equivalent function or something that can be easily used. Maybe, one way to implement this would be to use a `VALUES` clause instead, like in the following example:

```sql
-- Snowflake
SELECT LEAST(1, 3, 0);

-- SQLite                                                     
SELECT (WITH _v(_c) AS (SELECT * FROM (VALUES (1), (3), (0))) SELECT MIN(_c) FROM _v);
```

I added the CTE so that I could somehow refer to the single column of the `VALUES` clause. I couldn't create a table alias for it by doing something like `(VALUES ...) _v(_c)`.

**Comment by tobymao** [comment]
isn't least the same as min?

**Comment by GeorgeSittas** [comment]
You're actually right, my bad. I missed that it can be used like `least`, besides being an aggregate. Thanks!

**Comment by GeorgeSittas** [comment]
FYI @cillianod-wf I'm editing your original post to track progress and/or cross off entries that are not planned.

**Comment by GeorgeSittas** [comment]
@cillianod-wf managed to do half of the items in your list, the others were impossible to do or very tricky for sqlite, so I marked them as not planned for the time being. The remaining PRs for this are:

- Cast to `date`: https://github.com/tobymao/sqlglot/pull/1286
- Transpile `QUALIFY`: https://github.com/tobymao/sqlglot/pull/1286

Let me know if you want to tackle any of the remaining ones need help.

**Comment by cillianod-wf** [comment]
> @cillianod-wf managed to do half of the items in your list, the others were impossible to do or very tricky for sqlite, so I marked them as not planned for the time being. The last PRs to complete this are:
> 
> * [x]  Transpile `CAST(datetime AS DATE)`: [Fix transpilation of casting to date in sqlite #1286](https://github.com/tobymao/sqlglot/pull/1286)
> * [ ]  Transpile `QUALIFY`: [Implement eliminate_qualify transformation #1288](https://github.com/tobymao/sqlglot/pull/1288)
> 
> Let me know if you want to tackle any of the remaining ones need help.

@GeorgeSittas that's great, thanks for all your help!
