### ISSUE TITLE
Supporting ~*

### ISSUE THREAD

**Issue by hugokitano** [tobymao/sqlglot#1264]
I would love to be able to parse:

`select email ~* 'gmail' as is_gmail from table"`

with `parse_one()`. Is this doable?

**Comment by tobymao** [comment]
what dialect is this?

**Comment by tobymao** [comment]
this is supported in postgres

```
python -m sqlglot "select x ~* 'y'" --read=postgres
SELECT
  "x" ~* 'y'
```

**Comment by hugokitano** [comment]
got it, thanks! Needed to set the dialect
