### ISSUE TITLE
type `TIMESTAMPTZ` doesn't exist in sparksql

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1272]
sqlglot transpiles a trino type like `timestamp(6) with time zone` as the hive type `TIMESTAMPTZ` for spark, which isn't a spark type.  I'd be happy to submit a PR if there's advice about how to address this.

```
>>> sqlglot.transpile('select cast(created as timestamp(6) with time zone) created from some_table', read="trino", write="spark")
['SELECT CAST(created AS TIMESTAMPTZ) AS created FROM some_table']
```

**Comment by tobymao** [comment]
i assume we'd just drop it?

**Comment by GeorgeSittas** [comment]
@joshmarcus let me know if you plan to tackle this, otherwise I'll take a look soon.
