### ISSUE TITLE
Column order not preserved when executing SELECT statements

### ISSUE THREAD

**Issue by royvandewater** [tobymao/sqlglot#1273]
When using this table data:

```sql
{"table_a": [{"id": 1, "name": "a"}, {"id": 2, "name": "b"}]}
```

and this query:

```sql
SELECT id, name, id FROM table_a;
```

The columns in the results table are not in the correct order:

```python
query = 'SELECT id, name, id FROM table_a;'
results = execute(query, tables={"table_a": [{"id": 1, "name": "a"}, {"id": 2, "name": "b"}]})
print(results)
# id id name
# 1  1    a
# 2  2    b
```

I expected it to print then in the order `id`, `name`, `id`. This is a minimal example, in practice I ran into the issue when I'm joining across two tables that both have an `id` field and I can't tell which one is which since the order switches up on me. 

Using version `11.3.4`. Was also present in `11.2.3`

Thank you!

**Comment by royvandewater** [comment]
Will take a look myself to see if I can figure out what's going on and submit a PR. Will take me a little bit to get oriented

**Comment by royvandewater** [comment]
I [added a failing test](https://github.com/royvandewater/sqlglot/blob/8becaef029861a3b8955791839bfdd47621403f4/tests/test_executor.py#L572-L578) to demonstrate the issue and was able to narrow it down to this optimization rule _(I haven't checked any of the rules that come after this one yet)_:

I ran into two separate issues. The [first is that the rule uses a `defaultdict` to track the order](https://github.com/royvandewater/sqlglot/blob/royvandewater/execute-preserve-column-order/sqlglot/optimizer/pushdown_projections.py#L89:L89). According to the spec, `defaultdict` doesn't preserve order. However, I think the implementation still preserves insertion order in practice.

[The second issue is that SELECT statements are getting grouped into sets by name](https://github.com/royvandewater/sqlglot/blob/royvandewater/execute-preserve-column-order/sqlglot/optimizer/pushdown_projections.py#L96:L96). This means that even if the `defaultdict` is replaced with a `OrderedDict`, it will lose the order when we [iterate over the keys here](https://github.com/royvandewater/sqlglot/blob/royvandewater/execute-preserve-column-order/sqlglot/optimizer/pushdown_projections.py#L115:L115).

I don't feel like I know enough about why the columns are being grouped like that to introduce a change that could preserve the order. It seems like it's being done pretty intentionally, is there a performance benefit to selecting the same column twice immediately? I imagine that it might increase the chances of the value being readily available in a lower level cache or something, but I kinda expect the individual SQL engines to do that performance optimization right before it executes the query.

Do you have any advice on how I might approach preserving the order?

**Comment by tobymao** [comment]
i’ll have to look into this, thanks for the thorough investigation, should be an easy fix

**Comment by tobymao** [comment]
no problem, your investigation was half the battle!
