### ISSUE TITLE
WINDOW function in Postgres raising a ParseError

### ISSUE THREAD

**Issue by zshandy** [tobymao/sqlglot#1287]
Hi, I have been using sqlglot trying to parse multiple Postgres SQL, and I found out that sqlglot has trouble parsing this specific way of WINDOW function in Postgres(specifically the last example in https://www.postgresql.org/docs/current/tutorial-window.html)

```
from sqlglot import parse_one, exp
sql = """SELECT sum(salary) OVER w, avg(salary) OVER w
  FROM empsalary
  WINDOW w AS (PARTITION BY depname ORDER BY salary DESC);"""
sql_ast = parse_one(sql)
```

This query would produce this error, in which it is legitimate in Postgres dialect: 

ParseError: Invalid expression / Unexpected token. Line 3, Col: 10.
  SELECT sum(salary) OVER w, avg(salary) OVER w
  FROM empsalary
  WINDOW w AS (PARTITION BY depname ORDER BY salary DESC);

**Comment by GeorgeSittas** [comment]
Hey, are you using the latest main? I can't repro this issue.

```python
>>> import sqlglot
>>> sql = """SELECT sum(salary) OVER w, avg(salary) OVER w
...   FROM empsalary
...   WINDOW w AS (PARTITION BY depname ORDER BY salary DESC);"""
>>> sqlglot.transpile(sql)
['SELECT SUM(salary) OVER w, AVG(salary) OVER w FROM empsalary WINDOW w AS (PARTITION BY depname ORDER BY salary DESC)']
>>> sqlglot.__version__
'11.3.6'
```
