### ISSUE TITLE
Add Netezza NZSQL dialect

### ISSUE THREAD

**Issue by kur0dama** [tobymao/sqlglot#1289]
Good morning!

I work at an organization with a substantial codebase written in NZSQL for a an IBM Netezza server. We are looking to clean up legacy code and will ultimately move to a cloud based provider instead of using on-prem servers. I plan to create dialect definitions and accompanying tests for the NZSQL dialect, and will appreciate any guidance or support the maintainers can offer as I undertake this.

**Comment by tobymao** [comment]
morning. happy to help you add nzsql but we are not planning to add this ourselves. feel free to join the slack or start making prs and we can bell you out.
