### ISSUE TITLE
[Feature Request] Support transpiling full-text search queries

### ISSUE THREAD

**Issue by neilmcguigan** [tobymao/sqlglot#1290]
example:

sql = "select * from foo where bar match 'cat and hat' "

result = sqlglot.transpile(sql, read="sqlite", write="postgres")

assert result == "select * from foo where to_tsvector(bar) @@ to_tsquery('cat & hat') "

**Comment by tobymao** [comment]
this is not really standard, sqlite match is only available with an extension, i'm not inclined to implement this. you can easily create a custom transform of this yourself if you need it in your application.

untested pseudocode

```python
def match_to_tovector(node):
      if isinstance(node, exp.Match):
           return f"{exp.func('to_ts_vector', node.left)} @@ {exp.func('to_ts_query', node.right)}"
      return node

result.transform(match_to_tovector)
