### ISSUE TITLE
ARRAY_AGG() conversion between Trino and Spark

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1303]
ARRAY_AGG() in Trino supports  `array_agg(x ORDER BY y DESC)` which currently is translated to Spark as `COLLECT_LIST(x ORDER BY y DESC)` but Spark doesn't support that syntax at all -- just `COLLECT_LIST(x)`.  Could we fix this mapping to syntactically parse (and drop the ordering) or is there a way to support the ordering?

**Comment by GeorgeSittas** [comment]
I'll take a look soon
