### ISSUE TITLE
TRUNC(expr, 'DAY') returns null in SparkSQL

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1305]
This is an issue while transpiling Trino to SparkSQL:

A valid Trino date_trunc by day

`DATE_TRUNC('day' ,col);`

is transpiled into SparkSQL as

`TRUNC('day', col)`.

However, `TRUNC('day', col)` always returns NULL because `day` is not a valid argument for TRUNC.  It's potentially tricky as DATE_TRUNC in Trino is type parameterized on the input type.

**Comment by tobymao** [comment]
i'm not seeing what you're seeing, date_trunc in trino tranpiles to TRUNC(col, 'day')

```python -m sqlglot "date_trunc('day', x)" --read=trino --write=spark
TRUNC(`x`, 'day')
```

**Comment by tobymao** [comment]
i think this is what you mean

```python
spark.sql("select trunc('2017-01-01 00:00:00', 'day')").collect()
[Row(trunc(2017-01-01 00:00:00, day)=None)]
```

**Comment by joshmarcus** [comment]
yeah, exactly -- that's what I mean
