### ISSUE TITLE
Parsing of ClickHouse multi-level quantiles fails

### ISSUE THREAD

**Issue by wlhjason** [tobymao/sqlglot#1308]
The ClickHouse SQL expression `quantiles(level1, level2, …)(x)` cannot be parsed if there are more than 2 levels:

```python
>>> sqlglot.parse("SELECT quantiles(0.1, 0.2, 0.3)(a)", read="clickhouse")
sqlglot.errors.ParseError: The number of provided arguments (3) is greater than the maximum number of supported arguments (2). Line 1, Col: 34.
  SELECT quantiles(0.1, 0.2, 0.3)(a)
```

while `SELECT quantiles(0.1)(a)` and `SELECT quantiles(0.1, 0.2)(a)` can be parsed just fine.

**Comment by wlhjason** [comment]
Thanks for the speedy fix @tobymao!

**Comment by tobymao** [comment]
@wlhjason thank @GeorgeSittas !
