### ISSUE TITLE
Qualified column names within parametric functions (ClickHouse)

### ISSUE THREAD

**Issue by wlhjason** [tobymao/sqlglot#1310]
(Sorry, another ClickHouse one!)

The following ClickHouse SQL expressions lead to a parse error of the form `Expecting )` at `.`:
* `SELECT histogram(5)(t.x)`
* `SELECT groupUniqArray(2)(t.y)`
* `SELECT exponentialTimeDecayedAvg(60)(t."nested.value_col", t.time_col)`

(There is an incomplete list of parametric functions in ClickHouse here: https://clickhouse.com/docs/en/sql-reference/aggregate-functions/parametric-functions)

**Comment by tobymao** [comment]
@wlhjason what's the function signature of exponentialTimeDecayedAvg i can't find documentation on it

**Comment by wlhjason** [comment]
@tobymao It's kind of buried in the [implementation](https://clickhouse.com/codebrowser/ClickHouse/src/Processors/Transforms/WindowTransform.cpp.html)...

```
exponentialTimeDecayedAvg(decay_length: Float64)(value: Number, time: DateTime | Number)
```

There's also `exponentialTimeDecayedSum` and `exponentialTimeDecayedMax` with the same signature, plus `exponentialTimeDecayedCount` which omits the `value` input.

**Comment by tobymao** [comment]
i'll add what you have here, and then you can follow my PR and add the rest

**Comment by wlhjason** [comment]
Sure thing - thanks!

**Comment by tobymao** [comment]
check out this pr, it will show you how to add and test  the rest. ping me on slack if you have any questions

**Comment by wlhjason** [comment]
Amazing, will do - thanks @tobymao!
