### ISSUE TITLE
Allow for aliases in Snowflake predicate and other non-select clauses

### ISSUE THREAD

**Issue by homebase3** [tobymao/sqlglot#1346]
Following up on issue #1345.

I know it's non-standard in many sql dialects to use aliases in the predicate and other non-select clauses, but my understanding is that this is actually acceptable syntax in Snowflake. See link [here](https://sqlkover.com/cool-stuff-in-snowflake-part-4-aliasing-all-the-things/).

Would it be possible to adjust the Snowflake parser to allow for this?

**Comment by tobymao** [comment]
yea, should be easy to add this

**Comment by homebase3** [comment]
Would it be possible to expand this capability for OVER clauses for window functions? Running into a similar issue with the following snippet for the column `sort_order`.

```{sql}
SELECT
    *,
    IFF(
      IFF(
        uploaded_at >= '2022-06-16',
        'workday',
        'bamboohr'
      ) = source_system,
      1,
      0
    ) AS sort_order
  FROM
    unioned
  WHERE
    (
      source_system = 'workday'
      AND '9999-01-01' >= '2022-06-16'
    )
    OR (
      source_system = 'bamboohr'
      AND '0001-01-01' < '2022-06-16'
    ) QUALIFY ROW_NUMBER() OVER (
      PARTITION BY unique_filter_key
      ORDER BY
        sort_order DESC,
        1
    ) = 1
```
