### ISSUE TITLE
snowflake -> trino|presto - json access

### ISSUE THREAD

**Issue by alaturqua** [tobymao/sqlglot#1348]
Is there plan supporting to transpile json value accessing from snowflake to other languages?

Example snowflake:
```
select json_field['json_key'] as json_key,
select json_field:json_key as json_key
from json_table
```

trino|presto:
```
select json_query(json_field, 'strict $."json_key"' omit quotes) as json_key
from json_table 
```

**Comment by tobymao** [comment]
it should already be supported if you use json extract functions. but since this relies on schema info, it’s not planned
