### ISSUE TITLE
sqlglot doesn't support split(str, pattern, limit=- 1)

### ISSUE THREAD

**Issue by xinglin-zhao** [tobymao/sqlglot#1361]
SPLIT with 3 arguments was introduced in spark 3.1.2 https://spark.apache.org/docs/3.1.2/api/python/reference/api/pyspark.sql.functions.split.html. 

However, when I use sqlglot 11.4.4 to parse
```
import sqlglot
print(sqlglot.__version__)

from sqlglot import parse_one
sql = "select SPLIT(my_str, '-', 2)[1] from foo.bar"
expression = parse_one(sql, read="databricks") 
```
it will fail with error
```
ParseError: The number of provided arguments (3) is greater than the maximum number of supported arguments (2). Line 1, Col: 28.
  select SPLIT(my_str, '-', 2[4m)[0m[1] from foo.bar
```

please help take a look and lets see if this is a valid feature request, thanks.

**Comment by tobymao** [comment]
i'll do it after #1360 is in

**Comment by GeorgeSittas** [comment]
Just posted the PR.
