### ISSUE TITLE
Trino 'FROM_UNIXTIME_MILLIS' to SparkSQL

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1369]
`FROM_UNIXTIME_MILLIS(column)` is not being converted but isn't a valid SparkSQL transformation.

`from_unixtime(CAST(column / 1000 AS BIGINT))` could be a good translation.

**Comment by GeorgeSittas** [comment]
Is this function documented somewhere? I can't find it in [trino's docs](https://trino.io/docs/current/functions/datetime.html) and with a quick check it seems unregistered in the Trino image I'm using (might be calling it wrong, though).

**Comment by tobymao** [comment]
doesn't seem to exist in the trino code base

https://github.com/search?q=repo%3Atrinodb%2Ftrino+FROM_UNIXTIME_MILLIS&type=code

@joshmarcus if this a custom UDF at your company, you can write your own transformation.
