### ISSUE TITLE
Issue with parsing of timestamp functions with time zones

### ISSUE THREAD

**Issue by homebase3** [tobymao/sqlglot#1373]
I believe there may be an issue parsing and transpiling timestamp functions, especially when timezones are introduced. Here is an example of (what I think are) functionally equivalent statements in BQ, Snowflake, and DuckDB, assuming the variable start is a timestamp in UTC:

```{python}
bq_txt = 'TIMESTAMP(DATETIME(start, "America/New_York"))'
snow_txt = 'CONVERT_TIMEZONE("America/New_York",CAST(start as TIMESTAMP_TZ))'
duck_txt = 'CAST(start as TIMESTAMPTZ) AT TIME ZONE "America/New_York"'
```

Yet when you try to transpile these statements to the other languages, the correct changes are not made and the statements will fail to run in their new dialects. The command below:

```{python}
import sqlglot
print(sqlglot.transpile(bq_txt, read='bigquery', write='snowflake')[0])
print(sqlglot.transpile(bq_txt, read='bigquery', write='duckdb')[0])
print(sqlglot.transpile(snow_txt, read='snowflake', write='bigquery')[0])
print(sqlglot.transpile(snow_txt, read='snowflake', write='duckdb')[0])
print(sqlglot.transpile(duck_txt, read='duckdb', write='bigquery')[0])
print(sqlglot.transpile(duck_txt, read='duckdb', write='snowflake')[0])
```
Returns
```{text}
TIMESTAMP(DATETIME(start, 'America/New_York'))
TIMESTAMP(DATETIME(start, 'America/New_York'))
CONVERT_TIMEZONE(`America/New_York`, CAST(start AS TIMESTAMPTZ))
CONVERT_TIMEZONE("America/New_York", CAST(start AS TIMESTAMPTZ))
CAST(start AS TIMESTAMPTZ) AT TIME ZONE `America/New_York`
CAST(start AS TIMESTAMPTZ) AT TIME ZONE "America/New_York"
```

**Comment by tobymao** [comment]
do these transpilation a fail in the other dialects?

**Comment by homebase3** [comment]
I'm not certain because these are the dialects I know the best, but definitely possible.

**Comment by tobymao** [comment]
you should only file issues if the transpilation don’t work

**Comment by homebase3** [comment]
Hi Toby -- to clarify, I know transpilation doesn't work in at least Snowflake, BigQuery, and DuckDB for these functions per example above. Is this expected behavior?

**Comment by tobymao** [comment]
ah ok thanks, will look at this tonight

**Comment by tobymao** [comment]
bigquery -> duckdb/snowflake conversion is not planned, all other variants are now supported

**Comment by homebase3** [comment]
ok thanks a bunch!

**Comment by homebase3** [comment]
What was the rationale behind not supporting the BigQuery 'read' options? It creates a situation where valid BQ sql is transpired into invalid Snowflake and DuckDB sql.

**Comment by tobymao** [comment]
i’m not sure how to do it. the bigquery version is much different from the others. datetime can take a format or a time zone. i’m not sure how to detect if something is a time zone

**Comment by homebase3** [comment]
Oh interesting. Agree with you that Bigquery takes a very weird approach to time zones.

Did some thinking on this... would it be possible to allow for transpiling as below instead?

```{python}
TIMESTAMP(EXTRACT(DATETIME FROM start at time zone 'America/New_York')
```

I've never written BQ sql this way, but apparently this is perfectly valid as well (I tested in the console).

**Comment by homebase3** [comment]
Also found the list of accepted time zones if helpful: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by tobymao** [comment]
> Oh interesting. Agree with you that Bigquery takes a very weird approach to time zones.
> 
> Did some thinking on this... would it be possible to allow for transpiling as below instead?
> 
> ```
> TIMESTAMP(EXTRACT(DATETIME FROM start at time zone 'America/New_York'))
> ```
> 
> I've never written BQ sql this way, but apparently this is perfectly valid as well (I tested in the console).

yea this could be easier to do

**Comment by turntable-justin** [comment]
Would it be possible to reopen the issue for this?

**Comment by homebase3** [comment]
Would it be possible to reopen the issue for this?

**Comment by tobymao** [comment]
no, this is low priority for me and i'm not planning to do it, it would be better if there was an easy way to to detect a time zone, but i'll accept a PR if you make one
