### ISSUE TITLE
Support All BigQuery Data Types

### ISSUE THREAD

**Issue by eakmanrq** [tobymao/sqlglot#1381]
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types

For example `BIGNUMERIC` is not supported. We should go through the whole list though and make sure everything works.

**Comment by eakmanrq** [comment]
Realized that I am running an old version and support for most already exists. `BIGNUMERIC` is a harder conversion.

**Comment by tcqiuyu** [comment]
Hi @eakmanrq, I am facing a similar parsing issue when encountered `BIGNUMERIC` in bq-sql. Is that supported or not? I tried to upgrade to the latest but seems still not working. And why do you say it is a harder conversion? Thank you!

**Comment by eakmanrq** [comment]
Hey @tcqiuyu. At the time I thought we were missing wide support of BQ types but realized that wasn't actually the case. You are correct that `BIGNUMERIC` is currently unsupported.

The conversion of harder since `BIGNUMERIC` supports a precision of 76 digits while it is more common to support a precision of 38 digits. So we would need to decide how to handle this lack of precision in the conversion. Since I didn't really need `BIGNUMERIC` at this time I decided to not address it at the time.

**Comment by tobymao** [comment]
we should add a new type called BIGDECIMAL which bignumeric maps to

**Comment by tobymao** [comment]
53321211
