### ISSUE TITLE
Calling `match` as a function fails to parse

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#1388]
In ibis, our ClickHouse backend uses [the `match` function](https://clickhouse.com/docs/en/sql-reference/functions/string-search-functions#matchhaystack-pattern-haystack-regexp-pattern-operator) for regular expression searching.

In 11.5.1 this function now fails to parse (it worked in 11.4.x):

```
In [4]: import sqlglot as sg

In [5]: sg.__version__
Out[5]: '11.5.1'

In [6]: sg.parse_one("select match('abc', '([a-z]+)')", read="clickhouse")
...
ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.MatchAgainst'>. Line 1, Col: 31.
  select match('abc', '([a-z]+)')
```

Unfortunately, switching to using `a REGEXP b` also doesn't work because that gets turned into a call to `REGEXP_LIKE` which isn't a function in ClickHouse so we can't upgrade our sqlglot version to pick up the fix to #1377 because it breaks our ClickHouse backend.

**Comment by cpcloud** [comment]
I guess there two issues here:

1. `match` doesn't parse
2. `a REGEXP b` should be turned into a `match` function call, and not a `REGEXP_LIKE` call.

**Comment by cpcloud** [comment]
We can work around this problem for now by using [`multiMatchAny(arg, [pattern])`](https://clickhouse.com/docs/en/sql-reference/functions/string-search-functions#multimatchanyhaystack-pattern1-pattern2--patternn).

**Comment by GeorgeSittas** [comment]
Thanks for reporting this, the parser fail is related to https://github.com/tobymao/sqlglot/commit/dc494fc650950d02cb35801d7811f30e032c2d13 (before it was parsed as anonymous). I'll try to fix both issues.

**Comment by GeorgeSittas** [comment]
@cpcloud I'm trying to run a query that uses `REGEXP`, but it doesn't seem to work as expected:

```sql
select 'abc' regexp '([a-z]+)'
```
> Code: 62. DB::Exception: Syntax error: failed at position 21 (''([a-z]+)''): '([a-z]+)'. Expected one of: token, Comma, FROM, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 23.3.1.1731 (official build))

Am I using this correctly? If yes, can you please check it too? I ran the above query in play.clickhouse.com
