### ISSUE TITLE
Translate dialect - MySQL to Snowflake

### ISSUE THREAD

**Issue by 4sushi** [tobymao/sqlglot#1393]
Hello,

I'm trying to translate MySQL dialect into Snowflake dialect.
I did some tests, but the translation doesn't seem to work.

> It can be used to format SQL or translate between [19 different dialects](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/__init__.py) like [DuckDB](https://duckdb.org/), [Presto](https://prestodb.io/), [Spark](https://spark.apache.org/), [Snowflake](https://www.snowflake.com/en/), and [BigQuery](https://cloud.google.com/bigquery/).

**Actual behaviour**
```python
sqlglot.transpile("select DATE_FORMAT(created_date, '%Y-%m')", read="mysql", write="snowflake")[0]
# "SELECT DATE_FORMAT(created_date, '%Y-%m')"
```

**Expected behaviour**
```python
sqlglot.transpile("select DATE_FORMAT(created_date, '%Y-%m')", read="mysql", write="snowflake")[0]
# "SELECT to_char(created_date, 'yyyy-mm')"
```

`sqlglot==11.5.2`

Thanks!

**Comment by GeorgeSittas** [comment]
I'll take a look, thanks for the report.
