### ISSUE TITLE
Comments lose their position in queries 

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1395]
I'm seeing an issue where comments end up moving to different positions in the tree during transpilation.  For example:

```
>>> query = """
... select a from b join c on c.id = b.id
... where 1 = 1
... -- comment 1
... and foo
... -- comment 2
... and bar
... """
>>> sqlglot.transpile(query)
['SELECT a FROM b JOIN c ON c.id = b.id WHERE /* comment 2 */ /* comment 1 */ 1 = 1 AND foo AND bar']
```

The comment2 move to the beginning of the WHERE clause.  If there is no condition after the comment, the comment is dropped entirely.

If we transpile that query again, the comments move again:

```
'SELECT a FROM b JOIN c ON c.id = b.id/* comment 2 */ /* comment 1 */  WHERE 1 = 1 AND foo AND bar'
```

**Comment by GeorgeSittas** [comment]
This is related to https://github.com/tobymao/sqlglot/commit/1f9a4f7f4 (related discussion: https://github.com/tobymao/sqlglot/pull/758#discussion_r1031702139).

cc: @mpf82 I think we may need to get rid of `exp.Binary` from `WITH_SEPARATED_COMMENTS`.

**Comment by GeorgeSittas** [comment]
There's actually another issue, because connectors (`AND`, `OR`) have special sqlgen logic. I'm looking into this now.

Example:
```python
import sqlglot

query = """
select a from b
where foo
-- comment 1
and bar
-- comment 2
and bla
"""

print(sqlglot.parse_one(query).sql(pretty=True))
```

Which outputs:
```
➜  sqlglot git:(main) ✗ python test_comments.py
SELECT
  a
FROM b
WHERE
  foo AND bar AND bla /* comment 2 */
```

Thanks for the report @joshmarcus!
