### ISSUE TITLE
Oracle: Format argument unsupported for TO_CHAR/TO_VARCHAR function

### ISSUE THREAD

**Issue by deliciouslytyped** [tobymao/sqlglot#1398]
```
>>> sqlglot.parse("SELECT to_char(szul_dat, 'YYYY-MM-DD') FROM s_ugyfel;", 'oracle')[0].sql()
Format argument unsupported for TO_CHAR/TO_VARCHAR function
'SELECT CAST(szul_dat AS TEXT) FROM s_ugyfel'
```
CC @GeorgeSittas , xref https://github.com/tobymao/sqlglot/pull/1275

**Comment by GeorgeSittas** [comment]
You need to specify the output dialect as well, e.g.

```python
>>> sqlglot.parse("SELECT to_char(szul_dat, 'YYYY-MM-DD') FROM s_ugyfel;", 'oracle')[0].sql("oracle")
"SELECT TO_CHAR(szul_dat, 'YYYY-MM-DD') FROM s_ugyfel"
```

Let me know if the issue persists and I'll reopen this.

**Comment by deliciouslytyped** [comment]
Oh! Thanks. I've probably seen that before and forgot about it.

Would it be reasonable for the parse trees to keep track of their source dialect and have `.sql()` use that as the default?

**Comment by GeorgeSittas** [comment]
I don't think so, the AST is supposed to abstract away the dialect completely. Also, there's no obvious place where you'd keep this information in the tree.
