### ISSUE TITLE
Fails to parse valid presto query

### ISSUE THREAD

**Issue by evyasonov** [tobymao/sqlglot#1400]
The query was returned by "SHOW CREATE TABLE" command in presto/athena (which makes it valid), but sqlglot can't parse it:

```
CREATE EXTERNAL TABLE `my_schema.my_table`(
  `a1` string,
  `a2` bigint,
  `a4` date,
  `a5` timestamp,
  `a6` boolean,
  `a7` array<date>)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://bucket/path/2023-04-08'
TBLPROPERTIES (
  'has_encrypted_data'='false')
```

Please fix

**Comment by tobymao** [comment]
this looks like hive, does it parse if you specify dialect hive?

**Comment by tobymao** [comment]
presto is reading a table created by hive, that does not mean it’s valid presto syntax

**Comment by evyasonov** [comment]
@tobymao 
Not sure about exact dialect, but I know for sure that if I execute this code on presto / athena, it will work correctly.
But I've tried `read='hive'` -- sqlglot still can not parse it.
And this is kind of popular format of queries, because `SHOW CREATE TABLE` every time returns it.

**Comment by tobymao** [comment]
this is hive syntax, support has been added. reading as presto will not be supported as it's not presto

**Comment by evyasonov** [comment]
Okay..... Thanks for the fixes.

Let's say I have lots of files of presto sql which need to be transpiled to different sql.
Files are good, presto executes all files without any errors.
But some files contain create table in the above format.
And I want to process the files with sqlglot one by one.
What should I do or how should I call sqlglot functions in this case? Because I can't just use `read='presto'`.

**Comment by tobymao** [comment]
if you detect stored as, change dialect to hive

**Comment by evyasonov** [comment]
But this is kind of dirty hack... And okay, I can do a workaround in my scripts: try parse as presto first, if fail, try parse with hive.
But I think that other people will also have this problem and it's good to think about it.

Maybe you can change read behavior the way it can accept a list such as `read=['presto', 'hive']` and if parser fails, it tries the next dialect from the list. What do you think?

P.S. my real example is that I use sqlglot as a formatter + checker (checking if partition columns are always presented, checking if there's not more than 2 nested subqueries in the query, checking if the query scans not more than X days of data and so on). And I spreaded it for a whole team. And we also use presto. So I always expect presto input. And `create table` query I mentioned works on presto. So the team expects that the formatter will also work...

**Comment by tobymao** [comment]
can you show me documentation that shows where presto supports this syntax?

**Comment by evyasonov** [comment]
@tobymao 
It's not in presto documentation, but it's in athena documentation: https://docs.aws.amazon.com/athena/latest/ug/create-table.html
But it works both for athena, presto and trino

**Comment by evyasonov** [comment]
> Maybe you can change read behavior the way it can accept a list such as `read=['presto', 'hive']` and if parser fails, it tries the next dialect from the list. What do you think?

@tobymao any update?

**Comment by tobymao** [comment]
nope. i already told you my decision
