### ISSUE TITLE
Performance is not great on larger files

### ISSUE THREAD

**Issue by deliciouslytyped** [tobymao/sqlglot#1404]
Parsing the attached file is rather slow. Splitting it over ";" (unsafe but it's fine for a test) reduced the time significantly, so something is not scaling well.

```python
from time import time as t
sql = open(r"insert_ship.sql").read()

start = t()
xx = sqlglot.parse(sql)
end = t()
print(end - start)

start = t()
for l in sql.split(";"):
    sqlglot.parse(l)
end = t()    
print(end - start)
```
```
324.2877616882324
1.7261686325073242
```

This kind of splitting is what results in https://github.com/tobymao/sqlglot/issues/1403 when there is a comment on a line.

[insert_ship.txt](https://github.com/tobymao/sqlglot/files/11184556/insert_ship.txt) (`.txt` because GitHub won't let me upload `.sql`)

**Comment by tobymao** [comment]
i can't open the file, what's the encoding of it?

**Comment by deliciouslytyped** [comment]
Windows-1250 apparently.

**Comment by deliciouslytyped** [comment]
Seems to have fixed my problem, thanks 👍
