### ISSUE TITLE
Support for Presto/Trino's interval syntax

### ISSUE THREAD

**Issue by vegarsti** [tobymao/sqlglot#1410]
As far as I can tell, most SQL dialects use `interval '1 days'` to specify intervals, where the unit is inside the quotes.

This is not valid in [Presto](https://prestodb.io/docs/current/functions/datetime.html#functions-datetime--page-root) and [Trino](https://trino.io/docs/current/functions/datetime.html#date-and-time-operators), where the value is the only thing inside quotes, and the unit comes after the quotes, i.e. `interval '1' day`, or `interval '3' year`. (Also there's no week interval unit in these dialects.) It looks like `interval '1' day` is also valid syntax in Postgres, so maybe this has to do with translating the interval to `interval '1' day` if the dialect doesn't support `interval '1 days'`.

Is it possible to add this rewrite? I'd be happy to contribute.

I don't really know, but I'd assume there needs to be a Presto override for `Generator.interval_sql()`.

And that the unit needs to be extracted from the value literal?

```terminal
>>> sqlglot.parse_one("select interval '1' day")
(SELECT expressions:
  (INTERVAL this:
    (LITERAL this: 1, is_string: True), unit:
    (IDENTIFIER this: day, quoted: False)))
>>> sqlglot.parse_one("select interval '1 days'")
(SELECT expressions:
  (INTERVAL this:
    (LITERAL this: 1 days, is_string: True)))
```

**Comment by GeorgeSittas** [comment]
Hello, and thanks for reporting this! I think there are two steps to resolve this issue:

- At parse time, if the `unit` argument is `None`, make sure to split `this` into its two parts, i.e. the value and the unit.
- Rewrite the base generator's `interval_sql` so that it defaults to the most commonly used syntax (i.e. `'1 days'` if that's what most dialects use) and then override it in each dialect that uses the other syntax to use the correct form for it.

This is just a guess/intuition, but I'll take a look because it might be trickier than it looks.

**Comment by vegarsti** [comment]
That sounds right to me!

**Comment by GeorgeSittas** [comment]
Did some investigation regarding what each dialect supports for interval expressions and made the following list. For some of these dialects I tested queries containing `INTERVAL` directly, and for the rest of them I relied on their docs.

```
• BigQuery: INTERVAL <num> <var> (<num> can also be a string, like ‘1’), values like ‘1 day’ don’t work
• ClickHouse: same as BigQuery, but values like ‘1 day’ work
• DataBricks: seems to support INTERVAL <str> <var>, where str is e.g. ‘5’.
• Drill: same as DataBricks
• DuckDB: same as ClickHouse
• Hive/Spark: same as ClickHouse
• MySQL: same as BigQuery
• Oracle: same as DataBricks
• Postgres: same as DataBricks, also supports values like ‘1 day’
• Presto/Trino: same as DataBricks
• Redshift: supports INTERVAL <str>, where str is e.g. ‘1 day’
• Snowflake: same as Redshift (note that it also supports values like ‘1 day, 1 year’, order is important)
```

Some of these dialects also support expressions like `INTERVAL <str> <var> TO <var>`, for example BigQuery includes the following example in the documentation: `INTERVAL ‘0-13 370 48:61:61’ YEAR TO SECOND`. Another example: DataBricks allows `SELECT INTERVAL ‘100-00’ YEAR TO MONTH`. This syntax is currently not supported in SQLGlot.

cc: @tobymao what do you think about this?

**Comment by tobymao** [comment]
right, at parse time we need to parse it to canonical form. and then have an enum at generation time to make it right

**Comment by GeorgeSittas** [comment]
Cool, I'll try to make a PR for this soon.

**Comment by vegarsti** [comment]
> Cool, I'll try to make a PR for this soon.

Awesome!
