### ISSUE TITLE
TABLESAMPLE BERNOULLI doesn't translate from TrinoSQL to SparkSQL

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1425]
`TABLESAMPLE BERNOULLI (50)` in TrinoSQL isn't translated cleanly to SparkSQL, as SparkSQL doesn't support `TABLESAMPLE BERNOULLI (50)`.  `TABLESAMPLE (50)` would be a fine translation -- it will use a random sampling, but the result will be similar.

**Comment by GeorgeSittas** [comment]
> TABLESAMPLE (50) would be a fine translation -- it will use a random sampling, but the result will be similar.

Don't think this form is supported in Spark either, see: https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-sampling.html

Example:

```sql
➜  sqlglot git:(main) spark-sql -e "WITH foo(x) AS (SELECT 1) SELECT * FROM foo TABLESAMPLE (50)"
Error in query:
50 is not a valid byte length literal, expected syntax: DIGIT+ ('B' | 'K' | 'M' | 'G')(line 1, pos 57)

== SQL ==
WITH foo(x) AS (SELECT 1) SELECT * FROM foo TABLESAMPLE (50)
---------------------------------------------------------^^^
```

**Comment by GeorgeSittas** [comment]
Happy to tackle this, can take a look a bit later if someone doesn't beat me to it.
