### ISSUE TITLE
DATE_ADD translation between Trino and SparkSQL

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1427]
This Trino query:

```
SELECT date_add('month', -1, TIMESTAMP '2020-03-01 00:00:00 UTC');
```
is translated to SparkSQL as:
```
["SELECT DATE_ADD(CAST('2020-03-01 00:00:00 UTC' AS TIMESTAMP), -1)"]
```

but should be

```
SELECT dateadd(month, -1, CAST('2020-03-01 00:00:00 UTC' AS TIMESTAMP))
```

This is also true for other units of time measurement besides month.

**Comment by tobymao** [comment]
is this new to spark?

**Comment by tobymao** [comment]
looks like dateadd with unit is new to 3.4

**Comment by tobymao** [comment]
i can't replicate this. in your future issues, please write the full commands you use to replicate the issues.

i'm seeing that sqlglot correctly translate to ADD_MONTHS

```(.env) [toby@muc sqlglot]$ python -m sqlglot "date_add('month', -1, timestamp '')" --read=trino --write=spark
ADD_MONTHS(CAST('' AS TIMESTAMP), -1)
```
