### ISSUE TITLE
parse fail when mysql 

### ISSUE THREAD

**Issue by jr981008** [tobymao/sqlglot#1434]
CREATE TABLE IF NOT EXISTS `test` (
 
    `updateTime`         DATETIME     NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
    `insertTime`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci ROW_FORMAT=DYNAMIC ;

parse fail

**Comment by tobymao** [comment]
@GeorgeSittas https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html

**Comment by GeorgeSittas** [comment]
Great thanks, will look into this
