### ISSUE TITLE
Optimize adds table alias to custom column name

### ISSUE THREAD

**Issue by steven-luabase** [tobymao/sqlglot#1443]
Follow-up/semi related to this [issue](https://github.com/tobymao/sqlglot/issues/1420)

See code snippet below for trying to optimize a specific query example:
```
sql = '''
SELECT
    DATE_TRUNC('month', t1."RETURN_DATE")::DATE AS "MONTH",
    COUNT(*) AS "RETURN_COUNT"
FROM
    "DEMO_DATA"."DBT_PAGILA"."RENTAL" AS t1
WHERE
    t1."RETURN_DATE" IS NOT NULL
GROUP BY
    "MONTH"
ORDER BY
    "MONTH";
'''

parsed = sqlglot.parse_one(sql)

schema = {
    "DEMO_DATA":{
        "DBT_PAGILA":{
            "RENTAL":{
                "RETURN_DATE":"DATE",
            },
        }
    }
}

print(optimize(parsed, schema).sql(pretty=True))
```

The optimized SQL looks like:
```
SELECT
  CAST(DATE_TRUNC('month', "t1"."RETURN_DATE") AS DATE) AS "MONTH",
  COUNT(*) AS "RETURN_COUNT"
FROM "DEMO_DATA"."DBT_PAGILA"."RENTAL" AS "t1"
WHERE
  NOT "t1"."RETURN_DATE" IS NULL
GROUP BY
  "t1"."MONTH"
ORDER BY
  "MONTH"
```

The problem in the optimized SQL is in the `GROUP BY` clause: `"t1"."MONTH"`. It attached the `t1` table alias to the custom named `MONTH` column which does not exist in the `RENTAL` table.

I've tried a few things for example removing the `qualify_columns` optimization rule, which works for this query, but causes other problems for other queries (I know in the previous issue it's been mentioned that removing this rule is highly advised against).

**Comment by steven-luabase** [comment]
I don't think it's a case issue, more that the custom column labeled `MONTH` doesn't exist in `t1`

**Comment by steven-luabase** [comment]
But I see what you're saying, if I add quotes into the schema it works as expected. Closing this for now.

**Comment by tobymao** [comment]
```
from sqlglot import parse_one
from sqlglot.optimizer import optimize

sql = '''
SELECT
    DATE_TRUNC('month', t1."RETURN_DATE")::DATE AS "MONTH",
    COUNT(*) AS "RETURN_COUNT"
FROM
    "DEMO_DATA"."DBT_PAGILA"."RENTAL" AS t1
WHERE
    t1."RETURN_DATE" IS NOT NULL
GROUP BY
    "MONTH"
ORDER BY
    "MONTH";
'''


schema = {
    '"DEMO_DATA"':{
        '"DBT_PAGILA"':{
            '"RENTAL"':{
                '"RETURN_DATE"':"DATE",
            },
        }
    }
}

print(optimize(sql, schema).sql(pretty=True))```
