### ISSUE TITLE
Redshift dialect: support for POSIX operators

### ISSUE THREAD

**Issue by paulgrow-octane** [tobymao/sqlglot#1450]
Using `sqlglot 11.5.5`, parsing the Redshift query:

```sql
SELECT column1 ~ '\\d'
FROM table1
```

results in the error:

```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 16.
  SELECT column1 ~ '\\d'
FROM table1
```

`expression [ ! ] ~ pattern` is valid syntax in the [Redshift SQL dialect](https://docs.aws.amazon.com/redshift/latest/dg/pattern-matching-conditions-posix.html).

**Comment by tobymao** [comment]
thanks!
