### ISSUE TITLE
Add support for Spark functions

### ISSUE THREAD

**Issue by vegarsti** [tobymao/sqlglot#1455]
Spark has [a bunch of built-in functions](https://spark.apache.org/docs/latest/api/sql/index.html), such as `timestamp()` which is a shorthand for casting something to a timestamp. It'd be nice to have these in Spark's Parser, right now this is treated as an anonymous function so it won't get transpiled.

I'd be happy to add these, and I've taken the liberty to add the `timestamp` one in this PR: https://github.com/tobymao/sqlglot/pull/1454

**Comment by GeorgeSittas** [comment]
Are there any functions that you currently need? I'm not sure if it's high priority to go through the whole list and add all missing expressions because there's a lot of them.

cc: @tobymao

**Comment by tobymao** [comment]
closing as not planned, but we’ll happily accept your prs, thanks!
