### ISSUE TITLE
apply_index_offset only applies offset to ints

### ISSUE THREAD

**Issue by vegarsti** [tobymao/sqlglot#1493]
For dialects where arrays are 1-indexed instead of 0-indexed, SQLGlot kindly adds a + 1 in indexing operations (`exp.Bracket`). This is done through [`apply_index_offset(expressions, offset)`](https://github.com/tobymao/sqlglot/blob/e40cb6312f8492d51fed5df454efca39bd517e39/sqlglot/helper.py#L134-L157).

Not surprisingly, it only does this if the expression passed in is an int:

https://github.com/tobymao/sqlglot/blob/e40cb6312f8492d51fed5df454efca39bd517e39/sqlglot/helper.py#L151

And this can be seen here:

```
>>> sqlglot.transpile("select array_col[1]", read="spark", write="trino")
Applying array index offset (1)
['SELECT array_col[2]']
>>> sqlglot.transpile("select array_col[array_size(col) - 1]", read="spark", write="trino")
['SELECT array_col[CARDINALITY(col) - 1]']
>>> sqlglot.parse_one("select array_col[array_size(col)-1]", read="spark")
(SELECT expressions:
  (BRACKET this:
    (COLUMN this:
      (IDENTIFIER this: array_col, quoted: False)), expressions:
    (SUB this:
      (ARRAYSIZE this:
        (COLUMN this:
          (IDENTIFIER this: col, quoted: False))), expression:
      (LITERAL this: 1, is_string: False))))
```

Would it be possible to extend this such that it's able to handle more cases than plain ints?

For instance, in the example above, it would be possible and correct to add 1 to the expression in the bracket. But we could only do this because the `array_size` function returns an int, and that int is using the offset of the dialect. So we would need to know that in here, I guess. A counter example would be if the expression in the bracket was an `array_position` call, for example. And there are probably many cases where it would not be correct.

**Comment by GeorgeSittas** [comment]
I don't think adding one to the index produced by `array_position` is wrong here. For example:

```sql
spark-sql> SELECT array_position(array(3, 2, 1), 1);
array_position(array(3, 2, 1), 1)
3
```

```sql
trino> SELECT ARRAY_POSITION(ARRAY[3, 2, 1], 1);
 _col0 
-------
     3 
(1 row)
```

So, if you used spark's array position as an index, it'd refer to the 4th element of the array and in order to get the same behavior in trino you'd have to add 1, since it's 1-based. Conversely, if you used trino's array position as an index, it'd refer to the 3rd element of the array and in order to get the same behavior in spark you'd have to subtract 1, since it's 0-based.

I'm not sure if adding one is generally correct, though. I also haven't worked much on `apply_index_offset`; maybe @tobymao can provide more context here?

**Comment by GeorgeSittas** [comment]
In the meantime, @vegarsti do you have any other example in mind where adding one could lead to problems? AFAIK only Presto / Trino use 1-indexing, among the dialects currently supported in SQLGlot.

**Comment by vegarsti** [comment]
> I don't think adding one to the index produced by `array_position` is wrong here. For example:
> 
> ```sql
> spark-sql> SELECT array_position(array(3, 2, 1), 1);
> array_position(array(3, 2, 1), 1)
> 3
> ```
> 
> ```sql
> trino> SELECT ARRAY_POSITION(ARRAY[3, 2, 1], 1);
>  _col0 
> -------
>      3 
> (1 row)
> ```
> 
> So, if you used spark's array position as an index, it'd refer to the 4th element of the array and in order to get the same behavior in trino you'd have to add 1, since it's 1-based. Conversely, if you used trino's array position as an index, it'd refer to the 3rd element of the array and in order to get the same behavior in spark you'd have to subtract 1, since it's 0-based.
> 
> I'm not sure if adding one is generally correct, though. I also haven't worked much on `apply_index_offset`; maybe @tobymao can provide more context here?

Ah, nice, that makes sense! I hadn't realized that. In that case I can't think of any other examples right now.

**Comment by GeorgeSittas** [comment]
@vegarsti we're investigating whether this is possible & how to implement the suggested change. Will get back to you once we have an update.

**Comment by vegarsti** [comment]
Sweet!!
