### ISSUE TITLE
Transform exp.Explode and exp.Posexplode into exp.Unnest

### ISSUE THREAD

**Issue by vegarsti** [tobymao/sqlglot#1495]
In some languages (at least Spark SQL), `select explode(array_col) as a` will unravel the `array_col` such that each element is on one line. If this is selected along with other columns, this is semantically the same as a cross join.

Some languages (not sure which, but at least Presto and Trino) have support for this as `select a from unnest(array_col) as unnested_alias.b`. If there's a select from a table, it will be a cross join. 

Examples of what we want

```
select explode(array_col)
-> select col from unnest(array_col) as some_alias(col)

select explode(array_col) as alias
-> select alias from unnest(array_col) as some_alias(alias)

select posexplode(array_col)
-> select pos, col from unnest(array_col) with ordinality as some_alias(col, pos)

select a, posexplode(array_col) from table
-> select a, pos, col cross join unnest(array_col) with ordinality as some_alias(col, pos)
```

There is support for this going in the opposite direction, cross join unnest to lateral view explode. Used in presto -> hive:
https://github.com/tobymao/sqlglot/blob/e40cb6312f8492d51fed5df454efca39bd517e39/sqlglot/transforms.py#L140-L161 
(Frankly, I'm not sure of the difference in just using explode and using lateral view explode.)

With help from @GeorgeSittas I've [added support for this](https://github.com/duneanalytics/harmonizer/blob/e022b92fe0bd75ceacea25d6aa2124a66f3e6e85/dune/harmonizer/dialects/dunesql.py#L8-L68) in [duneanalytics/harmonizer](https://github.com/duneanalytics/harmonizer) by adding it as a preprocessing step. Test cases are [here](https://github.com/duneanalytics/harmonizer/blob/e022b92fe0bd75ceacea25d6aa2124a66f3e6e85/tests/test_dialect.py#L42-L116).

Would love to harden this and get it in upstream, so I'm planning to create a PR for it.

**Comment by GeorgeSittas** [comment]
Awesome, feel free to create a PR and we'll be happy to help improve the current implementation and get it upstream!
