### ISSUE TITLE
T-SQL Table Hints not Removed During Conversion

### ISSUE THREAD

**Issue by cjkoester** [tobymao/sqlglot#1497]
T-SQL table hints are not removed when converting to Spark SQL. I would expect them to be removed since they are not valid in Spark SQL.

```python
import sqlglot

qry = 'select [col1], [col2] from some_table WITH (NOLOCK)'
sqlglot.transpile(qry, read="tsql", write="spark")[0]
```
Output:

```SELECT `col1`, `col2` FROM some_table WITH (NOLOCK)```

Expected output:

```SELECT `col1`, `col2` FROM some_table```

The [T-SQL table hints documentation](https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-ver16) contains a list of hints and where they can be applied.

**Comment by GeorgeSittas** [comment]
This is interesting, seems like Spark executes this query without problems (it most likely doesn't affect the query semantics, though):

```sql
spark-sql> WITH x AS (SELECT 1) SELECT * FROM X WITH (NOLOCK);
1
Time taken: 2.243 seconds, Fetched 1 row(s)
```

Another bizarre example:
```sql
spark-sql> WITH x AS (SELECT 1) SELECT * FROM X WITH (FOOBAR);
1
Time taken: 0.233 seconds, Fetched 1 row(s)
```

They probably parse these queries but "discard" the hints at execution time (unless I'm missing something).

**Comment by GeorgeSittas** [comment]
Ah, makes sense, thanks!

```sql
spark-sql> WITH x AS (SELECT 1) SELECT with.foobar FROM x WITH (FOOBAR);
1
Time taken: 0.206 seconds, Fetched 1 row(s)
```
