### ISSUE TITLE
Multiple Joins w/ Selects Still Fail

### ISSUE THREAD

**Issue by kgdiem** [tobymao/sqlglot#1500]
Follow up to https://tobiko-data.slack.com/archives/C0448SFS3PF/p1682527687012379 / 
https://github.com/tobymao/sqlglot/blob/main/sqlglot/dataframe/README.md?plain=1#L228

I made a 3 examples here using SQLGlot 11.6.0: https://github.com/kgdiem/sqlglot-join-example/blob/main/mismatched_join_columns.py 

Even in the event of selecting every column on the joined tables, a join key always references the wrong table in the unoptimized select

Still have to look at how we're making a dataframe that generates an empty select statement in the unoptimized SQL ([ref](https://tobiko-data.slack.com/archives/C0448SFS3PF/p1682628523070129?thread_ts=1682527687.012379&cid=C0448SFS3PF))

**Comment by eakmanrq** [comment]
Thanks @kgdiem for your repros. Small typo in one of them: https://github.com/kgdiem/sqlglot-join-example/blob/main/mismatched_join_columns.py#L55

Should be `f.lit('X')`

This PR fixes the issues identified: https://github.com/tobymao/sqlglot/pull/1509
