### ISSUE TITLE
Regression of interval parsing

### ISSUE THREAD

**Issue by alippai** [tobymao/sqlglot#1503]
```sql
select sum(x) over (partition by x order by y range between interval '1 days')
```
is parsed into:
```sql
SELECT
  SUM("x") OVER (PARTITION BY "x" ORDER BY "y" range BETWEEN INTERVAL '1' days AND CURRENT ROW)
```
instead of the previous (correct):
```
SELECT
  SUM("x") OVER (PARTITION BY "x" ORDER BY "y" range BETWEEN INTERVAL '1 days' AND CURRENT ROW)
```
Note the `days`

**Comment by tobymao** [comment]
what dialect is this an issue for?

**Comment by alippai** [comment]
I see https://github.com/tobymao/sqlglot/issues/1410 now. I'm using the postgres dialect, I was checking for changes when upgrading sqlglot and noticed this odd syntax.

**Comment by tobymao** [comment]
are you sure this is valid postgres? i can't get it to parse in postgres 13

**Comment by alippai** [comment]
I use a postgresql derivation, it doesn't really matter.
Better example:
```sql
select interval '1 hour'
```
vs
```sql
select interval '1 hours'
```

The first is parsed correctly, the second gives:
```sql
select interval '1' hours
```
Which is not valid. Only:
```sql
select interval '1' hour
```
is valid postgresql syntax

**Comment by alippai** [comment]
(The first means `select interval '1' as hours`)

**Comment by alippai** [comment]
Thanks!

**Comment by tobymao** [comment]
thanks for the report and the quick response to my questions!
