### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by rgudic** [tobymao/sqlglot#1518]
Hi,

I know this is not an issue but rather a need for assistance. if you can provide help i would be forever grateful :)

Is there an easy way to get FQDNs of columns, meaning catalog, db, table and the name of the column itself? I've tried `to_dot` function but it doesnt resolve columns to originating tables. I've also tried using `sqlglot.lineage` but I am still struggling to make it work; for example, it fails if some of the columns have different case in e.g. group by statement in comparison to select.

I know I can get list of columns, list of joins, list of tables, etc....but I would like to know which columns were from which table

**Comment by GeorgeSittas** [comment]
Hey, if your use case is a simple one, there are some helper methods on the `Column` expression. For example:

```python
>>> sqlglot.parse_one("catalog.database.table.column")
(COLUMN this:
  (IDENTIFIER this: column, quoted: False), table:
  (IDENTIFIER this: table, quoted: False), db:
  (IDENTIFIER this: database, quoted: False), catalog:
  (IDENTIFIER this: catalog, quoted: False))
>>> sqlglot.parse_one("catalog.database.table.column").catalog
'catalog'
>>> sqlglot.parse_one("catalog.database.table.column").db
'database'
>>> sqlglot.parse_one("catalog.database.table.column").table
'table'
>>> sqlglot.parse_one("catalog.database.table.column").name
'column'
```

> I know I can get list of columns, list of joins, list of tables, etc....but I would like to know which columns were from which table

If your columns are aliased, then you might wanna check out the "scope" module. There are several examples in the codebase and you can also find some past discussion on this topic, e.g. https://github.com/tobymao/sqlglot/discussions/522. Closing this issue, but let me know if something's unclear and I'll be happy to help!

**Comment by rgudic** [comment]
Hi, thanks for the reply....

use case is not that simple. I am fetching hundreds of SQL queries from Qlik Sense (our BI tool). My task is to generate lineage for BI reports/dashboards. 

I see that `scope` module works only for aliased tables, and that is **_probably_** ok for queries where there are joins and similar. Nevertheless, I never actually saw a query where users put 
`select catalog.database.table.column
from catalog.database.table.column`.

**Comment by GeorgeSittas** [comment]
Can you provide a small example of what you're looking to achieve in your application?

**Comment by tobymao** [comment]
i think they’re looking for the optimizer

**Comment by ninja96826** [comment]
Hello toby you have made a fabulous library . i wanted to use the lineage module i m not able to find how can i use it.if some sort of example could i see it would be grateful.
