### ISSUE TITLE
KEEP in an Oracle SQL Statement is retrieving a ParseError

### ISSUE THREAD

**Issue by Pizzi95** [tobymao/sqlglot#1520]
If you try to parse the statement below it returns an Invalid expression / unexpected token error
`
sql_query = """ SELECT  MIN(column_name) KEEP (DENSE_RANK FIRST ORDER BY column_name DESC)  FROM table_name;
"""
parsed = parse_one(sql_query , read='oracle')
`

**Retrieved Error:**
![image](https://user-images.githubusercontent.com/30730327/235735796-7b43b825-bdd4-4a09-a3cb-1f192d8fd981.png)

In general, the KEEP clause is used in combination with the DENSE_RANK, RANK, or ROW_NUMBER functions to identify the rows that satisfy the criteria for the aggregate function, and then the KEEP clause applies the aggregate function only to those rows. More info here: [Oracle Docs](https://docs.oracle.com/database/121/SQLRF/functions003.htm#SQLRF20035)

**Comment by GeorgeSittas** [comment]
Will take a look soon, thanks for the report!
