### ISSUE TITLE
qualify_columns does not work for some CTEs

### ISSUE THREAD

**Issue by Sharadh** [tobymao/sqlglot#1538]
I'm unable to get the optimizer to qualify columns that come from a CTE, for the root scope expression

**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark") - Dialect agnostic
- Check if the issue still exists on main - Yes

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

I added the following test-case to `tests/fixtures/optimizer/qualify_columns.sql`:
```sql
--------------------------------------
-- CTEs
--------------------------------------
WITH y2 AS (SELECT b, c from y) SELECT a, b FROM x JOIN y2 y3 ON x.c = y3.c;
WITH y2 AS (SELECT y.b AS b, y.c AS c FROM y AS y) SELECT x.a AS a, y3.b AS b FROM x  AS x JOIN y2 AS y3 ON x.c = y3.c;

```
...and verified that it failed when running:
```
pytest -vv tests/test_optimizer.py -k test_qualify_columns
```

The output seems to be:
```sql
E               sqlglot.errors.OptimizeError: Unknown column: c
```

**Official Documentation**
Please include links to official SQL documentation related to your issue. - N/A

**Comment by Sharadh** [comment]
FWIW, this fixture _does_ pass:
```sql
WITH y2 AS (SELECT b, c from y) SELECT a, b FROM x;
WITH y2 AS (SELECT y.b AS b, y.c AS c FROM y AS y) SELECT x.a AS a, x.b AS b FROM x AS x;
```

**Comment by barakalon** [comment]
`x.c` is the unknown column, not `y3.c`.

Check out the schema these tests use: https://github.com/tobymao/sqlglot/blob/main/tests/test_optimizer.py#L81
