### ISSUE TITLE
+ sign in comment throw ParseError for Oracle dialect

### ISSUE THREAD

**Issue by Pizzi95** [tobymao/sqlglot#1542]
If you try to parse the statement below it returns an Invalid expression / unexpected token error
`sql_query = """SELECT  column_name /*+ generic comment */ FROM table_name """
parsed = parse_one(sql_query, read='oracle')`

**Retrieve error**
![image](https://user-images.githubusercontent.com/30730327/236205821-e885d10b-ab64-42f9-9fcc-f06446bed435.png)

The + sign immediately following the opening of a comment (as above) returns Invalid expression

**Comment by GeorgeSittas** [comment]
Is this an Oracle hint? If not, why is there a + right after `*`? We treat `/*+` as a special hint token and it's only parseable after the `SELECT` token.

**Comment by Pizzi95** [comment]
Yes, in Oracle, "/*+" is a special syntax used to provide hints to the optimizer.
Sorry my sample sql_query could be misleading.

Some example could be:
- SELECT /*+ FULL(employees) */ * FROM employees;
- SELECT /*+PARALLEL(4)*/ column_name FROM table_name;

**Comment by GeorgeSittas** [comment]
Both these examples are parsed & generated correctly for Oracle:

```python
>>> sqlglot.transpile("SELECT /*+ FULL(employees) */  FROM employees", "oracle")
['SELECT /*+ FULL(employees) */ FROM employees']
>>> sqlglot.transpile("SELECT /*+ PARALLEL(4)*/  column_name FROM table_name", "oracle")
['SELECT /*+ PARALLEL(4) */ column_name FROM table_name']
```

The first example in the original post is not parseable because the hint is after the projection. Is that valid Oracle?

**Comment by GeorgeSittas** [comment]
Closing this as I don't think `SELECT DISTINCT /*+ PARALLEL(4) */ FROM table` is valid, at least according to Oracle's [documentation](https://user-images.githubusercontent.com/46752250/236273097-3383cb28-3b0a-4a60-99f2-35eb221749dc.png) («DELETE, INSERT, SELECT, and UPDATE are keywords that begin a statement block. Comments containing hints can appear only after these keywords»).

**Comment by Pizzi95** [comment]
It's seems like the hint is simply ignored by the optimizer but the query is executed. I mean, the hint is just ignored or threat as a simple comment but the query got executed without any problem

Below is a screenshot of a just executed query with this syntax
![Capture](https://user-images.githubusercontent.com/30730327/236410557-3a39c52b-5580-4125-9352-884c931dccb0.PNG)
