### ISSUE TITLE
CAST throw ParseError for Oracle dialect

### ISSUE THREAD

**Issue by Pizzi95** [tobymao/sqlglot#1543]
It seems that in oracle dialect it does not recogniye BINARZ_DOUBLE as a type and thow a ParseError.
If you try to parse the statement below it returns an Invalid expression / unexpected token error
`sql_query = "SELECT CAST(SUM(t0.column_name) AS BINARY_DOUBLE) FROM t0" `
`parsed = parse_one(sql_query , read='oracle')`

**Retrieved Error**
![image](https://user-images.githubusercontent.com/30730327/236212600-12590d49-858d-441f-8943-861169caf5fb.png)

More info about CAST in Oracle here: [Oracle Docs](https://docs.oracle.com/cd/E11882_01/server.112/e41084/functions023.htm#SQLRF00613)

**Comment by GeorgeSittas** [comment]
Can `BINARY_FLOAT` and `BINARY_DOUBLE` be mapped back to `FLOAT` and `DOUBLE`?

**Comment by Pizzi95** [comment]
Based on Oracle documentation it seems so, never tried
