### ISSUE TITLE
json access syntax between TrinoSQL and SparkSQL

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1544]
When translating a json object access from TrinoSQL to SparkSQL, sometimes the definition of the object access needs to be transformed.  For example,
This function in Trino SQL (read="trino")
```
json_extract_scalar(column, '$["property"]')
```
is translated to
```
get_json_object(dimensions, '$["property"]')
```

but SparkSQL only uses dot notation, so the second argument needs to be:
```
get_json_object(dimensions, '$.property')
```
**Fully reproducible code snippet**
```
>>> query = """select json_extract_scalar(column, '$["property"]') from table"""
>>> sqlglot.transpile(query, read="trino", write="spark")
['SELECT GET_JSON_OBJECT(column, \'$["property"]\') FROM table']
```
Expected result: 
```
['SELECT GET_JSON_OBJECT(column, \'$.property\') FROM table']
```
**Official Documentation**
https://trino.io/docs/current/functions/json.html#json-path-modes (trino supports both syntaxes)
https://docs.databricks.com/sql/language-manual/functions/get_json_object.html

**Comment by tobymao** [comment]
this is out of scope. it'd require having a json path parser. maybe one day... if someone is willing to implement a json path parser in pure python, i'll accept it.

for now i'd suggest that you write your queries in dot notation if you want them to be compatible, or you can do a custom transform

def transform(node):
   if isinstance(node, exp.JSONExtractScalar):
       ....

**Comment by georgesittas** [comment]
FYI @joshmarcus this is solved in the latest main branch:

```python
>>> import sqlglot
>>> print(sqlglot.transpile("""json_extract_scalar(column, '$["property"]')""", "trino", "spark")[0])
GET_JSON_OBJECT(column, '$.property')
```
