### ISSUE TITLE
json_format(to_json()) fails (trino -> spark)

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1547]
When translating SQL like `json_format(to_json(column))`  from read='trino' to write='spark', it's translated as:
`TO_JSON(TO_JSON(column))` which fails in SparkSQL, as TO_JSON doesn't accept the return type of TO_JSON.

```
query = "select json_format(to_json(column)) from table"
sqlglot.transpile(query, read="trino", write="spark")
```
returns
```
['SELECT TO_JSON(TO_JSON(column)) FROM table']
```
expected:
```
['SELECT TO_JSON(column) FROM table']
```

**Comment by joshmarcus** [comment]
Locally, I just drop `JSON_FORMAT()` instead of converting it to `TO_JSON()`.

**Comment by GeorgeSittas** [comment]
I can take a look soon, but it seems that `TO_JSON` is not in Trino's docs and indeed it throws an error for me:

```
trino> SELECT json_format(to_json('[1, 2, 3]'));
Query 20230504_171741_00002_uihyy failed: line 1:20: Function 'to_json' not registered
SELECT json_format(to_json('[1, 2, 3]'))
```

It works with `SELECT JSON_FORMAT(JSON '[1, 2, 3]')`, although it's not parsed correctly atm in SQLGlot.
