### ISSUE TITLE
presto to hive translator not translating ARRAY_JOIN which is not a function in hive

### ISSUE THREAD

**Issue by sarahsiedlecki** [tobymao/sqlglot#1558]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

ARRAY_JOIN is not being translated. the Hive function is CONCAT_WS

**Official Documentation**
Please include links to official SQL documentation related to your issue.

https://cwiki.apache.org/confluence/display/hive/languagemanual+udf

**Comment by tobymao** [comment]
@sarahsiedlecki are you sure this is right?concat_ws doens't work with arrays

**Comment by tobymao** [comment]
ah i found it now, please can you put more info in your issues so i don't have to dig?
