### ISSUE TITLE
presto to hive translator not correctly translating GROUP BY aliases

### ISSUE THREAD

**Issue by sarahsiedlecki** [tobymao/sqlglot#1559]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

in the presto to hive translator, this code
```
SELECT
  field_name,
  COUNT(id)
FROM tmp.table_name
GROUP BY
  1
```

should return 
```
SELECT
  field_name,
  COUNT(id)
FROM tmp.table_name
GROUP BY
  field_name
```

but instead it returns this 
```
SELECT
  field_name,
  COUNT(id)
FROM tmp.table_name
GROUP BY
  1
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
does hive not support group by 1?

**Comment by sarahsiedlecki** [comment]
didnt realize it was a configurable setting - that worked. if the typical default setting for this is off, it might still be nice to have the translator default to non aliased fields or include that setting in the translator.

**Comment by tobymao** [comment]
you can use the optimizer/qualify_columns to expand positional reference, so i'm not going to consider this in scope
