### ISSUE TITLE
BigQuery parsing produces incorrect AST for DATE_TRUNC where unit is WEEK(WEEKDAY)

### ISSUE THREAD

**Issue by pmsanford** [tobymao/sqlglot#1563]
I've tested this on the latest released version as well as on main and it is the same both places

**Fully reproducible code snippet**
```python
parse_one("DATE_TRUNC(tbl.col, WEEK(MONDAY))", read="bigquery").sql("bigquery")
# produces 'DATE_TRUNC(tbl.col, )'
```

**Official Documentation**
Here are the BigQuery docs for DATE_TRUNC showing `WEEK(WEEKDAY)` is a valid option: https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_trunc

I believe this happens because at this point: https://github.com/tobymao/sqlglot/blob/fb819f0d970417e86820f266c8aa10da05fcaa19/sqlglot/dialects/bigquery.py#L166 the return value of `seq_get(args, 1)` for a `WEEK` (or `QUARTER` or other date part) is an `exp.Column`, but `WEEK(MONDAY)` is an `exp.Week` (which of course doesn't have a `name` property). I hacked together the following custom dialect, which fixes the issue, but I'm guessing isn't going to cut it as a real fix:

```python
class NewBigquery(BigQuery):
    class Parser(BigQuery.Parser):
        FUNCTIONS = {
            **BigQuery.Parser.FUNCTIONS,
            "DATE_TRUNC": lambda args: exp.DateTrunc(
                unit=exp.Literal.string(seq_get(args, 1).sql()),  # type: ignore
                this=seq_get(args, 0),
                )
            }
```

I hacked around a little in bigquery.py to try and put together a PR but I wasn't able to quite figure out the right way to do it. I'm happy to contribute a PR if someone can point me in the right direction.

**Comment by tobymao** [comment]
thanks for the detailed report. i look forward to your future prs!
