### ISSUE TITLE
expressions.replace_tables() is wrongly replacing the CTE reference  

### ISSUE THREAD

**Issue by subhradip82** [tobymao/sqlglot#1577]
**My source query is :** with emp as (select * from emp) select * from emp
I am trying to replace the actual table i.e emp by dept using the following code 

t = expressions.replace_tables(parse_one("with emp as (select * from emp) select * from emp"), {"emp": "dept"})
print(t.sql())

**Expected result** : with emp as (select * from dept) select * from emp
**Actual result** : with emp AS (SELECT * FROM dept) SELECT * FROM dept

**Comment by tobymao** [comment]
this is not a bug, replace_tables replaces all references. if you want to do something custom, you need to do something a bit more sophisticated.
