### ISSUE TITLE
A valid ClickHouse `CREATE TABLE` gives ParseError

### ISSUE THREAD

**Issue by pkit** [tobymao/sqlglot#1578]
```
print(repr(parse_one("create table test (id UInt8) engine = AggregatingMergeTree() ORDER BY tuple()", read="clickhouse")))
```
```
Traceback (most recent call last):
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 65.
  create table test (data String) engine = AggregatingMergeTree() ORDER BY tuple()
```

```
$ echo "create table test (id UInt8) engine = AggregatingMergeTree() ORDER BY tuple()" | clickhouse-format 
CREATE TABLE test
(
    `id` UInt8
)
ENGINE = AggregatingMergeTree
ORDER BY tuple()
```

**Comment by tobymao** [comment]
Yes it is, albeit not the entire specification. My feedback to you would be to make the title of the issue relevant to the issue at hand.

**Comment by pkit** [comment]
@tobymao checking the code, looks like only `SELECT` is supported?

**Comment by pkit** [comment]
And looks like data-types are not checked for case too. AFAIK all CH data-types are case sensitive.

**Comment by tobymao** [comment]
i'm not sure how you came to that conclusion

https://github.com/tobymao/sqlglot/blob/main/tests/fixtures/identity.sql

**Comment by pkit** [comment]
These look generic. Clickhouse `create table` are invalid without `engine = ...`

**Comment by pkit** [comment]
Ok, I will check it further and do some PRs if needed. Thanks. Please don't close.

**Comment by tobymao** [comment]
i'm adding this now, no need for a pr.
