### ISSUE TITLE
Valid oracle sql can't be identified

### ISSUE THREAD

**Issue by RalfKow** [tobymao/sqlglot#1586]
**Description**
I have a valid oracle sql statement which I would like to transpile into snowflake sql. sql 

**Fully reproducible code snippet**
*Environement*
sqlglot = "12.2.0"
python = "3.8.13"

*Code snippet*
`import sqlglot

sql: str = """
create table DIM_AP_PRO_STOCK
(
    PK_AP_PRO_STOCK NUMBER(19) generated by default on null as identity (order nocache)
        constraint DIM_AP_PRO_STOCK_PK
            primary key,
    FK_STOCKWERK    NUMBER(19) not null
        constraint FK_DIM_AP_STOCKWERK
            references DIM_STOCKWERK,
    ANZAHL_AP       NUMBER(5),
    GUELTIG_VON     DATE,
    GUELTIG_BIS     DATE
);"""

result = sqlglot.transpile(sql, read="oracle", write="snowflake", identify=True, pretty=True)[0]

print(result)`

*Stack trace*
sqlglot.errors.ParseError: Required keyword: 'kind' missing for <class 'sqlglot.expressions.ColumnConstraint'>. Line 4, Col: 59.
  
create table DIM_AP_PRO_STOCK
(
    PK_AP_PRO_STOCK NUMBER(19) generated by default on null as identity (order nocache)
        constraint DIM_AP_PRO_STOCK_PK
            primary key,
    FK_

Process finished with exit code 1

**Official Documentation**
The sql has been verified on a oracle console and can be seen in https://www.oracletutorial.com/oracle-basics/oracle-identity-column/

**Comment by GeorgeSittas** [comment]
Hey, I'll take a look soon. Thanks for the report.

**Comment by GeorgeSittas** [comment]
Can you provide documentation on the `(order nocache)`? I can't find it in the link you sent or in Oracle's docs.
