### ISSUE TITLE
Oracle's STANDARD_HASH is missing

### ISSUE THREAD

**Issue by RobbertDM** [tobymao/sqlglot#1588]
**Fully reproducible code snippet**
```
sqlglot.parse_one("SELECT STANDARD_HASH('hello', 'SHA256') AS COL1", read="oracle")
```
yields an anonymous function for `standard_hash`.

**Official Documentation**
Please include links to official SQL documentation related to your issue.
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/STANDARD_HASH.html#GUID-4A68DACE-CFCF-443B-8651-B6CEAA7C4FD7

**Comment by GeorgeSittas** [comment]
@RobbertDM the documentation suggests that the method is a string. Can you please verify that your query works as is, i.e. without wrapping `sha256` in single quotes?

**Comment by RobbertDM** [comment]
@GeorgeSittas  Ah sorry, mistyped. The query is indeed with `'SHA256'` wrapped in single quotes.

**Comment by GeorgeSittas** [comment]
Great, thanks.
