### ISSUE TITLE
sqlglot doesn't parse UPDATE statement?

### ISSUE THREAD

**Issue by zeninpalm** [tobymao/sqlglot#16]
Hi Toby,

As far as I know, sqlglot doesn't support parsing the UPDATE statements yet, do you have a recent plan to support it?
Or, if you don't have such a plan, I would like to send an MR to support this 😄

**Comment by tobymao** [comment]
Sure, go for it! Thanks!

**Comment by zeninpalm** [comment]
Hi Toby,

Just submitted an MR to support parsing the UPDATE statement, please take a look at it and let me know if it is OK.

Thanks!

**Comment by tobymao** [comment]
Looks good, left a couple comments.

**Comment by zeninpalm** [comment]
Thanks for your kind comments, Toby. 
I've resolved them all, hope it works now 😄

**Comment by tobymao** [comment]
thanks!
