### ISSUE TITLE
Qualifying columns changes group by aliases to expressions, but keeps order by aliases

### ISSUE THREAD

**Issue by ibestvina** [tobymao/sqlglot#1613]
In some SQL dialects, such as BigQuery [1], if an alias from a SELECT list is used in the ORDER BY list, then it has to be used in the GROUP BY as well. Using the original expression instead does not work.

When optimizing code with 'qualify_columns', Sqlglot changes the GROUP BY alias for an expression, but keeps the ORDER BY alias, resulting in code that fails in BigQuery.

```py
import sqlglot
from sqlglot.optimizer.qualify_columns import qualify_columns
from sqlglot.optimizer.qualify_tables import qualify_tables
from sqlglot.optimizer.optimizer import optimize

query = """
SELECT
    c1 * 2 AS a1, 
    SUM(c2) AS a2,
FROM t1
GROUP BY a1
ORDER BY a1
"""

rules = [
    qualify_tables,
    qualify_columns,
]

parsed = sqlglot.parse_one(query, read="bigquery")
optimized = optimize(parsed, schema={'t1': {'c1': 'int', 'c2': 'int'}}, rules=rules)
opt_query = optimized.sql(dialect="bigquery", pretty=True)
print(opt_query)
```

Output:
```sql
SELECT
  t1.c1 * 2 AS a1,
  SUM(t1.c2) AS a2
FROM t1 AS t1
GROUP BY
  t1.c1 * 2
ORDER BY
  a1
```

Expected output:
```sql
SELECT
  t1.c1 * 2 AS a1,
  SUM(t1.c2) AS a2
FROM t1 AS t1
GROUP BY
  a1
ORDER BY
  a1
```

To be honest, I feel like I'm missing something obvious here and this is not actually an issue with Sqlglot, but I don't really know... I'm linking below some discussion on this as I found it more informative than the original docs (but docs are linked in the discussion as well).

[1] https://stackoverflow.com/questions/72809671/bigquery-giving-error-of-expression-not-grouped-by-when-order-by-is-included-in

**Comment by tobymao** [comment]
I think this is intentional. i ran this in postgres

```sql
with x as (select 1 a ) select a + 1 as b from x group by a + 1 order by b
```

and it's perfectly fine. the order by happens after the scopes of the group by. to get around this, run the optimizer with expand_alias_refs=False, and there won't be any replacements.

**Comment by ibestvina** [comment]
Thank you, that works!
