### ISSUE TITLE
BigQuery Table Quoting

### ISSUE THREAD

**Issue by AdeelK93** [tobymao/sqlglot#1616]
Hi, big fan of this library, and thanks for the quick fixes on issues I've raised in the past!

BigQuery quoting on a table can either be done for each part of the table identifier separately, or all-together. They are equivalent, but sqlglot treats them as distinct. This causes issues with working with schemas.

**Fully reproducible code snippet**
With separately quoting, you get the correct result.
```python
sqlglot.parse('select my_column from `my-project`.`my-dataset`.`my-table`', 'bigquery')
```
```
[(SELECT expressions: 
  (COLUMN this: 
    (IDENTIFIER this: my_column, quoted: False)), from: 
  (FROM expressions: 
    (TABLE this: 
      (IDENTIFIER this: my-table, quoted: True), db: 
      (IDENTIFIER this: my-dataset, quoted: True), catalog: 
      (IDENTIFIER this: my-project, quoted: True))))]
```
But most people quote the whole table identifier together, yielding a different TABLE.
```python
sqlglot.parse('select carry_through from `my-project.my-dataset.my-table`', 'bigquery')`
```
```
[(SELECT expressions: 
  (COLUMN this: 
    (IDENTIFIER this: carry_through, quoted: False)), from: 
  (FROM expressions: 
    (TABLE this: 
      (IDENTIFIER this: my-project.my-dataset.my-table, quoted: True))))]
```

**Official Documentation**
https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#quoted_identifiers

In the meanwhile, I'm using this below function to pre-process my BQ sql prior to sqlglot.
```python
import re

def replace_table_quoting(sql):
    pattern = r"`([^`]+)\.([^`]+)\.([^`]+)`"
    
    def replacer(match):
        project, dataset, table = match.group(1), match.group(2), match.group(3)
        return f"`{project}`.`{dataset}`.`{table}`"
    
    # Perform the substitution
    new_sql = re.sub(pattern, replacer, sql)
    
    return new_sql
```

**Comment by tobymao** [comment]
@AdeelK93 i read through the documentation, it doesn't show the syntax you're talking about 

if you do select `a.b` bigquery's documentation indicates the same behavior as sqlglot, that it would all be one identifier

**Comment by tobymao** [comment]
i'm going to close this for now as the documentation doesn't support what you're saying. but i may be misreading it, so if you could highlight the section that indicates that `db.table` is valid and parses as such we can reopen.

**Comment by AdeelK93** [comment]
Hi @tobymao - you're right, the documentation hardly makes this clear, but take a look at the "quoted identifiers"  and "table names" sections of [the link I shared](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#table_names). Or in the [query syntax documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax) you'll see that they use both styles interchangeably.

Here's screenshots too - it doesn't matter if project+dataset+table are each individually quoted, or quoted together.

<img width="1431" alt="image" src="https://github.com/tobymao/sqlglot/assets/16856016/4bacac4f-61f4-41e5-8159-950db85ffbae">
<img width="1428" alt="image" src="https://github.com/tobymao/sqlglot/assets/16856016/bc3bdb0a-fded-4d5f-81e1-a3c4f305eb46">

**Comment by tobymao** [comment]
how would you create a table called `x.y` with the period? so i want to make a table with the literal name x.y with the period?

**Comment by AdeelK93** [comment]
You're not allowed to have periods in the table name. [Source](https://cloud.google.com/bigquery/docs/tables#table_naming)

If I `CREATE TABLE X.Y` it'll create a table called Y in a dataset named X if it exists, the quoting does not escape or have any effects on periods.

**Comment by tobymao** [comment]
is this true for columns as well or just tables?

**Comment by tobymao** [comment]
this is pretty non-standard. 

instead of regex, you can run a custom transform

def explode_tables(node):
    if isinstance(node, exp.Table) and "." in node.name:
          return exp.to_table(node.name) 
   return node

expression.transform(explode_tables)

**Comment by AdeelK93** [comment]
It looks like you have to be consistent. If you quoted your table one way, you must work with columns the same way.

## For `bigquery-public-data.census_bureau_usa.population_by_zip_2010`

Fully qualified table name  + column works
<img width="1430" alt="image" src="https://github.com/tobymao/sqlglot/assets/16856016/3b4f6e15-78f2-4252-98a5-4a576e8948a3">

Just table name + column does not work
<img width="1427" alt="image" src="https://github.com/tobymao/sqlglot/assets/16856016/d8dcc6f1-841e-4470-8d05-c62ffed1d579">

## For `bigquery-public-data`.`census_bureau_usa`.`population_by_zip_2010`

Fully qualified table name + column does not work
<img width="1429" alt="image" src="https://github.com/tobymao/sqlglot/assets/16856016/bf401ded-dab6-4380-9cd0-7e6da5240602">

But just table name does work.
<img width="1417" alt="image" src="https://github.com/tobymao/sqlglot/assets/16856016/a2d7d835-5e1f-4b2a-995c-18f965444547">

So it looks like if you don't alias your table, but want to qualify the column, the automatic alias is the last quoted identifier of the table name (or full table name if it's all quoted)

**Comment by tobymao** [comment]
i'd suggest doing the transform for now which i've pasted above.

exploded out a single identifier into multiple at parse time is wonky

**Comment by AdeelK93** [comment]
Thanks - would you be open to re-opening this issue? Parsing SQL in general is wonky, but your library makes it possible 😄 

The idiomatic way of quoting in bigquery (`project.dataset.table`) is not fully compatible sqlglot, specifically in cases where you want to schema.add_table('`project.dataset.table`'). You instead need to schema.add_table('`project`.`dataset`.`table`') which sqlglot treats as a distinct table reference

**Comment by tobymao** [comment]
can you answer my question about columns?

can you do

`population_by_zip.zipcode` ?

**Comment by AdeelK93** [comment]
No you cannot. So I suppose that is a difference between table quoting and column quoting.

<img width="1433" alt="image" src="https://github.com/tobymao/sqlglot/assets/16856016/17df6591-72a3-437c-8c0f-a8aa32d5d63b">

**Comment by tobymao** [comment]
i don't understand how "`x.y`" is idiomatic, it's not even consistent within bigquery!

**Comment by tobymao** [comment]
a9731133

**Comment by AdeelK93** [comment]
Thank you @tobymao!!
