### ISSUE TITLE
Incorrect join parse?

### ISSUE THREAD

**Issue by pglass** [tobymao/sqlglot#1618]
Hi, I'm new to using this library so let me know if I've missed something.

I parsed the following query, an inner join of `a` and `b` cross joined with `c`

```sql
SELECT * FROM a JOIN b ON a.id = b.a_id, c
```

When parsed and printed back, I see that sqlglot returns the following, which reads differently than the original input. The inner join and cross join have swapped tables: `a` cross joined with the inner join of `b` and `c`.

```sql
SELECT * FROM a, c JOIN b ON a.id = b.a_id
```

The parse tree is the following, where I seemingly can't tell that `a` is joined with `b`. I would think the `JOIN` node in the tree should be nested under the `FROM` so that the join order is preserved (but I'm not an expert)

```
(SELECT expressions: 
  (STAR ), from: 
  (FROM expressions: 
    (TABLE this: 
      (IDENTIFIER this: a, quoted: False)), 
    (TABLE this: 
      (IDENTIFIER this: c, quoted: False))), joins: 
  (JOIN this: 
    (TABLE this: 
      (IDENTIFIER this: b, quoted: False)), on: 
    (EQ this: 
      (COLUMN this: 
        (IDENTIFIER this: id, quoted: False), table: 
        (IDENTIFIER this: a, quoted: False)), expression: 
      (COLUMN this: 
        (IDENTIFIER this: a_id, quoted: False), table: 
        (IDENTIFIER this: b, quoted: False)))))
```

**Before you file an issue**
- [x] Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- [x] Check if the issue still exists on main 

**Fully reproducible code snippet**

I added a similar query in the following example for comparison. I used the postgres dialect here (but the behavior is at least the same for sqlite).

```python
from sqlglot import parse_one

p1 = parse_one('SELECT * FROM a, b JOIN c ON b.id = c.b_id', read="postgres")
p2 = parse_one('SELECT * FROM a JOIN b ON a.id = b.a_id, c', read="postgres")

print(repr(p1))
print(repr(p2))

print(p1)
print(p2)
```

The output is the following: 

<details>
  <summary>Output (click to expand) </summary>

```
(SELECT expressions: 
  (STAR ), from: 
  (FROM expressions: 
    (TABLE this: 
      (IDENTIFIER this: a, quoted: False)), 
    (TABLE this: 
      (IDENTIFIER this: b, quoted: False))), joins: 
  (JOIN this: 
    (TABLE this: 
      (IDENTIFIER this: c, quoted: False)), on: 
    (EQ this: 
      (COLUMN this: 
        (IDENTIFIER this: id, quoted: False), table: 
        (IDENTIFIER this: b, quoted: False)), expression: 
      (COLUMN this: 
        (IDENTIFIER this: b_id, quoted: False), table: 
        (IDENTIFIER this: c, quoted: False)))))
(SELECT expressions: 
  (STAR ), from: 
  (FROM expressions: 
    (TABLE this: 
      (IDENTIFIER this: a, quoted: False)), 
    (TABLE this: 
      (IDENTIFIER this: c, quoted: False))), joins: 
  (JOIN this: 
    (TABLE this: 
      (IDENTIFIER this: b, quoted: False)), on: 
    (EQ this: 
      (COLUMN this: 
        (IDENTIFIER this: id, quoted: False), table: 
        (IDENTIFIER this: a, quoted: False)), expression: 
      (COLUMN this: 
        (IDENTIFIER this: a_id, quoted: False), table: 
        (IDENTIFIER this: b, quoted: False)))))
SELECT * FROM a, b JOIN c ON b.id = c.b_id
SELECT * FROM a, c JOIN b ON a.id = b.a_id
```
</details>

**Official Documentation**

* Postgres docs: https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-FROM
  * "If more than one table reference is listed in the FROM clause, the tables are cross-joined" (so `FROM a, b` is a cross join of `a` and `b`)
  * "Joins of all types can be chained together, or nested: either or both T1 and T2 can be joined tables. Parentheses can be used around JOIN clauses to control the join order. In the absence of parentheses, JOIN clauses nest left-to-right."
* Sqlite docs: https://www.sqlite.org/lang_select.html
  * Mainly, the flow chart shows that JOIN clauses nest under a FROM in the syntax tree

**Comment by tobymao** [comment]
i think the queries are identical semantically. sqglot parses sql into its canonical form. if you want to preserve the order, you can explicitly cross join.

**Comment by tobymao** [comment]
an alternative is that we could parse c into explicit cross joins

**Comment by GeorgeSittas** [comment]
Maybe that makes sense in order to ensure we'll always have a single expression in `from`? I think that it's going to improve the optimizer as well, because having the invariant that the length of `from.expressions` is always 1 means we won't have to deal with the old join style at all.

**Comment by pglass** [comment]
Hi, thanks for the quick response! 🙂 

For Postgres at least, the two queries aren't equivalent. Here is a SQLFiddle example: http://sqlfiddle.com/#!15/d59a5/1

The second query (`SELECT * FROM a, c JOIN b ON a.id = b.a_id;`) returns `ERROR: invalid reference to FROM-clause entry for table "a" Hint: There is an entry for table "a", but it cannot be referenced from this part of the query. Position: 32`

**Comment by tobymao** [comment]
@GeorgeSittas we expand multiple froms

**Comment by tobymao** [comment]
> Hi, thanks for the quick response! 🙂
> 
> For Postgres at least, the two queries aren't equivalent. Here is a SQLFiddle example: http://sqlfiddle.com/#!15/d59a5/1
> 
> The second query (`SELECT * FROM a, c JOIN b ON a.id = b.a_id;`) returns `ERROR: invalid reference to FROM-clause entry for table "a" Hint: There is an entry for table "a", but it cannot be referenced from this part of the query. Position: 32`

can you explain why it’s failing isn’t it just from a cross join c join b?

**Comment by pglass** [comment]
I'm not sure actually. It seems like these two queries are parsed differently in postgres:

1. `SELECT * FROM a, c JOIN b ON a.id = b.a_id;` (errors)
2. `SELECT * FROM a CROSS JOIN c JOIN b ON a.id = b.a_id;` (OK, though column ordering has changed from my original query)

(1) seems to parse something like this: `SELECT * FROM a, (c JOIN b ON a.id = b.a_id);`

**Comment by GeorgeSittas** [comment]
Maybe postgres treats the first query as ambiguous, because the relative precedence of `,` with respect to `JOIN` is not well-defined? It could be interpreted as either `(a, c) JOIN b` or `a, (c JOIN b)`.

**Comment by pglass** [comment]
FWIW, I did try this on a recent version of Postgres (15.3) which is the same.

> if you want to preserve the order, you can explicitly cross join.

I also think this solution is fine, if postgres seems like the odd one out among all the databases sqlglot supports. SQLite has no issue with this, query, for example.

**Comment by tobymao** [comment]
i will solve this by expanding all joins to cross joins
