### ISSUE TITLE
Observations with TPCH optimizations

### ISSUE THREAD

**Issue by marsupialtail** [tobymao/sqlglot#162]
1. handling independent/correlated subqueries with IN and NOT IN. The former can be converted into a left join while the latter can be converted into an anti join, (16, 18)
2. decorrelate independent subqueries in the WHERE or HAVING clause general into a tempscan, (11, 15)
3. does SQLGlot support left outer join vs left join (13)
4. Predicate pushdown fails for query 2, 8, 9 in the subquery? (part.p_name LIKE green not pushed down, part.p_type predicate not pushed down) for some reason it all has to do with the part table
5. Potential groupby simplication for 7,8,9 where you groupby on a projection to flatten the query.

**Comment by tobymao** [comment]
there's no difference between left outer join and left join, the outer is unnecessary

**Comment by marsupialtail** [comment]
subquery elimination can be improved for queries 2 and 11.

**Comment by tobymao** [comment]
closing for now
