### ISSUE TITLE
SparkSQL: TABLESAMPLE with aliased `database.table_name` fails

### ISSUE THREAD

**Issue by CDonnerer** [tobymao/sqlglot#1629]
**Fully reproducible code snippet**

1/ using `transpile`:

```python
import sqlglot

query = "SELECT * FROM my_database.my_table TABLESAMPLE (1 PERCENT) foo"
sqlglot.transpile(query, read="spark")
```
```python
SELECT * FROM my_table TABLESAMPLE (1 PERCENT) AS foo
```
here `my_database` is missing, expected:
```python
SELECT * FROM my_database.my_table TABLESAMPLE (1 PERCENT) AS foo
```

2/ using `parse_one`:
```python
import sqlglot

query = "SELECT * FROM my_database.my_table TABLESAMPLE (1 PERCENT) foo"
sqlglot.parse_one(query, read="spark")
```
```python
SELECT * FROM my_database.my_table AS foo TABLESAMPLE (1 PERCENT)
```
here the alias is misplaced, expected:
```python
SELECT * FROM my_database.my_table TABLESAMPLE (1 PERCENT) AS foo
```

**Official Documentation**

https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-sampling.html

See also here for example snippets https://github.com/sqlfluff/sqlfluff/blob/main/test/fixtures/dialects/hive/select_sampling_table.sql

**Comment by tobymao** [comment]
in the second case, this is expected because you didn't specify an output dialect, try it with sql(dialect="spark")

**Comment by CDonnerer** [comment]
Awesome, thanks a lot for the super quick fix!
