### ISSUE TITLE
APPROX_COUNT_DISTINCT and ANY_VALUE

### ISSUE THREAD

**Issue by ewjoachim** [tobymao/sqlglot#1633]
There are at least 2 (unrelated) functions that exist in BigQuery and have equivalents in ClickHouse: `ANY_VALUE()` is `any()` (note: exclusively lower case, `ANY` won't work) and `APPROX_COUNT_DISTINCT` is `uniq()` (note: same)

**Official Documentation**
- https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#any_value
- https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#approx_count_distinct
- https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/any
- https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/uniq#agg_function-uniq

Sqlglot completely ignores this:
```python
>>> sqlglot.transpile(
...     "SELECT APPROX_COUNT_DISTINCT(x) FROM (SELECT ANY_VALUE(y) x FROM (SELECT 1 y))",
...     read="bigquery",
...     write="clickhouse"
... )[0]
'SELECT APPROX_COUNT_DISTINCT(x) FROM (SELECT ANY_VALUE(y) AS x FROM (SELECT 1 AS y))'
```
(I've put the 2 in the same query, but those are 2 close but unrelated issues)

I'm pretty sure there are a ton of other things that are done differently, and not sure if the issue is in the parsing from bigquery dialect or dumping into clickhouse dialect (though I imagine it's the 2nd one).

What would be the best course of action ?

**Comment by ewjoachim** [comment]
I'm getting somewhere with:
```python
from sqlglot.dialects.bigquery import BigQuery
from sqlglot.dialects.clickhouse import ClickHouse
from sqlglot.dialects.dialect import rename_func
from sqlglot.helper import seq_get

class WorkingClickHouse(ClickHouse):
    class Generator(ClickHouse.Generator):
        TRANSFORMS = {
            **ClickHouse.Generator.TRANSFORMS,
            sqlglot.exp.AnyValue: rename_func("any"),
            sqlglot.exp.ApproxDistinct: rename_func("uniq")
        }
        
class WorkingBigQuery(BigQuery):
    class Parser(BigQuery.Parser):
        FUNCTIONS = {
            **BigQuery.Parser.FUNCTIONS,
            "APPROX_COUNT_DISTINCT": lambda args: sqlglot.exp.ApproxDistinct(this=seq_get(args, 0))
        }
```
so I believe this would pave the way for the PR we'd do to fix that, though I guess there may be quite a few other functions (also, those cases were really simple with nothing to change in the arguments)

**Comment by GeorgeSittas** [comment]
@ewjoachim take a look at the PR, your assumptions were mostly right. It was both a matter of translating the AST nodes correctly for Clickhouse and parsing the `APPROX_COUNT_DISTINCT` function correctly.

**Comment by GeorgeSittas** [comment]
Feel free to open up PRs for issues like this in the future, we'll be happy to guide you through a solution.
