### ISSUE TITLE
Support for more locking options

### ISSUE THREAD

**Issue by mpf82** [tobymao/sqlglot#1641]
sqlglot currently support ``SELECT ... FOR UPDATE`` and ``SELECT ... FOR SHARE``. 

However, the ``FOR ...`` can be more complex:

MySQL - https://dev.mysql.com/doc/refman/8.0/en/select.html

```
SELECT
    ...
    [FOR {UPDATE | SHARE}
        [OF tbl_name [, tbl_name] ...]
        [NOWAIT | SKIP LOCKED]
      | LOCK IN SHARE MODE]
```

Oracle - https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/SELECT.html

![for_update_clause 1](https://github.com/tobymao/sqlglot/assets/10152404/899dd28c-b72b-4b43-9903-73842bd95037)

Informix - https://www.ibm.com/docs/en/informix-servers/12.10?topic=statement-update-clause

```
|--------FOR UPDATE--+----------------+-------------------------|
                     |     .-,------. |   
                     |     V        | |   
                     '-OF----column-+-'   
```

MariaDB - https://mariadb.com/kb/en/select/ 

```
SELECT
    ...
      [FOR UPDATE lock_option | LOCK IN SHARE MODE lock_option]

lock_option:
    [WAIT n | NOWAIT | SKIP LOCKED]
```

**Comment by GeorgeSittas** [comment]
I'll take a look
