### ISSUE TITLE
Redshift UNLOAD statement query/options

### ISSUE THREAD

**Issue by DanCardin** [tobymao/sqlglot#1655]
**Is your feature request related to a problem? Please describe.**
`sqlglot.parse_one("UNLOAD ('select 1') TO 's3://dest' WITH CREDENTIALS '...'", read='redshift')` parses into an `UNLOAD` command, whose expression is the whole rest of the statement

**Describe the solution you'd like**
Ideally it would segment out the rest of the the portions of the statement such that the select statement, the credentials, and the statement options could be inspected/enumerated

**Describe alternatives you've considered**
Manually parsing the fields out myself 😬. Handling things like `PARTITION BY (foo)` or `REGION [AS] 'region'` versus parameters that have no options.

I **did** some looking into how i might contribute to sqlglot in order to implement this, but relatively quickly got lost. Is there's some existing analogue of what I'm asking for here (idk...like...postgres grant statements or something similarly complicated), that might already exist as a reference?

**Comment by tobymao** [comment]
you could check out _parse_load_data, it handles things like

```sql
LOAD DATA LOCAL INPATH 'x' INTO TABLE y PARTITION(ds = 'yyyy') INPUTFORMAT 'y' SERDE 'z'
```

which is probably similar

happy to accept a PR, but have no plans to implement this. or if you're looking for prioritized happy to chat about it on our slack channel.
