### ISSUE TITLE
INTERVAL as a column name fails as SparkSQL

### ISSUE THREAD

**Issue by joshmarcus** [tobymao/sqlglot#1664]
I'm translating from Trino to SparkSQL, and a query fails because INTERVAL is a column name of the table.  I'm generating SQL with `identify=False,  # Don't quote identifiers unless explicitly quoted` as otherwise the SQL looks too artificial -- is it in scope to have required keywords quoted?

**Comment by GeorgeSittas** [comment]
Can you show a minimal example that's failing?

**Comment by tobymao** [comment]
@joshmarcus, while we appreciate that you're taking the time to file issues, please follow the issue guide and show completely reproducible examples and their expected behavior.

**Comment by tobymao** [comment]
my guess is that you're doing

```python 

from sqlglot import parse_one

parse_one("select interval", read="presto")
```

in this case interval is an interval type and gets translated as such, if you want this to be safe across dialects, you should quote it

closing as not planned for now
