### ISSUE TITLE
Wrong PostgreSQL interval

### ISSUE THREAD

**Issue by alippai** [tobymao/sqlglot#1667]
```shell
python3 -m sqlglot --read postgres --write postgres "select interval '1.5 hours'"
```
Gives:
```SQL
SELECT
  INTERVAL '1.5' hour
```
However `INTERVAL '1.5' hour` is different from `INTERVAL '1.5 hours'` as the former is evaluated as 60 minutes and the latter is 90 minutes.

sqlglot version:
```python
import sqlglot
sqlglot.__version__  #'12.2.0'
```
PostgreSQL version: `12.2`

**Comment by GeorgeSittas** [comment]
This was fixed in https://github.com/tobymao/sqlglot/commit/6f9d531ea7ea31e7e5b0f0ac879f43a2bdb8a3ad, should be available in v13.3.0
