### ISSUE TITLE
TPCH-22 not correct

### ISSUE THREAD

**Issue by marsupialtail** [tobymao/sqlglot#167]
TPCH-22 optimizer produces wrong tree.
In particular the predicate
c_acctbal > (
                                select
                                        avg(c_acctbal)
                                from
                                        customer
                                where
                                        c_acctbal > 0.00
                                        and substring(c_phone ,1,2) in
                                                ('13', '31', '23', '29', '30', '18', '17')
                        )
is ignored

**Comment by tobymao** [comment]
this is still ignored beacuse there's no way to optimize this, it returns a singular number
