### ISSUE TITLE
POstgresql named placeholder isn't parsed

### ISSUE THREAD

**Issue by luanpontes100** [tobymao/sqlglot#1672]
When I try to parse this sql with a two forms of placeholder in postgresql
```python
import sqlglot
select = sqlglot.parse_one("SELECT * FROM t1 where id = %(id)s", read=sqlglot.Dialects.POSTGRES)
print(select)
```
```python
import sqlglot
select = sqlglot.parse_one("SELECT * FROM t1 where id = %s", read=sqlglot.Dialects.POSTGRES)
print(select)
```

I get the error
```python
sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.Mod'>. Line 1, Col: 35.
  SELECT * FROM t1 where id = %(id)s
```

The python DB API 2.0 defines this placeholders as valid https://peps.python.org/pep-0249/#paramstyle

**Comment by GeorgeSittas** [comment]
If I understand correctly, both of these syntax forms aren't part of postgres' SQL dialect, so it's out of scope to add support for them (cc: @tobymao).

Check the following discussion for more context on how to overcome this issue: https://github.com/tobymao/sqlglot/issues/338.
