### ISSUE TITLE
Failing to parse some CREATE TABLE statements with generated columns

### ISSUE THREAD

**Issue by bholzer** [tobymao/sqlglot#1681]
I am trying to parse table create statements used for Databricks, and they include generated columns. The example query from the [Databricks documentation](https://docs.databricks.com/delta/generated-columns.html) fails:

```python
import sqlglot

q = """
CREATE TABLE default.people10m (
  id INT,
  firstName STRING,
  middleName STRING,
  lastName STRING,
  gender STRING,
  birthDate TIMESTAMP,
  dateOfBirth DATE GENERATED ALWAYS AS (CAST(birthDate AS DATE)),
  ssn STRING,
  salary INT
)
"""

sqlglot.parse_one(q, read="databricks")
```

`sqlglot.errors.ParseError: Expecting )` on the `AS` of `GENERATED ALWAYS AS`

**Comment by GeorgeSittas** [comment]
Thanks for the report, will take a look soon

**Comment by bholzer** [comment]
Big thanks, impressive turnaround here 👍
