### ISSUE TITLE
Valid ClickHouse expression fails to parse

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#1690]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark"): **See the code snippet below**
- Check if the issue still exists on main: **Tried against `main`, still exists**

**Fully reproducible code snippet**

Successful clickhouse fiddle query:
https://fiddle.clickhouse.com/604acdad-bbe4-4226-97ae-5e825aa79db2

Failing sqlglot snippet:

```
In [3]: import sqlglot as sg

In [4]: sg.__version__
Out[4]: '14.0.0'

In [5]: sg.parse_one("SELECT CAST(tuple(1 as `a`, 2 as `b`, 3.0 as `c`).2 AS Nullable(
   ...: String))", read="clickhouse")
```

**Official Documentation**

I'm not sure what "official SQL documentation" means 😅.

**Comment by cpcloud** [comment]
This used to work before 14.0.0, if that helps.

**Comment by cpcloud** [comment]
This isn't a blocker for us in ibis, it turned out that we don't actually need to generate the `as` bits, just wanted to flag this as a bug.

**Comment by GeorgeSittas** [comment]
Hey @cpcloud, I'm already looking into this. We saw the ibis CI failure 😅 .

Thanks for the report!
