### ISSUE TITLE
BigQuery raw string support has regressed

### ISSUE THREAD

**Issue by pmsanford** [tobymao/sqlglot#1691]
This issue is present on the current release and on main.

In the following:
```
>>> q = "SELECT r'\s'"
>>> print(sqlglot.parse_one(q, "bigquery").sql("bigquery"))
SELECT '\s'
```

`SELECT r'\s'` is not the same as `SELECT '\s'` - the `r` prefix indicates the following is a "raw string," mostly used in REGEXP_REPLACE/REGEXP_EXTRACT ([the docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical) say it is also referred to as a "regex string")

It looks like this was addressed in  #218, but it appears to have regressed in https://github.com/tobymao/sqlglot/commit/d2377e04eacdb1e9793d77629baa9c0a751fd50c

The test [here in test_bigquery.py](https://github.com/tobymao/sqlglot/blob/eb6eaf5340bb7001e047583dc53735b54612c860/tests/dialects/test_bigquery.py#L110) is now incorrect:
```
        self.validate_all(
            r'R"""/\*.*\*/"""',
            write={
                "bigquery": r"'/\*.*\*/'",
                "duckdb": r"'/\*.*\*/'",
                "presto": r"'/\*.*\*/'",
                "hive": r"'/\*.*\*/'",
                "spark": r"'/\*.*\*/'",
            },
        )
```
The query string `R"""/\*.*\*/"""` starts with `R"`, so if the leading R is removed, all the backslashes in the resulting strings should be double escaped.

I'm working on wrapping my head around the tokenizer to see if I can fix this, but I thought I'd post an issue in the interim in case I'm called away from working on this before I can get to a PR.

**Fully reproducible code snippet**
`assert sqlglot.parse_one(r"SELECT r'\s'", "bigquery").sql("bigquery") == r"SELECT '\\s'"`

**Official Documentation**
https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#quoted_literals

**Comment by GeorgeSittas** [comment]
I can take a look shortly, thanks for the report.

**Comment by pmsanford** [comment]
Here's a possible fix:
https://github.com/pmsanford/sqlglot/commit/653d6abaed51a05aa6cdd7154b6f95290db68722

It feels a little clunky to me though

**Comment by tobymao** [comment]
i'm working on something @pmsanford appreciate the attempt
