### ISSUE TITLE
snowflake object_construct is converted to duckdb map with values of single type

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#1699]
In Snowflake, [OBJECT_CONSTRUCT](https://docs.snowflake.com/en/sql-reference/functions/object_construct) can be used to construct an object from the given key-value pairs. Keys must be strings, but values can be any type and can differ from each other.

When converting OBJECT_CONSTRUCT to duckdb, it ends up as a [map](https://duckdb.org/docs/sql/data_types/map). Maps must have a single type for all keys, and a **single** type for **all** values.

eg:

```python
sqlglot.parse_one("SELECT OBJECT_CONSTRUCT('a',1,'b','BBBB', 'c',null)", read="snowflake").sql(dialect="duckdb")

"SELECT MAP(LIST_VALUE('a', 'b', 'c'), LIST_VALUE(1, 'BBBB', NULL))"
```

Because the map/list must be of the same type, in this example the integer `1` becomes the string `"1"` when the expression is executed in duckdb:

```
D SELECT to_json(MAP(LIST_VALUE('a', 'b', 'c'), LIST_VALUE(1, 'BBBB', NULL)));
┌──────────────────────────────────────────────────────────────────────┐
│ to_json(map(list_value('a', 'b', 'c'), list_value(1, 'BBBB', NULL))) │
│                                 json                                 │
├──────────────────────────────────────────────────────────────────────┤
│ {"a":"1","b":"BBBB","c":null}                                        │
└──────────────────────────────────────────────────────────────────────┘
```
NB: `to_json` is used here to show that the value for the`a` key is a string.

**Comment by pkit** [comment]
Yup, struct should behave as needed, I think. As `struct` is the only type (besides `list`) that can contain other structs.
And in Snowflake `OBJECT` can contain other objects too.

**Comment by GeorgeSittas** [comment]
Ok, thanks for confirming. I'll look into this a bit closer and try to get a fix on Monday.
