### ISSUE TITLE
Microsoft SQL SINGLE QUOTED IDENTIFIER

### ISSUE THREAD

**Issue by ams1** [tobymao/sqlglot#1728]
First of all: amazing work, THANK YOU!

**Fully reproducible code snippet**
When I run (NOTE that the col alias uses SINGLE quotes which are allowed in MSSQL):
```py
from sqlglot import parse_one

expression_tree = parse_one("select x.id, sum(x.cola) 'col_alias' from tbl1 x group by x.id")
```
I get:
Invalid expression/ Unexpected token

Am I missing something/any workarrounds?

Again, THANK YOU so much.

**Comment by GeorgeSittas** [comment]
Hello, thanks for the kind words.

Can you please link any related documentation that demonstrates the usage of `'` as identifier delimiters?

**Comment by GeorgeSittas** [comment]
I'll go ahead and close this as not planned, as I can't find something in MSSQL's [docs](https://learn.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms176027(v=sql.105)?redirectedfrom=MSDN) that suggests this is allowed (or has the intended semantics). There's also the following section:

«When QUOTED_IDENTIFIER is set to ON, SQL Server follows the ISO rules for the use of double quotation marks (")and the single quotation mark (') in SQL statements. For example:

* Double quotation marks can be used only to delimit identifiers. They cannot be used to delimit character strings.

* To maintain compatibility with existing applications, SQL Server does not fully enforce this rule. Character strings can be enclosed in double quotation marks if the string does not exceed the length of an identifier. We do not recommend this practice.

* Single quotation marks must be used to enclose character strings. They cannot be used to delimit identifiers.»

This suggests that the standard way is to use `""` for delimited identifiers and `''` for strings.
