### ISSUE TITLE
Can not convert '||' from redshift to presto/trino when the arguments are not string typed

### ISSUE THREAD

**Issue by pangyifish** [tobymao/sqlglot#1735]
```
sql = """
select 'a' || 1 || 1.1
"""
converted_sql = sqlglot.transpile(sql, read="redshift", write="trino")[0]
print(converted_sql)
```
```
SELECT 'a' || 1 || 1.1

```

Trino would throw error `Unexpected parameters (varchar(1), integer) for function concat. Expected: concat(char(x), char(y)), concat(array(E), E) E, concat(E, array(E)) E, concat(array(E)) E, concat(varchar), concat(varbinary)'` when executing the output SQL, as Trino doesn't covert the type implicitly like Redshift does.

**Comment by GeorgeSittas** [comment]
I don't think this can be done without type annotations, because you could also have `'a' || x`. So for the transpilation to be correct you need to know the type of `x`.

**Comment by pangyifish** [comment]
There are some other issues also caused by Redshift implicit type converting.. such as 
```

sql = """
select a from (select '1' as a) 
where a = 1

"""
```
and 

```
sql = """
select a from (select 1 as a) 
where a = '1'

"""
```
the converted SQL does not works in Trino due to `Cannot apply operator: varchar(1) = integer`

**Comment by GeorgeSittas** [comment]
Yep, I think this is out of scope for now, similar to https://github.com/tobymao/sqlglot/issues/1736#issuecomment-1579567236.

**Comment by GeorgeSittas** [comment]
fyi, when I say "this" I meant your last comment -- currently working on a fix for the `||` issue.

**Comment by pkit** [comment]
I'm not sure what's the stance on "sqlglot is not a validator" here?
In my book, type inference is validation.
So, are we validating some cases and not the others? :)

**Comment by GeorgeSittas** [comment]
The rule of thumb is that we don't validate _syntax_, so that SQLGlot is as lenient as possible. I think there's no point in being strict when it comes to syntax when SQLGlot aims to be as universal as possible.

However, changes like the ones discussed in this thread are fine; the goal is to improve transpilation across dialects. Although these are also done in a best-effort manner, because it's not always trivial to implement them.

**Comment by pkit** [comment]
Yeah, makes sense. But transpilation can be hard to do if you're lenient, i.e. "garbage in - garbage out" rule...

**Comment by GeorgeSittas** [comment]
That's right, and so one core assumption in SQLGlot is that it won't deal with "garbage" input, with respect to the dialect of interest. If a user tries to transpile syntactically-invalid SQL, that's on them.
