### ISSUE TITLE
Cannot convert IN function from Redshift to Trino when IN value and list items are not the same type

### ISSUE THREAD

**Issue by pangyifish** [tobymao/sqlglot#1736]
```
sql = """
select a from (select 1 as a) 
where a in ('1', 2, 3)

"""
converted_sql = sqlglot.transpile(sql, read="redshift", write="trino")[0]
print(converted_sql)

select a from (select 1 as a) 
where a in ('1', 2, 3)

```
Trino error:
`IN value and list items must be the same type or coercible to a common type. Cannot find common type between integer and varchar(1), all types (without duplicates): [integer, varchar(1)]',`

**Comment by tobymao** [comment]
This is really poorly written in SQL, I don't think we're going to support this particular transpilation. Either fix your SQL or use a sqlglot custom transform to cast IN expressions to the same type.
