### ISSUE TITLE
Cannot convert Redshift syntax '2018-01-01' + 1 to Trino

### ISSUE THREAD

**Issue by pangyifish** [tobymao/sqlglot#1743]
```
sql = "select dt from (select '2018-01-02' as dt) where dt = '2018-01-01' + 1"
print(list(a.redshift.query(sql)))

converted_sql = sqlglot.transpile(sql, read="redshift", write="trino")[0]
print(converted_sql)
```

`SELECT dt FROM (SELECT '2018-01-02' AS dt) WHERE dt = '2018-01-01' + 1
`
This may not be easy to fix, but if possible, the converted SQL could be:
`WHERE CAST(dt AS timestamp) = DATE_ADD('day', 1, CAST('2018-01-01' AS timestamp))`

**Comment by tobymao** [comment]
this is out of scope, you should fix the upstream redshift sql to be more portable
