### ISSUE TITLE
Type error when converting datediff from redshift to trino 

### ISSUE THREAD

**Issue by pangyifish** [tobymao/sqlglot#1745]
```
sql = "select datediff(week,'2009-01-01','2009-12-31')"
converted_sql = sqlglot.transpile(sql, read="redshift", write="trino")[0]
print(converted_sql)
SELECT DATE_DIFF('week', '2009-01-01', '2009-12-31')
```

Trino error: `Unexpected parameters (varchar(4), varchar(10), varchar(10)) for function date_diff. Expected: date_diff(varchar(x), date, date), date_diff(varchar(x), timestamp(p), timestamp(p)), date_diff(varchar(x), timestamp(p) with time zone, timestamp(p) with time zone), date_diff(varchar(x), time(p), time(p)), date_diff(varchar(x), time(p) with time zone, time(p) with time zone)'
`

Changing the SQL to `SELECT DATE_DIFF('week', DATE'2009-01-01', DATE'2009-12-31')` works in Trino

https://trino.io/docs/current/functions/datetime.html

**Comment by tobymao** [comment]
feel free to start making prs

**Comment by pangyifish** [comment]
> feel free to start making prs

Sure, thanks!


+DATEADD function has the same issue

**Comment by tobymao** [comment]
we’ll address both , use these at examples for future issues

**Comment by tobymao** [comment]
also would be great if you joined or slack so we can help out with prs

tobikodata.com/slack

**Comment by pangyifish** [comment]
> 

Sure, joined already!
