### ISSUE TITLE
clickhouse: ON CLUSTER is not supported

### ISSUE THREAD

**Issue by pkit** [tobymao/sqlglot#1747]
see https://clickhouse.com/docs/en/sql-reference/distributed-ddl

I can implement this one, but I'm not sure about design.
On one hand it's a CH specific feature that has no usage otherwise.
On the other hand it's really similar to Teradata "properties before schema" feature, which is not sub-classed.
Any ideas?
Just add it to the main parser?

**Comment by GeorgeSittas** [comment]
I think you can implement this as a "post create" property, right?

**Comment by pkit** [comment]
I think it's simpler than that.
Current handling of the "CLUSTER" keyword is not clashing with CH-specific stuff.
But adding a new CH-specific stuff [here](https://github.com/tobymao/sqlglot/blob/bb1f1a035c8701c881f61c65742331cf7e667260/sqlglot/parser.py#L1180) feels wrong.

https://github.com/tobymao/sqlglot/blob/bb1f1a035c8701c881f61c65742331cf7e667260/sqlglot/parser.py#L1177-L1185

**Comment by GeorgeSittas** [comment]
What would you add there? I'd rather we don't complicate the `_parse_create` method any more than it already is if there's an alternative way to do it.

**Comment by pkit** [comment]
> What would you add there?

Something like:
```
     # exp.Properties.Location.POST_NAME 
     if self._match(TokenType.ON):
          temp_properties = self._parse_on_cluster_prop()
```

**Comment by tobymao** [comment]
can't you just put "ON" in property parsers and then check for cluster? we already have a parse_on_property

**Comment by pkit** [comment]
@tobymao there is no comma, and props are launched on: `if self._match(TokenType.COMMA): `

**Comment by tobymao** [comment]
if you can get rid of the if statement

**Comment by tobymao** [comment]
maybe just in terradata add the comma in generator
