### ISSUE TITLE
Formatting with long condition chain in `CASE`

### ISSUE THREAD

**Issue by TrebledJ** [tobymao/sqlglot#175]
Hi, this is a feature request. I have an SQL query resembling 

```
SELECT
a, 
CASE WHEN a = 1 OR a = 4 OR (a > 6 AND a < 10) OR a % 21 = 1 OR a = 124908 or a = 49876512 or a = 1097589162340 or a = 120498105 or a = 222229929 THEN 'Yes'
ELSE 'No'
END
FROM fruits
```

Even though I specify `pretty=True`, the formatted result is:

```
SELECT
  a,
  CASE
    WHEN a = 1 OR a = 4 OR (a > 6 AND a < 10) OR a % 21 = 1 OR a = 124908 OR a = 49876512 OR a = 1097589162340 OR a = 120498105 OR a = 222229929 
THEN 'Yes'
    ELSE 'No'
  END
FROM fruits
```
Here I would like the condition to break into several lines rather than have one massive line.

Is it possible to customise the formatting in this case?

**Comment by tobymao** [comment]
this would be possible now since sqlglot has better understanding of predicates would need to figure out the formatting rule for this
