### ISSUE TITLE
Databricks Dialect, Count() Validation

### ISSUE THREAD

**Issue by harryaultdev** [tobymao/sqlglot#1755]
Quick issue or me being stupid. 

Using the Databricks Dialect I get a parse failure with count() when it involves multiple columns, it’s returning a validation error stating count can only accept one argument. 

In SparkSQL Count(a.Id,a.test) is perfectly valid though.

**Comment by tobymao** [comment]
can you show the documentation where this is legal?

**Comment by harryaultdev** [comment]
Yeah sure you can find it here! Not painfully obvious and a a bit of a niche usecase. Would just return a count where all the expressions / columns are not null.

https://docs.databricks.com/sql/language-manual/functions/count.html
