### ISSUE TITLE
Request for support ksqlDB syntax

### ISSUE THREAD

**Issue by eshepelyuk** [tobymao/sqlglot#1759]
Hello

Is it possible to add support for https://ksqldb.io/ ?

Since it's not a storage but stream processing engine, so it has stream vs table semantics as well as kafka specific properties in `WITH` clause.

**Comment by tobymao** [comment]
Yes it is possible but it is not on our roadmap. We're happy to receive contributions. So feel free to make a pr.

You can join our [slack](tobikodata.com/slack) if you need help getting started.
