### ISSUE TITLE
SQLServer dialect support

### ISSUE THREAD

**Issue by ptallada** [tobymao/sqlglot#176]
Hi,

I'm trying to create a transpiler for ADQL (Astronomical Data Query Language) which is based on SQLServer.
The general syntax is:

```sql

    SELECT
        [ ALL | DISTINCT ]
        [ TOP unsigned_decimal ]
        {
             * |
             { value_expression [ [AS] column_name ] }, ...
         }
        FROM {
                {
                table_name [ [AS] identifier ] |
                ( SELECT ....) [ [AS] identifier ] |
                table_name [NATURAL]
                    [ INNER | { LEFT | RIGHT | FULL [OUTER] } ]
                    JOIN table_name
                    [ON search_condition | USING ( column_name,...) ]
                },
            ...
            }

        [ WHERE search_condition ]
        [ GROUP BY group_by_term, ... ]
        [ HAVING search_condition ]
        [ ORDER BY
            { order_by_expression } [ ASC | DESC],
            ...
            ]
        [ OFFSET unsigned_decimal ]
```

The main problem is the particular syntax for the LIMIT, which goes at the beginning:

```sql
SELECT TOP <N> FROM ...
```

Any pointers where should I start looking to implement this?
I've been inspecting the code for two hours and it might be more difficult than I thought...

Thanks!

Pau.

**Comment by tobymao** [comment]
this should be easy. i’m parse_select in Parser, add a segment where you look for the keyword TOP and add it as a limit

**Comment by tobymao** [comment]
feel free to continue asking questions in this thread

**Comment by barakalon** [comment]
We'll also need the inverse - something to write the limit as a TOP clause in the Generator. I think it gets tricky because its not easy to override the parser/generator order from within a Dialect.

Maybe we also add a _top_sql method to the Generator, but make it a noop by default. And then make it possible to override Generator methods from within a Dialect?

**Comment by ptallada** [comment]
Thanks, I'll start looking into it :)

**Comment by ptallada** [comment]
Hi, I just opened a merge request for this change :)

https://github.com/tobymao/sqlglot/pull/177
