### ISSUE TITLE
Correlated Subqueries with Limit

### ISSUE THREAD

**Issue by andyoneal** [tobymao/sqlglot#1775]
Having an issue with transpiling from PostgreSQL to Snowflake.

```python
import sqlglot

sql = '''select ct.userid, ct.page_path, ct.date, ct.page_title 
from ga.customer_traffic ct
left join lateral (
    select zu.userid
    from support.users zu
    where zu.id = ct.userid
    order by zu.created_at asc
    limit 1
) zu on true;'''

print(sqlglot.transpile(sql, read='postgres', write='snowflake', pretty=True)[0])
```

output:
```sql
SELECT
  ct.userid,
  ct.page_path,
  ct.date,
  ct.page_title
FROM ga.customer_traffic AS ct
LEFT JOIN LATERAL (
  SELECT
    zu.userid
  FROM support.users AS zu
  WHERE
    zu.id = ct.userid
  ORDER BY
    zu.created_at
  LIMIT 1
) AS zu
  ON TRUE
```

Running this in Snowflake results in this error: `Unsupported subquery type cannot be evaluated`

I believe this is because of the use of limit in a correlated subquery, [which is not supported in Snowflake.](https://docs.snowflake.com/en/user-guide/querying-subqueries#usage-notes) I understand if transpiling this functionality might be too complex to be worth supporting, but I couldn't find an issue where this was mentioned. Should it at least show an error/warning?

**Comment by tobymao** [comment]
sqlglot is not a validator, the best validator is the engine. correlated subqueries with limits cannot be optimized, which is probably why snowflake doesn't support it.

transpilation is also best effort, there's not much we can do here, so closing this issue. thanks for the report!
