### ISSUE TITLE
bigquery REGEXP_EXTRACT adds a non-supported fifth argument to the call

### ISSUE THREAD

**Issue by xiaoling** [tobymao/sqlglot#1776]
**Before you file an issue**
- [x] Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- [x] Check if the issue still exists on main 

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

Ran from main as of reporting
```
>>> import sqlglot
>>> sqlglot.parse_one("""SELECT
...   REGEXP_EXTRACT(`foo`, 'bar: (.+?)', 1, 1) AS `bar`
... FROM `DATA`""", read="bigquery").sql(dialect="bigquery")
'SELECT REGEXP_EXTRACT("foo", \'bar: (.+?)\', 1, 1, 1) AS "bar" FROM "DATA"'
```
The output adds a non-supported fifth argument to the function call of `REGEXP_EXTRACT`
We expect `'SELECT REGEXP_EXTRACT("foo", \'bar: (.+?)\', 1, 1) AS "bar" FROM "DATA"'` as the output

**Official Documentation**
Please include links to official SQL documentation related to your issue.
https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_extract
REGEXP_EXTRACT only supports at most 4 args.

Thanks in advance!

**Comment by xiaoling** [comment]
thank you @tobymao ❤️

**Comment by xiaoling** [comment]
@tobymao 

It looks like the same issue remains at the latest release which has https://github.com/tobymao/sqlglot/commit/0a1362b8ca5e18c2bee2cc8a6ab8554ed9142a78

```
In [4]: sqlglot.__version__
Out[4]: '16.2.1'

In [5]: import sqlglot
   ...: sqlglot.parse_one("""SELECT
   ...:   REGEXP_EXTRACT(`foo`, 'bar: (.+?)', 1, 1) AS `bar`
   ...: FROM `DATA`""", read="bigquery").sql()
Out[5]: 'SELECT REGEXP_EXTRACT("foo", \'bar: (.+?)\', 1, 1, 1) AS "bar" FROM "DATA"'
```

The output shouldn't contain the 5th argument

**Comment by GeorgeSittas** [comment]
@xiaoling you need to specify the dialect argument of the `sql` method to be `"bigquery"`:

```python
>>> import sqlglot
>>> sqlglot.parse_one("""SELECT
...   REGEXP_EXTRACT(`foo`, 'bar: (.+?)', 1, 1) AS `bar`
...   FROM `DATA`""", read="bigquery").sql(dialect="bigquery")
"SELECT REGEXP_EXTRACT(`foo`, 'bar: (.+?)', 1, 1) AS `bar` FROM `DATA`"
```

**Comment by xiaoling** [comment]
Thank you @GeorgeSittas was thinking the parse might carry the dialect. this works now
