### ISSUE TITLE
`DATE_DIFF` incorrectly parsed as `DATEDIFF` in presto.

### ISSUE THREAD

**Issue by RossKen** [tobymao/sqlglot#1783]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

```
import sqlglot

tree = sqlglot.parse_one("""select date_diff("day", a, b)""", read="presto")
tree
```
outputs
```
(SELECT expressions: 
  (DATEDIFF this: 
    (COLUMN this: 
      (IDENTIFIER this: b, quoted: False)), expression: 
    (COLUMN this: 
      (IDENTIFIER this: a, quoted: False)), unit: 
    (VAR this: day)))
```
where I would expect 
```
(SELECT expressions: 
  (DATE_DIFF this: 
    (COLUMN this: 
      (IDENTIFIER this: b, quoted: False)), expression: 
    (COLUMN this: 
      (IDENTIFIER this: a, quoted: False)), unit: 
    (VAR this: day)))
```
which results in
```
tree.sql()
```
giving
```
'SELECT DATEDIFF(b, a, day)'
```
instead of 
```
'SELECT DATE_DIFF(b, a, day)'
```

given the specification of the date_diff function in presto (see docs below).

Having tested further, this also seems to be an issue with `trino`.

I'm not particularly familiar with the sqlglot codebase, but I will have a dig around. It is entirely possible that I am wrong in my assumptions for how ☝️ should work. If any maintainers/people with more experience have time to advise that would be much appreciated! 

**Official Documentation**
[Presto date_diff function docs](https://prestodb.io/docs/current/functions/datetime.html?highlight=date_diff#date_diff)
[Trino date_diff_ function docs](https://trino.io/docs/current/functions/datetime.html#date_diff)

**Comment by GeorgeSittas** [comment]
Hey,

This is expected behavior: `exp.DateDiff` is the AST node that represents this function and depending on the target dialect, it can be transpiled to `DATEDIFF`, or `DATE_DIFF`.

```python
>>> import sqlglot
>>> sqlglot.transpile("SELECT DATE_DIFF('day', date '2020-06-15', date '2020-06-25')", "presto")
["SELECT DATE_DIFF('day', CAST('2020-06-15' AS DATE), CAST('2020-06-25' AS DATE))"]
```

**Comment by RossKen** [comment]
Ah great. As expected, it was a me problem. Thanks for the swift reply @GeorgeSittas!
