### ISSUE TITLE
now and current_timestamp in duckdb transpilation

### ISSUE THREAD

**Issue by osalloum** [tobymao/sqlglot#1785]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
Dialect duckdb 

- Check if the issue still exists on main 
Yes

**Fully reproducible code snippet**

The issue lies with how DuckDB treats now and current_timestamp functions 
should the default behavior of transpilation in sqlglot cast those values to support seamless transpilation or should this be left to the app developer to handle ?

```
osalloum=> /* @no-transpile */ select now();
          now()           
--------------------------
 2023-06-15T19:27:56.208Z
(1 row)

osalloum=> /* @no-transpile */ select typeof(now());
      typeof(now())       
--------------------------
 TIMESTAMP WITH TIME ZONE
(1 row)

osalloum=> /* @no-transpile */ select typeof(current_timestamp);
 typeof(current_timestamp) 
---------------------------
 TIMESTAMP WITH TIME ZONE
(1 row)

osalloum=> /* @no-transpile */ select typeof(cast(current_timestamp as timestamp));
 typeof(CAST(current_timestamp AS TIMESTAMP)) 
----------------------------------------------
 TIMESTAMP
(1 row)

osalloum=> /* @no-transpile */ select date_trunc('day', now());
ERROR:  Binder Error: No function matches the given name and argument types 'date_trunc(VARCHAR, TIMESTAMP WITH TIME ZONE)'. You might need to add explicit type casts.
        Candidate functions:
        date_trunc(VARCHAR, TIMESTAMP) -> TIMESTAMP
        date_trunc(VARCHAR, DATE) -> TIMESTAMP
        date_trunc(VARCHAR, INTERVAL) -> INTERVAL
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.
Documentation does not mention returned data types
I am on latest version of duck 0.8.1

**Comment by GeorgeSittas** [comment]
I'm not sure about this one. What you're saying makes sense, and these seem like the kind of functions that have relatively stable API, but since DuckDB hasn't documented these return types, I'm not sure if it's worth adding these casts. What do you think @tobymao?

**Comment by tobymao** [comment]
yea i don't think so
