### ISSUE TITLE
not-sure-if-bug: strange mypy behavior in the latest sqlglot

### ISSUE THREAD

**Issue by pkit** [tobymao/sqlglot#1796]
```python
from sqlglot import parse_one, exp

a = parse_one("SELECT * FROM t").find(exp.Table)
print(a)
```

```bash
$ python -m mypy test.py
test.py:3: error: <nothing> has no attribute "find"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

Could be a mypy bug or the usual mypy idiocy, but just FYI.

**Comment by GeorgeSittas** [comment]
Not sure why this is happening.. any execution path in `parse_one` should either raise or return an `Expression`.

FWIW, `<nothing>` means that mypy failed to solve the type constraints [1, 2] introduced by the use of `TypeVar`s, so my guess is that it's either a mypy bug, or our `@t.overload` annotations are wrong for `parse_one`.

On another note: I think we should clean up `IntoType` at some point. It feels inelegant to have a `str` variant, even more so if the only reason to do have it is to enable the hack with `"JoinType"` in `EXPRESSION_PARSERS`.

[1] https://github.com/python/mypy/issues/3283
[2] https://github.com/python/mypy/blob/6f2bfff521e708f015af1eec5118db4600b829be/mypy/typeops.py#L330

**Comment by tobymao** [comment]
can you repro this @GeorgeSittas ?

**Comment by GeorgeSittas** [comment]
> can you repro this @GeorgeSittas ?

Yeah and it seems like an issue in general, not just our latest release.

**Comment by GeorgeSittas** [comment]
I can also verify that by getting rid of the `@t.overload`s, the error disappears

```
# With just this mypy stopped complaining
def parse_one(
    sql: str,
    read: DialectType = None,
    into: t.Optional[exp.IntoType] = None,
    **opts,
) -> Expression:
    # Definition goes here
```

**Comment by pkit** [comment]
> Yeah and it seems like an issue in general, not just our latest release.

I have upgraded both mypy and sqlglot recently. But I'm not sure anymore. Maybe it was indeed happening before, but just silenced.
In any case my investigation also didn't find any problems in sqlglot type hits.
That's why "not-sure-if-bug"

**Comment by pkit** [comment]
Looks like it's a mypy bug: https://github.com/python/mypy/issues/10817

**Comment by GeorgeSittas** [comment]
@pkit take a look at the PR if you like, it solves the issue.

**Comment by pkit** [comment]
Looks good, I still don't like mypy though.

**Comment by GeorgeSittas** [comment]
Yeah.. It has some rough edges, but I like to think that in the long run it helps with the development process by catching errors early vs at runtime, even if they're trivial ones. Hopefully it also helps "documenting" the code more than it makes it unreadable. :-)
