### ISSUE TITLE
Teradata: TOP N is not supported

### ISSUE THREAD

**Issue by Srivatzn** [tobymao/sqlglot#1798]
Thankyou for SQLGLOT. Fantastic library.

The below fails 
```python
import sqlglot

sqlglot.transpile("select top 10 column1 from table1.column1", identity=True, read="teradata")
```

***Error***
```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 12.
  select top 10 column1 from table1.column1
```

**Official Documentation**
[Teradata SQL reference](https://docs.teradata.com/r/2_MC9vCtAJRlKle2Rpb0mA/__1TX6kDYjUS0vA5Hi0Y0g)

I will be happy to contribute the fix but I am new here and would like some guidance on where to start. If my guess is right, I will have to make changes only to the `KEYWORDS` dict in `dialects/teradata.py` to add `"TOP": TokenType.TOP` but I am not entirely sure. I will watch and learn for the next time. 

Thanks again for this library.

**Comment by GeorgeSittas** [comment]
> I will be happy to contribute the fix but I am new here and would like some guidance on where to start. If my guess is right, I will have to make changes only to the KEYWORDS dict in dialects/teradata.py to add "TOP": TokenType.TOP but I am not entirely sure. I will watch and learn for the next time.

Like you said, the mapping of `"TOP"` to `TokenType.TOP` was all that was needed in this particular case, because this syntax is already supported for other dialects. If you want to contribute in the future, a good first step is to search SQLGlot's codebase to see if the feature of interest is already covered.
