### ISSUE TITLE
`optimize` fails on query which has tables as rows

### ISSUE THREAD

**Issue by itamarom** [tobymao/sqlglot#1801]
Looks like sqlglot is having some issues dealing with queries that return rows which are full rows of another table. This issue also manifests when working with `JSON_ARRAY_ELEMENTS` (see second example)

**Fully reproducible code snippet**
```python
from sqlglot.optimizer import optimize
from sqlglot import dialects
from sqlglot.schema import ensure_schema

schema = ensure_schema({"othertable": {"a": "text", "cleaned_url_tags": "json"}, "numbers": {"b": "integer"}}, dialect="postgres")

# Fails with `OptimizeError: Column 'numbers' could not be resolved`
optimize("""
SELECT
  numbers
  FROM othertable
  LEFT JOIN numbers
  ON TRUE;
""", schema, "postgres")
```
```python
from sqlglot.optimizer import optimize
from sqlglot import dialects
from sqlglot.schema import ensure_schema

schema = ensure_schema({"othertable": {"a": "text", "cleaned_url_tags": "json"}}, dialect="postgres")

# Fails with `OptimizeError: Column 'url_tag_element' could not be resolved`
optimize("""SELECT
    url_tag_element
  FROM othertable
  LEFT JOIN JSON_ARRAY_ELEMENTS(cleaned_url_tags) AS url_tag_element
    ON TRUE;""", schema, "postgres")

```
**Official Documentation**
https://www.postgresql.org/docs/9.5/functions-json.html

**Comment by tobymao** [comment]
the first query doesn't seem valid to me, there is no column numbers, so it should fail.

the second one although is valid, is out of scope for now, we don't handle qualification of UDTFs. closing as won't do

you can get around this by passing validate_qualify_columns=False

**Comment by itamarom** [comment]
Hi, thanks for the quick reply. The first one is definitely valid is Postgres, though I agree it's weird.
See example here: https://www.db-fiddle.com/f/hiCNexnSnbwtpKprGKKYNo/0

**Comment by GeorgeSittas** [comment]
> The first one is definitely valid is Postgres, though I agree it's weird.

What's the use case for such a query? Couldn't you just rewrite it into a more standard form like the following?

```sql
SELECT
  b
  FROM othertable
  LEFT JOIN numbers
  ON TRUE;
```
