### ISSUE TITLE
parse_one not support force/use index for dialect MySQL

### ISSUE THREAD

**Issue by WSKINGS** [tobymao/sqlglot#1811]
when execute parse_one method, it not support index hint for mysql

test code as following:

`sql = """
       SELECT * FROM table1 USE INDEX (col1_index,col2_index)
       WHERE col1=1 AND col2=2 AND col3=3;
     """
        parse_one(sql, read=dialects.mysql.MySQL)`

**Official Documentation**
Please include links to official SQL documentation related to your issue.
https://dev.mysql.com/doc/refman/8.0/en/index-hints.html

**Comment by xuyuan23** [comment]
it wasn't work utill now?

**Comment by xuyuan23** [comment]
Error `sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 29.
  select * from t_c FORCE INDEX(idx_a) where a > 0`  appeared when execute `parse_one("select * from t_c FORCE INDEX(idx_a) where a > 0")` , how can I resolve this problem?
