### ISSUE TITLE
could be a logic problem in the diff() function

### ISSUE THREAD

**Issue by manmustbecool** [tobymao/sqlglot#1813]
code:
```
from sqlglot import parse_one, diff
import sqlglot
source = "SELECT a, b from t"
target = "SELECT a, b from t t1"
optimized_source = parse_one(source)
optimized_target = parse_one(target)
edit_script = diff(optimized_source, optimized_target)
for e in edit_script:
    edit_l = edit_l + [type(e)]
    print(type(e))
```
output: 
```
<class 'sqlglot.diff.Remove'>
<class 'sqlglot.diff.Insert'>
<class 'sqlglot.diff.Insert'>
<class 'sqlglot.diff.Insert'>
<class 'sqlglot.diff.Keep'>
<class 'sqlglot.diff.Keep'>
<class 'sqlglot.diff.Keep'>
<class 'sqlglot.diff.Keep'>
```
1 <Remove> and 3 <Insert> are used for transforming source to target. The <insert> does not make much sense in this example

**Comment by GeorgeSittas** [comment]
This doesn't seem like an actual issue to me. The "AST diff" algorithm follows a best-effort approach and so it might be a bit "verbose" some times.

For your example, the first four actions of the edit script are:

```python
>>> edit_script
Remove(expression=(TABLE this:
  (IDENTIFIER this: t, quoted: False)))
Insert(expression=(TABLEALIAS this:
  (IDENTIFIER this: t1, quoted: False)))
Insert(expression=(TABLE this:
  (IDENTIFIER this: t, quoted: False), alias:
  (TABLEALIAS this:
    (IDENTIFIER this: t1, quoted: False))))
Insert(expression=(IDENTIFIER this: t1, quoted: False))
...
```

There are also some `Keep` actions remaining, signifying that the rest of the AST is unchanged. Notice that these first four actions are not invalid. It's just that, to my understanding, the diff algorithm "notices" the missing `TableAlias` expression in the `Table` expression of the source query and so tries to "reconstruct" the whole `Table` expression that contains it.

The query ASTs for context:

```python
>>> source
(SELECT expressions:
  (COLUMN this:
    (IDENTIFIER this: a, quoted: False)),
  (COLUMN this:
    (IDENTIFIER this: b, quoted: False)), from:
  (FROM this:
    (TABLE this:
      (IDENTIFIER this: t, quoted: False))))
>>> target
(SELECT expressions:
  (COLUMN this:
    (IDENTIFIER this: a, quoted: False)),
  (COLUMN this:
    (IDENTIFIER this: b, quoted: False)), from:
  (FROM this:
    (TABLE this:
      (IDENTIFIER this: t, quoted: False), alias:
      (TABLEALIAS this:
        (IDENTIFIER this: t1, quoted: False)))))
```

@izeigerman can probably provide more context here. :)

I'll go ahead and close this issue, but happy to reopen if there's room for improvement in the diff module.
