### ISSUE TITLE
Cannot parse this sqlite query

### ISSUE THREAD

**Issue by tshu-w** [tobymao/sqlglot#1838]
**Before you file an issue**
- [x] Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- [x] Check if the issue still exists on main 

**Fully reproducible code snippet**
```python
from sqlglot import parse_one
sql_query = "SELECT CAST(SUM(CASE WHEN T2.DESCRIPTION = 'Allergy to grass pollen' THEN 1 ELSE 0 END) AS REL) * 100 / COUNT(T1.patient) FROM patients AS T1 INNER JOIN allergies AS T2 ON T1.patient = T2.PATIEN"
parse_one(sql_query)
```

**Comment by GeorgeSittas** [comment]
What dialect is this? What type does `REL` correspond to?

**Comment by GeorgeSittas** [comment]
You have a typo in your query, it should be `CAST(... AS REAL)`, not `AS REL`.

**Comment by tshu-w** [comment]
Thank you for your reply. I am not very familiar with SQL, so I only tried it on an online validation webpage.

I would greatly appreciate it if you could tell me what is wrong with these two SQL queries 🙏:
1. SELECT T1.first_name, T1.last_name FROM current AS T1 INNER JOIN `current-terms` AS T2 ON T1.bioguide_id = T2.bioguide WHERE T2.party = 'Republican' AND T1.gender_bio = 'F' AND T2.END > DATE() GROUP BY T1.bioguide_id
2. SELECT max_temperature_f, date FROM weather WHERE max_temperature_f = (SELECT MAX(max_temperature_f) FROM weather WHERE max_temperature_f IS NOT NULL AND max_temperature_f IS NOT '')
