### ISSUE TITLE
Incorrect parsing of column a name when an identifier is used in Snowflake TIMEDIFF in the qualify method

### ISSUE THREAD

**Issue by wezham** [tobymao/sqlglot#1851]
[As stated in the snowflake documentation](https://docs.snowflake.com/en/sql-reference/functions/timediff#arguments) the signature for timediff

`TIMEDIFF( <date_or_time_part> , <date_or_time_expr1> , <date_or time_expr2> )`

> date_or_time_part
> The unit of time. Must be one of the values listed in [Supported Date and Time Parts](https://docs.snowflake.com/en/sql-reference/functions-date-time.html#label-supported-date-time-parts) (e.g. month). The value can be a string literal or can be unquoted (e.g. 'month' or month).

However, when using the unquoted argument like `YEAR` instead of `'YEAR'`, qualify sees the argument as a column and attempts to resolve it in the schema. For example you can see the code block below: 

```
table_schema = {"sample_table": {"created_at": "timestamp_tz"}}
sql_query = "SELECT TIMEDIFF(YEAR, created_at, current_timestamp()) from sample_table;"
expression_ = qualify(
    parse_one(sql_query),
    dialect="snowflake",
    qualify_columns=True,
    validate_qualify_columns=True,
    expand_alias_refs=True,
    schema=table_schema,
)
```

Results in 
```
    raise OptimizeError(
sqlglot.errors.OptimizeError: Column '"YEAR"' could not be resolved
```

**Comment by tobymao** [comment]
you need to specify dialect in parse_one

parse_one(sql, read="snowflake")

**Comment by tobymao** [comment]
separately we need to implement timediff

**Comment by wezham** [comment]
Yep that was my error when re-producing. Thanks
