### ISSUE TITLE
Failure to parse nested ANY_VALUE HAVING MIN [Dialect: BigQuery]

### ISSUE THREAD

**Issue by lucia-vargas-a** [tobymao/sqlglot#1858]
sqlglot 10.1.3 fails to parse this query:

`sqlglot.parse_one('SELECT ANY_VALUE(fruit HAVING MAX sold) AS a_highest_selling_fruit FROM (( SELECT 20 AS sold, "apples" AS fruit UNION ALL SELECT 30 AS sold, "pears" AS fruit UNION ALL SELECT 30 AS sold, "bananas" AS fruit UNION ALL SELECT 10 AS sold, "oranges" AS fruit))')`

It expect a closing ) after HAVING.

**Error**
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 29.
  SELECT ANY_VALUE(fruit HAVING MAX sold) AS a_highest_selling_fruit FROM (( SELECT 20 AS sold, "apples" AS fruit UNION ALL SELECT

**Official Documentation**
BigQuery docs for [ANY_VALUE HAVING MIN](https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#any_value)

**Comment by GeorgeSittas** [comment]
Hey,

You should generally use the dialect of interest when parsing / generating SQL (here, you'd need `read="bigquery"`).

In this particular case, there's indeed a bug when parsing with `"bigquery"` as the dialect. I'll take a look, thanks for the report!

**Comment by lucia-vargas-a** [comment]
Thank you!

**Comment by GeorgeSittas** [comment]
FYI just released v16.7.4 which contains the fix.

**Comment by lucia-vargas-a** [comment]
Many thanks!
