### ISSUE TITLE
mysql parser not support  some INSERT operations

### ISSUE THREAD

**Issue by brosoul** [tobymao/sqlglot#1862]
1. mysql parser not support  `INSERT ... ON DUPLICATE KEY UPDATE Statement`
example sql followed
> INSERT INTO t1 (a,b,c) VALUES (1,2,3),(4,5,6) ON DUPLICATE KEY UPDATE c=VALUES(a)+VALUES(b);

ref: https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html

2. mysql parse not support `INSERT IGNORE INTO xxx `

ref : https://dev.mysql.com/doc/refman/5.7/en/insert-select.html

**Comment by GeorgeSittas** [comment]
Thanks for the report, I'm gonna look into this soon.
