### ISSUE TITLE
SQLite double-quoted string literals result in an error

### ISSUE THREAD

**Issue by infokiller** [tobymao/sqlglot#1867]
First of all, thanks for this amazing project!
SQLite has a quirk where it [supports double-quoted string literals](https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted). It seems to first check if it's an identifier, and if not, it considers it a string literal. A few questions about this:

1. Would it be possible to support this in sqlglot?
2. If I wanted to add a new dialect that supports this, how would you recommend doing this? I thought about adding a new `IdentifierOrString` token type, and then let the parser resolve it, however it seems the default parser doesn't take the schema into account (which is required in this case). In this case, would you recommend overriding `SQLite.parse` to use a custom parser that inherits from `Parser`, and get the schema in `**opts`?

**Fully reproducible code snippet**

```python
import sqlglot
sqlglot.optimizer.optimize('SELECT c from t WHERE c = "str"', dialect='sqlite', schema={'t': {'c': 'INT'}})
```

**Official Documentation**

https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted

**Comment by GeorgeSittas** [comment]
Hey! 👋

I don't think it's necessary to create a schema-aware parser in order to tackle this problem.

What about using the SQLite parser, like you would normally do, and just run a transformation to replace `Identifier` AST nodes with `Literal` (string) nodes, based on schema information? You could leverage some of the optimizer's infra to do this (e.g. scope, resolver) -- it shouldn't be very hard.

One gotcha is that the parser may only expect strings in some places, so identifiers would be unparseable there, but you should be able to override the corresponding methods and patch this issue easily.

The ROI doesn't seem high enough to justify adding support for this in SQLGlot itself, but I'd be happy to help if you need to make a custom implementation for your use-case (either here, or in our [Slack](https://tobikodata.com/slack) channel).

**Comment by infokiller** [comment]
Hey, and many thanks for the quick and helpful reply!
Right now, to work around this, I'm defining a custom dialect as following:

```python
class SQLiteDQ(sqlite.SQLite):

    def parse(self, sql: str, **opts) -> t.List[t.Optional[exp.Expression]]:
        toks = self.tokenize(sql)
        # Hack to handle:
        # https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted
        if schema := opts.pop('schema', None):
            col_names = sum([list(t.keys()) for t in schema.values()], [])
            for tok in toks:
                if tok.token_type == TokenType.IDENTIFIER and sql[tok.start] == sql[
                        tok.end] == '"' and tok.text not in col_names:
                    tok.token_type = TokenType.STRING
        return self.parser(**opts).parse(toks, sql)
```

This is only a quick hack, as it doesn't actually consider the table of the identifier.

Just to make sure I understand your proposed solution:

- Use `sqlglot.parse_one` normally to get the AST
- For each double-quoted identifier in `ast.find_all(sqlglot.exp.Identifier)`:
  - Resolve the table for the identifier
  - If the table does not have a column with the identifier name, replace it with a `Literal` node

Did I miss anything?

For resolving the table, should I do something similar to the code in https://github.com/tobymao/sqlglot/blob/main/sqlglot/optimizer/qualify_columns.py? Is that the best reference?

Thanks in advance!

**Comment by GeorgeSittas** [comment]
Yeah, that's what I was suggesting more or less. The `qualify_columns` module should be a good reference on how to work with the `schema` and `scope` modules.

Maybe another way to approach this would be to use the `qualify` rule with `validate_qualify_columns=False`, and then write your own function, which would be similar to `validate_qualify_columns`, that replaces all unresolved / unqualified columns with the corresponding string literals.

> This is only a quick hack, as it doesn't actually consider the table of the identifier.

Yep, it doesn't take scopes into account too so it's not very robust.

**Comment by infokiller** [comment]
Many thanks! I will try to follow these approaches
