### ISSUE TITLE
why a.id = b.id be changed to JON b:ON: True?

### ISSUE THREAD

**Issue by xkkjiayou** [tobymao/sqlglot#1876]
SELECT
  `a`.`city` AS `city`,
  `b`.`price` AS `price`
FROM `a` AS `a`
JOIN `b` AS `b`
  ON `a`.`id` = `b`.`id` AND `a`.`oo` > 44 AND `b`.`bvb` > 2
JOIN `c` AS `c`
  ON `c`.`ee` > 11 AND `c`.`id` = `a`.`id`
WHERE
  `a`.`dass` > 55 AND `a`.`q` > 33
`

Plan
----
- Join: a (2396155995808)
    Context:
      b:
      On: TRUE AND "a"."oo" > 44 AND "b"."bvb" > 2
      c:
      On: "c"."ee" > 11 AND TRUE
    Projections:
      - "a"."city" AS "city"
      - "b"."price" AS "price"
    Condition: "a"."dass" > 55 AND "a"."q" > 33
    Dependencies:
    - Scan: b (2396155996048)
      Context:
        Source: "b" AS "b"
      Projections:
    - Scan: a (2396155995760)
      Context:
        Source: "a" AS "a"
      Projections:
    - Scan: c (2396155996144)
      Context:
        Source: "c" AS "c"
      Projections:
`

I do not know why a.id = b.id be changed to JON b:ON: True?
![image](https://github.com/tobymao/sqlglot/assets/38376865/d4878fac-576f-4809-b943-bb7bd369d6d6)

**Comment by xkkjiayou** [comment]
i also do not know why not put Condition into Dependencies so that  can do "Filter A>33 while scanning Table A" is faster?

**Comment by tobymao** [comment]
if there’s no issue please don’t file an issue and use the discussions forum. an issue would be if the results are wrong.

but my guess is that its a hash join so that condition is removed

**Comment by xkkjiayou** [comment]
感谢您的来信，此时我不在办公室，稍后会及时阅读。在此期间我不方便接收邮件。如果您想及时获得通讯，请拨打我的手机联系我，谢谢您。
