### ISSUE TITLE
Parsing nested joins without parenthesis

### ISSUE THREAD

**Issue by 10bas10** [tobymao/sqlglot#1878]
By applying the nested join you are able to LEFT JOIN a combined set where an INNER JOIN is applied. However the last ON syntax isnt parsed properly:

```
import sqlglot
from sqlglot import optimizer
expr = sqlglot.parse_one("""
SELECT
 a.id
,b.test
,c.test2
FROM a
LEFT JOIN
    b
    INNER JOIN c
        ON c.id = b.id
    ON b.id = a.id
""", read="tsql")
```

Resulting in an error:
```
ParseError: Invalid expression / Unexpected token. Line 11, Col: 6.
```

**Comment by tobymao** [comment]
i can't find the old issue, but i'm going to close this again as not planned.

**Comment by 10bas10** [comment]
What does "not planned" mean?

**Comment by GeorgeSittas** [comment]
@tobymao in order to handle this, I think we'd need to make `_parse_join` recursive so that each `ON` clause is matched with the corresponding join.

**Comment by tobymao** [comment]
> What does "not planned" mean?

it means we’re not committing to doing this.

we may if it’s easy

**Comment by tobymao** [comment]
i have a fix for this coming soon
