### ISSUE TITLE
Using optimizer with nested joins

### ISSUE THREAD

**Issue by 10bas10** [tobymao/sqlglot#1879]
When using a nested join, where table b and c need to be joined before making the join to table a is not working without using parenthesis, as it will result in a parsing error. This has been filed as separate bug. However when using parenthesis at this nested join, the query is actually wrongly parsed. As the parenthesis is currently parsed as a subquery, while it is not. 

When using the optimizer on this AST, an error occurs `OptimizeError: Column 'c.id' could not be resolved for table: 'c'`, this is due to the fact that table alias c does not exist anymore if you parse the parenthesis as a subquery. 

```
import sqlglot
from sqlglot import optimizer
expr = sqlglot.parse_one("""
SELECT
 a.id
,b.test
,c.test2
FROM a
LEFT JOIN (
    b
    INNER JOIN c
        ON c.id = b.id
)
    ON b.id = a.id
""", read="tsql")

schema={
    "testcat": {
        "testdb": {
            "a": {
                "id": "INT",
            },
            "b": {
                "id": "INT",
                "test": "STRING",
            },
            "c": {
                "id": "INT",
                "test2": "STRING",
            },
        }
    }
}

expr = optimizer.optimize(
    expression=expr,
    schema=schema,
)
```

**Comment by tobymao** [comment]
maybe need to expand this out into (select * from b join c) as b

**Comment by 10bas10** [comment]
Shouldnt the scope component also be able to handle such statements and identify tables a, b and c in its most outer scope?

**Comment by GeorgeSittas** [comment]
The problem is that `c` is used as a source (e.g. in `c.test2`), but it's not in scope because we parse it as a subquery.

**Comment by GeorgeSittas** [comment]
FYI @10bas10 this is in-progress, I'll have a fix soon hopefully.

**Comment by 10bas10** [comment]
> FYI @10bas10 this is in-progress, I'll have a fix soon hopefully.

Hey George,

Great, thanks alot. Ill have a look as soon as its available.
