### ISSUE TITLE
Add DATE_SUB() support between PostgreSQL and BigQuery

### ISSUE THREAD

**Issue by yingw787** [tobymao/sqlglot#188]
Wanted to create a pull request to create a BigQuery Dialect as per [this LinkedIn post](https://www.linkedin.com/feed/update/urn:li:activity:6947607094099345408?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6947607094099345408%2C6948008642889601024%29), still inspecting the code though and wanted to get some traction tonight so creating a small issue instead; hopefully a pull request tomorrow will get me started on resolving this issue.

In BigQuery, this is how dates are incremented/decremented:

```sql
SELECT DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY);
```

This translates to the following in PostgreSQL:

```sql
SELECT CURRENT_DATE - INTERVAL '1 DAY';
```

Notes for me: Definition of done would be a dialect for BigQuery, support for this syntax transformation, and a successful test case with example.

**Comment by tobymao** [comment]
more canonical form would be select current_date - interval '1' day

**Comment by tobymao** [comment]
@yingw787 do you plan on working on this? if so i won't touch it for now

**Comment by yingw787** [comment]
Hey @tobymao, can I have until this Saturday to make some progress? If I don't finish by this Saturday I'll push what I have up and then feel free to use/discard

**Comment by tobymao** [comment]
yep no rush, i was just curious if you're planning to tackle it, feel free to ask me any questions

**Comment by yingw787** [comment]
So I added some tracers using `ipdb` and it looks like the `Generator` class in `generator.py` isn't designed to be modified but rather populated with `opts` passed in such as `self.transforms` and other stuff from each Dialect.

When I run through current HEAD of main of `sqlglot` my use case, I get the following raw-looking expression:

```bash
$ ipython                                                                                                                                      
Python 3.9.12 (main, Jun  1 2022, 11:38:51)                                                                                                                                                               
Type 'copyright', 'credits' or 'license' for more information                                                                                                                                             
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sqlglot

In [2]: sql = "SELECT DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)"

In [3]: sqlglot.transpile(sql, write='postgres')
Out[3]: ['SELECT DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)']
```

Questions:
- I know there's an expression parsed and passed into the Generator, but I'm not sure where the transpilation step occurs. I thought there would be a step mapping the parsed expression to a standard format before generating via dialect, but I don't see such a step taking place. How would I convert e.g. `DATE_SUB()` function to a `-` operator?
- For time-based functions, am I supposed to use `inverse_time_mapping` and `inverse_time_trie`? What are those supposed to be?

**Comment by tobymao** [comment]
you'd do that in dialects.py, you can pass in a custom function that handles date_sub for big query

no, the time_tries are used for converting date format strings like '%YY-%MM%DD"

if it's easier, you can contact me on slack or twitter @captaintobs

https://join.slack.com/t/18xxgames/shared_invite/zt-1bvd256hi-fH6Cm~EEXMFqZ36_OudVbA
