### ISSUE TITLE
Use readable alias for aggr columns' name

### ISSUE THREAD

**Issue by stonyw** [tobymao/sqlglot#1888]
**Is your feature request related to a problem? Please describe.**

I am working on cleaning sql dataset. I try to compare the result from sqlite and sqlglot. 
The cells in table's are same. The headers are under diferent rules. 
sqlglot use an internal name for aggr column as header.
SQlite / MySQL / PostgreSQL use aggr fun name as column alias.

**Describe the solution you'd like**
```sql
select t , sum ( a ) from x group by t ;
```
| engine |   header 1 | header 2 |
| ---| ---| ---| 
|sqlglot| t | _col_1|
|sqlite 3.39| t | sum(a)|
|mysql 5.7| t | sum(a)|
|postgres 15| t | sum|

I prefer  mysql/sqlite:  "sum(a)" 

**Describe alternatives you've considered**
1. Quoted is True all the time.
2. use "sum(a)" as column alias might be easier than as column name.

**Additional context**
Verified on https://www.db-fiddle.com/
shema
```sql
CREATE TABLE x (
  t text,
  a INT
);

INSERT INTO x (
  t,
  a
)
VALUES
  ('a', 6),
  ('b', 12),
  ('a', 10),
  ('b', 12);
```

**Comment by tobymao** [comment]
you can simply alias the query yourself inside the sql. there is no standard for aliasing things
