### ISSUE TITLE
Excecutor supports Bare columns

### ISSUE THREAD

**Issue by stonyw** [tobymao/sqlglot#1892]
## Is your feature request related to a problem? Please describe.

https://dev.mysql.com/doc/refman/8.0/en/group-by-handling.html
For the query to be legal in SQL-92, the name column must be omitted from the select list or named in the GROUP BY clause.

SQL:1999 and later permits such nonaggregates per optional feature T301 if they are functionally dependent on GROUP BY columns

## Describe the solution you'd like
Accept "a"  as well as "MAX(a)" like SQlite.
```sql
SELECT a, SUM(b) FROM x GROUP BY c;
```

## Describe alternatives you've considered

Alternative. Support ANY_VALUE for MySQL / Postgres(16)
```sql
SELECT ANT_VALUE(a), SUM(b) FROM x GROUP BY c;
```

https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_any-value
https://commitfest.postgresql.org/42/4038/

## Additional context
SQlite: Bare columns in an aggregate query
https://www.sqlite.org/lang_select.html#bare_columns_in_an_aggregate_query

MySQL: after disable sql_mode  ONLY_FULL_GROUP_BY, MySQL works in same way with SQlite.
https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_only_full_group_by
`SET session sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''));`

**Comment by tobymao** [comment]
you can just use min or max. or if you want feel free to make a PR for any_value
