### ISSUE TITLE
Support for OUTPUT in t-sql

### ISSUE THREAD

**Issue by jh88** [tobymao/sqlglot#1901]
Thank you for the great work. I have been using this for transpiling SQL server (`tsql`) to PostgreSQL. 

I would like to request support for the [`OUTPUT`](https://learn.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-ver16) keyword in T-SQL, which is similar to the `RETURNING` keyword in PostgreSQL.

For instance, when executing an `INSERT` statement like the one below, the `OUTPUT` clause would return the primary key value id of the inserted row:
```
INSERT INTO [my_table] ([my_column]) OUTPUT inserted.id VALUES(0);
```

Thank you.

**Comment by tobymao** [comment]
thanks for the report

**Comment by jh88** [comment]
Thank you Toby for the quick response.

The aforementioned sample query, when transpiled using the new code, would be as follows:

```
INSERT INTO "my_table" (
  "my_column"
)
VALUES
  (0)
RETURNING inserted.id
```
However, it is necessary to remove `inserted` in the `RETURNING` clause.

Conversely, when returning inserted fields in T-SQL, we need to add the `inserted` prefix.

**Comment by tobymao** [comment]
did you test it with tsql specified?

**Comment by tobymao** [comment]
ah i see what you're saying, when going to returning, we need to remove inserted. it doesn't seem like the prefix can be added in the other direction though because it doesn't exist

**Comment by jh88** [comment]
Yes, I'm transpiling between `tsql` and `postgres`. 

I created a new AzureSQL class which inherits your `TSQL`. In the `returning_sql` method, as a workaround, I manually assign `table` to `inserted`.

```
def returning_sql(self, expression: exp.Returning) -> str:
    into = self.sql(expression, "into")
    into = self.seg(f"INTO {into}") if into else ""

    for exp in expression.args['expressions']:
        exp.args['table'] = 'iniserted'

    return f"{self.seg('OUTPUT')} {self.expressions(expression, flat=True)}{into}"
```

**Comment by tobymao** [comment]
sorry, is inserted a magic keyword in tsql?

**Comment by jh88** [comment]
Apologies for any misunderstandings. I am not inserting data into the table named `inserted`. 
It is a table that is managed by SQL Server. You can find more information about it [here](https://learn.microsoft.com/en-us/sql/relational-databases/triggers/use-the-inserted-and-deleted-tables?view=sql-server-ver16).

> The inserted table stores copies of the new or changed rows after an INSERT or UPDATE statement.

My understanding is that we should use the `inserted` table when working with the INSERT statement, and the [`deleted`](https://learn.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-ver16#deleted) table for the DELETE statement.

**Comment by tobymao** [comment]
it's not so simple

```
UPDATE Production.WorkOrder
SET ScrapReasonID = 4
OUTPUT DELETED.ScrapReasonID,
       INSERTED.ScrapReasonID,
       INSERTED.WorkOrderID,
       INSERTED.ProductID,
       p.Name
    INTO @MyTestVar
FROM Production.WorkOrder AS wo
    INNER JOIN Production.Product AS p
    ON wo.ProductID = p.ProductID
    AND wo.ScrapReasonID= 16
    AND p.ProductID = 733;
```

if you're trying to convert postgres into tsql, you won't be able to know what inserted and deleted columns are

**Comment by tobymao** [comment]
i'm not going to support this for now, you can add a custom transform to do what you're looking for

expr.transform(...)
