### ISSUE TITLE
Redshift DATEDIFF parsed wrongly 

### ISSUE THREAD

**Issue by EladSisu** [tobymao/sqlglot#1915]
Additional 'TS_OR_DS_TO_DATE' added to redshift dialect. 
*Might be a regression on this [commit](https://github.com/tobymao/sqlglot/pull/1746)
`>>> query
'select DATEDIFF(day,start_day,end_day) as date_diff from table;'
>>> parsed_query
(SELECT expressions: 
  (ALIAS this: 
    (DATEDIFF this: 
      (TSORDSTODATE this: 
        (COLUMN this: 
          (IDENTIFIER this: end_day, quoted: False))), expression: 
      (TSORDSTODATE this: 
        (COLUMN this: 
          (IDENTIFIER this: start_day, quoted: False))), unit: 
      (VAR this: day)), alias: 
    (IDENTIFIER this: date_diff, quoted: False)), from: 
  (FROM this: 
    (TABLE this: 
      (IDENTIFIER this: table, quoted: False))))
>>> print(parsed_query)
SELECT DATEDIFF(TS_OR_DS_TO_DATE(end_day), TS_OR_DS_TO_DATE(start_day), day) AS date_diff FROM table`

**Comment by GeorgeSittas** [comment]
Thanks for the report, I'll take a look shortly

**Comment by GeorgeSittas** [comment]
This isn't parsed wrongly, it's intended behaviour. As you can see, transpilation hasn't been broken:

```python
>>> import sqlglot
>>> sqlglot.transpile("select DATEDIFF(day,start_day,end_day) as date_diff from table", "redshift")
['SELECT DATEDIFF(day, start_day, end_day) AS date_diff FROM table']
```

The representation was changed in order to facilitate the transpilation of `DATEDIFF` when targetting Presto SQL.

**Comment by EladSisu** [comment]
Thanks for a quick replay, I guess what I was referring to is the parse_one method spitting out extra 'TS_OR_DS_TO_DATE' which break the sql once we try to read it back.

**Comment by GeorgeSittas** [comment]
You need to use the correct dialect when printing out the expression, i.e.

```python
print(parsed_query.sql(dialect="redshift"))
```

instead of simply

```python
print(parsed_query)
```

**Comment by EladSisu** [comment]
Oh ok that works ! thanks again.
