### ISSUE TITLE
feat(spark) Add mappings for SQL variables

### ISSUE THREAD

**Issue by dmoore247** [tobymao/sqlglot#1920]
**Is your feature request related to a problem? Please describe.**
Spark doesn't support SQL variables but does support setting a context variable. Would like to transpile common variable usage to spark. Examples:

```sql
-- TSQL
DECLARE @year_variable INT;
SET @year_variable = YEAR(GETDATE());
SELECT @year_variable
```
```sql
-- Snowflake
SET MY_VARIABLE=10;
SELECT $MY_VARIABLE
```

**Describe the solution you'd like**
```sql
-- Spark SQL
SET var.year_variable = YEAR(CURRENT_DATE());
SELECT ${var.year_variable};
```
```sql
-- Spark SQL
SET var.quantity = (select count(1) from range(123));
SELECT ${var.quantity}
```

**Describe alternatives you've considered**
Generating mappings outside of `sqlglot` would be more cumbersome and harder to find for end users.

**Additional context**
The next mapping would be to map stored procedure input variables. This [blog](https://medium.com/@24chynoweth/converting-stored-procedures-to-databricks-73fe4ab64ed0) recommends using CREATE WIDGET and $parametername.
The discussion would be around if there's overlap in setting local variables and stored proc parameters. If it's best to split the PRs to spark and databricks dialects. Etc...
Example:
```sql
-- databricks sql notebook
CREATE WIDGET TEXT CostCenter DEFAULT '';
SELECT $CostCenter
```

**Comment by tobymao** [comment]
we have no plans to implement but perhaps open to a pr, i don't think we parse ${var.quantity} as it's probably text preprocessor and not actually sql

**Comment by dmoore247** [comment]
@tobymao Would you like to assign this to me to implement? Any additional requirements you'd like to add.

**Comment by tobymao** [comment]
exactly, it’s not sql so it’s out of the scope of sqlglot
