### ISSUE TITLE
sqlglot should raise and error when a comma comes after the last argument before a from keyword

### ISSUE THREAD

**Issue by wezham** [tobymao/sqlglot#1926]
When a comma comes after the last column name and before the `from`keyword, SQL will fail to compile in snowflake. Therefore the following sql should not parse_succesfully in sqlglot:

```
>>> from sqlglot import parse_one
>>> parse_one("SELECT item, from orders where is_sent=False", read="snowflake")
(SELECT expressions:
  (COLUMN this:
    (IDENTIFIER this: item, quoted: False)), from:
  (FROM this:
    (TABLE this:
      (IDENTIFIER this: orders, quoted: False))), where:
  (WHERE this:
    (EQ this:
      (COLUMN this:
        (IDENTIFIER this: is_sent, quoted: False)), expression:
      (BOOLEAN this: False))))
```

**Official Documentation**

I can't find a link to some official documentation in snowflake but can confirm that the above query does not compile in snowflake.

**Comment by tobymao** [comment]
sqlglot is not a validator. it has a much more flexible parser than most engines. when you generate sql with a trailing comma it is removed, ensuring that the sql produced by sqlglot is valid

so this is working as intended

**Comment by wezham** [comment]
You do make this clear in this description

> However, it should be noted that SQL validation is not SQLGlot’s goal, so some syntax errors may go unnoticed.

That is good to know
