### ISSUE TITLE
Spark functions months_bewteen & to_timestamp not transpiling to DuckDB

### ISSUE THREAD

**Issue by richard-a-lott** [tobymao/sqlglot#1928]
I'm attempting to transpile from Spark to DuckDB. Sqlglot doesn't seem to be recognising the spark functions "months_between" and "to_timestamp". 

See example below (apologies for the image, I can't paste the code directly), neither of those functions gets transpiled:

![image](https://github.com/tobymao/sqlglot/assets/136445689/b81a5764-c5dc-482e-a741-9dee1a3c2efa)

"months_bewteen" should become "date_diff", and
"to_timestamp" should become "strptime" in duckdb, see below:

![image](https://github.com/tobymao/sqlglot/assets/136445689/866f299c-50b9-41ca-9ba1-6a8fffebffa1)

**Official Documentation**
[spark: months_bewteen](https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.functions.months_between.html)
[spark: to_timestamp](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.to_timestamp.html)
[duckdb: time functions](https://duckdb.org/docs/sql/functions/timestamp.html)

**Comment by GeorgeSittas** [comment]
Thanks for the report, I'll take a look
