### ISSUE TITLE
Transforming node tree backwards

### ISSUE THREAD

**Issue by dmelchor-stripe** [tobymao/sqlglot#1932]
**Is your feature request related to a problem? Please describe.**

To apply transformations to a node tree we currently need to manually transform the node's children and then return the node's transformation.

**Describe the solution you'd like**

It would be extremely useful to be able to walk the node tree backwards (starting from leafs up to the parent) and apply transformations to each node visited.

**Describe alternatives you've considered**

Our current approach looks something like this:

```python
def transformer(node):
    if isinstance(node, exp.Anonymous) and node.name == "ARBITRARY":
        # Here we apply the recursive transform to the child expr to not skip it
        expr = node.args["expressions"][0].transform(transformer).sql(dialect="spark")
        return parse_one(f"first({expr}, True)", read="spark")

sql = sqlglot.transpile("SELECT arbitrary(arbitrary(foo))", read="trino", write="spark")[0]
transformed_sql = sql.transform(transformer)
```

We need to call `transform` on the child since the parent is transformed first and the children would be skipped after the parents transformation. Without this, chained functions like `arbitrary(arbitrary(foo))` are not transformed correctly since the inner `arbitrary` is ignored.

**Additional context**

**Comment by GeorgeSittas** [comment]
I think you can use `replace_children` to do what you're suggesting. Take a look at `canonicalize.py::canonicalize`.

**Comment by barakalon** [comment]
You can also walk the expression in reverse, replacing nodes in-place:

```python
sql = sqlglot.parse_one("SELECT arbitrary(arbitrary(foo))", read="trino")

for node, *_ in reversed(list(sql.walk())):
    if isinstance(node, exp.Anonymous) and node.name.upper() == "ARBITRARY":
        node.replace(exp.func("FIRST", node.expressions[0].copy(), exp.true()))
```
