### ISSUE TITLE
not working for separator getting parsing error ; 

### ISSUE THREAD

**Issue by ninja96826** [tobymao/sqlglot#1939]
sql query - CREATE OR REPLACE
VIEW data_view AS
select
    id AS client_id,
    substring_index(group_concat(coach_id order by created DESC separator ','), ',', 1) AS s_id
from
    user ucm
where
    (ucm.event_status in (1, 3));

error - raise error
sqlglot.errors.ParseError: Expecting ). Line 6, Col: 73.
  view AS
select
    id AS client_id,
    substring_index(group_concat(coach_id order by created DESC separator ','), ',', 1) AS s_id
from
    user ucm
where
    (ucm.event_status in (1, 3));

**Comment by GeorgeSittas** [comment]
Hello,

What dialect is this? Please make sure to include documentation related to the issue at hand.

**Comment by ninja96826** [comment]
sorry for not mentioning above  its mysql dialect,

for select in parse_one(sql, read="mysql").find_all(exp.Select):
    for projection in select.expressions:
        print(f"columns alias used in select : {projection.alias_or_name}")

**Comment by ninja96826** [comment]
my bad you can close this issue.
