### ISSUE TITLE
Spark to DuckDB 'datediff' transpilation error

### ISSUE THREAD

**Issue by richard-a-lott** [tobymao/sqlglot#1943]
Possibly related to #1929 

Getting an issue transpiling from Spark to DuckDB, the 'datediff' function is transpiling correctly to "date_diff" but the period parameter is being returned as "None" instead of "Day".

Source sql:
![image](https://github.com/tobymao/sqlglot/assets/136445689/329dbe3d-8e7b-452e-9557-35747a054075)

Expected:
![image](https://github.com/tobymao/sqlglot/assets/136445689/c8ee6801-18fc-425e-9666-57b2ce577a4f)

Actual:
![image](https://github.com/tobymao/sqlglot/assets/136445689/a730cfd3-bf57-44cf-b977-b545df53de79)

Can you take a look please.

**Comment by GeorgeSittas** [comment]
Will take a look, thanks for the report
