### ISSUE TITLE
Support for calculation in value part of DATE_SUB

### ISSUE THREAD

**Issue by bobvanratingen** [tobymao/sqlglot#195]
It's not possible to do the following with the DATE_SUB function:

INTERVAL 28 * 12 DAY
INTERVAL 30 + 1 DAY

**Comment by tobymao** [comment]
what languages is this legal in? for example trying postgres, it only works with strings '12' day

**Comment by tobymao** [comment]
v3.0.7

**Comment by bobvanratingen** [comment]
> It's not possible to do the following with the DATE_SUB function:

I know you can do it for bigquery
