### ISSUE TITLE
error in optimizer.qualify with mixed identifier quotation.

### ISSUE THREAD

**Issue by push2prod** [tobymao/sqlglot#1950]
**Fully reproducible code snippet**:
```
from sqlglot import parse_one
from sqlglot.dialects.oracle import Oracle
from sqlglot.lineage import lineage
from sqlglot.optimizer.qualify import qualify

parser = Oracle()

sql = """
with base as
(

    select x.dummy as COL_1
    from dual x
)
select b."COL_1"
from base b
"""

ast = parse_one(sql, read=parser)
qualified = qualify(
        ast,
        dialect=parser,
        schema=None,
    )

```
error:
```
Exception has occurred: OptimizeError
Unknown column: COL_1
  File "C:\Users\itay5\Desktop\work\sql\main.py", line 20, in <module>
    qualified = qualify(
                ^^^^^^^^
sqlglot.errors.OptimizeError: Unknown column: COL_1
```
I get the same error while trying to use identify=False, and still no luck.

**Comment by GeorgeSittas** [comment]
Hey, have you verified whether this query is valid in Oracle SQL? If it is, it might be a bug on our end w.r.t. how we've implemented Oracle's identifier resolution rules, so additional documentation on this topic would be much appreciated.

**Comment by push2prod** [comment]
> Hey, have you verified whether this query is valid in Oracle SQL? If it is, it might be a bug on our end w.r.t. how we've implemented Oracle's identifier resolution rules, so additional documentation on this topic would be much appreciated.

Yeah I've verified with live SQL of oracle, couldn't link to it because it requires a user to log in. I'll try to look for some documentation

**Comment by GeorgeSittas** [comment]
Interesting, so it seems like Oracle has the same resolution semantics as Snowflake:

> Nonquoted identifiers are not case sensitive. Oracle interprets them as uppercase. Quoted identifiers are case sensitive.

I'll fix this, thanks for the report.
