### ISSUE TITLE
Parser Error on Top N in Snowflake SQL

### ISSUE THREAD

**Issue by BBischof** [tobymao/sqlglot#1955]
I'm using the Table identification code snippet from the README:

```
tables = [
    table.name for table in parse_one(sql_as_string, read="snowflake").find_all(exp.Table)
]
```
and I'm getting this ParserError:

```
ParseError: Invalid expression / Unexpected token. Line 1, Col: 12.
  SELECT TOP 50
    ii.PRODUCT_ID,
    ii.PRODUCT_NAME,
    ii.PRODUCT_BRAND,
    ii.PRODUCT_CATEGORY,
    COUNT(oi
```

I have confirmed that this query is valid by running it against my snowflake database. Here's the full SQL statement

```
SELECT TOP 50
    ii.PRODUCT_ID,
    ii.PRODUCT_NAME,
    ii.PRODUCT_BRAND,
    ii.PRODUCT_CATEGORY,
    COUNT(oi.ID) AS order_volume,
    AVG(oi.SALE_PRICE - ii.COST) AS average_profit
FROM
    DEMO_DATA.ECOMMERCE.ORDER_ITEMS AS oi
INNER JOIN
    DEMO_DATA.ECOMMERCE.INVENTORY_ITEMS AS ii
    ON
        oi.INVENTORY_ITEM_ID = ii.ID
GROUP BY
    ii.PRODUCT_ID,
    ii.PRODUCT_NAME,
    ii.PRODUCT_BRAND,
    ii.PRODUCT_CATEGORY
ORDER BY
    order_volume DESC;
```

Any suggestions would be appreciated

**Comment by BBischof** [comment]
One thing that raises my suspicion is that I get the exact row and column (1, 12) for other SQL statements it claims are invalid (but are confirmed valid)

**Comment by BBischof** [comment]
From a bit more poking; I'm reasonably confident that this is because SQLglot doesn't know about `top N` in Snowflake: https://docs.snowflake.com/en/sql-reference/constructs/top_n

**Comment by tobymao** [comment]
I cannot reproduce this, it works fine for me, make sure you're on the latest version of SQLGlot.

**Comment by BBischof** [comment]
@tobymao on most recent version; are you saying that if you ask SQLglot to find the tables in the pasted query it works just fine?
