### ISSUE TITLE
getting error for foreign key constrain for mysql 

### ISSUE THREAD

**Issue by ninja96826** [tobymao/sqlglot#1959]
code =  from sqlglot import parse_one,dialects
sql = """
CREATE TABLE IF NOT EXISTS `industry_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `industry_id` bigint(20) NOT NULL,
  `industry_column_1` varchar(1000) ,
  `industry_column_2` varchar(1000) ,
  `industry_column_3` varchar(1000) ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_industry_id` (`industry_id`),
  KEY `fk_industry_info_id` (`industry_id`)
) ;
     """
s = parse_one(sql, dialect = dialects.Dialects.MYSQL)
print(s)

error        -        raise error
sqlglot.errors.ParseError: Expecting ). Line 10, Col: 27.
  n_3` varchar(1000) ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_industry_id` (`industry_id`),
  KEY `fk_industry_info_id` (`industry_id`)
) ;
**mainly the error is because of this foreign key constraint line   KEY `fk_industry_info_id` (`industry_id`)**

**Comment by GeorgeSittas** [comment]
Will take a look soon
