### ISSUE TITLE
Trino's `is_nan()` is traslated wrong to SparkSQL

### ISSUE THREAD

**Issue by dmelchor-stripe** [tobymao/sqlglot#1964]
**Fully reproducible code snippet**

```python
transpile("SELECT is_nan(DOUBLE 'NaN')", read="trino", write="spark")[0]
```

Results in

```sql
SELECT IS_NAN(CAST('NaN' AS DOUBLE))
```

But should result in:
```sql
SELECT ISNAN(CAST('NaN' AS DOUBLE))
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.
https://spark.apache.org/docs/latest/api/sql/index.html#isnan

**Comment by tobymao** [comment]
@dmelchor-stripe thanks for these issues, they are relatively simple, feel free to make prs in the future
