### ISSUE TITLE
Parsing tsql stored proc with declare variable

### ISSUE THREAD

**Issue by bayees** [tobymao/sqlglot#1966]
**Error description**
I get the following sqlglot.errors.ParseError: Invalid expression / Unexpected token Line 4, Col: 28. which is the datatype varchar. 

I have look through the library and testet with and without the variable and it might be related to the way that the chunks is made when parsing. 

**Fully reproducible code snippet**
```sql
from sqlglot import parse_one, exp

sql = """
CREATE PROC [dbo].[transform_proc] AS 

DECLARE @CurrentDate VARCHAR(20);
SET @CurrentDate = CONVERT(VARCHAR(20), GETDATE(), 120);

CREATE TABLE [target_schema].[target_table]
WITH (DISTRIBUTION = REPLICATE, HEAP)
AS 

SELECT 
	@CurrentDate AS DWCreatedDate
FROM source_schema.sourcetable;
"""

for table in parse_one(sql, dialect='tsql').find_all(exp.Table):
    print(table.db + '.' + table.name)
```

**Official Documentation**
https://learn.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-develop-ctas

**Comment by GeorgeSittas** [comment]
Don't you need to use the `;` separator between the `PROC`'s statements?

**Comment by bayees** [comment]
Not needed, but bast practice. Same resultat though.
