### ISSUE TITLE
MySQL tokenizer errors on "IS ?"

### ISSUE THREAD

**Issue by SoftwareGuy2020** [tobymao/sqlglot#1975]
Hello,
I am trying out sqlglot and ran into an error when testing various parameterized mysql queries.

The following works just fine
```
query = "SELECT a FROM b WHERE c IS TRUE;"
parse_one(query, dialect='mysql')

query = "SELECT a FROM b WHERE c = ?;"
parse_one(query, dialect='mysql')
```

But when a placeholder is used with the `IS` operator it errors.
```
query = "SELECT a FROM b WHERE c IS ?;"
parse_one(query, dialect='mysql')
```
The error
```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 26.
  SELECT a FROM b WHERE c IS ?;
```

I tried searching around the closed issues to see if this was previously discussed, as well as in slack, but I wasn't able to find anything.

Any ideas what's going on? Is this intentional?

EDIT: grammar

**Comment by SoftwareGuy2020** [comment]
UPDATE: I tried wrapping `IS ?` with parantheses as a last ditch attempt, and that worked.
```
query = "SELECT a FROM b WHERE c (IS ?);"
parse_one(query, dialect='mysql')
```
Follow up question is why? The MySQL documentation on the IS operator doesn't specify needing these parentheses
https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#operator_is

**Comment by GeorgeSittas** [comment]
The parenthesized query is parsed differently and is ultimately an ill-informed one. This one was a bug on our end.

**Comment by SoftwareGuy2020** [comment]
Oh interesting! Thank you for the incredibly fast response and fix. 
When you say that the parenthesized query is ill-formed, should I be avoiding that type of query then?

**Comment by GeorgeSittas** [comment]
It's just my guess is that `SELECT a FROM b WHERE c (IS ?)` is invalid in MySQL. Does it execute it successfully?

**Comment by SoftwareGuy2020** [comment]
Good question. Performed a quick toy example on my mysql server to see
```
mysql> create table temp (id int, name varchar(10), valid bool);
Query OK, 0 rows affected (0.12 sec)

mysql> describe temp;
+-------+-------------+------+-----+---------+-------+
| Field | Type        | Null | Key | Default | Extra |
+-------+-------------+------+-----+---------+-------+
| id    | int         | YES  |     | NULL    |       |
| name  | varchar(10) | YES  |     | NULL    |       |
| valid | tinyint(1)  | YES  |     | NULL    |       |
+-------+-------------+------+-----+---------+-------+
3 rows in set (0.06 sec)

mysql> insert into temp values(1, "john", TRUE);
Query OK, 1 row affected (0.06 sec)

mysql> insert into temp values(2, "adam", FALSE);
Query OK, 1 row affected (0.06 sec)

mysql> select name from temp where (valid is TRUE);
+------+
| name |
+------+
| john |
+------+
1 row in set (0.06 sec)
```

So it turns out it is valid, but yea I agree it looks bad.

Anyway, thank you for taking care of this.

**Comment by GeorgeSittas** [comment]
You might've made a typo, but the original parenthesized query you posted above is different. Notice how you've fed `(valid is TRUE)` in MySQL, but the original one was `c (IS ?)`.

**Comment by SoftwareGuy2020** [comment]
Oh! good catch! Let me try that again. Hang on.

**Comment by SoftwareGuy2020** [comment]
Yup you're completely right it is invalid
```
mysql> select name from temp where valid (is TRUE);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'is TRUE)' at line 1
```
