### ISSUE TITLE
Problem with parsing Teradata COLLECT STATISTICS command

### ISSUE THREAD

**Issue by MarkBell920** [tobymao/sqlglot#1978]
I have found a problem parsing the COLLECT STATISTICS command in Teradata.  
All variations of the COLLECT STATISTICS command fail

COLLECT STATISTICS ON TABLE1
INDEX(COL1);

COLLECT STATS
ON TABLE1
COLUMNS(COL1);

COLLECT STATS ON TABLE1
COLUMNS(COL1);

COLLECT STATS
COLUMNS(COL1)
ON TABLE1;

sqlglot Version: 17.4.1
Teradata version 17.10

Error message is 

File ~\AppData\Roaming\Python\Python311\site-packages\sqlglot\parser.py:946, in Parser._parse(self, parse_method, raw_tokens, sql)
    943     expressions.append(parse_method(self))
    945     if self._index < len(self._tokens):
--> 946         self.raise_error("Invalid expression / Unexpected token")
    948     self.check_errors()
    950 return expressions

File ~\AppData\Roaming\Python\Python311\site-packages\sqlglot\parser.py:987, in Parser.raise_error(self, message, token)
    975 error = ParseError.new(
    976     f"{message}. Line {token.line}, Col: {token.col}.\n"
    977     f"  {start_context}\033[4m{highlight}\033[0m{end_context}",
   (...)
    983     end_context=end_context,
    984 )
    986 if self.error_level == ErrorLevel.IMMEDIATE:
--> 987     raise error
    989 self.errors.append(error)

or 

File ~\AppData\Roaming\Python\Python311\site-packages\sqlglot\parser.py:946, in Parser._parse(self, parse_method, raw_tokens, sql)
    943     expressions.append(parse_method(self))
    945     if self._index < len(self._tokens):
--> 946         self.raise_error("Invalid expression / Unexpected token")
    948     self.check_errors()
    950 return expressions

File ~\AppData\Roaming\Python\Python311\site-packages\sqlglot\parser.py:987, in Parser.raise_error(self, message, token)
    975 error = ParseError.new(
    976     f"{message}. Line {token.line}, Col: {token.col}.\n"
    977     f"  {start_context}\033[4m{highlight}\033[0m{end_context}",
   (...)
    983     end_context=end_context,
    984 )
    986 if self.error_level == ErrorLevel.IMMEDIATE:
--> 987     raise error
    989 self.errors.append(error)

ParseError: Invalid expression / Unexpected token. Line 2, Col: 16.
  
COLLECT STATS ON TABLE1
COLUMNS(COL1);

**Comment by GeorgeSittas** [comment]
Hey, thanks for the report. Could you please provide any related documentation for this command?

**Comment by treysp** [comment]
I think this has the full syntax definition https://docs.teradata.com/r/SQL-Data-Definition-Language-Syntax-and-Examples/March-2019/Statistics-Statements/COLLECT-STATISTICS-Optimizer-Form

**Comment by GeorgeSittas** [comment]
Thanks Trey! I think I might just parse it as a `Command` after all for now since it's very Teradata-specific (and based on the spec could be a bit complicated to add in one go).
