### ISSUE TITLE
Support parsing UDF definition in Databricks SQL

### ISSUE THREAD

**Issue by xinglin-zhao** [tobymao/sqlglot#1980]
**Is your feature request related to a problem? Please describe.**
context: UDF definition on Databricks: https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-create-sql-function.html#create-python-functions

Tried to use sqlglot to parse a creation sql, but no luck:
```
from sqlglot import parse_one, expressions
def_func = """CREATE OR REPLACE FUNCTION my_catalog.my_schema.greet(s STRING)
RETURNS STRING
LANGUAGE SQL
CONTAINS SQL
RETURN s"""

parse_one(def_func)
```
`parse_one` gives a parse error:
```
ParseError: Invalid expression / Unexpected token. Line 5, Col: 6.
  CE FUNCTION my_catalog.my_schema.greet(s STRING)
RETURNS STRING
LANGUAGE SQL
CONTAINS SQL
[4mRETURN[0m s
```

**Describe the solution you'd like**
I hope sqlglot will be able to parse the FUNCTION creation sql, recognize it's about FUNCTION, and find out elements such as catalog, database, function name, etc.

**Comment by tobymao** [comment]
not a priority for us but happy to accept a pr
