### ISSUE TITLE
invalid transpilation of clickhouse `isNaN` function

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#1982]
**Fully reproducible code snippet**

```
In [9]: import sqlglot as sg

In [10]: sg.__version__
Out[10]: '17.8.6'

In [11]: sg.parse_one("select isNaN(1.0)", read="clickhouse").sql(dialect="clickhouse")
Out[11]: 'SELECT IS_NAN(1.0)'
```

Expected output is:

```
Out[11]: 'SELECT isNaN(1.0)'
```

**Official Documentation**

https://clickhouse.com/docs/en/sql-reference/functions/other-functions#isnanx

Is there a way I can disable function normalization for any and all function calls for clickhouse?

These incorrect translation bugs keep popping up and I'd like for function calls to pass through unchanged if possible.

**Comment by cpcloud** [comment]
Looks like `startsWith` is another example with 17.8.6

**Comment by GeorgeSittas** [comment]
> Is there a way I can disable function normalization for any and all function calls for clickhouse?

I thought we already had already switched off function name normalization for clickhouse:

https://github.com/tobymao/sqlglot/blob/be7d4e6f7da143c4eac6f9ad389d088c582b2d03/sqlglot/dialects/clickhouse.py#L24

Could be a bug on our end, I'll try to resolve it asap. Thanks for the report!

**Comment by cpcloud** [comment]
Awesome, thank you!
