### ISSUE TITLE
Failed to parse escaped punctuation mark

### ISSUE THREAD

**Issue by ShayYaari** [tobymao/sqlglot#1986]
Hi!

I get an error when trying to parse a query contains an escaped punctuation mark.

Example:

`
sqlglot.parse("SELECT 'I wasn\'t there' AS cc")
`

It seems like an issue in the tokenizing stage.

ValueError: Error tokenizing 'SELECT 'I wasn't there' AS c'

**Comment by mpf82** [comment]
The default way to escape a single quote is to double it.

Escaping a single quote with a backslash is a MySQL thing.

So either use doubled single quotes, or specify the dialect:

```python
sqlglot.parse(r"SELECT 'I wasn''t there' AS cc")
sqlglot.parse(r"SELECT 'I wasn\'t there' AS cc", read="mysql")
```

**Comment by ShayYaari** [comment]
Thank you @mpf82 
I found it in a Spark dialect.

**Comment by GeorgeSittas** [comment]
@ShayYaari you need to specify the input dialect and either escape the backslash itself or use a raw string, as Mike already suggested. This is a python issue, not a SQLGlot one:

```python
>>> import sqlglot
>>> sqlglot.__version__
'17.9.1.dev1'
>>>
>>> sqlglot.transpile(r"SELECT 'I wasn\'t there' AS cc", read="mysql")
["SELECT 'I wasn''t there' AS cc"]
```
