### ISSUE TITLE
pr checks failed

### ISSUE THREAD

**Issue by liujiwen-up** [tobymao/sqlglot#2000]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 
- When submitting PR, the check did not pass, how should I adjust it? https://github.com/tobymao/sqlglot/pull/1999
Run make check
pre-commit run --all-files
autoflake................................................................Failed
- hook id: autoflake
- files were modified by this hook
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /home/runner/work/sqlglot/sqlglot/sqlglot/dialects/__init__.py
Fixing /home/runner/work/sqlglot/sqlglot/sqlglot/dialects/doris.py

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted sqlglot/dialects/doris.py

All done! ✨ 🍰 ✨
1 file reformatted, [13](https://github.com/tobymao/sqlglot/actions/runs/5784488537/job/15675269297?pr=1999#step:5:14)5 files left unchanged.

mypy.....................................................................Passed
make: *** [Makefile:[19](https://github.com/tobymao/sqlglot/actions/runs/5784488537/job/15675269297?pr=1999#step:5:20): style] Error 1
Error: The operation was canceled.
**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by GeorgeSittas** [comment]
You should run `make style && make unit` before pushing a commit.
