### ISSUE TITLE
Optimizer alias expansion does not wrap expanded expressions

### ISSUE THREAD

**Issue by z3z1ma** [tobymao/sqlglot#2003]
**Is your feature request related to a problem? Please describe.**
Lateral alias / derived column expansion interpolates the column SQL as-is. This results in surprising behavior as it messes up operator precedence which should be consistent **per expression**. When using this feature the alias should be equivalent to the result of the derived column. 

**Describe the solution you'd like**
Lateral alias expansion should wrap the interpolated column in parentheses.

**Describe alternatives you've considered**
Wrap things myself to ensure intended precedence. Error prone.

**Additional context**
```sql
select
  a.x + a.y as f,
  f * a.z
from a
```
Expands to
```sql
select
  a.x + a.y as f,
  a.x + a.y * a.z
from a
```

To get consistent results as other databases (snowflake, teradata, etc) you would require this, which is more correct
```sql
select
  a.x + a.y as f,
  (a.x + a.y) * a.z
from a
```

I can say this has bitten me in the foot already leaning on this optimizer feature in bigquery.

**Comment by GeorgeSittas** [comment]
Thanks for reporting this, Alex. I'll take a look shortly.
