### ISSUE TITLE
Translation fails on datetime handling across dialect

### ISSUE THREAD

**Issue by pramitchoudhary** [tobymao/sqlglot#2011]
Hi there,
Recently ran into this error. Sharing in-case there are additional thoughts. Still thinking about how to handle it.

E.g. 
Input dialect sqlite: `SELECT DATETIME(MAX(timestamp), '-5 minutes') FROM demo WHERE id = '88109';`
Expected output: `SELECT MAX(timestamp) - INTERVAL '5 minutes' FROM demo where id = '88109';`

Returned: `SELECT DATETIME(MAX(timestamp), '-5 minutes') FROM demo WHERE isin_id = '88109'`

```
import sqlglot
res = sqlglot.transpile("SELECT DATETIME(MAX(timestamp), '-5 minutes') FROM demo WHERE id = '88109'",
                  read="sqlite", write="postgres")[0]
```

cc @narasimhard

**Comment by GeorgeSittas** [comment]
Hey, thanks for the report. We'll take a look soon.
