### ISSUE TITLE
Some questions about project code calls.

### ISSUE THREAD

**Issue by echo-hhj** [tobymao/sqlglot#2013]
I would like to ask about some functions that are not implemented in the dialect, but can be translated to other dialects, for example, there is no parsing of STANDARD_HASH in oracle, but as long as I support exp.StandardHash in other dialects, I will be able to convert oracle to STANDARD_HASH to the corresponding function in another dialect, which is a bit confusing to me, how does this work? If I want to convert a dialect, how do I know which functions are supported by the dialect itself? Please clarify my confusion.

**Comment by tobymao** [comment]
if you want to convert a function, you need to make a first class expression, have dialect A parse the function by name into the expression, and then have dialect b generate it.

there are many examples of this

https://github.com/tobymao/sqlglot/commit/661a1403bea3951f330a89a5903ce5f05b0ab871#diff-7857fedd1d1451b1b9a5b8efaa1cc292c02e7ee4f0d04d7e2f9d5bfb9565802cR2620
