### ISSUE TITLE
Bug in transpiling?

### ISSUE THREAD

**Issue by awakim** [tobymao/sqlglot#2014]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
    - not applicable
- Check if the issue still exists on main:
    - does not

*SQLGLOT version*: `sqlglot==17.10.2`
I'm trying to raise parsing errors as suggested by the docs. Unless I'm missing something (which I might be tbh), the following code does not raise anything.
What am I doing wrong? Is the documentation up to date? 

Sorry for the inconvenience and thank you for your time.

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected out

input:
```python
import sqlglot
try:
    sqlglot.transpile("SELECT foo( FROM bar")
except sqlglot.errors.ParseError as e:
    print(e.errors)
```

expected output:
```python
[{
  'description': 'Expecting )',
  'line': 1,
  'col': 16,
  'start_context': 'SELECT foo( ',
  'highlight': 'FROM',
  'end_context': ' bar',
  'into_expression': None,
}]
```

Actual output:
empty! ⚠️ 

**Official Documentation**
Please include links to official SQL documentation related to your issue.

https://github.com/tobymao/sqlglot

**Comment by GeorgeSittas** [comment]
Hey 👋

As mentioned in the README, SQLGlot's not supposed to be a SQL validator:

> Syntax [errors](https://github.com/tobymao/sqlglot#parser-errors) are highlighted and dialect incompatibilities can warn or raise depending on configurations. However, it should be noted that SQL validation is not SQLGlot’s goal, so some syntax errors may go unnoticed.

The reason this parses is that the underlying logic is probably more lenient than a strict parser to easily capture more complex syntax forms without introducing unnecessary syntax validating logic.

**Comment by awakim** [comment]
Thanks for the quick answer. 

If reverting is not possible for obvious reasons, would you mind pointing me to a version matching the current doc
Thanks!

**Comment by GeorgeSittas** [comment]
Yeah, taking a look and will provide and update on this shortly. The rest of the README should be up-to-date, I believe.

**Comment by awakim** [comment]
Alrighty! Thank you for that!
