### ISSUE TITLE
Support additional duckdb data types

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2022]
I've started work to move our type parser in ibis from parsy to sqlglot for performance reasons: sqlglot is much much faster.

sqlglot is missing a few types that we previously supported (parsing metadata that come back from DuckDB's `DESCRIBE` directive) and while these aren't blocks because they are simple to intercept, it would be nice if sqlglot supported some or all of these.

**Is your feature request related to a problem? Please describe.**

Not related to a problem.

Here's the list of types that are currently supported by ibis and potentially returned from duckdb's `DESCRIBE` that aren't supported in sqlglot:

- `INT128`
- `HUGEINT`
- `NUMERIC` with no precision or scale arguments
- `TIMESTAMP_SEC`
- `TIMESTAMP_S`
- `TIMESTAMP_MS`
- `TIMESTAMP_US`
- `TIMESTAMP_NS`
- `TIMESTAMP_TZ`

**Describe the solution you'd like**

- `INT128`, `HUGEINT` -> `DataType.Type.INT128`
- `NUMERIC` -> `DECIMAL(18, 3)` DuckDB's default precision and scale
- `TIMESTAMP_*` -> ? not sure if these have an exact sqlglot equivalent

**Describe alternatives you've considered**

I've implemented the only viable alternative I can think of, which is to handle these strings before passing the text to sqlglot.

**Additional context**

NA

**Comment by GeorgeSittas** [comment]
> I've started work to move our type parser in ibis from parsy to sqlglot for performance reasons: sqlglot is much much faster.

That's great! :-)

I'll have a look and let you know once there's an update.

**Comment by GeorgeSittas** [comment]
FYI seems like `TIMESTAMP_SEC` does not exist, at least in duckdb v0.8.0:

```python
>>> import duckdb
>>> duckdb.connect().execute("select cast('2020-01-01' as timestamp_sec)").fetchdf()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.CatalogException: Catalog Error: Type with name timestamp_sec does not exist!
Did you mean "timestamp_s"?
```

Also, seems like `TIMESTAMP_TZ` is actually named `TIMESTAMPTZ`, which I believe we already handle correctly:

```python
>>> import sqlglot
>>> import duckdb
>>>
>>> sqlglot.parse_one("cast(x as timestamptz)", "duckdb")
(CAST this:
  (COLUMN this:
    (IDENTIFIER this: x, quoted: False)), to:
  (DATATYPE this: Type.TIMESTAMPTZ, nested: False, prefix: False))
>>>
>>> sqlglot.transpile("cast(x as timestamptz)", "duckdb")
['CAST(x AS TIMESTAMPTZ)']
>>>
>>> duckdb.connect().execute("select cast('2020-01-01' as timestamp_tz)").fetchdf()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.CatalogException: Catalog Error: Type with name timestamp_tz does not exist!
Did you mean "timestamptz"?
>>>
>>> duckdb.connect().execute("select cast('2020-01-01' as timestamptz)").fetchdf()
  CAST('2020-01-01' AS TIMESTAMP WITH TIME ZONE)
0                      2019-12-31 22:00:00+00:00
```

The other `TIMESTAMP_*` types all work fine in DuckDB but I'm not sure what they mean because they don't seem to be documented:

```python
>>> import duckdb
>>> duckdb.connect().execute("select cast('2020-01-01' as timestamp_ms)").fetchdf()
  CAST('2020-01-01' AS TIMESTAMP_MS)
0                         2020-01-01
>>> duckdb.connect().execute("select cast('2020-01-01' as timestamp_us)").fetchdf()
  CAST('2020-01-01' AS TIMESTAMP)
0                      2020-01-01
>>> duckdb.connect().execute("select cast('2020-01-01' as timestamp_ns)").fetchdf()
  CAST('2020-01-01' AS TIMESTAMP_NS)
0                         2020-01-01
```

**Comment by GeorgeSittas** [comment]
Gotcha, I'll get what I have in for now then!

**Comment by cpcloud** [comment]
It does seem like you can get type information:

```
D describe select now()::timestamp_ns;
┌─────────────────────────────┬──────────────┬─────────┬─────────┬─────────┬─────────┐
│         column_name         │ column_type  │  null   │   key   │ default │  extra  │
│           varchar           │   varchar    │ varchar │ varchar │ varchar │ varchar │
├─────────────────────────────┼──────────────┼─────────┼─────────┼─────────┼─────────┤
│ CAST(now() AS TIMESTAMP_NS) │ TIMESTAMP_NS │ YES     │         │         │         │
└─────────────────────────────┴──────────────┴─────────┴─────────┴─────────┴─────────┘
```

... but you can't create a table 😕 

```
D create table t as select now()::timestamp_ns;
Error: Conversion Error: Unimplemented type for cast (TIMESTAMP WITH TIME ZONE -> TIMESTAMP_NS)
```

**Comment by GeorgeSittas** [comment]
I see, perhaps it's a type useful only in the context of `DESCRIBE` then?

**Comment by cpcloud** [comment]
Ok, it turns out I may have been using this incorrectly. These types are valid for use in expressions:

```
❯ duckdb
v0.8.1
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table t as select now()::timestamp::timestamp_ns as now;
D describe t;
┌─────────────┬──────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name │ column_type  │  null   │   key   │ default │ extra │
│   varchar   │   varchar    │ varchar │ varchar │ varchar │ int32 │
├─────────────┼──────────────┼─────────┼─────────┼─────────┼───────┤
│ now         │ TIMESTAMP_NS │ YES     │         │         │       │
└─────────────┴──────────────┴─────────┴─────────┴─────────┴───────┘
```

@GeorgeSittas Should I create a new issue for this?

**Comment by GeorgeSittas** [comment]
What do you mean you were using it incorrectly?

**Comment by GeorgeSittas** [comment]
Ok I see what you mean, do you wanna take a stab at this?

**Comment by GeorgeSittas** [comment]
Perhaps https://github.com/tobymao/sqlglot/commit/36f308e80253d4c6b13232f21a5fd221d0757fb5 can help, you need to add a token, map the uppercase string version of the type to that token in duckdb etc.
