### ISSUE TITLE
`time(precision) with time zone` is parsed incorrectly into `TIMESTAMPTZ`

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2028]
**Fully reproducible code snippet**

```
In [7]: import sqlglot as sg

In [8]: sg.__version__
Out[8]: '17.9.1'

In [9]: sg.parse_one("time(7) with time zone", into=sg.exp.DataType, read="trino")
Out[9]:
(DATATYPE this: Type.TIMESTAMPTZ, expressions:
  (DATATYPESIZE this:
    (LITERAL this: 7, is_string: False)))
```

**Official Documentation**

The specific combination of `time (P) with time zone` [isn't documented](https://trino.io/docs/current/language/types.html#time-with-time-zone), but using `trino-cli` it's supported:

```
trino:default> create table t (x time (3) with time zone);
CREATE TABLE
trino:default> drop table t; create table t (x time with time zone);
CREATE TABLE
```

sqlglot also incorrectly returns `TIMESTAMPTZ` for `time with time zone`

**Comment by GeorgeSittas** [comment]
Will take a look at both this and #2027 soon, thanks
