### ISSUE TITLE
Support for parsing ClickHouse `Nested` type

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2030]
**Is your feature request related to a problem? Please describe.**

Not related to a problem.

**Describe the solution you'd like**

I'd like `Nested` to be parsed into an array of struct. This seems like the right approach looking at [the documentation](https://clickhouse.com/docs/en/sql-reference/data-types/nested-data-structures/nested).

**Describe alternatives you've considered**

I haven't considered any alternatives

**Additional context**

N/A

**Comment by GeorgeSittas** [comment]
> I'd like Nested to be parsed into an array of struct

@cpcloud I parsed it into a `NESTED` type for now; is that what you mean?

**Comment by cpcloud** [comment]
I think `NESTED` should work.

What I meant is that in ClickHouse `Nested` types behave like arrays of structs. So,

```
Nested(a Int32, b String)
```

behaves like

```
Array(Tuple(a Int32, b String))
```

**Comment by GeorgeSittas** [comment]
That makes sense, but I'm skeptical as to whether this will always be a correct conversion for ClickHouse: perhaps some functions expect only `Nested` and not `Array(Tuple(...))`? And since `Array(Tuple(...))` is also a valid type in ClickHouse, you can't really always treat it as a `Nested`, too.

**Comment by cpcloud** [comment]
True! That's a good point and I vaguely recall that being the case in practice. In any event, thanks for the quick turnaround.
