### ISSUE TITLE
Support for parsing `timestamp with/without time zone[]` and `time with/without time zone[]` with postgres

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2034]
**Is your feature request related to a problem? Please describe.**

Not related to a problem.

**Describe the solution you'd like**

I'd like sqlglot to support parsing the `timestamp without time zone[]` and `time without time zone[]` types for the postgres dialect.

**Describe alternatives you've considered**

I haven't considered any alternatives

**Additional context**

Proof that this is a thing :)

```
ibis_testing> create table t (x timestamp without time zone []);
CREATE TABLE
Time: 0.009s
```

**Comment by tobymao** [comment]
can you share the docs for this @cpcloud

**Comment by cpcloud** [comment]
```
ibis_testing> select cast(array['2022-01-01'] as timestamp without time zone[]);
+-------------------------+
| array                   |
|-------------------------|
| ['2022-01-01 00:00:00'] |
+-------------------------+
```

You need to wrap it in the array constructor :)

**Comment by cpcloud** [comment]
The [arrays docs](https://www.postgresql.org/docs/current/arrays.html) say

> PostgreSQL allows columns of a table to be defined as variable-length multidimensional arrays. Arrays of any built-in or user-defined base type, enum type, composite type, range type, or domain can be created.

Since `timestamp without time zone` is a built in type, it would follow that `timestamp without time zone[]` is a valid array type.
