### ISSUE TITLE
ParserError when use OVER for Hive and Spark dialect

### ISSUE THREAD

**Issue by eiphy** [tobymao/sqlglot#2043]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark") | Yes I use read="hive"
- Check if the issue still exists on main | Yes, I tested on the main branch.

**Fully reproducible code snippet**
```python
from sqlglot import parse_one
parse_one("select ROW_NUMBER() OVER(DISTRIBUTE BY id) FROM t", read="hive")
parse_one("select ROW_NUMBER() OVER(DISTRIBUTE BY id) FROM t", read="spark")
```

**Official Documentation**
https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-window.html
https://docs.cloudera.com/HDPDocuments/HDP2/HDP-2.0.0.2/ds_Hive/language_manual/ptf-window.html

**Comment by tobymao** [comment]
what’s the difference between partition by and distribute by or are they the same?

**Comment by tobymao** [comment]
the second link you posted has no reference to distribute by

**Comment by eiphy** [comment]
> what’s the difference between partition by and distribute by or are they the same?

They are different. Distribute by adjust the allocation to reducer, e.g., send the rows with the same col value to the same reducer.

**Comment by tobymao** [comment]
i don't think that's right, that link is for select * from x SORT BY y, that's not the same as a window function

**Comment by eiphy** [comment]
> i don't think that's right, that link is for select * from x SORT BY y, that's not the same as a window function

That's true. But I have tested on Hive 3.1.0 and the expression is executed correctly. So I guess this means this is still a valid expression?

BTW, does over(distribute by) for spark make sense to you?

**Comment by tobymao** [comment]
yes, databricks documentation confirms it's simply an alias

**Comment by eiphy** [comment]
Hi @tobymao , This issues is not resolved? I just tried on master branch but seems:
![image](https://github.com/tobymao/sqlglot/assets/46335499/cf8f14b5-d471-4ada-ae51-69e58f795ac6)

**Comment by tobymao** [comment]
you need to specify the dialect

```Before you file an issue

    Make sure you specify the "read" dialect eg. parse_one(sql, read="spark") | Yes I use read="hive"```

**Comment by eiphy** [comment]
> you need to specify the dialect
> 
> ```
> 
>     Make sure you specify the "read" dialect eg. parse_one(sql, read="spark") | Yes I use read="hive"```
> ```
@tobymao 
Sorry for that.

Another issue is the current parser does not support:
SELECT ROW() OVER (DISTRIBUTE BY x SORT BY y) FROM tb

The SORT BY clause is claimed to be the alias for order by in:
https://docs.databricks.com/en/sql/language-manual/sql-ref-window-functions.html
So I believe this should also be supported.
