### ISSUE TITLE
(oracle parse)Outer join syntax using the (+) operator is not supported

### ISSUE THREAD

**Issue by liujiwen-up** [tobymao/sqlglot#2045]
**Is your feature request related to a problem? Please describe.**
`print(sqlglot.parse_one("""SELECT *
FROM a, b, e, f, g, h, q
WHERE a.policyno = b.policyno
  AND b.registno = e.registno(+)
  AND e.claimno = f.claimno(+)
  AND e.claimno = g.claimno(+)
  AND b.registno = h.registno(+)
  AND e.claimno = q.claimno(+)""", "oracle"))

Outer join syntax using the (+) operator is not supported.

Can it be converted into the JOIN form supported by mysql?`
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tobymao** [comment]
Can you please spend more effort writing clearer issues? It's unclear what issues you're facing.

if you want (+), you can call sql(dialect="oracle"), and no it can't be converted trivially.
