### ISSUE TITLE
Support for Spark's `str_to_map` and Presto's `split_to_map`

### ISSUE THREAD

**Issue by edwinlei** [tobymao/sqlglot#2050]
**Is your feature request related to a problem? Please describe.**
[Spark](https://spark.apache.org/docs/latest/api/sql/index.html#str_to_map) and [Presto](https://trino.io/docs/current/functions/string.html?highlight=split_to_map#split_to_map) support splitting text into into key/value pairs using delimiters. This is useful when parsing text fields.

sqlglot currently parses either one into an anonymous, i.e., `sqlglot.parse_one("select str_to_map(c1, ';', '=')")` gives
```python
(SELECT expressions:
  (ANONYMOUS this: str_to_map, expressions:
    (COLUMN this:
      (IDENTIFIER this: c1, quoted: False)),
    (LITERAL this: ;, is_string: True),
    (LITERAL this: =, is_string: True)))
```

This prevents us from transpiling `str_to_map` to `split_to_map` (and vice versa).

**Comment by GeorgeSittas** [comment]
Gotcha will have a look

**Comment by edwinlei** [comment]
Sorry added more details to the description
