### ISSUE TITLE
Bug when transpiling `struct` to Presto

### ISSUE THREAD

**Issue by edwinlei** [tobymao/sqlglot#2052]
**Fully reproducible code snippet**
`sqlglot.parse_one("select struct(1, 2)").sql(dialect="presto")` returns
```sql
SELECT STRUCT(1, 2)
```
instead of 
```sql
SELECT ROW(1, 2)
```

**Comment by GeorgeSittas** [comment]
I think the issue here is that you haven't specified `"presto"` as the input dialect:

```python
>>> import qslglot
>>> sqlglot.transpile("select struct(1, 2)", "presto")
['SELECT STRUCT(1, 2)']
```

I'll go ahead and close this one but let me know if I missed something.

**Comment by GeorgeSittas** [comment]
er
