### ISSUE TITLE
Support UNNEST

### ISSUE THREAD

**Issue by bobvanratingen** [tobymao/sqlglot#206]
They following is not possible with UNNEST

```
SELECT
  *
FROM
UNNEST
  (['7', '14', '30', '45', '45+']) AS time_window
```

**Comment by tobymao** [comment]
for now, you can do unnest (ARRAY(1, 2))... i haven't seen the [a, b] notation before

**Comment by bobvanratingen** [comment]
This notation is used in BigQuery

https://cloud.google.com/bigquery/docs/reference/standard-sql/arrays#flattening_arrays

**Comment by tobymao** [comment]
yup got it, i’ll start working on full fledged support of big query tonight, thanks again for all of you’re issues, it’s very much appreciated, 

hopefully we’ll have big query support soon!

**Comment by bobvanratingen** [comment]
That's great to hear!
