### ISSUE TITLE
Snowflake parsing issue

### ISSUE THREAD

**Issue by darshan-rathi-df** [tobymao/sqlglot#2069]
**Input Sql**

```
WITH first_activity AS (
  SELECT USER_ID, MIN(TO_TIMESTAMP(EVENT_DATE)) AS first_activity_date
  FROM DF.USER_EVENTS
  GROUP BY USER_ID
)
SELECT COUNT(*) AS active_users_count
FROM first_activity
WHERE DATEDIFF(day, first_activity_date, CURRENT_TIMESTAMP()) > 90
```

I am using sqlglot transpile function in the following manner
```sqlglot.transpile(query, write="snowflake", pretty=True)[0]```

**Output Query**

```
WITH first_activity AS (
  SELECT
    USER_ID,
    MIN(TO_TIMESTAMP(EVENT_DATE)) AS first_activity_date
  FROM DF.USER_EVENTS
  GROUP BY
    USER_ID
)
SELECT
  COUNT(*) AS active_users_count
FROM first_activity
WHERE
  DATEDIFF(, first_activity_date, day) > 90
```

The output query is failing as there is a leading comma in the DATEDIFF function. Moreover I'm not sure why it changed the function signature and parameters altogether.

**Comment by GeorgeSittas** [comment]
Thanks, will look into this soon

**Comment by GeorgeSittas** [comment]
@darshan-rathi-df what's the input dialect? You should specify `read="snowflake"` in `transpile` if it's Snowflake, for example:

```python
>>> sql = """
... WITH first_activity AS (
...   SELECT USER_ID, MIN(TO_TIMESTAMP(EVENT_DATE)) AS first_activity_date
...   FROM DF.USER_EVENTS
...   GROUP BY USER_ID
... )
... SELECT COUNT(*) AS active_users_count
... FROM first_activity
... WHERE DATEDIFF(day, first_activity_date, CURRENT_TIMESTAMP()) > 90
... """
>>>
>>> import sqlglot
>>>
>>> print(sqlglot.transpile(sql, "snowflake", pretty=True)[0])
WITH first_activity AS (
  SELECT
    USER_ID,
    MIN(TO_TIMESTAMP(EVENT_DATE, 'yyyy-mm-DD hh24:mi:ss')) AS first_activity_date
  FROM DF.USER_EVENTS
  GROUP BY
    USER_ID
)
SELECT
  COUNT(*) AS active_users_count
FROM first_activity
WHERE
  DATEDIFF(day, first_activity_date, CURRENT_TIMESTAMP()) > 90
```

**Comment by vishaldas-datafacade** [comment]
@GeorgeSittas 
In the same script, I see sqlglot.transpile is changing the argument inside TO_TIMESTAMP function to an incorrect form. This looks like a bug to me. 


Snowflake function TO_TIMESTAMP only takes 1 argument. 
`SELECT USER_ID, MIN(TO_TIMESTAMP(EVENT_DATE)) AS first_activity_date` is a correct usage. 
sqlglot.transpile with read="snowflake" makes it incorrect and the modified script gives a syntax error. 
`SELECT
    USER_ID,
    MIN(TO_TIMESTAMP(EVENT_DATE, 'yyyy-mm-DD hh24:mi:ss')) AS first_activity_date`

**Comment by tobymao** [comment]
you need to set the write dialect, the default is sqlglot dialect

**Comment by GeorgeSittas** [comment]
> @GeorgeSittas In the same script, I see sqlglot.transpile is changing the argument inside TO_TIMESTAMP function to an incorrect form. This looks like a bug to me.
> 
> Snowflake function TO_TIMESTAMP only takes 1 argument. `SELECT USER_ID, MIN(TO_TIMESTAMP(EVENT_DATE)) AS first_activity_date` is a correct usage. sqlglot.transpile with read="snowflake" makes it incorrect and the modified script gives a syntax error. `SELECT USER_ID, MIN(TO_TIMESTAMP(EVENT_DATE, 'yyyy-mm-DD hh24:mi:ss')) AS first_activity_date`

Snowflake's docs specify that `TO_TIMESTAMP` can accept a `format` argument as well, for example the following executes just fine:

```sql
WITH foo(USER_ID, EVENT_DATE) AS (
  SELECT 1, '2020-01-01 00:00:00'
)
SELECT
  USER_ID,
  MIN(TO_TIMESTAMP(EVENT_DATE, 'yyyy-mm-DD hh24:mi:ss')) AS first_activity_date
FROM foo
GROUP BY USER_ID
```

See: https://docs.snowflake.com/en/sql-reference/functions/to_timestamp#syntax

**Comment by vishaldas-datafacade** [comment]
@GeorgeSittas your code does execute fine. however in few of my tables, the TO_TIMESTAMP works without the second argument. Whereas I get an error when the second argument is given. 

`too many arguments for function [TO_TIMESTAMP(DIM_CUSTOMER_TABLE.EVENT_DATE, 'yyyy-mm-DD hh24:mi:ss')] expected 1, got 2`

is there a reason sqlglot.transpile makes this change and adds the second argument for the TO_TIMESTAMP function even when it is not present in the input script?

**Comment by GeorgeSittas** [comment]
Can you please provide a fully reproducible example that includes the following?

- The original SQL
- The SQLGlot calls (e.g. to `transpile`)
- The error you get back when you try to execute the resulting SQL in Snowflake

**Comment by vishaldas-datafacade** [comment]
@GeorgeSittas I found the difference. 

In your code EVENT_DATE is stored as a string. In this case TO_TIMESTAMP accepts the format. 
```
WITH foo(USER_ID, EVENT_DATE) AS (
  SELECT 1, '2020-01-01 00:00:00'
)
```

However, in my case, the column is already in Date type. In this case TO_TIMESTAMP does not accept two arguments.
How to handle this in sqlglot.transpile and make sure that the change does not happen depending on the data type. 
 
<img width="895" alt="image" src="https://github.com/tobymao/sqlglot/assets/122136856/cf4e8001-22ff-4624-a01d-bb11081334ae">

**Comment by GeorgeSittas** [comment]
I see, makes sense. I'll take a look and see if we can avoid this.

**Comment by GeorgeSittas** [comment]
@vishaldas-datafacade check out the linked PR, I think it should be good for your use case
