### ISSUE TITLE
[Question] About function matching

### ISSUE THREAD

**Issue by echo-hhj** [tobymao/sqlglot#2070]
I support exp.StandardHash in mysql: rename_func("MD5") and then test that oracle's STANDARD_HASH('hello') can be converted to mysql's MD5('hello'). However, I can't find a parse for STANDARD_HASH in oracle's parser section. I was very curious about how oracle STANDARD_HASH was mapped to exp.StandardHash, and I couldn't parse to MD5 if I left out the underline and used STANDARDHASH('hello') sql. thanks！

<img width="634" alt="image" src="https://github.com/tobymao/sqlglot/assets/50286010/b2b5422a-8f28-4424-92aa-e2c88f564fb4">
<img width="427" alt="image" src="https://github.com/tobymao/sqlglot/assets/50286010/f8eb260e-17b9-46a0-a104-9d581ab0559d">

**Comment by GeorgeSittas** [comment]
There are several layers of magic in SQLGlot, check out how `Func`s are handled in the parser.

Btw, I don't think that mapping `STANDARD_HASH('hello')` from Oracle to MySQL's `MD5('hello')` is accurate, based on their docs:

> The optional method argument lets you specify the name of the hash algorithm to be used. Valid algorithms are SHA1, SHA256, SHA384, SHA512, and MD5. If you omit this argument, then SHA1 is used (oracle).

- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/STANDARD_HASH.html#GUID-4A68DACE-CFCF-443B-8651-B6CEAA7C4FD7
- https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_md5

**Comment by echo-hhj** [comment]
Thank you for your answer. I know what my question is, but I still don't understand the "several layers of 'magic'" in your answer. Could you give me more details?

**Comment by GeorgeSittas** [comment]
> and I couldn't parse to MD5 if I left out the underline and used STANDARDHASH('hello') sql.

I'm not sure what you mean here, could you elaborate? Is there an issue with the `MD5` function?

**Comment by echo-hhj** [comment]
STANDARD_HASH matches up as StandardHash, is there something going on here, not a strict match or a fuzzy match? What is the special treatment of the matching mechanism here

**Comment by echo-hhj** [comment]
Oh okay, now I get it!Thank you very much.
