### ISSUE TITLE
Parser is failing due to UNIQUE keyword

### ISSUE THREAD

**Issue by sashindeitidata** [tobymao/sqlglot#2074]
when read='oracle' 

for table in parse_one("**SELECT UNIQUE col1, col2 FROM table**").find_all(exp.Table):
    print(table.name)

Parser is unable to understand the UNIQUE keyword. Without UNIQUE keywork parser works fine even for complex queries.

I'm trying to get all the table list from the above query, but parser fails when UNIQUE is avialable in the query, without UNIQUE, it returns correct table list.

**Comment by tobymao** [comment]
please create a more detailed pr in the future, what dialect is this and can you link the relevant documentation
