### ISSUE TITLE
DATE_ADD function's second argument becomes empty

### ISSUE THREAD

**Issue by aman-wisdom** [tobymao/sqlglot#2078]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
I'm on the latest version `17.14.2`
```
>>> x = """ SELECT x FROM y WHERE DATE( z) <= DATE_ADD('year', 1, DATE(w))"""
>>> parse_one(x).sql()
"SELECT x FROM y WHERE DATE(z) <= DATE_ADD('year', 1, '')"
```
**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
Please take the time to read the issue template, you even copied and pasted it! You're missing the read/dialect argument, you have your arguments mixed up for unit and column.

**Comment by aman-wisdom** [comment]
Hey, sorry for that. I somehow missed copying all that info. Here it is:
- My read dialect is 'postgres`.
- The issue still exists on the latest pip version of sqlglot (17.14.2)
- Here is the fully reproducible code:
```
Python 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlglot import parse_one
>>> sql_query = """ SELECT col_name FROM table_name WHERE DATE(creation_date) <= DATE_ADD('year', 1, DATE(proposal_date))"""
>>> parsed_query = parse_one(sql_query, read='postgres')
>>> parsed_query
(SELECT expressions:
  (COLUMN this:
    (IDENTIFIER this: col_name, quoted: False)), from:
  (FROM this:
    (TABLE this:
      (IDENTIFIER this: table_name, quoted: False))), where:
  (WHERE this:
    (LTE this:
      (DATE this:
        (COLUMN this:
          (IDENTIFIER this: creation_date, quoted: False))), expression:
      (DATEADD this:
        (LITERAL this: year, is_string: True), expression:
        (LITERAL this: 1, is_string: False), unit:
        (DATE this:
          (COLUMN this:
            (IDENTIFIER this: proposal_date, quoted: False)))))))
>>> parsed_query.sql()
"SELECT col_name FROM table_name WHERE DATE(creation_date) <= DATE_ADD('year', 1, '')"
```
Problem: The parsed query is correct but when it is converted to sql again, the second argument of DATE_ADD becomes empty. I was expecting "SELECT col_name FROM table_name WHERE DATE(creation_date) <= DATE_ADD('year', 1, proposal_date)".

I believe the above code is fully reproducible. I didn't find any official documentation mentioning this issue but maybe I am missing something.

I didn't get your comment "you have your arguments mixed up for unit and column." Sorry if it's something dumb, I'm a bit new to the library so would appreciate any help.

**Comment by aman-wisdom** [comment]
Adding this in a new issue.
