### ISSUE TITLE
Problem with DATE_ADD function

### ISSUE THREAD

**Issue by aman-wisdom** [tobymao/sqlglot#2079]
Hey, sorry for #2078 . I somehow missed copying all the info. Here it is:

- My read dialect is postgres.
- The issue still exists on the latest pip version of sqlglot (17.14.2)

Here is the fully reproducible code:
```
Python 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlglot import parse_one
>>> sql_query = """ SELECT col_name FROM table_name WHERE DATE(creation_date) <= DATE_ADD('year', 1, DATE(proposal_date))"""
>>> parsed_query = parse_one(sql_query, read='postgres')
>>> parsed_query
(SELECT expressions:
  (COLUMN this:
    (IDENTIFIER this: col_name, quoted: False)), from:
  (FROM this:
    (TABLE this:
      (IDENTIFIER this: table_name, quoted: False))), where:
  (WHERE this:
    (LTE this:
      (DATE this:
        (COLUMN this:
          (IDENTIFIER this: creation_date, quoted: False))), expression:
      (DATEADD this:
        (LITERAL this: year, is_string: True), expression:
        (LITERAL this: 1, is_string: False), unit:
        (DATE this:
          (COLUMN this:
            (IDENTIFIER this: proposal_date, quoted: False)))))))
>>> parsed_query.sql()
"SELECT col_name FROM table_name WHERE DATE(creation_date) <= DATE_ADD('year', 1, '')"
```
Problem: The parsed query is correct but when it is converted to sql again, the second argument of DATE_ADD becomes empty. I was expecting `SELECT col_name FROM table_name WHERE DATE(creation_date) <= DATE_ADD('year', 1, proposal_date)`.

I believe the above code is fully reproducible. I didn't find any official documentation mentioning this issue but maybe I am missing something.

I didn't get your comment "you have your arguments mixed up for unit and column." Sorry if it's something dumb, I'm a bit new to the library so would appreciate any help.

**Comment by tobymao** [comment]
postgres does not have date_add, so the date_add you're trying to use is sqlglot dialect which is of the form

date_add(column, num, unit)

try switching up the order and you'll see it work properly

```
python -m sqlglot "date_add(x, 1, 'year')" --read=postgres
"x" + INTERVAL '1 year'
```

additionally, don't forget to set the dialect when you call sql(dialect="postgres")

**Comment by aman-wisdom** [comment]
Thanks so mucu!
