### ISSUE TITLE
parsing `struct(number bigint)` as a DataType treats number as a data type

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2080]
**Fully reproducible code snippet**

```
In [11]: import sqlglot as sg

In [12]: sg.__version__
Out[12]: '17.12.0'

In [13]: sg.parse_one("struct(number bigint)", read="duckdb", into=sg.exp.DataType)
Out[13]:
(DATATYPE this: Type.STRUCT, expressions:
  (DATATYPE this: Type.DECIMAL, expressions:
    (DATATYPESIZE this:
      (LITERAL this: 18, is_string: False)),
    (DATATYPESIZE this:
      (LITERAL this: 3, is_string: False)), nested: False, prefix: False), nested: True, prefix: False)
```

This is part of the schema inferred from running DuckDB's `read_json_auto` on a response from the [GitHub issues REST API](https://docs.github.com/en/free-pro-team@latest/rest/issues/issues?apiVersion=2022-11-28) 

**Official Documentation**

N/A

**Comment by cpcloud** [comment]
It seems like at least for duckdb, struct field name parsing should always be attempted before attempting to parse a type.

**Comment by cpcloud** [comment]
I don't think there's any documentation for this syntax, but it's what comes back from a `DESCRIBE` query containing any struct columns.

**Comment by cpcloud** [comment]
Actually there's a small example here: https://duckdb.org/docs/sql/data_types/overview#nested--composite-types

**Comment by GeorgeSittas** [comment]
Gotcha, let me see..
