### ISSUE TITLE
Documentation/specification of possible expression argument types

### ISSUE THREAD

**Issue by kszucs** [tobymao/sqlglot#2088]
**Is your feature request related to a problem? Please describe.**

I convert ibis and sqlglot expressions back and forth. It is usually cumbersome to "infer" what kind of arguments an expression can have and/or actually has. I'm not sure how much a downstream library could/should depend on the expression API, but it would be great to either document or specify at the code level what are the possible argument types for an expression. 

Something like "a datetime64 type accepts a numeric and a string literal as arguments":      `DataType(this=DataType.Type.DATETIME64, expressions=[<numeric literal>, <string literal>])`

Most of the time I have an expectation upfront which is mostly totally wrong or incomplete, so I need to debug it. 

**Describe the solution you'd like**

Fully fledged documentation could be an overkill, so I'd rather think of additional methods where I can infer the argument types. e.g.:

```py
class DataType(...):
    @classmethod
    def build_datetime64(scale: int | None=None, timestamp: str | None=None):
       ...
    
    @classmethod
    def build_decimal(precision: int | None=None, scale: int | None=None):
        ...
```

This way I could expect that `DataType.build_decimal(5, 2)` would construct something like:

```py
DataType(this=DECIMAL, expressions=[Literal.number(5), Literal.number(2)]
```
    
Currently decimal parameters are encoded as `DataTypeSize` expressions, which is fine, but `DataTypeSize` is used for string parameters as well, see https://github.com/tobymao/sqlglot/issues/2087

**Comment by tobymao** [comment]
You don't really want to construction expressions with the initializer, instead you should use the built in methods like

DataType.build(...), in your case it's

exp.DataType.build("DateTime64(1, 'Europe/Berlin')", dialect="clickhouse")

that way you don't have to deal with the paramater names and underlying types. there are many helper functions like this such as exp.func as well as builder methods like __add__ etc.

happy to accept new builder methods, in this case, i think build for datatype is sufficient

**Comment by kszucs** [comment]
So the point of ibis' use case to defer the string parsing and generation to sqlglot. As an example we have an ibis datatype which we convert to a sqlglot expression using the type kind and the required parameters. 
In order to call DataType.build() we would need to convert the ibis datatype to a string first, but that is what we want to use sqlglot for.

**Comment by tobymao** [comment]
ah that makes sense, in that case what you're trying to do is a bit lower level than the intention of sqlglot, either you'll have to use the AST (which as you've pointed out is a big opaque and low level) or perhaps you could implement an api. it's not something that i'm particularly keen on, but i'm happy to chat about it. if we agree to a spec and you implement it, i'll accept it.
