### ISSUE TITLE
Support for mathematical functions (BigQuery)

### ISSUE THREAD

**Issue by bobvanratingen** [tobymao/sqlglot#209]
Would be nice when this is supported: https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#mathematical_functions

For example:

 SAFE_DIVIDE(SUM(field1), SUM(field2))

**Comment by tobymao** [comment]
what do you mean supported? this should parse? is there an exception?

**Comment by bobvanratingen** [comment]
Sorry this works!

**Comment by tobymao** [comment]
safe_divide has been added as a first class function
