### ISSUE TITLE
Unable to parse the oracle query when "#" is present in the column names

### ISSUE THREAD

**Issue by sashindeitidata** [tobymao/sqlglot#2090]
Hello,

Parser is throwing an error when there is "#" character is present in the column name.

**Code for your reference -**

```
import sqlglot.expressions as exp

query ="""
SELECT A.COL#, B.COL2 FROM SCHEMA1.TABLE1 A
"""

expressions = sqlglot.parse_one(query, read='oracle')
x = list(expressions.find_all(exp.Table))

for i in x:
  listTables = str(i).split(' ')[0]
  print(listTables)
```

Above code fails as it cannot process '#' and throws the error.
Request you to add support for '#' for query parsing.

**Comment by GeorgeSittas** [comment]
Please link any related documentation that shows this identifier syntax is valid in Oracle.

**Comment by sashindeitidata** [comment]
Hi @GeorgeSittas 

Many systems table will have columns with # and $ charactor.
like you can try below query in your database -
```
SELECT OWNER, TABLE_NAME, COLUMN_NAME FROM dba_tab_cols
where COLUMN_NAME like '%#%';
```
Thanks

**Comment by sashindeitidata** [comment]
Hi @GeorgeSittas 

The character '#' is not supported yet.
Could you please add support for this? Thanks!

**Comment by GeorgeSittas** [comment]
Can you show what you're trying to do? It should work for oracle, see the above commit.

**Comment by sashindeitidata** [comment]
I'm trying to parse a query where column name ends with #, as shown in the below query - 

```
import sqlglot.expressions as exp

query ="""
SELECT COL#, COL2 FROM SCHEMA.TABLE 
"""

expressions = sqlglot.parse_one(query, read='oracle')
x = list(expressions.find_all(exp.Table))

for i in x:
  listTables = str(i).split(' ')[0]
  print(listTables)
```

I upgraded the installation to 17.14.2 version.

**Comment by GeorgeSittas** [comment]
The fix hasn't been released yet, you can do a local `pip install -e .` to pick it up until we deploy it.
