### ISSUE TITLE
add support for table cast to parse the tables correctly.

### ISSUE THREAD

**Issue by sashindeitidata** [tobymao/sqlglot#2091]
Hello,

Parser is unable to parse the query when there is a table cast function used in the query.

**Code for your reference -**

```
import sqlglot.expressions as exp

query ="""
SELECT count(1)
INTO V_Temp
FROM TABLE(CAST(somelist as data_list))
WHERE col like '%contact'
"""

expressions = sqlglot.parse_one(query, read='oracle')
x = list(expressions.find_all(exp.Table))

for i in x:
listTables = str(i).split(' ')[0]
print(listTables)
```

Above code fails as it cannot process table casting and throws the error as 'Expected TYPE after CAST'
Request you to add support for table cast in query parsing.

**Comment by GeorgeSittas** [comment]
Hey, appreciate you taking the time to file these issues, but you also need to provide documentation if e.g. something missing is non-trivial. From the issue creation template:

> Official Documentation Please include links to official SQL documentation related to your issue.

**Comment by GeorgeSittas** [comment]
I'm not sure I follow; what are `data_list` and `ID_OBJ_TBL` in your examples? Are they supposed to be columns, types, or something else which is Oracle-specific?

The issue is that these names don't represent types in SQLGlot and so parsing the `CAST` fails.

**Comment by GeorgeSittas** [comment]
Ok I think I get it: after digging a bit I found that [you can create custom user types in Oracle SQL](https://docs.oracle.com/cd/B14117_01/server.101/b10759/functions015.htm), so I assume these names are user-constructed types?

**Comment by sashindeitidata** [comment]
Hello @GeorgeSittas 

We also have table function used on top of binds, like **'Table(:Varible)'**
Please add support to the Table function when used with bind alone. 

Thank you so much for your support!
