### ISSUE TITLE
Struct is not parsing correctly

### ISSUE THREAD

**Issue by bobvanratingen** [tobymao/sqlglot#210]
```
SELECT
  my_struct.field1.field2
FROM
  `table`
```

`my_struct` is parsed as a table.

```
(SELECT expressions: 
  (DOT this: 
    (COLUMN this: 
      (IDENTIFIER this: field1, quoted: False), table: 
      (IDENTIFIER this: my_struct, quoted: False)), expression: 
    (IDENTIFIER this: field2, quoted: False)), from: 
  (FROM expressions: 
    (TABLE this: 
      (IDENTIFIER this: table, quoted: True))))
```

**Comment by bobvanratingen** [comment]
Okay understand!

**Comment by bobvanratingen** [comment]
With calling struct explicitly it's still having my_struct as table. Do you have an example?

**Comment by tobymao** [comment]
STRUCT_EXTRACT

let's not close this yet, let me think about it for a day

**Comment by tobymao** [comment]
@bobvanratingen are you interested in chatting with me on slack or some other chat platform?

totally optional if you prefer to just chat via issues

https://join.slack.com/t/18xxgames/shared_invite/zt-1bvd256hi-fH6Cm~EEXMFqZ36_OudVbA

**Comment by tobymao** [comment]
this cannot be done at the parser stage because i have no context of what the fields are, this would have to be done in the sqlglot optimizer, closing for now
