### ISSUE TITLE
Unable to parse the oracle query when ":SCHEMA" bind is present

### ISSUE THREAD

**Issue by sashindeitidata** [tobymao/sqlglot#2100]
Hello,

Parser is throwing an error when there is ":SCHEMA" bind is present in the oracle query.

Code for your reference -

```
import sqlglot.expressions as exp

query ="""
SELECT A.COL1, B.COL2 FROM SCHEMA1.TABLE1 A, SCHEMA2.TABLE2 B WHERE A.COL1 = :SCHEMA AND B.COL2 = :SOMEVARIABLE 
"""

expressions = sqlglot.parse_one(query, read='oracle')
x = list(expressions.find_all(exp.Table))

for i in x:
  listTables = str(i).split(' ')[0]
  print(listTables)
```

Above code works fine if Bind name is different that SCHEMA. If ':SCHEMA' is present in the query, then it fails.

Request you to add support for ':SCHEMA' for query parsing.

**Comment by tobymao** [comment]
can't reproduce this, works fine for me on main
