### ISSUE TITLE
TSQL: computed column not parsed

### ISSUE THREAD

**Issue by dmoore247** [tobymao/sqlglot#2104]
TSQL computed column example:
```sql
CREATE TABLE [dbo].[mytable](
	[zip_cd] [varchar](5) NULL,
	[safe_harbor_zip_cd]  AS (case when left([zip_cd],(3))='893' 
                              then left([zip_cd],(3))+'XX' 
                              else [zip_cd] end) PERSISTED,
 )
```

doesn't parse
<img width="685" alt="image" src="https://github.com/tobymao/sqlglot/assets/1122251/ca8ed9f8-273e-4da5-9f0b-df941031ba7f">

**Fully reproducible code snippet**
```python
tsql = """CREATE TABLE [dbo].[mytable](
[zip_cd] [varchar](5) NULL,
[safe_harbor_zip_cd]  AS (case when left([zip_cd],(3))='893' 
                            then left([zip_cd],(3))+'XX' 
                            else [zip_cd] end) PERSISTED,
)
"""
sqlglot.parse(sql=tsql, read="tsql")
```

**Official Documentation**
TSQL[ computed_column_expression:](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16)
<img width="686" alt="image" src="https://github.com/tobymao/sqlglot/assets/1122251/cd430eb5-f3e3-4441-8a7e-66c8b8a1e0e5">

sqlfiddle:
<img width="610" alt="image" src="https://github.com/tobymao/sqlglot/assets/1122251/59a7fe78-12ac-44dd-8fa5-cf9ce3ea0478">

**Comment by dmoore247** [comment]
Thanks!

**Comment by eliotgerson** [comment]
@tobymao  did this break at some point / does the test still pass? using the example statement from the test, I do get an error (in a large tsql file that otherwise parses fine). 

<img width="1131" alt="image" src="https://github.com/tobymao/sqlglot/assets/14575730/86bea677-feae-473a-9652-b5293d4f86d4">

**Comment by eliotgerson** [comment]
@tobymao  Did this break at some point? The example from the test that was added in the fix fails with "Unsupported Column Type: None" in a large tsql file that otherwise parses fine.

**Comment by eliotgerson** [comment]
@tobymao  nvm, I was being silly. thanks for confirming!!
