### ISSUE TITLE
tsql: "IDENTITY(1,1) NOT FOR REPLICATION NOT NULL," parse issue on `FOR`

### ISSUE THREAD

**Issue by dmoore247** [tobymao/sqlglot#2107]
For tsql:
```sql
CREATE TABLE [dbo].[mytable](
	[id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[mycolumn] [varchar](500) NULL
 CONSTRAINT [PK__mytable_1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
       ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```
we receive parse error on the `FOR`
```
ParseError: Required keyword: 'kind' missing for . Line 3, Col: 33.
  
CREATE TABLE [dbo].[mytable](
	[id] [int] IDENTITY(1,1) NOT [4mFOR[0m REPLICATION NOT NULL,
	[mycolumn] [varchar](500) NULL
 CONSTRAINT [PK__mytable_1] PRIMARY KEY CLUST
```

**Fully reproducible code snippet**
```python
tsql6 = """
CREATE TABLE [dbo].[mytable](
	[id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[mycolumn] [varchar](500) NULL
 CONSTRAINT [PK__mytable_1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
"""
sqlglot.parse(sql=tsql6, read="tsql")
```

**Official Documentation**
<img width="730" alt="image" src="https://github.com/tobymao/sqlglot/assets/1122251/8ff59d76-ab36-4f89-97ae-3b84257951c0">

Please include links to official SQL documentation related to your issue.
I can't find the official MSFT documentation, but it is called out 100's of times in an exact search (`IDENTITY(1,1) NOT FOR REPLICATION NOT NULL`) and called out [in official blog:](https://devblogs.microsoft.com/premier-developer/dacpac-always-changes-previously-replicated-tables-on-the-target/)

**Comment by tobymao** [comment]
@dmoore247 now that you have a couple examples of these, please make PRs in the future
