### ISSUE TITLE
tsql: Parse Error on constraint, this time on partition column name

### ISSUE THREAD

**Issue by dmoore247** [tobymao/sqlglot#2115]
Seems like I found another variant on create table, this time the partition scheme has a partition column name that isn't parsing
<img width="686" alt="image" src="https://github.com/tobymao/sqlglot/assets/1122251/45d00059-366c-4e7a-87c3-733bf0d90908">

**Fully reproducible code snippet**
```python
tsql= """
CREATE TABLE [dbo].[mytable](
	[col1] [varchar](16) NOT NULL,
	[created] [date].    NOT NULL,
 CONSTRAINT [PK_mytable] PRIMARY KEY NONCLUSTERED 
(
	[request_id] ASC
)
) ON [ps_trr_yearmonth]([created])
"""
import sqlglot
sqlglot.parse(tsql, read="tsql")
```

generating error:
<img width="602" alt="image" src="https://github.com/tobymao/sqlglot/assets/1122251/c4e2ba10-9220-4e15-9a70-02f5b576806d">

**Official Documentation**
[Docs](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16)
```
<column_constraint> ::=
[ CONSTRAINT constraint_name ]
{
   { PRIMARY KEY | UNIQUE }
        [ CLUSTERED | NONCLUSTERED ]
        [ ( <column_name> [ ,... n ] ) ]
        [
            WITH FILLFACTOR = fillfactor
          | WITH ( <index_option> [ ,... n ] )
        ]
        [ ON { partition_scheme_name ( partition_column_name )
            | filegroup | "default" } ]
```

**Comment by tobymao** [comment]
@dmoore247 please make a prs in the future as i'll start closing these as unplanned when my bandwidth gets low
