### ISSUE TITLE
(hive) hive parsing error, date addition and subtraction are parsed into aliases

### ISSUE THREAD

**Issue by liujiwen-up** [tobymao/sqlglot#2123]
`sqlglot.parse_one("""cast('1998-01-06' as date) + 30 days""", "hive")
TRY_CAST('1998-01-06' AS DATE) + 30 AS days

The syntax tree is as follows:
Parse days into an alias

[(ALIAS this: 
  (ADD this: 
    (TRYCAST this: 
      (LITERAL this: 1998-01-06, is_string: True), to: 
      (DATATYPE this: Type.DATE, nested: False, prefix: False)), expression: 
    (LITERAL this: 30, is_string: False)), alias: 
  (IDENTIFIER this: days, quoted: False))]
`

**Comment by tobymao** [comment]
this is the correct behavior.

```
>>> spark.sql("select cast('1998-01-06' as date) + 30 year ").collect()
[Row(year=datetime.date(1998, 2, 5))]
```

in this case i change it to year and you can see spark returns the column name year as an alias

**Comment by liujiwen-up** [comment]
@tobymao In hive, this does not seem to be in the form of an alias, please see the figure
![img_v2_2d435aed-ad90-4307-8718-d9ae3e48e70g](https://github.com/tobymao/sqlglot/assets/61498169/1cc07b7c-bb11-4237-bc41-141e02f44ee4)

**Comment by liujiwen-up** [comment]
@GeorgeSittas Can you help me look into this issue again? Thank you very much.

**Comment by GeorgeSittas** [comment]
> @GeorgeSittas Can you help me look into this issue again? Thank you very much.

I'll take a look soon
