### ISSUE TITLE
Unable to parse the oracle query when JSON_OBJECT is present

### ISSUE THREAD

**Issue by sashindeitidata** [tobymao/sqlglot#2124]
Hello,

Parser is throwing an error when there is JSON_OBJECT is present in the query.

Code for your reference -

```
import sqlglot.expressions as exp

query ="""
with data as (select col1, col2, col3 from sampletable)

select col1,
_JSON_OBJECT(
KEY 'obj2' IS data.col2,
KEY 'obj3' IS data.col3
) "DATA_OBJECTS"_
from data
"""

expressions = sqlglot.parse_one(query, read='oracle')
x = list(expressions.find_all(exp.Table))

for i in x:
  listTables = str(i).split(' ')[0]
  print(listTables)

```

Above code fails as it cannot process JSON_OBJECT.
Request you to add support for JSON_OBJECT for query parsing. So that it won't fail.
Thanks ton in advance!

**Comment by tobymao** [comment]
no documentation linked also _json_object doesn't seem to be correct, closing as not planned

**Comment by sashindeitidata** [comment]
Hi @tobymao 

Please see the oracle documentation for json related objects - 
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/JSON_OBJECT.html#GUID-1EF347AE-7FDA-4B41-AFE0-DD5A49E8B370

Could you please add support for json_object?

Thanks in advance!

**Comment by GeorgeSittas** [comment]
@sashindeitidata your example references `_JSON_OBJECT` -- note the `_` prefix, which is probably a typo.

The `JSON_OBJECT` function is currently supported for the Oracle dialect:

```python
>>> import sqlglot
>>>
>>> sqlglot.transpile("""
... SELECT JSON_OBJECT(
...     'name': name,
...     'email': email,
...     'phone': phone_number,
...     'hire_date': hire_date
... )
... FROM tbl
... """, read="oracle")
["SELECT JSON_OBJECT('name': name, 'email': email, 'phone': phone_number, 'hire_date': hire_date) FROM tbl"]
```
