### ISSUE TITLE
Error Result Sql After Optimize

### ISSUE THREAD

**Issue by 245Bluesky** [tobymao/sqlglot#2131]
**Sql Fragment:**
((CAST(random_id AS BIGINT) % 20 = 0) = TRUE)

**Optimize with rules:** 
pushdown_predicates
simplify

**Result:**
CAST(random_id AS BIGINT) % 20 = 0 = TRUE

**ps: The Result Sql is a wrong sql.**

**A Test Example:**
sql = """
SELECT DATE_TRUNC('day', CAST("dt" AS TIMESTAMP)) AS "dt1",
       APPROX_DISTINCT(CASE
                           WHEN "event" = 'Start' THEN "distinct_id"
                       END, 0.0040625) + 6 AS "metric#q3ll_g"
FROM table_1
WHERE "dt" < '2023-08-30'
  AND "dt" >= '2023-08-29'
  AND ((CAST("random_id" AS BIGINT) % 20 = 0) = TRUE)
GROUP BY DATE_TRUNC('day', CAST("dt" AS TIMESTAMP))
ORDER BY "metric#q3ll_g" DESC
LIMIT 10
"""

**Comment by tobymao** [comment]
@245Bluesky can you be more specific and explain why it's not correct?

**Comment by 245Bluesky** [comment]
**After Run The Result Sql :**
`SELECT
  DATE_TRUNC('day', CAST("table_1"."dt" AS TIMESTAMP)) AS "dt1",
  APPROX_DISTINCT(
    CASE WHEN "table_1"."event" = '$AppStart' THEN "table_1"."distinct_id" END,
    0.0040625
  ) + 6 AS "metric#q3ll_g"
FROM "table_1" AS "table_1"
WHERE
  "table_1"."dt" < '2023-08-30'
  AND "table_1"."dt" >= '2023-08-29'
  AND CAST("table_1"."random_id" AS BIGINT) % 20 = 0 = TRUE
AND "table_1"."event" = '$AppStart'
GROUP BY
  DATE_TRUNC('day', CAST("table_1"."dt" AS TIMESTAMP))
ORDER BY
  "metric#q3ll_g" DESC
LIMIT 10`

**With Trino**
trino error: line 3:61: mismatched input '='. Expecting: '%', '*', '+', ',', '-', '.', '/', 'AND', 'AS', 'AT', 'EXCEPT', 'FETCH', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'OR', 'ORDER', 'UNION', 'WHERE', 'WINDOW', '[', '||', <EOF>, <identifier>

**With Awsathena:**
awsathena error: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 3:61: mismatched input '='. Expecting: '%', '*', '+', ',', '-', '.', '/', 'AND', 'AS', 'AT', 'EXCEPT', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'OR', 'ORDER', 'UNION', 'WHERE', '[', '||', <EOF>, <identifier>

**Comment by tobymao** [comment]
Thanks, please add this additional detail next time.

**Comment by 245Bluesky** [comment]
👍 ok, thanks.  Solved so quickly！

**Comment by 245Bluesky** [comment]
Hi, tobymao, May I ask a question?

How to judge a expression in Select with ‘CASE WHEN’  is Nested or Parallel  by using sqlglot?

for example：
**1、Nested**
CASE
    WHEN condition_1 THEN
      CASE
        WHEN nested_condition_1 THEN result_1
        WHEN nested_condition_2 THEN result_2
        ELSE nested_result
      END
    WHEN condition_2 THEN result_3
    ELSE result_4
  END AS nested_case,

**2、Parallel**
CASE
    WHEN condition_5 THEN result_5
    WHEN condition_6 THEN result_6
    ELSE result_7
  END AS standalone_case

**my code like:**
for index, expression in enumerate(self.sql_ast.expressions):
    sub_expression = self.sql_ast.args['expressions'][index]
    for case in sub_expression.find_all(exp.Case):
        **how to judge?**
