### ISSUE TITLE
(oracle)minus keyword parsing error

### ISSUE THREAD

**Issue by liujiwen-up** [tobymao/sqlglot#2132]
`SELECT
  *
FROM (
  SELECT
    *
  FROM a AS a
) AS _q_0
minus
(
  SELECT
    *
  FROM b AS b
)
`
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 8, Col: 5

**Comment by tobymao** [comment]
please follow the instructions of the bug report, you need to specify the read dialect

1. you didn't read the instructions so you filed a bad bug report
2. you didn't provide fully reproducible code, which would have showed that you didn't provide the dialect
