### ISSUE TITLE
Optimize Error When Field Is AwsAthena Struct Type

### ISSUE THREAD

**Issue by 245Bluesky** [tobymao/sqlglot#2133]
**My SQL:**
SELECT dt AS dt,
       ipregion AS ipregion,
       sum(user_cnt) AS user_cnt,
       sum(req) AS req,
       sum(fill) AS fill,
       sum(imp) AS imp,
       sum(click) AS click,
       sum(click)*1.0/sum(imp) AS "ctr%",
       sum(fill)*1.0/sum(req) AS "fill%",
       sum(active)*1.0/sum(click) AS "cvr%",
       sum(imp)*1.0/sum(fill) AS "imp%"
FROM
  (with dau as
     (select *
      from
        (select dt,
                network_country_iso as ipregion,
                count(DISTINCT device_id) as user_cnt
         from table_1
         where dt>= CAST(CURRENT_DATE + interval '-30' day AS VARCHAR)
           and event='$AppStart'
         group by 1,
                  2)),
        fill as
     (SELECT dt,
             context.ipregion as ipregion,
             count(*) as request,
             sum(case
                     when is_filled='FILLED' then 1
                     else 0
                 end) as fill
      from table_2
      where dt >= CAST(CURRENT_DATE + interval '-30' day AS VARCHAR)
        and context.packagename='aaa'
        and context.placement = 'interstitial_launch7_dt'
        and context.ipregion = 'MX'
      group by 1,
               2),
        imp as
     (SELECT dt,
             fill.context.ipregion as ipregion,
             count(*) as impression
      from table_3
      where dt >= CAST(CURRENT_DATE + interval '-30' day AS VARCHAR)
        and fill.context.packagename='aaa'
        and fill is not null
        and placement = 'interstitial_launch7_dt'
        and ipregion = 'MX'
      group by 1,
               2),
        click as
     (SELECT dt,
             fill.context.ipregion as ipregion,
             count(*) as click
      from table_4
      where dt >= CAST(CURRENT_DATE + interval '-30' day AS VARCHAR)
        and fill.context.packagename='aaa'
        and fill is not null
        and placement = 'interstitial_launch7_dt'
        and ipregion = 'MX'
      group by 1,
               2),
        active as
     (SELECT dt,
             fill.context.ipregion as ipregion,
             sum(case
                     when fill.winnerinfo.rankitem.pricetype='CPI' then fill.winnerinfo.rankitem.price
                     else 0
                 end) as CPI_revenue,
             count(*) as active
      from table_5
      where dt >= CAST(CURRENT_DATE + interval '-30' day AS VARCHAR)
         and fill is not null
        and fill.context.placement = 'interstitial_launch7_dt'
        and fill.context.ipregion = 'MX'
      group by 1,
               2) select *
   from
     (SELECT x.dt,
             x.ipregion,
             sum(user_cnt) as user_cnt,
             sum(request) as req,
             sum(fill) as fill,
             sum(impression) as imp,
             sum(click) as click,
             sum(active) as active,
             sum(CPI_revenue) as CPI_revenue
      from fill x
      left join imp a on x.dt=a.dt
      and x.ipregion=a.ipregion
      left JOIN click b on x.dt=b.dt
      and x.ipregion=b.ipregion
      left JOIN active c on x.dt=c.dt
      and x.ipregion=c.ipregion
      left join dau d on x.dt=d.dt
      and x.ipregion=d.ipregion
      group by 1,
               2)) AS virtual_table
WHERE ipregion IN ('MX')
GROUP BY dt,
         ipregion
ORDER BY user_cnt DESC
LIMIT 50

**type of fill:**
`fill` struct<globalid:string,context:struct<udid:string,placement:string,ip:string,ipRegion:string,region:string,packageName:string,gaid:string,version:int,strategyId:int,coldBoot:boolean,learningPeriod:boolean,abTestIds:array<bigint>,cookies:array<struct<key:string,value:string>>,boosters:array<string>,ranker:string,randomId:int,ipState:string,androidId:string,debug:boolean,lang:string,strategyTags:array<string>,requestId:string,waterFall:struct<clientRequestTime:bigint,adSubProvider:string,requestType:string,waterfallConfigId:string,serverWaterfallConfig:string,adTypeExpDirectTimes:int,adRequestDirectTimes:int,layerIndex:int,adPosRequestDirectTimes:int,adTypeRequestDirectTimes:int,adExpDirectTimes:int,adPosExpDirectTimes:int,isFirstDay:boolean,isConfigPreRequest:boolean>,layer:string,wfConfigId:string,model:string,adapter:string,adPos:string,isUnionVersion:boolean,adPosParent:string,osVersion:int,brand:string,requirePackageName:string,nativeAbTestIds:array<bigint>>,rankitems:array<struct<projectId:bigint,campaignId:bigint,groupId:bigint,creativeId:bigint,materialId:bigint,materialType:int,packageName:string,smartBid:float,pCTR:double,pCVR:double,score:double,coldBootPercentage:double,coldBootState:string,priceType:string,price:double,redirectType:bigint,downloadMethod:bigint,source:string,learningPeriodState:string,payoutModel:string,impCvr:double,priority:int,groupViewCtn:int,typeTags:array<string>,smartBidThreshold:double,dynamicSmartBidPrediction:double,dynamicSmartBidFinal:double,offerId:bigint,orderId:bigint,eCPM:double,eEVR:double,payoutEventProb:double,ctrModelType:string,calibratePctvr:double,hourlyCalibrationRate:float>>,winnerfeature:string,winnerinfo:struct<rankItem:struct<projectId:bigint,campaignId:bigint,groupId:bigint,creativeId:bigint,materialId:bigint,materialType:int,packageName:string,smartBid:float,pCTR:double,pCVR:double,score:double,coldBootPercentage:double,coldBootState:string,priceType:string,price:double,redirectType:bigint,downloadMethod:bigint,source:string,learningPeriodState:string,payoutModel:string,impCvr:double,priority:int,groupViewCtn:int,typeTags:array<string>,smartBidThreshold:double,dynamicSmartBidPrediction:double,dynamicSmartBidFinal:double,offerId:bigint,orderId:bigint,eCPM:double,eEVR:double,payoutEventProb:double,ctrModelType:string,calibratePctvr:double,hourlyCalibrationRate:float>>,timestamp:bigint,tracker:struct<beforeQueryUserProfileTs:bigint,afterQueryUserProfileTs:bigint,beforeRecallTs:bigint,afterRecallTs:bigint,beforeBuildCandidateTs:bigint,afterBuildCandidateTs:bigint,beforeCTRPredictTs:bigint,afterCTRPredictTs:bigint,beforeCVRPredictTs:bigint,afterCVRPredictTs:bigint>,deploymentversion:string,extend1:string,extend2:string,source:string,bidders:array<struct<name:string,floorPrice:double,bidPrice:double,isBidding:boolean,isWinner:boolean>>,bidderContext:struct<bidders:array<string>,winner:string,adx:struct<bidFloor:double,isBid:boolean,bidPrice:double,extend1:string,extend2:string>,dt:struct<ecpm:double,bidPrice:double,extend1:string,extend2:string>,taboola:struct<bidPrice:double,extend1:string,extend2:string>,extend1:string,extend2:string>> COMMENT '',

**My Code:**
optimize(sql, dnf=True, dialect=self.dialect, rules=RULES).sql(dialect=self.dialect, pretty=True)

**Returns Error:**
optimizer/qualify_columns.py", line 73, in validate_qualify_columns
    raise OptimizeError(
sqlglot.errors.OptimizeError: Column 'fill.context' could not be resolved for table: 'fill'

**Comment by GeorgeSittas** [comment]
Hey, I can't figure out what the issue is; you should provide a schema to the `optimize` function, otherwise it might not be possible to optimize your query due to ambiguous columns, etc.

On another note, please take the time to create higher quality issues in the future, e.g. by formatting the code / summary of the issue and also constructing a minimal query that demonstrates the problem at hand. This report is unreadable.
