### ISSUE TITLE
Add Alias to Column Name

### ISSUE THREAD

**Issue by jimmyruann** [tobymao/sqlglot#2155]
Hi team, is it possible to add and modify column alias after parsing raw SQL?

```
from sqlglot import parse_one

sql = "SELECT a.apple, b.banana FROM shop"
sql_object = parse_one(sql)

# some how to add or modify alias of column
...

sql_object.sql()
# SELECT a.apple AS ap, b.banana AS ba FROM shop


```

Thank you for the help.

**Comment by GeorgeSittas** [comment]
Hey 👋

Yeah, you can do something like:

```python
from sqlglot import exp, parse_one

sql = "SELECT a.apple, b.banana FROM shop"
sql_object = parse_one(sql)

for select in sql_object.selects:
    if not select.alias:
        select.replace(exp.alias_(select, <your_alias>))
```

Gonna close this issue, but happy to continue chatting if this doesn't solve your problem. In the future you can also post similar questions in our [slack](https://tobikodata.com/slack).

**Comment by ewhitley** [comment]
@georgesittas - TY for the replace example. Incredibly helpful.
