### ISSUE TITLE
Teradata to Databricks transpilation of "Sample" keyword

### ISSUE THREAD

**Issue by Ashay4u** [tobymao/sqlglot#2161]
When working on Teradata to Databricks conversion I ran into another issue where "Sample" clause in Teradata is not getting transpiled correctly. Details below

**Sample code**

```
sql="""
	SELECT * FROM 
	Employee 
	Sample 0.33, .25, .1;
"""


try:
    new_query = sqlglot.transpile(sql, read='teradata', write='databricks', pretty=True)[0]
    print(new_query)
except sqlglot.errors.ParseError as error:
    print(traceback.format_exc())
    print(error.errors)
```

**Expected output:**

```
SELECT * FROM
Employee
TABLESAMPLE (33 PERCENT)
  ;
```

**Current SqlGlot Output**

```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 4, Col: 12.

        SELECT * FROM
        Employee
        Sample 0.33, .25, .1;


[{'description': 'Invalid expression / Unexpected token', 'line': 4, 'col': 12, 'start_context': '\n\tSELECT * FROM \n\tEmployee \n\tSample ', 'highlight': '0.33', 'end_context': ', .25, .1;\n', 'into_expression': None}]
```

**Official Documentation**
Source: https://www.teradatapoint.com/teradata/teradata-sample-function.htm
Target: https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-sampling.html

**Comment by GeorgeSittas** [comment]
Transpiling `SAMPLE ...` is currently out of scope because it's not trivial, but I created a PR that at least adds support for the Teradata form.
