### ISSUE TITLE
Support for REGEXP_EXTRACT

### ISSUE THREAD

**Issue by bobvanratingen** [tobymao/sqlglot#218]
Example whats's using REGEXP_EXTRACT:

```
    SELECT
      TRIM(REGEXP_EXTRACT(query, r'/\*.*\*/'), '*/') AS query_comment,
    FROM
      `table`
```

**Comment by tobymao** [comment]
is this legal sql? https://support.google.com/datastudio/answer/7064476?hl=en&ref_topic=7041728

r'' is python syntax isn't it?

**Comment by bobvanratingen** [comment]
https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_extract

_BigQuery provides regular expression support using the [re2](https://github.com/google/re2/wiki/Syntax) library; see that documentation for its regular expression syntax._
