### ISSUE TITLE
Generate from the syntax tree (string)

### ISSUE THREAD

**Issue by GearLeeess-JOE** [tobymao/sqlglot#2181]
Hi team, thanks for your efforts! 

I'm wondering if it's possible to generate from a syntax tree (it's a string rather than an Expression class). 

Here's my story: I saved the hive syntax trees in a JSON file, by using these codes:
```
repr(expression)
  for expression in sqlglot.parse(
      sql,
      read="hive",
      error_level=error_level,
  )
```
Later on, I want to generate them into spark. Is there any way to achieve this?

Thank you for the help.

**Comment by GeorgeSittas** [comment]
Hey, have you checked the `dump` and `load` methods of the `Expression` class? They might be helpful for your use case.

**Comment by GeorgeSittas** [comment]
Gonna close this issue for now; take a look at the above methods and if they don't help feel free to reach out in [slack](https://tobikodata.com/slack) where people might be able to provide more help / context on this problem.

**Comment by GearLeeess-JOE** [comment]
> Hey, have you checked the `dump` and `load` methods of the `Expression` class? They might be helpful for your use case.

Thanks for your reply! Really helpful!
