### ISSUE TITLE
Unable to parse when DISTINCT is followed by /*HINT*/

### ISSUE THREAD

**Issue by sashindeitidata** [tobymao/sqlglot#2188]
Hello Toby & Team,
Warm greetings!

**Thank you for fixing all the issues we reported in the past. We really appreciate your efforts!
We have been using your parser for our work and it has been a great help!**

Could you please help us by providing support following case? - 

**Parser failed to parse the query when there a DISTINCT keyword followed by a Hint.**

**Documentation -** 
https://docs.oracle.com/cd/B13789_01/server.101/b10752/hintsref.htm

**Code for your reference -**

```
import sqlglot.expressions as exp

query1 ="""
SELECT DISTINCT /*+ LEADING(e2 e1) USE_NL(e1) INDEX(e1 emp_emp_id_pk) 
    USE_MERGE(j) FULL(j) */
    e1.first_name, e1.last_name, j.job_id, sum(e2.salary) total_sal
FROM employees e1, employees e2, job_history j
WHERE e1.employee_id = e2.manager_id
    AND e1.employee_id = j.employee_id
    AND e1.hire_date = j.start_date
GROUP BY e1.first_name, e1.last_name, j.job_id 
ORDER BY total_sal
"""

query2 ="""
SELECT DISTINCT e1.id, /*+ LEADING(e2 e1) USE_NL(e1) INDEX(e1 emp_emp_id_pk) 
    USE_MERGE(j) FULL(j) */
    e1.first_name, e1.last_name, j.job_id, sum(e2.salary) total_sal
FROM employees e1, employees e2, job_history j
WHERE e1.employee_id = e2.manager_id
    AND e1.employee_id = j.employee_id
    AND e1.hire_date = j.start_date
GROUP BY e1.first_name, e1.last_name, j.job_id 
ORDER BY total_sal
"""

expressions = sqlglot.parse_one(query1, read='oracle')
x = list(expressions.find_all(exp.Table))

for i in x:
  listTables = str(i).split(' ')[0]
  print(listTables)
```

Request you to add support for this scenario as well.
Thanks ton in advance!

Thanks,
Sachin

**Comment by GeorgeSittas** [comment]
Hey, thanks for the kind words.

Are you sure this syntax is valid Oracle? The link you provided doesn't document the syntax itself, and after some searching I couldn't find an example with the `SELECT DISTINCT <hint> ....` syntax. For example, check this SO thread: https://stackoverflow.com/questions/936328/faster-select-distinct-thing-id-thing-name-from-table1-in-oracle

**Comment by GeorgeSittas** [comment]
I'll go ahead and close this issue, as Oracle's [docs](https://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_10002.htm#SQLRF01702) show that the official syntax is:

```sql
SELECT [<hint>] [{DISTINCT | UNIQUE} | ALL] <select_list>
```

**Comment by sashindeitidata** [comment]
Hi @GeorgeSittas 

Thanks for looking into this.
Yes, Syntax is valid and following basic query runs fine in oracle -

```
SELECT DISTINCT /*+ dynamic_sampling ag(4) */ 1,2 from DUAL;
SELECT DISTINCT 1, /*+ dynamic_sampling ag(4) */ 2 from DUAL;
```

Hint can be given before DISTINCT or after Column name as well.
This is supported by oracle and it's a valid syntax. 

Can you please fix this so that parsing works fine? Thanks a ton, in advance!

Thank, Sachin

**Comment by tobymao** [comment]
not planned, feel free to make a PR for this yourself
