### ISSUE TITLE
Unable to parse the oracle query when query has 'sample block(n1, n2)'

### ISSUE THREAD

**Issue by sashindeitidata** [tobymao/sqlglot#2206]
Hello Team,
Warm greetings!

Parser is throwing an error when there is sample block with 2 parameters.

Following query works fine in oracle-
select count(*)*2, count(distinct substr(rowid,1,15)) from foo sample block (50,1)

**Oracle Documentation -**
https://blogs.oracle.com/machinelearning/post/to-sample-or-not-to-sample-part-2
https://dba.stackexchange.com/questions/166495/why-does-sample-block-often-return-zero

**Code for your reference -**

```
import sqlglot.expressions as exp

# works fine
query1 ="""
select count(*)*2, count(distinct substr(rowid,1,15)) from foo sample block (50)
"""
# Doesn't work
query2 ="""
select count(*)*2, count(distinct substr(rowid,1,15)) from foo sample block (50,1)
"""

expressions = sqlglot.parse_one(query1, read='oracle')
x = list(expressions.find_all(exp.Table))

for i in x:
  listTables = str(i).split(' ')[0]
  print(listTables)
```

Note that above queries are valid oracle queries.

query2 fails as it cannot process sample block function with two parameters.
Request you to add support for the same.

Thanks ton in advance!

Thanks,
Sachin

**Comment by GeorgeSittas** [comment]
This doesn't look it matches Oracle's syntax spec:

<img width="656" alt="Screenshot 2023-09-13 at 3 20 53 PM" src="https://github.com/tobymao/sqlglot/assets/46752250/27dbe3a1-e985-461f-b3f5-abaf702bdacf">

**Comment by GeorgeSittas** [comment]
@sashindeitidata if I understand correctly, some of the queries in the issues you raised use undocumented Oracle SQL syntax. If that's indeed the case, we're not inclined to support that syntax - you can instead convert these queries to use the more standard syntax, which should generally already be supported by SQLGlot.

I'll close this issue as not planned. Feel free to join our [slack](https://tobikodata.com/slack) if you want guidance on making PRs for future issues you encounter.

**Comment by sashindeitidata** [comment]
Hi @GeorgeSittas 

Can you at least provide support for following - 

`select count(*)*2, count(distinct substr(rowid,1,15)) from foo sample (  .25)`

Above query is working fine in oracle. Percentage can be .25 or .21153 or 0.15 kind of value.
Request you to add the support where percentage can start with decimal point (eg '.50')

Thanks in advance!

Thanks, Sachin

**Comment by GeorgeSittas** [comment]
Fixed in https://github.com/tobymao/sqlglot/commit/46342204037afb91f3c865b367d70fe4f8116584

**Comment by sashindeitidata** [comment]
Thanks a ton! SQLGLOT is helping us a lot, great parser!

**Comment by GeorgeSittas** [comment]
Cool - please consider creating PRs yourself for future issues now that you have several examples, as our bandwidth is relatively limited and Oracle isn't a high priority at the moment. And, again, if you need help you can reach out in Slack.

**Comment by sashindeitidata** [comment]
Sure, noted. Thanks for the help!!
Thanks to you, most of our issues are resolved, if we observe any more issues with SQLGLOT, will let you know and create PRs if possible.
Thank you so much!
