### ISSUE TITLE
Datatype in DECLARE statement not translated (`v18.5.0` , `bigquery → mysql`)

### ISSUE THREAD

**Issue by rafaelzig** [tobymao/sqlglot#2213]
## Input
```python
sqlglot.transpile('DECLARE x AS INT64', read='bigquery', write='mysql')[0]
```

## Expected output
```sql
'DECLARE x AS BIGINT'
```

## Actual output
```sql
'DECLARE x AS INT64'
```

## Official Documentation

* [MySQL 8.0 Reference Manual  /  Data Types  /  Numeric Data Types  /  Integer Types (Exact Value) - INTEGER, INT, SMALLINT, TINYINT, MEDIUMINT, BIGINT](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html)
* [MySQL 8.0 Reference Manual  /  SQL Statements  /  Compound Statement Syntax  /  Variables in Stored Programs  /  Local Variable DECLARE Statement](https://dev.mysql.com/doc/refman/8.0/en/declare-local-variable.html)
* [bigquery/docs/reference/standard-sql/data-types/numeric-types](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric_types)

**Comment by tobymao** [comment]
not planned, declare is parsed as a command, happy to accept a pr adding this functionality
