### ISSUE TITLE
bigquery whitespace characters need to be escaped in string and bytes literals

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2225]
Looks like newlines are handled but the remaining characters are not escaped correctly.

**Fully reproducible code snippet**

```
In [22]: import sqlglot as sg

In [23]: sg.__version__
Out[23]: '18.0.0'

In [24]: sql = sg.parse_one("SELECT '\a\b\f\n\r\t\v'", read="bigquery").sql("bigquery")

In [25]: !bq shell <<< "$sql"
Welcome to BigQuery! (Type help for more information.)
ibis-gbq> Error in query string: Error processing job 'ibis-gbq:bqjob_r1fef3289cccddd3_0000018a987c16e2_1': Syntax error: Unclosed string literal at [1:8]
ibis-gbq> Goodbye.
```

**Official Documentation**

https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#escape_sequences

**Comment by GeorgeSittas** [comment]
Hey @cpcloud, I tried to reproduce this but the string I get back from the SQL generator seems valid in BQ (screenshot attached):

```python
>>> import sqlglot as sg
>>>
>>> sg.__version__
'18.5.1.dev10'
>>>
>>> sql = sg.parse_one("SELECT '\a\b\f\n\r\t\v'", read="bigquery").sql("bigquery")
>>> print(sql)
SELECT '
       \n
        '
>>> sql
"SELECT '\x07\x08\x0c\\n\r\t\x0b'"
```

Am I missing something here?

<img width="1151" alt="Screenshot 2023-09-15 at 2 13 12 PM" src="https://github.com/tobymao/sqlglot/assets/46752250/05ef679e-6b69-408f-834a-ca57995f7cae">

**Comment by cpcloud** [comment]
```
>>> sql
```

shows the result `__repr__`

while `print` shows the result of `__str__` which is what is going to be passed to Python APIs as well as command line tools:

```
>>> class Demo:
...     def __str__(self):
...         print("__str__ called")
...         return "Demo"
...     def __repr__(self):
...         print("__repr__ called")
...         return "Demo"
...
>>> d = Demo()
>>> d
__repr__ called
Demo
>>> print(d)
__str__ called
Demo
```

You have to test with the result of `__str__`

**Comment by GeorgeSittas** [comment]
Ah right, makes sense. I will have a look :)
