### ISSUE TITLE
duckdb unnest to snowflake generates incorrect code

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2228]
**Fully reproducible code snippet**

```
In [7]: import sqlglot as sg

In [8]: sg.__version__
Out[8]: '18.0.0'

In [9]: sg.parse_one("select unnest([1, 2, 3])", read="duckdb").sql(dialect="snowflake")
Out[9]: 'SELECT EXPLODE([1, 2, 3])'
```

As far as I can tell, `EXPLODE` is not a function that exists in Snowflake.

Array flattening operations are done with their `FLATTEN` function

**Official Documentation**

https://docs.snowflake.com/en/sql-reference/functions/flatten

**Comment by GeorgeSittas** [comment]
It seems like `select unnest([1, 2, 3])` is equivalent to `select value from table(flatten(input => [1, 2, 3]))`, so perhaps this needs a two-step process to fix:

- Use something like the unnest-to-cross-join transformation (i.e. this might require #2227 to be solved first)
- Convert `unnest(x)` to `table(flatten(input => x))` @ generation time
