### ISSUE TITLE
duckdb struct to trino row syntax is incorrect

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2229]
**Fully reproducible code snippet**

```
In [12]: sg.parse_one("select {'a': 1}", read="duckdb").sql(dialect="trino")
Out[12]: "SELECT ROW('a' : 1)"
```

The generated code is a syntax error in trino:

```
❯ trino --catalog hive --schema default --execute "SELECT ROW('a' : 1)"
Query 20230915_181601_00052_vnzqz failed: line 1:16: mismatched input ':'. Expecting: '%', ')', '*', '+', ',', '-', '.', '/', 'AND', 'AT', 'OR', 'ORDER', '[', '||', <predicate>
SELECT ROW('a' : 1)
```

The code generated from `struct_pack` is syntactically valid but incorrect:

```
In [13]: sg.parse_one("select struct_pack(a := 1)", read="duckdb").sql(dialect="trino")
Out[13]: 'SELECT ROW(a = 1)'
```

**Official Documentation**

https://trino.io/docs/current/language/types.html#row

**Comment by GeorgeSittas** [comment]
Can take a look at these issues shortly - currently checking out the one with the escape sequences.

**Comment by cpcloud** [comment]
Don't mind me 😄  I was just poking around sqlglot to see just exactly how much code we can delete from ibis once we move our backends over to it for sql generation.

**Comment by GeorgeSittas** [comment]
I'm not 100% sure we can fully solve this problem, because Trino requires to do a `CAST` into a `ROW` that contains the necessary type information. Their example:

```sql
CAST(ROW(1, 2e0) AS ROW(x BIGINT, y DOUBLE))
```

**Comment by cpcloud** [comment]
IMO it would be acceptable to call `ROW(x)` on the result, which will preserve the structure sans struct field names:

Trino CLI:

```
trino:default> select row(x) from (values (1), (2), (3)) _ (x);
 _col0
-------
 {1}
 {2}
 {3}
(3 rows)
```

**Comment by GeorgeSittas** [comment]
@cpcloud won't accessing the struct fields end up being broken this way though? E.g. `{'a': 1}.a` wouldn't work I think?

**Comment by cpcloud** [comment]
That's correct, but that seems better than generating incorrect code.

Personally would also be fine with an error message indicating the transformation isn't possible.

**Comment by GeorgeSittas** [comment]
Gotcha, I think I'm going to display an error message for now; happy to accept a PR implementing a viable alternative.
