### ISSUE TITLE
Snowflake \\-escaped single quotes causes syntax error

### ISSUE THREAD

**Issue by maureen-daum** [tobymao/sqlglot#2234]
When parsing a Snowflake statement with a single quote in a string, sqlglot escapes it with a double backslash (https://github.com/tobymao/sqlglot/pull/879/files). However, this causes a syntax error when trying to run it in Snowflake.
Example query with the problem:
```
select * from tutorial.stackoverflow."Answers" where "Body" ILIKE '%Don\\'t%' limit 5;
```
Results:
```
Syntax error: unexpected 't'.
```

**Fully reproducible code snippet**
```
sql = "select * from foo where col like '%don''t%'"
valid_sql = {
    "select * from foo where col like '%don''t%'",
    "select * from foo where col like '%don\'t%'"
}
transpiled_sql = sqlglot.transpile(sql, read="snowflake")[0]
if transpiled_sql == "SELECT * FROM foo WHERE col LIKE '%don\\'t%'":
    print("BAD: snowflake doesn't like the double backslash escape")
if transpiled_sql in valid_sql:
    print("GOOD: valid snowflake sql")
```
Expected output: `GOOD: valid snowflake sql`
Actual output: `BAD: snowflake doesn't like the double backslash escape`

**Official Documentation**
The documentation says that single quotes should either be doubled up or be escaped with a single backslash (https://docs.snowflake.com/en/sql-reference/data-types-text#single-quoted-string-constants). Both of these variants correctly execute on Snowflake.

**Comment by tobymao** [comment]
you need to specify the write dialect

**Comment by tobymao** [comment]
```import sqlglot 
sql = "select * from foo where col like '%don''t%'"
print(sqlglot.transpile(sql, read="snowflake", write="snowflake")[0])```

**Comment by maureen-daum** [comment]
Oops, thanks for the pointer. Sorry for the noise!
