### ISSUE TITLE
xor codegen for a few dialects is incorrect

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2238]
**Fully reproducible code snippet**

```
In [30]: import sqlglot as sg

In [31]: sg.__version__
Out[31]: '18.5.1'

In [32]: sg.parse_one("a xor b", read="mysql").sql("duckdb")
Out[32]: 'a XOR b'
```

DuckDB doesn't have an `XOR` operator:

```
❯ duckdb <<< 'select true xor false'
Error: near line 1: Parser Error: syntax error at or near "false"
LINE 1: select true xor false
                        ^
```

This is also incorrect for other backends that don't have an xor operator:

- Postgres
- Trino
- Snowflake
- Clickhouse

and probably others.

**Official Documentation**

- https://duckdb.org/docs/archive/0.3.0/sql/expressions/logical_operators
- https://docs.snowflake.com/en/sql-reference/operators-logical

**Comment by tobymao** [comment]
@cpcloud it'd be appreciated if you made PR for these future minor transpilation issues. thanks
