### ISSUE TITLE
Support Sqlite datetime functions

### ISSUE THREAD

**Issue by mhamra** [tobymao/sqlglot#2252]
**Is your feature request related to a problem? Please describe.**
I've tried to run queries with SQLite dialect, and I found that the following datetime functions are not defined:
- date
- datetime
- julianday
- unixepoch
- timediff

In this link, you can see their definition [](https://www.sqlite.org/lang_datefunc.html)

**Describe the solution you'd like.**
I wanted these functions to be supported.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GeorgeSittas** [comment]
Please elaborate on what exactly is not working as expected.

**Comment by GeorgeSittas** [comment]
Hey Marcelo 👋

This is not really a high priority for us right now, so I'd say it's out of scope to add support for them, cc: @tobymao.
