### ISSUE TITLE
sort order is not rendered for duckdb

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2253]
**Fully reproducible code snippet**

DuckDB has a setting `default_order`, which can be set to `'DESC'`, and results in unspecified sort order in `ORDER BY` queries being ordered according to `default_order`.

sqlglot seems to assume (reasonably so, I think) that `ORDER BY x ASC` is equivalent to `ORDER BY x`, which is an invalid assumption for duckdb given the presence of `default_order`:

```
In [4]: import sqlglot as sg

In [5]: sg.__version__
Out[5]: '18.5.1'

In [6]: sg.parse_one("select i from range(5) _ (i) order by i asc", read="duckdb").sql("duckdb")
Out[6]: 'SELECT i FROM RANGE(5) AS _(i) ORDER BY i'

In [7]: !duckdb
D set default_order = 'DESC';
D select i from range(5) _ (i) order by i;
┌───────┐
│   i   │
│ int64 │
├───────┤
│     4 │
│     3 │
│     2 │
│     1 │
│     0 │
└───────┘
```

**Official Documentation**

- https://duckdb.org/docs/sql/query_syntax/orderby.html

**Comment by GeorgeSittas** [comment]
I see, it seems like we need to preserve the `ASC` / `DESC` information then, cc @tobymao. I'll start working towards a fix, thanks Phillip.

**Comment by cpcloud** [comment]
I wonder if there's value in always compiling in `ASC` and `DESC`, then whatever the user asked for isn't lost during the parse.

**Comment by cpcloud** [comment]
> In your example the ASC is dropped because that's the default behavior of DuckDB

That's the rub though, the default is configurable and sqlglot doesn't know about my configuration.

I can totally live with a `generator_flag` though if it's settled.
