### ISSUE TITLE
Failure on parsing queries containing reserved words as columns in SELECT projection

### ISSUE THREAD

**Issue by ShayYaari** [tobymao/sqlglot#2257]
Hi!

I encountered a valid query in Snowflake which queries a table with columns named "case" and "from".
Apparently these are valid queries in snowflake:

`
SELECT a, case, c FROM table
SELECT a, from, c FROM table
`

However I receive a ParseError exception when I try to parse them using the library.

`
sqlglot.errors.ParseError: Expected END after CASE. Line 2, Col: 14.
`

Do you have any suggestion?

**Comment by GeorgeSittas** [comment]
I don't think either of these queries is valid Snowflake, I just tested them:

<img width="908" alt="Screenshot 2023-09-19 at 5 32 32 PM" src="https://github.com/tobymao/sqlglot/assets/46752250/0e384937-ebcc-4c87-b0c7-6d134fa62dee">

<img width="772" alt="Screenshot 2023-09-19 at 5 32 49 PM" src="https://github.com/tobymao/sqlglot/assets/46752250/aa27cf2f-b86c-4cc0-a8d5-5615d8faeaba">
