### ISSUE TITLE
Convert to SQL from AST

### ISSUE THREAD

**Issue by dharmeshpkk** [tobymao/sqlglot#2264]
I have generated the `AST` and modified AST a little bit. How can `AST` be converted to perfect SQL. Following is the code:
import re
from sqlglot import parse_one
from sqlglot.optimizer import optimize

query = "select * from t where t.id = 1 and t.name = '123'"
str_ast_of_query = repr(parse_one(query, dialect="postgres"))
print(str_ast_of_query)

literal_values = re.findall(r'\(LITERAL this: ([^,]+),', str_ast_of_query)
.
str_ast_of_query = str_ast_of_query.replace("123", "abc")
for value in literal_values:
     str_ast_of_query = str_ast_of_query.replace("123", "abc")
Now how to get query as:
`select * from t where t.id = 1 and t.name = 'abc'`

**Comment by tobymao** [comment]
you can’t do that you need to modify the ast nodes direcfly
