### ISSUE TITLE
Snowflake `exclude` incorrect parsing

### ISSUE THREAD

**Issue by diogo-fernan** [tobymao/sqlglot#2265]
Hi! `sqlglot` seems to be incorrectly parsing `exclude` for single columns when no parenthesis are used. Having no parenthesis is [valid Snowflake syntax](https://docs.snowflake.com/en/sql-reference/sql/select).

Thoughts?

```python
import sqlglot

sql = """
select
    * exclude b  -- incorrectly parsed
    ,b
    ,c
from
    test
;
"""

print(sqlglot.parse_one(sql, read="snowflake"))

sql = """
select
    * exclude(b) -- correctly parsed
    ,b
    ,c
from
    test
;
"""

print(sqlglot.parse_one(sql, read="snowflake"))

# output:
# SELECT * EXCEPT (b /* incorrectly parsed */, b, c) FROM test
# SELECT * EXCEPT (b) /* correctly parsed */, b, c FROM test
```

**Comment by GeorgeSittas** [comment]
Thanks for the report @diogo-fernan, looks like this was an [oversight](https://github.com/tobymao/sqlglot/pull/1021) on our end.
