### ISSUE TITLE
BQ Navigation functions are considered as Anonymous

### ISSUE THREAD

**Issue by bgedik** [tobymao/sqlglot#2274]
**Is your feature request related to a problem? Please describe.**
Is it expected that BQ navigation functions are considered as Anonymous? 

**Describe the solution you'd like**
I would like to see them as non-Anonymous.

**Additional context**

```
"""
SELECT name,
   finish_time,
   division,
   LEAD(name)
     OVER (PARTITION BY division ORDER BY finish_time ASC) AS followed_by
 FROM finishers;
"""

next(sqlglot.parse_one(x, read="bigquery").find_all(expressions.Anonymous))
(ANONYMOUS this: LEAD, expressions:
  (COLUMN this:
    (IDENTIFIER this: name, quoted: False)))
```

**Comment by tobymao** [comment]
feel free to make a pr, all functions that aren’t implemented are considered anonymous
