### ISSUE TITLE
 Unable to parse the oracle query when query has MODEL, DIMENSION BY & MEASURES clauses

### ISSUE THREAD

**Issue by sashindeitidata** [tobymao/sqlglot#2276]
Hello Toby & Team,
Warm greetings!

Thank you for fixing all the issues we reported in the past. We really appreciate your efforts!
We have been using your parser for our work and it has been a great help!

Parser is throwing an error when there are following clauses- 
MODEL
DIMENSION BY 
MEASURES 

**Oracle Documentation -**
https://www.experts-exchange.com/articles/14879/The-Oracle-MODEL-clause-part-I.html
https://asktom.oracle.com/pls/apex/asktom.search?tag=sql-model-clause
https://docs.oracle.com/cd/E87221_07/otn/pdf/user/html_oplac/output/appendix_a.htm

**Code for your reference -**

```
import sqlglot.expressions as exp

query1 ="""
SELECT X1, X2, Y, Z FROM DUAL
MODEL
DIMENSION BY (1 X1, 1 X2)
MEASURES (1 Y, 1 Z)
RULES UPSERT
(
  Y[2, 1] = Y[1, 1]
)
"""

expressions = sqlglot.parse_one(query1, read='oracle')
x = list(expressions.find_all(exp.Table))

for i in x:
  listTables = str(i).split(' ')[0]
  print(listTables)

```
Above code fails as it cannot process above clauses.
Request you to add support for the same.

Thanks ton in advance!

Thanks,
Sachin

**Comment by GeorgeSittas** [comment]
We don't currently have the bandwidth for this; closing it as out-of-scope. It's more likely that we'll accept a high-quality PR if you want to contribute one yourself. Feel free to reach out in [slack](https://tobikodata.com/slack) if you wanna chat about it.
