### ISSUE TITLE
Support postgres Operator Classes and Operator Families

### ISSUE THREAD

**Issue by Nitrino** [tobymao/sqlglot#2278]
An index definition can specify an operator class for each column of an index. 
Right now, the library does not support such cases

**Fully reproducible code snippet**
```python
    sql = """
        CREATE INDEX index_routes_on_path_text_pattern_ops ON public.routes USING btree (path varchar_pattern_ops);
        CREATE INDEX index_ci_pipelines_on_project_idandrefandiddesc ON public.ci_pipelines USING btree (project_id, ref, id DESC);
        CREATE INDEX index_issues_on_title_trigram ON public.issues USING gin (title public.gin_trgm_ops);
    """
    parsed_sql_exprs = sqlglot.parse(sql, read="postgres")
```

**Official Documentation**
https://www.postgresql.org/docs/current/indexes-opclass.html

**Comment by GeorgeSittas** [comment]
@Nitrino the second `CREATE INDEX` statement looks legit, i.e. it matches what I see in Postgres' syntax spec. Can you point me to examples on the docs page for the other two? I don't see the `USING <method> (key value)` syntax like you showed in the first one:

```
CREATE [ UNIQUE ] INDEX [ CONCURRENTLY ] [ [ IF NOT EXISTS ] name ] ON [ ONLY ] table_name [ USING method ]
    ( { column_name | ( expression ) } [ COLLATE collation ] [ opclass [ ( opclass_parameter = value [, ... ] ) ] ] [ ASC | DESC ] [ NULLS { FIRST | LAST } ] [, ...] )
    [ INCLUDE ( column_name [, ...] ) ]
    [ NULLS [ NOT ] DISTINCT ]
    [ WITH ( storage_parameter [= value] [, ... ] ) ]
    [ TABLESPACE tablespace_name ]
    [ WHERE predicate ]
```

**Comment by Nitrino** [comment]
@GeorgeSittas I can't find a suitable example in the documentation, but my examples above are taken from a real Gitlab database schema from the Prisma test repository
https://github.com/prisma/database-schema-examples/blob/8cea37d834f3effd6aad53e98c5bc865b4d85335/postgres/gitlab/schema.sql#L10740

**Comment by GeorgeSittas** [comment]
What are the semantics of `USING btree (path varchar_pattern_ops)`? I can't understand based on the docs

**Comment by Nitrino** [comment]
@GeorgeSittas Hi, sorry for the long reply. 
I'm not sure I fully understood your question. 

The documentation on index creation does not describe the semantics of operator class in much detail:

```sql
CREATE [ UNIQUE ] INDEX ... [ opclass [ ( opclass_parameter = value [, ... ] ) ] ] ...
```

But there is a clarification in [Section 11.10](https://www.postgresql.org/docs/current/indexes-opclass.html).

> An index definition can specify an operator class for each column of an index.

```sql
CREATE INDEX name ON table (column opclass [ ( opclass_options ) ] [sort options] [, ...]);
```

>  The main reason for having operator classes is that for some data types, there could be more than one meaningful index behavior.

Thus an operator class can be specified for any index field. 
And these classes can be different for different types of indexes (e.g. `USING btree`)

**Comment by GeorgeSittas** [comment]
I see, I misread the doc page for opclasses I think, I'll try to completely fix this in a followup PR.

**Comment by GeorgeSittas** [comment]
@Nitrino PR's up
