### ISSUE TITLE
Incorrect precedence of AND, OR

### ISSUE THREAD

**Issue by kunal-wisdom** [tobymao/sqlglot#2286]
The abstract syntax tree seems to be incorrect for OR, AND combination in where clause.

```python
from sqlglot import parse_one

parsed = parse_one("SELECT * FROM table_name where col1 = 1 or col2 = 2 and col3 = 3", read="postgres")
```

The parsed tree is: 
```
'18.5.1'
(SELECT expressions: 
  (STAR ), from: 
  (FROM this: 
    (TABLE this: 
      (IDENTIFIER this: table_name, quoted: False))), where: 
  (WHERE this: 
    (AND this: 
      (OR this: 
        (EQ this: 
          (COLUMN this: 
            (IDENTIFIER this: col1, quoted: False)), expression: 
          (LITERAL this: 1, is_string: False)), expression: 
        (EQ this: 
          (COLUMN this: 
            (IDENTIFIER this: col2, quoted: False)), expression: 
          (LITERAL this: 2, is_string: False))), expression: 
      (EQ this: 
        (COLUMN this: 
          (IDENTIFIER this: col3, quoted: False)), expression: 
        (LITERAL this: 3, is_string: False)))))
```

Basically it's parsing it as `WHERE(AND(OR(condition1, condition 2), condition 3))` but it should be `WHERE(OR(condition1, AND( condition 2, condition 3)))`

Screenshot:
<img width="1301" alt="image" src="https://github.com/tobymao/sqlglot/assets/140655443/65ad8e65-19d3-4757-9f72-7b2f1d1221d4">

**Comment by kunal-wisdom** [comment]
So I do see it documented for redshift for example: 
https://docs.aws.amazon.com/redshift/latest/dg/r_logical_condition.html

```
The NOT operator is evaluated before AND, and the AND operator is evaluated before the OR operator. Any parentheses used may override this default order of evaluation.
```

Anyways, is it possible to configure a precedence? If not we will definitely try a workaround and fall back to adding parentheses.

**Comment by kunal-wisdom** [comment]
By the way, really appreciate the prompt responses here! And great work with the library overall :)

**Comment by tobymao** [comment]
you’d have to have a customized parser that treats and and ors differently
