### ISSUE TITLE
bigquery user-defined function `OPTIONS` syntax doesn't parse

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2290]
**Fully reproducible code snippet**

This BigQuery SQL fails to parse:

```
In [6]: import sqlglot as sg

In [7]: sql = '''
   ...: CREATE TEMPORARY FUNCTION string_length_0(strings ARRAY<STRING>)
   ...: RETURNS FLOAT64
   ...: LANGUAGE js AS """
   ...: 'use strict';
   ...: function string_length(strings) {
   ...:     return _.sum(_.map(strings, ((x) => x.length)));
   ...: }
   ...: return string_length(strings);
   ...: """
   ...: OPTIONS (
   ...:     library=['gs://ibis-testing-libraries/lodash.min.js']
   ...: );
   ...: '''

In [8]: sg.parse_one(sql)
...
ParseError: Invalid expression / Unexpected token. Line 11, Col: 9.
```

**Official Documentation**

https://cloud.google.com/bigquery/docs/user-defined-functions#including-javascript-libraries

**Comment by GeorgeSittas** [comment]
I can take a look into this soon

**Comment by GeorgeSittas** [comment]
@cpcloud can you double check if the above statement is syntactically correct? Based on BQ's [docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_function_statement), it seems that when creating JS UDFs, the `OPTIONS` property comes before `AS javascript_code`.

**Comment by cpcloud** [comment]
Sweet! Yeah as long as it can be parsed and the SQL emitted is valid then it should be totally fine to put it wherever's easiest for you.

**Comment by cpcloud** [comment]
I will likely change the way ibis is constructing these as well. I find it easier to read all the configuration up front and end with the code.
