### ISSUE TITLE
What about differnt parsing policy for different dialects?

### ISSUE THREAD

**Issue by zeninpalm** [tobymao/sqlglot#23]
Hi Toby,

I'm using sqlglot to parse the SQL syntax from Hive 3.0. There are some new keywords and new syntax, I have to change the lexer and parser somehow, but those keywords and syntax are not supported in MySQL or PostgreSQL at all.

So, I got this idea, what about moving the tasks of parsing those uncommon and special syntax into those specific dialects? And we may need to change the interface a little, for example, the users may use sqlglot.parse(code, dialect='hive-3') to indicate which dialect to use. Of course, if the user doesn't specify any dialect, we will keep using the existing logic 😄 

I would like to do this refactoring for sqlglot if you don't mind, or if you think this change violates the philosophy of sqlglot, I may create a new project based on sqlglot.

Please let me know if you think it's OK, thanks.

**Comment by zeninpalm** [comment]
Sorry, I just noticed that you already have this scalability built into sqlglot, great job!
I will work on the existing framework now.

**Comment by tobymao** [comment]
sounds good, happy to discuss anything if you have questions
