### ISSUE TITLE
Add Bigquery COPY statement to the parser

### ISSUE THREAD

**Issue by razvan-am** [tobymao/sqlglot#2304]
**Is your feature request related to a problem? Please describe.**
Bigquery dialect parser does not seem to recognize the COPY statement.

**Describe the solution you'd like**
Add the copy statement to the parser.
Documentation [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_copy)

**Describe alternatives you've considered**

At the moment I'm using my own regex function whenever I encounter a copy statement but a better implementation would be usefull.

**Additional context**

Sample sql code to be recognized
```
create or replace table `my_project.my_dataset.my_destination_table` copy `my_project.my_dataset.my_source_table`;
```

**Comment by razvan-am** [comment]
I'm thinking we can reopen this due to [#2307 ]

**Comment by GeorgeSittas** [comment]
What do you mean?

**Comment by razvan-am** [comment]
```python

import sqlglot


try:
    parsed_object = sqlglot.parse_one('create or replace table `my_project.my_dataset.my_destination_table` copy `my_project.my_dataset.my_source_table`;', read='bigquery')
except sqlglot.errors.ParseError as e:
    print(e.errors)
    parsed_object= None
print(parsed_object)
```

```
{'description': 'Invalid expression / Unexpected token', 'line': 1, 'col': 73, 'start_context': 'create or replace table `my_project.my_dataset.my_destination_table` ', 'highlight': 'copy', 'end_context': ' `my_project.my_dataset.my_source_table`;', 'into_expression': None}]
```

**Comment by GeorgeSittas** [comment]
Are you using the latest main branch or just the latest sqlglot version deployed in pypi?

**Comment by razvan-am** [comment]
pypi

**Comment by GeorgeSittas** [comment]
This hasn't been released yet. Check out latest main if you need the patch earlier.

**Comment by razvan-am** [comment]
Thank you. I tested after you asked me. Seems to work as intended. How can I see a release schedule and/or release notes.

**Comment by GeorgeSittas** [comment]
There's no release schedule but we deploy new releases frequently. Should be a couple of days, I think.
