### ISSUE TITLE
clickhouse: heredoc is not parsable

### ISSUE THREAD

**Issue by pkit** [tobymao/sqlglot#2316]
```python
import sqlglot

sql = """
SELECT $$this is a heredoc string$$
"""
print(sqlglot.parse_one(sql, read="clickhouse"))
```
```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 2, Col: 18.
  
SELECT $$this is a heredoc string$$
```

docs: https://clickhouse.com/docs/en/sql-reference/syntax#heredoc

_Note: `$$anything$$` is a form of heredoc too, i.e. `SELECT $$aaa$$this is a heredoc string$$aaa$$`, and it could be multiline, etc._

**Comment by GeorgeSittas** [comment]
Ah this seems like a tricky one, sort of like a dynamically generated "raw string" token pair.. Will see if it's easy to alter the tokenizer to add support for it. Do you know of any other dialect that supports this @pkit?

**Comment by pkit** [comment]
@GeorgeSittas I suppose postgres stored procedure definitions are exactly the same?

**Comment by pkit** [comment]
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

**Comment by GeorgeSittas** [comment]
I see, yeah I remembered now. I think we'd only added support for the "untagged" variant of this syntax, e.g. `$$foo$$`. I'll take a look and try to add support for this, but if it's too tricky I might postpone it for later since it's not high priority.

**Comment by pkit** [comment]
I don't need more than "one liner" support for that one too.
But failing is not an option. :)

**Comment by pkit** [comment]
Ok, I think I found a workaround for now. 
This one is essentially a pure string replacement so I can inject tokens and then "post-process" it myself. Kinda ugly though...

**Comment by tobymao** [comment]
why don't you just make this a comment?
