### ISSUE TITLE
Matching Column with Table

### ISSUE THREAD

**Issue by charliemday** [tobymao/sqlglot#2318]
**Is your feature request related to a problem? Please describe.**
I'd like to match the column names with the table they're associated with

**Describe the solution you'd like**
Take the expression:

`SELECT * FROM users_user WHERE date_joined >= '2022-01-01'`

Would expect an output of:

```
{
  "table": "users_user",
  "columns": ["date_joined"]
}
```

**Describe alternatives you've considered**
Manually doing this by going over the column and table names and generating a dict however sometimes the `column.table` is empty for example if you were to use the SQL expression above

```
for col in parse_one(sql).find_all(exp.Column):
    print(col.name) # date_joined
    print(col.table) 

# col.table = ''
```

**Comment by GeorgeSittas** [comment]
You need to pass in a schema to achieve this, take a look at optimizer's `qualify` function. The `scope` module might be useful too. Closing this but you can reach out if you want in [slack](https://tobikodata.com/slack).
