### ISSUE TITLE
ParseError raised when clickhouse SQL include sample clause

### ISSUE THREAD

**Issue by yagggi** [tobymao/sqlglot#2323]
When parsing clickhouse SQL with `sample` clause, there's an error raised.

**Fully reproducible code snippet**

```
import sqlglot

sql = """
SELECT sum(PageViews * _sample_factor)
FROM visits
SAMPLE 10000000
"""

print(sqlglot.parse_one(sql, read="clickhouse"))
```
```
ParseError: Invalid expression / Unexpected token. Line 3, Col: 15.
  SELECT sum(PageViews * _sample_factor)
FROM visits
SAMPLE 10000000
```

**Official Documentation**
[clickhouse sample clause](https://clickhouse.com/docs/en/sql-reference/statements/select/sample)

**Comment by yagggi** [comment]
Hi @GeorgeSittas , thanks for your quick reaction, but I noticed that there is a weird behavior, a redundant parenthesis is required otherwise `ParseError` will be raised. Please see below code snippet for reference:

```
In [64]: sqlglot.__version__
Out[64]: '18.8.0'

In [68]: sql = """
    ...: SELECT * FROM (SELECT a from b SAMPLE 0.01)
    ...: """

In [69]: print(sqlglot.parse_one(sql, read="clickhouse"))
...
ParseError: Expecting ). Line 2, Col: 43.

In [70]: sql = """
    ...: SELECT * FROM (SELECT a from b SAMPLE 0.01)) /* <-- here is the required redundant ')' */
    ...: """

In [71]: print(sqlglot.parse_one(sql, read="clickhouse"))
SELECT * FROM (SELECT a FROM b SAMPLE (0.01))
```

**Comment by GeorgeSittas** [comment]
@yagggi thanks, seems like an oversight. Fixed in the linked PR

**Comment by yagggi** [comment]
Have tested the latest version and `SAMPLE` works fine, thanks.
