### ISSUE TITLE
transformation from qualify to project + where

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2338]
**Is your feature request related to a problem? Please describe.**

Not really related to a problem.

**Describe the solution you'd like**

I'd like `QUALIFY` queries to be transformed into their non-`QUALIFY` equivalent for dialects that don't support `QUALIFY` syntax.

```sql
SELECT x, y
FROM t
QUALIFY SUM(s) OVER () > 2
```

becomes

```sql
SELECT x, y
FROM (
  SELECT *, SUM(s) OVER () > 2 AS col0
  FROM t
) table0
WHERE table0.col0
```

**Describe alternatives you've considered**

I haven't considered any alternatives.

**Additional context**

- DuckDB `QUALIFY`: https://duckdb.org/docs/sql/query_syntax/qualify.html
- Snowflake `QUALIFY`: https://docs.snowflake.com/en/sql-reference/constructs/qualify

**Comment by GeorgeSittas** [comment]
We already have this [transformation](https://github.com/tobymao/sqlglot/blob/main/sqlglot/transforms.py#L86) in place, perhaps just need to add it to another dialect to take effect?

**Comment by cpcloud** [comment]
Excellent! Lemme poke around and see about adding it to some dialects.

**Comment by GeorgeSittas** [comment]
Cool, feel free to open a PR if it's missing from somewhere :)

Gonna go ahead and close this one.
