### ISSUE TITLE
sqlglot cannot parse double-dot tables <catalog_name>.<schema_name>.<table_name>

### ISSUE THREAD

**Issue by xinglin-zhao** [tobymao/sqlglot#235]
Hi there, recently I am exploring the databricks [Unity catalog ](https://docs.microsoft.com/en-us/azure/databricks/data-governance/unity-catalog/create-tables#create-a-managed-table). The full name of a table will be something like <catalog_name>.<schema_name>.<table_name>. 

I try to use sqlglot.parse_one to parse queries using this full name table (double dots), it failed with error like:
ParseError: Invalid expression / Unexpected token. Line 1, Col: 20.
  select a,d from b.c.e

I wonder if we can add support to parse this type of double dots tables or any number of dots tables.

**Comment by tobymao** [comment]
this works for me in v4.1.1

```
(env) [toby@muc sqlglot]$ python -m sqlglot "select a,d from b.c.e"
SELECT
  "a",
  "d"
FROM "b"."c"."e"
(env) [toby@muc sqlglot]$ python -m sqlglot "select a,d from b.c.e" --parse
(SELECT expressions:
  (COLUMN this:
    (IDENTIFIER this: a, quoted: False)),
  (COLUMN this:
    (IDENTIFIER this: d, quoted: False)), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: e, quoted: False), db:
      (IDENTIFIER this: c, quoted: False), catalog:
      (IDENTIFIER this: b, quoted: False))))
```
