### ISSUE TITLE
Snowflake - Querying data in Stage Files, "format" is not supported.

### ISSUE THREAD

**Issue by ShayYaari** [tobymao/sqlglot#2363]
Hello!

According to Snowflake documentation, the following query should be valid: (https://docs.snowflake.com/en/user-guide/querying-stage)

`
SELECT t.$1, t.$2 FROM @mystage1 (file_format => myformat) t;
`

However it seems like the last part of the query: `(file_format => myformat)` is not supported by the lib.

**Comment by tobymao** [comment]
please follow the the instructions on the issues template and check main next time.
