### ISSUE TITLE
generated sql of current_date doesn't include the parens

### ISSUE THREAD

**Issue by xiaoling** [tobymao/sqlglot#2370]
I checked out main and ran `make install`. Hope i didn't miss anything obvious. thanks!

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```
>>> import sqlglot
>>> sqlglot.__version__
'18.11.3.dev1'
>>> sqlglot.exp.CurrentDate(expressions=[]).sql()
'CURRENT_DATE'
>>> sqlglot.parse_one("SELECT CURRENT_DATE()", dialect='snowflake').sql(dialect='snowflake')
'SELECT CURRENT_DATE'
>>> sqlglot.parse_one("SELECT CURRENT_DATE()").sql()
'SELECT CURRENT_DATE'
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by GeorgeSittas** [comment]
`CURRENT_DATE` doesn't need parentheses in the Snowflake dialect, so I don't see any issue here.
