### ISSUE TITLE
Return warning instead of exception on parsing errors

### ISSUE THREAD

**Issue by Nitrino** [tobymao/sqlglot#2378]
**Is your feature request related to a problem? Please describe.**
I come across quite a variety of SQL schemas and `sqlglot` can't always parse this syntax. Often expressions that cannot be parsed are not important to the operation of my application and can be omitted.

**Describe the solution you'd like**
Add `raise_exeption = False` parameter, for `parse` method. 
By default this parameter can be `True` and it will not break backward compatibility
```python
    sql = """
        Some unexpected syntax
    """
    parsed_sql_exprs = sqlglot.parse(sql, read="mysql", raise_exeption=False)
```

**Describe alternatives you've considered**
As an alternative, I can see implementing the `parse` method on my side, but then I will probably have to use a non-public interface and there may be problems with updates

**Comment by GeorgeSittas** [comment]
This is already supported, you need to do something like `sqlglot.parse(sql, error_level=sqlglot.ErrorLevel.IGNORE)`:

```python
>>> import sqlglot
>>> from sqlglot import ErrorLevel
>>>
>>> sqlglot.parse_one("select", error_level=ErrorLevel.IGNORE)
(SELECT )
```

**Comment by Nitrino** [comment]
@GeorgeSittas wow cool, thanks!
