### ISSUE TITLE
Modifying SQL using node. Question

### ISSUE THREAD

**Issue by JDRanpariya** [tobymao/sqlglot#238]
I'm having query like ``` select A.name, B.name, A.id, A.city from db1.Pub.T1 A Full Outer Join db1.Pub.country B On A.name = B.name;```

So, I want to replace `A.name` with `A.name as alias`. I'm trying to do that with following query
```
expression_tree = parse_one(query)

def transform_col_to_alias(node):
    if isinstance(node, exp.Column):
        return parse_one(f"{node.name} {(node.name).title()}")
    return node

transformed_tree = expression_tree.transform(transform_col_to_alias)
print(transformed_tree.sql())
```
The output Expected is: 
```SELECT A.name AS Name, B.name AS Name, id AS Id, city AS City  from db1.Pub.T1 A Full Outer Join db1.Pub.country B On A.name = B.name```

But this is what I'm getting:
```SELECT name AS Name, name AS Name, id AS Id, city AS City FROM db1.Public.Table1 AS A FULL OUTER JOIN db1.Public.countries AS B ON name AS Name = name AS Name```

Q1. how do I get the table name from node( i.e A and B)?
Q2. Is there a better way to do it?
Q3. How do I just transform the part between select and from, not affecting A.name = B.name?
Q4. Do we have any documentation for usage in depth?

**Comment by tobymao** [comment]
you can do

```
def transform(node):
    if isinstance(node, exp.Column):
         return exp.alias_(my_alias, node)
```

q3 you could check that the node.parent is not in a condition

```
if not node.find_ancestor(exp.Predicate):
```

q4. the documentation is the readme and the docstrings in the code

happy to answer anymore questions

**Comment by JDRanpariya** [comment]
Thanks that really helped. Trying to make sense of code by looking at docstrings. Any other material you would suggest to easily understand the code base?
