### ISSUE TITLE
Missing comma versus Alias

### ISSUE THREAD

**Issue by roberto-hakkoda** [tobymao/sqlglot#2382]
**Dialect**
- snowflake
- although I think this applies to all dialects

**Fully reproducible code snippet**
Invalid query (aka comma missing after second attribute):
```sql
 select attribute_01,
        attribute_02
        attribute_03,
        attribute_04,
   from my_table
```

Expected outcome:
```json
[
  {
    "description": "Invalid expression / Unexpected token",
    "line": 5,
    "col": 20,
    "start_context": "select attribute_01,\n        attribute_02\n        ",
    "highlight": "attribute_03",
    "end_context": ",\n        attribute_02\n   from my_table\n;",
    "into_expression": null
  }
]
```

Actual result (attribute 3 is treated as the alias for attribute 2, even though it is on a separate line)
```sql
 select attribute_01,
        attribute_02 as
        attribute_03,
        attribute_04,
   from my_table
```

Would it make sense to:
- add an argument to disallow aliases on a separate line, or
- add a warning to indicate that there is an alias on a separate line and highlight which line number(s) that happened on?

Thanks for the lovely work!!

**Comment by tobymao** [comment]
sqglot is not a validation library, and this is legal sql as it is an alias

**Comment by roobyz** [comment]
Thanks for the quick reply.

I understand, although the third attribute wasn't intended to be an alias, by accidentally missing the comma:
- even though the generated outcome is wrong
- the syntax is still technically _correct_

Was hoping that there could be an simple warning approach, to alert users when this potentially unintended user-error occurs. We'll just need to add some kind of unit test for this. Thanks again!!

**Comment by tobymao** [comment]
it is not simple because the parser has no notion of white space. this would be very difficult to detect
