### ISSUE TITLE
Parsing oracle queries having SQL/JSON functions like JSON_*

### ISSUE THREAD

**Issue by Shweta-BI-Lead** [tobymao/sqlglot#2391]
I have been trying to parse our Oracle queries using sqlglot. It's been very useful so far. 
I have observed that sqlglot parsing fails for few SQL/JSON functions like JSON_OBJECT, JSON_OBJECTAGG, JSON_ARRAY, JSON_TABLE, JSON_VALUE etc.

**Sample oracle query snippet - ** 
```
JSON_TABLE(res,'$.info[*]' COLUMNS (
tempid NUMBER PATH '$.tempid',
NESTED PATH '$.calid[*]' COLUMNS (
last_dt PATH '$.last_dt '))) src
```
For above query, sqlglot.parse_one method fails to parse. Similarly, it doesn't parse other JSON methods too.

**Official Documentation -**
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/JSON_TABLE.html#GUID-09422D4A-936C-4D38-9991-C64101283D98

Request team to look into this. Thank you!

**Comment by GeorgeSittas** [comment]
@Shweta-BI-Lead is `NESTED` required in this syntax, or is it optional? Is the following equivalent to the above?

```
JSON_TABLE(res,'$.info[*]' COLUMNS (
tempid NUMBER PATH '$.tempid',
PATH '$.calid[*]' COLUMNS (
last_dt PATH '$.last_dt '))) src
```

**Comment by Shweta-BI-Lead** [comment]
Thank you for the quick fix.
