### ISSUE TITLE
Misplaced NOT keyword after parsing

### ISSUE THREAD

**Issue by sharmagg** [tobymao/sqlglot#2398]
I have a SQL statement ```SELECT * FROM x WHERE y IS NOT NULL```
and I have make some changes in its AST and get the output sql again. But the final output is misplacing the ```NOT``` keyword.
Output - ```SELECT * FROM x WHERE NOT y IS NULL```
This is incorrect. Here is the code to reproduce the error.
```
import sqlglot
query = """SELECT * FROM x WHERE y is NOT NULL"""
ast = sqlglot.parse_one(query, 'hive')
ast.sql()
```

**Comment by GeorgeSittas** [comment]
It's not incorrect, the semantics of the query are preserved.

**Comment by GeorgeSittas** [comment]
Related discussion: https://github.com/tobymao/sqlglot/discussions/274
