### ISSUE TITLE
`ANY()` method used instead of `has()` in ClickHouse

### ISSUE THREAD

**Issue by samuelcolvin** [tobymao/sqlglot#2408]
```py
import sqlglot
sql = "select * from table where x = any(ARRAY[1, 2, 3])"
print(sqlglot.parse_one(sql, read='postgres').sql(dialect='clickhouse'))
#> SELECT * FROM table WHERE x = ANY ([1, 2, 3])
```

Should be translated to `SELECT * FROM table WHERE has([1, 2, 3], x)`.

---

Don't worry, no more issues from me for now - this is the last issue from me today - I only have two failing unit tests, both caused by this.

**Comment by samuelcolvin** [comment]
FWIW

Here's a transform function I'm using:

```py
def replace_any_in(node: Exp) -> Exp:
    if isinstance(node, exp.Binary) and isinstance(node.right, (exp.AnyValue, exp.Any)):
        if isinstance(node, exp.EQ):
            prefix = ''
        elif isinstance(node, exp.NEQ):
            prefix = 'NOT '
        else:
            raise InvalidSql(f'unknown binary node: {node}')

        left_sql = node.left.sql(dialect='clickhouse')
        if isinstance(node.right, exp.Any):
            right_value = node.right.this.this
        else:
            right_value = node.right.this
        right_sql = right_value.sql(dialect='clickhouse')
        return sqlglot.parse_one(f'{prefix}has({right_sql}, {left_sql})', read='clickhouse')
    elif isinstance(node, exp.In):
        field = node.args['field']
        field_sql = field.sql(dialect='clickhouse')
        this_sql = cast(Exp, node.this).sql(dialect='clickhouse')
        return sqlglot.parse_one(f'has({field_sql}, {this_sql})', read='clickhouse')

    return node
```

**Comment by samuelcolvin** [comment]
Your fix is incorrect, you're assuming that `has(a)` is equivalent to `any(a)`, in fact `has(a, b)` is equivalent to `b = any(a)`.

Also, as per my snippet, it would be nice if `b in a` was also replaced with `has(a, b)`, i should have mentioned that in the issue.

Can I also suggest that allowing issue creators to review fixed before merging them will lead to less churn 😄.

**Comment by tobymao** [comment]
woops, can you create a new issue for in the in case?

**Comment by tobymao** [comment]
tested IN on clickhouse with an array and it works fine so i'm not going to do anything  there for now
