### ISSUE TITLE
Upgrade build setup?

### ISSUE THREAD

**Issue by samuelcolvin** [tobymao/sqlglot#2410]
Again, thanks for sqlglot, it's awesome.

It's slightly surprising that an actively developed project like this is still using an outdated build configuration.

Would you be open to switching:
* `setup.py` and `setup.cfg` to `pyproject.toml`
* `autoflake` and `isort` to `ruff`
* `unittest` to `pytest`

?

**Comment by tobymao** [comment]
happy to accept a pr to go to pyproject.toml and ruff as long as all configurations are the same, not interested in pytest, i much prefer unittest
