### ISSUE TITLE
Transpiler for Teradata dialect modifies TOP<N> command

### ISSUE THREAD

**Issue by Srivatzn** [tobymao/sqlglot#2419]
Since TOP is a supported command in Teradata, the transpiler should not translate the SQL with TOP to LIMIT. Also LIMIT is not supported in Teradata.

```python
import sqlglot

sqlglot.transpile("select top 10 column1 from table1.column1", identity=True, read="snowflake", write="teradata")
```

Output:

`['SELECT column1 FROM table1.column1 LIMIT 10']`

Expectation:

`['SELECT TOP 10 column1 FROM table1.column1']`

Please let me know if I am missing anything.

**Comment by tobymao** [comment]
do you have documentation showing they don’t support limit?
