### ISSUE TITLE
Generating random SQL queries

### ISSUE THREAD

**Issue by MohammadrezaPourreza** [tobymao/sqlglot#2421]
Hello,
Thank you for providing such an excellent library. I'm curious to know if there's a way to utilize the parser to generate random SQL queries for database testing purposes?

**Comment by tobymao** [comment]
i don't think you can use the parser, but you can use the sqlglot builder api for this

https://github.com/tobymao/sqlglot#build-and-modify-sql

**Comment by MohammadrezaPourreza** [comment]
@tobymao Thanks for your quick response, Can I generate random queries samples from your grammar?
Using the builder I have to define another grammar to generate random SQL queries.
I really appreciate your help with this matter

**Comment by tobymao** [comment]
i don't know what you mean by generate random queries samples from my grammar. but that sounds hard given that sqlglot implements a hand written recursive descent parser
