### ISSUE TITLE
Snowflake dayofmonth function is re-written to DAY_OF_MONTH which causes compilation error

### ISSUE THREAD

**Issue by Sorrop** [tobymao/sqlglot#2422]
Hi there! I have a use-case where I need to parse the user's `snowflake` flavored SQL, perform some manipulation to the AST and convert it back to SQL string. It looks like if the sql calls the `dayofmonth` function, it gets rewritten to `DAY_OF_MONTH` which triggers an error when one tries to execute. 

Is there maybe a way to [opt out](https://sqlglot.com/sqlglot/generator.html#Generator) of such re-writing when converting back to sql by providing some option to the sql method? I tried using `normalize_functions=False` but didn't seem to work

**Fully reproducible code snippet**
sqlglot version: `17.16.0`
```python
import sqlglot
parsed = sqlglot.parse_one("select dayofmonth(current_timestamp);", dialect="snowflake")
parsed.sql(dialect="snowflake")
# 'SELECT DAY_OF_MONTH(CURRENT_TIMESTAMP())'
```

**Official Documentation**
https://docs.snowflake.com/en/sql-reference/functions/year

**Error when executed**
```
SQL compilation error:
Unknown function DAY_OF_MONTH
```

**Comment by GeorgeSittas** [comment]
This should become available in the next release, thanks for the report @Sorrop.
