### ISSUE TITLE
Redshift to Trino datediff transpilation data issue

### ISSUE THREAD

**Issue by as-sher** [tobymao/sqlglot#2423]
When transpiling datediff in redshift does not perform same as trino 

Redshift 
SELECT datediff('month', TIMESTAMP '2020-02-29 00:00:00', TIMESTAMP '2020-03-02 00:00:00');
Output
1

Trino
SELECT date_diff('month', TIMESTAMP '2020-02-29 00:00:00', TIMESTAMP '2020-03-02 00:00:00');
Output
0

Is this by design or should we fix this, would be happy to help here.

**Comment by GeorgeSittas** [comment]
It seems like Trino's implementation is different in that it factors in the days / hours of a timestamp and possibly rounds down somehow too.

**Comment by GeorgeSittas** [comment]
I think that in order to match Trino's semantics in Redshift, for instance, one would have to do something like:

```sql
SELECT EXTRACT('month' FROM TIMESTAMP '2020-03-02 00:00:00' - TIMESTAMP '2020-02-29 00:00:00')
```

This results in `0`. Conversely, we'd need to do the following in Trino to match Redshift's semantics:

```sql
trino> SELECT MONTH(TIMESTAMP '2020-03-02 00:00:00') - MONTH(TIMESTAMP '2020-02-29 00:00:00');
 _col0 
-------
     1 
(1 row)
```

@tobymao maybe should we encode this in the AST level.

**Comment by tobymao** [comment]
this would need to be encoded at the ast level to understand the intention of these functions

**Comment by GeorgeSittas** [comment]
I can try to take a stab at this tomorrow

**Comment by GeorgeSittas** [comment]
@as-sher this has turned out to be more tricky than initially expected, so I'm going to hold off working on a complete solution for now since it's not high-priority.

Feel free to join our [Slack](https://tobikodata.com/slack) if you're interested in working on this and want to chat about it.
