### ISSUE TITLE
Trino to spark-sql date_diff gives syntax issue.

### ISSUE THREAD

**Issue by as-sher** [tobymao/sqlglot#2426]
When transpiling date_diff in trino to spark-sql

Trino
SELECT date_diff('month', TIMESTAMP '2020-02-29 00:00:00', TIMESTAMP '2020-03-02 00:00:00');

Spark-sql 
SELECT DATEDIFF(month, CAST('2020-02-29 00:00:00' AS TIMESTAMP), CAST('2020-03-02 00:00:00' AS TIMESTAMP))

But spark does not support 3 params in datediff 
https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.functions.datediff.html
Please can you help here?

**Comment by GeorgeSittas** [comment]
It does work with 3 parameters, it's just not documented well:

```python
>>> import sqlglot
>>> sqlglot.transpile("SELECT date_diff('month', TIMESTAMP '2020-02-29 00:00:00', TIMESTAMP '2020-03-02 00:00:00');", "trino", "spark")
["SELECT DATEDIFF(month, CAST('2020-02-29 00:00:00' AS TIMESTAMP), CAST('2020-03-02 00:00:00' AS TIMESTAMP))"]
```

```
spark-sql (default)> SELECT DATEDIFF(month, CAST('2020-02-29 00:00:00' AS TIMESTAMP), CAST('2020-03-02 00:00:00' AS TIMESTAMP));
0
Time taken: 4.423 seconds, Fetched 1 row(s)
```

**Comment by GeorgeSittas** [comment]
FWIW if you're using Spark v2 then there's an option to transpile towards that to avoid this issue if needed:

```python
>>> import sqlglot
>>> sqlglot.transpile("SELECT date_diff('month', TIMESTAMP '2020-02-29 00:00:00', TIMESTAMP '2020-03-02 00:00:00');", "trino", "spark2")
["SELECT MONTHS_BETWEEN(CAST('2020-03-02 00:00:00' AS TIMESTAMP), CAST('2020-02-29 00:00:00' AS TIMESTAMP))"]
```

**Comment by as-sher** [comment]
Thanks a ton

**Comment by as-sher** [comment]
@GeorgeSittas  the query
`["SELECT MONTHS_BETWEEN(CAST('2020-03-02 00:00:00' AS TIMESTAMP), CAST('2020-02-29 00:00:00' AS TIMESTAMP))"]`
Gives a decimal number which is not same as redshift.

SELECT months_between('1997-02-28 10:30:00', '1996-10-30');
>> 3.94959677

**Comment by GeorgeSittas** [comment]
@as-sher take a look at 2445, it should address this issue I believe, cc @tobymao
