### ISSUE TITLE
Lineage not able to handle alias in subquery

### ISSUE THREAD

**Issue by eliaperantoni** [tobymao/sqlglot#2431]
**Fully reproducible code snippet**

```python
from sqlglot.lineage import lineage
sql = "SELECT (SELECT max(t3.my_column) FROM table3 t3) AS output FROM table3"
sources = {
    "table3": "SELECT 1 AS my_column"
}

lin = lineage("output", sql, dialect="postgres")
```

When inspecting the HTML result you get this:

<img width="356" alt="image" src="https://github.com/tobymao/sqlglot/assets/6002855/bfc5fc8f-6962-4a96-ad90-d0a26c5bcf85">

And printing the result of the `lineage` call also confirms that it's not a bug in the HTML renderer:

```shell
~/code/lineage > poetry run python demo.py | grep PLACEHOLDER
        (IDENTIFIER this: table3, quoted: False))))), downstream=[Node(name='t3.my_column', expression=(PLACEHOLDER ), source=(PLACEHOLDER ), downstream=[], alias='')], alias='')
```

---

By removing the `table3 t3` alias (i.e. `SELECT (SELECT max(my_column) FROM table3) AS output FROM table3`) it works correctly again:

<img width="342" alt="image" src="https://github.com/tobymao/sqlglot/assets/6002855/a3d2cf94-4c0b-4c14-8226-b13150371a0a">

**Comment by eliaperantoni** [comment]
That was lightning quick, thank you!

**Comment by tobymao** [comment]
@eliaperantoni thanks for the issue, and feel free to join us on [slack](https://tobikodata.com/slack) if you wanna chat about anything!

**Comment by eliaperantoni** [comment]
@tobymao I'm afraid I found another counterexample:

```sql
SELECT
    sum(
        (SELECT max(t1.my_column) from table1 t1)
    ) AS output
FROM table1
```

It works either by removing the alias `table1 t1` or by unwrapping the subquery from the `sum`. But, as-it-is, it will return a `Placeholder`.
