### ISSUE TITLE
`REGEXP_REPLACE` `'g'` argument to enable global replacement is not rendered

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2436]
**Is your feature request related to a problem? Please describe.**

Sort of. I can't generate SQL to globally replace a matched string using `REGEXP_REPLACE` with DuckDB

**Describe the solution you'd like**

I'd like the fourth argument to be rendered when using

```python
sg.func("REGEXP_REPLACE", col, pattern, replacement, 'g')
```

**Describe alternatives you've considered**

Manually rendering the SQL

**Additional context**
N/A

**Comment by tobymao** [comment]
why is this only “sort of a problem”, can you share some docs with this? will help me make sure i implement the right thing

**Comment by cpcloud** [comment]
Sorry, by "sort of" I meant it's sort of related to a problem (answering the issue template question).

Thinking about it again, this is definitely just a regular problem 🙂

Re docs: here are the text function docs: https://duckdb.org/docs/sql/functions/char.html

The thing I'm interested in is being able to pass `'g'` to `regexp_replace` as shown here:

![image](https://github.com/tobymao/sqlglot/assets/417981/e9484d61-4826-4a73-9ff8-a34981b6c702)
