### ISSUE TITLE
Erroneous handling of redshift's JSON_PARSE

### ISSUE THREAD

**Issue by Sorrop** [tobymao/sqlglot#2442]
**sqlglot version: 18.16.1**

**Fully reproducible code snippet**
```python
import sqlglot
sql = "SELECT JSON_PARSE('[10001,10002,\"abc\"]');"
parsed = sqlglot.parse_one(sql,dialect="redshift")
parsed.sql(dialect="redshift")
#'SELECT PARSE_JSON(\'[10001,10002,"abc"]\')'
```
The generated sql triggers an error when executed in redshift

>Failed to execute query: ERROR: function parse_json("unknown") does not exist
  Hint: No function matches the given name and argument types. You may need to add explicit type casts.

**Official Documentation**
https://docs.aws.amazon.com/redshift/latest/dg/JSON_PARSE.html

**Comment by purcell** [comment]
Suggested a fix in #2443 — turns out Trino uses the same naming.
