### ISSUE TITLE
ClickHouse doesn't allow plurals for interval units

### ISSUE THREAD

**Issue by samuelcolvin** [tobymao/sqlglot#2448]
We currently have the following transformation:

```py
        elif isinstance(node, exp.Interval) and isinstance(node.unit, exp.Var) and node.unit.this.endswith(('s', 'S')):
            # clickhouse requires interval units not to be plural, note this wouldn't work for "centuries",
            # but CH doesn't support that anyway
            return exp.Interval(this=node.this, unit=exp.Literal.string(node.unit.this[:-1]))
```

[Clickhouse documentation](https://clickhouse.com/docs/en/sql-reference/data-types/special-data-types/interval)

types supported:
* `NANOSECOND`
* `MICROSECOND`
* `MILLISECOND`
* `SECOND`
* `MINUTE`
* `HOUR`
* `DAY`
* `WEEK`
* `MONTH`
* `QUARTER`
* `YEAR`

[Postgres documentation](https://www.postgresql.org/docs/current/datatype-datetime.html#:~:text=unit%20is%20microsecond%2C%20millisecond%2C%20second%2C%20minute%2C%20hour%2C%20day%2C%20week%2C%20month%2C%20year%2C%20decade%2C%20century%2C%20millennium%2C%20or%20abbreviations%20or%20plurals%20of%20these%20units):

> `unit` is `microsecond`, `millisecond`, `second`, `minute`, `hour`, `day`, `week`, `month`, `year`, `decade`, `century`, `millennium`, or abbreviations or plurals of these units

Technically there's also the issue that `decade`, `century` and `millennium` won't be supported by Clickhouse although they are else where, but that's not a big issue for us.

**Comment by GeorgeSittas** [comment]
@samuelcolvin I think ClickHouse allows plural forms too, I just tried in their playground and doesn't seem to be a problem. Can you share some context on why you need this transformation? Or maybe some docs that show that some units can't be plural.

**Comment by samuelcolvin** [comment]
Weird, I got an error earlier but maybe I was being dumb. I'll comment again here if I find the issue.

**Comment by samuelcolvin** [comment]
Somewhat related, this doesn't work:

```py
sqlglot.transpile("SELECT interval '500' us", read="postgres", write="clickhouse")[0]
```

prints `"SELECT INTERVAL '500' us"` which [fails](https://fiddle.clickhouse.com/729b6bf3-8d41-4f2f-9264-3b2c3ca0f4c7) on clickhouse.

**Comment by GeorgeSittas** [comment]
What is the `us` unit?

**Comment by tobymao** [comment]
micros?

**Comment by samuelcolvin** [comment]
Yes, others like `ms`, `s`, `m` work in Pg too.

**Comment by GeorgeSittas** [comment]
Got it will look deeper thanks
