### ISSUE TITLE
Keeping comments at the end of a query

### ISSUE THREAD

**Issue by yogevyuval** [tobymao/sqlglot#2459]
In Snowflake, a common practice is to add a comment with some info to the end of a query, so it can later be tracked down when analyzing queries that ran. It has to be at the end since SF removes comments at the beginning of a query.

I've been trying to experiment with the comments api but i'm facing 2 challenges:

1. When you hold a reference to a query, you essentially hold a reference to the beginning of a the query tree, which means if you call add_comments the comments are appended at the beginning. Is there a way to get the "last" item in the query tree? I've been trying to use q.walk()[-1] but it does really achieve the goal, since the tree is not necessarily organized the way the query is actually being printed at the end. For example for the query `SELECT * from table where field = value order by field1 limit 10`, I would like to add a comment to the "limit 10" part, but the limit is not the last leaf of the tree.

2. It would be even better than solving 1, to have a more consistent way to make sure a query have a comment at the end, even when the query changes. Let's say I managed to get the "last" element of the query, but now I'm using sqlglot to make some changes to the query, I now need to keep track and "move" the comment to the last element each time.

Appreciate your thoughts!

**Comment by GeorgeSittas** [comment]
Perhaps you could solve this at the tokenization level, i.e. by extracting the comments stored in the last (or second-to-last, perhaps?) token and storing them where you need them to be manually. Does this make sense?

**Comment by yogevyuval** [comment]
> Perhaps you could solve this at the tokenization level, i.e. by extracting the comments stored in the last (or second-to-last, perhaps?) token and storing them where you need them to be manually. Does this make sense?

The issue is how do you determine which is the "last" token?

Now that i'm thinking about it, a "workaround" can be just converting the query to str, appending the comment, and parsing back to a query

**Comment by GeorgeSittas** [comment]
> The issue is how do you determine which is the "last" token?

Isn't the last token simply the last element in the list produced by `tokenize`?
