### ISSUE TITLE
Copy Into is not extracting table names

### ISSUE THREAD

**Issue by RamanKharchee** [tobymao/sqlglot#2463]
I have the following `snowflake` query 

`COPY INTO "SAMPLE_DATABASE"."EMP"."REFERENCE_DATA" FROM '@"SAMPLE_DATABASE"."EMP"."%REFERENCE_DATA"/__snowflake_temp_import_files__/' FILES = ('your_table_name.csv') FILE_FORMAT = ( TYPE=CSV, SKIP_HEADER=1, FIELD_DELIMITER=',', TRIM_SPACE=TRUE, FIELD_OPTIONALLY_ENCLOSED_BY='"', DATE_FORMAT=AUTO, TIME_FORMAT=AUTO, TIMESTAMP_FORMAT=AUTO ) ON_ERROR=ABORT_STATEMENT PURGE=TRUE`

And I want to extract table names from this query. I executed `parse_one(query, read="snowflake").find_all(exp.Table)`. It gives empty value. 

When checked the AST of this query(`repr(parse_one(query, read="snowflake"))`) it is:
```
(COMMAND this: COPY, expression:
  (LITERAL this: INTO "SAMPLE_DATABASE"."EMP"."REFERENCE_DATA" FROM '@"SAMPLE_DATABASE"."EMP"."%REFERENCE_DATA"/__snowflake_temp_import_files__/' FILES = ('your_table_name.csv') FILE_FORMAT = ( TYPE=CSV, SKIP_HEADER=1, FIELD_DELIMITER=',', TRIM_SPACE=TRUE, FIELD_OPTIONALLY_ENCLOSED_BY='"', DATE_FORMAT=AUTO, TIME_FORMAT=AUTO, TIMESTAMP_FORMAT=AUTO ) ON_ERROR=ABORT_STATEMENT PURGE=TRUE, is_string: True))
```

How to get table name from above type of queries?

**Comment by tobymao** [comment]
you'd have to implement copy into parsing, right now it's falling back to a command, since this is not high priority, i'm going to close this as not planned, but happy to accept a high quality PR
