### ISSUE TITLE
Parsing of HiveConf variables do not succeed

### ISSUE THREAD

**Issue by travis-cook-sfdc** [tobymao/sqlglot#2464]
**Is your feature request related to a problem? Please describe.**

Hive & Spark SQL parsing does not seem to support hive's variable syntax.

https://sparkbyexamples.com/apache-hive/how-to-set-variables-in-hive-scripts/

**Describe the solution you'd like**

Ideally, `parse` would be able to recognize the variables that were set and interpolate them into the SQL and parse them correctly.

Here's a script that is currently failing and should succeed:
```
from sqlglot import parse, Dialects
sql = """
set src_table=stage.foo;
set src_path=s3://var/stage/foo;

set dst_table=dw.foo;
set dst_path=s3://var/dw/foo;

create external table ${hiveconf:src_table}
(
	id                  	bigint
)
partitioned by
(
    ds STRING
)
stored as parquet
location '${hiveconf:src_path}';
"""

parsed_sql = parse(sql, read=Dialects.SPARK)
print(repr(parsed_sql))

parsed_sql = parse(sql, read=Dialects.HIVE)
print(repr(parsed_sql))
```

**Describe alternatives you've considered**

Two alternatives are:
1. Interpolate these variables prior to sending them to `parse`.  Given that these are valid Hive / Spark SQL commands, it feels like sqlglot should be able to handle them.
2. Not use these set statements.  Honestly, this would be better, but they are littered all over the codebase, so removing them is a somewhat significant project.

**Additional context**

This seems related to [this PR](https://github.com/tobymao/sqlglot/pull/1292), in that the `set` commands are now getting parsed correctly.  Unfortunately, the usage of the variables still does not seem to be.

**Comment by GeorgeSittas** [comment]
Taking a look, thanks for the report.

**Comment by travis-cook-sfdc** [comment]
Looks like the PR referenced will fix the issue for Hive.

However, this syntax is also supported for SparkSQL.

See the 3rd example on this page: https://spark.apache.org/docs/latest/sql-distributed-sql-engine-spark-sql-cli.html#examples

**Comment by GeorgeSittas** [comment]
Hive is a superclass the Spark dialect and so it should inherit the fix.
