### ISSUE TITLE
sqlglot as a vscode extension?

### ISSUE THREAD

**Issue by vishalsurana** [tobymao/sqlglot#2471]
**Is your feature request related to a problem? Please describe.**
All of the functionality wrapped as a vscode extension

**Describe the solution you'd like**
Developers rely on IDE for formatting, quick fixes, refactoring. This tool does the same and more. Thus it would help to have it integrated with an IDE such as VSCode. 

**Describe alternatives you've considered**
Use this tool as is

**Comment by GeorgeSittas** [comment]
Hello, thanks for the suggestion but this is currently out of scope for us. I have a feeling that people have either discussed about this or even implemented similar plugins in the past, but can't find the relevant threads now.

Feel free to join our [slack](https://tobikodata.com/slack) community if you want to chat about this or other topics.

**Comment by Minyus** [comment]
@vishalsurana @georgesittas [shameless promotion] I published a vscode extension for diagnosis of SQL by [sqlglot's parser errors](https://github.com/tobymao/sqlglot?tab=readme-ov-file#parser-errors).

https://marketplace.visualstudio.com/items?itemName=Minyus.anysqldiag
