### ISSUE TITLE
teradata `eq` and `minus` support

### ISSUE THREAD

**Issue by hsheth2** [tobymao/sqlglot#2474]
**Fully reproducible code snippet**

This query should parse properly.
```sql
select col1, col2 from dbc.table1
where col1 eq 'value1'
minus
select col1, col2 from dbc.table2
```

There's some other ones beyond `EQ` like `NOT=` - I think most of these are covered though

For eq and minus, the fix is likely just this 

```diff
diff --git a/sqlglot/dialects/teradata.py b/sqlglot/dialects/teradata.py
index 152afa6a..1becfc0b 100644
--- a/sqlglot/dialects/teradata.py
+++ b/sqlglot/dialects/teradata.py
@@ -38,12 +38,14 @@ class Teradata(Dialect):
             "^=": TokenType.NEQ,
             "BYTEINT": TokenType.SMALLINT,
             "COLLECT": TokenType.COMMAND,
+            "EQ": TokenType.EQ,
             "GE": TokenType.GTE,
             "GT": TokenType.GT,
             "HELP": TokenType.COMMAND,
             "INS": TokenType.INSERT,
             "LE": TokenType.LTE,
             "LT": TokenType.LT,
+            "MINUS": TokenType.EXCEPT,
             "MOD": TokenType.MOD,
             "NE": TokenType.NEQ,
             "NOT=": TokenType.NEQ,
```

**Official Documentation**

- https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Manipulation-Language/Set-Operators/MINUS/EXCEPT-Operator
- https://docs.teradata.com/r/SQL-Functions-Operators-Expressions-and-Predicates/June-2017/Comparison-Operators-and-Functions/Comparison-Operators/ANSI-Compliance

**Comment by tobymao** [comment]
can you make a PR?

**Comment by tobymao** [comment]
ah george too fast

**Comment by hsheth2** [comment]
Thanks! I would've made a PR, but wasn't fully sure where/how to write corresponding tests.

**Comment by tobymao** [comment]
like this https://github.com/tobymao/sqlglot/commit/a1252d8ba7d2394bbb14ccd42d835da8cd4eb740#diff-13b16abb7ff3dafb23d1cfba6ff4a8d921c5512cecf44b51b2d4a115d44f61ccR151
