### ISSUE TITLE
[TSQL] DATENAME is replaced incorrectly

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#2481]
# Issue Description

sqlglot==13.3.0

**Code**
```python
query = "Select DATENAME(dw, some_date) FROM my_table"
query = parse_one(query, dialect='tsql')
print(query)
```

**Output**
```sql
Select FORMAT(some_date, '%A') AS day FROM my_table
```

**Expected Output**
```
Select FORMAT(some_date, 'dddd') AS day FROM my_table
```

## Analysis

> format
nvarchar format pattern.
The format argument must contain a valid .NET Framework format string, either as a standard format string (for example, "C" or "D"), or as a pattern of custom characters for dates and numeric values (for example, "MMMM DD, yyyy (dddd)"). Composite formatting is not supported. For a full explanation of these formatting patterns, consult the .NET Framework documentation on string formatting in general, custom date and time formats, and custom number formats. A good starting point is the topic, "[Formatting Types](https://learn.microsoft.com/en-us/dotnet/standard/base-types/formatting-types)."

The correct format should be `dddd`. See [here](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#ddddSpecifier) for more info.

## Additional Question
Could you please provide the rationale behind replacing DATENAME with FORMAT? Also, in general why are some functions replaced but not others?

**Comment by GeorgeSittas** [comment]
> Could you please provide the rationale behind replacing DATENAME with FORMAT? Also, in general why are some functions replaced but not others?

The answer to both questions is that this happens in order to facilitate transpilation towards other dialects. The SQL code is converted into a canonical form which is easier to transpile, and at the same time we try to preserve the semantics in the source dialect.
