### ISSUE TITLE
teradata `AS FORMAT` support

### ISSUE THREAD

**Issue by asikowitz** [tobymao/sqlglot#2485]
**Fully reproducible code snippet**
This query should parse properly.
```
select CAST(TimestampCol AS FORMAT 'YYYY-MM-DD') FROM dbc.table
```
There's a lot of other potential formats, e.g. '$$9.99'	or 'E4'.

**Official Documentation**
- https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Types-and-Literals/Data-Type-Formats-and-Format-Phrases/FORMAT-Phrase-and-DateTime-Formats
- https://docs.teradata.com/r/Teradata-Warehouse-Miner-User-Guide-Volume-2ADS-Generation/February-2018/Analytic-Data-Sets/Variable-Creation/Initiating-a-Variable-Creation-Function/Variable-Creation-INPUT-Variables-SQL-Elements/Other/Cast-Function
- https://docs.teradata.com/r/SQL-Functions-Operators-Expressions-and-Predicates/June-2017/Data-Type-Conversions/Period-to-DATE-Conversion/CAST-Syntax

**Comment by tobymao** [comment]
@asikowitz i don't see any documentation related to cast(x as format ...) what does it even mean? is format a type?

sqlglot supports cast(x as date format '...')

**Comment by asikowitz** [comment]
It seems teradata allows you to omit the type. I can't find comprehensive docs on the syntax, but here's an example from the official docs:
https://docs.teradata.com/r/SQL-Functions-Operators-Expressions-and-Predicates/June-2017/Data-Type-Conversions/DATE-to-Character-Conversion/Examples/Example-Creating-a-Script-to-Convert-Date-Values

**Comment by tobymao** [comment]
is the default type always varchar? if you just do format ...?

**Comment by asikowitz** [comment]
Alright, so I think officially this syntax is a "Teradata SQL data definition phrase" (see [here](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Types-and-Literals/SQL-Data-Definition/Data-Definition-Phrases/Data-Type-Phrases) which notes you can use data definition phrases for casts in expressions). Under that is the [core data type attributes](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Types-and-Literals/SQL-Data-Definition/Data-Definition-Phrases/Core-Data-Type-Attributes) which notes certain non-ANSI attributes like FORMAT.

As for what the types is, it seems the type is retained (despite the cast statement...) as the cast is really changing the FORMAT attribute not the type.
