### ISSUE TITLE
INTERVAL Issue from redshift to trino

### ISSUE THREAD

**Issue by as-sher** [tobymao/sqlglot#2497]
This code
```
import sqlglot

queryTxt = '''select now() + INTERVAL '5:30' '''
print(sqlglot.transpile(queryTxt, read="redshift", write="trino")[0])
```
returns
`SELECT CURRENT_TIMESTAMP + INTERVAL '5:30'
`

which is not trino compatible. Please help

**Comment by tobymao** [comment]
trino doesn't support interval 'h:mm', i'd suggest rewriting your redshift so it's more easily transpilable

https://trino.io/docs/current/functions/datetime.html
