### ISSUE TITLE
TSQL table with format database_name.schema_name.table_name representation issue

### ISSUE THREAD

**Issue by robertkosz** [tobymao/sqlglot#2512]
sqlglot version: 18.16.1

I am not sure if this is a bug or a terminology issue. TSQL tables can be referenced in database_name.schema_name.table_name format:
[documentation](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16)

But it seems schema and database exchanged in the parsed tree:
```
from sqlglot import parse_one, exp,Dialects

ins = """
select a,b,c + d as k
into sch2.tmp
from 
dbn.schn.tablen
"""

nodes = parse_one(ins,dialect=Dialects.TSQL)
print(repr(nodes))

for table in nodes.find_all(exp.Table):
    print("table name: ",table.name," database name: ",table.db," catalog name: ",table.catalog," sql repr: " ,table.parts)
```

Or what TSQL calls database is called catalog in sqlglot and what TSQL calls schema is db in sqlglot?

**Comment by tobymao** [comment]
this is just naming, 

sqlglot calls it catalog.db.name
