### ISSUE TITLE
[Bug] Transpiling built-in functions is not accurate.

### ISSUE THREAD

**Issue by CBQu** [tobymao/sqlglot#2517]
**Before you file an issue**
- updated to 19.0.3

**Fully reproducible code snippet**
I am transpiling Oracle SQL to Postgres. There are multiple functions that fail when executed.
Here is an example.
`sql_in_oracle = "to_char(123)"`
`sqlglot.transpile(sql_in_oracle, read='oracle', write='postgres')`

Output: `['to_char(123)']`
Expected: `['123::text']` or whatever is valid in Postgres
Postgres supports `to_char(expr, format)`, but not `to_char(expr)`.

I have many functions that cannot be tranpiled correctly in my query list, such as,

Truncate datetime to day:
TRUNC(datetime) -- Valid Oracle
Output: TRUNC(datetime) -- Invalid Postgres
Expected: DATE_TRUNC('day', datetime) -- Valid postgres

**Official Documentation**
[sqlines](https://sqlines.com/oracle-to-postgresql) has an online tool I tried once. On its website, it lists many migration conversions for different databases. It might be a helpful resource for you to check out. Thanks.

**Comment by tobymao** [comment]
@CBQu please list the correct transpilations and supporting documentation

**Comment by GeorgeSittas** [comment]
@CBQu I've pushed a fix for the `TO_CHAR` issue, the `TRUNC` one is a bit more tricky because Oracle's semantics are somewhat different from the rest of the dialects and I think it'll require more work to transpile since we need to map the various formats to units used by other dialects. We'll accept a high-quality PR for if you want to contribute a fix yourself, but for the time it's out of scope.

**Comment by CBQu** [comment]
> @CBQu please list the correct transpilations and supporting documentation

I listed 2 examples. The **expected** outputs are the correct ones. The further documentation is a link to SQLines. It would be nice to elaborate more on what you are expecting. I am willing to add more details.

As you know, database migration is hard and trivial. Although the identical functionality is supported by different databases, the implementation varies. It may not be a one-to-one mapping. So the SQLines is a reference and I find it works for my examples.

**Comment by CBQu** [comment]
> @CBQu I've pushed a fix for the `TO_CHAR` issue, the `TRUNC` one is a bit more tricky because Oracle's semantics are somewhat different from the rest of the dialects and I think it'll require more work to transpile since we need to map the various formats to units used by other dialects. We'll accept a high-quality PR for if you want to contribute a fix yourself, but for the time it's out of scope.

Thanks for fixing it so fast. Currently, I do not have time to make a PR. But I might be able to do it a few months later. IMHO, I think migration is a painful process and a practical use case in real-world applications. For me, it would be really nice to fully support it, since I use sqlglot's parser a lot and it is amazingly good.

**Comment by tobymao** [comment]
relevant links to official documentation (oracle/postgres), and input output as well as various edge cases. the more detail, the more it saves us time with having to research. in this example trunc -> date_trunc could have had more details and investigation.

we try to be robust and thus want to understand the semantics and behavior of each dialect, it helps us a lot if you do that work up front.

**Comment by CBQu** [comment]
> relevant links to official documentation (oracle/postgres), and input output as well as various edge cases. the more detail, the more it saves us time with having to research. in this example trunc -> date_trunc could have had more details and investigation.
> 
> we try to be robust and thus want to understand the semantics and behavior of each dialect, it helps us a lot if you do that work up front.

Thanks for clarifying this to me! Since you have done the research job for these 2 functions, I will list more detailed documentation if I report an issue next time. :)

**Comment by GeorgeSittas** [comment]
> > relevant links to official documentation (oracle/postgres), and input output as well as various edge cases. the more detail, the more it saves us time with having to research. in this example trunc -> date_trunc could have had more details and investigation.
> > we try to be robust and thus want to understand the semantics and behavior of each dialect, it helps us a lot if you do that work up front.
> 
> Thanks for clarifying this to me! Since you have done the research job for these 2 functions, I will list more detailed documentation if I report an issue next time. :)

Thank you! Appreciate you reporting these issues.

Feel free to also join our [Slack](https://tobikodata.com/slack) to sync about future contributions or just chat in general.
