### ISSUE TITLE
Question. do we have alternate syntex when setting alias with alias_ method?

### ISSUE THREAD

**Issue by JDRanpariya** [tobymao/sqlglot#253]
By using alias_ method we get the following result for the query `select foo from bar`
output -> `select foo AS alias from bar`

How do I get `select foo alias from bar`?
I looked through Docstring but didn't find any argument that can be passed to change the syntax. Does it have to do anything with Alias class?

**Comment by tobymao** [comment]
that is not possible with the default generator, aliases always have AS, if you want to do this, you need a customer dialect with a custom generator where you override the alias_sql method
