### ISSUE TITLE
Incorrect presto to spark sql translation for map_from_entries function

### ISSUE THREAD

**Issue by cploonker** [tobymao/sqlglot#2536]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
Steps to reproduce
working presto-sql
```
select json_format(cast(map_from_entries(ARRAY[('action_type','at'), ('action_payload', 'ap'), ('action_result', 'ar')]) as json))
```
Translated to spark-sql which fails to execute
```
SELECT
  TO_JSON(
    TO_JSON(
      MAP_FROM_ENTRIES(ARRAY(('action_type', 'at'), ('action_payload', 'ap'), ('action_result', 'ar')))
    )
  )
```
**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
@cploonker in the future can you please link relevant documentation and also provide guidance on what the proper transpilation is? it will save us time
