### ISSUE TITLE
clickhouse: "cannot traverse scope" for "scalar with" expressions

### ISSUE THREAD

**Issue by pkit** [tobymao/sqlglot#2555]
```python
import sqlglot
from sqlglot import exp
from sqlglot.optimizer import traverse_scope

sql = """
with
  (select data from t5) as p1,
  t3 as (select * from t4)
select * from t1 join t3 on t1.id = t3.id where c = p1
"""
expr = sqlglot.parse_one(sql, read="clickhouse")

for s in traverse_scope(expr):
    for k, v in s.sources.items():
        if isinstance(v, exp.Table):
            print(k, repr(v))
```
Result:
```
Cannot traverse scope (SELECT data FROM t5) AS p1 with type '<class 'sqlglot.expressions.Alias'>'
t4 (TABLE this: 
  (IDENTIFIER this: t4, quoted: False))
t1 (TABLE this: 
  (IDENTIFIER this: t1, quoted: False))
```
I.e. the scope of `t5` is undetected.
Docs: https://clickhouse.com/docs/en/sql-reference/statements/select/with

**Comment by pkit** [comment]
@tobymao I'm not sure that `with a as (...)` == `with (...) as a`
As the first one is a CTE which you can `select ... from` and the second one is just an alias for an expression. That you can use only as subquery at best.

**Comment by tobymao** [comment]
then is your example legal? because you're not using an aggregation

**Comment by pkit** [comment]
for example: `with toDate('2023-01-01') as dt select * from t1 where ts > dt`
you cannot do: `with dt as toDate('2023-01-01')`

**Comment by pkit** [comment]
> then is your example legal? because you're not using an aggregation
it is, only if it produces just one row in the `(select data from t5) as p1`

**Comment by tobymao** [comment]
ok, i tested it, your example was a bit misleading, so it must be a scalar value

**Comment by pkit** [comment]
I should have probably created something like:
```sql
with
  (select data from t5) as p1,
  t3 as (select * from t4)
select * from t1 join t3 on t1.id = t3.id where c in p1
```
to make it more clear how it is usually used

**Comment by pkit** [comment]
Sorry, for a bad repro :(

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/8cfb39eeccfec3a246d1e28c1922d7f605ec53f5

**Comment by tobymao** [comment]
no worries @pkit

**Comment by pkit** [comment]
https://github.com/tobymao/sqlglot/commit/8cfb39eeccfec3a246d1e28c1922d7f605ec53f5

Looks nice, `scalar` flag will also help constructing these!
