### ISSUE TITLE
Looking for guidance on the best way to get the last `SELECT` statement from an input sql

### ISSUE THREAD

**Issue by sarahspak** [tobymao/sqlglot#2563]
Really appreciate the hard work that's been put into this project. 

I've been building a script to programmatically find the last SELECT statement in a given `.sql` input, but am having some trouble getting the "last" select statement.

Here's an example:
```
with daily_tbl as (SELECT a, b, c, d FROM schema_a.table_a),
weekly_tbl as (SELECT d, e, f, g, h FROM schema_b.table_b),
monthly_tbl as (SELECT a, e, i, j, k, l FROM schema_b.table_c)
SELECT a, b, c, e, k
FROM daily_tbl dt
LEFT JOIN weekly_tbl wt
ON dt.d = wt.d
LEFT JOIN monthly_tbl mt
ON dt.a = mt.a;
```

I'd like to just extract:
```
SELECT a, b, c, e, k
FROM daily_tbl dt
LEFT JOIN weekly_tbl wt
ON dt.d = wt.d
LEFT JOIN monthly_tbl mt
ON dt.a = mt.a;
```

`parse_one()` returns a syntax tree with everything under a single select statement. Is there a method to get the final select statement?

**Comment by tobymao** [comment]
the whole sql query is one statement, you can pop off the cte by doing 

query = parse_one(...)

query.pop("with")
