### ISSUE TITLE
sqlglot does not roundtrip assignment operator `:=`

### ISSUE THREAD

**Issue by j-bennet** [tobymao/sqlglot#2575]
There is no way to roundrip `:=` through sqlglot. It's converted into `EQ`, vs `PropertyEQ`.

**Fully reproducible code snippet**

> Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

```python
In [28]: sqlglot.parse_one('SELECT @x := 1', read='mysql')
Out[28]:
(SELECT expressions:
  (EQ this:
    (PARAMETER this:
      (VAR this: x)), expression:
    (LITERAL this: 1, is_string: False)))

In [29]: sqlglot.parse_one('SELECT @x := 1', read='mysql').sql()
Out[29]: 'SELECT @x = 1'
```

Expected output: `SELECT @x := 1`.

**Official Documentation**

> Please include links to official SQL documentation related to your issue.

I couldn't find anything meaningful about `PropertyEQ`.

**Comment by georgesittas** [comment]
Is the `@x = 1` syntax invalid in this case? What does `@x := 1` mean?

**Comment by tobymao** [comment]
https://dev.mysql.com/doc/refman/8.0/en/assignment-operators.html

:= is never equality, only setting

**Comment by georgesittas** [comment]
I see, so @tobymao should we just generate `:=` for `PropertyEQ` for every dialect instead of just DuckDB?

**Comment by tobymao** [comment]
ok

**Comment by j-bennet** [comment]
That was the quickest fix I've seen I'm my life. :) Thanks!
