### ISSUE TITLE
MySQL roundtrip issues

### ISSUE THREAD

**Issue by j-bennet** [tobymao/sqlglot#2577]
I'm seeng roundtrip problems for some queries in MySQL, they don't come back as expected.

> - Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")

Yes.

> - Check if the issue still exists on main 

Yes.

**Fully reproducible code snippet**

> Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

```
In [6]: sqlglot.parse_one('IFNULL(1, 5, 10)', read='mysql').sql()
Out[6]: 'COALESCE(1, 5, 10)'

In [7]: sqlglot.parse_one('IF(x = 1, 5, 10)', read='mysql').sql()
Out[7]: 'CASE WHEN x = 1 THEN 5 ELSE 10 END'
```

**Official Documentation**

> Please include links to official SQL documentation related to your issue.

**Comment by georgesittas** [comment]
@j-bennet it seems like `IFNULL` doesn't have the correct number of arguments. Also, I'm not sure if that's your intent, but if you want to generate SQL towards MySQL you need to call `sql` as `sql(dialect="mysql")`.

Now, regarding:

> I'm seeng roundtrip problems for some queries in MySQL, they don't come back as expected.

SQLGlot doesn't guarantee that the output matches the input when reading/generating from/to a given dialect. The contract is that the output must preserve the semantics, i.e. not break the input query when generating it back.

In the above examples, I think the output you're seeing is reasonable. Did you encounter any issues?

**Comment by georgesittas** [comment]
I'll go ahead and close this one, I double-checked and both transformations (`IFNULL` -> `COALESCE` and `IF` -> `CASE`) seem good. Happy to continue chatting, though.

**Comment by j-bennet** [comment]
@georgesittas Do I still have to specify `.sql(dialect="mysql")`, even though I already parsed it with `read="mysql"`?

**Comment by georgesittas** [comment]
That is correct, the dialect is not preserved in the AST you get back from parsing so in order to generate SQL from the AST you should also specify the "output" dialect.
