### ISSUE TITLE
sqlite insert returning

### ISSUE THREAD

**Issue by shomodj** [tobymao/sqlglot#2579]
Hi,

I was trying to build sql for sqlite that will insert with `returning`, I might be wrong, but what I see from the code is that only Delete class has a returning method.

Is it possible to add returning to Insert class or I'm off on this?

Thanks,

BTW amazing project, I don't use sqlglot for parsing, I use it for building sql in similar way like pypika

**Comment by tobymao** [comment]
can you please add more detail to this request? what is the input sql that you're trying to parse or generate?

**Comment by shomodj** [comment]
@tobymao ah sorry, here is partial snippet but I think you will understand, I'm trying to build a generic function that will receive a dataclass slots object and insert it into database

```
        columns: list[str] = []
        values: list[str] = []

        for key in obj.__slots__:
            columns.append(key)

            val = getattr(obj, key)
            values.append(val)

        exp_vals = [tuple(values)]
        sql = exp.insert(exp.values(exp_vals), table_name, columns).sql(self._dialect)
        sql = f"{sql} RETURNING *"
        logger.debug(sql)
```
so `exp.insert` does not have `returning` method but `exp.delete` does.

**Comment by tobymao** [comment]
@shomodj this is now added, would appreciate future prs for additions like this in the future, happy to guide you along the way. you can reach us in our [slack channel](tobikodata.com/slack) for quick iteration.

**Comment by shomodj** [comment]
@tobymao Thanks, will do next time.
