### ISSUE TITLE
Query parsing stuck when query is ended with " \r"

### ISSUE THREAD

**Issue by saitejamanchi-db** [tobymao/sqlglot#2585]
Hi Team,

We are trying to parse an SQL query but it seems to run forever when the query has a " \r" at the end.

Following is the snippet that kept on running for more than an hour:

```
import sqlglot
sqlglot.parse_one("""SELECT * FROM DB.TABLE order \r""")
```

I tried removing the \r at the end and it ran with a fraction of a second.

```
import sqlglot
sqlglot.parse_one("""SELECT * FROM DB.TABLE order """)
```

This is happening only with the queries that have a " \r" at the end.

**Comment by saitejamanchi-db** [comment]
Hi @tobymao 
Could you please let me know in which release would the fix be rolled out?
Thanks for your immediate response!

**Comment by tobymao** [comment]
i’m the next release, we release often but without a set schedule
