### ISSUE TITLE
Splitting multi-statement SQL inputs safely

### ISSUE THREAD

**Issue by purcell** [tobymao/sqlglot#2587]
**Is your feature request related to a problem? Please describe.**

A hard problem in general is to accurately split up a large text containing multiple SQL statements into individual statements. I need to do this reliably across multiple SQL dialects.

sqlglot has an _amazingly good parser_ so it can reliably do this for a wide range of dialects, and I have been using it for this purpose — I'm very grateful!

However, the result from sqlglot is a list of statements in an AST. Those can be converted back to statements, but they do not necessarily correspond exactly to the original query: the intent is that they are semantically identical, but this isn't always guaranteed, and I'm using this in a context where it's _weird_ for users to see errors from executing a modified version of their SQL.

**Describe the solution you'd like**

I'd love to be able to get the original text ranges for parsed statements, or to otherwise obtain the source text for each statement. Some ideas:

* Perhaps the AST could be enriched with the source locations for the parsed elements? Even if this were just the start/end of top-level statements, it would do the job.
* Or perhaps the AST nodes could retain the original text for their subtree, and use that instead of any rewritten version when round-tripping nodes back to the source dialect?

Or maybe there's a way to achieve this already? I just failed to find anything in the docs or source code.

**Describe alternatives you've considered**

* For some DBs there are parser-based tools which can help (e.g. libpgquery for postgresql-compatible dialects), but sqlglot is the only parser which supports many dialects
* Splitting SQL text from various databases using regexes is error-prone because string/comment/escape syntax and other subtleties are easy to mess up.

Would love to have any suggestions!

**Comment by georgesittas** [comment]
Perhaps you can already achieve this by tokenizing your SQL and then splitting the tokens into chunks using the `SEMICOLON` token as a delimiter. That's how the parser splits the statements too.

I don't think this is high priority for us right now if the above solution doesn't work well for you, but feel free to join our [Slack](https://tobikodata.com/slack) if you wanna discuss about your use cases and possible solutions / contributions.

**Comment by purcell** [comment]
Ah, great idea — I'll give that a go and report back. Thanks!

**Comment by tobymao** [comment]
it's not in sqlglot's scope to preserve the input sql, only to generate valid semantically identical sql. 

as jo says, you can tokenize the raw sql and just do things at the tokenizer level.

**Comment by purcell** [comment]
That's cool, and thanks for the helpful pointers. 💪
