### ISSUE TITLE
Snowflake syntax for dollar-quoted-string is transformed incorrectly 

### ISSUE THREAD

**Issue by shaiv-syg** [tobymao/sqlglot#2603]
Snowflake allows to avoid escaping secial regex patterns using dollar quoted strings (useful when searching for escaped literals):
https://docs.snowflake.com/en/sql-reference/data-types-text#label-dollar-quoted-string-constants

When used with sqlglot it ignores the dollars quotes and changes the string to normal sql string literal.

For example (sqlglot version 19.6)

```
from sqlglot import parse_one

query = """
SELECT *
FROM X
WHERE REGEXP_LIKE(val, $$pattern$$, 'i')
"""

parse_one(query, read='snowflake').sql(dialect='snowflake')

>> "SELECT * FROM X WHERE REGEXP_LIKE(val, 'pattern', 'i')" 
```

The pattern inside the regex should contain the dollar quotes `$$` and not the regular string quotes `'`

**Comment by georgesittas** [comment]
@shaiv-syg can you share an example where the semantics of the resulting query are different than that of the source one?

**Comment by shaiv-syg** [comment]
Hi @georgesittas sorry I missed it, my bad.
Thanks for the clarification 🙏
