### ISSUE TITLE
DuckDB bracket operator is 1-indexed

### ISSUE THREAD

**Issue by j1ah0ng** [tobymao/sqlglot#2617]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark") Bigquery, for example
- Check if the issue still exists on main yes

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

DuckDB arrays are 1-indexed. When providing a literal to the subscript/bracket operator the expected output for a transpilation of
```sql
SELECT some_arr[0] AS first FROM blah
```
should render to
```sql
SELECT some_arr[1] AS first FROM blah
```
in DuckDB. However, this is not the case:
```python
>>> transpile("SELECT some_arr[0] AS first FROM blah", read="bigquery", write="duckdb")
['SELECT some_arr[0] AS first FROM blah']
```

I attempted to patch this by incrementing in the case that `exp.Bracket.expressions` is of length 1 and type `Literal`, but this does not seem to be directionally correct (do you still increment in the case where the subscript is a column?). I think there are some semantics concerns here which I'm not well-versed enough to address.

**Official Documentation**
Please include links to official SQL documentation related to your issue.

[DuckDB array documentation](https://duckdb.org/docs/sql/data_types/array.html)

**Comment by j1ah0ng** [comment]
Specifically in the case of [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/operators) (unsure if this is true for other dialects) the user has to specify whether the bracketed expression is an `ORDINAL` (1-indexed), an `OFFSET` (0-indexed), a `SAFE_OFFSET` (0-indexed returns null if OOB), or a `SAFE_ORDINAL` (you get the idea). This also does not seem to be supported today:

```python
>>> transpile("SELECT some_numbers[ORDINAL(1)] AS ordinal_1", read='bigquery', write='duckdb')
['SELECT some_numbers[ORDINAL(1)] AS ordinal_1']
>>> transpile("SELECT some_numbers[SAFE_ORDINAL(1)] AS ordinal_1", read='bigquery', write='duckdb')
['SELECT some_numbers[SAFE_ORDINAL(1)] AS ordinal_1']
```

**Comment by georgesittas** [comment]
Interesting, I'd expect this issue to have surfaced earlier but it seems like you're right:

```
D select ([1,2,3])[0];
┌─────────────────────────────┐
│ main.list_value(1, 2, 3)[0] │
│            int32            │
├─────────────────────────────┤
│                             │
└─────────────────────────────┘
D select ([1,2,3])[1];
┌─────────────────────────────┐
│ main.list_value(1, 2, 3)[1] │
│            int32            │
├─────────────────────────────┤
│                           1 │
└─────────────────────────────┘
```

**Comment by georgesittas** [comment]
I'll take a look @j1ah0ng, thanks for the report!
