### ISSUE TITLE
BigQuery log argument order is incorrect

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2621]
**Fully reproducible code snippet**

```
In [8]: import sqlglot as sg

In [9]: sg.__version__
Out[9]: '19.7.1.dev13'

In [10]: print(sg.func("log", sg.to_identifier('x'), 2).sql(dialect="bigquery"))
LOG(2, x)
```

**Official Documentation**

https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#log

**Comment by georgesittas** [comment]
Just FYI @cpcloud I'm actively working on this but we've chatted internally and realized the fix will be more robust once I get https://github.com/tobymao/sqlglot/pull/2627 in.

**Comment by cpcloud** [comment]
No rush, I am able to workaround this pretty easily.
