### ISSUE TITLE
BigQuery `OFFSET`, `ORDINAL` subscript operators are parsed as anonymous functions

### ISSUE THREAD

**Issue by j1ah0ng** [tobymao/sqlglot#2624]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark") **BigQuery**
- Check if the issue still exists on main **Yes**

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

In BigQuery, bracket notation is supplemented with `OFFSET` and `ORDINAL` functions, where `array[OFFSET(0)]` is equivalent to `array[ORDINAL(1)]` i.e. OFFSET corresponds to a zero-indexed operator and ORDINAL corresponds to a one-indexed operator. However, parsing such a query:
```python
>>> parse_one("SELECT foo[OFFSET(1)] FROM z", read="bigquery")
(SELECT expressions: 
  (BRACKET this: 
    (COLUMN this: 
      (IDENTIFIER this: foo, quoted: False)), expressions: 
    (ANONYMOUS this: OFFSET, expressions: 
      (LITERAL this: 1, is_string: False))), from: 
  (FROM this: 
    (TABLE this: 
      (IDENTIFIER this: z, quoted: False))))
```
yields that `OFFSET` is parsed as an anonymous function. Note that neither ORDINAL nor OFFSET are normal functions (they only work within the context of a BRACKET expression) as shown by the errors thrown by the queries `select offset(0) from x` or `select ordinal(1) from x` respectively:
<img width="778" alt="image" src="https://github.com/tobymao/sqlglot/assets/13944989/afcb0345-20f3-4638-b030-72128271849d">
<img width="765" alt="image" src="https://github.com/tobymao/sqlglot/assets/13944989/8c572e6d-ffcd-480f-bde4-21b59a985855">
I tried to extend `dialects.Bigquery.Tokenizer.FUNCTIONS` but this requires adding special cases to each dialect's `Generator` subclass based on their `index_offset`, which seems incorrect.

**Official Documentation**
Please include links to official SQL documentation related to your issue.

[BigQuery array function documentation](https://cloud.google.com/bigquery/docs/arrays)

**Comment by tobymao** [comment]
@j1ah0ng what exactly is the bug? this is expected behavior, any function that is not implemented falls back to anonymous. i'm not seeing an action item here.

**Comment by j1ah0ng** [comment]
Whoops, forgot to add that - I expect that the transpilation fixes the offset depending on the target language: e.g.
```
In [6]: transpile("SELECT x[ORDINAL(1)] AS z from y", read="bigquery", write="duckdb")
Out[6]: ['SELECT x[ORDINAL(1)] AS z FROM y']
# should be SELECT x[1] AS z FROM y because duckdb is 1-indexed

In [7]: transpile("SELECT x[OFFSET(0)] AS z from y", read="bigquery", write="duckdb")
Out[7]: ['SELECT x[OFFSET(1)] AS z FROM y']
# should be SELECT x[1] AS z FROM y because duckdb is 1-indexed
```
As you said I'm not sure how in-scope this is for the transpiler itself, or if there's any suggested workaround

**Comment by j1ah0ng** [comment]
What I'm currently trying to do is
- add an optional arg `index_offset` to `exp.Bracket`,
- parse:
  -  `[OFFSET( ... )]` into `exp.Bracket` with index_offset = 0, 
  - `[SAFE_OFFSET( ... )]` into `exp.SafeBracket` with index_offset = 0, 
  - `[SAFE_ORDINAL( ... )]` into `exp.SafeBracket` with index_offset = 1, and 
  - `[ORDINAL( ... )]` into `exp.Bracket` with index_offset = 1
- modify the `Generator` to apply both the target dialect's index offset as well as the bracket expression's index_offset
