### ISSUE TITLE
interval column name not parsed correctly

### ISSUE THREAD

**Issue by xiasongh** [tobymao/sqlglot#2625]
This code throws a parsing error even though it runs fine on ClickHouse. The issue seems to be the `ORDER BY interval`. If I change `interval` to something else, like `int`, it will work.

```
import sqlglot

query = '''
SELECT
    interval,
    user_id,
    SUM(value) OVER (PARTITION BY user_id ORDER BY interval RANGE BETWEEN 604800 PRECEDING AND CURRENT ROW) AS timeseries
FROM (
    SELECT toStartOfInterval(transaction_time, INTERVAL 1 DAY) AS interval,
        user_id,
        COUNT(amount) AS value
    FROM
        transactions
    WHERE
        transaction_time >= toStartOfInterval(now(), INTERVAL 1 DAY) - INTERVAL 7 DAY
    GROUP BY
        interval,
        user_id
)
'''

print(sqlglot.transpile(query, read='clickhouse', write='clickhouse', pretty=True)[0])
```

**Comment by tobymao** [comment]
it's difficult to do this because interval range is ambiguous -- interval is a special keyword in clickhouse, and you can do interval x to specify days. closing this as unplanned, so for now just change your query to quote "interval"
