### ISSUE TITLE
sql generation is broken

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2631]
**Fully reproducible code snippet**

```
In [4]: import sqlglot as sg

In [5]: sg.func("concat", sg.exp.convert("a")).sql("duckdb")
...
TypeError: 'Literal' object is not iterable
```

Bisecting `main` against 019e0e5ba4b5df1ef3b34510c2fa07f8623af364, which doesn't have this issue it looks like 6e71c348eab63125e412382381acbcbd79efac43 is the first bad commit.

**Comment by cpcloud** [comment]
It looks like `Concat.from_arg_list` is also no longer viable.

**Comment by georgesittas** [comment]
Right, makes sense
