### ISSUE TITLE
Impala dialect support

### ISSUE THREAD

**Issue by ergodiclife** [tobymao/sqlglot#2637]
Hi,

I wondered whether there are any plans to add support for Apache Impala SQL. I explored the Hive option, but there are [key differences](https://docs.cloudera.com/cdw-runtime/cloud/impala-sql-reference/topics/impala-langref-unsupported.html) between Hive and Impala SQL. I would also be happy to give this a go with some guidance...

Thanks

**Comment by tobymao** [comment]
we are not planning to do this, but happy to accept / help you with a PR, join us at [slack](tobikodata.com/slack) if you're seriously considering contributing
