### ISSUE TITLE
TOP N clauses fail to parse

### ISSUE THREAD

**Issue by xeroskiller** [tobymao/sqlglot#2642]
Quick Background:
 - I'm developing a process to review query history and capture SELECT statements within CTEs, count them, and propose materializations as a possible optimization. After parsing a wide range of queries, this appears to be the most common issue.

Read dialect: "snowflake"

**Fully reproducible code snippet**
Input SQL:
 - select top 10 * from tableA

SQLGLOT Action taken:
 - import sqlglot as sg
 - sg.parse_one('select top 10 * from tableA', read="snowflake")

Expected Result:
 - Query parses successfully, and allows me to retrieve the TOP N node from the AST

Actual Result:
 - Parsing generates the following error:
 - sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 12.
  select top [4m10 [0m * from tableA
 in function SQLGLOT_TEST with handler main

Environment:
 - This is running within Snowflake, in a Snowpark context. This is a standard Python 3.11 environment.

**Official Documentation**
 - No relevant documentation

Please do let me know anything I can do to assist. I tried to sus out how I could implement this myself and PR it, but it's fairly complicated (as I'm sure you know) and I couldn't nail it down within an hour or two.

On an unrelated note, your library is awesome, and I love you for it.

**Comment by tobymao** [comment]
cannot reproduce, make sure you're using the latest version of sqlglot

**Comment by tmanningsf** [comment]
Using sqlglot version 11.5.7
Code to reproduce (in snowflake) below:

`create or replace procedure tm_testing.public.sqlglot_test()
    returns variant
    language python
    runtime_version = '3.11'
    packages = ('sqlglot', 'snowflake-snowpark-python')
    handler = 'main'
    execute as caller
as
$$
from snowflake.snowpark import Session
import sqlglot as sg

def main(session: Session):
    q = sg.parse_one('select top 10 * from tableA', read="snowflake")
    return q
$$
;

call sqlglot_test();`

This yields precisely the error documented above.

**Comment by tobymao** [comment]
we’re on version 20.
