### ISSUE TITLE
UNION parsing issue with Postgres dialect

### ISSUE THREAD

**Issue by J000Z** [tobymao/sqlglot#2653]
It may not limited to Postgres dialect. But I will refer to Postgres document on Union https://www.postgresql.org/docs/current/queries-union.html

Expectations:
- respect left-to-right association when parsing multi unions
- `intersect` should have highest association priority
- suffix `limit` by default applies to the union instead of the last select

Examples:
- `select * from A union select * from B union select * from C` should be parsed to 
```
exp.Union
    - left: exp.Union
        - left: select * from A
        - right: select * from B
    - right: select * from C
```

- `select * from A union select * from B intersect select * from C` should be parsed to 
```
exp.Union
    - left: select * from A
    - right: exp.Intersect
        - left: select * from B
        - right: select * from C
```

- `select * from A union select * from B limit 10` should be parsed to
```
exp.Union
    - left: select * from A
    - right: select * from B
    - limit: 10
```

**Comment by georgesittas** [comment]
Fwiw the second example does work as expected:

```python
>>> import sqlglot
>>> sqlglot.parse_one("select 1 union all select 2 intersect select 1")
(UNION this:
  (SELECT expressions:
    (LITERAL this: 1, is_string: False)), distinct: False, by_name: False, expression:
  (INTERSECT this:
    (SELECT expressions:
      (LITERAL this: 2, is_string: False)), distinct: True, by_name: False, expression:
    (SELECT expressions:
      (LITERAL this: 1, is_string: False))))
```

But yeah, if you reverse the order of the operations then the precedence is not captured correctly:

```python
>>> sqlglot.parse_one("select 1 intersect select 2 union all select 1")
(INTERSECT this:
  (SELECT expressions:
    (LITERAL this: 1, is_string: False)), distinct: True, by_name: False, expression:
  (UNION this:
    (SELECT expressions:
      (LITERAL this: 2, is_string: False)), distinct: False, by_name: False, expression:
    (SELECT expressions:
      (LITERAL this: 1, is_string: False))))
```

**Comment by tobymao** [comment]
all have been addressed except for precedence of intersect, which is not consistente across dialects, i'm going to mark that as out of scope for now, you should really use parenthesis to determine precedence.
