### ISSUE TITLE
Optimizer doesn't transform 'NOT BETWEEN' correctly

### ISSUE THREAD

**Issue by HuashiSCNU0303** [tobymao/sqlglot#2682]
I use sqlglot 20.2.0, and I use the following code,

sql = "SELECT * FROM TableA WHERE TableA.sS NOT BETWEEN 4 AND 7"
print(optimize(sqlglot.parse_one(sql, read='spark'), schema={'TableA': {'sS': 'INT'}}).sql())

It outputs "SELECT "tablea"."ss" AS "ss" FROM "tablea" AS "tablea" WHERE NOT "tablea"."ss" <= 7 AND "tablea"."ss" >= 4". There are three issues:
1. The uppercase letters in table and columns names are all converted to lowercase, e.g., 'TableA' -> 'tablea'
2. 'SELECT *' is converted to 'SELECT "tablea"."ss"', that's unnecessary in my case, can I disable it?
3. 'NOT BETWEEN' is not simplified correctly, since "NOT "tablea"."ss" <= 7 AND "tablea"."ss" >= 4" and "NOT BETWEEN 4 AND 7" are not equivalent.

The expected output should be 'SELECT * FROM "TableA" AS "TableA" WHERE "TableA"."sS" > 7 OR "TableA"."sS" < 4'.
Thanks for your great works!

**Comment by tobymao** [comment]
your number 1 and 2 not correct. spark i case insensitive and the point of the optimizer is to qualify columns.

**Comment by HuashiSCNU0303** [comment]
Oh, it seems that I made a mistake. Thanks for your clarification and help!

**Comment by tobymao** [comment]
you can avoid the other stuff by just doing simplify() only
