### ISSUE TITLE
transpile from spark sql to duckdb sql, does not work for spark from_json

### ISSUE THREAD

**Issue by ruiyang2015** [tobymao/sqlglot#2685]
I have following spark sql
```
  SELECT
    *,
    FROM_JSON(
      "unparsed_message",
      'event_time TIMESTAMP, environment STRING, metrics STRING, user STRING,
          data_service STRING, dataflow STRING, component STRING, type STRING, service
          STRING',
      MAP(['timestampFormat'], ['yyyy-MM-dd''T''HH:mm:ss[.SSS][XXX])'])
    ) AS "activity"
  FROM "combined"
```
need to run this in a duckdb, so tried with the sqlglot, but feed this sql to sqlglot
value = sqlglot.transpile(sql_str, read='spark', write='duckdb', identify=True, pretty=True)
it give me back the same string, looking up dockdb manual, the equivillent from_json call in spark seems to be read_json.

**Comment by georgesittas** [comment]
I believe `FROM_JSON` does the same in both [DuckDB](https://duckdb.org/docs/extensions/json.html#transforming-json) and [Spark](https://spark.apache.org/docs/latest/api/sql/index.html#from_json), so that part of the transpilation doesn't look problematic to me. However, the query produced by `transpile` doesn't seem to work as-is in DuckDB:

```python
>>> import sqlglot
>>> print(sqlglot.transpile("""SELECT from_json('{"a":1, "b":0.8}', 'a INT, b DOUBLE')""", "spark", "duckdb")[0])
SELECT FROM_JSON('{"a":1, "b":0.8}', 'a INT, b DOUBLE')
```

Spark:

```
spark-sql (default)> SELECT from_json('{"a":1, "b":0.8}', 'a INT, b DOUBLE');
{"a":1,"b":0.8}
Time taken: 4.194 seconds, Fetched 1 row(s)
```

DuckDB:

```sql
D SELECT FROM_JSON('{"a":1, "b":0.8}', 'a INT, b DOUBLE');
Error: Invalid Input Error: Malformed JSON at byte 0 of input: unexpected character.  Input: a INT, b DOUBLE
```

It seems like the schema also needs to be transpiled for this to work, i.e. this executes fine:

```sql
D SELECT FROM_JSON('{"a":1, "b":0.8}', '{"a": "INT", "b": "DOUBLE"}');
┌──────────────────────────────────────────────────────────────┐
│ from_json('{"a":1, "b":0.8}', '{"a": "INT", "b": "DOUBLE"}') │
│                 struct(a integer, b double)                  │
├──────────────────────────────────────────────────────────────┤
│ {'a': 1, 'b': 0.8}                                           │
└──────────────────────────────────────────────────────────────┘
```

**Comment by georgesittas** [comment]
We don't plan to implement schema parsing to fix this transpilation issue, so I'll go ahead and close the ticket. We'll be happy though to accept a well-crafted PR if you're willing to work this -- feel free to reach out in [Slack](https://tobikodata.com/slack) if you need guidance.
