### ISSUE TITLE
BigQuery UNPIVOT not recognized 

### ISSUE THREAD

**Issue by kwindau** [tobymao/sqlglot#2687]
The issue is that UNPIVOT is not recognized when using sqlglot.parse

**Fully reproducible code snippet**
```
with sample_wide_data AS (
  SELECT 1 AS id, 'apple' AS fave_fruit, 'banana' AS least_fave_fruit
  UNION ALL 
  SELECT 2 AS id, 'watermelon' AS fave_fruit, 'orange' AS least_fave_fruit
) 

SELECT *
FROM sample_wide_data UNPIVOT(fruit for preference_type in (fave_fruit, least_fave_fruit))
```

**Official Documentation**

- https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#unpivot_operator

**Comment by tobymao** [comment]
i don't see an issue. please make sure you're using the sqlglot and in the future it helps us if you create a more detailed bug report with a fully reproduce snippet and stack trace.
