### ISSUE TITLE
Error with GENERATE_DATE_ARRAY + UNNEST

### ISSUE THREAD

**Issue by bobvanratingen** [tobymao/sqlglot#269]
I get the error "Unknown colum" when I use this query with the optimizer.
```
SELECT
  *
FROM
  table_1
CROSS JOIN
UNNEST(GENERATE_DATE_ARRAY(start_time, date_snapshot, INTERVAL 1 MONTH)) AS time_value

```

**Comment by tobymao** [comment]
@barakalon i took a stab at this, but this is really gnarly and i don't know how to do it T_T

```
select aa from x cross join unnest(array(a)) as aa;
```

the issue is that the unnest is sourcing the from (it grabs column a from table x) so need to call add_sources, but it also is it's own scope because it provides aa as a new column

**Comment by barakalon** [comment]
Reading up a little on this...

Looks like the UNNEST operator is optional for cross joins: https://cloud.google.com/bigquery/docs/reference/standard-sql/arrays

Also, seems like these "correlated joins" can have correlated subqueries: https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#correlated_join

Not to mention "as aa" defines a column, not a source, which is a new thing.

Gnarly indeed.

I can take a look at this, but it might take a few days for me to get to it, if that's OK.

**Comment by tobymao** [comment]
yup, no rush

**Comment by bobvanratingen** [comment]
Some related variants

```
SELECT
  id,
  type,
  unnest_value AS array_ids
FROM
  table_1
  LEFT JOIN
UNNEST
  (array_ids) AS unnest_value
```

```
SELECT
  COUNT(DISTINCT items.id) AS items,
FROM
  table_1,
UNNEST
  (items) AS items
```
