### ISSUE TITLE
Snowflake to_array implemented incorrectly 

### ISSUE THREAD

**Issue by wezham** [tobymao/sqlglot#2695]
The docs for snowflake implementation of [to_array](https://docs.snowflake.com/en/sql-reference/functions/to_array) state 

> If the input is an ARRAY, or VARIANT containing an array value, the result is unchanged.
> For NULL or a JSON null input, returns NULL.
> For any other value, the result is a single-element array containing this value.

As we can see below, the input as an array, the result is an array of arrays which is not unchanged. 
```
>>> parse_one("select to_array(['test']) from test;", dialect="snowflake").sql(pretty=True)
"SELECT\n  ARRAY(ARRAY('test'))\nFROM test"
```

```
sqlglot==20.2.0
```

**Comment by wezham** [comment]
I raised this PR https://github.com/tobymao/sqlglot/pull/2696

**Comment by georgesittas** [comment]
> I raised this PR #2696

See https://github.com/tobymao/sqlglot/pull/2696#issuecomment-1860263568
