### ISSUE TITLE
Unicode character escape is not correctly converted from Trino

### ISSUE THREAD

**Issue by rantos9** [tobymao/sqlglot#2702]
Trino uses a `U&` prefix to indicate that a string has unicode characters escaped with a `\`.
https://trino.io/docs/current/language/types.html#varchar

SparkSQL don't use a prefix but escapes unicode characters with a `\u`.
https://spark.apache.org/docs/latest/sql-ref-literals.html#parameters 

**Fully reproducible code snippet**
```
in_sql = '''select U&'n\00e3o' as no'''
out_sql = sqlglot.transpile(in_sql, read='trino', write='spark', pretty=True)[0]
print(out_sql)
```

** Output **
```
SELECT
  U & 'ne3o' AS no
```

** Expected Output **
```
SELECT 
   'n\u00e3o' AS no
```

**Comment by georgesittas** [comment]
@rantos9 I'll try to add support for this at least for the Trino -> Trino case, as it seems that we don't currently support it; the tokenization is invalid. After that's done, I'll take a look at the Trino -> Spark conversion, but my first guess is that it's gonna be cumbersome to do it and so we might not solve that for now. Will let you know when there's an update..
