### ISSUE TITLE
Expected CTE to have alias when using `final` as CTE name in Clickhouse

### ISSUE THREAD

**Issue by Somtom** [tobymao/sqlglot#2711]
Hey team,
I realized that when we use `final` as CTE alias in Clickhouse dialect, the parser would break.
Without providing a dialect (or with other ones I tested) it works.

sqlglot version = 20.3.0

**Fully reproducible code snippet**

```python
query = """ 
WITH final AS (
    SELECT 1
)

SELECT * FROM final
"""
ast = sqlglot.parse_one(query, dialect='clickhouse')
```

**Official Documentation**
NA

**Comment by Somtom** [comment]
Hey @tobymao it seems that this still as issue for the CTE alias.
When I run the example on the latest commit db9de94004b8cb1ee7a10d9dd63d679adff12bc8 , I still get the error:

<img width="1292" alt="image" src="https://github.com/tobymao/sqlglot/assets/29712801/47c4a775-c5c4-447f-a3d1-f012e19dbdea">

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/1abd731143beb148d4759f6db721a0c429f3ec1f
