### ISSUE TITLE
Parsing of some column types returns wrong type

### ISSUE THREAD

**Issue by Somtom** [tobymao/sqlglot#2712]
Hey,
I identified an issue when we parse a SQL query that has `cast` expressions. Some of the target types change when converting the parsed ast back to SQL. I only have checked some cases for BigQuery and Clickhouse (see examples below)

sqglot version == 20.4.0

## Fully reproducible code snippet

**BigQuery:** 

```python
query = """ 
SELECT 
    CAST('1' AS STRING),
    CAST(['1','2','3'] AS ARRAY<STRING>),
    CAST('1.0' AS FLOAT64),
    CAST([1.0,2.0,3.0] AS ARRAY<FLOAT64>),
    CAST('1' AS INT64),
    CAST([1,2,3] AS ARRAY<INT64>),
    CAST('true' AS BOOL),
    CAST('2023-12-21' AS DATE),
    CAST('15:30:00' AS TIME),
    CAST('2023-12-21 15:30:00' AS DATETIME),
    CAST('2023-12-21 15:30:00+00' AS TIMESTAMP),
    CAST('1' AS BYTES)
"""
ast = sqlglot.parse_one(query, dialect='bigquery')
res = ast.sql(pretty=True)
print(res)
```
> SELECT
  CAST('1' AS TEXT),
  CAST(ARRAY('1', '2', '3') AS ARRAY<TEXT>),
  CAST('1.0' AS DOUBLE),
  CAST(ARRAY(1.0, 2.0, 3.0) AS ARRAY<DOUBLE>),
  CAST('1' AS BIGINT),
  CAST(ARRAY(1, 2, 3) AS ARRAY<BIGINT>),
  CAST('true' AS BOOLEAN),
  CAST('2023-12-21' AS DATE),
  CAST('15:30:00' AS TIME),
  CAST('2023-12-21 15:30:00' AS DATETIME),
  CAST('2023-12-21 15:30:00+00' AS TIMESTAMPTZ),
  CAST('1' AS BINARY)

Here, different issues are happening since the resulting query is not executable in BigQuery anymore

1. `STRING` get's wrongly converted to `TEXT` (also when wrapped in an `ARRAY`)
2. `FLOAT64` get's wrongly converted to `DOUBLE`(also when wrapped in an `ARRAY`)
3. . `INT64` get's wrongly converted to `BIGINT`(also when wrapped in an `ARRAY`)
4. . `TIMESTAMP` get's wrongly converted to `TIMESTAMPTZ`
5.  `BYTES` get's wrongly converted to `BINARY`
6.  Array values like `[ 1, 2, 3]` get converted to `ARRAY(1, 2, 3)`

I am sure I did not check all possible types but maybe the example already helps identifying the issue.

## Clickhouse

For Clickhouse I identified similar issues:

```python
query = """ 
SELECT 
    cast('1' AS String),
    cast(['1','2','3'] AS Array(String)),
    cast('1.0' AS Float64),
    cast([1.0,2.0,3.0] AS Array(Float64)),
    cast('1' AS Int64),
    cast([1,2,3] AS Array(Int64)),
    cast(true AS UInt8),
    cast('true' AS BOOL),
    cast('true' AS BOOLEAN),
    cast('2023-12-21' AS Date),
    cast('2023-12-21 15:30:00' AS DateTime)
"""
ast = sqlglot.parse_one(query, dialect='clickhouse')
res = ast.sql(pretty=True)
print(res)
```
> SELECT
  CAST('1' AS TEXT),
  CAST(ARRAY('1', '2', '3') AS ARRAY<TEXT>),
  CAST('1.0' AS DOUBLE),
  CAST(ARRAY(1.0, 2.0, 3.0) AS ARRAY<DOUBLE>),
  CAST('1' AS BIGINT),
  CAST(ARRAY(1, 2, 3) AS ARRAY<BIGINT>),
  CAST(TRUE AS UTINYINT),
  CAST('true' AS BOOLEAN),
  CAST('true' AS BOOLEAN),
  CAST('2023-12-21' AS DATE),
  CAST('2023-12-21 15:30:00' AS DATETIME)

1. `STRING` get's wrongly converted to `TEXT` (also when wrapped in an `ARRAY`)
2. `FLOAT64` get's wrongly converted to `DOUBLE`(also when wrapped in an `ARRAY`)
3. . `INT64` get's wrongly converted to `BIGINT`(also when wrapped in an `ARRAY`)
5.  `UInt8` get's wrongly converted to `UTINYINT`
6.  Array values like `[ 1, 2, 3]` get converted to `ARRAY(1, 2, 3)`
6.  **Arrays are casted to `ARRAY<dtype>` which also does not work in Clickhouse

**Official Documentation**
* [Bigquery data types](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#data_type_sizes)
* [Clickhouse data types](https://clickhouse.com/docs/en/sql-reference/data-types)

**Comment by tobymao** [comment]
you need to specify the dialect sql(dialect="bigquery")

**Comment by Somtom** [comment]
Yes that worked. Thanks for pointing me to that. I oversaw that part. Is this something that is documented? I didn't find it in the docs.

**Comment by tobymao** [comment]
[you need to specify the dialect sql(dialect="bigquery")](https://github.com/tobymao/sqlglot/blob/main/README.md#faq)
