### ISSUE TITLE
Redshift materialized view auto refresh syntax

### ISSUE THREAD

**Issue by hsheth2** [tobymao/sqlglot#2713]
**Fully reproducible code snippet**

```sql
CREATE MATERIALIZED VIEW mv_total_orders
AUTO REFRESH YES -- Add this clause to auto refresh the MV 
AS
 SELECT c.cust_id,
        c.first_name,
        sum(o.amount) as total_amount
 FROM orders o
 JOIN customer c
    ON c.cust_id = o.customer_id
 GROUP BY c.cust_id,
          c.first_name;
```

```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 2, Col: 4.
  CREATE MATERIALIZED VIEW mv_total_orders
AUTO REFRESH YES -- Add this clause to auto refresh the MV
```

**Official Documentation**

- https://docs.aws.amazon.com/prescriptive-guidance/latest/materialized-views-redshift/refreshing-materialized-views.html
- https://docs.aws.amazon.com/redshift/latest/dg/materialized-view-create-sql-command.html

**Comment by tobymao** [comment]
would appreciate a PR for small feature gaps like these @hsheth2

**Comment by hsheth2** [comment]
I did briefly look at building it myself, but frankly the core parsing code remains pretty opaque to me. The docs https://sqlglot.com/sqlglot/parser.html aren't really built out, and a lot of things aren't particularly clear (e.g. when is it allowable to use `_retreat`, what types of things do you consider properties, what are the side-effects of `_match`, etc), especially for someone who hasn't built a parser before. Fwiw, the generator code does feel a lot more straightforward and easy to contribute to.

**Comment by tobymao** [comment]
greats happy to answer questions and help you become a regular contributor
