### ISSUE TITLE
sqlglot.errors.ParseError when parsing DATE_SUB、DATE_ADD... function

### ISSUE THREAD

**Issue by yiliang-neo** [tobymao/sqlglot#2716]
### Discussed in https://github.com/tobymao/sqlglot/discussions/2715
borther you again. thank you
<div type='discussions-op-text'>

<sup>Originally posted by **yiliang-neo** December 22, 2023</sup>
hi.
There is a problem confuses me.
i use sqlglot==18.11.6.
when i run
```
sqlglot.parse("select date_sub(current_date(), 1);", "doris")
```
it raises a sqlglot.errors.ParseError, but the errors in sqlglot.errors.ParseError is empty: [].
<img width="554" alt="截屏2023-12-22 17 23 11" src="https://github.com/tobymao/sqlglot/assets/33338065/404f252c-2398-4527-baee-af0f2ebcea48">
i want to know if it is an error actually(i tested this sql in engine and it can be executed) and seek a advice about how to identify this non-errors error?</div>

**Comment by tobymao** [comment]
docs clearly say you need to do date_sub(current_date(), interval 1 day) which works

https://doris.apache.org/docs/dev/sql-manual/sql-functions/date-time-functions/date-add/

**Comment by yiliang-neo** [comment]
sorry to borther you. maybe i do not say clearly. i have two questions:
1. if the statement : "date_sub(current_date(), 1 )" is wrong, why the errors in  sqlglot.errors.ParseError is empty?
![image](https://github.com/tobymao/sqlglot/assets/33338065/3ed0bed2-e978-436e-bdc0-bc5931cabe6e)

3. actually, i run the statement : "date_sub(current_date(), 1 )" it can work like this
<img width="593" alt="image" src="https://github.com/tobymao/sqlglot/assets/33338065/86c1d451-b004-4838-b778-a4036b31ece8">

thank you again
