### ISSUE TITLE
Parsing queries with REGEXP Funtions

### ISSUE THREAD

**Issue by Shweta-BI-Lead** [tobymao/sqlglot#2722]
I'm trying to parse queries using SQLGLOT to identify the table objects.
I have many queries which uses functions like REGEXP_REPLACE, REGEXP_SUBSTR etc.
Could you please provide support for REGEXP functions?

Official Documentation -
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/REGEXP_REPLACE.html#GUID-EA80A33C-441A-4692-A959-273B5A224490

Request team to look into this. Thank you!

**Comment by georgesittas** [comment]
Hey, many `REGEXP_*` functions are already supported, including the ones you mentioned.

**Comment by Shweta-BI-Lead** [comment]
Hello @georgesittas,
Happy New Year to You and Your Team!

I can see that SQLGLOT fails when it doesn't find third argument in the REGEXP_REPLACE method.

```
SELECT 
    REGEXP_REPLACE('Th♥is∞ is a dem☻o of REGEXP_♫REPLACE function','[^a-z_A-Z ]') 
FROM 
    dual
```
Above sample query is a valid query but SQLGLOT fails because it doesn't find the third argument.

Supported documents - 
https://www.oracletutorial.com/oracle-string-functions/oracle-regexp_replace/

Same goes for other REGEXP functions too. 
Request you to look into this. 

Thank you,
Shweta

**Comment by Shweta-BI-Lead** [comment]
> Hello @georgesittas, Happy New Year to You and Your Team!
> 
> I can see that SQLGLOT fails when it doesn't find third argument in the REGEXP_REPLACE method.
> 
> ```
> SELECT 
>     REGEXP_REPLACE('Th♥is∞ is a dem☻o of REGEXP_♫REPLACE function','[^a-z_A-Z ]') 
> FROM 
>     dual
> ```
> 
> Above sample query is a valid query but SQLGLOT fails because it doesn't find the third argument.
> 
> Supported documents - https://www.oracletutorial.com/oracle-string-functions/oracle-regexp_replace/
> 
> Same goes for other REGEXP functions too. Request you to look into this.
> 
> Thank you, Shweta

Hi Team,

Could you please look into above issue? Thank you!

Thanks, Shweta
