### ISSUE TITLE
Read existing SQL and add new expressions to it

### ISSUE THREAD

**Issue by Kannedhara** [tobymao/sqlglot#2724]
I have a sql statement which is in string format and I want to add join using .join() operator. how is it possible ?

query = 'select * from tableA'
query = parse_one(query).join('tableB', ....,)

or query = parse_one(query, into=exp.Select).join('tableB', .....,) 

throws an error.

Any help ?

**Comment by tobymao** [comment]
can’t help without more detail. it should work.
