### ISSUE TITLE
clickhouse: parse all aggregate functions as `exp.AggFunc` and support aggregate combinators

### ISSUE THREAD

**Issue by pkit** [tobymao/sqlglot#2727]
ClickHouse has a very long list of aggregate functions [here](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference)
It also has something that's called "combinators", [here](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/combinators).

I can cook up a PR with all the non-standard aggregates injected into the dialect. But it's not clear what to do with combinators?
Just subclass if from `exp.AggFunc` ? But then it probably needs to exist in non-dialect specific files?

Mapping from aggregate to combinator(s) and back is pretty important for MV handling, as these have different semantics in MV or regular views...

**Comment by tobymao** [comment]
not planning to do this but happy to accept and assist you with a pr. you can probably programatically inject something here, but not exactly sure, happy to chat on slack or something to discuss
