### ISSUE TITLE
: is parsed as Bracket (Snowflake)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#2738]
`:` in the snowflake dialect is parsed to `Bracket`:
```python
>>> import sqlglot; sqlglot.parse_one("""select parse_json('{"fruit":"banana"}'):fruit""", read="snowflake")
Select(
  expressions=[
    Bracket(
      this=ParseJSON(
        this=Literal(this={"fruit":"banana"}, is_string=True)),
      expressions=[
        Literal(this=fruit, is_string=True)])])
```

But `:` is [GET_PATH ](https://docs.snowflake.com/en/sql-reference/functions/get_path).

NB: In duckdb this would be equivalent to `JSONExtract`.

**Comment by tekumara** [comment]
Another example with a nested path:
```python
sqlglot.parse_one("""
select parse_json('{"food":{"fruit":"banana"}}'):food.fruit::varchar
            """, read="snowflake")
```
produces:
```
(SELECT expressions: 
  (DOT this: 
    (BRACKET this: 
      (PARSEJSON this: 
        (LITERAL this: {"food":{"fruit":"banana"}}, is_string: True)), expressions: 
      (LITERAL this: food, is_string: True)), expression: 
    (IDENTIFIER this: fruit, quoted: False)))
```            
ie: the `.fruit` is turned into an IDENTIFIER.

**Comment by georgesittas** [comment]
https://github.com/tobymao/sqlglot/pull/2744/commits/3eaef65e62d77a47b788ff9e3922af85130e6ec5

> Another example with a nested path:
> 
> ```python
> sqlglot.parse_one("""
> select parse_json('{"food":{"fruit":"banana"}}'):food.fruit::varchar
>             """, read="snowflake")
> ```
> 
> produces:
> 
> ```
> (SELECT expressions: 
>   (DOT this: 
>     (BRACKET this: 
>       (PARSEJSON this: 
>         (LITERAL this: {"food":{"fruit":"banana"}}, is_string: True)), expressions: 
>       (LITERAL this: food, is_string: True)), expression: 
>     (IDENTIFIER this: fruit, quoted: False)))
> ```
> 
> ie: the `.fruit` is turned into an IDENTIFIER.

**Comment by tekumara** [comment]
Nice thank you for covering this!

PS: just realised my example above was copy-pasted incorrectly and had a stray trailing `::varchar` in the sql string, which is why my parse tree didn't have a `CAST`.
