### ISSUE TITLE
CROSS APPLY is changed to LATERAL (tsql)

### ISSUE THREAD

**Issue by deschman** [tobymao/sqlglot#2743]
Code to reproduce:
```
import sqlglot

input_sql = """
SELECT
    sd1.id,
    sd1.item_id,
    sd1.ds,
FROM
    sqlmesh_example.seed_model AS sd1
CROSS APPLY (
    SELECT TOP 1
        sd2.id
    FROM
        sqlmesh_example.seed_model AS sd2
    WHERE sd1.id = sd2.id
)
"""

sqlglot.transpile(input_sql, read="tsql")
```

Code output:
`'SELECT sd1.id, sd1.item_id, sd1.ds FROM sqlmesh_example.seed_model AS sd1, LATERAL (SELECT TOP 1 sd2.id FROM sqlmesh_example.seed_model AS sd2 WHERE sd1.id = 
sd2.id)`

Error when executing query - coming from inner-select inside parenthases:
`SQL Error [156] [S0001]: Incorrect syntax near the keyword 'SELECT'.`

While LATERAL is reserved in tsql, there is no functional use. I would expect that CROSS APPLY would stay CROSS APPLY when transpiling back to tsql or when transpiling inner LATERAL joins from other dialects to tsql.

**Comment by georgesittas** [comment]
Will try to fix this one tomorrow, it's a bit more involved than initially expected

**Comment by deschman** [comment]
Does it simplify the problem scope at all if we only needed CROSS APPLY to stay CROSS APPLY, leaving the LATERAL joins problem for future implementation?

**Comment by georgesittas** [comment]
Yeah, my goal was to actually preserve the roundtrip as a first step, but that got a bit involved because some parts need to be refactored. I did a pass yesterday but put it on hold, will try to get a fix in today. We can chat about the `LATERAL` -> T-SQL later, to keep the scope small.
