### ISSUE TITLE
timestamp_from_parts signature with date and time input arguments not supported (snowflake)

### ISSUE THREAD

**Issue by notgerry** [tobymao/sqlglot#2751]
Snowflake has a version of `timestamp_from_parts` that takes a `date` and a `time` that doesn't seem to be supported yet.

**Fully reproducible code snippet**
```
import sqlglot

sql = """
with

data as (
select '2020-01-01'::date as d, time_from_parts(12,0,0) as t
)

select
 timestamp_from_parts(d, t) as dt
from
  data
"""

sqlglot.parse(sql, dialect="snowflake")
```
<img width="932" alt="image" src="https://github.com/tobymao/sqlglot/assets/991997/eaadd12b-1bd1-4023-ae4c-e8c84566cc48">

**Official Documentation**
https://docs.snowflake.com/en/sql-reference/functions/timestamp_from_parts

**Comment by georgesittas** [comment]
Hey, thanks for the report. Will take a look shortly.
