### ISSUE TITLE
Support BigQuery UNIX_DATE

### ISSUE THREAD

**Issue by jherrmannNetfonds** [tobymao/sqlglot#2758]
**Is your feature request related to a problem? Please describe.**
When I want to translate BigQuery [UNIX_DATE ](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#unix_date) to duckdb it is not supported

**Describe the solution you'd like**
Bigquery `SELECT UNIX_DATE(DATE '2008-12-25') AS days_from_epoch;`
should become something like
DuckDB: `SELECT epoch(DATE '2008-12-25')/86400 AS days_from_epoch;`

**Describe alternatives you've considered**
Since there maybe no good mapping, an error would be fine, so that you know that the bigquery SQL could not be translated

**Comment by georgesittas** [comment]
Hey, thanks for the report. We'll look into this soon.

@tobymao did we use to have an expression for days since epoch or something?

**Comment by tobymao** [comment]
i don't think so

**Comment by tobymao** [comment]
@jherrmannNetfonds thanks for the report, it'd be great if you could start making prs for some of these simpler issues. thanks!

**Comment by jherrmannNetfonds** [comment]
Sure, I am in the process to find my way around in the source code :)
