### ISSUE TITLE
`qualify` fails with `schema`

### ISSUE THREAD

**Issue by virendrakabra14** [tobymao/sqlglot#2760]
Reproducible example
```python
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify

sql = "SELECT * FROM tab WHERE `Name` = 'someText'"
schema = {"tab": {"Name": "text"}}
dialect = "mysql"

# works without schema
print(qualify(parse_one(sql, dialect=dialect), identify=False).sql(dialect=dialect))
# SELECT * FROM tab AS tab WHERE tab.`Name` = 'someText'

# does not work with schema
print(qualify(parse_one(sql, dialect=dialect), identify=False, schema=schema).sql(dialect=dialect))
# OptimizeError: Column '"Name"' could not be resolved
```

This might be due to `Name` being specified as a keyword in [mysql docs](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-N) but similar behavior is seen with `dialect="sqlite"` that does not have `Name` as a keyword ([sqlite docs](https://sqlite.org/lang_keywords.html))

**Comment by georgesittas** [comment]
You need to also make `Name` case-sensitive in the schema definition:

```python
>>> from sqlglot import parse_one
>>> from sqlglot.optimizer.qualify import qualify
>>>
>>> sql = "SELECT * FROM tab WHERE `Name` = 'someText'"
>>> schema = {"tab": {"`Name`": "text"}}
>>> dialect = "mysql"
>>>
>>> print(qualify(parse_one(sql, dialect=dialect), identify=False).sql(dialect=dialect))
SELECT * FROM tab AS tab WHERE tab.`Name` = 'someText'
>>> print(qualify(parse_one(sql, dialect=dialect), identify=False, schema=schema, dialect=dialect).sql(dialect=dialect))
SELECT tab.`Name` AS `Name` FROM tab AS tab WHERE tab.`Name` = 'someText'
```

**Comment by virendrakabra14** [comment]
It wasn't the `Name` -> ``` `Name` ``` that worked, but it was adding the `dialect` kwarg to `qualify`.
But the latter expands `*` to all columns - something that I would have liked to be avoided.

**Comment by georgesittas** [comment]
> It wasn't the `Name` -> ``` `Name` ``` that worked

I guess that makes sense for MySQL specifically, because it's case-sensitive by default.

>  But the latter expands `*` to all columns - something that I would have liked to be avoided.

https://github.com/tobymao/sqlglot/pull/2762
