### ISSUE TITLE
Tsql Exec command not parsed by sqlglot

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#2772]
sqlglot=20.7.0

**Code**:
```
transpile("EXEC MyProc @id=7, @name='Lochristi';", read='tsql', write='tsql')
```

**Error**:
```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 13.
  EXEC MyProc @id=7, @name='Lochristi';
```

**Expected Behaviour**:
This is a valid t-sql command and should be parsed correctly by the package.

**Official Documnetation**:
https://learn.microsoft.com/en-us/sql/t-sql/language-elements/execute-transact-sql?view=sql-server-ver16#examples-sql-server

**Comment by tobymao** [comment]
feel free to submit a pr
