### ISSUE TITLE
nulls first/last transformation for mysql is incorrect in the context of `RANGE` windows

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2779]
```
In [12]: sg.parse_one(
    ...:     "select sum(x) over (order by 1 nulls last range between 1 preceding and current row)",
    ...:     read="duckdb",
    ...: ).sql("mysql")
Out[12]: 'SELECT SUM(x) OVER (ORDER BY CASE WHEN 1 IS NULL THEN 1 ELSE 0 END, 1 range BETWEEN 1 preceding AND CURRENT ROW)'
```

`RANGE` windows cannot have more than one key when using `ORDER BY`, so this transformation can't be used in that context.

**Comment by cpcloud** [comment]
Outside of a window context this transformation is incorrect for a different reason:

```
In [7]: sg.parse_one("select x from t order by 1 nulls last", read="duckdb").sql("mysql")
Out[7]: 'SELECT x FROM t ORDER BY CASE WHEN 1 IS NULL THEN 1 ELSE 0 END, 1'
```

The `1` in `ORDER BY 1` in the original query refers to a column in ordinal position, whereas the transformed query contains `CASE WHEN 1 IS NULL`. The `1` in that case is an integer expression and so the case statement will always test `FALSE`.

**Comment by cpcloud** [comment]
@tobymao I see you closed this, but the issue seems to remain for `RANGE` windows.

**Comment by tobymao** [comment]
@cpcloud could you elaborate more on what the issue is? we don't do the transform anymore when i try it.

```python -m sqlglot "select sum(x) over (order by 1 nulls last range between 1 preceding and current row)" --read=duckdb --write=mysql
```
```
'NULLS LAST' not supported with positional ordering
SELECT
  SUM(`x`) OVER (ORDER BY 1 range BETWEEN 1 preceding AND CURRENT ROW)
```

**Comment by tobymao** [comment]
3f7748b0
