### ISSUE TITLE
Relation to SQLParser-rs

### ISSUE THREAD

**Issue by astronautas** [tobymao/sqlglot#2781]
Hey guys,

I've been using sqlglot for my projects and I think it's great. It does 1 job extremely well. I was wondering why you guys opted to write your own rust-based parser to boost performance instead of using already existing [sqlparser-rs](https://github.com/sqlparser-rs/sqlparser-rs)? Dialects do change, although probably not that too often. Just to understand the rationale.

Cheers!

**Comment by tobymao** [comment]
Only the tokenizer is written to rust, the parser would be a completely different story. Additionally, the functionality between sqlglot and sqlparse-rs are complete different. SQLGlot is a full transpiler, optimizer, and engine built in python. So it’s really not transferable.
