### ISSUE TITLE
Support for SHOW SCHEMAS and SHOW OBJECTS (Snowflake)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#2784]
- [SHOW SCHEMAS docs](https://docs.snowflake.com/en/sql-reference/sql/show-schemas)
- [SHOW OBJECTS docs](https://docs.snowflake.com/en/sql-reference/sql/show-objects)
 
NB: Although not mentioned in the docs, SHOW OBJECTS supports a similar syntax to SHOW SCHEMAS, eg: this is valid
```
show terse objects in db1.schema1 starts with 'a' limit 1 from 'b';
```

**Comment by tobymao** [comment]
this is parsed already as a command, more comprehensive parsing is not planned, but we'd happily accept a pr.
