### ISSUE TITLE
Interactive code examples

### ISSUE THREAD

**Issue by nalgeon** [tobymao/sqlglot#2789]
Hi Toby! Thank you for this awesome project!

Would you be interested in making the code examples in the docs interactive for better understanding? Here is what it could look like: [Try SQLGlot in Y minutes](https://codapi.org/try/sqlglot/)

As an added benefit, I've also fixed some examples that failed due to import errors.

If you're interested, I'll be happy to send you a PR.

**Comment by tobymao** [comment]
not interested in that but would be interested in fixes to import errors thanks!
