### ISSUE TITLE
INTERVAL '5' hours '30' minutes not working.

### ISSUE THREAD

**Issue by nikmalviya** [tobymao/sqlglot#2793]
Not able to parse databricks query which contains `INTERVAL x hours y minutes`.

getting this error.

`sqlglot.errors.ParseError: Expecting ).`

**Comment by tobymao** [comment]
https://docs.databricks.com/en/sql/language-manual/data-types/interval-type.html

looks like it works for base spark as well

**Comment by nikmalviya** [comment]
Yes this is working for spark as well.

**Comment by georgesittas** [comment]
I plan to take a look into this soon.

**Comment by georgesittas** [comment]
It seems like this is also supported:

```
spark-sql (default)> select interval '5' hours '30' minutes '5' seconds '6' milliseconds '7' microseconds;
0 05:30:05.006007000
Time taken: 0.144 seconds, Fetched 1 row(s)
```
