### ISSUE TITLE
Nested `COALESCE(CAST(` is added on `parse_one` even though I already added it to my input query 

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#2802]
sqlglot==20.7.0
dialect=postgres

**Code**:
```python
query= """
SELECT
  *
FROM hubspot.contacts
WHERE
  CONCAT(
    COALESCE(CAST(property_email AS TEXT), ''),
    COALESCE(CAST(property_city AS TEXT), '')
  ) <> ''
"""
dialect="postgres"
expression_tree = parse_one(query, read=dialect)
result = expression_tree.sql(pretty=True, dialect=dialect)
print(result)
```

**Output**:
```sql
SELECT
  *
FROM hubspot.contacts
WHERE
  CONCAT(
    COALESCE(CAST(COALESCE(CAST(property_email AS TEXT), '') AS TEXT), ''),
    COALESCE(CAST(COALESCE(CAST(property_city AS TEXT), '') AS TEXT), '')
  ) <> ''
```

**Issue**:
It is very unexpected that `property_email` and `property_city` get wrapped in a nested `COALESCE(CAST(` expression again.

**Background**:
We have the following scenario,
1. A user enter an sql query and saves it to their notebook.
2. sqlglot parses the query, and we apply some rules on it.
3. A prettified version is returned to the user.

The sequence of steps mentioned above is repeated every time a user saves their query. As a result, we end up in a situation where a nested `COALESCE(CAST(` is added on each save.

**Question**:
Is it possible to not add `COALESCE(CAST(` if a column is already wrapped in it? (like in the code snippet above)

**Comment by tobymao** [comment]
![Screenshot_2024-01-09_22 20 33](https://github.com/tobymao/sqlglot/assets/8205034/d1a2be36-f79c-4e78-9a4c-a77c9078cfe4)

i'm unable to reproduce the issue you're seeing

**Comment by SudarshanVS** [comment]
Sorry, looks like my version was wrong. I was using version `19.0.0`
