### ISSUE TITLE
Parse_one does not raise error when USING clause not found on left side of join (BIGQUERY)

### ISSUE THREAD

**Issue by pablo-statsig** [tobymao/sqlglot#2809]
Here is a simple example of this case:

from sqlglot import parse_one

res = parse_one(
    """
select * from ( ( select col_a from  table_1  ) as f inner join  table_1  using(col_b) )   """,
    dialect="bigquery",
)

Column col_b in USING clause not found on left side of join

Bigquery will return the error:
Column col_b in USING clause not found on left side of join

**Comment by georgesittas** [comment]
SQLGlot is [not a validator](https://github.com/tobymao/sqlglot/blob/main/README.md) and this is not an error you usually catch at parse time anyway.

**Comment by pablo-statsig** [comment]
> SQLGlot is [not a validator](https://github.com/tobymao/sqlglot/blob/main/README.md) and this is not an error you usually catch at parse time anyway. If you want to do checks like this one you need to use the optimizer, specifically the `qualify` rule, provided you also have the relevant table schemas.

Ah I see thanks for the tip.
