### ISSUE TITLE
SQLGlot does not support parsing SQLAlchemy / DuckDB PREPARE statements

### ISSUE THREAD

**Issue by baruchoxman** [tobymao/sqlglot#2813]
For example:

```
PREPARE query_person AS 
SELECT *
FROM person
WHERE starts_with(name, ?)
  AND age >= ?;
```

Or:

```
PREPARE st_a20ab3bbed2a428097f87e93f308b6f5 FROM SELECT "table_name"
FROM "information_schema"."tables"
WHERE "table_schema" = ?
  AND "table_type" = 'BASE TABLE'
```

**Comment by georgesittas** [comment]
This is currently "parsed" into a `Command` - adding full parsing support for this is not a priotity for us right now but we'll be happy to accept a well-crafted PR. If you want to chat about this feel free to join our [Slack](https://github.com/tobymao/sqlglot#get-in-touch).

Additionally - please, include additional docs for future issues you create, it helps us understand the issue's scope better. Thanks!
