### ISSUE TITLE
ParseError not working as expected

### ISSUE THREAD

**Issue by JDRanpariya** [tobymao/sqlglot#283]
query = `selec col from t1;`
while doing `transpile(query)`
output = `sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 11.
  selec col from t1;`

Expected Output -> It should say selec is unexpected. I mean why from is underlined at Col 11 and not select at Col 1.

**Comment by tobymao** [comment]
well selec could be a column name followed by the alias col, so it's kind of hard to specify exactly the error you'd expect, i'm closing this for now as won't fix
