### ISSUE TITLE
[oracle] trunc's parse is not implemented

### ISSUE THREAD

**Issue by liujiwen-up** [tobymao/sqlglot#2837]
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/TRUNC-date.html#GUID-BC82227A-2698-4EC8-8C1A-ABECC64B0E79
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/TRUNC-number.html#GUID-911AE7FE-E04A-471D-8B0E-9C50EBEFE07D
SELECT TRUNC(TO_DATE('27-OCT-92','DD-MON-YY'), 'YEAR')
SELECT TRUNC(15.79,1) "Truncate" FROM DUAL;

**Comment by tobymao** [comment]
there are no issues with trunc

```(.env) [toby@muc sqlglot]$ python -m sqlglot "trunc(x, 1)" --read=oracle
TRUNC("x", 1)
```
