### ISSUE TITLE
Parsing oracle queries with 'IN <Column>' Clause 

### ISSUE THREAD

**Issue by Shweta-BI-Lead** [tobymao/sqlglot#2841]
Hi Team,

I have observed that sqlglot parsing fails when oracle query has in clause where some value or column is looked-up in a column.
Please check the below query for your reference -

```
SELECT * FROM EMP
WHERE 'a21' IN EMP_ID

OR

SELECT * FROM EMP1, EMP2
WHERE EMP1.EMP_ID IN EMP2.EMP_ID
```
**Above queries are valid ones and tested in the oracle latest version.**

**Documentation -**
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/IN-Condition.html#GUID-C7961CB3-8F60-47E0-96EB-BDCF5DB1317C

Request team to look into this. Thank you!

Thanks,
Shweta

**Comment by tobymao** [comment]
no issues, please include a stack trace next time and make sure you're using the latest version of sqlglot

`python -m sqlglot "SELECT * FROM EMP WHERE 'a21' IN EMP_ID" --read=oracle`
