### ISSUE TITLE
Support for timezone conversion functions between Spark and Trino/Presto dialects

### ISSUE THREAD

**Issue by hdemers** [tobymao/sqlglot#2846]
**Is your feature request related to a problem? Please describe.**
The Spark functions [`from_utc_timestamp`](https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.functions.from_utc_timestamp.html) and [`to_utc_timestamp`](https://spark.apache.org/docs/3.1.2/api/python/reference/api/pyspark.sql.functions.to_utc_timestamp.html) are transpiled as such when converting to Presto/Trino, but these don't exist in those dialects. I believe they should be converted to [ `at_timezone`](https://trino.io/docs/current/functions/datetime.html#at_timezone) and [`with_timezone`](https://trino.io/docs/current/functions/datetime.html#with_timezone) respectively. 

**Describe the solution you'd like**
I'd like support for `at_timezone` and `with_timezone` be added to Presto/Trino dialects such that they transpile `from_utc_timestamp` and `to_utc_timestamp`, from Spark. And vice versa.

**Describe alternatives you've considered**
I don't have any alternative if I want to use sqlglot.

**Additional context**

**Comment by georgesittas** [comment]
Hey, thanks for the report - will take a look tomorrow.

**Comment by georgesittas** [comment]
The behavior you described doesn't match what's on the current main branch, make sure you're on the latest version:

```python
>>> import sqlglot
>>> sqlglot.transpile("FROM_UTC_TIMESTAMP(CAST(x AS TIMESTAMP), 'utc')", "spark", "presto")
["TRY_CAST(x AS TIMESTAMP) AT TIME ZONE 'utc'"]
```

**Comment by georgesittas** [comment]
I guess `to_utc_timestamp` is not parsed into an appropriate `Func` at the moment, so that would not be transpiled:

```python
>>> sqlglot.parse_one("SELECT to_utc_timestamp('2016-08-31', 'Asia/Seoul')", "spark")
Select(
  expressions=[
    Anonymous(
      this=to_utc_timestamp,
      expressions=[
        Literal(this=2016-08-31, is_string=True),
        Literal(this=Asia/Seoul, is_string=True)])])
>>> sqlglot.parse_one("SELECT to_utc_timestamp('2016-08-31', 'Asia/Seoul')", "spark").sql("presto")
"SELECT TO_UTC_TIMESTAMP('2016-08-31', 'Asia/Seoul')"
```

I'll leave this one open after all and try to get it in tomorrow.

**Comment by hdemers** [comment]
Sorry for the very slow reply, I was out. And thank you for looking into this so quickly.

I must be doing something wrong, because I still can't get these functions transpiled from Presto to Spark. Here's what I'm doing.

```python
>>> import sqlglot
>>> print(sqlglot.__version__)
20.9.0

>>> q_presto = """
>>>    select time_utc
>>>         , time_zone
>>>         , at_timezone(time_utc, time_zone) as time_at_tz
>>>         , with_timezone(time_utc, time_zone) as time_with_tz
>>>      from mytable
>>> """
>>> print(sqlglot.transpile(q_presto, 'presto', 'spark', pretty=True)[0])
SELECT
  time_utc,
  time_zone,
  AT_TIMEZONE(time_utc, time_zone) AS time_at_tz,
  WITH_TIMEZONE(time_utc, time_zone) AS time_with_tz
FROM mytable
```
Also
```python
>>> q_spark = """
>>>     select time_utc
>>>          , time_zone
>>>          , from_utc_timestamp(time_utc, time_zone) as time_at_tz
>>>          , to_utc_timestamp(time_utc, time_zone) as time_with_tz
>>>       from mytable
>>> """
>>> print(sqlglot.transpile(q_spark, 'spark', 'presto', pretty=True)[0])
SELECT
  time_utc,
  time_zone,
  CAST(time_utc AS TIMESTAMP) AT TIME ZONE time_zone AS time_at_tz,
  TO_UTC_TIMESTAMP(time_utc, time_zone) AS time_with_tz
FROM mytable
```

If I'm not mistaken, `AT TIME ZONE` can only accept a literal time zone, not a column, so translating `from_utc_timestamp` to `AT TIME ZONE` doesn't achieve the exact same thing. I think we should transpile `from_utc_timestamp` to `at_timezone`, right?

**Comment by ddelzell** [comment]
@georgesittas did you see the above comment?  I'm also having the same issue when transpiling between spark and presto.

**Comment by georgesittas** [comment]
Hey, thanks for bumping this thread, it seems like I missed the comment. I will have a look shortly and let you know when there's an update.

**Comment by georgesittas** [comment]
I see now what you meant @hdemers - iirc, I'd initially dismissed those alternatives because they weren't documented in Presto's docs. I also didn't test the column case with `AT TIME ZONE`, so wasn't aware of that issue.

Will look into fixing this, thanks for reporting it.

**Comment by georgesittas** [comment]
The fix for this will be included in the next release, probably some time soon.

**Comment by hdemers** [comment]
Awesome, looking forward to it. Thanks again for looking into this.
