### ISSUE TITLE
ParseError for FETCH clause

### ISSUE THREAD

**Issue by nattaylor** [tobymao/sqlglot#285]
I was hoping to parse statements from Looker which include FETCH clauses but I got a ParseError

I understand this may not be supported but thought I'd raise an issue anyway

```
import sqlglot
sqlglot.parse_one('SELECT 1 FETCH NEXT 1 ROWS ONLY')

ParseError: Invalid expression / Unexpected token. Line 1, Col: 16.
  SELECT 1 FETCH NEXT 1 ROWS ONLY
```

**Comment by tobymao** [comment]
what is fetch? can you post relevant documentation

**Comment by nattaylor** [comment]
Here's what the Snowflake docs say https://docs.snowflake.com/en/sql-reference/constructs/limit.html#limit-fetch

>LIMIT / FETCH
>Constrains the maximum number of rows returned by a statement or subquery. Both LIMIT (Postgres syntax) and FETCH (ANSI syntax) are supported, and produce the same result.

And here's PG https://www.postgresql.org/docs/current/sql-fetch.html
