### ISSUE TITLE
Support `TRUNCATE TABLE` statments

### ISSUE THREAD

**Issue by judahrand** [tobymao/sqlglot#2850]
**Is your feature request related to a problem? Please describe.**
Currently, `TRUNCATE TABLE table` is parsed like this:

```python
>>> sqlglot.parse_one('TRUNCATE TABLE "table"')
(COMMAND this: TRUNCATE, expression: 
  (LITERAL this: TABLE "table", is_string: True))
```

This doesn't seem correct. 

**Describe the solution you'd like**

I'd expect something more like:

```python
>>> sqlglot.parse_one('TRUNCATE TABLE "table"')
(TRUNCATE this: 
  (IDENTIFIER this: table, quoted: True) , kind: TABLE)
```
**Describe alternatives you've considered**

**Additional context**

**Comment by tobymao** [comment]
not planned, feel free to contribute a PR if you need this

**Comment by tobymao** [comment]
we like to keep the issues list clean and as an indication of work that is actively being worked on and will be completed soon. you can filter on the issues list of the 'not planned' tag.

i don't have an objection to the suggested functionality, but it's not high priority.

**Comment by benknoble** [comment]
This used to be supported, if I'm reading the history right. In https://github.com/tobymao/sqlglot/commit/48b8b186aaf9f5380c5b72012c39e6a7370222e2 from https://github.com/tobymao/sqlglot/issues/63, you added a TRUNCATE token. But later in https://github.com/tobymao/sqlglot/commit/1d7c5e74b2cfe48b0f8c9152905714bf090e7c1a you made TRUNCATE a command.

TRUNCATE is part of the SQL standard (introduced in 2008) according to https://en.wikipedia.org/wiki/Truncate_(SQL).

Can we please bring back correct parsing of the truncate command?

**Comment by georgesittas** [comment]
The result was the same for the commit you're referencing:

```python
➜  sqlglot git:(48b8b186) ✗ python
Python 3.10.13 (main, Nov  1 2023, 16:34:31) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlglot
>>> sqlglot.parse_one('TRUNCATE TABLE "table"')
(COMMAND this: TRUNCATE, expression:
  (LITERAL this:  TABLE "table", is_string: True))
>>>
```

**Comment by benknoble** [comment]
In that case, it's hard for me to see how this isn't a bug, then. It especially makes methods like `find_all` much harder to use to look for `TRUNCATE` (now I have to look for `sqlglot.exp.Command` and filter where `args['this']` is `'TRUNCATE'`, etc.).

**Comment by georgesittas** [comment]
It's not a bug, it's simply unimplemented behavior. Having the parser succeed is useful for people who don't care about parsing certain statements and just wanna roundtrip (parse, generate) them when hitting the engine.

**Comment by georgesittas** [comment]
In any case, as Toby said we're happy to accept a contribution for this. Our bandwidth is relatively limited and it's not high priority so we don't plan to work on this right now. If you wanna take a stab at this feel free to join our [Slack](https://tobikodata.com/slack) and we can chat about possible approaches.

**Comment by georgesittas** [comment]
Fixed in #3026 by @VaggelisD!

**Comment by benknoble** [comment]
Thanks @VaggelisD !

@georgesittas and others: what's the release cadence like so that I can start using this new feature?

**Comment by georgesittas** [comment]
We have a short release cadence, but I'm not sure when exactly we'll deploy the next one - probably soon.

**Comment by VaggelisD** [comment]
No problem @benknoble, looking forward to hearing your feedback on this feature, if any.

**Comment by georgesittas** [comment]
This feature has been deployed with v22.1.0
