### ISSUE TITLE
ParseError for Snowflake's : operator

### ISSUE THREAD

**Issue by nattaylor** [tobymao/sqlglot#286]
I tried to parse a query with Snowflake's `:` operator for traversing semi-structured data and got a ParseError https://docs.snowflake.com/en/user-guide/querying-semistructured.html#traversing-semi-structured-data

```
import sqlglot
sqlglot.parse_one("""SELECT PARSE_JSON('{foo: 1}'):foo""")
ParseError: Invalid expression / Unexpected token. Line 1, Col: 30.
```

**Comment by tobymao** [comment]
you need to specify read="snowflake"

**Comment by nattaylor** [comment]
Thank you!
