### ISSUE TITLE
Bug report : OptimizerError thrown by qualify when INTERSECT, UNION, or EXCEPT used in uncorrelated subquery

### ISSUE THREAD

**Issue by derekpaulsen** [tobymao/sqlglot#2860]
## Summary / Background

When using `qualify` with `'mysql'` dialect there is an unexpected error. The following code snippet throws an OptimizerError due to an unresolved column despite all columns being well defined. It appears as though quoting the identifier "B" resolves the issue but this should not be required since the query is unambiguous. 

## Steps to Reproduce

To reproduce, run the following code snippet with python3.11 and sqlglot==20.8.0.

```python3
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify

schema = {
        '' : {
            'table_a' : {
                'col1' : 'INT'
            },
            'table_b' : {
                'col2' : 'INT'
            }
        }
    }

query = """
SELECT *
FROM 
"table_a" as "A"
WHERE "A"."col1" IN (
    SELECT MAX(B."col2") FROM "table_b" as "B"
    UNION ALL
    SELECT MAX("C"."col2") FROM "table_b" as "C"
);"""

dialect='mysql'
qualify(parse_one(query, dialect=dialect), schema=schema, dialect=dialect)
# throws error : OptimizeError: Column '"B".'col2'' could not be resolved for table: 'B'
# thrown by validate_qualify_columns
```

## Documentation Links
[qualify documentation](https://sqlglot.com/sqlglot/optimizer/qualify.html#qualify)
[MySQL dialect documentation](https://sqlglot.com/sqlglot/dialects/mysql.html#MySQL)
[validate_qualify_columns documentation](https://sqlglot.com/sqlglot/optimizer/qualify_columns.html#validate_qualify_columns)

## Additional Information 

When investigating the source of the exception, it appears as though the bug is in the `scope` code.  

From the source file `sqlglot/optimizer/qualify_columns.py` line 83.
```python3
            if scope.external_columns and not scope.is_correlated_subquery and not scope.pivots:
                column = scope.external_columns[0]
                for_table = f" for table: '{column.table}'" if column.table else ""
                raise OptimizeError(f"Column '{column}' could not be resolved{for_table}")
```
Based of the if statement, the scope has `B."col2"` as an external column (which I believe is incorrect), the subquery as uncorrelated (correct) and the scope containing no pivots (also correct).

Below are additional code snippets with the output which are possibly useful for debugging the issue. If you quote "B" or remove `UNION ALL` the validation passes and no error is thrown.

```python3
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify

schema = {
        '' : {
            'table_a' : {
                'col1' : 'INT'
            },
            'table_b' : {
                'col2' : 'INT'
            }
        }
    }

query = """
SELECT *
FROM 
"table_a" as "A"
WHERE "A"."col1" IN (
    SELECT MAX("B"."col2") FROM "table_b" as "B"
    UNION ALL
    SELECT MAX("C"."col2") FROM "table_b" as "C"
);"""

dialect='mysql'
qualify(parse_one(query, dialect=dialect), schema=schema, dialect=dialect)
# Okay, no error thrown if we quote "B"
```
```python3
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify

schema = {
        '' : {
            'table_a' : {
                'col1' : 'INT'
            },
            'table_b' : {
                'col2' : 'INT'
            }
        }
    }

query = """
SELECT *
FROM 
"table_a" as "A"
WHERE "A"."col1" IN (
    SELECT MAX(B."col2") FROM "table_b" as "B"
);"""

dialect='mysql'
qualify(parse_one(query, dialect=dialect), schema=schema, dialect=dialect)
# Okay, without UNION ALL there is no need to quote "B".
```

Thank you for the help, please let me know if there is any other information that I can provide.

**Comment by georgesittas** [comment]
FYI @derekpaulsen I think your schema and quotes were off in this bug report: you need backticks for identifier delimiters AFAIK and the schema doesn't need the empty strings (it's probably incorrect, but would need to double-check if it is). Here's how I'd test it:

```python
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify

schema = {
    "table_a" : {"col1" : "INT"},
    "table_b" : {"col2" : "INT"},
}

query = """
SELECT *
FROM `table_a` AS `A`
WHERE `A`.`col1` IN (
  SELECT MAX(`B`.`col2`) FROM `table_b` AS `B`
  UNION ALL
  SELECT MAX(`C`.`col2`) FROM `table_b` AS `C`
)
"""

expr = parse_one(query, read="mysql")
print(qualify(expr, dialect="mysql", schema=schema))
```
