### ISSUE TITLE
T-SQL string concatenation using '+' not translated to CONCAT in other dialects

### ISSUE THREAD

**Issue by joshnatis** [tobymao/sqlglot#2881]
Hello there, hope you're doing well. Firstly thank you so much for this amazing library, it's basically magical haha.

T-SQL supports string concatenation via the '+' operator, for example `SELECT month + '-' + year` or `SELECT 'hello' + 'world'`. See: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/string-concatenation-transact-sql?view=sql-server-ver16

This is not supported in the dialects I'm translating to, such as MySQL and TrinoSQL. For example, in TrinoSQL (within AWS Athena), when running `SELECT 'hello' + 'world'`, I get the error:
> TYPE_MISMATCH: line 1:16: Cannot apply operator: varchar(5) + varchar(5)

A reproducer:
```python
import sqlglot

query = sqlglot.transpile("SELECT 'hello' + 'world'",
    read="tsql", write='trino')[0]
print(query)
```
>SELECT 'hello' + 'world'

I tried with every dialect:
```python
import sqlglot

query = "SELECT month + '-' + year"

dialects = [
        'bigquery',
        'clickhouse',
        'databricks',
        'doris',
        'drill',
        'duckdb',
        'hive',
        'mysql',
        'oracle',
        'postgres',
        'presto',
        'redshift',
        'snowflake',
        'spark',
        'spark2',
        'sqlite',
        'starrocks',
        'tableau',
        'teradata',
        'trino',
        'tsql',
]

print('Original\t', query)
for dialect in dialects:
        query2 = sqlglot.transpile(query, read="tsql", write=dialect)[0]
        print(f'{dialect}\t', query2)
```
> Original         SELECT month + '-' + year
> bigquery         SELECT month + '-' + year
> clickhouse       SELECT month + '-' + year
> databricks       SELECT month + '-' + year
> doris    SELECT month + '-' + year
> drill    SELECT month + '-' + year
> duckdb   SELECT month + '-' + year
> hive     SELECT month + '-' + year
> mysql    SELECT month + '-' + year
> oracle   SELECT month + '-' + year
> postgres         SELECT month + '-' + year
> presto   SELECT month + '-' + year
> redshift         SELECT month + '-' + year
> snowflake        SELECT month + '-' + year
> spark    SELECT month + '-' + year
> spark2   SELECT month + '-' + year
> sqlite   SELECT month + '-' + year
> starrocks        SELECT month + '-' + year
> tableau  SELECT month + '-' + year
> teradata         SELECT month + '-' + year
> trino    SELECT month + '-' + year
> tsql     SELECT month + '-' + year

Thinking about it now, I'm guessing it may be impossible in many contexts to determine whether a field is a string or some other type. But in some cases it should be possible to translate right, e.g. when we're adding string literals?

Thanks in advance for your time in considering this, and please let me know if I can provide any further information.

**Comment by joshnatis** [comment]
Hi Toby, thanks for the super quick answer! That is nifty, apologies if I missed that in the documentation.

That only handles string literals though, right? In the case of concatenating string fields, or string fields in literals, it doesn't seem to help:
```python
from sqlglot import parse_one
from sqlglot.optimizer.annotate_types import annotate_types
from sqlglot.optimizer.canonicalize import canonicalize

query = "SELECT (month + '-' + year) FROM calendar"
canonicalize(annotate_types(parse_one(query))).sql()
```
> SELECT (month + '-' + year) FROM calendar

(Sorry if that aspect wasn't clear in my original issue, I realize I scuffed the queries a bit)

Thanks

**Comment by tobymao** [comment]
try using qualify_columns and pass in a schema.
