### ISSUE TITLE
T-SQL 'STR' function not translated in other dialects

### ISSUE THREAD

**Issue by joshnatis** [tobymao/sqlglot#2882]
Hi there, thank you for again for this great library. To be clear, I'm filing this issue in hopes of improving the project, not for free tech support : P (I feel bad for filing multiple issues).

T-SQL supports a `STR` function, which "returns character data converted from numeric data. The character data is right-justified, with a specified length and decimal precision". See https://learn.microsoft.com/en-us/sql/t-sql/functions/str-transact-sql?view=sql-server-ver16

Example usage:
```sql
SELECT STR(5.58943, 10, 2)
```
> `      5.59`

This function is not supported in the dialects I'm translating to, such as MySQL and Trino. However, sqlglot seems to leave `STR` intact:

```python
import sqlglot

for dialect in ['mysql', 'trino']:
    query = sqlglot.transpile('SELECT STR(5.58943, 10, 2)', read='tsql', write=dialect)[0]
    print(f'{dialect}:\t{query}')
```
> `mysql:  SELECT STR(5.58943, 10, 2)`
> `trino:  SELECT STR(5.58943, 10, 2)`

I think the closest equivalent in Trino and MySQL is the `FORMAT` function:
- https://trino.io/docs/current/functions/conversion.html#format
- https://www.w3schools.com/sql/func_mysql_format.asp

The MySQL function is not powerful enough, it only deals with the decimal portion. The Trino function accepts a format string so I think it should be a possible replacement?

Thanks in advance for your time

**Comment by tobymao** [comment]
hey @joshnatis, thanks for the issue report. 

transpilation is difficult, especially if certain engines implement nuanced functions. certain functions may not be able to be transpiled, and so we leave the in tact. if you do come up with a way to transpile them, then it could probably be done.

as currently stated, we have no plans to implement this, but if you're willing, we're happy to help you make a PR and implement this.

**Comment by joshnatis** [comment]
Hey Toby, thanks for taking a look, appreciate your time. I'd like to help implement this at some point in the future when I have the time : )
