### ISSUE TITLE
T-SQL `LEN` function accepts integers, should cast argument as varchar when translating to `LENGTH` in Trino

### ISSUE THREAD

**Issue by joshnatis** [tobymao/sqlglot#2885]
Hi there! I'm back with one more T-SQL issue, hope this is not too annoying...

T-SQL's `LEN` function returns the length of a string. I found that when it is given an integer argument, it treats it as a string and returns its length.

### tsql

For example:
![image](https://github.com/tobymao/sqlglot/assets/31445542/8ee5546a-6cd1-4a57-aa7b-836867e9c1b5)

### trino
On the other hand, the `LENGTH` function in Trino throws an error when given an integer:
```sql
SELECT LENGTH(1052)
```
> FUNCTION_NOT_FOUND: line 1:8: Unexpected parameters (integer) for function length. Expected: length(varchar(x)), length(char(x)), length(varbinary)

### transpilation

```python
import sqlglot

query = sqlglot.transpile("SELECT LEN(1052)", read="tsql", write="trino")[0]
print(query)
```
> `SELECT LENGTH(1052)`

If we added a `CAST ... AS VARCHAR` to the transpilation then it seems to me we could have parity with T-SQL's behavior.

### documentation

This behavior is **NOT** documented in the official documentation, I don't see it in https://learn.microsoft.com/en-us/sql/t-sql/functions/len-transact-sql?view=sql-server-ver16. I do see it in https://www.tutorialspoint.com/sql/sql-string-functions-len.htm, though of course that is not an authoritative source.

The same seems to be true of MySQL, its [official documentation for its `LENGTH` function](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_length) doesn't mention that it accepts integer arguments, but it does, at least in 8.0.34.

Trino's documentation looks similar to MSSQL and MySQL, it just mentions strings https://trino.io/docs/current/functions/string.html#length

Thank you again for your time in fielding these issues

**Comment by joshnatis** [comment]
Wow that turnaround time!! Haha. Thanks for looking at this Toby :)

**Comment by tobymao** [comment]
you're welcome!
