### ISSUE TITLE
Parse ALTER TABLE .. ALTER [COLUMN] COMMENT (Snowflake)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#2889]
```python
sqlglot.parse_one("""ALTER TABLE ingredients ALTER amount COMMENT 'tablespoons' """, read="snowflake")
```
> 'ALTER TABLE ingredients ALTER amount COMMENT 'tablespoons'' contains unsupported syntax. Falling back to parsing as a 'Command'.
> Command(this=ALTER, expression=TABLE ingredients ALTER amount COMMENT 'tablespoons')

https://docs.snowflake.com/en/sql-reference/sql/alter-table-column

**Comment by tobymao** [comment]
@tekumara if you have more of these their generally pretty easy, would appreciate if you would submit some pr's yourself, thanks!
