### ISSUE TITLE
Support for STRUCT/ROW type

### ISSUE THREAD

**Issue by bobvanratingen** [tobymao/sqlglot#289]
Is it possible to have the STRUCT type working in combination with the optimizer?

```
WITH
  cte_1 AS (
    SELECT
      STRUCT(4 AS a, 5 AS b) AS field
  )
SELECT
  field.a
FROM
  cte_1
```

refs:

https://duckdb.org/docs/sql/data_types/struct#creating-structs-with-the-row-function
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#constructing_a_struct
https://prestodb.io/docs/current/language/types.html#row

**Comment by tobymao** [comment]
sorry but i'm going to close this one for now, the hard part with this is that i have to understand that field is a struct and carry that throughout the stack. we can maybe revisit this when we start understanding types more

**Comment by masterlittle** [comment]
Is it possible to revisit this if the types support has matured?

**Comment by georgesittas** [comment]
I think this works already:

```python
>>> print(optimize(sql).sql(pretty=True))
WITH "cte_1" AS (
  SELECT
    STRUCT(4 AS "a", 5 AS "b") AS "field"
)
SELECT
  "cte_1"."field"."a" AS "a"
FROM "cte_1" AS "cte_1"
```
