### ISSUE TITLE
Failed to parse BigQuery create procedure statement

### ISSUE THREAD

**Issue by nadav-botanica** [tobymao/sqlglot#2890]
Hello,

I'm trying to use sqlglot to parse a create procedure statement in big query syntax.

The query in question is:

`
CREATE OR REPLACE PROCEDURE mydataset.create_customer()
BEGIN
  DECLARE id STRING;
  SET id = GENERATE_UUID();
  INSERT INTO mydataset.customers (customer_id)
    VALUES(id);
  SELECT FORMAT("Created customer %s", id);
END
`

However, I get the following AST for it:

`
Create(
  this=UserDefinedFunction(
    this=Dot(
      this=Identifier(this=mydataset, quoted=False),
      expression=Identifier(this=create_customer, quoted=False)),
    wrapped=True),
  kind=PROCEDURE,
  replace=True,
  expression=Command(this=BEGIN, expression=DECLARE id STRING),
  exists=False)
`

The stored procedure here is taken directly from the docs of big query [here](https://cloud.google.com/bigquery/docs/procedures).

It appears that I only get a truncated body for the stored procedure, and that the body is stored in the Command class, as a raw string.
Is this the expected behaviour? What kind of stored procedures parsing is supported, and which sub-items should appear?

Thanks in advance, Nadav

**Comment by tobymao** [comment]
i don't see any truncation. parsing procedures into raw strings is expected because full parsing isn't implemented. 

you're welcome to contribute that if you like, but we are not planning to do that in the immediate future.
