### ISSUE TITLE
"position" function getting transpiled to "str_position" for multiple dialects while using parse function

### ISSUE THREAD

**Issue by ayushbindlish** [tobymao/sqlglot#2894]
position function is being transpiled to str_position for multiple dialects.

**PSQL Error:**

```
localhost:5433 dpg_user@testglue=# SELECT DISTINCT C1, SUM(C1), C9, COUNT(DISTINCT C9), C10, SUM(DISTINCT EXTRACT(year FROM C11)) + 1 FROM testglue.dpe2e.duplicate_data_withoutnull_2 WHERE C1 > C3 AND STR_POSITION(C8, LOWER('A')) > 0 GROUP BY C1, C9, C10;
ERROR:  42883: function str_position(text, text) does not exist
LINE 1: ...2e.duplicate_data_withoutnull_2 WHERE C1 > C3 AND STR_POSITI...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
LOCATION:  ParseFuncOrColumn, parse_func.c:629
Time: 0.361 ms
```

```python
from sqlglot import parse_one

sql_query = "select distinct C1, sum(C1), C9, count(distinct C9), C10, sum(distinct extract(year from C11)) + 1 from testglue.dpe2e.duplicate_data_withoutnull_2 where C1 > C3 and position(lower('A') in C8) > 0 group by C1, C9, C10;"
print(f"Input Query: {sql_query}\n\n")
parsed_query = parse_one(sql_query, read="postgres").sql()
print(f"Parsed Query (PG): {parsed_query}\n\n")

parsed_query = parse_one(sql_query, read="databricks").sql()
print(f"Parsed Query (DB): {parsed_query}\n\n")

parsed_query = parse_one(sql_query, read="oracle").sql()
print(f"Parsed Query (oracle): {parsed_query}\n\n")

parsed_query = parse_one(sql_query, read="mysql").sql()
print(f"Parsed Query (MSQL): {parsed_query}\n\n")
```

**Output:**

Input Query: select distinct C1, sum(C1), C9, count(distinct C9), C10, sum(distinct extract(year from C11)) + 1 from testglue.dpe2e.duplicate_data_withoutnull_2 where C1 > C3 and position(lower('A') in C8) > 0 group by C1, C9, C10;

Parsed Query (PG): SELECT DISTINCT C1, SUM(C1), C9, COUNT(DISTINCT C9), C10, SUM(DISTINCT EXTRACT(year FROM C11)) + 1 FROM testglue.dpe2e.duplicate_data_withoutnull_2 WHERE C1 > C3 AND STR_POSITION(C8, LOWER('A')) > 0 GROUP BY C1, C9, C10

Parsed Query (DB): SELECT DISTINCT C1, SUM(C1), C9, COUNT(DISTINCT C9), C10, SUM(DISTINCT EXTRACT(year FROM C11)) + 1 FROM testglue.dpe2e.duplicate_data_withoutnull_2 WHERE C1 > C3 AND STR_POSITION(C8, LOWER('A')) > 0 GROUP BY C1, C9, C10

Parsed Query (oracle): SELECT DISTINCT C1, SUM(C1), C9, COUNT(DISTINCT C9), C10, SUM(DISTINCT EXTRACT(year FROM C11)) + 1 FROM testglue.dpe2e.duplicate_data_withoutnull_2 WHERE C1 > C3 AND STR_POSITION(C8, LOWER('A')) > 0 GROUP BY C1, C9, C10

Parsed Query (MSQL): SELECT DISTINCT C1, SUM(C1), C9, COUNT(DISTINCT C9), C10, SUM(DISTINCT EXTRACT(year FROM C11)) + 1 FROM testglue.dpe2e.duplicate_data_withoutnull_2 WHERE C1 > C3 AND STR_POSITION(C8, LOWER('A')) > 0 GROUP BY C1, C9, C10

**SQLGlot Commit Used:**
`-e git+ssh://git@github.com/tobymao/sqlglot.git@5fc7791a4d19d704c0d4fafe8924cf8f76fcb867#egg=sqlglot`

**Edit:**
Just figured that even the sql function takes a dialect. But how to only parse and not transpile?

```
from sqlglot import parse_one
sql_query = "select distinct C1, sum(C1), C9, count(distinct C9), C10, sum(distinct extract(year from C11)) + 1 from testglue.dpe2e.duplicate_data_withoutnull_2 where C1 > C3 and position(lower('A') in C8) > 0 group by C1, C9, C10;"
print(f"Input Query:\n {sql_query}\n\n")
parsed_query = parse_one(sql_query, read="postgres").sql("postgres")
print(f"Parsed Query (PG):\n {parsed_query}\n\n")
```

```
Input Query:
 select distinct C1, sum(C1), C9, count(distinct C9), C10, sum(distinct extract(year from C11)) + 1 from testglue.dpe2e.duplicate_data_withoutnull_2 where C1 > C3 and position(lower('A') in C8) > 0 group by C1, C9, C10;


Parsed Query (PG):
 SELECT DISTINCT C1, SUM(C1), C9, COUNT(DISTINCT C9), C10, SUM(DISTINCT EXTRACT(year FROM C11)) + 1 FROM testglue.dpe2e.duplicate_data_withoutnull_2 WHERE C1 > C3 AND STRPOS(C8, LOWER('A')) > 0 GROUP BY C1, C9, C10

```

**Comment by georgesittas** [comment]
You need to set the correct [output dialect](https://github.com/tobymao/sqlglot#faq), like you said in your edit. I'm not sure what you mean by "how to only parse", but if you only use `parse_one` then you can view the AST with `repr`.

**Comment by ayushbindlish** [comment]
@georgesittas I do not want `parse_one` to change `position` function to `strpos` function. How can I achieve that?

**Comment by ayushbindlish** [comment]
@georgesittas I have a custom sql engine which only supports position function. So I would like the function to be retained in the query. This sql engine conforms to a subset of calcite features and as there is no specific dialect for calcite, I do not know to to achieve the above without writing a new dialect.
