### ISSUE TITLE
T-SQL `LEFT` and `RIGHT` functions accept integers, should cast arguments as varchar when translating to Trino

### ISSUE THREAD

**Issue by joshnatis** [tobymao/sqlglot#2899]
Hi Toby and friends. This is a very similar issue to https://github.com/tobymao/sqlglot/issues/2885, except regarding the `LEFT` and `RIGHT` functions instead of the `LEN` function.

## T-SQL

![image](https://github.com/tobymao/sqlglot/assets/31445542/fbdf9de6-b146-43dc-8779-209fcf3596f5)

As seen above, T-SQL accepts non-varchar data as arguments for its `LEFT` and `RIGHT` functions. The documentation explicitly documents this this time:

https://learn.microsoft.com/en-us/sql/t-sql/functions/left-transact-sql?view=sql-server-ver16

> LEFT ( character_expression , integer_expression )  
>
> character_expression
Is an expression of character or binary data. character_expression can be a constant, variable, or column. **character_expression can be of any data type, except text or ntext, that can be implicitly converted to varchar or nvarchar**. Otherwise, use the CAST function to explicitly convert character_expression.

## Trino
```sql
query = sqlglot.transpile("SELECT RIGHT(123456, 2)", read="tsql", write="trino")[0]
print(query)
```
> `SELECT SUBSTRING(123456, LENGTH(123456) - (2 - 1))`

Running the translated result in AWS Athena, we get:
> FUNCTION_NOT_FOUND: line 1:26: Unexpected parameters (integer) for function length. Expected: length(varchar(x)), length(char(x)), length(varbinary)

We need to cast the argument for `LENGTH` in order to support the specification

Thanks, still hope this isn't too annoying. I'm dealing with a large codebase of MSSQL queries, so that's why I keep coming back with issues :). But it's actually quite magical to see how almost everything works without requiring modifications

**Comment by tobymao** [comment]
@joshnatis would appreciate it if you took the time to learn the code base to do these easy transpilations in the future. that way you can become a contributor! happy to help :)

**Comment by joshnatis** [comment]
@tobymao noted! I’ll study the changes you made when closing out these issues, thanks for the encouragement
