### ISSUE TITLE
create table transpile snowflake to duckdb fails with autoincrement

### ISSUE THREAD

**Issue by tharwan** [tobymao/sqlglot#2900]
**Fully reproducible code snippet**
```python
sqlglot.transpile(
  "CREATE TABLE testtable ( id_col INTEGER AUTOINCREMENT NOT NULL, val_col INTEGER, PRIMARY KEY (id_col))", 
read="snowflake", write="duckdb")
# >>>  ['CREATE TABLE testtable (id_col INT AUTO_INCREMENT NOT NULL, val_col INT, PRIMARY KEY (id_col))']
duckdb.sql('CREATE TABLE testtable (id_col INT NOT NULL, val_col INT, PRIMARY KEY (id_col))')
# >>>ParserException: Parser Error: syntax error at or near "AUTO_INCREMENT"
```

**Official Documentation**
DuckDB probably needs to create a sequence: https://duckdb.org/docs/sql/statements/create_sequence.html#using-sequences-for-primary-keys

https://docs.snowflake.com/en/sql-reference/sql/create-table#syntax

**Comment by tobymao** [comment]
it's not clear how you'd do this given duckdb needs an explicit sequence created. if you're interested in contributing this let me know, but we have no plans to do it given it doesn't seem straight forward.

**Comment by tharwan** [comment]
This kind of SQL is probably a little over my head. 

The other thing that maybe could be improved is the error message? So that upstream it is easier to detect that this is not supported?
