### ISSUE TITLE
Cannot parse multiple parameters of clickhouse's JSONExtractString

### ISSUE THREAD

**Issue by echo-hhj** [tobymao/sqlglot#2901]
Implement parsing of multiple parameters in JSONExtractString in clickhouse, as an example ck: SELECT JSONExtractString(eventattr, 'result', 'error', 'res');
mysql: SELECT JSON_EXTRACT(eventattr, '$.result','$.error','$.res').

There are other clickhouse functions such as JSONExtractInt, JSONExtractBool, etc. 

https://clickhouse.com/docs/en/sql-reference/functions/json-functions#jsonextractstringjson-indices_or_keys

**Comment by tobymao** [comment]
parsing of these expressions in clickhouse works as they are anonymous. if you're interested in having first class support of this we're happy to support you. 

please work with us to create a well crafted / thoroughly tested PR. thanks!
