### ISSUE TITLE
UNIQUE column constraint in Teradata removes entire sql when converting to databricks sql

### ISSUE THREAD

**Issue by mgeddam-db** [tobymao/sqlglot#2905]
The keyword UNIQUE used in Teradata as a column constraint deletes the entire sql after running transpile. I'm using the latest sqlglot version. When UNIQUE is commented out, it works fine. 

transpile(sql, read='teradata', write='databricks', pretty=True, error_level=None)

teradata sql = """
CREATE SET TABLE testdb.test_table1 ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     (
     test_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY
           (START WITH 1 
            INCREMENT BY 1 
            MINVALUE 1 
            MAXVALUE 2147483647 
            NO CYCLE),
      test_date TIMESTAMP(0), 
      UNIQUE ( test_ID ), 
PRIMARY KEY ( test_ID )) 
PRIMARY INDEX (test_ID);
"""

returns 

CREATE TABLE  PRIMARY INDEX (test_ID)

[https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Types-and-Literals/SQL-Data-Definition/Uniqueness-Constraints/UNIQUE-Constraint](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Types-and-Literals/SQL-Data-Definition/Uniqueness-Constraints/UNIQUE-Constraint)

**Comment by tobymao** [comment]
i'm not sure i see the issue, make sure to use the latest version of sqlglot
