### ISSUE TITLE
simplify function does not work properly for sql snippets in 20.11.0

### ISSUE THREAD

**Issue by git-xp** [tobymao/sqlglot#2906]
Here is a simple example
```
import sqlglot
from sqlglot.optimizer.simplify import simplify

expr = "IF 'YES' = 'YES' THEN ABC END"
simplified_expr = simplify(sqlglot.parse_one(expr, "snowflake")).sql("snowflake")
print(simplified_expr)
```
on sqlglot 20.10.0
it generates the correct output:
```
ABC
```
while on latest 20.11.0
it complains 
`'IF 'YES' = 'YES' THEN ABC END' contains unsupported syntax. Falling back to parsing as a 'Command'.`
and generates the original sql
```
IF 'YES' = 'YES' THEN ABC END
```
instead  of `ABC`.

**Comment by tobymao** [comment]
this is not really sql, it's more snowflake scripting language, so simplification is not in scope

**Comment by git-xp** [comment]
The cause seems from the changing behavior of parsing sql snippets. 
on 20.10.0
```
import sqlglot
sqlglot.parse_one("IF 'YES' = 'YES' THEN ABC END", "snowflake")
```
produces
```
If(
  this=EQ(
    this=Literal(this=YES, is_string=True),
    expression=Literal(this=YES, is_string=True)),
  true=Column(
    this=Identifier(this=ABC, quoted=False)))
```
and on 20.11.0
it produces
```
Command(this=IF, expression='YES' = 'YES' THEN ABC END)
```

**Comment by tobymao** [comment]
right, because anything can go in if then statements, it's safer to parse them as commands
