### ISSUE TITLE
bug: `unnest_sql` hits errors when the alias is the 'Identifier' object and it has no attribute 'columns'

### ISSUE THREAD

**Issue by chelsea-lin** [tobymao/sqlglot#2907]
**Fully reproducible code snippet**
This bug is minor and can be fixed by checking the `alias` object has the `columns` attribute before calling it. When the `alias` is a `sqlglot.expressions.Identifier`, the exception would be triggered. Here is the call stacks:

<img width="1171" alt="Screenshot 2024-02-01 at 4 17 12 PM" src="https://github.com/tobymao/sqlglot/assets/124939984/23fd4037-dff6-402c-a457-6ff0a72b75db">

**Comment by tobymao** [comment]
i don't believe alias can be an identifier by natural means (using the parser). so i'm going to close this for now. if you can show me a test case where unnest alias is an identifier, we should fix that instead.

**Comment by chelsea-lin** [comment]
Hi @tobymao, thank you to look at the issue. 
I'm using `sqlglot` within [ibis](https://github.com/ibis-project/ibis) to generate BigQuery SQL with a `UNNEST` node. Below are the mininum codes to repro the issue within `sqlglot` only. I think I might be creating an `UNNEST` object incorrectly. Any insights would be greatly appreciated!

```
In [23]: unnest=sg.parse_one("UNNEST(array_types.x)")
    ...: alias = sg.to_identifier("t0")
    ...: 

In [24]: sg.expressions.Unnest(expressions=[unnest], offset=None).as_(alias).sql()
Out[24]: 'UNNEST(UNNEST(array_types.x)) AS t0'

In [25]: sg.expressions.Unnest(expressions=[unnest], offset=None).as_(alias).sql(dialect="bigquery")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[25], line 1
----> 1 sg.expressions.Unnest(expressions=[unnest], offset=None).as_(alias).sql(dialect="bigquery")

File ~/src/forkibis/venv/lib/python3.11/site-packages/sqlglot/expressions.py:528, in Expression.sql(self, dialect, **opts)
    516 """
    517 Returns SQL string representation of this tree.
    518 
   (...)
    524     The SQL string.
    525 """
    526 from sqlglot.dialects import Dialect
--> 528 return Dialect.get_or_raise(dialect).generate(self, **opts)

File ~/src/forkibis/venv/lib/python3.11/site-packages/sqlglot/dialects/dialect.py:450, in Dialect.generate(self, expression, copy, **opts)
    449 def generate(self, expression: exp.Expression, copy: bool = True, **opts) -> str:
--> 450     return self.generator(**opts).generate(expression, copy=copy)

File ~/src/forkibis/venv/lib/python3.11/site-packages/sqlglot/generator.py:475, in Generator.generate(self, expression, copy)
    472 expression = self.preprocess(expression)
    474 self.unsupported_messages = []
--> 475 sql = self.sql(expression).strip()
    477 if self.pretty:
    478     sql = sql.replace(self.SENTINEL_LINE_BREAK, "\n")

File ~/src/forkibis/venv/lib/python3.11/site-packages/sqlglot/generator.py:629, in Generator.sql(self, expression, key, comment)
    626 exp_handler_name = f"{expression.key}_sql"
    628 if hasattr(self, exp_handler_name):
--> 629     sql = getattr(self, exp_handler_name)(expression)
    630 elif isinstance(expression, exp.Func):
    631     sql = self.function_fallback_sql(expression)

File ~/src/forkibis/venv/lib/python3.11/site-packages/sqlglot/generator.py:2128, in Generator.unnest_sql(self, expression)
   2126 # TODO(chelsealin): and hasattr(alias, 'columns') 
   2127 if alias and self.dialect.UNNEST_COLUMN_ONLY:
-> 2128     columns = alias.columns
   2129     alias = self.sql(columns[0]) if columns else ""
   2130 else:

AttributeError: 'Identifier' object has no attribute 'columns'
```

Besides, I am trying to understand how the `sqlglot` handles [correlated joins](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#correlated_join) within its `unnest` API. If possible, a simple example would be very helpful. In BigQuery, the `unnest` column can be `cross join` or `left join` by the column table.

**Comment by tobymao** [comment]
in the future, please file issues with fully reproducible code snippets, that will help. in this case, the as_ for an unnest needs to happen with table=True, you need to try to match the ast built by the parser.
