### ISSUE TITLE
Count distinct syntax error while transpiling to trino sql

### ISSUE THREAD

**Issue by Jake-00** [tobymao/sqlglot#2930]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
```python
import sqlglot

sql = """
with tbl as (
	select 1 as id, 'eggy' as name
	union all
	select null as id, 'jake' as name
)
select count(distinct id, name) as cnt from tbl
"""
sqlglot.transpile(sql, read="hive", write="trino")[0]
```

**Details**
The result of code sinppet is ⬇️ 
```
"WITH tbl AS (SELECT 1 AS id, 'eggy' AS name UNION ALL SELECT NULL AS id, 'jake' AS name) SELECT COUNT(DISTINCT id, name) AS cnt FROM tbl"
```
and I run this sql in the trino cli, it would raise error below, as I konwn that trino/presto dose not support syntax `count(distinct col_1, col_2, ...)` but for wrapping multi-columns into **row** type like `count(distinct (col_1, col_2, ...))`.
<img width="808" alt="image" src="https://github.com/tobymao/sqlglot/assets/60967034/82f76a45-1519-401a-9133-b749317ba0d5">

**Comment by georgesittas** [comment]
These two queries don't look equivalent:

Spark:
```
spark-sql (default)> WITH tbl AS (SELECT 1 AS id, 'eggy' AS name UNION ALL SELECT NULL AS id, 'jake' AS name) SELECT COUNT(DISTINCT id, name) AS cnt FROM tbl;
1
```

Presto / Trino:
```
presto> WITH tbl AS (SELECT 1 AS id, 'eggy' AS name UNION ALL SELECT NULL AS id, 'jake' AS name) SELECT COUNT(DISTINCT (id, name)) AS cnt FROM tbl;

 cnt 
-----
   2 
(1 row)

**Comment by Jake-00** [comment]
Agree with you @georgesittas , `COUNT(DISTINCT id, name)` would neglect a row containing one more null value. The transpiling SQL below seems more resonable
```sql
WITH tbl AS (SELECT 1 AS id, 'eggy' AS name UNION ALL SELECT NULL AS id, 'jake' AS name) 
SELECT COUNT(DISTINCT 
        CASE 
            WHEN id is null THEN null
            WHEN name is null THEN null
        ELSE (id, name) END
) AS cnt FROM tbl
```

**Comment by Jake-00** [comment]
> Agree with you @georgesittas , `COUNT(DISTINCT id, name)` would neglect a row containing one more null value. The transpiling SQL below seems more resonable
> 
> ```sql
> WITH tbl AS (SELECT 1 AS id, 'eggy' AS name UNION ALL SELECT NULL AS id, 'jake' AS name) 
> SELECT COUNT(DISTINCT 
>         CASE 
>             WHEN id is null THEN null
>             WHEN name is null THEN null
>         ELSE (id, name) END
> ) AS cnt FROM tbl
> ```
Attached below is result running on trino
```
trino> WITH tbl AS (SELECT 1 AS id, 'eggy' AS name UNION ALL SELECT NULL AS id, 'jake' AS name) SELECT COUNT(DISTINCT 
    ->         case 
    ->             when id is null then null
    ->             when name is null then null
    ->         else (id, name) end
    -> ) AS cnt FROM tbl;
 cnt 
-----
   1 
(1 row)
```

**Comment by georgesittas** [comment]
I see, perhaps we can make this transpilation work. I'll take a look at this soon.
