### ISSUE TITLE
Transpiling time spine from snowflake to duckdb is not supported

### ISSUE THREAD

**Issue by daniel769** [tobymao/sqlglot#2933]
Transpile date spine generation from snowflake TABLE(GENERATOR... constructs to RANGE(<date>, <date>, <interval>)
read dialect: "snowflake"

**Fully reproducible code snippet**
input SQL:
```sql
  SELECT
    DATEADD(DAY, SEQ4(), '2016-01-01')::DATE AS DATE_VAL
  FROM
    TABLE(GENERATOR(ROWCOUNT=>365*10))
  WHERE
    DATE_VAL < '2018-01-01'
```

expected output:
```sql
  SELECT CAST(RANGE AS DATE) AS DATE_VAL
  FROM RANGE(DATE '2016-01-01', DATE '2026-01-01', INTERVAL 1 DAY)
  WHERE DATE_VAL  < '2018-01-01'
```

**Official Documentation**
Snowflake:
https://docs.snowflake.com/en/sql-reference/functions/generator
https://docs.snowflake.com/en/sql-reference/functions/seq1
Duckdb:
https://duckdb.org/docs/sql/data_types/interval.html
https://duckdb.org/docs/sql/query_syntax/from.html

**Comment by georgesittas** [comment]
This looks like a very complicated transformation to implement imo and we don't really have the bandwidth to look into it right now, so I'm going to close this as not planned. If you're interested in contributing, feel free to join our [Slack](https://tobikodata.com/slack) and we can chat about possible approaches.
