### ISSUE TITLE
Missing Postgres operators and user-defined operator support

### ISSUE THREAD

**Issue by amacfie-tc** [tobymao/sqlglot#2940]
Some [built-in Postgres operators](https://www.postgresql.org/docs/current/functions.html) aren't recognized, such as [square root](https://www.postgresql.org/docs/current/functions-math.html#:~:text=%E2%86%92%20double%20precision-,Square%20root,-%7C/%2025.0%20%E2%86%92%205), and user-defined operators, which match a pattern [described here](https://www.postgresql.org/docs/current/sql-createoperator.html#:~:text=The-,operator%20name,-is%20a%20sequence) generally aren't  recognized. User-defined operators may be parsed but parsed incorrectly, e.g.
```
>>> print(repr(sqlglot.parse_one("select 3 *** 4", dialect="postgres")))
Select(
  expressions=[
    Mul(
      this=Mul(
        this=Literal(this=3, is_string=False),
        expression=Star()),
      expression=Literal(this=4, is_string=False))])
```

It would be great if all Postgres operators could be parsed, and in such a way that tells the user whether the operator is built-in/recognized or not.

ETA: Parsing fails for unary operators wrapped with `operator(...)`, e.g. `select operator(-) 4`

**Comment by tobymao** [comment]
this issue is unclear, can you put specifically the operators missing? example sql?

i see no reference to x *** y, what does it mean?

**Comment by amacfie-tc** [comment]
Well there are various operators listed at that link that SQLGlot doesn't parse. Rather than listing them all and/or adding them individually as classes, it would be great if anything that is syntactically an operator is at least parsed to something like `Operator` with the operator token as the `operator` arg (although `Operator` currently only applies to binary operators). This way both built-in and user-defined operators are covered.

Based on the above link I'm assuming operators are tokens that appear where an operator can appear and satisfy the requirements
* at least one character
* characters can be <verbatim>+ - * / < > = ~ ! @ # % ^ & | ` ?</verbatim>
* -- and /* cannot appear anywhere 
* A multicharacter operator cannot end in + or -, unless the name also contains at least one of these characters:
  <verbatim>~ ! @ # % ^ & | ` ?</verbatim>
* The symbol => cannot be used as an operator name.

The `***` in `3 *** 4` is an example of what should be parsed as an operator. Even if `***` isn't defined, Postgres knows it's playing the role of an operator:
```
> select 3 *** 4
operator does not exist: integer *** integer
LINE 1: select 3 *** 4
                 ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by tobymao** [comment]
that's not really how the parser works and there's no plan to change that. can you please reframe this issue to specific operators you want implemented that are also supported by postgres?

**Comment by amacfie-tc** [comment]
> that's not really how the parser works and there's no plan to change that

I see. User-defined data types and functions are parsed usefully so I though operators could be too.

**Comment by amacfie-tc** [comment]
If anyone's interested, the parser https://github.com/wseaton/sqloxide also doesn't recognize user-defined operators but at least it raises an exception rather than misparsing e.g. `select 3 *** 4`
