### ISSUE TITLE
Oracle syntax with (+) operator not supported

### ISSUE THREAD

**Issue by streamnsight** [tobymao/sqlglot#2949]
**Is your feature request related to a problem? Please describe.**
I'm trying to convert Oracle syntax to more ANSI SQL, like:
```
sql = "SELECT * FROM A, B WHERE A.ID = B.ID(+)"
ast = parse_one(sql, read='oracle')
ast.sql()
```
and I run into the warning:
`Outer join syntax using the (+) operator is not supported.`

If I don't specify the dialect, it happily ignores the (+), but I guess that changes the query.

So what is a good way to parse / replace this type of query?
How much work would it be to implement? I'm no expert here, but happy to try to contribute if I can.

**Comment by tobymao** [comment]
no plans yet to implement this conversion

**Comment by streamnsight** [comment]
@tobymao 
I get that's it's not implemented and not on the roadmap. I'm curious what it would take to implement. Is it complicated? What's involved? I'm guessing it's not trivial, but maybe I can work on it.
I have 10's of 1000's of queries to parse that I'd like to use this for. I'd like to understand where to start to implement this support.
Thanks

**Comment by tobymao** [comment]
it’s quite complicated to handle all cases correctly like multiple joins, and documentation is not great and we don’t have oracle to test. if you’re interested in implementing it we’re more than happy to help guide you.

reach out to us on slack tobikodata.com/slack
