### ISSUE TITLE
tableau dialect parsing issue

### ISSUE THREAD

**Issue by git-xp** [tobymao/sqlglot#2950]
Hi there, it appears that tableau dialect is not correctly supported.
its tokenizer is using  double quotes for identifiers and single quote for literals, based on the [tableau documentation](https://help.tableau.com/current/pro/desktop/en-us/functions_operators.htm#:~:text=A%20string%20literal%20can%20be,type%20%22%27cat%27%22%20.) here 

tableau uses `[]` for identifiers and uses both double and single quotes for literals and `#` for date literals.

also it would be great to support [ElSEIF](https://help.tableau.com/current/pro/desktop/en-us/functions_all_alphabetical.htm#ELSEIF) function in this dialect as well.

**Comment by tobymao** [comment]
PRs appreciated.

**Comment by tobymao** [comment]
i've added quotes and identifiers for tabelau, feel free to contribute elseif if you need it
