### ISSUE TITLE
Hiveconf variable parsing does not succeed

### ISSUE THREAD

**Issue by travis-cook-sfdc** [tobymao/sqlglot#2958]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
```
from sqlglot import parse, exp

sql = """
set src_table=dw.foo;
set dest_table=dw.bar; 

insert overwrite table ${hiveconf:dest_table}
partition (ds='2024-01-01')
select
    bat
    , baz
from
    ${hiveconf:src_table};
"""


parsed = parse(sql, read='hive')
for query in parsed:
    for table in query.find_all(exp.Table):
        print(table.name)
```

Expected output:
```
dw.foo
dw.bar
```

Actual Output:
```
hiveconf
hiveconf
```

**Official Documentation**
https://sparkbyexamples.com/apache-hive/how-to-set-variables-in-hive-scripts/

**Notes**

This is similar to #2464, though that example had a create table statement.  #2464 has regressed though, so the fix there does not work anymore either.

**Comment by tobymao** [comment]
there's no plans to support this substitution at parse time, it looks like the params are parsed correctly, so you should be able to perform this transform yourself.

**Comment by travis-cook-sfdc** [comment]
Totally understand - sqlglot's responsibility isn't really to be able to parse and translate variables across multiple statements.

That being said, I'm struggling to figure out how to transform this specific example.

I was able keep track of the variables across statements like this:
```
statements = parse(sql, read="hive")
hive_vars = {}
for query in parsed:
   if isinstance(statement, sqlglot.expressions.Set):
      # Determine set expressions and store any variables being set
      for expression in statement.expressions:
          if isinstance(expression, sqlglot.expressions.SetItem):
              hive_variables[str(expression.this.left)] = str(
                  expression.this.right
              )
      continue
```

And then I thought I could take the statements and transform them like this:
```
def transform(node):
    if isinstance(node, sqlglot.expressions.Parameter):
         return parse_one(hive_variables[node.expression.name])
    return node
```

This hasn't worked since `parse_one("dw.foo")` returns:
```
Column(
  this=Identifier(this=foo, quoted=False),
  table=Identifier(this=dw, quoted=False))
```

Whereas the interpolated version of the statement returns:
```
this=Table(
    this=Identifier(this=foo, quoted=False),
    db=Identifier(this=dw, quoted=False)),
```

Do you have any suggestions on how to perform this transform correctly given the type of the value is unknown

**Comment by tobymao** [comment]
you can construct the proper ast using sqlglot's expression builders, for example

exp.table_("foo", "dw")
or exp.to_table("dw.foo")

does that answer your question?

**Comment by travis-cook-sfdc** [comment]
This was what I ended up with, but I'm not sure if it's the best way:

```python
def replace_variables(sql: str, variables: dict[str, str]) -> str:
    for variable_name, variable_value in variables.items():
        sql = sql.replace(f"${{hiveconf:{variable_name}}}", variable_value)
    return sql
```

And then do a pure string replacement before parsing:
```python
sql = replace_variables(sql, hive_variables)
statement = parse_one(
    sql, read='hive'
)
```

**Comment by travis-cook-sfdc** [comment]
Ah I see.  That makes sense for this specific use case, but unfortunately I'm trying to work with parsing all sorts of SQL that could use those variables in both table contexts as well as other contexts (path locations, column names, etc)

The best solution I've come up with for now is to mutate the raw string before parsing:

```python
def replace_variables(sql: str, variables: dict[str, str]) -> str:
    for variable_name, variable_value in variables.items():
        sql = sql.replace(f"${{hiveconf:{variable_name}}}", variable_value)
    return sql

...
sql = replace_variables(sql, hive_variables)
statement =parse_one(
    sql, read="hive"
)

```

**Comment by tobymao** [comment]
how do you know what the the type of "set" is going to be? i'd say that the approach of parsing the SQL after replacement makes a lot of sense.

templates IS NOT SQL, it only becomes valid sql after replacement.
