### ISSUE TITLE
Hive Multiple Insert Fails to Parse

### ISSUE THREAD

**Issue by travis-cook-sfdc** [tobymao/sqlglot#2959]
**Fully reproducible code snippet**
```
from sqlglot import parse

sql = """
WITH foo AS (
    SELECT 1 AS col_1
        , 2 AS col_2
    FROM dw.foo
)
FROM foo
INSERT OVERWRITE TABLE dw.bar_1
PARTITION(ds='2024-01-01')
SELECT col_1
    , col_2
WHERE col_1 >= 0

INSERT OVERWRITE TABLE dw.bar_2
PARTITION(ds='2024-01-01')
SELECT col_1
    , col_2
WHERE col_1 < 0;

"""


parsed = parse(sql, read='hive')
````

This currently raises an exception, but is valid Hive SQL.

**Official Documentation**
This links to a specific bullet in this doc, but see the example above this bullet with multiple inserts.

https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DML#:~:text=Multiple%20insert%20clauses%20(also%20known%20as%20Multi%20Table%20Insert)%20can%20be%20specified%20in%20the%20same%20query.

**Comment by georgesittas** [comment]
Thanks for the report, will take a look soon.

**Comment by georgesittas** [comment]
We don't plan to add support for this as the syntax spec is relatively complex and very specific to Hive (it's an extension).

**Comment by travis-cook-sfdc** [comment]
understandable.  Agreed that this syntax is absolutely wild and very non-standard.  I'll work with the team of folks writing SQL this way to stop using this pattern.
