### ISSUE TITLE
Support detection of BOOLEAN literals

### ISSUE THREAD

**Issue by adamf** [tobymao/sqlglot#296]
In trying to transpile sqlite to postgres, I noticed that boolean literals are not being correctly identified.

For example, given column `foo` of type `BOOLEAN`, this is valid in sqlite:

`SELECT foo FROM tablename WHERE foo IN (1, 0)`

The same is not valid in Postgres, as Postgres doesn't allow literal 1 or 0 to be true or false (Postgres does accept the characters `'1'` and `'0'`). 

sqlglot currently will transpile this statement without changing the literals.

I looked at the code but didn't see how to do this sort of type mapping correctly.

**Comment by tobymao** [comment]
sqlglot transpiler doesn't really support types. at the moment. we have some form of a type schema in the optimizer, but it's not going to do what you want. what would the valid postgresql be for this translation?

i'm not sure i can build this into sqlglot today, but i can probably help you write something for your specific use case.

**Comment by adamf** [comment]
I've got this table in sqlite:

```
CREATE TABLE IF NOT EXISTS "MAEEADP_Facility" (
	"index" BIGINT,
	"Active" BOOLEAN,
	"FacilityName" TEXT,
	"FacilityType" TEXT,
	"Id" BIGINT,
	"Program" TEXT,
	"ProgramSpecificId" TEXT,
	"StreetName" TEXT,
	"Town" TEXT,
	CHECK ("Active" IN (0, 1))
);
```

And that `CHECK` constraint isn't valid in Postgres; it would be if it was:
```
	CHECK ("Active" IN ('0', '1'))
```

The tree looks like:
```
(IN this:
  (COLUMN this:
    (IDENTIFIER this: active, quoted: True)), expressions:
  (LITERAL this: 0, is_string: False),
  (LITERAL this: 1, is_string: False))
```

Would love any help!

**Comment by tobymao** [comment]
this would be better solved by doing 

def transform(node):
   if isinstance(node, exp.In):
        node.this.expressions = [exp.Literal.string(e.name) e in for node.this.expressions]
   return this

sqlglot.parse_one(sql).transform(transform)

**Comment by adamf** [comment]
I'm a bit confused by this code - it doesn't appear to identify the literal as boolean (because the column referenced is BOOLEAN), nor convert between. Could you explain?

**Comment by tobymao** [comment]
this code blindly converts any IN statement to strings.

if you want, you can parse the create, and figure out which columns are boolean, and then see when check is calling against the boolean
