### ISSUE TITLE
Invalid SQL constructed after parse

### ISSUE THREAD

**Issue by JoeNaso** [tobymao/sqlglot#2960]
**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
This occurs on both `21.1.1` and `21.1.1.dev11` (main). 
```
test = """
with sampled as (
    select 'a' as a, 'b' as b, [0,1,2,3] AS vals
)
select 
    a, 
    b, 
    idx,
    val
from sampled
cross join unnest(sampled.vals) AS val WITH OFFSET AS idx
"""

out = sqlglot.parse(test, dialect="bigquery").sql()

# WITH sampled AS (SELECT 'a' AS a, 'b' AS b, ARRAY(0, 1, 2, 3) AS vals) SELECT a, b, idx, val FROM sampled CROSS JOIN UNNEST(sampled.vals) WITH ORDINALITY AS _t(val, idx)
```
In a real-world scenario, additional modifications to the syntax tree would happen after parsing. Regardless, the `.sql()` produces invalid SQL caused by this usage of ARRAY(). 

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
you need to specify the output dialect to bigquery as well.
