### ISSUE TITLE
Large unions cannot be constructed

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#2961]
Constructing a large union of 72 tables in sqlglot hits the stack recursion limit in Python.

We finally landed our port of all the ibis backends to sqlglot and we found that the benchmark that tests ibis's ability to construct these huge unions broke.

The original issue was reported as arising from an in-the-wild data validation use case in https://github.com/ibis-project/ibis/issues/7124.

We haven't yet fully addressed the issue in ibis, but now that we're using sqlglot, the same problem is arising from our use of sqlglot.

**Fully reproducible code snippet**

```python
from functools import reduce

import sqlglot as sg
import sqlglot.expressions as sge


def make_union(left, right):
    if isinstance(left, sge.Table):
        left = sg.select("*",copy=False).from_(left, copy=False)

    if isinstance(right, sge.Table):
        right = sg.select("*", copy=False).from_(right, copy=False)

    return sg.select("*").from_(
        sg.union(
            left.args.get("this", left),
            right.args.get("this", right),
            copy=False,
        ).subquery(copy=False)
    )

n = 72

t = sg.table("t")

expr = reduce(make_union, [t] * n)

# fails to generate the sql
print(expr.sql(copy=False))
```

In the original Ibis issue there [are around 495 tables](https://github.com/ibis-project/ibis/issues/7124#issuecomment-1715882618) involved.

Without passing `copy=False` everywhere, I get a slightly different stack recursion limit error caused by what seems to be pervasive deep copying throughout sqlglot.

**Comment by tobymao** [comment]
no plans to solve this as it's a bit tricky to unravel. you can get around this by increasing your stack limit

import sys

sys.setrecursionlimit(100000)

**Comment by cpcloud** [comment]
Definitely aware of the recursion limit option, not a huge fan of that approach but I understand it's a tricky problem. We're probably going to do it ibis FWIW, perhaps our implementation will be useful as a starting point.

**Comment by tobymao** [comment]
it's definitely possible, and if you made a PR to change unions to non-recursive we'll be more than happy to help you get it in.

**Comment by cpcloud** [comment]
The initial approach we're considering is to treat all set operations as N-ary operations with N relations and N - 1 "distinct" boolean flags.

**Comment by tobymao** [comment]
we're not going to switch the ast, there are too many dependent optimizations and code that relies on the current nested ast.

**Comment by tobymao** [comment]
imo it's simpler (albeit not super simple) to reorganize the generator, you'll just need to handle various issues that would come across it

**Comment by cpcloud** [comment]
I don't how this problem can be solved without changing the representation. Even if you don't copy, it's still not possible to recurse into the structure to check whether its of a give type.

**Comment by tobymao** [comment]
sqlglot is able to parse an infinite number of unions without blowing out the stack because it doesn't use recursion at parse. 

it still uses recursion for the generation. the trick would be to not use recursion for the generation.

**Comment by cpcloud** [comment]
I guess we'll see how it goes and whether this problem pops up again.

Since we just got through an enormous port, I don't think any of us has the energy right now to convert complex recursion to iteration.
