### ISSUE TITLE
Column could not be resolved in a correlated subquery without a FROM clause

### ISSUE THREAD

**Issue by Konntroll** [tobymao/sqlglot#2964]
I believe there might be an issue with how the `optimize` method handles correlated subqueries for T-SQL, MySQL, and possibly other dialects. The following snippet results in `OptimizeError: Column 'col1' could not be resolved`. If I add `FROM tab1` to the subquery, the optimizer will process it but the query should be valid without that clause.

```
q = """
SELECT col1,
       col2,
       col3
FROM tab1
WHERE NOT EXISTS
    (SELECT col1
     WHERE col3 > 3000000
       AND col2 > 250000000)
"""

schema = {
  'tab1': {'col1': 'STRING', 'col2': 'INT', 'col3': 'INT'}
}

formatted_query_txt = parse_one(q, dialect='tsql')
opt = optimize(formatted_query_txt, schema).sql(dialect='tsql')
```

**Comment by georgesittas** [comment]
Is the version without `FROM` always equivalent to the one with `FROM`?

**Comment by Konntroll** [comment]
@georgesittas, curiously, no. The complete query I'm working with looks like this:

```
SELECT col1,
       col2,
       col3
FROM tab1
WHERE col1 IN
    (SELECT col1
     FROM tab1
     WHERE col3>=3000000
       OR col2>=250000000)
  AND col1 NOT IN
    (SELECT col1
     WHERE col3>=3000000
       AND col2>=250000000);
```

This yields the expected result whereas adding 'FROM tab1' to the second subquery makes the whole thing return an empty set, which is wrong.

Sadly, I can't seem to find much in the docs to shed some light on this behaviour.

**Comment by georgesittas** [comment]
Is there any documentation for this syntax? I haven't seen it before and it kinda looks non-standard, but I could be wrong.

**Comment by Konntroll** [comment]
[Apparently](https://stackoverflow.com/questions/34340013/sql-syntax-select-without-from-clause-as-subquery-in-select-subselect) it used to be documented in an [ISO standard for SQL](https://web.cecs.pdx.edu/~len/sql1999.pdf) but I'm not sure how to find it there.

**Comment by georgesittas** [comment]
Interesting, we'll take a look thanks!

**Comment by Konntroll** [comment]
Sorry, the full query I posted earlier _does_ yield the correct result with and without `FROM tab1`. It is this query that behaves differently:

```
SELECT col1,
       col2,
       col3
FROM tab1
WHERE (col3 > 3000000
       OR col2 > 250000000)
  AND NOT EXISTS
    (SELECT col1
     WHERE col3 > 3000000
       AND col2 > 250000000);
```

The two are meant to accomplish the same thing and both cause the same OptimizeError.

**Comment by georgesittas** [comment]
Hey @Konntroll, I tried out all queries you posted in this issue and doesn't seem like the optimizer's failing. I'll close this for now, can you make sure you're using the latest version and share the exact query that's failing if there's still an issue?

**Comment by Konntroll** [comment]
@georgesittas, you are right. I must have forgotten the `--upgrade` flag when updating to the latest version. Thank you for looking into this! Sorry it was nothing :-)

**Comment by georgesittas** [comment]
No worries, happens all the time :)
