### ISSUE TITLE
b"'STR_POSITION' is not a recognized built-in function name

### ISSUE THREAD

**Issue by mclowdus** [tobymao/sqlglot#2968]
**Is your feature request related to a problem? Please describe.**
I am working on a project where I am attempting to join one integer column with another column that contains the same integer, but after a text value and a hyphen. Clarifying further, as an example, I want to join the value 12345 with the value 'hello-12345', by using the charindex() function (tsql is my base dialect here) to get the location of the hyphen. When I do this I run into an error saying that the str_position function is not recognizable. I have also attempted changing my dialect to postgres to use strpos() or position() but I ran into the same error.

tsql attempts:
cast(substring(x.id from position('~' in x.id) + 1) as bigint) = y.id

postgres attempts:
cast(substring(x.id from strpos(x.id, '-') + 1) as bigint) = y.id
on  cast(substring(x.id from position('~' in x.id) + 1) as bigint) = y.id

**Describe the solution you'd like**
I would love to be able to utilize this function in my model to extract other attributes from the joined table.

**Describe alternatives you've considered**
Hopefully I outlined my attempts in the description above but happy to answer any follow ups!

**Comment by georgesittas** [comment]
Hey, can you show exactly which functions you tried to execute and how, as well as the actual vs expected result? Thanks

**Comment by mclowdus** [comment]
Yes, the tsql snippet would be most prevalent. 

I am trying this inner join in my model definition

```sql
select  t1.name
from  table1 t1
inner join table2 t2 
on t1.id = SUBSTRING(t2.id, CHARINDEX('~', t2.id) + 1, LEN(t2.id))
```
with the attempt to get the number after the '~' in t2.

The expected result would be a complete model where I can access elements in both t1 and t2. Instead I get the error:
(195, b"'STR_POSITION' is not a recognized built-in function name.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

**Comment by georgesittas** [comment]
Sorry, I'm not sure what you mean. Are you trying to transpile this query? If so, I understand that the input dialect is T-SQL - what about the target dialect? Please provide some more details, such as the actual call to `transpile` or `parse_one` etc.

**Comment by Rahlir** [comment]
I think a similar problem with `oracle` dialect. Running
```python
sqlglot.parse_one("cast(substr(table.column, 1, instr(table.other_column, '#')-1) as int)", dialect="oracle").sql(dialect="oracle")
```
yields
```
"CAST(SUBSTR(table.column, 1, STR_POSITION(table.other_column, '#') - 1) AS NUMBER)"
```
But oracle throws error:
```
ORA-00904: "STR_POSITION": invalid identifier
```

**Comment by Rahlir** [comment]
@georgesittas @mclowdus  Could we re-open this please? I could try submitting a PR fixing this, but not sure right now when I will have enough time.

**Comment by georgesittas** [comment]
The behavior in main is different than what you showed above:

```python
>>> import sqlglot
>>> sqlglot.parse_one("cast(substr(table.column, 1, instr(table.other_column, '#')-1) as int)", dialect="oracle").sql(dialect="oracle")
"CAST(SUBSTR(table.column, 1, INSTR(table.other_column, '#') - 1) AS INT)"
```

I think the issue has been fixed since then.
