### ISSUE TITLE
json_extract_path is added for JSONB columns

### ISSUE THREAD

**Issue by l-vincent-l** [tobymao/sqlglot#2971]
This [PR](https://github.com/tobymao/sqlglot/pull/2883) introduces a regression with postgres

Before this PR I could do:
``python
from sqlglot import parse_one
query = """ 
SELECT
   (j->'i')::int,
  (j->>'i')::int,
   (j->'f')::float,
   (j->>'f')::float
FROM
  (SELECT '{"i":123,"f":12.34}'::jsonb) t(j)
"""
parse_one(query).sql(dialect="postgres")
 ```
That would give me a query that i could execute
```sql
SELECT 
  CAST((j -> 'i') AS INT),
  CAST((j ->> 'i') AS INT),
  CAST((j -> 'f') AS REAL),
  CAST((j ->> 'f') AS REAL)
FROM (SELECT CAST('{"i":123,"f":12.34}' AS jsonb)) AS t(j)
```

With version 21.1.0, the same code returns
```sql
SELECT
  CAST((JSON_EXTRACT_PATH(j, 'i')) AS INT),
  CAST((JSON_EXTRACT_PATH_TEXT(j, 'i')) AS INT),
  CAST((JSON_EXTRACT_PATH(j, 'f')) AS REAL),
  CAST((JSON_EXTRACT_PATH_TEXT(j, 'f')) AS REAL)
FROM (SELECT CAST('{"i":123,"f":12.34}' AS jsonb)) AS t(j)
```

When I execute it I have this error : `ERROR:  function json_extract_path(jsonb, unknown) does not exist` because `json_extract_path` expects a JSON.
If I manually change the query to cast `j` to json like this

```sql
SELECT
  CAST((JSON_EXTRACT_PATH(j, 'i')) AS INT),
  CAST((JSON_EXTRACT_PATH_TEXT(j, 'i')) AS INT),
  CAST((JSON_EXTRACT_PATH(j, 'f')) AS REAL),
  CAST((JSON_EXTRACT_PATH_TEXT(j, 'f')) AS REAL)
FROM (SELECT CAST('{"i":123,"f":12.34}' AS json)) AS t(j)
```

I have this error : `ERROR:  cannot cast type json to integer` because you can not cast json to integer you need to either a `JSONB` or a `TEXT`.

**Comment by georgesittas** [comment]
This seems like an oversight on my end - apologies! Need to figure out how to solve this, it may be a bit tricky to preserve both the query roundtrip in postgres and the ability to transpile these operators / functrions from postgres to other dialects.

Thanks for reporting this!
