### ISSUE TITLE
Keep the (+) or (-) where it is in oracle query using them for join options.

### ISSUE THREAD

**Issue by Hal-H2Apps** [tobymao/sqlglot#2979]
Python 3.11 / sqlglot 21.1.1

**Fully reproducible code snippet**
`    text: str = "SELECT actor.actor_id, actor.last_name, actor_addresses.address FROM  actor, actor_addresses WHERE actor.actor_id = actor_addresses.actor_id(+)"
    try:
        sql = parse_one(sql=text, read="oracle")
    except ParseError as e:
        pass
    print(sql)`

-> Outer join syntax using the (+) operator is not supported.
-> SELECT actor.actor_id, actor.last_name, actor_addresses.address FROM actor, actor_addresses WHERE actor.actor_id = actor_addresses.actor_id
=> The query drop the (+)

**Is your feature request related to a problem? Please describe.**
I'm using sqlglot to analyse query from different clients, and adding command in them. Without full support of oracle Union, I can't rely on sqlglot to do it.  

**Describe the solution you'd like**
I would like to have the (+) or (-) been kept where it is when I'm using the print from parse_one. I'm okay with an option saying I will not be able to manage joins or be limited about what I will be able to do if I want to use the (+) and (-) as outer join in oracle.

**Describe alternatives you've considered**
I don't see any alternative than not using sqlglot. And it's really a product I love!

**Additional context**

**Official Documentation**
[Please include links to official SQL documentation related to your issue.
](https://blogs.oracle.com/optimizer/post/outerjoins-in-oracle)

**Comment by georgesittas** [comment]
This is already supported, you just need to specify the target dialect when generating SQL:

```python
from sqlglot import parse_one

sql = """
SELECT
  actor.actor_id,
  actor.last_name,
  actor_addresses.address
FROM actor, actor_addresses
WHERE
  actor.actor_id = actor_addresses.actor_id(+)
"""

ast = parse_one(sql, dialect="oracle")

# This targets the "SQLGlot" dialect by default
# print(ast)

print(parse_one(sql, dialect="oracle").sql(dialect="oracle"))
# SELECT actor.actor_id, actor.last_name, actor_addresses.address FROM actor, actor_addresses WHERE actor.actor_id = actor_addresses.actor_id (+)
```

**Comment by Hal-H2Apps** [comment]
Indeed!! Thank you for your quick tip!
