### ISSUE TITLE
Failed to parse TSQL query with 'OPTION' statement

### ISSUE THREAD

**Issue by ShayYaari** [tobymao/sqlglot#2988]
Hi!

I'm trying to use sqlglot to parse the following query:

SELECT a FROM b OPTION (MAXDOP 1)

using Dialect.TSQL.

It fails with the following error:

`
sqlglot.errors.ParseError: Expecting ). Line 2, Col: 32.
`

Any suggestions?

Thanks!

**Comment by georgesittas** [comment]
Hey, this isn't high priority right now so we don't plan to implement it. Feel free to make a PR if you need this - my guess is that the `OPTION` should be supported as a "query modifier", at least only for T-SQL (unless other dialects have something similar). If you need any guidance, feel free to reach out in [Slack](https://tobikodata.com/slack).

**Comment by georgesittas** [comment]
Fixed in https://github.com/tobymao/sqlglot/commit/51f8d5897b18e6f7c0bc66881a3e36c8842ff2ff by @nadav-botanica!
