### ISSUE TITLE
Support for JSON operators?

### ISSUE THREAD

**Issue by gotdan** [tobymao/sqlglot#299]
Postgres, SQLite, DuckDB, and potentially other dialects support JSON operators (`->`, `->>`, `#>` and `#>>`) to reference elements in a json column. For example:

```sql
SELECT customer ->> 'id' AS id
FROM customers
WHERE (customer -> '2021' -> 'revenue')::INTEGER > 100
```

Docs are at https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-OP-TABLE

Postgres also supports a set of JSONB specific operators listed in https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSONB-OP-TABLE

Currently, I'm getting a parse error when a query contains these elements. Is it possible to add support for parsing the JSON operators, and potentially the JSONB operators as well?

**Comment by tobymao** [comment]
done thanks. i don't convert postgres path syntax into xml path yet
