### ISSUE TITLE
Bigquery implicit unnest transpile error

### ISSUE THREAD

**Issue by wizardxz** [tobymao/sqlglot#2996]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```
>>> import sqlglot
>>> sqlglot.transpile("""WITH Coordinates AS (SELECT [1,2] AS position)
... SELECT results FROM Coordinates, Coordinates.position AS results;
... """, read="bigquery", write="presto")[0]
'WITH Coordinates AS (SELECT ARRAY[1, 2] AS position) SELECT results FROM Coordinates, Coordinates.position AS results'
```
Bigquery has implicit unnest, while the presto does not have, so this presto sql is wrong

**Official Documentation**
Please include links to official SQL documentation related to your issue.
https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#implicit_unnesting

**Comment by georgesittas** [comment]
Thanks, will look into this soon.

**Comment by wizardxz** [comment]
Thanks for quick fix.
```
>>> import sqlglot
>>> sqlglot.transpile("""WITH Coordinates AS (SELECT [1,2] AS position)
... SELECT results FROM Coordinates, `Coordinates.position` AS results;
... """, read="bigquery", write="presto")[0]
```
should have result
```
'WITH Coordinates AS (SELECT ARRAY[1, 2] AS position) SELECT results FROM Coordinates, Coordinates.position AS results'
```
actually I got the unnest
```
WITH Coordinates AS (SELECT ARRAY[1, 2] AS position) SELECT results FROM Coordinates, UNNEST(Coordinates.position) AS _t(results)
```

**Comment by tobymao** [comment]
@wizardxz aren't they equivalent?

**Comment by wizardxz** [comment]
@tobymao No you can see my comment in
https://github.com/tobymao/sqlglot/issues/3014

**Comment by tobymao** [comment]
appreciate the issues, but please put more details in them next time.
