### ISSUE TITLE
TO_CHAR(number) in Oracle is parsed as DATE_FORMAT in Doris

### ISSUE THREAD

**Issue by codeDing18** [tobymao/sqlglot#3000]
`sqlglot.transpile(sql,read="oracle", write="doris")[0]`

sql:
`SELECT TO_CHAR(100);`

is parsed as:
`SELECT DATE_FORMAT(100, None)`

**Comment by tobymao** [comment]
closing for lack of details / docs. please follow the guides when making an issue
