### ISSUE TITLE
Unable to use optimizer on SQL with create statement

### ISSUE THREAD

**Issue by matthewsilver** [tobymao/sqlglot#3004]
I’m unable to optimize SQL with create statements even though other users mention code snippets that do so. Is this no longer possible, or is there an error in how I’m doing it?

SQL:

import sqlglot
from sqlglot.optimizer import optimize

ast = sqlglot.parse_one(“create table a as (select * from abc)”, read=“hive”)

print(optimize(ast).sql(pretty=True))

Output:

OptimizeError: Unexpected expression type: <class ‘sqlglot.expressions.Create’>

**Comment by georgesittas** [comment]
This is working fine with the latest SQLGlot version:

```python
>>> import sqlglot
>>> from sqlglot.optimizer import optimize
>>>
>>> ast = sqlglot.parse_one("create table a as (select * from abc)", read="hive")
>>> print(optimize(ast).sql(pretty=True))
CREATE TABLE "a" AS
(
  SELECT
    *
  FROM "abc" AS "abc"
)
```
