### ISSUE TITLE
Qualify Columns fails with LATERAL FLATTEN of ARRAY in snowflake when VALUE is lowercase

### ISSUE THREAD

**Issue by pedro-delphina** [tobymao/sqlglot#3006]
Example query that fails:

```sql
SELECT 
    d.ORDER_ID
    , f.value
FROM DISCOUNTS AS d
, LATERAL FLATTEN(input => d.DISCOUNTS_ARRAY) AS f
```
with the error `OptimizeError(f"Unknown column: {column_name}")`

When I change this to:

```sql
SELECT 
    d.ORDER_ID
    , f.VALUE
FROM DISCOUNTS AS d
, LATERAL FLATTEN(input => d.DISCOUNTS_ARRAY) AS f
```

then it just works. It looks like the problem is not converting the column identifier to upper case before checking it is on the `FLATTEN_COLUMNS` list.

https://github.com/tobymao/sqlglot/blob/541e6de950934fb440256132e4240f218fa3240d/sqlglot/dialects/snowflake.py#L516

The version I'm using is `21.1.2`

**Comment by georgesittas** [comment]
I can successfully qualify this query:

```python
>>> from sqlglot.optimizer.qualify import qualify
>>> from sqlglot import parse_one
>>>
>>> sql = """
... SELECT
...     d.ORDER_ID
...     , f.value
... FROM DISCOUNTS AS d
... , LATERAL FLATTEN(input => d.DISCOUNTS_ARRAY) AS f
... """
>>>
>>> expr = parse_one(sql, "snowflake")
>>> qualify(expr, dialect="snowflake").sql("snowflake")
'SELECT "D"."ORDER_ID" AS "ORDER_ID", "F"."VALUE" AS "VALUE" FROM "DISCOUNTS" AS "D", LATERAL FLATTEN(input => "D"."DISCOUNTS_ARRAY") AS "F"("SEQ", "KEY", "PATH", "INDEX", "VALUE", "THIS")'
```

**Comment by pedro-delphina** [comment]
> I can successfully qualify this query:
> 
> ```python
> >>> from sqlglot.optimizer.qualify import qualify
> >>> from sqlglot import parse_one
> >>>
> >>> sql = """
> ... SELECT
> ...     d.ORDER_ID
> ...     , f.value
> ... FROM DISCOUNTS AS d
> ... , LATERAL FLATTEN(input => d.DISCOUNTS_ARRAY) AS f
> ... """
> >>>
> >>> expr = parse_one(sql, "snowflake")
> >>> qualify(expr, dialect="snowflake").sql("snowflake")
> 'SELECT "D"."ORDER_ID" AS "ORDER_ID", "F"."VALUE" AS "VALUE" FROM "DISCOUNTS" AS "D", LATERAL FLATTEN(input => "D"."DISCOUNTS_ARRAY") AS "F"("SEQ", "KEY", "PATH", "INDEX", "VALUE", "THIS")'
> ```

Interesting, now that you mentioned `qualify` does work for me too, but not `qualify_columns`. This is on `21.1.2`. Thank you for pointing me in the right direction!

**Comment by georgesittas** [comment]
Yeah, `qualify` does some preprocessing related to identifier normalization which I guess is important in this case because of the mix-casing. I think you should just use that  instead of `qualify_columns` to avoid similar issues.
