### ISSUE TITLE
Support AUTO_INCREMENT to SERIAL in transpile to Postgres

### ISSUE THREAD

**Issue by adamf** [tobymao/sqlglot#301]
Postgres has no `AUTO_INCREMENT` type; instead it uses `SMALLSERIAL`, `SERIAL` and `BIGSERIAL`:

https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-SERIAL

Right now the transpiler doesn't support this; it'd be nice if it did. 

Looking at the code I _think_ this is adding `"SERIAL"` to the https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/postgres.py#L36 mapping to the `AUTO_INCREMENT` token type. Is that correct?

**Comment by tobymao** [comment]
also needed to add a token_mapping from auto_increment -> serial

**Comment by mpf82** [comment]
What about smallserial and bigserial?

https://www.postgresql.org/docs/current/datatype-numeric.html
