### ISSUE TITLE
Unexpected unnest

### ISSUE THREAD

**Issue by wizardxz** [tobymao/sqlglot#3014]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. parse_one(sql, read="spark")
- Check if the issue still exists on main 

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```
>>> import sqlglot
>>> sqlglot.transpile("""WITH Coordinates AS (SELECT [1,2] AS position)
... SELECT results FROM Coordinates, `Coordinates.position` AS results;
... """, read="bigquery", write="presto")[0]
```
should have result
```
'WITH Coordinates AS (SELECT ARRAY[1, 2] AS position) SELECT results FROM Coordinates, Coordinates.position AS results'
```
actually I got the unnest

```
WITH Coordinates AS (SELECT ARRAY[1, 2] AS position) SELECT results FROM Coordinates, UNNEST(Coordinates.position) AS _t(results)
```
**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
these are equivalent so it looks right to me

**Comment by georgesittas** [comment]
Your example contains backticks which is actually invalid BQ:

```
--  Not found: Dataset ...:Coordinates was not found in location ... 
WITH Coordinates AS (SELECT [1,2] AS position)
SELECT results FROM Coordinates, `Coordinates.position` AS results;
```

The result is as you said if we get rid of the backticks, but I see no issue - the semantics are preserved:

```
presto> WITH Coordinates AS (SELECT ARRAY[1, 2] AS position) SELECT results FROM Coordinates, UNNEST(Coordinates.position) AS _t(results);
 results 
---------
       1 
       2 
(2 rows)
```

<img width="536" alt="Screenshot 2024-02-23 at 2 17 49 AM" src="https://github.com/tobymao/sqlglot/assets/46752250/b5bf6865-8163-4848-8e05-e22b0f920929">

SQLGlot doesn't guarantee that the generated SQL which match the input, it aims to produce something with equivalent semantics.

**Comment by wizardxz** [comment]
If you create a table
`Coordinates.position`
You will see different results

**Comment by wizardxz** [comment]
>SQLGlot doesn't guarantee that the generated SQL which match the input, it aims to produce something with equivalent semantics.

The semantics depends on the context
- if you have Coordinates.position, it produce one semantic
- if you don't have Coordinates.position, it produce different

You need more input to make decision

**Comment by georgesittas** [comment]
I see what you mean - that makes sense, thanks. I'll try fix this tomorrow.

**Comment by wizardxz** [comment]
Thanks! Take your time. I am not in rush
