### ISSUE TITLE
sqlglot doesn't support SQLITE square brackets around keywords

### ISSUE THREAD

**Issue by adamf** [tobymao/sqlglot#302]
See https://www.sqlite.org/lang_keywords.html

The square bracket notation is used in place of other means of escaping keywords - eg, instead of double quotes. 

```
sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.Table'>. Line 2, Col: 14.

CREATE TABLE [Track]
(
    [TrackId] INTEGER  NOT NULL,
    [Name] NVARCHAR(200)  NOT NULL,
    [AlbumId] INTEGER,
```

Column 14 is the square bracket.

Another example:
`SELECT [track].[name] FROM [track];`
Runs fine in SQLite, fails to parse:
```
sqlglot.errors.ParseError: Required keyword: 'expression' missing for <class 'sqlglot.expressions.Dot'>. Line 1, Col: 16.
  SELECT [track].[name] FROM [track];
```

**Comment by tobymao** [comment]
does sqlite support brackets in other context like column[‘y’] ?

**Comment by adamf** [comment]
Looking at the documentation for, eg, https://www.sqlite.org/syntax/expr.html it doesn't look like the square bracket is used anywhere else - but I'm not sure. 

I do have a lot of test sqlite files I can test with if you have a branch you want to put up.

**Comment by tobymao** [comment]
this one is a bit more involved, we'll see when i'll get to it. or if you are i can help you out. you'll need to refactor tokenizer to support multiple identifiers and to also allow them to have a start and an end, so identifiers instead of just being a string, could also be a tuple

**Comment by adamf** [comment]
I've not had time, but @crericha if you have an in-progress branch I'm happy to look and test.

**Comment by crericha** [comment]
Thanks @adamf. I'll let you know when I have something to test.

**Comment by plexilcrf** [comment]
I have a fork I developed to handle the square bracket issue. IIUC the square bracket quoting syntax actually is a Microsoft-originated quirk. See: https://github.com/plexilcrf/sqlglot
