### ISSUE TITLE
Doesn't Differentiate Using Aliases in Group By 

### ISSUE THREAD

**Issue by vldt-aem** [tobymao/sqlglot#304]
The test that I used was:

```python
sql = """SELECT
    table_schema
    , CASE WHEN table_schema = 'my_table' THEN 1 ELSE 0 END as test
    , COUNT(*)

FROM information_schema.columns
GROUP BY
    table_schema
    , test
LIMIT 10 """
print(sqlglot.transpile(sql, read='postgres', write='oracle', identify=True, pretty=True)[0])
```

And what it returned was: 
```
SELECT
  "table_schema",
  CASE
    WHEN "table_schema" = 'my_table'
    THEN 1
    ELSE 0
  END AS "test",
  COUNT(*)
FROM "information_schema"."columns"
GROUP BY
  "table_schema",
  "test"
LIMIT 10
```

Referencing aliases in the group by is not supported in Oracle SQL, so this returns an error

**Comment by tobymao** [comment]
what is the correct behavior?

**Comment by tobymao** [comment]
i guess you're asking to rewrite the case statement in the group by? i think for now it's best to do this yourself using the transform api. 

you can walk the expression tree, find expressions within group by that point to aliases and rewrite them.

**Comment by barakalon** [comment]
What if we add the transformation logic to the generator of Oracle's dialect?

**Comment by tobymao** [comment]
@barakalon sounds good to me, should i reopen this issue?

**Comment by vldt-aem** [comment]
@tobymao @barakalon Awesome, thank you!
