### ISSUE TITLE
Raise or detect errors instead of swallowing with warning

### ISSUE THREAD

**Issue by edongashi** [tobymao/sqlglot#3042]
We have this mechanism where we parse DDLs with an optional dialect. If the dialect is unspecified, we try to guess by going through a list of dialects and taking the first one that passes.

The above worked reasonably well in version 19, but no longer works when I updated to 21.2. I suspect because of changes made in #2873.

**Fully reproducible code snippet**

Say I have this bigquery table and I try to parse it with the postgres dialect. 

```py
result = parse(
    """
    CREATE TABLE `bigquery-public-data.new_york_citibike.CitibikeStations` (
        `StationId` INTEGER,
        `Name` STRING,
        `ShortName` STRING,
        `Data` JSON,
        `Meya` JSON,
        `RegionId` INTEGER,
        `RentalMethods` ARRAY<STRING>,
        `Capacity` INTEGER,
        `EightdHasKeyDispenser` BOOLEAN,
        `ExternalId` STRING,
        `LegacyId` STRING,
        `StationSype` STRING,
        `RentalUrl` STRING,
        `EightdStationServices` ARRAY<STRING>,
        `HasKiosk` BOOLEAN
    );
""",
    dialect="postgres",
)
```

Expected outcome is a raised exception.

Instead I get a warning and the result is:

```
'CREATE TABLE `bigquery-public-data.new_york_citibike.CitibikeStations` (
        `StationId` INTEGER' contains unsupported syntax. Falling back to parsing as a 'Command'.
```

I tried playing with `ErrorLevel` but as far as I'm aware there is no way to crash instead of the silent fallback.

My question is, is there any way to either:

1. Detect that this fallback has occurred?
2. Pass an option to make it raise instead of swallow?

I guess I could walk the result and check if we have a `Command(this=CREATE ...` statement; but this feels a little hacky, as there might be a legitimate occurrence of such statement.

Thanks!

**Comment by georgesittas** [comment]
I'd just go with checking if the parsed statement is a `Command` - you can make it more specific by checking if the `Command`'s primary argument (`this`) stores `CREATE`, if you're only interested in DDLs.

SQLGlot intentionally produces `Command` nodes as a fallback for some statements that it doesn't recognize, to avoid failing in cases where the user is not interested in transpilation but just wants to parse many statements in bulk and generate them as is.

**Comment by edongashi** [comment]
> I'd just go with checking if the parsed statement is a `Command` - you can make it more specific by checking if the `Command`'s primary argument (`this`) stores `CREATE`, if you're only interested in DDLs.

Alright, that's also what I had in mind. Thanks!
