### ISSUE TITLE
Remove the catalog name from trino/presto to other dialects

### ISSUE THREAD

**Issue by metalshanked** [tobymao/sqlglot#3054]
Is there a way to automatically remove the intial "catalog" name when transpiling from Trino to other DBs like Postgres?

Example:-
```
import sqlglot
res = sqlglot.transpile('''SELECT col1,col2 FROM catalog.schema.table LIMIT 1;''', read="trino", write="postgres")

#Postgres --> ['SELECT col1, col2 FROM catalog.schema.table LIMIT 1']
```
I want to have "catalog" removed in the Postgres SQL output since the query fails in Postgres with the catalog name in the SQL

Thanks!

**Comment by georgesittas** [comment]
You can write a custom transformation that removes it prior to transpiling:

```python
import sqlglot

def remove_catalog(expression):
    if isinstance(expression, sqlglot.exp.Table) and expression.catalog:
        expression.args["catalog"].pop()
    return expression

expression = sqlglot.parse_one(<your query>, read="trino")
transformed = expression.transform(remove_catalog)

print(transformed.sql(dialect="postgres"))
```

**Comment by metalshanked** [comment]
@georgesittas - Apologies for the basic question but how do i use the above custom transformation in 
`sqlglot.transpile`? 
I want it to automatically kick in only when the "read" is set to "trino" dialect in the sqlglot.transpile invokation.

Any example would be helpful. 
Thanks!

**Comment by georgesittas** [comment]
A simple way is to use `parse_one` and then invoke the `sql` method on the produced AST:

```python
ast = parse_one(query, dialect=read)
if read == "trino":
    ast = ast.transform(remove_catalog)

output = ast.sql(dialect=write)
```
