### ISSUE TITLE
Error with JSON / Array conversions

### ISSUE THREAD

**Issue by metalshanked** [tobymao/sqlglot#3060]
Hi,

The below query seems to be erroring

Error
```
ERROR in JDBC Postgres Client: cannot cast type jsonb to json[]
```

READ: trino
```
select id,
      json_extract_scalar(boxes,'$.name') name,
      json_extract_scalar(boxes,'$.type') type,
      json_extract_scalar(boxes,'$.color') color
  from postgres.schema.table
  CROSS JOIN UNNEST(CAST(boxcrate as array(json))) as x(tbox)
  CROSS JOIN UNNEST(CAST(json_extract(tbox, '$.boxes') AS array(json))) AS y(boxes)
  where fruit like '%apple%'
limit 5
```

WRITE: postgres
```
SELECT id, JSON_EXTRACT_PATH_TEXT(boxes, 'name') AS name, 
  JSON_EXTRACT_PATH_TEXT(boxes, 'type') AS type, 
  JSON_EXTRACT_PATH_TEXT(boxes, 'color') AS color
FROM postgres.schema.table 
  CROSS JOIN UNNEST(CAST(boxcrate AS JSON[])) AS x(tbox) 
  CROSS JOIN UNNEST(CAST(JSON_EXTRACT_PATH(tbox, 'boxes') AS JSON[])) AS y(boxes)
WHERE fruit LIKE '%apple%' LIMIT 5
```

MANUAL POSTGRES CONVERSION (WORKING)
```
SELECT id
    , boxes ->> 'name' AS name
    , boxes ->> 'type' AS type
    , boxes ->> 'color' AS color
FROM (
    SELECT id, json_array_elements((json_array_elements(boxcrate::JSON) ->> 'boxes')::JSON) AS boxes
    FROM postgres.schema.table 
) a
LIMIT 5 ;
```

**Comment by georgesittas** [comment]
Hey @metalshanked, can you give me a complete, self-contained Trino query to use as input? I'll need to understand a bit more about the type semantics involved here. Some static data defined in a CTE will do, as long as I have a query that can be executed as is in Trino.

**Comment by metalshanked** [comment]
Thanks @georgesittas. Sure, will try to figure out the self contained query. 

Meanwhile if it helps. The above queries mostly operate on a single JSONB field which has a json like below
You can ignore the "id" and WHERE clause in the queries

--Column Name : `boxcrate`
```
[
    {
        "boxes": [
            {
                "name": "f1",
                "type": "plant",
                "color": "red"
           
            },
            {
                "name": "f2",
                "type": "plant",
                "color": "green"
            }
        ]
    }
]
```

**Comment by tobymao** [comment]
trino doesn’t have a concept of jsonb so i don’t know if what you want is possible

**Comment by georgesittas** [comment]
To my understanding, you've manually specified that the column's type is `JSONB` in Postgres @metalshanked? Like Toby said, Trino doesn't have the `JSONB` type, so I assume if you were simply transpiling the Trino query as-is you wouldn't have to deal with `JSONB` values at all.

I'm exploring a way to fix the transpilation of `UNNEST`, _assuming_ that you have either a string or a `JSON` column as input, but other than that I can't think of a way to support what you're saying here. We don't have enough type information statically to use the correct Postgres JSON functions, both for value extraction and for exploding the JSON array.

I'll close this issue as not planned, but will try to implement what I said above. Will update if / when I have an update on this.

**Comment by metalshanked** [comment]
Thanks @georgesittas. Yes, the table column is JSONB in postgres
What would be a manual edit way to make the above transpiled query work in Postgres?  I tried casting to JSON but gave errors too.

**Comment by georgesittas** [comment]
I think you have to replace the cast to `JSON[]` with cast to `[]` and the `UNNEST` calls with `JSON_ARRAY_ELEMENTS`.

**Comment by georgesittas** [comment]
Check out #3063 @metalshanked.

**Comment by georgesittas** [comment]
Yes that's reasonable, that direction is not yet supported. It'll require more work to add proper transpilation support for `JSON[B]_ARRAY_ELEMENTS` and I think that's out of scope for us right now. If you want to contribute, we'll be happy to accept a well-crafted PR that implements this.

**Comment by metalshanked** [comment]
Thanks @georgesittas , will work on level/skill up to contribute to this item.
P.S. Was trying out Starrocks as a "Write" and see below
```
SELECT
  id,
  boxes ->>
  ...
  ```
```
: Unexpected input '>', the most similar input is {SINGLE_QUOTED_TEXT, DOUBLE_QUOTED_TEXT}.
```
