### ISSUE TITLE
Hive to Trino Timestamp Issue

### ISSUE THREAD

**Issue by metalshanked** [tobymao/sqlglot#3078]
Hi I have the below transpile from Hive to Trino

```
SELECT
  table
FROM hive
WHERE
  dt > '2024-01-20 03:31:34'
  ```
  
  ```
  SELECT
  table
FROM hive
WHERE
  dt > '2024-01-20 03:31:34'
  ```
  
  This throws an error in Trino `Cannot apply operator: timestamp(3) < varchar(19)`
  I think this is because hive allows timestamp match directly with strings and trino does not.
  
  The manual working solution seems to be adding TIMESTAMP to trino like below
  ```
  SELECT
  table
FROM hive
WHERE
  dt > TIMESTAMP '2024-01-20 03:31:34'
  ```

**Comment by tobymao** [comment]
this is not possible to do without additional information. you should rewrite your query so that it's more easily transpilable
