### ISSUE TITLE
SQLGlot Transpiles "SELECT * EXCEPT" into invalid Spark SQL.

### ISSUE THREAD

**Issue by jmsmdy** [tobymao/sqlglot#3082]
Consider the following code:

```python
ast = (
    sqlglot.parse_one("""
        SELECT
      tableA.*,
      tableB.* EXCLUDE (col1, col2)
    FROM
      tableA
      LEFT JOIN b AS other
      ON tableA.col1 = tableB.col1
      AND tableA.col2 = tableB.col2
    """, read='duckdb')
)
print(ast.sql(dialect='spark', pretty=True))
```
This generates the following invalid output:

```sql
SELECT
  tableA.*,
  tableB.*
  EXCEPT (col1, col2)
FROM tableA
LEFT JOIN b AS other
  ON tableA.col1 = tableB.col1 AND tableA.col2 = tableB.col2;
```
This is invalid because (Apache) Spark SQL doesn't support `SELECT * EXCEPT` in this format. A correct transpilation would look something like this:

```sql
SET spark.sql.parser.quotedRegexColumnNames=true;
SELECT
  tableA.*,
  tableB.`^(?!(col1|col2)$).*$`
FROM tableA
LEFT JOIN b AS other
  ON tableA.col1 = tableB.col1 AND tableA.col2 = tableB.col2;
RESET spark.sql.parser.quotedRegexColumnNames;
```

This is using the `regex_column_names` feature of Spark SQL to select all columns from table B which are not literally equal to col1, col2. 

BTW, I am not interested in converting *from* Spark SQL with regex column names, as that would require parsing and understanding arbitrary regex, which is probably impossible. But I am interested in correctly converting `SELECT * EXCLUDE` / `SELECT * EXCEPT` *to* Spark SQL with regex column names.

**Comment by tobymao** [comment]
this is possible by using the optimizer qualify method. you'll just need to pass in the schema so that we can figure out what columns to exclude.

i'm not a big fan of the regex method because it results in multiple statements returned

**Comment by tobymao** [comment]
```python
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify

q = parse_one("SELECT * except (a) FROM x")
qualify(q, schema={"x": {"a": "int", "b": "int"}}).sql()

'SELECT "x"."b" AS "b" FROM "x" AS "x"'
```

**Comment by jmsmdy** [comment]
For anyone else reading this, I was able to create a new Dialect for Spark SQL which can generate regex expressions to exclude columns:

```python
import sqlglot

class ExcludeSpark(sqlglot.dialects.spark.Spark):
    class Generator(sqlglot.dialects.spark.Spark.Generator):
        def star_sql(self, expression: sqlglot.exp.Star) -> str:
            except_ = self.expressions(expression, key="except", flat=True)
            replace = self.expressions(expression, key="replace", flat=True)
            replace = f"{self.seg(self.STAR_MAPPING['replace'])} ({replace})" if replace else ""
            if except_:
                column_exclude_regex = (
                    r'`^(?!(' 
                    + '|'.join([x.strip() for x in except_.lstrip('(').rstrip(')').split(',')]) 
                    + r')$).*$`'
                )
                return f"{column_exclude_regex}{replace}"
            else:
                return f"*{replace}"
```

Used as:

```python
ast.sql(dialect=ExcludeSpark)
```

Not fully tested, but seems to work. @tobymao the hackability of sqlglot is much appreciated!
