### ISSUE TITLE
parsing a bigquery statement not recognising project_id when backtick separates the project

### ISSUE THREAD

**Issue by razvan-am** [tobymao/sqlglot#3083]
Bigquery has many distinct types of marking tables/objects. 
In one of the cases it can handle: ``` `project`.`dataset.table` ``` sql_glot doesn't seem to be able to identify the project. 

**Fully reproducible code snippet**
```python
my_str = 'SELECT * FROM `project_id`.`dataset_id.table_id`'

parsed_string = sqlglot.parse(my_str, dialect='bigquery')

print(repr(parsed_string))
```

**Output**
```
[Select(
  expressions=[
    Star()],
  from=From(
    this=Table(
      this=Identifier(this=table_id, quoted=True),
      db=Identifier(this=dataset_id, quoted=True))))]
```

**Comment by tobymao** [comment]
hi @razvan-am do you have documentation for this or could you show us a screen shot that this is legal syntax?

**Comment by razvan-am** [comment]
<img width="949" alt="image" src="https://github.com/tobymao/sqlglot/assets/94355655/7d5eb302-31fa-4096-a4cb-9b22194dd38b">

**Comment by razvan-am** [comment]
If I'll stumble upon the documentation, I'll share it here.

we've had many issues due to the many ways that bigquery accetps the syntax. I have many tests and i'll share as I go through them.
