### ISSUE TITLE
sqlglot wrongly adds index offset to a MAP key

### ISSUE THREAD

**Issue by anhqle** [tobymao/sqlglot#3085]
In the snippet below, sqlglot mistakenly thinks that `my_map` is an ARRAY, and adds an index offset to `my_map`'s key.

```
In [2]: sqlglot.transpile("SELECT my_map[0]", read="spark", write="presto")[0]
Applying array index offset (1)
Out[2]: 'SELECT my_map[1]'
```

Pretty tricky issue--I'm not sure how to tell sqlglot that a column is a MAP<INT, ...> instead of an ARRAY.

**Comment by tobymao** [comment]
this isn't a mistake, it's ambiguous, this can be worked around if you have proper types, so if you do annontate_types before hand, you won't run into this

**Comment by tobymao** [comment]
another workaround could be like this

```python
sqlglot.transpile("SELECT my_map::map[0]", read="spark", write="presto")[0]
```
