### ISSUE TITLE
Lineage  - not downstreaming to subquery expression

### ISSUE THREAD

**Issue by sunrutcon** [tobymao/sqlglot#3086]
I'm trying to generate column level lineage from given INSERT statement.

I'm exploring column RUN_DATE,  and expect to get expression for last available downstream.

I expect to get same expression of last step in walk for sql_nok as in sql_ok.

Name: sqlglot
Version: 22.2.1

# Python code

```python
from sqlglot.lineage import lineage

sql_nok = """
insert /*+ HINT1*/ 
into	AML_NWU.DLT_TAXDAILY 
( 
	ORG_UNIT_CODE,
	RUN_DATE 
)
select
	nd.ORG_UNIT_CODE,
	nd.RUN_DATE
from
(select /*+ HINT2*/ 
	MAP_TAXDAILY.ORG_UNIT_CODE as ORG_UNIT_CODE,
	to_date('2023-12-19', 'YYYY-MM-DD') as RUN_DATE
from	AML_NWU.MAP_TAXDAILY MAP_TAXDAILY
where (1=1)
and RUN_DATE = to_date('2023-12-19', 'YYYY-MM-DD')
) nd
"""

sql_ok = """
insert /*+ HINT1*/ 
into	AML_NWU.DLT_TAXDAILY 
( 
	ORG_UNIT_CODE,
	RUN_DATE 
)
select
	MAP_TAXDAILY.ORG_UNIT_CODE as ORG_UNIT_CODE,
	to_date('2023-12-19', 'YYYY-MM-DD') as RUN_DATE
from	AML_NWU.MAP_TAXDAILY MAP_TAXDAILY
where (1=1)
and RUN_DATE = to_date('2023-12-19', 'YYYY-MM-DD')

"""

#sql = sql_nok
sql = sql_ok

column = 'RUN_DATE'
lin = lineage(column, sql, dialect='oracle')

for n in lin.walk():
  print(str(n.name) + ' - ' + str(n.expression))
```

**Comment by georgesittas** [comment]
Hey @sunrutcon, we'll need more time to figure out how we want to deal with lineage on non-queries, because it will require a bit more work than initially expected. Until then, I'm marking this one as not planned. You can work around this issue by intercepting `DDL` expressions with queries (`expression`) and then computing the lineage on the queries instead.

**Comment by sunrutcon** [comment]
What do you mean by non-query?
Could you provide me more details on workaround?

**Comment by georgesittas** [comment]
`INSERT` is not a query but rather a DML statement. It's not clear to us yet how we want to deal with such statements when it comes to lineage inference. In this particular case, fixing the issue will require refactoring some parts of the codebase, and so we'll have to think more about this before proceeding.

>  Could you provide me more details on workaround?

Sure, this is what I had in mind:

```python
import sqlglot

sql = "...."
expr = sqlglot.parse_one(sql, dialect="oracle")

if isinstance(expr, exp.DDL) and isinstance(expr.expression, exp.Query):
    expxr = expr.expression

for n in lineage("...", expr, dialect='oracle').walk():
  print(str(n.name) + ' - ' + str(n.expression))
```

**Comment by sunrutcon** [comment]
Tnx, I've tested workaround, and it is working great.
I've removed INSERT part and applied lineage on  just SELECT, and it is working as expected.

**Comment by georgesittas** [comment]
FYI @sunrutcon this was fixed in 3096.
