### ISSUE TITLE
Support for Snowflake TO_TIME , TIME

### ISSUE THREAD

**Issue by erik-farmer** [tobymao/sqlglot#3088]
**Is your feature request related to a problem? Please describe.**
The executor is not able to run queries containing `TO_TIME` , or `TIME` calls when the reader is set to `sqlglot.dialects.Snowflake`

Example:
```python
def test_time_function():
    query = "SELECT TO_TIME('13:30:00');"
    assert executor.execute(query, read=Snowflake)
```
raises:
```
>               raise ExecuteError(f"Step '{node.id}' failed: {e}") from e
E               sqlglot.errors.ExecuteError: Step 'Scan: (4541617904)' failed: name 'TO_TIME' is not defined
```

**Describe the solution you'd like**
I would like support for this function

**Describe alternatives you've considered**
I would gladly take on authoring a PR (including testing) if documentation was provided for how to implement this feature. Even if those steps were provided in this GH issue I could add them to the readme

**Additional context**
N/A

**Comment by VaggelisD** [comment]
Hi Erik,

Thanks for reporting this issue, I'll look into it. Indeed, documentation could be improved in this aspect, it's something that we are looking at lately and will be happy to accept PR's to increase it's scope.
