### ISSUE TITLE
Is there an online demo?

### ISSUE THREAD

**Issue by dashmug** [tobymao/sqlglot#3099]
**Is your feature request related to a problem? Please describe.**
I'd like to use SQLGlot's features without needing to setup a project or a notebook locally. 

**Describe the solution you'd like**
As a data analyst, I would like to go to a website powered by SQLGlot, type an SQL query (in a specific dialect) in a text box and get the equivalent SQL (for a different dialect).

**Describe alternatives you've considered**
Data Analysts can set up a local notebook to try out SQLGlot's features but that will take time. If they only need to convert a snippet of SQL code from one dialect to another, there should be a quicker way.

**Additional context**
I'm requesting this not for me but for the Data Analysts that I work with. I will build a solution for them if there's nothing like this out there yet.

Potentially, I can add it on to the SQLGlot website if that's something that could be helpful.

**Comment by georgesittas** [comment]
Hey, we haven't built a website like that, but it's not high priority for us right now. It should be easy to do it though, for example @pkit [made](https://github.com/pkit/sql-translate) https://sql-translate.tools/.

**Comment by dashmug** [comment]
Thank you. That's exactly what I need.
