### ISSUE TITLE
Oracle - INSERT ALL - Support

### ISSUE THREAD

**Issue by sunrutcon** [tobymao/sqlglot#3113]
Not sure if this is bug or should be feature, but I'll write it here :D

I'm testing sqlglot on large amount of Oracle SQL statements (SELECT, INSERT, UPDATE, MERGE,...)

One of the errors I'm getting is when trying to parse INSERT ALL statement, here is the reproduceable example:

# SQL

```SQL
-- Oracle version:
-- Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
select * from v$version;

-- will be used as source table to fetch data
create table src_tbl (
  id int, 
  col1 varchar2(50 char),
  col2 varchar2(50 char),
  col3 varchar2(50 char)
);

-- will be used as 1. target table
create table trg_tb1 (
  id int, 
  col1 varchar2(50 char),
  col2 varchar2(50 char),
  col3 varchar2(50 char)
);

-- will be used as 2. target table
create table trg_tb2 (
  id int, 
  col1 varchar2(50 char),
  col2 varchar2(50 char),
  col3 varchar2(50 char)
);

-- will be used as 3. target table
create table trg_tb3 (
  id int, 
  col1 varchar2(50 char),
  col2 varchar2(50 char),
  col3 varchar2(50 char)
);

-- insert some test data to srouce table
insert into src_tbl (id, col1, col2, col3) values (1,'trg1',null,null);
insert into src_tbl (id, col1, col2, col3) values (2,'trg1','trg2',null);
insert into src_tbl (id, col1, col2, col3) values (3,'trg1','trg2','trg3');
commit;

-- check data
select * from src_tbl order by id;

-- check target tables - should be empty
select * from trg_tb1 order by id;
select * from trg_tb2 order by id;
select * from trg_tb3 order by id;

truncate table trg_tb1;
truncate table trg_tb2;
truncate table trg_tb3;

insert /*+ append */ all
-- insert into TB1
WHEN col1 = 'trg1' THEN
INTO trg_tb1 (id, col1, col2, col3)
VALUES
(id ,col1, '*n.a.*','*n.a.*')
-- insert into TB2
WHEN col2 = 'trg2' THEN
INTO trg_tb2 (id, col1, col2, col3)
VALUES
(id ,'*n.a.*',col2,'*n.a.*')
-- insert into TB3
WHEN col3 = 'trg3' THEN
INTO trg_tb3 (id, col1, col2, col3)
VALUES
(id ,'*n.a.*','*n.a.*', col3)
-- select from SRC table
select
  id,
  col1,
  col2,
  col3
from src_tbl
;
commit;
```

# Python

```Python
import sqlglot

#Name: sqlglot
#Version: 22.2.1

sql = """
insert /*+ append */ all
-- insert into TB1
WHEN col1 = 'trg1' THEN
INTO trg_tb1 (id, col1, col2, col3)
VALUES
(id ,col1, '*n.a.*','*n.a.*')
-- insert into TB2
WHEN col2 = 'trg2' THEN
INTO trg_tb2 (id, col1, col2, col3)
VALUES
(id ,'*n.a.*',col2,'*n.a.*')
-- insert into TB3
WHEN col3 = 'trg3' THEN
INTO trg_tb3 (id, col1, col2, col3)
VALUES
(id ,'*n.a.*','*n.a.*', col3)
-- select from SRC table
select
  id,
  col1,
  col2,
  col3
from src_tbl
"""

p = sqlglot.parse_one(sql, dialect="oracle")
```

**Comment by georgesittas** [comment]
@sunrutcon please make sure to link any related documentation for future issues, so it's easier to understand the syntax.

**Comment by sunrutcon** [comment]
I hope this could help.

https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/INSERT.html#GUID-903F8043-0254-4EE9-ACC1-CB8AC0AF3423

![image](https://github.com/tobymao/sqlglot/assets/5195910/07dd9798-9d6f-4d9d-b9e3-086e7124c51f)

**Comment by meetFarmanUllah** [comment]
i also faced some problems while translating Oracle to tslq. getting below error

'SET IDENTITY_INSERT dbo.SYT_CNF_KEYS ON
INSERT [dbo].[SYT_CNF_KEYS ] ([FLD_NME], [DISP_NME], [KEY_V' contains unsupported syntax. Falling back to parsing as a 'Command'.

even if it is a correct Oracle query.

**Comment by sunrutcon** [comment]
Ok, tnx for the info!

**Comment by sunrutcon** [comment]
Hey @georgesittas, you've done great job in the branch [jo/multi_insert_oracle].
I've tested table extraction from parsed INSERT ALL, and it looks great.
Do you plan to merge it to main branch?

**Comment by georgesittas** [comment]
It's not finished, there are various issues and decided to pause it for the time being. Inserts are very commonly used and so I want to make sure the fix is implemented properly and ideally without being a breaking change.

**Comment by sunrutcon** [comment]
Thanks anyway!

**Comment by georgesittas** [comment]
@sunrutcon fixed in https://github.com/tobymao/sqlglot/commit/dedd75790ecc2549fa7b28b3612125ca2aaeb762
