### ISSUE TITLE
Quoted identifier missing while eliminating sub queries.

### ISSUE THREAD

**Issue by aniket-wisdom** [tobymao/sqlglot#3140]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Issue**
The eliminate subqueries optimizer is not handling corner case when the table alias is quoted identifier. The identifier created without quotes is a redshift keyword and thus query returned is not working.
Version: 22.0.2.dev99
Incorrect output
```
>>> from sqlglot import parse_one
>>> from sqlglot.optimizer.eliminate_subqueries import eliminate_subqueries
>>> sql_tree = parse_one('SELECT * FROM (SELECT * FROM TEST_TABLE) AS "ORDER"', dialect="redshift")
>>> eliminate_sub_query_tree = eliminate_subqueries(sql_tree)
>>> eliminate_sub_query_tree.sql(dialect="redshift")
'WITH ORDER AS (SELECT * FROM TEST_TABLE) SELECT * FROM ORDER AS ORDER'
Select(
  expressions=[
    Star()],
  from=From(
    this=Table(
      this=Identifier(this=ORDER, quoted=False),
      alias=Identifier(this=ORDER, quoted=False))),
  with=With(
    expressions=[
      CTE(
        this=Select(
          expressions=[
            Star()],
          from=From(
            this=Table(
              this=Identifier(this=TEST_TABLE, quoted=False)))),
        alias=TableAlias(
          this=Identifier(this=ORDER, quoted=False)))],
    recursive=False))
>>> 
>>> 

>>> 
````
Expected Output
WITH "ORDER" AS (SELECT * FROM TEST_TABLE) SELECT * FROM "ORDER" AS "ORDER"

ORDER is a keyword in redshift dialect.
https://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html

**Comment by tobymao** [comment]
optimizer functions are not meant to be run in isolation. you can manually quote your identifiers with qualify_columns.quote_identifiers
