### ISSUE TITLE
logo not showing properly in the docs

### ISSUE THREAD

**Issue by lostmygithubaccount** [tobymao/sqlglot#3146]
doesn't seem like the logo is showing correctly in the docs

<img width="504" alt="image" src="https://github.com/tobymao/sqlglot/assets/54814569/8a921baa-5464-4673-b2d7-96db23b4b84f">

I assume it's this line? not sure what's wrong though: https://github.com/tobymao/sqlglot/blob/main/docs/sqlglot.html#L99

**Comment by lostmygithubaccount** [comment]
perhaps just copying the SVG into `docs/sqlglot.svg`

**Comment by georgesittas** [comment]
Hooray! :-)

<img width="826" alt="Screenshot 2024-03-15 at 1 22 13 AM" src="https://github.com/tobymao/sqlglot/assets/46752250/cbb2bbc3-e811-4333-8e3b-d81e5409b063">
