### ISSUE TITLE
Support for parsed expression source code position/range

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3159]
**Is your feature request related to a problem? Please describe.**

I'm trying to integrate with LSP protocol and cannot find the source code position anywhere in the AST provided by this great no-dependency library:

```
{
    start: { line: 5, character: 23 },
    end : { line: 6, character: 0 }
}
```

See https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#range

For context:
- https://github.com/databrickslabs/ucx/pull/1067

**Comment by georgesittas** [comment]
SQLGlot only preserves this information at the token level, not in the AST itself. The latter is out of scope for us right now, but we're open to discussing potential approaches in case someone's interested to implement it.

**Comment by nfx** [comment]
@georgesittas how is it possible to access a token for an expression?

**Comment by georgesittas** [comment]
I'm not sure without digging deeper, but my guess is that it's not trivial and would probably require a refactor of the parser.
