### ISSUE TITLE
Changed pretty formatting of subqueries in 22.5 

### ISSUE THREAD

**Issue by kszucs** [tobymao/sqlglot#3164]
We updated sqlglot to 22.5 in ibis and the pretty formatted queries involving subqueries have changed:

With 22.4:

```sql
SELECT
   "t0"."x" IN (
     SELECT
       "t0"."x"
     FROM "t" AS "t0"
     WHERE
       "t0"."x" > 2
   ) AS "InSubquery(x)"
 FROM "t" AS "t0"
```

after pinning `22.5`:

```sql
SELECT
   "t0"."x" IN (SELECT
     "t0"."x"
   FROM "t" AS "t0"
   WHERE
     "t0"."x" > 2) AS "InSubquery(x)"
 FROM "t" AS "t0"
```

I wonder whether this change was intentional? If it was then feel free to close this bug report, but I find the previous formatting easier to read. It is more apparent in a [bigger query](https://github.com/ibis-project/ibis/pull/8682/files#diff-d9aabfcc274aa1054cc9314596a7ccb3ba2d2090b14b403366e5e5271bf704f6).

**Comment by tobymao** [comment]
i can't reproduce this

```
(.env) [toby@muc sqlglot]$ python -m sqlglot "select x in (select * from y) as z"
SELECT
  "x" IN (
    SELECT
      *
    FROM "y"
  ) AS "z"
```

**Comment by kszucs** [comment]
Strange, we didn't change anything else which would affect this. Let me investigate this a bit further.

**Comment by kszucs** [comment]
The ibis PR removed a `sg.transpile()` call which surfaced that we compile `In` differently as sqlglot parses it:

```py
In(this=Column(...), expressions=[Select(...)])
```

after transpile 

```py
In(this=Column(...), query=Select(...))
```

Going to fix that on our side. Sorry for the early report!
