### ISSUE TITLE
ClickHouse: fail to parse "WITH <expression> AS <identifier>"

### ISSUE THREAD

**Issue by herry13** [tobymao/sqlglot#3175]
**Description**

`sqlglot` fails to parse `WITH <expression> AS <identifier>`.

**Before you file an issue**

- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")` -- Yes, I have specified the "read" dialect.
- Check if the issue still exists on main -- I have cloned and used the latest main branch. But the issue still exists.

**Fully reproducible code snippet**

```python
import sqlglot
from sqlglot.dialects.clickhouse import ClickHouse

query = "WITH 1 AS var SELECT var"
sqlglot.maybe_parse(query, dialect=ClickHouse(), error_level=sqlglot.ErrorLevel.RAISE)
```

**Official Documentation**

Link to [WITH Clause syntax and its example](https://clickhouse.com/docs/en/sql-reference/statements/select/with#syntax) available in the ClickHouse documentation website.

**Comment by georgesittas** [comment]
Appreciate the report @herry13, we'll take a look soon.

**Comment by herry13** [comment]
@VaggelisD Thank you for fixing this!
