### ISSUE TITLE
Unable to parse with TOP statement as SQL Server

### ISSUE THREAD

**Issue by JaimeLoring** [tobymao/sqlglot#3177]
First, thanks for this amazing library. I have been struggling with several parses for SQL server dialect. I have not found a dialect amongst the available ones that suits SQL Server, mainly because of the word TOP vs LIMIT. However, following this issue  https://github.com/tobymao/sqlglot/pull/177 I have seen that the token TOP is already in the code. Digging further I found that there is a TokenType.TOP in the QUERY_MODIFIER_PARSERS constant of parser.Parser. I even think the method self._parse_limit has an argument for using TOP as delimiter.

However, the parse_one() method is not accepting my SQL Server query. I can´t set the Parser to accept TOP and I have not managed to find a working dialect or modify the arguments of the Parser in any way. I think this is a bug or something I am missunderstanding.
I would be thankful if you could explain me how can I perform a parsing as the example below. Thanks in advance.

**Fully reproducible code snippet**
from sqlglot import parse_one, exp
sql_query = 'SELECT TOP 1 abc.Discharge, COUNT(*) AS TotDischarge FROM abc GROUP BY abc.Discharge ORDER BY TotDischarge DESC'
sql_query = parse_one(sql_query).sql(pretty=True, identify=True)

**Error**
ParseError: Invalid expression / Unexpected token. Line 1, Col: 12.
  SELECT TOP 1 abc.Discharge, COUNT(*) AS TotDischarge FROM abc GROUP BY abc.DischargeORDER BY TotDischarge DESC

**Comment by georgesittas** [comment]
Hey,

You need to set the input / output dialect:

```python
>>> from sqlglot import parse_one, exp
>>> sql_query = 'SELECT TOP 1 abc.Discharge, COUNT(*) AS TotDischarge FROM abc GROUP BY abc.Discharge ORDER BY TotDischarge DESC'
>>> sql_query = parse_one(sql_query, read="tsql").sql(dialect="tsql", pretty=True, identify=True)
>>> print(sql_query)
SELECT
TOP 1
  [abc].[Discharge],
  COUNT(*) AS [TotDischarge]
FROM [abc]
GROUP BY
  [abc].[Discharge]
ORDER BY
  [TotDischarge] DESC
```
