### ISSUE TITLE
Adopting Substrait.io execution plans

### ISSUE THREAD

**Issue by davlee1972** [tobymao/sqlglot#3184]
I know sqlglot generates it's own execution plan format, but I'm wondering if it would make sense to adopt an open standard like substrait.io?

https://substrait.io/
https://substrait.io/tutorial/sql_to_substrait/

Here are some of the benefits..

Some of the SQL dialects like DuckDB, Presto, Spark, Clickhouse already support substrait plan generation so there shouldn't be a need to create these dialects within sqlglot. As more products adopt Substrait, sqlglot could support them with a lot less infrastructure code. I think the Java version of Substrait is using Calcite for a lot of the SQL parsing and conversion..

Some compute engines also support substrait plans: R Dataframes, Apache Arrow Acero, Datafusion, PyArrow Compute Expressions, Comet, etc.. You can write a SQL statement and execute it on a directory of files with a compute engine.

Substrait compatible SQL engines support substrait plan execution without having to run SQL.
https://duckdb.org/docs/extensions/substrait.html

This is essentially what sqlglot.transpile() does between SQL dialects.. but there is a open source standard for capturing the SQL logic in between the SQL dialects.

Here's a good video explaining substrait as a standard and adoption..
https://www.youtube.com/watch?v=5JjaB7p3Sjk

**Comment by tobymao** [comment]
@davlee1972 there are no plans to do this but I'm open to the idea. But i think one big gotcha is that sqlglot is pure python with no dependencies. wouldn't we need to generate protobuf?

**Comment by davlee1972** [comment]
There is tooling in python, rust, java, R, etc to generate substrait plans. Ibis is particular is a python sql wrapper.

https://pypi.org/project/substrait/

https://ibis-project.org/posts/ibis_substrait_to_duckdb/

This is interesting.. Ibis uses sqlglot to generate sql so maybe the Substrait plan generation fuctionality can be carried over..

**Comment by davlee1972** [comment]
https://github.com/ibis-project/ibis-substrait
