### ISSUE TITLE
Fails to produce SQL representation of transformed tree when a JSON key has a `-`

### ISSUE THREAD

**Issue by ZipBrandon** [tobymao/sqlglot#3185]
Having a dash in the key is valid but sqlglot warns against it and raises a `ValueError`

`2024-03-20 21:44:30 [ WARNING] Invalid JSON path syntax. Unexpected TokenType.DASH at index 1: en-US (dialect.py:485)`

` ValueError: Expected an Expression. Received <class 'bool'>: True`

```py
import sqlglot 

sql = """
    SELECT ("data" ->> 'en-US') AS "acat" FROM "my_table" 
    """
parsed_query = sqlglot.parse_one(sql, read="postgres")

def transformer(node):
    ### Actually doing stuff with the node but for example just returning it ###
    return node

transformed_tree = parsed_query.transform(transformer)

## Fails to parse with '-' in the json key.
modified_sql_query = transformed_tree.sql(dialect="postgres")
```

**Comment by tobymao** [comment]
@georgesittas it looks like ->> is calling to_json_path, but i don't think postgres ->> x is a json path, i think it's just a key
