### ISSUE TITLE
MySQL: Parsing ALTER TABLE ... MODIFY not parsed as exp.AlterTable

### ISSUE THREAD

**Issue by kosti-hokkanen-supermetrics** [tobymao/sqlglot#3186]
When parsing through a modification of existing column in MySQL dialect (datatype or not null constraint being set), I get an error message: `'ALTER TABLE test_table MODIFY COLUMN test_column LONGTEXT' contains unsupported syntax. Falling back to parsing as a 'Command'.`

This statement is found in the test suite of the dialect, so I'm not sure why it would parse as command. Expected result would be to return Expression of type AlterTable.

MySQL documentation: https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

Happy to contribute a PR if someone confirms the source of problems, but since I found this case also in the test suite, I'm not sure if there's something wrong with the tests too.

**Comment by VaggelisD** [comment]
Hi,

Thanks for reporting this issue. Regarding the test cases, I could find it under 2 places:
1. In `test_transpile.py::test_command_identity()`, which validates that the queries under it will be parsed as commands and will roundtrip (i.e parsed + generated) exactly as-is
2. In `test_mysql.py::test_ddl()` which uses a `validate_identity()` call with 2 queries; This indicates that the first query with `ALTER COLUMN` is what the SQLGlot parser will read, and the second query with `MODIFY COLUMN` matches what the MySQL Generator should write. However, the opposite direction is not always true, i.e this does not mean that `MODIFY COLUMN` is parseable syntax.

As for the `MODIFY COLUMN` MySQL syntax, it should be a relatively straightforward addition.

**Comment by kosti-hokkanen-supermetrics** [comment]
Thanks for swift support, amazing job!
