### ISSUE TITLE
Parsing does not fail on invalid syntax queries

### ISSUE THREAD

**Issue by dlahyani** [tobymao/sqlglot#3187]
** Description **

Some invalid syntax queries (in multiple dialects) are being parsed by sqlglot "successfully" returning an AST.
The expected behavior is for the Parser (or `sqlglot.parse`) to fail and raise a `ParseError` for all queries that has invalid syntax.

**Fully reproducible code snippet**
```python
import sqlglot

# Expected to raise a ParserError, instead this succeeds.
sqlglot.parse("SELECT , FROM T", dialect=sqlglot.Dialects.SNOWFLAKE)

# The returned AST:
"""
[Select(
  from=From(
    this=Table(
      this=Identifier(this=T, quoted=False))))]
"""
```

While the code samples uses Snowflake dialect, the issue is also relevant for other dialects - specifically to BigQuery and Postgres.

**Official Documentation**
Snowflake SELECT command syntax: https://docs.snowflake.com/en/sql-reference/sql/select
BigQuery SELECT command syntax: https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax
Postgres: https://www.postgresql.org/docs/current/sql-select.html

In all there engines trying to execute this query fails with a syntax error.

**Comment by georgesittas** [comment]
This is expected, SQLGlot is not a SQL validator. From the [README](https://github.com/tobymao/sqlglot/blob/main/README.md):

> However, it should be noted that SQL validation is not SQLGlot’s goal, so some syntax errors may go unnoticed.
