### ISSUE TITLE
date_trunc for Athena/Trino incorrectly truncates

### ISSUE THREAD

**Issue by rubytobi** [tobymao/sqlglot#3196]
Hi, first of all, great library! Really appreciate the hard work going into this 👍 
I noticed the Athena and Trino dialects struggle with the `date_trunc` execution. Below examples are directly from their documentation. The executed results are always the same, independent of dialect and `day` vs `month` truncation.

I hope I didn't miss anything obvious!
Thanks

**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")` ✅ - both Athena and Trino
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")` n/a
- Check if the issue still exists on main ✅ - both on the latest version as well as on master branch

**Fully reproducible code snippet**
```
from sqlglot.executor import execute
from sqlglot.dialects import Athena, Trino


def test_day_trino():
    sql = "SELECT date_trunc('day' , TIMESTAMP '2022-10-20 05:10:00')"
    result_ = execute(sql=sql, dialect=Trino)
    assert result_ == "_col_0\n2022-10-20 00:00:00.000"

# fails with: AssertionError: assert _col_0\n2022-1 == '_col_0\n2022-10-20 00:00:00.000'


def test_month_trino():
    sql = "SELECT date_trunc('month' , TIMESTAMP '2022-10-20 05:10:00')"
    result_ = execute(sql=sql, dialect=Trino)
    assert result_ == "_col_0\n2022-10-01 00:00:00.000"

# fails with: AssertionError: assert _col_0\n2022-1 == '_col_0\n2022-10-01 00:00:00.000'

def test_day_athena():
    sql = "SELECT date_trunc('day' , TIMESTAMP '2022-10-20 05:10:00')"
    result_ = execute(sql=sql, dialect=Athena)
    assert result_ == "_col_0\n2022-10-20 00:00:00.000"

# fails with: AssertionError: assert _col_0\n2022-1 == '_col_0\n2022-10-20 00:00:00.000'

def test_month_athena():
    sql = "SELECT date_trunc('month' , TIMESTAMP '2022-10-20 05:10:00')"
    result_ = execute(sql=sql, dialect=Athena)
    assert result_ == "_col_0\n2022-10-01 00:00:00.000"

# fails with: AssertionError: assert _col_0\n2022-1 == '_col_0\n2022-10-01 00:00:00.000'
```

**Official Documentation**
* https://docs.aws.amazon.com/athena/latest/ug/functions.html (just pointing to Trino docs)
* https://trino.io/docs/current/functions/datetime.html#truncation-function

**Comment by georgesittas** [comment]
Hey @rubytobi, appreciate the report but this is relatively low priority for us so I'm closing it as out of scope for now. We'll be happy to accept a well-crafted PR for it, so feel free to reach out in [Slack](https://tobikodata.com/slack) if you need assistance.
