### ISSUE TITLE
Support ClickHouse Dialect

### ISSUE THREAD

**Issue by EugeneTorap** [tobymao/sqlglot#320]
Hi @tobymao. I appreciate the project and how often you contribute it and keep sqlglot up to date.
We use sqlglot for parsing ClickHouse SQL queries and this lib works quite well but noticed some parser problems:

- CH (ClickHouse) functions: For example if we use CH function: `dictGet`, `indexOf` and so on then sqlglot make it uppercase: `DICTGET`, `INDEXOF` and CH throws error because there's no such functions in CH.
- CH `FINAL` Keyword for tables: If we write such query `SELECT * FROM users FINAL`. It works `users FINAL` will be alias but if we write `SELECT * FROM users AS u FINAL` then it throws parsing error.

@tobymao What do you think about it? Can we resolve such issues and support the CH dialect in sqlglot?

**Comment by tobymao** [comment]
i can add this initial support for clickhouse, but for other issues in the future, would you mind contributing?

**Comment by EugeneTorap** [comment]
Of course, I will support CH dialect in future
When will you add the initial CH support?

**Comment by tobymao** [comment]
@EugeneTorap main branch now supports clickhouse dialect with function name support, so dictGet now works, i'll add final in a bit, closing this for now, you can open up specific issues in the future, or simply make prs

**Comment by tobymao** [comment]
it's a bit late, i'll do it tomorrow morning
