### ISSUE TITLE
Windows line endings cause IndexOutOfRange during tokenization

### ISSUE THREAD

**Issue by mr-miles** [tobymao/sqlglot#3200]
I am parsing view and stored procedure definitions from windows-based mssql.

I am getting failures from IndexOutOfRange and strange parsing contexts where the leading character has been removed.

I think I have identified the problem + solution - are you open to a PR (with unit test)?

The issue is this:

In _advance:
https://github.com/tobymao/sqlglot/blob/a18444dbd7ccfc05b189dcb2005c85a1048cc8de/sqlglot/tokens.py#L1008

If it sees \r\n, then it sets i to 2
_current is increased by i
_char always looks at position _current-1

This can lead to it looking past the end of the source text, as _current-1 > size

I believe the fix is something like changing:
https://github.com/tobymao/sqlglot/blob/a18444dbd7ccfc05b189dcb2005c85a1048cc8de/sqlglot/tokens.py#L1022

to

```
        if self._end:
            self._peek = ""
            self._char = self.sql[self.size - 1]
        else:
            self._char = self.sql[self._current - 1]
            self._peek = self.sql[self._current]
```

**Comment by georgesittas** [comment]
Hey @mr-miles, can you share a repro for the issue first here?

**Comment by mr-miles** [comment]
Good idea!

```
from sqlglot import parse_one, exp

# find all tables (x, y, z)
for table in parse_one("SELECT * FROM x JOIN y JOIN z\r\n").find_all(exp.Table):
    print(table.name)
```

Blows up with qlglot.errors.TokenError

End the query with \r or \n on their own or some other whitespace and it is fine

**Comment by georgesittas** [comment]
I see, I can reproduce this issue - thanks!

It seems like this is an edge case that we didn't test, apparently! Namely: having the `\r\n` sequence at the end of the SQL. I'm not sure if your suggestion is the cleanest way to solve this issue, so I will probably look into this as well. Note that changes in the tokenizer must be made in both the Python and the Rust [tokenizer](https://github.com/tobymao/sqlglot/blob/main/sqlglotrs/src/tokenizer.rs).

**Comment by georgesittas** [comment]
Check out the linked PR @mr-miles.
