### ISSUE TITLE
`SORT BY` gets removed

### ISSUE THREAD

**Issue by dmelchor-stripe** [tobymao/sqlglot#3205]
**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

```python
from sqlglot import parse_one
sql = """
SELECT
    a,
    b,
    c,
    d
FROM table
GROUP BY
    3
SORT BY
    1,
    2
"""
tree = parse_one(sql, dialect="spark")
new_sql = tree.sql(dialect="spark")
print(new_sql)
```

I expect the same SQL, but instead, I get:
```sql
SELECT a, b, c, d FROM table GROUP BY 3
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
<img width="449" alt="Screenshot 2024-03-22 at 15 51 23" src="https://github.com/tobymao/sqlglot/assets/8205034/638ac961-c468-446e-821e-8818e5f9f3c2">

works for me, please make sure you update to the latest version of sqlglot / main before making an issue

**Comment by dmelchor-stripe** [comment]
Hi! Sorry this was my fault. I put in the wrong dialect:
```
>>> from sqlglot import __version__
>>> __version__
'23.0.5'
>>> from sqlglot import parse_one
>>> sql = """
... SELECT
...     a,
...     b,
...     c,
...     d
... FROM table
... GROUP BY
...     3
... SORT BY
...     1,
...     2
... """
>>> tree = parse_one(sql, dialect="trino")
>>> new_sql = tree.sql(dialect="trino")
>>> new_sql
'SELECT a, b, c, d FROM table GROUP BY 3'
```

**Comment by georgesittas** [comment]
@dmelchor-stripe can you point us to Trino documentation for `SORT BY`? This is currently "expected", in that we treat `SORT BY` as only supported by Hive, Spark, Databricks.

**Comment by dmelchor-stripe** [comment]
> @dmelchor-stripe can you point us to Trino documentation for `SORT BY`? This is currently "expected", in that we treat `SORT BY` as only supported by Hive, Spark, Databricks.

Okay I see the issue here, I guess I was expecting `SORT BY` to translate to `ORDER BY` but it's true they are not the same. Sorry for the confusion + the issue mention.
