### ISSUE TITLE
Trino - `SORT BY` gets removed:

### ISSUE THREAD

**Issue by dmelchor-stripe** [tobymao/sqlglot#3206]
**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

Sorry for the other issue, I messed up the dialect (it was Trino).

```python
from sqlglot import parse_one
sql = """
SELECT
    a,
    b,
    c,
    d
FROM table
GROUP BY
    3
SORT BY
    1,
    2
"""
tree = parse_one(sql, dialect="trino")
new_sql = tree.sql(dialect="trino")
print(new_sql)
```

I expect the same SQL, but instead, I get:
```sql
SELECT a, b, c, d FROM table GROUP BY 3
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by georgesittas** [comment]
See https://github.com/tobymao/sqlglot/issues/3205#issuecomment-2016120090

Please link docs for future issues so it's easy to cross-verify them.
