### ISSUE TITLE
Provide broad support for the SHOW COLUMNS statement

### ISSUE THREAD

**Issue by john-bodley** [tobymao/sqlglot#3218]
**Is your feature request related to a problem? Please describe.**

Per https://github.com/tobymao/sqlglot/pull/2778, it seems like @andrew-sha added support for the `SHOW COLUMNS` statement  for Snowflake, which is helpful for extracting the referenced table:

```sql
>>> parse_one("SHOW COLUMNS IN foo", read="snowflake")
Show(
  this=COLUMNS,
  scope=Table(
    this=Identifier(this=foo, quoted=False)),
  scope_kind=TABLE)
>>> _.find(exp.Table)
Table(
  this=Identifier(this=foo, quoted=False))
```

It seems—in addition to Snowflake—a number of dialects also support `SHOW COLUMNS` statements of the form, 

```sql
SHOW COLUMNS {FROM | IN} <table>
```

i.e., [MySQL](https://dev.mysql.com/doc/refman/8.0/en/show-columns.html), [Presto*](https://prestodb.io/docs/current/sql/show-columns.html)/[Trino*](https://trino.io/docs/current/sql/show-columns.html), [Spark SQL](https://spark.apache.org/docs/3.0.0-preview/sql-ref-syntax-aux-show-columns.html), etc. yet said functionality is not Supported by SQLGlot:

```python
>>> parse_one("SHOW COLUMNS FROM foo", read="trino")
Command(
  this=SHOW,
  expression=Literal(this=COLUMNS FROM foo, is_string=True))
```

I'm not overly familiar with the workings of SQLGlot, but I was wondering whether support for these statements should be handled on a per dialect basis, or should primarily be handled by the base `Dialect`?

The TL;DR is I was _thinking_ about adding support for Trino (by emulating https://github.com/tobymao/sqlglot/pull/2778) and realized that this would likely result in a lot of copypasta—especially given it seems most dialects don't implement the `show_sql` function.

\* Per the Presto/Trino documentation they only support  statements of the form`SHOW COLUMNS FROM` yet `SHOW COLUMNS IN` statements also work which could be a legacy syntax which likely also needs to be supported.

**Describe the solution you'd like**

It would be great it SQLGlot could natively handle parsing of the `SHOW COLUMNS` commands for various dialects. This would prevent others—like Apache Superset ([example](https://github.com/apache/superset/blob/4fce940a9c3566c5dded68aa5cbba26fb562ae69/superset/sql_parse.py#L788-L800))—from implementing custom logic. 

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

cc: @betodealmeida

**Comment by tobymao** [comment]
hey @john-bodley we'd love it if you added support for broad show support. in general, we try to put as much parsing code into the base parser, that way sqlglot becomes a superset parser. we only put dialect specific parsing into dialects when it is necessary because it'd be too disruptive. other options are adding flags in the base parser to toggle per dialect, we do this when there are patterns that various dialects share.

hit us up on slack if you need any help.

closing this issue as not planned as we  aren't gonig to do this as a core team, but happy to assist you as you work towards adding this.
