### ISSUE TITLE
Question. How to collapse AND or OR expression.

### ISSUE THREAD

**Issue by davlee1972** [tobymao/sqlglot#3219]
Here’s my use case..

I’ve got some naughty end users who like to pass 100 stock tickers into a sql IN clause.

What I want to do is to remove the IN clause and replace it with a temp table join where the temp table contains 100 tickers.

So far I’ve been able the create the temp table, insert 100 tickers and add it as a join.

I can also pop or remove the SQL in clause but I can’t figure out how to shift any remaining AND expressions up one level.

and_(x.eq(123), y.isin(4,5,6)) needs be replaced with just x.eq(123)

**Comment by tobymao** [comment]
check out transform, or replace methods.

https://github.com/tobymao/sqlglot/blob/main/posts/ast_primer.md

**Comment by davlee1972** [comment]
Yeah I tried transform and returned None to remove exp.In types but it converted

Where y  in (1,2,3) and x=123
To
Where and x = 123

I need to set the parent And to its child Exp = 123
