### ISSUE TITLE
语法校验的规则是什么？不太懂为什么很明显的错误都校验不出来

### ISSUE THREAD

**Issue by chaishare** [tobymao/sqlglot#323]
sqlglot.transpile("select from3 testwhere", read='mysql')  竟然没有报parse error

**Comment by tobymao** [comment]
there's no syntax error here, this is valid sql

this parses as

select from3 AS testwhere

**Comment by chaishare** [comment]
> select from3 testwhere


I don't quite understand what you said. I reported an error when I used this SQL to execute on mysql

**Comment by tobymao** [comment]
where your error and what do you think k sqlglot is at fault
