### ISSUE TITLE
Transpiling RANDOM order by between dialects

### ISSUE THREAD

**Issue by johannesboyne** [tobymao/sqlglot#3232]
Problem transpiling between different dialects using `RANDOM`:

```Python
import sqlglot

postgres_query = 'SELECT * FROM "test_table" ORDER BY RANDOM() LIMIT 5'

expected_duckd = 'SELECT * FROM "test_table" ORDER BY RANDOM() LIMIT 5'
expected_tsqlq = 'SELECT TOP 5 * FROM [test_table] ORDER BY NEWID()'
expected_bigqu = 'SELECT * FROM `test_table` ORDER BY RAND() LIMIT 5'

# duckdb:     ['SELECT * FROM "test_table" ORDER BY RANDOM() LIMIT 5']
# -> exp: ✅  ['SELECT * FROM "test_table" ORDER BY RANDOM() LIMIT 5']
assert sqlglot.transpile(postgres_query, read="postgres", write="duckdb") == [expected_duckd]

# tsql:      ['SELECT TOP 5 * FROM [test_table] ORDER BY CASE WHEN RAND() IS NULL THEN 1 ELSE 0 END, RAND()'] => "CASE WHEN RAND() IS NULL THEN 1 ELSE 0 END, RAND()" seems to be wrong
# -> exp: ❌ ['SELECT TOP 5 * FROM [test_table] ORDER BY NEWID()']
assert sqlglot.transpile(postgres_query, read="postgres", write="bigquery") == [expected_bigqu]

# (Changed later: big query change to NULLS LAST is not wrong! Just left for transparency!)
# bigquery:  ['SELECT * FROM `test_table` ORDER BY RAND() NULLS LAST LIMIT 5'] => "NULLS LAST" seems to be wrong
# -> exp: ❌ ['SELECT * FROM `test_table` ORDER BY RAND() LIMIT 5']
assert sqlglot.transpile(postgres_query, read="postgres", write="tsql") == [expected_tsqlq]
```

Very happy to provide a pull request, would just appreciate a hint into the right direction.

**Comment by tobymao** [comment]
why is nulls last wrong?

**Comment by georgesittas** [comment]
Also, the `RANDOM() -> NEWID()` conversion doesn't seem reasonable, these two do different things. I believe the current generation of `RAND()` when targeting T-SQL is correct.

**Comment by georgesittas** [comment]
The only issue I see here is the following output for the -> T-SQL direction, and that's because `RAND()` is non-deterministic.

```python
>>> import sqlglot
>>> postgres_query = 'SELECT * FROM "test_table" ORDER BY RANDOM() LIMIT 5'
>>> sqlglot.transpile(postgres_query, "postgres", "tsql")
['SELECT TOP 5 * FROM [test_table] ORDER BY CASE WHEN RAND() IS NULL THEN 1 ELSE 0 END, RAND()']
```

**Comment by johannesboyne** [comment]
From my understanding:

1. **`[NEWID](https://learn.microsoft.com/en-us/sql/t-sql/functions/newid-transact-sql?view=sql-server-ver16)()`:** Generates a new uniqueidentifier for each row when the query is executed. Since GUIDs are highly random, using `NEWID()` in an `ORDER BY` clause effectively randomizes the order of the rows. Each time the query runs, `NEWID()` produces different values for each row, leading to a different ordering.

2. **`RAND()`:** Generates a pseudo-random number between 0 and 1. When used in a query without a seed value, `RAND()` is evaluated once for the entire query, not per row. This means every row would get the same value if `RAND()` were used in the `ORDER BY` clause without additional mechanisms, failing to randomize the order of rows.

Maybe I am completely wrong wired here!

**Comment by georgesittas** [comment]
I see, so it may be more nuanced because it's used in the `ORDER BY` clause? What does postgres do there, does it evaluate `RANDOM()` for each row?

In general, you can't just arbitrarily convert Postgres' `RANDOM()` [function](https://www.postgresql.org/docs/8.2/functions-math.html) into `NEWID()`, because then you're not respecting the original semantics. This may only be useful here as a a best-effort transpilation to match the random ordering behavior, but need to understand it a bit more.

**Comment by johannesboyne** [comment]
Yes, for sure it's a bit more nuanced. Yes, in PostgreSQL, the `RANDOM()` function is evaluated for each row when used in the ORDER BY clause of a query.

Will close the issue and we will change the approach for our use case, e.g., parsing / replacing post transpiling or similar.

**Comment by georgesittas** [comment]
Sounds good. FWIW I went ahead and [changed](https://github.com/tobymao/sqlglot/pull/3233) the generator to take this case into account:

> The only issue I see here is the following output for the -> T-SQL direction, and that's because RAND() is non-deterministic.

**Comment by georgesittas** [comment]
I think it should be relatively simple to implement the `RANDOM()` -> `NEWID()` transformation in your application in any case. Look into https://github.com/tobymao/sqlglot?tab=readme-ov-file#build-and-modify-sql for custom transformations.

**Comment by johannesboyne** [comment]
Thanks a lot for the hint regarding the custom transformations!

**Comment by georgesittas** [comment]
You're welcome! Perhaps using `TABLESAMPLE` instead of ordering by `RANDOM()` can also help for your use case?
