### ISSUE TITLE
Snowflake FETCH exception during Plan

### ISSUE THREAD

**Issue by brentonmallen1** [tobymao/sqlglot#3239]
I'm seeing a `ValueError: invalid literal for int() with base 10: ''` exception when attempting to build a plan from a query that uses the snowflake FETCH function. I saw [this](https://github.com/tobymao/sqlglot/issues/285) previous issue that may help with context? The exception is thrown at [this](https://github.com/tobymao/sqlglot/blob/main/sqlglot/planner.py#L237) point in the planner.

small, reproducible example:
```
import sqlglot
from sqlglot.planner import Plan


fetch_query = 'select * from table fetch next 500 rows only'
ast = sqlglot.parse_one(fetch_query, dialect='snowflake')
Plan(ast)
```

Relavent Snowflake documentation: https://docs.snowflake.com/en/sql-reference/constructs/limit#limit-fetch

I'm not sure if I'm doing something wrong of if this is indeed a bug? Any info would be appreciated.

Thank you!

**Comment by brentonmallen1** [comment]
Looking into it a little more. it seems that the limit expression when created by the FETCH function doesn't have an `expression` arg/attribute:

![Screenshot 2024-03-28 at 10 29 26 AM](https://github.com/tobymao/sqlglot/assets/7488494/af5ba335-c497-420a-9dae-68c5dd305080)

**Comment by tobymao** [comment]
fetch isn't supported in the executor, feel free to contribute / make a pr if you need this

**Comment by brentonmallen1** [comment]
Is this something that just needs to be handled by adding an `expression` kwarg in the Snowflake [parser](https://github.com/tobymao/sqlglot/blob/main/sqlglot/parser.py#L3631) which would be picked up in the [planner](https://github.com/tobymao/sqlglot/blob/main/sqlglot/planner.py#L449)? Is there some other interaction that I need to be aware of/pointed to so that I can appreciate this potential change's impact down the line? 

I'm having difficulty putting together high level picture of how each part (parser, planner, optimizer/qualifier, executor) is intended to integrate with each other and what considerations should be kept in mind with making changes at the parser in terms of the impact down the line to the executor. Is there there something that I may have missed in the documentation that might help shine some light on this, for building confidence in contributing?

**Comment by georgesittas** [comment]
This should be relatively easy. The section you linked (L237) in planner.py needs to be adjusted in order to handle a `Fetch` expression. Right now we assume there will only be a `Limit` expression, but you can e.g. do an instance check and if `limit` is actually a `Fetch` and it has a `count` argument, then convert it into an integer. Something like that. The `NEXT` vs `FIRST` semantics will be probably a bit trickier to capture, but the above should be a good starting point.

**Comment by brentonmallen1** [comment]
that's really helpful, thank you!
