### ISSUE TITLE
Use Dialects Enum instead of literals

### ISSUE THREAD

**Issue by EugeneTorap** [tobymao/sqlglot#324]
We hardcode a dialect literal everywhere for example: "clickhouse" in:

- sqlglot.transpile(query, read="clickhouse")
- sqlglot.parse_one(query, read="clickhouse")
- parsed_query.sql(dialect="clickhouse")

I think the best approach to use a Enum for all sqlglot dialects
For example:
`from sqlglot import DialectType`
- sqlglot.transpile(query, read=DialectType.CLICKHOUSE)
- sqlglot.parse_one(query, read=DialectType.CLICKHOUSE)
- parsed_query.sql(dialect=DialectType.CLICKHOUSE)

@tobymao What do you think about it? Is it the good idea?

**Comment by tobymao** [comment]
i think this makes the api harder to use because you need another import, i think strings are easier on the api, so not inclined to force people to do this.

with regards to adding a DialectType enum to optionally use, we could do it, but i'm also not inclined to having 2 ways to do the same thing

@barakalon @izeigerman what are your thoughts here?

**Comment by tobymao** [comment]
closing this issue for now, but we can continue to discuss and the outcome of this could be an optional dialecttype, but i definitely wouldn't support forcing dialecttype in the api

**Comment by EugeneTorap** [comment]
@tobymao I guess DialectType.CLICKHOUSE will return "clickhouse" string value which don't break current API

**Comment by EugeneTorap** [comment]
You don't need another import because you can write:

```python
from sqlglot import parse_one, DialectType

parse_one(query, read=DialectType.CLICKHOUSE)
```

**Comment by EugeneTorap** [comment]
Enum is helpful to check which sqlglot support dialects and don't need to read doc for that.
Another Enum plus, you will never make a mistake in spelling a dialect name

**Comment by tobymao** [comment]
ok, sounds good, as long as it doesn't break the api, can you make a PR adding Dialect types?

**Comment by EugeneTorap** [comment]
In which sqlglot file?

**Comment by tobymao** [comment]
in sqlglot/dialects/dialect.py and make sure DialectType is imported in __init__.py so that you can do fromsqlglot import DialectType

**Comment by EugeneTorap** [comment]
@tobymao 
sqlglot/dialects/constants.py ?

**Comment by tobymao** [comment]
nah, just add it to sqlglot/dialects/dialect.py

**Comment by EugeneTorap** [comment]
Ok, got it

**Comment by EugeneTorap** [comment]
Do you have slack or discord for sqlglot?

**Comment by tobymao** [comment]
not yet, maybe next month, for now you can hit me up on discord directly captaintobs#2594

**Comment by barakalon** [comment]
Python 3.11 will have StrEnums: https://docs.python.org/3.11/library/enum.html#enum.StrEnum

Until then, I think it’s common to use multiple inheritance, first str and then Enum. Im not at a computer so I cant confirm if that will work this instant.

**Comment by EugeneTorap** [comment]
@barakalon We've added such class for that because we need to support Python 3.7, 3.8, 3.9, 3.10
```python
class LowercaseStrEnum(str, Enum):
    """
    A ``StrEnum`` where ``auto()`` will convert the name to `lowercase` to
    produce each member's value.
    """

    def _generate_next_value_(name, *_):
        return name.lower()

    def __str__(self):
        return str(self.value)
```

**Comment by barakalon** [comment]
Oops, sorry. I see I’m late to the party. Don’t mind me…
