### ISSUE TITLE
`DATETIME` `parse_one` using BigQuery dialect is incorrect

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#3251]
**Fully reproducible code snippet**

```
In [1]: import sqlglot as sg, sqlglot.expressions as sge

In [2]: sg.parse_one("DATETIME", into=sge.DataType, read="bigquery")
Out[2]: DataType(this=Type.TIMESTAMP, nested=False)
```

I would expect this to return `DataType(this=Type.DATETIME, nested=False)`.

**Official Documentation**

https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#datetime_type

**Comment by tobymao** [comment]
this is correct, bigquery datetime type maps to a sqlglot timestamp. 

call sql(dialect="bigquery") to verify.

historically, this is because timestamp maps to a spark timestamp

**Comment by cpcloud** [comment]
I'm familiar with the details of bigquery and spark re datetime, just seemed a bit surprising given that sqlglot used to return datetime.

**Comment by tobymao** [comment]
yea this was recently fixed
