### ISSUE TITLE
Parser._find_token() fails to consider '\r' as a line breaking character

### ISSUE THREAD

**Issue by plexilcrf** [tobymao/sqlglot#326]

**Comment by plexilcrf** [comment]
Sorry, hit Return while typing the issue title.

Tokenizer considers any line breaking character as the start of a new line. Parser._find_token() only considers '\n' as a line breaking character. In SQL containing '\r' or '\r\n' line endings, this causes parse errors to be reported at the wrong location.

**Comment by tobymao** [comment]
v4.5.1
