### ISSUE TITLE
Running "optimize" with only merge_subqueries rule results in wrong SQL

### ISSUE THREAD

**Issue by daniel769** [tobymao/sqlglot#3263]
For the following input SQL:

```sql
select "customers.c_nationkey" as "nation",
    "C1",
    "C2"
from 
(
    select "customers.c_nationkey",
        sum("C2") as "C1",
        sum("C1") as "C2"
    from 
    (
        select "customers.c_nationkey",
            "order_lines.count_outstanding" as "C1",
            "order_lines.revenue" as "C2"
        from "world"."world"
         
    ) as "ITBL"
    group by "customers.c_nationkey"
) as "ITBL"
where not "C1" is null or not "C2" is null
 LIMIT 1000001
```

running the following code:
```python
RULES = (
    merge_subqueries,
)
parsed = parse_one(sql, dialect=Dialects.TRINO)
parsed = optimize(parsed, dialect="trino",rules=RULES)
sql = parsed.sql(pretty=True)
```

The source columns are truncated and the output SQL is
```sql
SELECT
  "customers.c_nationkey" AS "nation",
  "C1",
  "C2"
FROM (
  SELECT
    "customers.c_nationkey",
    SUM("C2") AS "C1",
    SUM("C1") AS "C2"
  FROM "world"."world"
  GROUP BY
    "customers.c_nationkey"
) AS "ITBL"
WHERE
  NOT "C1" IS NULL OR NOT "C2" IS NULL
LIMIT 1000001
```

instead of the expected output:
```sql
SELECT
  "itbl"."customers.c_nationkey" AS "nation",
  "itbl"."c1" AS c1,
  "itbl"."c2" AS c2
FROM (
  SELECT
    world."customers.c_nationkey" AS "customers.c_nationkey",
    SUM(world."order_lines.revenue") AS "c1",
    SUM(world."order_lines.count_outstanding") AS "c2"
  FROM "world"."world" AS world
  GROUP BY
    world."customers.c_nationkey"
) AS "itbl"
WHERE
  NOT "itbl"."c1" IS NULL OR NOT "itbl"."c2" IS NULL
LIMIT 1000001
```

The last one was generated when adding the qualify optimization rule:
```python
RULES = (
    qualify,
    merge_subqueries,
)
```

However, it seems that a rule should be a standalone and not depend on prior rules.
In addition the qualify rule by itself changes the query and sometimes it's not the desired behavior.
 - unaliased output column will get default "_col_<i>" output names
 - Expanding select star

The first artifact is more severe, since it effects the result of the query (different names vs unaliased output columns)
for example in this query:
```sql
SELECT 
    "customers.c_nationkey", 
    count("orders.order_id")
FROM world.world
GROUP BY 1
```

becomes:
```sql
SELECT
  world."customers.c_nationkey" AS "customers.c_nationkey",
  AGG(world."order_lines.revenue") AS _col_1
FROM world.world AS world
GROUP BY
  world."customers.c_nationkey"
```

**Comment by georgesittas** [comment]
Rules such as `merge_subqueries` are not meant to run in isolation, unless you know what you're doing. Even running `qualify` before it is not guaranteed to produce valid SQL, I think.

The rules that should work "fine" are `qualify`, and then `annotate_types` (after you qualify the query). Both of the bullets in your description seem to be expected behavior imo. There's an option called `expand_stars` which you can deactivate if you don't want the star expansion to happen.

If there's an issue with either just `qualify` or the full optimizer, please post in this thread and we'll look into it. Otherwise imo there's no issue here AFAICT and I'll go ahead and close the ticket.

In any case, thanks for the report!

**Comment by daniel769** [comment]
> Rules such as `merge_subqueries` are not meant to run in isolation, unless you know what you're doing. I believe that even running `qualify` beforehand is not guaranteed to produce valid SQL, @tobymao or @barakalon please correct me if I'm wrong here.
> 
> Some "important" rules that we expect to work just fine are `qualify` and `annotate_types` afterwards. You can also generally run `simplify` on an AST.
> 
> Both of the bullets in your description seem to be expected behavior imo. There's an option called `expand_stars` which you can set to `False` if you don't want the star expansion to happen.
> 
> If there's an issue with either just `qualify` or the full optimizer, please post in this thread and we'll look into it. Otherwise imo there's no issue here AFAICT and I'll go ahead and close the ticket.
> 
> In any case, thanks for the report!

The issue shouldn't be closed IMO.
Since you pointed out that qualify rule is mandatory, and should work as is, and in addition it needs to be in the rules set, for other rules to work. 
Main problem is that it adds default output aliases. This is an unexpected artifact on the result, as the header will be modified, something that an optimizer rule shouldn't do by default IMO. This isn't a dialect specific as stated in another comment, but a general behavior by the optimizer.
Does the output aliases required for later rules, or can it be enabled by a flag?
If it's possible to be optional, please reopen this issue.

**Comment by tobymao** [comment]
what you’re looking for isn’t in scope of the optimizer. it’s functioning as designed. 
additionally it’s documented that rules cannot be run in isolation unless you know what you’re doing.

**Comment by barakalon** [comment]
> This is an unexpected artifact on the result, as the header will be modified

Depends on the use case. I think an option to disable automatic aliasing of the top most query makes sense. We'd welcome that contribution.

> This isn't a dialect specific as stated in another comment

All engines automatically pick an alias if one is not set, and the rules for picking aren't standard.

> Does the output aliases required for later rules, or can it be enabled by a flag?

It _might_ be referenced by some other rules... but if so, it shouldn't be anything that hard to work around.

> If there's an expand star operation, it would be nice to have a reverse transformation as "fold to star", to return the query to its prior way of writing.

Why don't you want to expand stars? Maybe you're inferring the schema?

"Folding to star" would certainly require the schema.

You could also implement you own transformations that do this kind of thing, for your specific use case.

**Comment by daniel769** [comment]
> what you’re looking for isn’t in scope of the optimizer. it’s functioning as designed. additionally it’s documented that rules cannot be run in isolation unless you know what you’re doing.
Understood, but in the documentation of the optimize function, it only states that the custom set of rules, requires that "qualify" rule will be in the sequence. It doesn't state that running optimize with custom set of rules such as `["qualify", <some_rule>]` is not guaranteed to work, or that there can be some unexpected artifacts, such as added aliases "_col_i" in case no aliases were provided in the output columns.
