### ISSUE TITLE
Sybase TSQL Support

### ISSUE THREAD

**Issue by davlee1972** [tobymao/sqlglot#3274]
Can we create a separate dialect for Sybase based on TSQL? Both Sybase and Microsoft SQL Server shared the same transact-sql dialect back in the 2000s, but they have diverged..

If we can't create a separate dialect then what is the best way to inject a "sybase" dialect into sqlglot?
Right now I'm just replacing the TSQL generator with a modified one, but I would like to keep them separate..

Changes made to support python datetime in Sybase:
1. Sybase does not have a DATETIME2 type. It uses a BIGDATETIME type which is the TSQL equivalent.
2. Sybase does not support any type of timezone info. You have to adjust the time by any local timezone difference relative to the server timezone in your application before passing it to the server. "2024-04-04T04:51:31.420156+00:00" cannot be parsed by Sybase unless "+00:00" is stripped first..

Valid sql after the changes:
action_date >= CAST('2024-04-04T04:51:31.420156' AS BIGDATETIME)

```

# fix TSQL parsing for date and datetime
class SybaseGenerator(TSQL.Generator):

    TYPE_MAPPING = TSQL.Generator.TYPE_MAPPING
    TYPE_MAPPING[sqlglot.exp.DataType.Type.DATETIME] = "BIGDATETIME"
    TYPE_MAPPING[sqlglot.exp.DataType.Type.TIMESTAMP] = "BIGDATETIME"

    TRANSFORMS = TSQL.Generator.TRANSFORMS
    TRANSFORMS[sqlglot.exp.DateStrToDate] = sqlglot.dialects.dialect.datestrtodate_sql
    TRANSFORMS[sqlglot.exp.TimeStrToTime] = lambda self, e: self.sql(
        sqlglot.exp.cast(
            sqlglot.exp.Literal.string(
                datetime.isoformat(datetime.fromisoformat(e.this.this).replace(tzinfo=None))
            ),
            to="TIMESTAMP"
        )
    )

# Need a better solution to create a real Sybase dialect here instead of replacing TSQL.
sqlglot.dialects.tsql.TSQL.Generator = SybaseGenerator

```

**Comment by georgesittas** [comment]
The way to do this is to [subclass](https://github.com/tobymao/sqlglot/blob/8d87d11174df61a49af23042d94b6be24282d29e/sqlglot/dialects/__init__.py#L25) `T-SQL` and override its functionality to conform to Sybase's spec. This is out of scope for us, but we're open to accepting a well-crafted PR.

**Comment by davlee1972** [comment]
Ok. Thanks for the subclass link.. I was digging around forever..

Just some history and my personal journey..

In the 1990s, Sybase was the best RDBMS in the market and most major financial firms adopted it.
In the 2000s, Oracle was the best RDBMS and was adopted by most tech firms during the dot com era.
Now in the 2020s, Microsoft SQL Server is gaining popularity as part of Microsoft's Azure cloud offering.

https://en.wikipedia.org/wiki/Adaptive_Server_Enterprise

In 1988, Sybase, [Microsoft](https://en.wikipedia.org/wiki/Microsoft) and [Ashton-Tate](https://en.wikipedia.org/wiki/Ashton-Tate) began development of a version of SQL Server for [OS/2](https://en.wikipedia.org/wiki/OS/2), but Ashton-Tate later left the group and Microsoft went on to port the system to [Windows NT](https://en.wikipedia.org/wiki/Windows_NT). When the agreement expired in 1993, Microsoft purchased a license for the source code and began to sell this product as [Microsoft SQL Server](https://en.wikipedia.org/wiki/Microsoft_SQL_Server).[[2]](https://en.wikipedia.org/wiki/Adaptive_Server_Enterprise#cite_note-2) MS SQL Server and Sybase SQL Server share many features and syntax peculiarities.

**Comment by davlee1972** [comment]
Ok here's my code for a Sybase class. I'm not submitting a PR since I'm not sure what other differences between TSQL and Sybase are out there.. This class is also inherited from TSQL and not a standalone dialect.. I'm sure I'll bump into other TSQL differences which need fixing as this gets used..

```
# create a Sybase Dialect class off TSQL (ms_sql) 
class Sybase(TSQL):
    class Generator(TSQL.Generator):

        TYPE_MAPPING = TSQL.Generator.TYPE_MAPPING
        TYPE_MAPPING[sqlglot.exp.DataType.Type.DATETIME] = "BIGDATETIME"
        TYPE_MAPPING[sqlglot.exp.DataType.Type.TIMESTAMP] = "BIGDATETIME"

        TRANSFORMS = TSQL.Generator.TRANSFORMS
        TRANSFORMS[sqlglot.exp.DateStrToDate] = sqlglot.dialects.dialect.datestrtodate_sql
        TRANSFORMS[sqlglot.exp.TimeStrToTime] = lambda self, e: self.sql(
            sqlglot.exp.cast(
                sqlglot.exp.Literal.string(
                    datetime.isoformat(datetime.fromisoformat(e.this.this).replace(tzinfo=None))
                ),
                to="TIMESTAMP"
            )
        )
```
