### ISSUE TITLE
Invalid datediff when converting from presto to spark

### ISSUE THREAD

**Issue by williaster** [tobymao/sqlglot#3279]
**Before you file an issue**
- [x] Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- [x] Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- [x] Check if the issue still exists on main

**Fully reproducible code snippet**
It looks like the `spark` version of `datediff` doesn't have a unit, so when converting from `presto` syntax **with** a unit the query fails in `spark`. I'm not exactly sure how this would be handled since it seems like the only supported conversion between the two would be `days` 🤔 

`presto` input
```sql
SELECT DATE_DIFF('day', ds_a, ds_b) FROM table
```

`spark` output
```sql
SELECT DATEDIFF(DAY, ds_a, ds_b) FROM table
```
> AnalysisException: cannot resolve '`DAY`' given input columns

the expected output would be `SELECT DATEDIFF(ds_a, ds_b) FROM table`

`sqlglot`
```py
from sqlglot import parse_one

parse_one("SELECT DATE_DIFF('day', ds_a, ds_b) FROM table", dialect="presto").sql(dialect="spark")
```

**Official Documentation**
- [spark `datediff`](https://spark.apache.org/docs/latest/api/sql/#datediff)
- [presto `date_diff`](https://prestodb.io/docs/current/functions/datetime.html#date_diff)

**Comment by williaster** [comment]
I do see https://github.com/tobymao/sqlglot/issues/2426 which seems similar for `month`s. is it possible the `month` unit is supported (although not documented) but `day` isn't?

**Comment by tobymao** [comment]
spark3 supports datediff with a unit

```
>>> spark.sql("select datediff(day, '2020-01-04', '2020-01-05') as x").collect()
[Row(x=1)]
```

spark2 and hive don't, if you want that behavior you need to specify that dialect.

```
python -m sqlglot "date_diff('day', a, b)" --read=presto --write=spark2
DATEDIFF(`b`, `a`)
```

**Comment by williaster** [comment]
ah this is perfect thank you 🙏
