### ISSUE TITLE
Presto. Qualify alias name is treated as a special expression

### ISSUE THREAD

**Issue by bkyryliuk** [tobymao/sqlglot#3287]
**Before you file an issue**
- [x] Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- [x] Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- [ ]  Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```
import sqlglot

asts = sqlglot.parse(q, dialect='presto')
q = """select count(distinct table_a.cola)
from (select * from table_a) alias_b
join
(
  select distinct cola from table_b
    where sku_plan_type = 'BASIC'
    and locale in ('en', 'en_GB')

) qualify
on alias_b.cola = qualify.cola
LIMIT 11"""
asts = sqlglot.parse(q, dialect='presto')
```

Error: 
```
ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.Qualify'>. Line 10, Col: 2.
  ct cola from table_b
    where sku_plan_type = 'BASIC'
    and locale in ('en', 'en_GB')

) qualify
on alias_b.cola = qualify.cola
LIMIT 11
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
@bkyryliuk thanks for the report. would appreciate PRs in the future for small things like this.

**Comment by bkyryliuk** [comment]
We will do our best, right now I don't have capacity for it / codebase familiarity. Would you still prefer bugs to be filed ?

**Comment by tobymao** [comment]
yes, as long as the reports contain all the information i need, like documentation, expected behavior, what expected out come is thanks!

**Comment by bkyryliuk** [comment]
sounds good, will do
