### ISSUE TITLE
Teradata datetime functions

### ISSUE THREAD

**Issue by maureen-daum** [tobymao/sqlglot#3296]
Teradata has numerous issues when transpiling from other dialects, particularly around date functions. 

I opened https://github.com/tobymao/sqlglot/pull/3295 to address a number of issues:
* Syntax error when casting to DOUBLE
* Syntax error when using `CURRENT_TIMESTAMP()`
* Translate date_add/date_sub to interval addition/subtraction
* Support week/quarter intervals
* Support extract(quarter)

The one remaining issue that I know of that I'm not sure how to tackle is the following case, where `QUARTER(date_col)` could be parsed as `EXTRACT(QUARTER FROM date_col)` (and then transpiled to the teradata `to_char` expression):
```
query = "QUARTER(date_col)"
sqlglot.parse_one(query).sql(dialect="teradata") == "CAST(TO_CHAR(date_col, 'Q') AS INT)"
```

**Comment by georgesittas** [comment]
Fixed in https://github.com/tobymao/sqlglot/commit/b28cd89823a38f3a90c57344a44719364d66d723
