### ISSUE TITLE
order of logical operation is not interpreted correctly

### ISSUE THREAD

**Issue by khabiri** [tobymao/sqlglot#3298]
```
from sqlglot import optimizer, parse_one

sql = "select * from t where a=1 and b=1 or c=1 and d=1"
q = parse_one(sql, "postgres")
oq = optimizer.optimize(q, dnf=True, dialect="postgres")

print ("oq", oq)
```
will result in 
```
SELECT * FROM "t" AS "t" WHERE ("t"."a" = 1 AND "t"."b" = 1 AND "t"."d" = 1) OR ("t"."c" = 1 AND "t"."d" = 1)
```

Which means that 
```a^b V c^d```
 is interpreted as 
```(a^b^d) V (c^d) = (a^b V c)^d``` 
The desired interpretation should be:
```(a^b) V (c^d)```

**Comment by georgesittas** [comment]
SQLGlot's parser does not assume either CNF or DNF - it expects expressions that mix `AND` and `OR` to disambiguate their relative precedence using parentheses. For example:

```python
>>> import sqlglot
>>> sqlglot.parse_one("a and b or c and d")
And(
  this=Or(
    this=And(
      this=Column(
        this=Identifier(this=a, quoted=False)),
      expression=Column(
        this=Identifier(this=b, quoted=False))),
    expression=Column(
      this=Identifier(this=c, quoted=False))),
  expression=Column(
    this=Identifier(this=d, quoted=False)))
```

@tobymao I believe that in the past we suggested using parentheses. Is this still true, or does this look like something we need to fix? It would mean we need to split `_parse_conjunction` into two levels of precedence and assume either normal form. I'm also not sure whether the normal form assumed by dialects is consistent, but my expectation is that it's not.

**Comment by tobymao** [comment]
right, still the same. the sql spec says to use parenthesis

**Comment by achillefokoue** [comment]
@khabiri,  thanks for reporting this issue.
@georgesittas , thanks for your comment! 

I agree that the parser should not expect CNF or DNF. However, when parentheses are not provided, it should enforce the standard operator precedence. According to [1] and [2], AND has a higher precedence than OR,  and should be evaluated first. Thus, the parser should parse the expression as (a AND b) OR (c AND d). 

[1] https://ramkedem.com/en/sql-server-and-or/
[2] https://learn.microsoft.com/en-us/sql/t-sql/language-elements/operator-precedence-transact-sql?view=sql-server-ver16

**Comment by khabiri** [comment]
@georgesittas 
@tobymao
Thank you for your comments.

We are currently using LLM to generate the SQL commands. Enforcing LLM to add parenthesis to its query when it is not needed, is not always possible. 

I am sure there are many other projects that are using LLM to generate SQL queries and therefore, the ability of SQLglot to deal with such cases will be very critical at this era. 

LLM creates the commands based on SQL spec which observes the precedence of AND to OR even without usage of the parenthesis.
