### ISSUE TITLE
Precedence of AND over OR is ignored

### ISSUE THREAD

**Issue by michael-leanix** [tobymao/sqlglot#330]
Minimal example:
`sqlglot.parse("SELECT * FROM foo WHERE a=1 OR a=3 AND b=2")`

As `AND` has precedence over `OR` in SQL (https://www.postgresql.org/docs/7.0/operators.htm, https://dev.mysql.com/doc/refman/8.0/en/operator-precedence.html), I'd expect the `WHERE` part to be interpreted as `a=1 OR (a=3 AND b=2)`. Instead it seems to be interpreted from left to right, i.e. the `OR` binds before the `AND` (`(a=1 OR a=3) AND b=2`). This also happens when I set the dialect to Postgres explicitly. Here's the `str` representation of the parse output:
```
[(SELECT expressions: 
   (STAR ), from: 
   (FROM expressions: 
     (TABLE this: 
       (IDENTIFIER this: foo, quoted: False))), where: 
   (WHERE this: 
     (AND this: 
       (OR this: 
         (EQ this: 
           (COLUMN this: 
             (IDENTIFIER this: a, quoted: False)), expression: 
           (LITERAL this: 1, is_string: False)), expression: 
         (EQ this: 
           (COLUMN this: 
             (IDENTIFIER this: a, quoted: False)), expression: 
           (LITERAL this: 3, is_string: False))), expression: 
       (EQ this: 
         (COLUMN this: 
           (IDENTIFIER this: b, quoted: False)), expression: 
         (LITERAL this: 2, is_string: False)))))]
```

Is this a bug or is it considered out of scope for SQLGlot?

**Comment by tobymao** [comment]
i'd consider this out of scope because operator precedence is not always clearly defined. it's considered best practice to have parenthesis around and and ors.

however, if you were to make a PR that adds easily overridable precedence i would accept it.

closing this as won't fix for now but happy to chat more.
