### ISSUE TITLE
Solving: 'Union' object has no attribute 'order_by'

### ISSUE THREAD

**Issue by williaster** [tobymao/sqlglot#3300]
Filed this as a request as I'm not sure if it's a bug or by design.

**Is your feature request related to a problem? Please describe.**
Basically I'm trying to add an `order by` clause to a union which is valid, but when using the `sqlglot` primitives it's not straight forward.

The following approaches both give the error `AttributeError: 'Union' object has no attribute 'order_by'`
```py
import sqlglot

select = sqlglot.parse_one("select * from hi union select * from hello")

select.order_by('ts').sql()
sqlglot.parse_one(select.sql()).order_by('ts').sql()
```

But the following works
```py
# ...
sqlglot.parse_one(f'{select.sql()} order by ts').sql()
# prints 'SELECT * FROM hi UNION SELECT * FROM hello ORDER BY ts'
```

**Describe the solution you'd like**
Should the `union` interface match the general `select` interface?

**Describe alternatives you've considered**
See above

**Comment by tobymao** [comment]
at the time it was by design. but i guess i'll change it now

**Comment by williaster** [comment]
thanks again toby! 🙏
