### ISSUE TITLE
"NOT BETWEEN" not supported

### ISSUE THREAD

**Issue by LoganDark** [tobymao/sqlglot#3312]
**Fully reproducible code snippet**

```
>>> sqlglot.parse_one('select x from y where z not between 5 and 10', read = 'postgres')
(SELECT expressions:
  (COLUMN this:
    (IDENTIFIER this: x, quoted: False)), from:
  (FROM this:
    (TABLE this:
      (IDENTIFIER this: y, quoted: False))), where:
  (WHERE this:
    (NOT this:
      (BETWEEN this:
        (COLUMN this:
          (IDENTIFIER this: z, quoted: False)), low:
        (LITERAL this: 5, is_string: False), high:
        (LITERAL this: 10, is_string: False)))))
>>> _.sql(dialect = 'postgres')                                                                                                                       
'SELECT x FROM y WHERE NOT z BETWEEN 5 AND 10'
```

[`between`](https://sqlglot.com/sqlglot/expressions.html#Expression.between) and [`Between`](https://sqlglot.com/sqlglot/expressions.html#Between) probably need a corresponding `not_between` and `NotBetween`

**Official Documentation**
https://www.postgresql.org/docs/current/functions-comparison.html#FUNCTIONS-COMPARISON-PRED-TABLE

**Comment by georgesittas** [comment]
What's the issue with the generated SQL? Aren't the two forms equivalent?

**Comment by LoganDark** [comment]
I'm not too familiar with SQL, but wouldn't this be testing if `(NOT z) BETWEEN 5 AND 10` rather than `z NOT BETWEEN 5 AND 10`?

**Comment by georgesittas** [comment]
That doesn't really make sense to me, what would be the point of `NOT` having higher precedence than `BETWEEN` here? That's essentially checking if a boolean is within a given range.

I think both forms are equivalent. The conversion is expected, SQLGlot aims to produce equivalent canonical SQL and in this case `NOT` wraps the predicate expression, thus it's moved to the left. See also: https://github.com/tobymao/sqlglot/discussions/274.

I'll go ahead and close this as a non-issue, but happy to reopen it if you find that the two forms are not equivalent.

**Comment by LoganDark** [comment]
> That doesn't really make sense to me, [...] That's essentially checking if a boolean is within a given range.

Yes, that's exactly what prompted me to open an issue about it. lol

> I think both forms are equivalent. [...] See also: https://github.com/tobymao/sqlglot/discussions/274.

Thanks. I never expected SQLGlot to produce identical code, but in this case it looked like it was changing the meaning of the code which would definitely be a bug.

If the meaning of the code is not changed then I agree with the closure (I would have closed it myself, fwiw).

Thanks for the reference.

**Comment by georgesittas** [comment]
Yep, sure thing - appreciate the report!

FWIW I run a few simple queries against Postgres to verify both forms produce the same result:

```
georgesittas=# select not 2 between 1 and 3;
 ?column?
----------
 f
(1 row)

georgesittas=# select 2 not between 1 and 3;
 ?column?
----------
 f
(1 row)

georgesittas=# select 4 not between 1 and 3;
 ?column?
----------
 t
(1 row)

georgesittas=# select not 4 between 1 and 3;
 ?column?
----------
 t
(1 row)
georgesittas=# select not null between 1 and 3;
 ?column?
----------

(1 row)

georgesittas=# select null not between 1 and 3;
 ?column?
----------

(1 row)
```
