### ISSUE TITLE
Hive's CREATE TABLE SQL comments and storage format in the output of  statement are formatted incorrectly.

### ISSUE THREAD

**Issue by PaienNate** [tobymao/sqlglot#3323]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
```python
import sqlglot

from sqlglot import exp,parse,parse_one
from sqlglot.optimizer import optimize


#    # 替换为你的 SQL 文件路径
#    sql_file_path = 'SQL_CREATE\\example.sql'
#    parse_sql_file(sql_file_path)
def parse_sql_file(file_path):
    with open(file_path, 'r',encoding='utf-8') as file:
        sql_content = file.read()
        parsed = parse(sql_content,read='hive')
        for parse_node in parsed:
            test_parse = parse_node.transform(transformer)
            print(optimize(test_parse.sql(dialect='hive')).sql(pretty=True))


def transformer(node):
    if isinstance(node, exp.Table):
        return parse_one(node.name + "_A")
    return node


if __name__ == '__main__':
    parse_sql_file("SQL_CREATE\\EXAMPLE.SQL")
```
Example SQL:
```sql
CREATE TABLE xxxx.yyyyyyyy
(
    id     STRING comment "ID",
    name   STRING COMMENT "名称",
    rate DOUBLE comment "比率",
    update_time STRING comment "更新时间"
) COMMENT "天表"
    STORED AS ORC;
```
Output:
```sql
CREATE TABLE "xxxx.yyyyyyyy_A" (
  "id" TEXT COMMENT 'ID',
  "name" TEXT COMMENT '名称',
  "rate" DOUBLE COMMENT '比率',
  "update_time" TEXT COMMENT '更新时间'
)
COMMENT='天表' --WRONG HERE
WITH (
  FORMAT=ORC -- WRONG HERE
)
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DML#LanguageManualDML-Loadingfilesintotables

**Comment by PaienNate** [comment]
> **Before you file an issue**
> 
> * Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
> * Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
> * Check if the issue still exists on main
> 
> **Fully reproducible code snippet**
> 
> ```python
> import sqlglot
> 
> from sqlglot import exp,parse,parse_one
> from sqlglot.optimizer import optimize
> 
> 
> #    # 替换为你的 SQL 文件路径
> #    sql_file_path = 'SQL_CREATE\\example.sql'
> #    parse_sql_file(sql_file_path)
> def parse_sql_file(file_path):
>     with open(file_path, 'r',encoding='utf-8') as file:
>         sql_content = file.read()
>         parsed = parse(sql_content,read='hive')
>         for parse_node in parsed:
>             test_parse = parse_node.transform(transformer)
>             print(optimize(test_parse.sql(dialect='hive')).sql(pretty=True))
> 
> 
> def transformer(node):
>     if isinstance(node, exp.Table):
>         return parse_one(node.name + "_A")
>     return node
> 
> 
> if __name__ == '__main__':
>     parse_sql_file("SQL_CREATE\\EXAMPLE.SQL")
> ```
> 
> Example SQL:
> 
> ```sql
> CREATE TABLE xxxx.yyyyyyyy
> (
>     id     STRING comment "ID",
>     name   STRING COMMENT "名称",
>     rate DOUBLE comment "比率",
>     update_time STRING comment "更新时间"
> ) COMMENT "天表"
>     STORED AS ORC;
> ```
> 
> Output:
> 
> ```sql
> CREATE TABLE "xxxx.yyyyyyyy_A" (
>   "id" TEXT COMMENT 'ID',
>   "name" TEXT COMMENT '名称',
>   "rate" DOUBLE COMMENT '比率',
>   "update_time" TEXT COMMENT '更新时间'
> )
> COMMENT='天表' --WRONG HERE
> WITH (
>   FORMAT=ORC -- WRONG HERE
> )
> ```
> 
> **Official Documentation** Please include links to official SQL documentation related to your issue. https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DML#LanguageManualDML-Loadingfilesintotables

Actually, another wrong here:
```sql
CREATE TABLE "xxxx.yyyyyyyy_A" ( -- should be: xxxx.yyyyyyyy, without quotation mark
  "id" TEXT COMMENT 'ID', -- should be "STRING" not "TEXT", and without quotation mark here
  "name" TEXT COMMENT '名称', 
  "rate" DOUBLE COMMENT '比率',
  "update_time" TEXT COMMENT '更新时间'
)
COMMENT='天表' --WRONG HERE
WITH (
  FORMAT=ORC -- WRONG HERE
)
```

**Comment by VaggelisD** [comment]
Hi @PaienNate,

You need to also define a write dialect in `.sql()` in order to get proper Hive back:

```
...
ast.sql(dialect='hive')).sql(dialect="hive", pretty=True)
```

Can you retry your queries and report any new issues ?

**Comment by PaienNate** [comment]
> ```python
> sql(dialect='hive')
> ```

Works well, sorry for my mistake.
