### ISSUE TITLE
BigQuery: `*` turns into `6` in PARSE_TIMESTAMP format string 

### ISSUE THREAD

**Issue by schmee-td** [tobymao/sqlglot#3328]
**Before you file an issue**
- [x] Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- [x] Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- [x] Check if the issue still exists on main

**Fully reproducible code snippet**

```python
import sqlglot

parsed = sqlglot.parse_one("select PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E*S%Ez', '2024-04-06T02:37:21.155304676Z')", read="bigquery")
print(parsed.sql("bigquery"))
```

Output:
```sql
SELECT PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%E6S%Ez', '2024-04-06T02:37:21.155304676Z')
```

Note how the `%E*S` in the input turned into `%E6S` in the output. The input SQL runs successfully in the BigQuery console, but the output from SQLGlot fails with this error:

```
Failed to parse input string "2024-04-06T02:37:21.155304676Z"
```

I would expect the `%E*S` in the input string to be preserved since replacing it with `6` changes the semantics.

Thank you for all your hard work on SQLGlot! ❤️

**Official Documentation**

[Format elements  |  BigQuery  |  Google Cloud](https://cloud.google.com/bigquery/docs/reference/standard-sql/format-elements#format_elements_date_time)

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/eb8d7b80c74850d791ac51a117ed5381b3431b3b
