### ISSUE TITLE
Conjunction precedence issue: and/or evaluation order

### ISSUE THREAD

**Issue by anil-panicker** [tobymao/sqlglot#3335]
The ast for condition expression seems to build based on the ordering of the operators while most sql dialects evaluates AND first. 
i.e., both "a or b and c" and "b and c or a" should resolve to "a or (b and c)" and "(b and c) or a" respectively. 

Hence, both these conditions should have a root node of `And`. Linking snowflake and t-sql documentation.

**Fully reproducible code snippet**
```
print(sqlglot.parse("a or b and c"))
[And(
  this=Or(
    this=Column(
      this=Identifier(this=a, quoted=False)),
    expression=Column(
      this=Identifier(this=b, quoted=False))),
  expression=Column(
    this=Identifier(this=c, quoted=False)))]


print(sqlglot.parse("b and c or a"))
[Or(
  this=And(
    this=Column(
      this=Identifier(this=b, quoted=False)),
    expression=Column(
      this=Identifier(this=c, quoted=False))),
  expression=Column(
    this=Identifier(this=a, quoted=False)))]
```

**Official Documentation**
https://docs.snowflake.com/en/sql-reference/operators-logical
https://learn.microsoft.com/en-us/sql/t-sql/language-elements/operator-precedence-transact-sql?view=sql-server-ver16

**Comment by tobymao** [comment]
this is out of scope for now, i believe the sql standard doesn't define these and recommends you use parenthesis
