### ISSUE TITLE
Sqlglot does not preserve Snowflake comments format and merges them into one line

### ISSUE THREAD

**Issue by baruchoxman** [tobymao/sqlglot#3337]
For example:
sql = "-- comment1\n-- comment2\nselect * from table"
sql_expr = parse_one(sql, dialect=Dialects.SNOWFLAKE)
new_sql = sql_expr.sql(dialect=Dialects.SNOWFLAKE, pretty=True)

new_sql is:
/* comment1 */ /*comment2 */\nselect * from table

I'd like the comments formatting from the original sql to be preserved in such a case, or at least the line break between the comments to be preserved

**Comment by tobymao** [comment]
this isn’t in scope of sqlglot, comments are best effort
