### ISSUE TITLE
[feature request] Support Trino FUNCTION declaration

### ISSUE THREAD

**Issue by kevinjqliu** [tobymao/sqlglot#3349]
**Is your feature request related to a problem? Please describe.**
Add the ability to parse Trino FUNCTION as valid SQL. 
Example:
```
FUNCTION simple_case(a bigint)
  RETURNS varchar
  BEGIN
    CASE a
      WHEN 0 THEN RETURN 'zero';
      WHEN 1 THEN RETURN 'one';
      ELSE RETURN 'more than one or negative';
    END CASE;
    RETURN NULL;
  END
```
https://trino.io/docs/current/routines/case.html#examples

**Describe the solution you'd like**
```
from sqlglot import parse
parse("""FUNCTION simple_case(a bigint)
  RETURNS varchar
  BEGIN
    CASE a
      WHEN 0 THEN RETURN 'zero';
      WHEN 1 THEN RETURN 'one';
      ELSE RETURN 'more than one or negative';
    END CASE;
    RETURN NULL;
  END
""")
```
Should properly parse without returning error

FUNCTION can be [tokenized](https://sqlglot.com/sqlglot/tokens.html#TokenType.FUNCTION) already. Extend support to parse Trino Function.

**Describe alternatives you've considered**
N/A

**Additional context**
Ability to parse sql string with multiple `;` characters into separate sql statements. https://github.com/apache/superset/issues/26162

This might be complicated by the use of `;` characters within the FUNCTION declaration.

**Comment by tobymao** [comment]
we're not planning to implement it but happy to accept a pr for this. we can continue to discuss here
