### ISSUE TITLE
oracle to pyspark sql query convertion

### ISSUE THREAD

**Issue by ACHINTA-MONDAL** [tobymao/sqlglot#3362]
we are trying to convert oracle query to **pyspark** script so we are looking for something we can easily convert oracle query to **pyspark** sql.
we have tried  **sqlglot** package but not getting expected result for sub query and (+) join condition.
it will be appreciated for your helpful support.

**Comment by tobymao** [comment]
there's not enough detail here to help you out, but in general the (+) is not widely transpilable, it'll be easier if you don't use (+) which is considered deprecated.
