### ISSUE TITLE
[bug] postgres sql to doris sql fail

### ISSUE THREAD

**Issue by Toms1999** [tobymao/sqlglot#3365]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by Toms1999** [comment]
gpdb_test=# SELECT NOW() - 'yesterday';
?column?        
-----------------------
 1 day 15:40:04.502763
(1 row)

**Comment by Toms1999** [comment]
SELECT NOW() - 'yesterday';
ERROR 1105 (HY000): errCode = 2, detailMessage = string literal 'yesterday' cannot be cast to double

**Comment by Toms1999** [comment]
import sqlglot

sql = """select now() - 'yesterday' ;"""

result = sqlglot.transpile(sql, read="postgres", write="doris")


print(result)

**Comment by georgesittas** [comment]
This is out of scope for us, type inference is required to parse and transpile the postgres datetime operations.
