### ISSUE TITLE
XOR transformed into an OR depending on the alphabetical order of operands

### ISSUE THREAD

**Issue by colincointe** [tobymao/sqlglot#3372]
Hello,

I stumbled upon an apparent bug still present in the 23.12.1 release (I was using 20.9.0 when I first saw the bug). When using the `optimize` function on a MySQL constraint, result depends on the alphabetical order of the operands (with one of the results being wrong):

```python
from sqlglot import parse_one
from sqlglot.optimizer import optimize

# Returns '`bar` IS NULL XOR `foo` IS NULL'
optimize(parse_one('(bar IS NULL) XOR (foo IS NULL)', read="mysql")).sql("mysql")

# Returns '`bar` IS NULL OR `foo` IS NULL'
optimize(parse_one('(foo IS NULL) XOR (bar IS NULL)', read="mysql")).sql("mysql")
```

In the second example, the XOR is transformed into an OR which in this case does not seem to be equivalent. I would expect both results to be the same (or at least not converting the XOR into OR).

Is there something wrong in the way I used those functions or is this a bug ?

I can give more details if needed !
Thank you

**Comment by georgesittas** [comment]
This look like a bug, thanks for reporting. We'll take a look soon.
