### ISSUE TITLE
Support for generation of different SQL

### ISSUE THREAD

**Issue by Beliefuture** [tobymao/sqlglot#3378]
Thanks for your efforts on this great project!

I have two questions listed below:

1. Does this project provide the off-the-shelf function to generate different SQL by traversing the syntax AST from scratch?

2. What should be done if I want to support a new DBMS dialect (e.g., implementing a new `dialect` class)?

**Comment by georgesittas** [comment]
1. I'm not sure what this means, but the SQL generation can be specified on a per-AST-node basis and is easily overridable by subclassing the `Generator` class in a dialect.

2. Yes, look into https://sqlglot.com/sqlglot/dialects.html

**Comment by Beliefuture** [comment]
> 1. I'm not sure what you mean here, but the SQL generation happens on a per-AST-node basis and is easily overridable by subclassing the `Generator` class in a dialect.
> 2. You need to subclass `Dialect`, look into https://sqlglot.com/sqlglot/dialects.html.

Hi, For 1., what I mean is to generate SQL queries of different clauses and structures according to the grammar rules, i.e., something like sampling different paths in the superset AST.

**Comment by georgesittas** [comment]
So, produce random queries that conform to a grammar, eg. for fuzzing? If that's what you mean, it's not supported by sqlglot because it's a typical recursive-descent parser.

**Comment by Beliefuture** [comment]
> So, produce random queries that conform to a grammar, eg. for fuzzing? If that's what you mean, it's not supported by sqlglot because it's a typical recursive-descent parser.

Yes. I want to generate different syntactically correct SQL queries just like randomly walking through a superset AST (i.e., with all the clauses supported) and exclude certain clauses.
