### ISSUE TITLE
Does this support mysql query placeholders

### ISSUE THREAD

**Issue by togakangaroo** [tobymao/sqlglot#338]
In python's mysql client, parameter placeholders use `%s`

    select * from users where id = %s

trying this out doesn't seem to work in sqlglot. Using a `?` works but that's not the syntax. Is there a way to change the placeholder token?

**Comment by tobymao** [comment]
%s is not sql, it’s python format strings so it’s out scope.

? is the sql i believe which is supported

**Comment by barakalon** [comment]
`%s` placeholders aren't part of the actual MySQL dialect. I'm not sure which MySQL Python client you're using, but it likely either replaces the `%s` placeholders with their values client side or replaces them with `?` before sending over a prepared statement. Here's how the official client does it:

https://github.com/mysql/mysql-connector-python/blob/7c7b1d9f587b8d8ae570ce101aeda966ffba8326/lib/mysql/connector/cursor.py#L1239

That being said, two options:

1. Copy that regex from the client into your code and use it before sending the statement to sqlglot.

2. Implement a custom dialect:

```python
from sqlglot import Tokenizer, TokenType, parse_one
from sqlglot.dialects import MySQL

class PyMySQL(MySQL):
    class Tokenizer(Tokenizer):
        KEYWORDS = {
            **Tokenizer.KEYWORDS,
            "%S": TokenType.PLACEHOLDER
        }

parse_one("select * from users where id = %s", read="pymysql")
```

**Comment by tobymao** [comment]
@barakalon should we add it?

**Comment by barakalon** [comment]
It feels pretty niche to me. Plus, there're a [plethora of Python MySQL clients](https://stackoverflow.com/questions/43102442/whats-the-difference-between-mysqldb-mysqlclient-and-mysql-connector-python), and this dialect would really be specific to one client.

So I'd say no, we shouldn't add it, unless there's a common enough use case. @togakangaroo - what are you trying to do? do either of the proposed solutions above work for you?

**Comment by togakangaroo** [comment]
Thanks a lot for the discussion, this is so helpful and thank you for demonstraiting how to do this with a custom dialect.

To explain the use case @barakalon , I am using the [official mysql-python connector](https://dev.mysql.com/doc/connector-python/en/connector-python-example-cursor-select.html) which does - indeed - use `%s`. What I need is the ability to do some query transformation to help developers avoid footguns. For example, in mysql you cannot do an `IN` query against an empty list *even when you are passing that list as a parameter*. The resulting error is confusing, there are no good workarounds, and this is a niche enough issue that I can't really expect all developers who come along after me to know this. They are likely to be coding difficult to catch bugs.

I already have a function that is used to run sql queries that abstracts away the connection management bits so I thought if I could get a syntax tree for a query, I could try to do some query transformation to remove the clause whenever the parameter passed in is an empty list.

I'm at the early toying-around-with-the-idea stages so was trying out the various sql parsers out there but simply passing my queries (with `%s` placeholders) through sqlglot's `parse` function generates an error.

**Comment by barakalon** [comment]
Got it - thanks for the detailed explanation. IIUC, its a query validator/fixer, in lieu of proper support in the mysql-python-connector or MySQL itself.

This doesn't feel concrete enough to warrant a new SQLGlot dialect yet. Let me know if you have any issues with the solutions above (if you choose the custom dialect, based on your description, I think you'll also want to add the custom Generator to write placeholders back as %s).

_A potentially unwanted, misdirected aside:_ 
Syntactically, I think "x IN ()" should be interpreted as "false", not "true". I imagine this ambiguity is why MySQL throws an error.
In the past, I've wanted this to be interpreted as "true" when passing parameters directly from some outer API layer, which might be defaulting a missing parameter to an empty list. In this case (which might not be yours at all) I wonder if it makes sense to use an imperative query builder, as opposed to string interpolation.

**Comment by togakangaroo** [comment]
@barakalon yup, I want it to be `false` too. it's just not that - it's a syntax error. which is understandable but a total pain regardless. A query builder is definitely the right way to go with stuff like this but I'm shimming this into existing code so its not straightforward.

To continue the sidenote, you would think that subbing in something like `x IN (NULL)` would work, but it just creates a different type of footgun where `x NOT IN (NULL)` actually gives you the same answer. Since `NULL` in sql means "I don't know" the answer to both of those is `NULL` (I don't know) and both coerce to `FALSE`

**Comment by barakalon** [comment]
yowza. Well, good luck 😂 

Again, let me know if you have any more questions.
