### ISSUE TITLE
T-SQL and Text Data Types

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#3381]
```python
import sqlglot

print(sqlglot.transpile("create table tester(a string)", read="spark", write="tsql"))
# prints ['CREATE TABLE tester (a VARCHAR(MAX))'], which does not support unicode, while spark's string does
# better take nvarchar?
```

All database systems I know except MS SQL Server use some Unicode/UTF-8 Data Type to store text. MS SQL Server however distinguishes between Unicode Text (NVARCHAR) and Non-Unicode Text Varchar. I had hoped that transpilation defaults to nvarchar, since that's the type which supports unicode the same way other database systems do (like spark in the example). 

See also https://learn.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver16

**Comment by treysp** [comment]
Hello - thanks for bringing this to our attention. After some investigation, we have decided to keep the transpilation as `VARCHAR(MAX)`.

The primary issue is that `NVARCHAR` type columns [require string literals to be prefixed with `N`](https://learn.microsoft.com/en-us/sql/t-sql/data-types/constants-transact-sql?view=sql-server-ver15#unicode-strings). 
- As this requirement is specific to MSSQL, codebases in other SQL dialects will use normal string literals. Therefore, transpiling to `NVARCHAR` will break all code that contains string literals.

Starting in MSSQL-2019, [`VARCHAR` supports utf-8 encoding based on choice of collation character set](https://techcommunity.microsoft.com/t5/sql-server-blog/introducing-utf-8-support-for-sql-server/ba-p/734928). This allows unmodified `VARCHAR` transpiled code to work for utf-8 data.

**Comment by aersam** [comment]
Ok, thanks for your investigation. MSFT has really messed this up, it's a very common source of confusion with MS SQL Server.

I'm however not sure if not prefixing with N is really an issue: varchar Literals can easily be inserted into nvarchar columns. Ok, there are exceptions, eg. you cannot call certain system procs with varchar literals, but whole fail without N anyway. The issue mostly appears if you have a non-unicode character in a varchar Literal

The UTF-8 collations are a solution, but since SQL Server often gives you errors when working with different collations, most people do not use them. 

But all ok for me, I can workaround it. I also very much understand your compatibility concern
