### ISSUE TITLE
BigQuery - Changing any table name part does not work properly when the entire table name is surrounded by backticks

### ISSUE THREAD

**Issue by jvaesteves** [tobymao/sqlglot#3400]
Recently, I've been using sqlglot to enforce that all queries sent to my BigQuery project reference any tables by their fully qualified name (i.e., `<project>.<dataset>.<table>`), and always point to the same project. Here is how I do it:

```python
from sqlglot import parse_one, exp

sql = '''
    SELECT
        *
    FROM
        `wrong-catalog.census_bureau_usa.population_by_zip_2010`
    LIMIT 1000;
'''

tokenized_sql = parse_one(sql, dialect='bigquery')

for table in tokenized_sql.find_all(exp.Table):
    table.set('catalog', 'bigquery-public-data')
    # table.set('db', 'bar') - although not part of my application, the same error happens if I try changing the dataset value

rewritten_sql = tokenized_sql.sql(dialect='bigquery', pretty=True)
print(rewritten_sql)
```

However, if I try to change the `catalog` value of a table that is surrounded by backticks, whenever I parse it back to its string notation, it'll omit the catalog information from the table name (using the example above, I would get `census_bureau_usa.population_by_zip_2010` (surrounded by backticks).

Furthermore, although not important for my application, the same behaviour happens if I try to change the `db` value, resulting in `population_by_zip_2010` (surrounded by backticks).

I saw a [similar issue reported two weeks ago](https://github.com/tobymao/sqlglot/issues/3318), but this was solved for when each fragment of the table is surrounded by backticks, and not for the entire table name (which is a valid usage of the backticks).

More info about my setup:
- OS: macosx 14.4.1 (23E224)
- Python: 3.9.19
- sqlglot: 23.12.2
- sqlglotrs: 0.2.0

**Comment by georgesittas** [comment]
The issue here is that you're not modifying the AST correctly. You need to respect the structure that the `Parser` emits, ie. the catalog can't be a plain string.

```python
>>> from sqlglot import parse_one, exp
>>>
>>> sql = '''
...     SELECT
...         *
...     FROM
...         `wrong-catalog.census_bureau_usa.population_by_zip_2010`
...     LIMIT 1000;
... '''
>>>
>>> tokenized_sql = parse_one(sql, dialect='bigquery')
>>>
>>> for table in tokenized_sql.find_all(exp.Table):
...     table.set('catalog', exp.Identifier(this='bigquery-public-data', quoted=True))
...     # table.set('db', 'bar') - although not part of my application, the same error happens if I try changing the dataset value
...
>>> rewritten_sql = tokenized_sql.sql(dialect='bigquery', pretty=True)
>>> print(rewritten_sql)
SELECT
  *
FROM `bigquery-public-data.census_bureau_usa.population_by_zip_2010`
LIMIT 1000
```

Notice how I've created an `Identifier` for the catalog.

**Comment by tobymao** [comment]
easier to just do

table.args["catalog"].set("this", "...")
