### ISSUE TITLE
Flink sql support

### ISSUE THREAD

**Issue by tonyxiao** [tobymao/sqlglot#3404]
Is flink sql already supported by sqlglot? I don't see any issues / code related to it which is pretty surprising given the popularity of both projects.

**Comment by tobymao** [comment]
it is not supported since flink is not really used in the python ecosystem. feel free to make a PR if you're interested, please look over other dialects and follow conventions and refrain from copy and pasting.

join us at tobikodata.com/slack if you wanna chat about it
