### ISSUE TITLE
oracel to hive query

### ISSUE THREAD

**Issue by Maheshkumar094** [tobymao/sqlglot#3407]
**Transcript the oracle query to hive**
I have two questions listed below appreciate your support.

 
**1.oracle Sub query transcription to hive left join**

Is possible to possible to convert oracle sub query to hive left join say for example
`select id, (select name from student where class_id = id) as student_name  from class;`
expected output
`select id,student_name   from class left join student on class.id=student.class_id 
`
**2.Oracle ANSI  query to non  ANSI query**

Input
`SELECT a.name,
         a.empno,
         b.loc 
    FROM tab a,
         tab b 
   WHERE a.deptno = b.deptno(+)
     AND a.empno = 190;`

Output
`SELECT a.name,
                a.empno,
                b.loc 
           FROM tab a,
LEFT OUTER JOIN tab b 
             ON a.deptno = b.deptno
          WHERE a.empno = 190;`

**Comment by georgesittas** [comment]
These are not in scope for SQLGlot, you'll need to implement custom transformations on the AST to achieve what you're looking for. Look into `Expression.transform` and other rules in transforms.py.

**Comment by Maheshkumar094** [comment]
can you share some example for custom transformation
