### ISSUE TITLE
Optimize translates query into different dialect

### ISSUE THREAD

**Issue by raeudigerRaeffi** [tobymao/sqlglot#3409]
When I use optimize and specify the dialect it triggers a translation to a different dialect. For example different functions and datatypes are introduced. In this example, the code adds DATETIME and TIMESTAMP_TRUNC to the queries which both do not exist in postgres.
```
from sqlglot.optimizer import optimize

query1 = """SELECT DATE_TRUNC('month', order_date) AS month, SUM(sales) AS total_sales, AVG(sales) AS average_sales FROM orders GROUP BY month ORDER BY total_sales DESC LIMIT 5;"""
query2 = """SELECT EXTRACT(YEAR FROM order_date) AS year, EXTRACT(MONTH FROM order_date) AS month, SUM(sales) AS total_sales FROM orders GROUP BY year, month ORDER BY total_sales DESC LIMIT 5;"""

opt_query1 = str(optimize(query1, dialect="postgres"))
opt_query2 = str(optimize(query2, dialect="postgres"))
print("Before:", query1)
print("After:", opt_query1)
print("Before:", query2)   
print("After:", opt_query2)
```
Before: SELECT DATE_TRUNC('month', order_date) AS month, SUM(sales) AS total_sales, AVG(sales) AS average_sales FROM orders GROUP BY month ORDER BY total_sales DESC LIMIT 5;
After: SELECT TIMESTAMP_TRUNC("orders"."order_date", MONTH) AS "month", SUM("orders"."sales") AS "total_sales", AVG("orders"."sales") AS "average_sales" FROM "orders" AS "orders" GROUP BY TIMESTAMP_TRUNC("orders"."order_date", MONTH) ORDER BY "total_sales" DESC NULLS FIRST LIMIT 5

Before: SELECT EXTRACT(YEAR FROM order_date) AS year, EXTRACT(MONTH FROM order_date) AS month, SUM(sales) AS total_sales FROM orders GROUP BY year, month ORDER BY total_sales DESC LIMIT 5;
After: SELECT EXTRACT(YEAR FROM CAST("orders"."order_date" AS DATETIME)) AS "year", EXTRACT(MONTH FROM CAST("orders"."order_date" AS DATETIME)) AS "month", SUM("orders"."sales") AS "total_sales" FROM "orders" AS "orders" GROUP BY EXTRACT(YEAR FROM CAST("orders"."order_date" AS DATETIME)), EXTRACT(MONTH FROM CAST("orders"."order_date" AS DATETIME)) ORDER BY "total_sales" DESC NULLS FIRST LIMIT 5;

**Comment by georgesittas** [comment]
The `str` function basically invokes `.sql()` on the AST, i.e. it omits the output dialect silently. You need to explicitly call `.sql(dialect="<output dialect>")`.
