### ISSUE TITLE
SQL with GROUPING SETS transpiled unexpectedly from Spark to Trino

### ISSUE THREAD

**Issue by Jake-00** [tobymao/sqlglot#3410]
**Description**
This issue was renewed based on #3361 
There are 2 edge cases that sqlglot would handle unexpectedly, whose table `shipping` refers to [Trino doc](https://trino.io/docs/current/sql/select.html#grouping-sets).

*CASE 1: all dimension columns in SELECT statement show up in grouping sets, these two sqls are equivalent*
```sql
-- Hive
SELECT origin_state, origin_zip, destination_state, sum(package_weight)
FROM shipping
GROUP BY origin_state, origin_zip, destination_state
GROUPING SETS (
    (origin_state),
    (origin_state, origin_zip),
    (destination_state))
ORDER BY origin_state, origin_zip, destination_state;

-- Presto
SELECT origin_state, origin_zip, destination_state, sum(package_weight)
FROM shipping
GROUP BY GROUPING SETS (
    (origin_state),
    (origin_state, origin_zip),
    (destination_state))
ORDER BY origin_state NULLS FIRST, origin_zip NULLS FIRST, destination_state NULLS FIRST;
```
Raw Rules: then using sqlglot transpilation from hive to presto, transpiled sql should rather remove three columns (origin_state, origin_zip, destination_state) following `GROUP BY` than remaining them. As for transpilation from Presto to Hive, transpiled sql should supplement three columns (origin_state, origin_zip, destination_state) after `GROUP BY`.
```python
# Presto SQL from Hive SQL
"""
SELECT
  origin_state,
  origin_zip,
  destination_state,
  SUM(package_weight)
FROM shipping
GROUP BY
  origin_state,
  origin_zip,
  destination_state,
GROUPING SETS (
  (origin_state),
  (origin_state, origin_zip),
  (destination_state)
)
ORDER BY
  origin_state NULLS FIRST,
  origin_zip NULLS FIRST,
  destination_state NULLS FIRST
"""

# Hive SQL from Presto SQL
"""
SELECT
  origin_state,
  origin_zip,
  destination_state,
  SUM(package_weight)
FROM shipping
GROUP BY
GROUPING SETS (
  (origin_state),
  (origin_state, origin_zip),
  (destination_state)
)
ORDER BY
  origin_state NULLS FIRST,
  origin_zip NULLS FIRST,
  destination_state NULLS FIRST;
"""
```
****

*CASE 2: at least one dimension column in SELECT statement dose not show up in grouping sets, these two sqls are equivalent*
```sql
-- Hive
SELECT origin_state, origin_zip, destination_state, sum(package_weight)
FROM shipping
GROUP BY origin_state, origin_zip, destination_state
GROUPING SETS (
    (origin_state),
    (origin_state, origin_zip))
ORDER BY origin_state, origin_zip, destination_state;

-- Presto
SELECT origin_state, origin_zip, null as destination_state, sum(package_weight)
FROM shipping
GROUP BY GROUPING SETS (
    (origin_state),
    (origin_state, origin_zip))
ORDER BY origin_state NULLS FIRST, origin_zip NULLS FIRST, destination_state NULLS FIRST;
```
Raw Rules: then using sqlglot transpilation from hive to presto, transpiled sql should rather remove three columns (origin_state, origin_zip, destination_state) following `GROUP BY` than remaining them, and set default null to column which dose not show up in grouping sets statement. As for transpilation from Presto to Hive, transpiled sql should supplement three columns (origin_state, origin_zip, destination_state) after `GROUP BY`.
```python
# Presto SQL transpiled from Hive SQL
"""
SELECT
  origin_state,
  origin_zip,
  destination_state,
  SUM(package_weight)
FROM shipping
GROUP BY
  origin_state,
  origin_zip,
  destination_state,
GROUPING SETS (
  (origin_state),
  (origin_state, origin_zip)
)
ORDER BY
  origin_state NULLS FIRST,
  origin_zip NULLS FIRST,
  destination_state NULLS FIRST
"""

# Hive SQL transpiled from Presto SQL
"""
SELECT
  origin_state,
  origin_zip,
  NULL AS destination_state,
  SUM(package_weight)
FROM shipping
GROUP BY
GROUPING SETS (
  (origin_state),
  (origin_state, origin_zip)
)
ORDER BY
  origin_state,
  origin_zip,
  destination_state
"""
```

**Comment by georgesittas** [comment]
We'll take a closer look, thanks for the report.

**Comment by tobymao** [comment]
@Jake-00 i think you're missing another case which is where spark-sql has group by a, b, c, with a trailing comma, that seems to make the behavior match

**Comment by tobymao** [comment]
@Jake-00 please don't open this unless you have comprehensive proof and very clear transpilation rules, i don't think your examples are correct. i don't want to spend the time implementing a complex rule if it's bugged.

you haven't addressed the case where spark has a comma after group by...

```
group by a, b, c, grouping sets
```

this has different behavior without the trailing comma after c

additionally, your rule 2 doesn't seem correct.

this spark
```
WITH x AS (
  SELECT 0 AS a, 0 AS b, 0 AS c, 0 AS d
  UNION ALL SELECT 0 AS a, 0 AS b, 1 AS c, 1 AS d
  UNION ALL SELECT 1 AS a, 0 AS b, 1 AS c, 2 AS d
)
SELECT a, b, c, sum(d) AS d
FROM x
GROUP BY a, b, c
GROUPING SETS (
    (a),
    (a, b),
  )
ORDER BY a, b, c;
```

```
a |  b   |  c   | d
---+------+------+---
 0 | NULL | NULL | 1
 0 |    0 | NULL | 1
 1 | NULL | NULL | 2
 1 |    0 | NULL | 2
```

has different results from trino
```
WITH x AS (
  SELECT 0 AS a, 0 AS b, 0 AS c, 0 AS d
  UNION ALL SELECT 0 AS a, 0 AS b, 1 AS c, 1 AS d
  UNION ALL SELECT 1 AS a, 0 AS b, 1 AS c, 2 AS d
)
SELECT a, b, null as c, sum(d) AS d
FROM x
GROUP BY 
GROUPING SETS (
    (a),
    (a, b)
  )
ORDER BY a NULLS FIRST, b NULLS FIRST, c NULLS FIRST;
```

```
a |  b   |  c   | d
---+------+------+---
 0 | NULL | NULL | 1
 0 |    0 | NULL | 1
 1 | NULL | NULL | 2
 1 |    0 | NULL | 2
```

**Comment by Jake-00** [comment]
> @Jake-00 i think you're missing another case which is where spark-sql has group by a, b, c, with a trailing comma, that seems to make the behavior match

@tobymao 
Spark would raise ParseError
```
mismatched input 'SETS' expecting <EOF>(line 9, pos 9)

== SQL ==
WITH x AS (
  SELECT 0 AS a, 0 AS b, 0 AS c, 0 AS d
  UNION ALL SELECT 0 AS a, 0 AS b, 1 AS c, 1 AS d
  UNION ALL SELECT 1 AS a, 0 AS b, 1 AS c, 2 AS d
)
SELECT a, b, c, sum(d) AS d
FROM x
GROUP BY a, b, c,
GROUPING SETS (
---------^^^
    (a),
    (a, b)
  )
ORDER BY a, b, c
```

**Comment by Jake-00** [comment]
> @Jake-00 please don't open this unless you have comprehensive proof and very clear transpilation rules, i don't think your examples are correct. i don't want to spend the time implementing a complex rule if it's bugged.
> 
> 
> 
> you haven't addressed the case where spark has a comma after group by...
> 
> 
> 
> ```
> 
> group by a, b, c, grouping sets
> 
> ```
> 
> 
> 
> this has different behavior without the trailing comma after c
> 
> 
> 
> additionally, your rule 2 doesn't seem correct.
> 
> 
> 
> this spark
> 
> ```
> 
> WITH x AS (
> 
>   SELECT 0 AS a, 0 AS b, 0 AS c, 0 AS d
> 
>   UNION ALL SELECT 0 AS a, 0 AS b, 1 AS c, 1 AS d
> 
>   UNION ALL SELECT 1 AS a, 0 AS b, 1 AS c, 2 AS d
> 
> )
> 
> SELECT a, b, c, sum(d) AS d
> 
> FROM x
> 
> GROUP BY a, b, c
> 
> GROUPING SETS (
> 
>     (a),
> 
>     (a, b),
> 
>   )
> 
> ORDER BY a, b, c;
> 
> ```
> 
> 
> 
> ```
> 
> Row(a=None, b=None, c=0, d=0)
> 
> Row(a=None, b=None, c=1, d=3)
> 
> Row(a=0, b=None, c=0, d=0)
> 
> Row(a=0, b=None, c=1, d=1)
> 
> Row(a=0, b=0, c=None, d=1)
> 
> Row(a=1, b=None, c=1, d=2)
> 
> Row(a=1, b=0, c=None, d=2)
> 
> ```
> 
> 
> 
> has different results from trino
> 
> ```
> 
> WITH x AS (
> 
>   SELECT 0 AS a, 0 AS b, 0 AS c, 0 AS d
> 
>   UNION ALL SELECT 0 AS a, 0 AS b, 1 AS c, 1 AS d
> 
>   UNION ALL SELECT 1 AS a, 0 AS b, 1 AS c, 2 AS d
> 
> )
> 
> SELECT a, b, null as c, sum(d) AS d
> 
> FROM x
> 
> GROUP BY 
> 
> GROUPING SETS (
> 
>     (a),
> 
>     (a, b)
> 
>   )
> 
> ORDER BY a NULLS FIRST, b NULLS FIRST, c NULLS FIRST;
> 
> ```
> 
> 
> 
> ```
> 
> a |  b   |  c   | d
> 
> ---+------+------+---
> 
>  0 | NULL | NULL | 1
> 
>  0 |    0 | NULL | 1
> 
>  1 | NULL | NULL | 2
> 
>  1 |    0 | NULL | 2
> 
> ```

@tobymao It's so weird, I have test the spark sql you provided at both Spark2 env and Spark3 env, they all yield the same result as presto does.

**Comment by Jake-00** [comment]
> @Jake-00 please don't open this unless you have comprehensive proof and very clear transpilation rules, i don't think your examples are correct. i don't want to spend the time implementing a complex rule if it's bugged.
> 
> you haven't addressed the case where spark has a comma after group by...
> 
> ```
> group by a, b, c, grouping sets
> ```
> 
> this has different behavior without the trailing comma after c
> 
> additionally, your rule 2 doesn't seem correct.
> 
> this spark
> 
> ```
> WITH x AS (
>   SELECT 0 AS a, 0 AS b, 0 AS c, 0 AS d
>   UNION ALL SELECT 0 AS a, 0 AS b, 1 AS c, 1 AS d
>   UNION ALL SELECT 1 AS a, 0 AS b, 1 AS c, 2 AS d
> )
> SELECT a, b, c, sum(d) AS d
> FROM x
> GROUP BY a, b, c
> GROUPING SETS (
>     (a),
>     (a, b),
>   )
> ORDER BY a, b, c;
> ```
> 
> ```
> Row(a=None, b=None, c=0, d=0)
> Row(a=None, b=None, c=1, d=3)
> Row(a=0, b=None, c=0, d=0)
> Row(a=0, b=None, c=1, d=1)
> Row(a=0, b=0, c=None, d=1)
> Row(a=1, b=None, c=1, d=2)
> Row(a=1, b=0, c=None, d=2)
> ```
> 
> has different results from trino
> 
> ```
> WITH x AS (
>   SELECT 0 AS a, 0 AS b, 0 AS c, 0 AS d
>   UNION ALL SELECT 0 AS a, 0 AS b, 1 AS c, 1 AS d
>   UNION ALL SELECT 1 AS a, 0 AS b, 1 AS c, 2 AS d
> )
> SELECT a, b, null as c, sum(d) AS d
> FROM x
> GROUP BY 
> GROUPING SETS (
>     (a),
>     (a, b)
>   )
> ORDER BY a NULLS FIRST, b NULLS FIRST, c NULLS FIRST;
> ```
> 
> ```
> a |  b   |  c   | d
> ---+------+------+---
>  0 | NULL | NULL | 1
>  0 |    0 | NULL | 1
>  1 | NULL | NULL | 2
>  1 |    0 | NULL | 2
> ```

@tobymao  It's so weird, I have tested the spark sql you provided at both Spark2 env and Spark3 env, they all yield the same result as trino does.

**Comment by Jake-00** [comment]
And it is better to keep this issue open for a few days for comprehensive discussion, I think this rule can benefits users who deep use sql with `GROUPING SETS` for analysis.

**Comment by Jake-00** [comment]
latest version of docker image is 3.5.1
<img width="943" alt="image" src="https://github.com/tobymao/sqlglot/assets/60967034/8259a038-aaad-45c8-b4f1-dc0e599a8115">

**Comment by tobymao** [comment]
![Screenshot_2024-05-07_08 27 25](https://github.com/tobymao/sqlglot/assets/8205034/837fe4ee-f920-452b-964c-feddd3a82239)

**Comment by tobymao** [comment]
notice the trailing comma group by a,b, c,

**Comment by Jake-00** [comment]
> notice the trailing comma group by a,b, c,

Spark v3.1.1 would raise error, but the latest version 3.5.1 works well.

**Comment by tobymao** [comment]
right so this is quite complicated and it’s not clear to me the exact rules
