### ISSUE TITLE
[feature] Support for concatenation operator "||"

### ISSUE THREAD

**Issue by iNSDX** [tobymao/sqlglot#3412]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Support for the concatenation operator "||" for dialects like 'bigquery' ([concat operator](https://cloud.google.com/bigquery/docs/reference/standard-sql/operators#concatenation_operator)) or 'databricks' ([pipepipesign operator](https://docs.databricks.com/en/sql/language-manual/functions/pipepipesign.html))

**Describe alternatives you've considered**
The CONCAT function can be used instead to achieve the same functionality, but we have a code base where people tend to use the "||" operator. There are other sql parsers that support this, so it'd great if we could add it.

**Additional context**
N/A

**Comment by georgesittas** [comment]
The `||` operator is already supported:

```python
>>> import sqlglot
>>>
>>> sqlglot.parse_one("select a || b", "bigquery")
Select(
  expressions=[
    DPipe(
      this=Column(
        this=Identifier(this=a, quoted=False)),
      expression=Column(
        this=Identifier(this=b, quoted=False)),
      safe=True)])
>>>
>>> sqlglot.parse_one("select a || b", "bigquery").sql("bigquery")
'SELECT a || b'
```

**Comment by iNSDX** [comment]
Thank you @georgesittas, I had some issues with it in SLQMesh, will review it again
