### ISSUE TITLE
Preserve casing of quoted identifiers for SQL function calls [Snowflake/Postgres]

### ISSUE THREAD

**Issue by whummer** [tobymao/sqlglot#3413]
Hi folks 👋 , we've recently been facing some test errors in our pipeline, and were able to trace it down to the following test:

```
#  Currently getting an assertion error: assert 'SELECT "myfunc_lower"()' == 'SELECT """MYFUNC_LOWER"""()'
@pytest.mark.xfail
def test_parse_one_preserves_lowercase_quoted():
    query = 'SELECT "myfunc_lower"()'
    result = parse_one(query, read="snowflake").sql(dialect="postgres")
    assert query == result
```

Basically, a Snowflake query like this:
```
SELECT "myfunc_lower"()
```
... gets transformed to a Postgres query like this:
```
SELECT """MYFUNC_LOWER"""()
```

Haven't traced down the change/commit which may have introduced this change in behavior - happy to dig more into it (and potentially work towards a PR), but just wanted to confirm first if our assertion is correct here or if the behavior of `sqlglot` is expected here.. Thanks a lot! 🙌

**Comment by tobymao** [comment]
this is working as expected because we normalize functions, you can call sql(normalize_functions=False) if you don't want that
