### ISSUE TITLE
Getting an unexpected parse error: Expected AS after CAST

### ISSUE THREAD

**Issue by MatKadd** [tobymao/sqlglot#3420]
I am parsing a lot of tables and for each column I create a CAST statement that is then parsed. Everything works fine until, a column called "cross" is passed, which crashes.  
![image](https://github.com/tobymao/sqlglot/assets/82376286/25d19622-8cc1-43c6-910e-0477d0f776eb)

```py
from sqlglot import parse_one
from sqlglot.dialects import oracle, bigquery

expression = parse_one("CAST(avoid AS BIGDECIMAL(38, 0)) AS avoid")
print(expression)

expression = parse_one("CAST(cross AS BIGDECIMAL(38, 0)) AS cross")
print(expression)
```

Not sure what is causing the issue here, I am getting the same error on 2 separate machines.

**Comment by georgesittas** [comment]
Isn't `cross` a reserved keyword? What's your source dialect?

**Comment by georgesittas** [comment]
I just tried this in BigQuery and I'm getting a syntax error, as expected:

```sql
--  Syntax error: Unexpected keyword CROSS at [1:24] 
with t as (select 1 as cross) select cast(cross as bigdecimal(38, 0)) from t
```
