### ISSUE TITLE
Expanding diff to compare 2 SQL documents

### ISSUE THREAD

**Issue by ikasovitch** [tobymao/sqlglot#3438]
**Describe the solution you'd like**
At the moment the diff helper is comparing 2 Expressions. An expression is basically a single SQL statement.
What if I want to compare sql documents which have multiple Expressions in them. Is it possible to introduce 
an Expression of type SQLDocument to the model and then compare 2 Expressions of type SQLDocument?

**Describe alternatives you've considered**
The alternative is to compare pairs of Expressions from the document but that will not solve the problem since the Expressions can be ordered in various ways in the document and I would want to compare in a smarter way (like comparing Expressions that seem similar and not just 2 Expressions based on their order.

**Additional context**
My end goal is to find breaking changes in DDL documents by comparing 2 versions of the documents and checking if the diffs are breaking changes.

**Comment by georgesittas** [comment]
I believe this is already possible. You can do something like:

```python
>>> from sqlglot import exp, parse
>>> from sqlglot.diff import diff
>>>
>>> class SQLDocument(exp.Expression):
...     arg_types = {"expressions": True}
...
>>> expressions_1 = parse("select 1; select 2; select 3")
>>> expressions_2 = parse("select 1; select 3; select 2")
>>>
>>> expressions_1_ast = SQLDocument(expressions=expressions_1)
>>> expressions_2_ast = SQLDocument(expressions=expressions_2)
>>>
>>> diff(expressions_1_ast, expressions_2_ast)
```

**Comment by ikasovitch** [comment]
Interesting - I actually tried that but I had this:
```
class SQLDocument(exp.Expression):
    arg_types = {"this": True, "expressions": True}
```

and diff throwed an error for this case. Just for my understanding - what is `{"this": True}` doing?

**Comment by georgesittas** [comment]
`arg_types` defines the supported children for an AST node, so in this definition `SQLDocument` expects two _required_ (because of `True`) children nodes, named `this` and `expressions`. In the one I shared, it only expects a single expression, and I just made it be a list so the node is n-ary.

Take a look at https://github.com/tobymao/sqlglot/blob/main/posts/ast_primer.md.

**Comment by ikasovitch** [comment]
Great. Thanks @georgesittas.
