### ISSUE TITLE
Determine whether my `where` clause needs an alias?

### ISSUE THREAD

**Issue by jonathanstegall** [tobymao/sqlglot#344]
I'm parsing a SQL query from another source, and sometimes it can have aliases. Here's an example query:

```sql
SELECT r.*, c.* FROM contests AS c LEFT JOIN results AS r ON c.id = r.contest_id WHERE c.id = 'id-MN---43000-2191' ORDER BY r.percentage, r.candidate
```

I'm using sqlglot to check all of the queries and add a `where` clause, like this:

```python
from sqlglot import exp, parse_one, condition, errors

def format_sql(self, sql, election_id = None):
    try:
        expression_tree = parse_one(sql).assert_is(exp.Select).where('1=1')
    except errors.ParseError:
        return ""
    transformed_tree = expression_tree.transform(self.transform_sql, election_id=election_id)
    # make the query case insensitive
    sql = transformed_tree.sql().replace(" LIKE ", " ILIKE ")
    return sql

def transform_sql(self, node, election_id = None):
    if isinstance(node, exp.Where):
        node.args["this"] = parse_one(f"{node.this.sql()} AND election_id = '{election_id}'")
    return node
```

This works fine on queries where there isn't an alias, but on a query like my example, it results in a query like this:

```sql
SELECT r.*, c.* FROM contests AS c LEFT JOIN results AS r ON c.id = r.contest_id WHERE c.id = 'id-MN---43000-2191' AND 1 = 1 AND election_id = 'id-20211102' ORDER BY r.percentage, r.candidate
```

And this one fails because `AND election_id = 'id-20211102'` doesn't have the `c.` or `r.` alias.

Is there any way I can find out if the query already has an alias, and if there is one, just assign it to my additional `where` clause? In this case, it doesn't matter if it's `c` or `r`, but I for this project I'd prefer to assume it's the main table (`c`) rather than the join table (`r`).

Originally I thought this might work:

```python
sql = "SELECT r.*, c.* FROM contests AS c LEFT JOIN results AS r ON c.id = r.contest_id WHERE c.id = 'id-MN---43000-2191' AND 1 = 1 ORDER BY r.percentage, r.candidate"
for table in parse_one(sql).find_all(exp.Table):
     print(table.alias)
```

But this prints an empty value. Running this instead:

```python
for table in parse_one(sql).find_all(exp.Table):
     print(table.alias_or_name)
```

Results in:

```python
contests
results
```

**Comment by tobymao** [comment]
if you want to change the predicates in the where statement, you can do

parse_one(...).find(exp.Where).transform(...)

and then the transform can be like

def transform(node):
   if isinstance(node, exp.Column) and not isinstance(node, exp.Alias):
        ...

so a table itself is just a node, the alias is also a node, so you need to check a table's parent,

you can do
```
for table in parse_one(sql).find_all(exp.Table):
   if isinstance(table.parent, exp.TableAlias):
      table.parent.alias_or_name
   else:
      table.name
```
