### ISSUE TITLE
`to_date` with formatting is not supported by `spark` dialects

### ISSUE THREAD

**Issue by ovcharenko** [tobymao/sqlglot#345]
Spark supports [to_date(e: Column, fmt: String):](https://sparkbyexamples.com/spark/spark-sql-date-and-time-functions/#to_date) function, but trying to parse it produces
> sqlglot.errors.ParseError: The number of provided arguments (2) is greater than the maximum number of supported arguments (1)

Steps to reproduce:

```python
>>> import sqlglot
>>> sqlglot.transpile(sqlglot.transpile("""SELECT TO_DATE('2022-1-1', 'yyyy-dd-mm')""", read='mysql', write='spark')[0], read='spark')
```

**Comment by tobymao** [comment]
hive does not support it

https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF

looks like this is spark specific

**Comment by ovcharenko** [comment]
@tobymao Any ETA when to see this fix in release?

**Comment by tobymao** [comment]
maybe tomorrow, there are some issues that i need to fix internally before i launch this next cut

**Comment by tobymao** [comment]
v5 released
