### ISSUE TITLE
Trino/Presto dialect regression/change starting in 23.11.0? (table identifier quoted attribute ignored)

### ISSUE THREAD

**Issue by forgeljet** [tobymao/sqlglot#3455]
Hi, I was updating my SqlGlot dependency from 23.10.0 to the latest version, and I noticed a change of behavior that my unit tests picked up.

It appears like formatting an AST with the **trino dialect** now ignores the Identifier quoted attribute, whereas it was respected before. I tried a number of version to see where this behavior changed, at it was between 23.10.0 and 23.11.0. 

Here is a small unit test to show the issue:
```
from sqlglot import parse_one

def test_trino_parse_format():
    sql = "SELECT id FROM table"
    ast = parse_one(sql, dialect="trino")
    print(f"---ast: {ast!r}")
    assert ast.sql(dialect="trino") == sql
```
The printed output in 23.11.0+:
```
---ast: Select(
  expressions=[
    Column(
      this=Identifier(this=id, quoted=False))],
  from=From(
    this=Table(
      this=Identifier(this=table, quoted=False))))

tests/test_example.py:3 (test_trino_parse_format)
'SELECT id FROM "table"' != 'SELECT id FROM table'

Expected :'SELECT id FROM table'
Actual   :'SELECT id FROM "table"'
```
Note how the parsed table Identifier object has quoted=False (which is ignored), but the column Identifier quoted value is respected. 

**EDIT: I just ran this for all dialects, the following dialects failed this test:**
- **Trino**
- **Presto**
- **Redshift**
- **Prql**

I realize that these queries may be syntactically equivalent in the Trino dialect, but this change in behavior is concerning. So my questions are:
- Is this change intended or is it a bug?
- If the change was intentional, is there some way to format the query where it respects the quoted attribute?

Thanks!

**Comment by georgesittas** [comment]
This is expected, `table` is a [reserved keyword](https://trino.io/docs/current/language/reserved.html) in Trino and SQLGlot understands that and adds the quotes to facilitate the transpilation from other dialects that allow it to be used as an identifier.

```
trino> create table memory.default."table" as select 1 as c;
CREATE TABLE: 1 row

Query 20240510_181043_00007_jdq2a, FINISHED, 1 node
Splits: 35 total, 35 done (100.00%)
0.33 [0 rows, 0B] [0 rows/s, 0B/s]

trino> select * from table;
Query 20240510_181047_00008_jdq2a failed: line 1:20: mismatched input '<EOF>'. Expecting: '('
select * from table <EOF>
```

**Comment by forgeljet** [comment]
Ok, I verified it works with a table not named "table"... Just a bad unit test from my end. Thanks!
