### ISSUE TITLE
sqlglot parsing error for specific SQL query

### ISSUE THREAD

**Issue by MNIKIEMA** [tobymao/sqlglot#3461]
Hi folks,

I am using `sqlglot` to parse SQL queries and it is very impressive.

However, I recently encountered a parsing error related to a specific query. Here are the details:

Environment:
```
python 3.9.16
sqlglot===23.12.2
```

Query causing the issue:

```python
query = SELECT Country FROM AIRLINES WHERE Airline  =  \"JetBlue Airways\""
```
When I use the `parse_one` method like that:

```
import sqlglot
query = "SELECT Country FROM AIRLINES WHERE Airline  =  \"JetBlue Airways\""
sqlglot.parse_one(sql)
```

I get the following output:

```python
Select(
  expressions=[
    Column(
      this=Identifier(this=Country, quoted=False))],
  from=From(
    this=Table(
      this=Identifier(this=AIRLINES, quoted=False))),
  where=Where(
    this=EQ(
      this=Column(
        this=Identifier(this=Airline, quoted=False)),
      expression=Column(
        this=Identifier(this=JetBlue Airways, quoted=True)))))
```

However, I was expecting the following output:

```python
Select(
  expressions=[
    Column(
      this=Identifier(this=Country, quoted=False))],
  from=From(
    this=Table(
      this=Identifier(this=AIRLINES, quoted=False))),
  where=Where(
    this=EQ(
      this=Column(
        this=Identifier(this=Airline, quoted=False)),
      expression=Literal(this=JetBlue Airways, is_string=True))))
```

It seems that the issue is related to the parsing of the string literal `"JetBlue Airways"`. Instead of being parsed as a `Literal` with `is_string=True`, it is being parsed as a `Column` with `quoted=True`.

Could you please help me understand if I am doing something wrong, or if this is a bug in `sqlglot`?

Thank you for your time and help!

Best regards,
Mahamadi

**Comment by georgesittas** [comment]
Double quotes are usually used as identifier delimiters, so this is expected behavior. If your dialect is, e.g., BigQuery where they are used as string delimiters, then you need to set `read="bigquery"`.

**Comment by MNIKIEMA** [comment]
I understand. Thanks a lot for your feedback.
