### ISSUE TITLE
Parse CREATE TAG (Snowflake)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#3468]
Currently parsed as a Command:

```
CREATE TAG cost_center COMMENT = 'cost_center tag';
```

Would be great to be parsed so the identifier, and comment, can be located.

https://docs.snowflake.com/en/sql-reference/sql/create-tag

**Comment by georgesittas** [comment]
This should be easy to implement, PRs are welcome.

**Comment by georgesittas** [comment]
@tekumara are you working on this? I'm planning to look soon.
