### ISSUE TITLE
Feature Request: Support for Materialized View Rewriting in SQL Optimizer

### ISSUE THREAD

**Issue by Smallhi** [tobymao/sqlglot#3480]
**Is your feature request related to a problem? Please describe.**
Yes, the problem arises when dealing with complex SQL queries, especially those involving large datasets and complex joins. Most of the current optimizations focus on query rewriting or index usage which don't fully leverage the power of materialized views to accelerate the querying process.
**Describe the solution you'd like**
I would like the SQL optimizer to incorporate a new rule or feature - materialized view rewriting. Meaning, when the optimizer detects a query that can be more efficiently served through an existing materialized view, it should be able to rewrite the original query to query the materialized view instead. This would not only significantly reduce query times but also lower the database's load.
**Describe alternatives you've considered**
As an alternative, I've considered manually modifying queries or manually creating specific materialized views to optimize particular queries. While effective in some cases, this approach requires substantial manual intervention and deep analysis of the queries, which is impractical in a dynamic or frequently changing query environment. Automatic materialized view rewriting would offer a more efficient and dynamic solution to this.
**Additional context**
I believe the inclusion of this feature would bring significant performance improvements to users of the SQL optimizer, especially in scenarios dealing with large volumes of data and complex queries. I hope the development team will consider the implementation of this feature. Thank you!

**Comment by tobymao** [comment]
This isn't really possible. SQLGlot has no knowledge of materialized views or anything in your schema. The only thing that is passed in is a dictionary representing the table names and columns/ types. It doesn't have access to your warehouse and isn't really part of the scope.

If you're just saying rewrite a query to create temporary tables, this is easily done but out of the scope of the optimizer because it converts a query into multiple queries with ddls.

**Comment by Smallhi** [comment]
@tobymao Thank you for your quick and detailed response!
