### ISSUE TITLE
syntax error when transpile from tsql to mysql

### ISSUE THREAD

**Issue by hatzhang** [tobymao/sqlglot#3490]
Here is my code:
```
import sqlglot
TEST_SQL=r"""
CREATE TABLE #tmpVersionApplied (VersionName NVARCHAR(300) PRIMARY KEY, ApplyStatus NVARCHAR(20) )
GO
"""
print(sqlglot.transpile(TEST_SQL, read="tsql", write="mysql")[0])
```
The syntax can be parsed successfully with common c# tsql parsers, like [TSQL.Parser](https://www.nuget.org/packages/TSQL.Parser).
I am new to this, but I kind hope it will convert the test sql into one that can run against mysql.
What am i missing?

**Comment by hatzhang** [comment]
Further test shows that It will give a valid result without `GO`, but isn't this a common tsql element?

**Comment by hatzhang** [comment]
I tried a few more, like the following one also raise error:
```
IF EXISTS (SELECT 1 FROM #tmpVersionApplied WHERE ApplyStatus = 'Error') BEGIN
   PRINT 'Skipping version 20230216160930-001-6.2302.3.0000-ReleaseVersion.sql because of previous errors'
   UPDATE #tmpVersionApplied SET ApplyStatus = 'Previous Failure' WHERE VersionName = '20230216160930-001-6.2302.3.0000-ReleaseVersion.sql'
   SET NOEXEC ON
END
```
How to find out to what degree, that we are supporting TSQL, or I just miss something.

**Comment by georgesittas** [comment]
SQLGlot doesn't support multiple SQL statements that are not separated by semicolons, so this behavior is expected. It also doesn't generally support the procedural statements, like `IF`, `WHILE` etc.

```python
>>> print(TEST_SQL)                                                                                                                    
CREATE TABLE #tmpVersionApplied (VersionName NVARCHAR(300) PRIMARY KEY, ApplyStatus NVARCHAR(20) )                                     
>>> print(sqlglot.transpile(TEST_SQL, read="tsql", write="mysql")[0])
CREATE TEMPORARY TABLE tmpVersionApplied (VersionName VARCHAR(300) PRIMARY KEY, ApplyStatus VARCHAR(20))                         
```
