### ISSUE TITLE
Field name in STRUCT type cannot start with a number， error occurred

### ISSUE THREAD

**Issue by madeirak** [tobymao/sqlglot#3492]
sqlglot==23.15.8 newest

struct<11timestamp: float, x: float>

extract type str by 
` ast = parse_one(sql=sql_input, dialect="spark")`
` sqlglot col_type = str(node.find(exp.DataType))`
bug as below:

![image](https://github.com/tobymao/sqlglot/assets/23215922/744b3740-7075-4d52-a44c-b0effe5c7b57)

**Comment by georgesittas** [comment]
What's the actual issue?

**Comment by georgesittas** [comment]
I see no issue here, this is functioning as expected:

```python
>>> import sqlglot
>>> sqlglot.transpile("struct<11timestamp: float, x: float>", "spark")
['STRUCT<11timestamp: FLOAT, x: FLOAT>']
```

**Comment by madeirak** [comment]
It does have a BUG
try like this
```
from sqlglot import parse_one, exp
sql = "create table tb1 (column1 struct<1col: int, bcol: string>)"
ast = parse_one(sql=sql, dialect="spark")
a = ast.find(exp.DataType)
print(a)

```

![image](https://github.com/tobymao/sqlglot/assets/23215922/2e4eaa7d-289e-4c4a-b351-e6948087f667)
**Extra quotation marks**

**Comment by georgesittas** [comment]
It does not. Please put some effort to understand what's happening, I already replied in your other [thread](https://github.com/tobymao/sqlglot/discussions/3493) and explained why you're seeing unexpected SQL.

**Comment by madeirak** [comment]
@georgesittas 
you know it is a BUG
```
from sqlglot import parse_one, exp
sql = "create table tb1 (column1 struct<1col: int, bcol: string>)"
ast = parse_one(sql=sql, dialect="spark")
a = ast.find(exp.DataType)
print(a)
```
1col begins with number and has Extra quotation marks , while bcol doesn`t
![image](https://github.com/tobymao/sqlglot/assets/23215922/505d72e7-41ed-4391-a625-25adc39a4fb4)

**Comment by georgesittas** [comment]
```python
>>> from sqlglot import parse_one, exp
>>> sql = "create table tb1 (column1 struct<1col: int, bcol: string>)"
>>> ast = parse_one(sql=sql, dialect="spark")
>>> a = ast.find(exp.DataType)
>>> print(a.sql("spark"))
STRUCT<1col: INT, bcol: STRING>
```
