### ISSUE TITLE
Rollup is a reserved word but can be unquoted as a table name in Snowflake

### ISSUE THREAD

**Issue by dangoldin** [tobymao/sqlglot#3494]
**Fully reproducible code snippet**
This works:
```python
q = """with "rollup" as (
    select 1
)
select * from "rollup"
"""

pq = parse_one(q, read="snowflake")
```

This fails:
```python
q = """with rollup as (
    select 1
)
select * from rollup
"""

pq = parse_one(q, read="snowflake")
```

```
ERROR:
sqlglot.errors.ParseError: Expected CTE to have alias. Line 1, Col: 11.
  with rollup as (
    select 1
)
select * from rollup
```

"rollup" is a reserved word but can also be used without the double quotes in Snowflake (maybe others?). I took a stab at adding it to `ID_VAR_TOKENS` but that ended up causing a variety of failures so I stopped for a bit.

Works in Snowflake:
<img width="566" alt="image" src="https://github.com/tobymao/sqlglot/assets/1406/de67efe1-ae9a-4c15-8978-0b8566229461">

**Comment by georgesittas** [comment]
@dangoldin in general we suggest not using reserved keywords as identifiers, as it's not always simple to avoid ambiguity issues in the parser. Since `TokenType.ROLLUP`'s usage is limited to the `GROUP BY` parser, this was a low lift.
