### ISSUE TITLE
ParseError returned when a MAP() function of a unsupported dialect is used in the SQL

### ISSUE THREAD

**Issue by xidian237** [tobymao/sqlglot#3497]
Hi expert,
I got a ParseError:
```
  File "C:\Project\AIProjectLangfuse\.venv\Lib\site-packages\sqlglot\parser.py", line 1312, in raise_error
    raise error
sqlglot.errors.ParseError: The number of provided arguments (10) is greater than the maximum number of supported arguments (2). Line 2, Col: 67.
SELECT MAP(2, 0, 'Zero', 1, 'One', 2, 'Two', 3, 'Three', 'Default') "map" FROM DUMMY;
```
Here is the code:
`actual_sql = '''
SELECT MAP(2, 0, 'Zero', 1, 'One', 2, 'Two', 3, 'Three', 'Default') "map" FROM DUMMY;
'''
res = parse_one(actual_sql)`

Actually, the MAP is a function of SAP HANA, which is not a supported dialect type in sqlglot.
![image](https://github.com/tobymao/sqlglot/assets/17851643/63ed952d-2ade-429a-9bfe-989851e192b3)

So should I implement the new dialect, or is there a better way to solve this problem?

**Comment by georgesittas** [comment]
Yep, SAP HANA is not supported by SQLGlot, so you could implement a dialect in your application to do this. We already have a few dialects that support this syntax, so you could mimic them (ClickHouse, Hive, Snowflake).

**Comment by xidian237** [comment]
@georgesittas , Thank you for your reply, actually, I found this MAP syntax is similar to the DECODE in Orcale, and I have implemented a simple HANA dialect to fix this problem.
