### ISSUE TITLE
Better support for Snowflake `WAREHOUSE` clauses?

### ISSUE THREAD

**Issue by yingw787** [tobymao/sqlglot#3502]
**Is your feature request related to a problem? Please describe.**

I'm working on a Snowflake thing, and pretty extensively using `sqlglot`. I'm running into an issue where parsing out WAREHOUSE queries is always falling back into `exp.Command`, and I'd really like it to be parsed like other supported tokens, such as DATABASE or FUNCTION. For example:

```python
In [5]: parse_one("CREATE OR REPLACE DATABASE IDENTIFIER(?)", dialect="snowflake")
Out[5]: 
Create(
  this=Table(
    this=Anonymous(
      this=IDENTIFIER,
      expressions=[
        Placeholder()])),
  kind=DATABASE,
  replace=True)
```

vs.

```python
In [6]: parse_one("CREATE OR REPLACE WAREHOUSE IDENTIFIER(?)", dialect="snowflake")
'CREATE OR REPLACE WAREHOUSE IDENTIFIER(?)' contains unsupported syntax. Falling back to parsing as a 'Command'.
Out[6]: Command(this=CREATE, expression=OR REPLACE WAREHOUSE IDENTIFIER(?))
```

**Describe the solution you'd like**

For the above example, I'd really like if I could get this result:

```python
In [5]: parse_one("CREATE OR REPLACE WAREHOUSE IDENTIFIER(?)", dialect="snowflake")
Out[5]: 
Create(
  this=Table(
    this=Anonymous(
      this=IDENTIFIER,
      expressions=[
        Placeholder()])),
  kind=WAREHOUSE,
  replace=True)
```

This, but for different types of queries, such as `DESCRIBE WAREHOUSE`, `DROP WAREHOUSE`, and `SHOW WAREHOUSES`.

**Describe alternatives you've considered**

Right now I'm catching these queries in my code and then handrolling a `sqlglot.exp` given the query that I see.

**Additional context**

This is my `pip freeze`:

```bash
sqlglot==23.15.9
sqlglotrs==0.2.5
```

I am using Ubuntu 22.04 LTS, this is my `lsb_release -a`:

```bash
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

I'm happy to make an upstream contribution if this is moreso a backlog item for the `sqlglot` core team - I contributed #204 back in the day. Just let me know.

**Comment by georgesittas** [comment]
A PR would be greatly appreciated. This should be a simple one, check out the blame history of `DB_CREATABLES` to look for similar additions. Thanks!

**Comment by yingw787** [comment]
Working on PR now, should be up in a bit. FYI, some of the `pyspark` tests appear to be failing when I'm running `make check` since I don't have `$JAVA_HOME` set on my machine - do you want me to add a `.java-version` file to the PR? I'm running:

```bash
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 make check
```

And it works fine.

**Comment by tobymao** [comment]
no because it's going to be different for everyone
