### ISSUE TITLE
RETURNS NULL ON NULL INPUT for CREATE FUNCTION in Snowflake Dialect is not supported

### ISSUE THREAD

**Issue by krzysztof-kwitt** [tobymao/sqlglot#3503]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```shell
pip install 'sqlglot@git+ssh://git@github.com/tobymao/sqlglot.git'
```
```python
create_text = """
CREATE OR REPLACE FUNCTION ibis_udfs.public.object_values("obj" OBJECT)
RETURNS ARRAY
LANGUAGE JAVASCRIPT
RETURNS NULL ON NULL INPUT
AS
$$ return Object.values(obj) $$
"""
import sqlglot
sqlglot.parse(create_text, dialect='snowflake')
```

```
sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.InputModelProperty'>. Line 6, Col: 2.
```
**Official Documentation**
Please include links to official SQL documentation related to your issue.
https://docs.snowflake.com/en/sql-reference/sql/create-function#optional-parameters

**Comment by tobymao** [comment]
this isn’t high priority for us, feel free to submit a pr for this. 

we welcome well documented, tested, and conforming prs, but won’t have time to implement this one for you
