### ISSUE TITLE
Incorrect `DATE_SUB` output in BigQuery

### ISSUE THREAD

**Issue by elongl** [tobymao/sqlglot#3509]
**Fully reproducible code snippet**

```py
query = "SELECT DATE_SUB(DATE '2008-12-25', INTERVAL 5 DAY) AS five_days_ago;"
opt_query = str(sqlglot.optimizer.optimize(query, dialect="bigquery", rules=[sqlglot.optimizer.qualify.qualify_tables]))
print(str(opt_query))

SELECT DATE_SUB(CAST('2008-12-25' AS DATE), 5, DAY) AS five_days_ago
```

The output `DATE_SUB` signature is [invalid syntax in BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_sub).

**Comment by georgesittas** [comment]
You need to specify the output dialect using either transpile or the sql method. Calling str on an ast implicitly generates towards the default sqlglot dialect which does not necessarily follow bq's syntax.
