### ISSUE TITLE
Add better support for `plpython3u` user-defined functions in PostgreSQL

### ISSUE THREAD

**Issue by yingw787** [tobymao/sqlglot#3517]
**Is your feature request related to a problem? Please describe.**

I'm not sure what kind of support `sqlglot` offers in terms of PL/Python support. From `sqlglot` latest `upstream/main`, I'm running this input and getting the following result:

```python
In [4]: parse_one("""CREATE FUNCTION pymax (a integer, b integer)
   ...:   RETURNS integer
   ...: AS $$
   ...:   if a > b:
   ...:     return a
   ...:   return b
   ...: $$ LANGUAGE plpython3u;""")
'CREATE FUNCTION pymax (a integer, b integer)
  RETURNS integer
AS $$
  if a > b:
    return a
  retu' contains unsupported syntax. Falling back to parsing as a 'Command'.
Out[4]: 
Command(this=CREATE, expression= FUNCTION pymax (a integer, b integer)
      RETURNS integer
    AS $$
      if a > b:
        return a
      return b
    $$ LANGUAGE plpython3u)
```

I'm not sure if `sqlglot` plans to support something like this, because in truth the Python version you can compile PostgreSQL to have PL/Python support with can differ pretty wildly, you just need to pass in `--with-python` and `PYTHON=/path/to/python` when compiling PostgreSQL to support PL/Python. If PL/Python isn't supported because it's an untrusted extension, that still leaves open things like plv8, but for my purposes I'm using `plpython3u`.

**Describe the solution you'd like**

I think if `exp.UserDefinedFunction` captured everything within `$$` and just passed that off as the function definition to be run as part of some Python REPL later using `eval()`, that would work (the implications of `eval()` would fall on the user vs. `sqlglot`), and everything else could be tokenized and parsed?

**Describe alternatives you've considered**

This would / could be upstreaming some internal changes. CC: @whummer

**Comment by georgesittas** [comment]
This syntax is already supported in SQLGlot, e.g. for Snowflake:

```python
>>> parse_one("CREATE FUNCTION a (x DATE, y BIGINT) RETURNS ARRAY LANGUAGE JAVASCRIPT AS $$ SELECT 1 $$", "snowflake")
Create(
  this=UserDefinedFunction(
    this=Identifier(this=a, quoted=False),
    expressions=[
      ColumnDef(
        this=Identifier(this=x, quoted=False),
        kind=DataType(this=Type.DATE, nested=False)),
      ColumnDef(
        this=Identifier(this=y, quoted=False),
        kind=DataType(this=Type.BIGINT, nested=False))],
    wrapped=True),
  kind=FUNCTION,
  expression=RawString(this=SELECT 1 ),
  properties=Properties(
    expressions=[
      ReturnsProperty(
        this=DataType(this=Type.ARRAY, nested=True)),
      LanguageProperty(
        this=Var(this=JAVASCRIPT))]))
```

My guess is that Postgres is missing a minor thing that will allow it to parse this as well.

> I think if exp.UserDefinedFunction captured everything within $$ and just passed that off as the function definition to be run as part of some Python REPL later using eval(), that would work (the implications of eval() would fall on the user vs. sqlglot), and everything else could be tokenized and parsed?

The dollar-delimited text is simply a string, so we shouldn't do any crazy stuff like that, just have to parse that string :) (which we do already!)
