### ISSUE TITLE
rows alias is key , execute error 

### ISSUE THREAD

**Issue by Toms1999** [tobymao/sqlglot#3520]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="postgres")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="doris")`
- Check if the issue still exists on main:Couldn't find anything related

**Fully reproducible code snippet**
```python
import sqlglot

sql = """SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows"""

print(sqlglot.transpile(sql ,read="postgres" , write="doris")[0]);
``` 

output
```
SELECT ROW_NUMBER() OVER (ORDER BY 1 NULLS LAST) AS rows
```

Expected output
```
SELECT ROW_NUMBER() OVER (ORDER BY 1 NULLS LAST) AS 'rows'

```
or
```
SELECT ROW_NUMBER() OVER (ORDER BY 1 NULLS LAST) AS "rows"

```

or
```
SELECT ROW_NUMBER() OVER (ORDER BY 1 NULLS LAST) AS `rows`

```

**Comment by georgesittas** [comment]
Don't see an issue here:

SQLite:

```
sqlite> SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows;
1
sqlite> WITH t AS (SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows) SELECT rows FROM t;
1
```

Postgres:

```
georgesittas=# SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows;
 rows
------
    1
(1 row)
georgesittas=# WITH t AS (SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows) SELECT rows FROM t;
 rows
------
    1
(1 row)
```

**Comment by Toms1999** [comment]
> Don't see an issue here:
> 
> SQLite:
> 
> ```
> sqlite> SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows;
> 1
> sqlite> WITH t AS (SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows) SELECT rows FROM t;
> 1
> ```
> 
> Postgres:
> 
> ```
> georgesittas=# SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows;
>  rows
> ------
>     1
> (1 row)
> georgesittas=# WITH t AS (SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows) SELECT rows FROM t;
>  rows
> ------
>     1
> (1 row)
> ```

i am so sorry , it's doris , write = doris

**Comment by Toms1999** [comment]
> Don't see an issue here:
> 
> SQLite:
> 
> ```
> sqlite> SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows;
> 1
> sqlite> WITH t AS (SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows) SELECT rows FROM t;
> 1
> ```
> 
> Postgres:
> 
> ```
> georgesittas=# SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows;
>  rows
> ------
>     1
> (1 row)
> georgesittas=# WITH t AS (SELECT ROW_NUMBER() OVER (ORDER BY 1) AS rows) SELECT rows FROM t;
>  rows
> ------
>     1
> (1 row)
> ```

I hope you can handle a request like this, there are many more, but I can learn from your pr, I'm sure I should be able to handle the others, please
