### ISSUE TITLE
postgres has problems with interval dates with ago

### ISSUE THREAD

**Issue by Toms1999** [tobymao/sqlglot#3523]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="postgres")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="mysql")`
- Check if the issue still exists on main:Couldn't find anything related

**Fully reproducible code snippet**
```python
from sqlglot import transpile

sql = """select current_date - interval '1 day ago';"""

result = transpile(sql , read="postgres" , write="mysql")[0]

print(result)
``` 

output:
SELECT CURRENT_DATE - INTERVAL '1 day ago'

but , the sql is error in mysql

**Comment by Toms1999** [comment]
<img width="1188" alt="image" src="https://github.com/tobymao/sqlglot/assets/94617906/41749286-707a-4c4b-8db3-28b4f9c2b3f4">

**Comment by georgesittas** [comment]
This requires type inference to transpile correctly and is out of scope for now.
