### ISSUE TITLE
postgres STRING_TO_ARRAY function for doris is SPLIT_BY_STRING

### ISSUE THREAD

**Issue by Toms1999** [tobymao/sqlglot#3528]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="postgres")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="doris")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

**Official Documentation**
[doris's split by string](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-functions/string-functions/split-by-string?_highlight=split)
[postgres's string to array](https://postgresql-tutorial.com/postgresql-string_to_array-function/)

**Comment by georgesittas** [comment]
Fixed https://github.com/tobymao/sqlglot/commit/a2556101c8d04907ae49252def84c55d2daf78b2

**Comment by Toms1999** [comment]
@georgesittas I'm not quite clear on why test_postgres is used instead of test_doris. I've completed the pull request, but my tests were added to doris, causing consistent failures. I apologize for this. Additionally, I've just resolved the conflicts in my Git environment, and I will continue to make more corrections. Thank you.

**Comment by georgesittas** [comment]
> I'm not quite clear on why test_postgres is used instead of test_doris.

In this case either one would work. In this case I included a `read` entry in the `validate_all` to test the Doris -> Postgres direction. If you added it to test_doris.py, you'd similarly add a `read` entry that checks the Postgres -> Doris direction.

> I apologize for this. Additionally, I've just resolved the conflicts in my Git environment, and I will continue to make more corrections. Thank you.

No worries, appreciate the willingness to help. Just check out our fixes to understand how we approach these issues.
