### ISSUE TITLE
The REGEXP_SPLIT_TO_TABLE function for postgres is not present in doris, but the transfer does not seem to know this

### ISSUE THREAD

**Issue by Toms1999** [tobymao/sqlglot#3538]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="postgres")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="doirs")`

in:
```
SELECT REGEXP_SPLIT_TO_TABLE('Apple', 'Banana', 'Cherry', ',') AS fruit
```

out:
```
SELECT REGEXP_SPLIT_TO_TABLE('Apple', 'Banana', 'Cherry', ',') AS fruit

```
expect out:
```
select e1 from (select 1)t1 lateral view explode_split('Apple', 'Banana', 'Cherry', ',') tmp1 as e1;

```

**Official Documentation**
[postgres function REGEXP_SPLIT_TO_TABLE](https://www.postgresql.org/docs/current/functions-matching.html)
[doris function EXPLODE_SPLIT ](https://doris.apache.org/docs/dev/sql-manual/sql-functions/table-functions/explode-split/)

**Comment by Toms1999** [comment]
@tobymao Ok, I'd like to ask which databases are high priority, and I can also test the other databases as well, because I think a lot of the problems here are co-existing

**Comment by tobymao** [comment]
@Toms1999 if you want these issues fixed, you can submit prs thanks!

**Comment by Toms1999** [comment]
@tobymao I'm studying hard. I'll do that
