### ISSUE TITLE
Question: how to edit Contents of sqlglot.expressions.Anonymous

### ISSUE THREAD

**Issue by JDRanpariya** [tobymao/sqlglot#355]
I'm having a query `'SELECT custom(amu, curr) FROM t1;'`
and I want the following output
`'SELECT custom("new string here", amu, curr) FROM t1;'`

I tried with exp.column() but it gives string like `'SELECT "custom(new string here, amu, curr)" FROM t1;'`

**Comment by tobymao** [comment]
```python
In [6]: from sqlglot import parse_one, exp

In [7]: query = parse_one("select custom(amu, curr) from t1")

In [8]: query.find(exp.Anonymous).args["expressions"].insert(0, parse_one("new_string"))

In [9]: query.sql()
Out[9]: 'SELECT CUSTOM(new_string, amu, curr) FROM t1'
```
