### ISSUE TITLE
Redshift - add support for set operator `MINUS`

### ISSUE THREAD

**Issue by sandband** [tobymao/sqlglot#3553]
**Issue**
`MINUS` operator is currently not supported in Redshift dialect. `MINUS` in Redshift is exactly synonymous to the standard `EXCEPT` operator

**Code**:
```python
from sqlglot import parse_one

redshift_ast = parse_one("""select foo, bar from table_1 
minus 
select foo, bar from table_2""", dialect="redshift")

print(redshift_ast.sql(dialect="redshift", pretty=True))
```
*Expected*: 
```sql
SELECT
  foo,
  bar
FROM table_1
EXCEPT
SELECT
  foo,
  bar
FROM table_2
```

*Actual*: throws error
```python
ParseError: Invalid expression / Unexpected token. Line 3, Col: 6.
  select foo, bar from table_1 
minus 
select foo, bar from table_2
```
**Official documentation**
[UNION, INTERSECT, and EXCEPT](https://docs.aws.amazon.com/redshift/latest/dg/r_UNION.html#r_UNION-parameters)
>MINUS and EXCEPT are exact synonyms

**Comment by georgesittas** [comment]
Fixed by https://github.com/tobymao/sqlglot/commit/e1a9a8b6b7fbd44e62cee626540f90425d22d50c
