### ISSUE TITLE
How to get the key value after where

### ISSUE THREAD

**Issue by 191220042** [tobymao/sqlglot#3557]
Hello, I want to know, for example, SELECT DISTINCT * FROM cmdb WHERE x = 'a', how should I get x and a respectively? I thought I could distinguish them by identifier and Literal but it doesn't work  for 'x'

**Comment by VaggelisD** [comment]
Check out the [AST Primer](https://github.com/tobymao/sqlglot/blob/main/posts/ast_primer.md) for a tutorial on how to traverse the AST.
