### ISSUE TITLE
Fields with a name of some types (like number) are parsed incorrectly on Snowflake dialect

### ISSUE THREAD

**Issue by galunto** [tobymao/sqlglot#3565]
**Fully reproducible code snippet**
```
query = """
select
  id,
  int,
  number
from some.table
"""
sqlglot.parse(query, sqlglot.Dialects.SNOWFLAKE)
```

The `number` field is parsed as `DataType` instead of `Column`.
This was introduced on #3472 , as the new code replace it even if it is used as a name (and not a type)
It affects all names that match `DECIMAL` type on snowflake

**Comment by georgesittas** [comment]
Thanks for the report and apologies for the inconvenience. Taking a look.
