### ISSUE TITLE
Support for CrateDB queries

### ISSUE THREAD

**Issue by robd003** [tobymao/sqlglot#3567]
**Is your feature request related to a problem? Please describe.**
Would love support for CrateDB queries which are mostly PostgreSQL-like with a few additional functions

**Describe the solution you'd like**
CrateDB as a supported dialect

**Additional Details**
https://cratedb.com/docs/crate/reference/en/master/general/dql/index.html
https://cratedb.com/docs/crate/reference/en/master/general/builtins/index.html

**Comment by georgesittas** [comment]
Hey 👋

This is currently out of scope / low priority for us. However, if supporting CrateDB is trivial by subclassing Postgres without missing important functionality, perhaps we could accept a well-crafted, tested and sufficiently documented PR for it.
