### ISSUE TITLE
Translating Postgres into str translated NOW() into CURRENT_TIMESTAMP()

### ISSUE THREAD

**Issue by JCatrielLopez** [tobymao/sqlglot#3584]
**Issue:**
The function NOW() is translated to CURRENT_TIMESTAMP() when parsed and cast to a string. This translation is not acceptable for Postgres as it should either retain NOW() or use CURRENT_TIMESTAMP without the parentheses.

**Fully reproducible code snippet**

```
import sqlglot

# Parsing the SQL with Postgres dialect
parsed_sql = sqlglot.parse_one("NOW() >= '60 seconds'::interval", dialect=sqlglot.dialects.Postgres)

# Casting parsed SQL to string
output_sql = str(parsed_sql)

print(output_sql)
```
**Input SQL:**
`NOW() >= '60 seconds'::interval`

**Read Dialect:**
`sqlglot.dialects.Postgres`

**Expected Output:**
`NOW() >= CAST('60 seconds' AS INTERVAL)` (or CURRENT_TIMESTAMP)

**Actual Output:**
`CURRENT_TIMESTAMP() >= CAST('60 seconds' AS INTERVAL)`

**Object:**
```
sqlglot.parse_one("NOW() >= '60 seconds'::interval", dialect=sqlglot.dialects.Postgres)
(GTE this: 
  (CURRENTTIMESTAMP ), expression: 
  (CAST this: 
    (LITERAL this: 60 seconds, is_string: True), to: 
    (DATATYPE this: Type.INTERVAL)))
```

---

Is there another way to get the string representation of an object?

**Comment by tobymao** [comment]
When you create an issue, it tells you to make sure you specify the dialect when you generate SQL, did you see that?

**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`

call .sql(dialect="postgres")

**Comment by JCatrielLopez** [comment]
Hi! I don't understand the comment. I included in my issue the dialect used (Postgres). It even has a separate title..

**Comment by tobymao** [comment]
parse_one(sql, "postgres").sql(dialect="postgres")

you need to specify the output dialect as well
