### ISSUE TITLE
Presto's date_trunc function incorrectly translated to hive TIMESTAMP_TRUNC

### ISSUE THREAD

**Issue by cploonker** [tobymao/sqlglot#3596]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

Presto input:
```
SELECT date_trunc('month', cast(ds as timestamp)) as mm
FROM tbl
WHERE ds between '2023-10-01' and '2024-02-29'
```
SQLGlot's hive translation output:
```
SELECT
  TIMESTAMP_TRUNC(CAST(ds AS TIMESTAMP), month) AS mm
FROM tbl
WHERE
  ds BETWEEN '2023-10-01' AND '2024-02-29'
```
TIMESTAMP_TRUNC doesn't seem to be recognized by Hive engine, and googling it indicates it exists in BigQuery but not Hive

Correct translation
```
SELECT trunc(cast(ds as timestamp), 'MM') as mm
FROM tbl
WHERE ds between '2023-10-01' and '2024-02-29'
```
**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by georgesittas** [comment]
Fixed by #3600
