### ISSUE TITLE
[Enhancement Request] Ensure deterministic behaviour for expression parse

### ISSUE THREAD

**Issue by philipfweiss** [tobymao/sqlglot#360]
```
query = ... # generates a query AST-equivalent to expected.
```
```
expected = """
          SELECT
            FROM_UNIXTIME(UNIX_TIMESTAMP(ts), "yyyy-MM-dd'T'HH:mm:ss'Z'") AS formatted_ts,
            measures AS measures,
            a AS a,
            b AS b,
            c AS c,
            d AS d,
          (
            CASE
              WHEN COALESCE(`e`, 0) > 0
              THEN `f`
              ELSE NULL
            END
          ) AS g,
          (
            CASE
              WHEN COALESCE(`h`, 0) > 0
              THEN `i`
              ELSE NULL
            END
          ) AS j
        FROM mytable
        WHERE
          ds BETWEEN "2022-08-01" AND "2022-08-05"
        """
```

In my unit test, I have `self.assertEqual(sqlglot.parse_one(query), sqlglot.parse_one(expected))`. This will pass ~50% of the time.

That to me says that there is some non-deterministic ordering in the SQLGlot expression class. Is it possible to make sure that the parse is deterministic? I think this will be very useful for unit testing that a query has the expected AST, and I am confident other people will want to write similar tests in the future. 

I'm ammending the unit test (just checking len of expression.selects, sincedon't want non-deterministic behaviour), but this could be a nice-to-have for the future.

**Comment by tobymao** [comment]
i need query in order to replicate this

**Comment by barakalon** [comment]
Not sure what the resolution was here, but I typically try to compare string to string, not AST to AST. The output is often easier to debug.

**Comment by tobymao** [comment]
the test that @philipfweiss was writing had column order mismatches which is why the equality check failed
