### ISSUE TITLE
Parsing issue for Snowflake COPY INTO with subqueries and FILE_FORMAT

### ISSUE THREAD

**Issue by ajuszczak** [tobymao/sqlglot#3604]
Hi!

This issue sounds like an extension of previously reported: https://github.com/tobymao/sqlglot/issues/3434 where support for COPY INTO with subqueries was added.

Looks like the library is facing an issue when FILE_FORMAT is being added to the query:
```
from sqlglot import parse_one

query = "COPY INTO @my_stage/result/data FROM (SELECT * FROM orderstiny) file_format=(type='csv');"
parse_one(query, read='snowflake')
```
above is producing following error:

```
sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.CopyParameter'>. Line 1, Col: 77
```

Please let me know in case of any additional information is needed.

**Comment by VaggelisD** [comment]
Thank you for your report @ajuszczak, `COPY INTO` was added recently and it has shown to have a few edge cases, hopefully they're getting straightened out.
