### ISSUE TITLE
Easier way to define type annotations for custom functions

### ISSUE THREAD

**Issue by igorcalabria** [tobymao/sqlglot#3624]
**Is your feature request related to a problem? Please describe.**
Not sure if I've missed something, but it would be nice to have a clean way to define type annotations for custom defined functions. For example, If I define a custom function expr like this 
```python
class Contains(Func):
    arg_types = {"this": True, "expression": True}
    _sql_names = ["CONTAINS"]
```
There's no easy mechanism for stating that "contains" func always returns boolean values. I've tried setting the type field explicitly but I think this is just ignored and overridden in the TypeAnnotator Rule. My extremely hacky workaround is to modify the TypeAnnotator directly 

```python
def _set_type(e: sqlglot.Expression, type):
    e.type = type

TypeAnnotator.TYPE_TO_EXPRESSIONS[DataType.Type.BOOLEAN].add(Contains)
TypeAnnotator.ANNOTATORS[Contains] = lambda self, e: _set_type(e, DataType.Type.BOOLEAN
```

**Comment by georgesittas** [comment]
The `annotate_types` rule can receive an `annotators` arg for this exact use case.

```python
from sqlglot import exp
from sqlglot.optimizer.annotate_types import TypeAnnotator, _annotate_with_type_lambda, annotate_types, 

annotators = {
    **TypeAnnotator.ANNOTATORS,
    Contains: _annotate_with_type_lambda(exp.DataType.Type.BOOLEAN),
}

...

annotate_types(your_expression, annotators=annotators)
```
