### ISSUE TITLE
Clickhouse date_trunc makes upper arg1 (bad query)

### ISSUE THREAD

**Issue by TacoBel42** [tobymao/sqlglot#3626]
```python
from typing import Type, Dict, Optional, List

import sqlparse

from sqlglot import exp, parse_one
from sqlglot.dialects.clickhouse import ClickHouse
from sqlglot.dialects.dialect import Dialect


tree = parse_one("date_trunc('day', Date)", read=ClickHouse)
print(tree.sql(dialect=ClickHouse))
```

got
date_trunc('DAY', Date)  (error on execution in clickhouse `DAY doesn't look like datepart name in date_trunc`)
expected
date_trunc('day', Date)

**Comment by TacoBel42** [comment]
Fixed with this code

```
class FixedClickHouse(ClickHouse):
    
    class Generator(ClickHouse.Generator):
        UNIT_NAME = set(["DAY","HOUR","MINUTE", "MILLISECOND", "NANOSECOND","QUARTER","SECOND","MICROSECOND","WEEK","YEAR",])
        
        def date_trunc(self, exp):
            if exp.unit.name in self.UNIT_NAME:
                return exp.sql(dialect=ClickHouse).replace(exp.unit.name, "'"+exp.unit.name.lower()+"'")
            return exp.sql(dialect=ClickHouse)
    
        TRANSFORMS = {
            **ClickHouse.Generator.TRANSFORMS,
            exp.DateTrunc: date_trunc
        }

```

but found same issue with `date_diff`, looks like all funcs that have unit in args have this bug

**Comment by georgesittas** [comment]
Can you share exactly what you executed? I can't reproduce this in CH's playground:

```sql
select date_trunc('DAY', date '2020-01-01')
```

Results in:

```
date_trunc('DAY', toDate('2020-01-01'))
----------------------------------------
2020-01-01 00:00:00
```

**Comment by TacoBel42** [comment]
@georgesittas 
generator returns sql like this `select date_trunc('DAY', Date) from dnsstest.dn_stg_tst_canary`
Executing this in my Clickhouse ends with error `Code: 36. DB::Exception: DAY doesn't look like datepart name in date_trunc: While processing date_trunc('DAY', Date). (BAD_ARGUMENTS) (version 22.8.6.71 (official build))`
only this works `select date_trunc('day', Date) from dnsstest.dn_stg_tst_canary`

**Comment by georgesittas** [comment]
Could it a be a version mismatch issue? Like I said, what I pasted above runs correctly:

<img width="1501" alt="Screenshot 2024-06-11 at 5 10 12 PM" src="https://github.com/tobymao/sqlglot/assets/46752250/8294783c-17df-459a-b1a0-81c2cd8b7bb9">

This also works:
<img width="979" alt="Screenshot 2024-06-11 at 5 11 04 PM" src="https://github.com/tobymao/sqlglot/assets/46752250/391d49db-63f6-48d8-bdfa-a59bd3fce106">

**Comment by georgesittas** [comment]
It does look like a version issue. I can also execute these fine in the client I have in my system:

```
georges-macbook-pro.local :) select date_trunc('DAY', date '2020-01-01');

SELECT date_trunc('DAY', toDate('2020-01-01'))

┌─dateTrunc('DAY', toDate('2020-01-01'))─┐
│                    2020-01-01 00:00:00 │
└────────────────────────────────────────┘

1 row in set. Elapsed: 0.003 sec.
```

**Comment by georgesittas** [comment]
The uppercasing is not CH-specific, it happens at parse time and is a way of canonicalizing date parts. I guess we can try lowercasing them for CH? cc @VaggelisD

**Comment by VaggelisD** [comment]
@georgesittas  Will give it a shot

**Comment by VaggelisD** [comment]
Hey @TacoBel42, 

I did some digging for this and concluded that it will require a non trivial refactor to make it work. The decision to canonicalize units in upper case across dialects was recent (~6 months) and it worked fine for Clickhouse at that point too, so undoing this now will require a strong reason.

In an attempt to unblock you, I came up with a short snippet that you can build on to do the upper -> lower transformation with less hassle than the first solution:

```Python3
ast = sqlglot.parse_one(sql, dialect="clickhouse")

for expr in ast.find_all(exp.TimeUnit, exp.DateTrunc):
  unit = expr.args.get("unit")
  if isinstance(unit, (exp.Column, exp.Literal, exp.Var)):
     expr.set('unit', Literal.string(unit.name.lower()))
```

All functions that have `unit` arg inherit from `exp.TimeUnit` with the exception of `exp.DateTrunc`, so one can mutate the AST in-place to change the representation. Check out the [AST Primer](https://github.com/tobymao/sqlglot/blob/main/posts/ast_primer.md) for more on that.
