### ISSUE TITLE
Postgres to Sqlite CREATE TABLE does not translate GENERATED BY DEFAULT AS IDENTITY

### ISSUE THREAD

**Issue by lelandbatey** [tobymao/sqlglot#3632]
## Issue Description
When we take a Postgres table creation statement with `GENERATED BY DEFAULT AS IDENTITY` (which is how we create an _identity column_ in Postgres, which is what we're supposed to do for auto incrementing primary keys, [per the docs](https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-PARMS-GENERATED-IDENTITY)) and we translate that CREATE TABLE statement to SQLite using `sqlglot`, the output SQLite statement still contains the `GENERATED BY DEFAULT AS IDENTITY` text from the Postgres statement. This shouldn't happen, because this is an un-parseable expression in SQLite and always causes a failure.

## Demonstration and steps to reproduce
The following copy of commands shows a reproducible code snippet demonstrating the problem, the output of that snippet, and the exact git hash version I am using at time of writing which contains the mistake:
```bash
$ cat test_pg_to_sqlite.py
import sqlglot

start = """
CREATE TABLE IF NOT EXISTS tableone (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	contents TEXT
);
"""

pg_text = sqlglot.transpile(start, read="sqlite", write="postgres", pretty=True)
print("# After translating to postgres:\n", pg_text[0])

back_to_sqlite = sqlglot.transpile(pg_text[0], read="postgres", write="sqlite", pretty=True)
print("# After translating back to sqlite:\n", back_to_sqlite[0])

$ python3 test_pg_to_sqlite.py
# After translating to postgres:
 CREATE TABLE IF NOT EXISTS tableone (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  contents TEXT
)
# After translating back to sqlite:
 CREATE TABLE IF NOT EXISTS tableone (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  contents TEXT
)

$ git log --graph -n 1 --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
* 96efb645 - (HEAD -> main, origin/main, origin/HEAD) Fix(tokenizer): properly handle tags that need to be identifiers in heredocs (#3630) (3 hours ago) <Jo>
```

## Expected output

Ideally, the output after translating back to SQLite dialect would once again have the primary key column defined as `id INTEGER PRIMARY KEY AUTOINCREMENT`

## Documentation

- [Link to SQLite Autoincrement documentation](https://www.sqlite.org/autoinc.html)
- [Link to Postgres documentation on Identity columns using `GENERATED BY DEFAULT AS IDENTITY`](https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-PARMS-GENERATED-IDENTITY)
- [Link to previous issue which resulted in the change to sqlglot which causes Postgres code to use the `GENERATED BY DEFAULT AS IDENTITY` syntax for primary keys instead of the different `SERIAL` types](https://github.com/tobymao/sqlglot/issues/464)

**Comment by lelandbatey** [comment]
Thank you for your speedy and helpful work to fix this so quickly!

**Comment by VaggelisD** [comment]
@lelandbatey Detailed explanations like this one help speed up the process, appreciate it 👍
