### ISSUE TITLE
Evaluate jsqltranspiler test suite

### ISSUE THREAD

**Issue by kuza55** [tobymao/sqlglot#3640]
Hey folks,

I stumbled upon another transpiler called [hsqltranspiler](https://github.com/starlake-ai/jsqltranspiler).

On Reddit the author [claimed](https://www.reddit.com/r/dataengineering/comments/1ddhs0l/comment/l88ckil/) that on their BigQuery->DuckDB test suite, sqlglot only transpiles 63% of queries accurately while they get 98% right and have a [document](https://github.com/starlake-ai/benchmarks/blob/main/sql-transpiler/bigquery.md) describing some of the failure modes.

Further they have a [test suite](https://github.com/starlake-ai/jsqltranspiler/tree/main/src/test/resources/ai/starlake/transpiler) that presumably demonstrates these gaps.

It seems like a good opportunity to close some gaps by running this test suite to identify gaps in sqlglot.

**Comment by georgesittas** [comment]
Hey,

Thanks for bringing this to our attention, it looks interesting. I'm going to close this ticket, but we'll take a look and evaluate what parts of the transpiler can be improved to increase SQLGlot's coverage 👍
