### ISSUE TITLE
The library didn't use a proper function to convert time to string when using parse_one 

### ISSUE THREAD

**Issue by rekha-cyber** [tobymao/sqlglot#3643]
-  "read" dialect: `parse_one(sql, read="databricks")`, `parse_one(sql, read="mysql")`,  `parse_one(sql, read="tsql")`.
-  "write" dialect: `sql()`- default
-  Check if the issue still exists on main: No, it doesnt exist

**Fully reproducible code snippet**
import sqlglot
###Define the SQL query
sql_query = "Select DATE_FORMAT(date, 'yy-mm') from table"

###Parse and transpile for different SQL dialects
tsql_output = sqlglot.parse_one(sql_query, read="tsql").sql()
mysql_output = sqlglot.parse_one(sql_query, read="mysql").sql()
databricks_output = sqlglot.parse_one(sql_query, read="databricks").sql()

###Print the outputs
T-SQL Output:  SELECT DATE_FORMAT(date, 'yy-mm') FROM table
MySQL Output:  SELECT STRFTIME(date, 'yy-mm') FROM table
Databricks Output:  SELECT STRFTIME(CAST(date AS TIMESTAMP), '%y-%M') FROM table

**Official Documentation**
https://sqlglot.com/sqlglot.html#parse_one

**Comment by georgesittas** [comment]
You need to set the output dialect, `.sql(dialect=...)`
