### ISSUE TITLE
Suppress errors

### ISSUE THREAD

**Issue by eliaperantoni** [tobymao/sqlglot#3654]
**Is your feature request related to a problem? Please describe.**

I'd like for sqlglot to have a flag that makes it keep on parsing even when it encounters non-fatal errors. This can be useful for building diagnostic SQL tools on top of sqlglot.

For example, I'm building a tool that reports dependencies on missing columns by first building a lineage graph. But I can't do it because `qualify` fails with `OptimizeError: column could not be resolved`.

**Describe the solution you'd like**

A flag that, when enabled, makes sqlglot avoid raising non-fatal errors and keep parsing, even though the AST might be incomplete. By "non-fatal error" I mean anything that indicates syntactically bad SQL but that doesn't make it impossible to continue parsing. 

**Describe alternatives you've considered**

Very hacky solutions like `unittest.mock` or function replacing to make sqlglot not enter those `if` branches where errors are raised.

**Additional context**

An example: I'd like to use sqlglot to parse the following query and detect that the root query depends on a non-existing column, but parsing halts altogether because of that very missing column:

```python
from sqlglot import parse_one
from sqlglot.expressions import expand
from sqlglot.optimizer.qualify import qualify

e = expand(
    parse_one("SELECT a FROM source"),
    {"source": parse_one("SELECT 1 AS b")},
)
qualify(e)
```

```
Traceback (most recent call last):
  File "playground.py", line 9, in <module>
    qualify(e)
  File "site-packages/sqlglot/optimizer/qualify.py", line 90, in qualify
    validate_qualify_columns_func(expression)
  File "site-packages/sqlglot/optimizer/qualify_columns.py", line 95, in validate_qualify_columns
    raise OptimizeError(f"Column '{column}' could not be resolved{for_table}")
sqlglot.errors.OptimizeError: Column '"a"' could not be resolved
```

**Comment by georgesittas** [comment]
You can do `qualify(e, validate_qualify_columns=False)`. There's also an `error_level` setting in the parser that allows you to control whether a `ParseError` should raise an exception or not.
