### ISSUE TITLE
Transpiling `AT TIME ZONE` from redshift to bigquery

### ISSUE THREAD

**Issue by anand-wisdom** [tobymao/sqlglot#3657]
**Fully reproducible code snippet**
```
import sqlglot

print(sqlglot.__version__) 
# Prints: 25.1.1.dev7

redshift_sql = "SELECT ('created_date' AT TIME ZONE 'UTC') FROM table1"
bigquery_sql = "SELECT DATETIME(`created_date`, 'UTC') FROM table1"

redshift_tree = sqlglot.parse_one(redshift_sql, dialect="redshift")
print(redshift_tree.sql(dialect="bigquery"))
# Prints: SELECT (TIMESTAMP(DATETIME('created_date', 'UTC'))) FROM table1
# Expected: SELECT (DATETIME('created_date', 'UTC')) FROM table1
```

**Official Documentation**
Redshift docs: https://docs.aws.amazon.com/redshift/latest/dg/r_AT_TIME_ZONE.html#r_AT_TIME_ZONE-return-type. 
Bigquery docs: https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#datetime

** Issue ** 
I understand that the following types are identical: 
Redshift: TIMESTAMP == Bigquery: DATETIME
Redshift: TIMESTAMPTZ == Bigquery: TIMESTAMP 

To convert from redshift TIMESTAMPTZ to TIMESTAMP, I'm using `AT TIME ZONE`. 
However, transpiling to bigquery generates an additional cast to `TIMESTAMP()` in addition to the timezone conversion through `DATETIME()`

**Comment by georgesittas** [comment]
Hey @anand-wisdom, can you elaborate on what's the actual issue with using `TIMESTAMP(...)` here? It seems like this transpilation was motivated by https://github.com/tobymao/sqlglot/issues/1373.

**Comment by georgesittas** [comment]
Closing this until more details are provided, but I don't think we can do much here because you need type information to figure out the return type (i.e. `TIMESTAMP` vs `TIMESTAMPTZ` in Redshift) and transpile it accordingly.
