### ISSUE TITLE
Maybe Intersect and Except should not be Union Subclasses

### ISSUE THREAD

**Issue by sorgfresser** [tobymao/sqlglot#3660]
**Is your feature request related to a problem? Please describe.**
This is related to using the AST for exact set matching similar to test-suite-sql-eval for benchmarking SQL-generation models, so a pretty niche field. I started to love this library, but now I am facing some strange behavior.
I need to differentiate between Union, Intersect and Except. More precisely, I currently want to find the first Union, the first Intersect and the first Except in a query (if present).
Initially, I was doing this using the find method. Sadly, this leads to a surprising problem: `find(Union)` returns the first Intersect and Except classes. Taking a look into the source code it becomes obvious that these two subclass `Union`.

At least for me, this is very frustrating and confusing, because I have to check against `__class__` attributes which I'd like to avoid.

**Describe the solution you'd like**
Instead of subclassing from `Union`, I would like Intersect, Union and Except to subclass from the same more abstract class, something like `SetQuery`. I am sure a better name exists for this, but for me the current subclassing behavior seems to be mostly done to avoid code duplication. While this is a noble cause, by using a shared base class one could still differentiate the types.

**Describe alternatives you've considered**

As a workaround, I could use the `__class__` check together with `find_all` and iterate through the list until the first "proper" union is found. But at least for me, this seems to be somewhat hacky.

**Additional context**
To reproduce this odd behavior:
```
ast = sqlglot.parse_one("SELECT * FROM test INTERSECT SELECT * FROM test")
ast.find(sqlglot.expressions.Union)
```

**Comment by georgesittas** [comment]
@barakalon @tobymao what do you think about this? Imo this request makes sense but it's gonna be a pretty big change. Probably something worthy of a major version bump?

**Comment by tobymao** [comment]
i don’t think so, we could just extend find to take a lambda or something

**Comment by tobymao** [comment]
i guess changing the subclass could work too. i’m fine with a major or minir

**Comment by sorgfresser** [comment]
Thank you very much @georgesittas
