### ISSUE TITLE
Makes upper case last arg in Clickhouse date_sub func 

### ISSUE THREAD

**Issue by TacoBel42** [tobymao/sqlglot#3679]
```python
from sqlglot import parse_one
from sqlglot.dialects.clickhouse import ClickHouse
tree = parse_one("SELECT date_sub(second , seconds_in_status, created) FROM table ", read=ClickHouse)

print(tree.sql(dialect=ClickHouse))
```
got: > `SELECT date_sub(second, seconds_in_status, CREATED) FROM table`
want: > `SELECT date_sub(second, seconds_in_status, created) FROM table`
or want: > `SELECT date_sub(SECOND, seconds_in_status, created) FROM table`

On exec sql in our clickhouse getting unknown column error 
Clickhouse docs: https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#date_sub

**Comment by TacoBel42** [comment]
and one more question, how can I get access to the original token/expression in the node (transformer)?

**Comment by TacoBel42** [comment]
found one more: `timestamp_sub`

**Comment by VaggelisD** [comment]
Hey @TacoBel42, thanks for reporting these issues.

> how can I get access to the original token/expression in the node
Can you explain with an example what you mean here? Generally during parse time (i.e during expression / node construction) tokens are consumed & thrown away, so accessing them at an AST level is not possible.

**Comment by TacoBel42** [comment]
@VaggelisD 
okey, let me explane my use case
I have some sql with many calc column, they can be calc with other same cols, and i do some "expander". So, i use your lib for replacing cols on expanded cols. Otherwise, I want to get the same sql as I had before. 

```
DICT_WITH_COL_MAPPING = {
col_1: (hidden_col_1+ 10)::string 
col_2: hidden_col_2 + 100
}

from sqlglot import parse_one
from sqlglot.dialects.clickhouse import ClickHouse
def transformer(node):
    if isinstance(node, exp.Column) and node.name in DICT_WITH_COL_MAPPING:
        return parse_one(DICT_WITH_COL_MAPPING[node.name])
    return node

tree = parse_one("SELECT col_1, col2 FROM table", read=ClickHouse)

tree.trasform()
result = tree.sql(dialect=ClickHouse))
# result: SELECT (hidden_col_1+ 10)::string, hidden_col_2 + 100 FROM table
```
I want more control on parsing/transformation process. No any hidden processes.
Your lib works really cool parsing ast, but for me it makes many other not requested transforms, `sql != parse_one(sql).sql()`  
I tried to use Anonimus func for all funcs (using dict which always returns Anonimus.from_args) but messed up on getting same case (as was in sql) func call name (Parser.FUNCTIONS.get(upper) getting always upper func name)

**Comment by georgesittas** [comment]
Hey @TacoBel42, in your example, exactly function gets generated differently? I assume it's the `::` -> `CAST`? You can generally override stuff like that if you want to, just subclass the dialect in your project and override the relevant generators / parsers. The AST expressions don't contain info about the source tokens or their positions and it's also not something in our roadmap currently.

**Comment by TacoBel42** [comment]
@georgesittas that was example, in production sqls can be very different, and we want to escape cases like date_sub, timestamp_sub, date_trunc(CH v22). We need replace col on some our another sql stmt, without any optimizations/changes on it.
We just don't want non-explicit transformations

**Comment by georgesittas** [comment]
I hear you. SQLGlot canonicalizes some function names / other parts of queries, aiming to canonicalize them into more standard forms and make them compatible with other dialects. Also, these changes shouldn't change the semantics of the input SQL. We don't plan to change this, but if you want finer-grained control over the generation you can override / patch the relevant parts of the codebase in your application to achieve it.
