### ISSUE TITLE
[Postgres/Redshift] - Treat optimizer hints as comments in Postgres/Redshift

### ISSUE THREAD

**Issue by sandband** [tobymao/sqlglot#3692]
**Issue**:
Postgres doesn't have any support for Optimizer hints. All seemingly-optimizer-hints should be treated as comments.
Currently if a comment starts with a `+`, that is assumed as a hint placed out of position and an error is thrown.

```python
from sqlglot import parse_one
sample_pseudo_hint_sql = "/*+ some comment*/ select  b.foo, b.bar from baz b"
parse_one(sample_pseudo_hint_sql, read="postgres") #Throws error
```
Expected:
Should parse `/*+ some comment*/` as a comment on the statement.

Actual:
`sqlglot.errors.ParseError: Invalid expression / Unexpected token.`

**Official Documentation**
This is the best I could find: https://wiki.postgresql.org/wiki/OptimizerHintsDiscussion which describes postgres's stance on optimizer hints.

[Mysql](https://dev.mysql.com/doc/refman/8.4/en/optimizer-hints.html)
[Doris](https://doris.apache.org/docs/query/join-optimization/join-hint)
[StarRocks](https://docs.starrocks.io/docs/administration/Query_planning/#query-hint)
[Oracle](https://docs.oracle.com/cd/B13789_01/server.101/b10752/hintsref.htm)
[spark sql](https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-hints.html)
[databricks sql](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-hints.html)
[Tsql](https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-query?view=sql-server-ver16)

are the databases that I could identify to have support for Optimizer hints.

**Comment by sandband** [comment]
I tried making some changes based on my understanding (ref [commit](https://github.com/sandband/sqlglot/commit/cc766f5a5131e5b574b542e499137b474c82d10d)). Can work further based on some feedback.

**Comment by georgesittas** [comment]
@tobymao what do you think about this one? Restricting hints to only the supported dialects makes sense to me.

**Comment by tobymao** [comment]
sure, by sqlglot dialect should support
