### ISSUE TITLE
Snowflake Dialect - Column By Position

### ISSUE THREAD

**Issue by johnpawleylr** [tobymao/sqlglot#3694]
**Fully reproducible code snippet**
```python
        from sqlglot import parse_one
        from sqlglot import Dialects
        from sqlglot.optimizer import qualify
        from sqlglot import MappingSchema

        schema = MappingSchema(dialect=Dialects.SNOWFLAKE)
        from sqlglot.expressions import DataType
        schema.add_table(
            'TABLE',
            {
                'FIELD': DataType.Type.VARCHAR
            },
            dialect=Dialects.SNOWFLAKE,
            normalize=False
        )

        parsed_sql = parse_one('SELECT $1 FROM TABLE', dialect=Dialects.SNOWFLAKE)
        qualified_sql = qualify.qualify(parsed_sql, dialect=Dialects.SNOWFLAKE, schema=schema, identify=False)

        print(qualified_sql.expressions)
```
at the moment this outputs
```
[Alias(
  this=Parameter(
    this=Literal(this=1, is_string=False)),
  alias=Identifier(this=_col_0, quoted=True))]
```
but i would expect the column position reference `$1` to resolve to `FIELD` from the schema. 

**Official Documentation**
https://docs.snowflake.com/en/sql-reference/sql/select#selecting-a-column-by-position
though confusingly these docs:
https://docs.snowflake.com/en/sql-reference/session-variables
seem to suggest `$` is used either to reference variables or literals, which would make what's output by the parser correct. I'm not sure what distinguishes these cases

**Question**
I've looked in the docs and I can not see a reference to this SNOWFLAKE functionality being supported. Is it a known limitation of the parser? Am I configuring something wrong here? It seems a difficult thing to add to the parser given it doesn't have the schema until after qualification, by which point the `$` has already been interpreted as a literal. 

Any and all info greatly appreciated 🙏

**Comment by johnpawleylr** [comment]
oh, forgot to mention but i am using `sqlglot==25.3.0`, latest tag atm

**Comment by georgesittas** [comment]
Hey, this is not currently supported by the optimizer. You can implement a custom transformation that replaces `$` column references prior to running `qualify`.

Happy to continue discussing this if you need more help.

**Comment by johnpawleylr** [comment]
> Hey, this is not currently supported by the optimizer. You can implement a custom transformation that replaces `$` column references prior to running `qualify`.
> 
> Happy to continue discussing this if you need more help.

thank-you for the response @georgesittas . Yes, i was thinking pre-replacing columns before parsing would likely be my out if there wasn't another solution.
