### ISSUE TITLE
clickhouse: "cannot traverse scope" for queries with CTEs and placeholders

### ISSUE THREAD

**Issue by pkit** [tobymao/sqlglot#3698]
essentially a continuation of #2555 
```sql
WITH
    {data: Int64} AS data
SELECT data
```

```
Cannot traverse scope :data with type '<class 'sqlglot.expressions.Placeholder'>'
```

**Comment by tobymao** [comment]
it's just a warning, and it's correct, there's no scope to traverse

**Comment by tobymao** [comment]
closing this for now, but happy to discuss / have my mind changed

**Comment by pkit** [comment]
Yeah, but it's kinda spurious. I don't like spurious warnings. :)
Will check it out.
