### ISSUE TITLE
[Databricks] Date units in functions interpreted as columns

### ISSUE THREAD

**Issue by cheesefactory** [tobymao/sqlglot#3700]
First off, great module! 

I've started using sqlglot somewhat recently and ran into what I think may be a bug:

```
import sqlglot
from sqlglot import parse_one, exp
from sqlglot.optimizer.qualify import qualify

sql = "select date_diff(day, created_at, current_date()) from test"
schema = {"test": {"created_at": "timestamp"}}
ast = parse_one(sql, dialect="databricks")
qualify(ast, schema=schema, dialect="databricks")
```
`sqlglot.errors.OptimizeError: Column '"day"' could not be resolved`

The [examples](https://docs.gcp.databricks.com/en/sql/language-manual/functions/date_diff.html#examples) in the Databricks docs show an unquoted date unit. I assume that other Databricks date/time functions that accept units may experience the same issue.

**Comment by georgesittas** [comment]
I think `date_diff(unit, d1, d2)` is not documented in either Spark's or Databricks' docs. I did test in Spark v3 and it seems to be supported, but do you have any docs for this?

**Comment by georgesittas** [comment]
Nvm, found it: https://docs.gcp.databricks.com/en/sql/language-manual/functions/date_diff.html. Whoops.
