### ISSUE TITLE
Wrong conversion to `STRING` type with Spark dialect

### ISSUE THREAD

**Issue by ovcharenko** [tobymao/sqlglot#371]
According to https://spark.apache.org/docs/latest/sql-ref-datatypes.html it only supports `STRING` type without length parameter, but conversion creates unusable SQL syntax:

```python
>>> sql = """SELECT CAST(boo as varchar(3))"""
>>> sqlglot.parse(sql, read='mysql')[0].sql(dialect='presto')
'SELECT TRY_CAST(boo AS VARCHAR(3))'
>>> sqlglot.parse(sql, read='mysql')[0].sql(dialect='spark')
'SELECT CAST(boo AS STRING(3))'
```

This SQL code will trigger "DataType string(N) is not supported." exception on Spark server.

**Comment by tobymao** [comment]
thanks, fixed
