### ISSUE TITLE
Bigquery support for Json types

### ISSUE THREAD

**Issue by masterlittle** [tobymao/sqlglot#3743]
**Is your feature request related to a problem? Please describe.**
Support for JSON type in Bigquery dialect seems to be less well supported. 

When a string is cast to JSON type.

Also additional functions - 
Eg - https://cloud.google.com/bigquery/docs/json-data#extract_arrays_from_json

**Describe the solution you'd like**
Having first class support for json type where the expression column.key is handled as such. Currently sqlglot parses the column as a Table.

**Additional context**

Example - 
WITH
  meals AS (
    SELECT
      json '{"l": 0}' AS breakfast,
  )
SELECT
  breakfast.l AS lunch_soup
FROM meals;

Here lunch_soup table refernce comes out as breakfast where it's a column

<img width="927" alt="Screenshot 2024-07-06 at 12 53 50 AM" src="https://github.com/tobymao/sqlglot/assets/13149023/22474add-60f5-43d8-8856-c4612c360f45">

**Comment by georgesittas** [comment]
There's not much to do if we don't know the tables' schemas, so I'd suggest playing around with the optimizer's `qualify` rule instead. This is out of scope for the parser itself.
