### ISSUE TITLE
Cannot parse duckdb Parameters

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#3750]
DuckDB supports different styles of parameters, which do not seem to be supported: https://duckdb.org/docs/sql/query_syntax/prepared_statements.html#named-parameters-parameter

This throws a tokenerror:

```python
import sqlglot

print(
    sqlglot.parse_one(
        """"select test from contract_tree 
                where customer_sk=$customer_sk and contract_id=$contract_id
                """,
        dialect="duckdb",
    ).sql("duckdb")
)
```

**Comment by aersam** [comment]
I'd expect these $parameters to be able to transpile to @Parameters of T-SQL or similar things for other dialects

**Comment by aersam** [comment]
Oh no. sorry :)

**Comment by VaggelisD** [comment]
No worries! Well-written issues are always appreciated and we are here to catch the mistake if it slips through :)
