### ISSUE TITLE
Dialect: trino(presto), apply_index_offset (in the parse_one function) get wrong result

### ISSUE THREAD

**Issue by fangxingli** [tobymao/sqlglot#3760]
**Version**
sqlglot 25.4.0

**Fully reproducible code snippet**

``` Python
import sqlglot

sql = "select REPLACE(SPLIT(begin_time, ' ')[1], '-', '')"
sqlglot.parse_one(ss, dialect='trino').sql()
```

**Error message**
the result is `REPLACE(SPLIT(begin_time, ' ')[0], '-', '')`,
which is incorrect

**Comment by tobymao** [comment]
did you try specifying the output dialect sql(…)

**Comment by fangxingli** [comment]
Awesome!, my mistake, I misunderstand the function, thanks
