### ISSUE TITLE
Transpiling timestampadd from Spark to Presto returns BigQuery function

### ISSUE THREAD

**Issue by ddelzell** [tobymao/sqlglot#3762]
When transpiling a query from Spark to Presto, where the Spark query uses the `timestampadd` function, this function is transpiled to `TIMESTAMP_ADD`, which is valid for the BigQuery dialect, but not the Presto dialect.  It should, instead, use the `DATE_ADD` function.

Reproducible Example:
```
q = "select region_uuid, 
    timestampadd(minute, 30, date_trunc(‘hour’, time_org)) as time 
    from timeseries"
sqlglot.transpile(q, read='spark', write='presto')
```

**Comment by ddelzell** [comment]
@tobymao can we reopen this issue?  I don't think it's completely resolved because of a different transpilation error.  I can also create a new issue if that would be better.

I have the following line in my SELECT statement, slightly different than the one above (second argument in the `timestampadd` Spark function)...

```
q = "select region_uuid, 
    timestampadd(minute, floor(extract(minute from delivery_created_time_local)/30)*30, date_trunc(‘hour’, time_org)) as time 
    from timeseries"
sqlglot.transpile(q, read='spark', write='presto')
```
The Presto transpiled result is

```
SELECT region_uuid, 
    DATE_ADD('MINUTE', FLOOR(CAST(EXTRACT(MINUTE FROM delivery_created_time_local) AS DOUBLE) / NULLIF(30, 0)) * 30, DATE_TRUNC('‘HOUR’', time_org)) AS time 
FROM timeseries
```

However, DATE_ADD requires the second argument to be BIGINT, not DOUBLE, as it's currently being cast.

**Comment by tobymao** [comment]
@VaggelisD can take a look

**Comment by VaggelisD** [comment]
Hey @ddelzell, 

Thanks for reporting, I'll look into this with the new repro. In the meantime, it would be great if you can create a new issue so it can be tracked properly.
