### ISSUE TITLE
Transpile functions to DuckDB using "CREATE MACRO"

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#3764]
I'd like to transpile some sql udf from databricks to duckdb, which seems to be lacking support for duckdb's `create macro` statement: https://duckdb.org/docs/sql/statements/create_macro.html 

So bascially I tried this:

```python
import sqlglot as sg
sql = """create or replace function
    udf_overlapping_ranges(
        from_id1 bigint,
        to_id1 bigint,
        from_id2 bigint,
        to_id2 bigint,
        min_interval bigint default 1
    )
returns bigint
return from_id1 """
sg.transpile(sql, "databricks", "duckdb")
```

which returns: `'CREATE OR REPLACE FUNCTION udf_overlapping_ranges(from_id1, to_id1, from_id2, to_id2, min_interval) AS RETURN from_id1'`

It's correct to drop the returns, though at best it would also support transpiling Table UDF's. In [Databricks](https://www.databricks.com/blog/2021/10/20/introducing-sql-user-defined-functions.html) they are defined as something like `RETURNS TABLE(name STRING )`, in duckdb it's without schema: `CREATE MACRO dynamic_table(col1_value, col2_value) AS TABLE`

**Comment by VaggelisD** [comment]
Hey @aersam, thanks for reporting this!

So if I'm not mistaken, this is a scalar UDF returning back `from_id1`; To fix this case and to enable the transpilation of  table UDFs we'd have to:
- Remove `RETURN` from `AS RETURN from_id1`, making it simply `AS from_id1`
- If this was a table UDF i.e `RETURNS TABLE(...)` in Databricks, we should instead have `AS TABLE <return_expr>` in DuckDB
