### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [tobymao/sqlglot#377]
Hello! I have successfully put this package on to Conda Forge, and I am extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/sqlglot-feedstock

**Comment by tobymao** [comment]
sure. what’s the process for that?

**Comment by thewchan** [comment]
@tobymao I'm already a maintainer there so I can add you, there is very little work involved. The bots will generate a PR for a new version whenever one is pushed upstream to PyPI, and we can just merge it in if all test passes. Occasionally we will have to modify the yaml recipe if test fails (usually due to upstream changes in dependencies), but it is all very self-explanatory.

**Comment by tobymao** [comment]
sounds good. closing this issue for now
