### ISSUE TITLE
DuckDB base text types incorrect

### ISSUE THREAD

**Issue by PadenZach** [tobymao/sqlglot#3772]
DuckDB's base [text type](https://duckdb.org/docs/sql/data_types/text) is VARCHAR, not text. CHAR, BPCHAR, STRING, TEXT are aliases of VARCHAR. 

EG:
```python
from sqlglot import parse_one
parse_one("CREATE table dummy (a text, b varchar, c varchar(20), e string);", dialect='duckdb')
```
Yields:
```python
Create(
  this=Schema(
    this=Table(
      this=Identifier(this=dummy, quoted=False)),
    expressions=[
      ColumnDef(
        this=Identifier(this=a, quoted=False),
        kind=DataType(this=Type.TEXT, nested=False)),
      ColumnDef(
        this=Identifier(this=b, quoted=False),
        kind=DataType(this=Type.TEXT, nested=False)),
      ColumnDef(
        this=Identifier(this=c, quoted=False),
        kind=DataType(this=Type.TEXT, nested=False)),
      ColumnDef(
        this=Identifier(this=e, quoted=False),
        kind=DataType(this=Type.TEXT, nested=False))]),
  kind=TABLE)
```

However, I believe it should be listing these all as Type.VARCHAR instead.

```python
import duckdb
duckdb.sql("CREATE or replace table dummy (a text, b varchar, c varchar(20), e string);")
duckdb.sql("describe dummy")
```
Yields:
```
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ a           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ b           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ c           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ e           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

Is there some sqlglot specific reason to maintain these as `Type.TEXT` instead?

**Comment by tobymao** [comment]
Aren't they all equivalent? Text is an alias for varchar isn't it?

**Comment by VaggelisD** [comment]
They should indeed be synonyms; Besides that, this was recently changed to facilitate transpilation to other dialects, see https://github.com/tobymao/sqlglot/pull/3631

**Comment by PadenZach** [comment]
So I dont think they are synonyms from sqlglot's perspective?

`ast.find(expressions.DataType).is_type("VARCHAR")` on the ast created in parse_one above yields False. This makes actually using and converting types between types quite difficult.

For more context, I'm trying to use SQLGLOT to help us manage a migration between SqlServer to a combination of DuckDB and postgres

**Comment by tobymao** [comment]
```
VARCHAR 	CHAR, BPCHAR, STRING, TEXT 	Variable-length character string
VARCHAR(n) 	STRING(n), TEXT(n) 	Variable-length character string. The maximum length n has no effect and is only provided for compatibility.
```

duckdb's varchar is a text type because it doesn't respect max length, so it's equivalent to the generict text type, so check is_type("TEXT")

**Comment by VaggelisD** [comment]
I see what you mean @PadenZach, our type inference system is dialect-agnostic so while `VARCHAR == TEXT` in DuckDB, `is_type("VARCHAR") ≠ is_type("TEXT")` in SQLGlot types; This is because we want to accommodate multiple dialects, so without context this can't be true for all.

Maybe in the future it'll be useful to add a dialect-specific grouping/mapping e.g.  `is_type("VARCHAR", "duckdb") == is_type("TEXT", "duckdb").

**Comment by PadenZach** [comment]
Yeah makes sense, I think I may be trying to use sqlglot for a purpose it may not quite be designed for in this case. Since the DataType object doesnt have dialect information baked in is_type resolving to false makes sense.

**Comment by PadenZach** [comment]
In case anyone else comes to this issue in the future, here's a way to implement dialect aware type comparison:

```python
def equal_sql_type(a:str, b:str, dialect:str) -> bool:
    """ Return if two types are equivalent with dialect awareness.

    EG:
    >>> equal_sql_type(
    >>>    DataType(this=Type.TEXT).kind.name,
    >>>    DataType(this=Type.VARCHAR).kind.name,
    >>>    dialect='duckdb')
    True

    >>> equal_sql_type(
    >>>    DataType(this=Type.TEXT).kind.name,
    >>>    DataType(this=Type.VARCHAR).kind.name,
    >>>    dialect='postgres')
    False
    """
    dialect = Dialect.get_or_raise(Dialects(dialect))
    return dialect.Tokenizer.KEYWORDS[a] == dialect.Tokenizer.KEYWORDS[b]
```
