### ISSUE TITLE
Support ALTER VIEW in expression

### ISSUE THREAD

**Issue by xiaohui-sun** [tobymao/sqlglot#3773]
**Is your feature request related to a problem? Please describe.**
We need to update Spark views daily. Previously we used "CREATE OR REPLACE VIEW", however this will recreate the view if it already exists.
Since replacing an existing view does not preserve privileges granted on the original view. We need to use ALTER VIEW to preserve privileges.
Specifically we want to support
https://spark.apache.org/docs/3.0.0-preview2/sql-ref-syntax-ddl-alter-view.html#alter-view-as-select

**Describe the solution you'd like**
I checked we already have [AlterTable](https://github.com/tobymao/sqlglot/blob/main/sqlglot/expressions.py#L4266), can we support `AlterView` as well?

**Describe alternatives you've considered**
Not at the moment.

**Comment by tobymao** [comment]
can you show me the sql statement you want supported?

**Comment by xiaohui-sun** [comment]
ALTER VIEW <view_name> (
<view_schema>
) AS
SELECT ... FROM

**Comment by tobymao** [comment]
this is already supported as a command, additional support is not high priority for us, feel free to submit a PR for this.
