### ISSUE TITLE
Support parsing of comma separated alter table clauses (snowflake)

### ISSUE THREAD

**Issue by tekumara** [tobymao/sqlglot#3776]
eg:
```python
>>> sqlglot.parse_one("alter table table1 alter id comment $$foo$$, name comment $$bar$$", read="snowflake")
'alter table table1 alter id comment $$foo$$, name comment $$bar$$' contains unsupported syntax. Falling back to parsing as a 'Command'.
Command(this=alter, expression=table table1 alter id comment $$foo$$, name comment $$bar$$)
```
see https://docs.snowflake.com/en/sql-reference/sql/alter-table

**Comment by VaggelisD** [comment]
Hey @tekumara, thanks for reporting this. I'll go ahead close this for now, it's not high priority and it will require a refactor on how `ALTER` statements are currently parsed.

Though, it is a good QoL improvement for the near future so I'll add it to our backlog so we can revisit this.
