### ISSUE TITLE
NULLS FIRST added to ORDER BY with oracle dialect. At least it should be NULLS LAST when sort direction is not provided.

### ISSUE THREAD

**Issue by Hal-H2Apps** [tobymao/sqlglot#3779]
**Fully reproducible code snippet**
Reproducible with sqlGlot 25.6.0

``` python
sql = sqlglot.parse_one(sql='SELECT actor_id, actor_name FROM actors ORDER BY actor_id', read='oracle')
print(sql.sql('oracle'))
```
--> SELECT actor_id, actor_name FROM actors ORDER BY actor_id
```python
sql = sqlglot.parse_one(sql='SELECT actor_id, actor_name FROM actors', read='oracle')
sql = sql.order_by('actor_id')
print(sql.sql('oracle'))
```
--> SELECT actor_id, actor_name FROM actors ORDER BY actor_id NULLS FIRST

It should produce the same output but didn't. I didn't ask to add the NULLS FIRST option.
Worst it should be NULLS LAST when no direction is provided (so ASC is the default, and NULLS LAST is the default for ASC)

**Official Documentation**
https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj13658.html

> ASC
Specifies that the results should be returned in ascending order. If the order is not specified, ASC is the default.
DESC
Specifies that the results should be returned in descending order.
NULLS FIRST
Specifies that NULL values should be returned before non-NULL values.
NULLS LAST
Specifies that NULL values should be returned after non-NULL values.

> If the null ordering is not specified then the handling of the null values is:
NULLS LAST if the sort is ASC
NULLS FIRST if the sort is DESC
If neither ascending nor descending order is specified, and the null ordering is also not specified, then both defaults are used and thus the order will be ascending with NULLS LAST.

**Comment by tobymao** [comment]
try to specify the dialect in order_by to oracle
