### ISSUE TITLE
Parsing falls back to Command when using BEGIN in BigQuery multi-statement

### ISSUE THREAD

**Issue by chillswim** [tobymao/sqlglot#3780]
Parsing the valid BigQuery sql below:
```python
query = """
BEGIN
    CREATE TEMP TABLE FOO (x INTEGER);
END;
"""
out = sqlglot.parse(query, dialect="bigquery")
print(out)
```

logs the following (unsupported syntax): 
```bash
2024-07-18T17:07:07.270+0200] {parser.py:1487} WARNING - 'BEGIN
    CREATE TEMP TABLE FOO (x INTEGER)' contains unsupported syntax. Falling back to parsing as a 'Command'.
```

The returned output is ("Create" node is not present):
```python
[Command(
  this=BEGIN,
  expression=Literal(this=CREATE TEMP TABLE FOO (x INTEGER), is_string=True)), Command(this=END, expression=)]
```

I am using sqlglot==25.6.0 and sqlglotrs==0.2.8.

**Official Documentation**
More examples and documentation here: https://cloud.google.com/bigquery/docs/multi-statement-queries.

**Comment by tobymao** [comment]
not planned at the moment. closing for now as it's not super high priority for us
