### ISSUE TITLE
SAS dialect

### ISSUE THREAD

**Issue by aktungmak** [tobymao/sqlglot#3781]
**Is your feature request related to a problem? Please describe.**
I need to parse SQL defined in SAS as a PROC SQL block. However, there are some peculiar things about the SAS dialect, for instance the following:

```
CREATE TABLE table_name (DROP = unwanted_column) AS
SELECT column1, column2, unwanted_column
FROM another_table;
```
The `DROP` statement after the table name tells SAS to throw away that column from the result. It does not exist in the parse tree of any other dialect I can find.

**Describe the solution you'd like**
I would like to be able to use SAS as a source dialect. I am happy to implement it but I need some pointers on where to start. 

**Describe alternatives you've considered**
Doing the translation manually, but I would like to automate this.

**Additional context**
Nothing I can think of at the moment.

**Comment by tobymao** [comment]
not planned at the moment, we do accept well tested and crafted PRs
