### ISSUE TITLE
`CREATE INDEX CONCURRENTLY` not parsed by postgres dialect

### ISSUE THREAD

**Issue by EdgyEdgemond** [tobymao/sqlglot#3783]
These all parse
```
sqlglot.parse_one("CREATE INDEX ix_table_id ON tbl USING btree (id);", read="postgres", dialect="postgres")
sqlglot.parse_one("CREATE INDEX IF NOT EXISTS ix_table_id ON tbl USING btree (id);", read="postgres", dialect="postgres")
sqlglot.parse_one("CREATE UNIQUE INDEX ix_table_id ON tbl USING btree (id);", read="postgres", dialect="postgres")
sqlglot.parse_one("CREATE UNIQUE INDEX IF NOT EXISTS ix_table_id ON tbl USING btree (id);", read="postgres", dialect="postgres")
```

These fail to parse (correctly)
```
sqlglot.parse_one("CREATE INDEX CONCURRENTLY ix_table_id ON tbl USING btree (id);", read="postgres", dialect="postgres")
sqlglot.parse_one("CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_table_id ON tbl USING btree (id);", read="postgres", dialect="postgres")
```

`'CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_table_id ON tbl USING btree (id)' contains unsupported syntax. Falling back to parsing as a 'Command'.`

From the documentation https://www.postgresql.org/docs/current/sql-createindex.html I belive it is just the `CONCURRENTLY` keyword that is an issue.

`CREATE [ UNIQUE ] INDEX [ CONCURRENTLY ] [ [ IF NOT EXISTS ] name ] ON [ ONLY ] table_name [ USING method ]`

**Comment by planet-lv-426** [comment]
DROP INDEX CONCURRENTLY can not be parsed by postgres dialect.

**Comment by s1101010110** [comment]
DROP INDEX CONCURRENTLY can not parsed by postgres dialect.

**Comment by georgesittas** [comment]
Feel free to make a PR

**Comment by s1101010110** [comment]
> Feel free to make a PR

I don't know Python, just trying to use the library.
