### ISSUE TITLE
transpile removes some comments

### ISSUE THREAD

**Issue by patricksurry** [tobymao/sqlglot#3794]
I know the README says "best effort" to preserve comments, but we've seen some odd behavior with `sqlmesh format` silently removing comments in some cases.  Here's one example I found in `sqlglot==25.6.1` while trying to reproduce:

```
sql = """
with 
a as /* some cte */ (
  select *,
    extract(month from timestamp) as cohort,
    case category /* category */
      when "orange" -- orange
      then "banana" -- banana
      else "apple"
    end as fruit /* some fruit */
  from somewhere
)
select * from a
"""
print(sqlglot.transpile(sql, read='bigquery', pretty=True)[0])
```
drops the `/* some cte */` comment:
```
WITH a AS (
  SELECT
    *,
    EXTRACT(MONTH FROM timestamp) AS cohort,
    CASE category /* category */
      WHEN 'orange' /* orange */
      THEN 'banana' /* banana */
      ELSE 'apple'
    END AS fruit /* some fruit */
  FROM somewhere
)
SELECT
  *
FROM a
```

In my more complex example, it was removing all of the comments within a case statement (category, orange, banana here) but this seems related.  If you move the dropped comment before `as` then it is preserved in this case.  

Our live dialect is bigquery.  Here's a snippet from the more complex model where I originally noticed the problem.  `@constant` is a macro that expands to a string literal.  In this case the comments b, c, and d are removed by `sqlmesh format`.  we're using `sqlmesh==0.110.0`
```
...
 bucketed /* bucket policies by category-specific dimension */ AS (
  SELECT
    *,
    CASE product_category /* a */
      WHEN @constant(ProductCategory.A) -- b
      THEN DIV(MOD(EXTRACT(MONTH FROM expiration_time) + 2, 12), 3) -- c
      WHEN @constant(ProductCategory.B) /* d */
      THEN range_bucket(term, [3,7,14])
      ELSE range_bucket(advance, [14,42,90])
    END AS bucket /* this must match the bucketing in imputed_report */
  FROM core
), 
...
```

**Comment by tobymao** [comment]
wasn't sure about the last one, if you have an easy repro i can fix that one too
