### ISSUE TITLE
Trino/Presto parsing allowing invalid syntax

### ISSUE THREAD

**Issue by maen-allaga** [tobymao/sqlglot#3795]
**Fully reproducible code snippet**
When parsing a SQL's query using `dialect=trino`, there are two cases where the parsing should error out, but sqlglot would produces an AST.
## First Query:
```
        SELECT * FROM tpch.sf1.customer WHERE nationkey = 3 LIMIT 5
        UNION ALL
        SELECT * FROM tpch.sf1.customer WHERE nationkey = 24
        ORDER BY nationkey
        LIMIT 6; 
```
In the query above, there should be an error when we get to the `UNION`, because the `LIMIT` is expected to be the last term (here's what Trino would show for the above query: ` failed: line 2:1: mismatched input 'UNION'. Expecting: <EOF>`. Not that if there are paranthesis around the first query (i.e. `(SELECT * FROM tpch.sf1.customer WHERE nationkey = 3 LIMIT 5)`) then the query is allowed.

## Second Query:
```
SELECT name, FROM tpch.sf1.customer
```
In this query, the resulted AST would show one column, while this should be an invalid SQL.ut.

**Comment by tobymao** [comment]
sqlglot is not a sql validator so closing this as not planned
