### ISSUE TITLE
Parsing Bug ? 

### ISSUE THREAD

**Issue by rich-junwang** [tobymao/sqlglot#380]
One example is given below. 

SQL: "alter table org drop primary key"
Parsing result:

(COMMAND this: alter, expression: 
  (LITERAL this:  table org drop primary key, is_string: True))

I'd like to contribute, but need a bit of time to get familiar with the repo. :)

**Comment by tobymao** [comment]
this is not a bug, it's a fallback for the alter command. right now alter is specified as a command type which means we don't intelligently parse it. 

if you'd like to add support for alter in it's entirety, look and the parser with _parse_create etc.

happy to accept a PR for alter table and help you out if you have any questions. you can continue to ask questions or in discussions.
