### ISSUE TITLE
Error transpiling OBJECT_CONSTRUCT from Snowflake to DuckDB

### ISSUE THREAD

**Issue by buremba** [tobymao/sqlglot#3802]
Thanks for creating this amazing library! It's very useful for my use-case where I transpile Snowflake queries to DuckDB. I found this bug while migrating some scripts. Not very familiar with the codebase but I can look into it if you provide some insights.

```python
sqlglot.parse_one('select 
     OBJECT_INSERT(OBJECT_INSERT(OBJECT_INSERT(OBJECT_CONSTRUCT(), 'key1', 'value1'), 'key2', 'value2'), 'key3', 'value3')',
 dialect='snowflake').sql(dialect='duckdb')
```

Outputs:

```sql
select Object_insert(Object_insert(Object_insert({}, 'key1', 'value1'), 'key2',
                     'value2'), 'key3', 'value3')     
```

And it fails with the following error:
![CleanShot 2024-07-24 at 02 51 18@2x](https://github.com/user-attachments/assets/68f1684e-fd8a-4b65-86fe-bab0ef004e8b)

**Comment by VaggelisD** [comment]
Hey @buremba, thanks for reporting this. It would help if you also include what you believe is the proper transpilation as well as docs indicating both the Snowflake & to-be-transpiled DuckDB syntax.

**Comment by buremba** [comment]
Looks like you got it right already. Amazing speed 🚀
