### ISSUE TITLE
Unexpected result occurred when converting MySQL statement to Oracle

### ISSUE THREAD

**Issue by hxxxxh** [tobymao/sqlglot#3803]
**Before you file an issue**
- [x] Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- [x] Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- [x] Check if the issue still exists on main

**Fully reproducible code snippet**
If `GROUP BY` in a MySQL statement uses renamed fields from a `SELECT` statement, unexpected results occur when converting to Oracle

Python code for reproducing：
```python
from sqlglot import parse_one
sql = "SELECT a AS attr, SUM(b) AS sum_b FROM t1 GROUP BY attr"
sql = parse_one(sql, read="mysql")
print(sql.sql(dialect="oracle", pretty=True))
```
Output:
```sql
SELECT
  a AS attr,
  SUM(b) AS sum_b
FROM t1
GROUP BY
  1
```

Except Output:
```sql
SELECT
  a AS attr,
  SUM(b) AS sum_b
FROM t1
GROUP BY
  a
```

It seems that Oracle does not support GROUP BY 1, 2, 3; Because 1, 2, and 3 are considered constants

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by VaggelisD** [comment]
This transformation looks like it was added a long time ago and survived through many refactors; I'll trace it's origin to find the context, but in the meantime I came across this which means it's now [supported](https://docs.oracle.com/en/database/oracle/oracle-database/23/refrn/GROUP_BY_POSITION_ENABLED.html) on Oracle 23. 

What Oracle version are you on?

**Comment by georgesittas** [comment]
For context:

- https://github.com/tobymao/sqlglot/issues/304
- https://github.com/tobymao/sqlglot/pull/305

**Comment by tobymao** [comment]
given that this is supported in oracle 23, i'm going to close this for now
