### ISSUE TITLE
SqlGlot messes up DuckDb Struct_pack + Json

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#3808]
DuckDB transforms struct_pack to json to row, which is wrong:

```python
import sqlglot

print(
    sqlglot.parse_one(
        """select struct_pack(pig:='other 42')::json""",
        dialect="duckdb",
    ).sql("duckdb")
)
# prints SELECT CAST(ROW('other 42') AS JSON)
```

Which is wrong, since it drops the struct key

Interestingly, the same does not happen without ::json

**Comment by VaggelisD** [comment]
Thanks for reporting this @aersam, it's a very specific regression due to a recent BQ -> DuckDB feature.
