### ISSUE TITLE
Preserve comment position between parsing and generating a query

### ISSUE THREAD

**Issue by JCZuurmond** [tobymao/sqlglot#3810]
# Description

I would like the comment positions to be preserved when parsing and generating a query

## Expected behavior

``` python
import sqlglot
query = """
/* first comment */
WITH data AS (
  SELECT
    1
)
/* second comment */
SELECT
  * /* third comment */
FROM data
""".strip()
assert sqlglot.parse_one(query, dialect=sqlglot.dialects.Databricks).sql(pretty=True, dialect=sqlglot.dialects.Databricks)) == query
```

## Current behavior

``` python
import sqlglot
query = """
/* second comment */ /* first comment */
WITH data AS (
  SELECT
    1
)
SELECT
  * /* third comment */
FROM data
""".strip()
assert sqlglot.parse_one(query, dialect=sqlglot.dialects.Databricks).sql(pretty=True, dialect=sqlglot.dialects.Databricks) == query
```

## Note

The comment style `--` or `/* ... */` does not matter in the above examples, it is about the position only

**Comment by tobymao** [comment]
This isn't possible at the moment or planned. There isn't always an easy correlation between tokens and ast because sqlglot handles many things generically, so comments are best effort.
