### ISSUE TITLE
[databricks] Parse fails when using protected keyword `ALL`

### ISSUE THREAD

**Issue by JCZuurmond** [tobymao/sqlglot#3821]
# Description

Parsing a query fails when using a protected `all` as a CTE name.

### Current Behavior

The following fails:

``` python
import sqlglot
sqlglot.parse_one("WITH all AS (SELECT 1 as count) SELECT all.count FROM all")
```

With error: `ParseError: Invalid expression / Unexpected token. Line 1, Col: 43.`

### Expected behavior:

No `ParseError` like with:

``` python
import sqlglot
sqlglot.parse_one("WITH something_else AS (SELECT 1 as count) SELECT something_else.count FROM something_else")
```

### Linked Issues

- Similar to #3819

**Comment by tobymao** [comment]
@JCZuurmond please don't make duplicate issues

**Comment by JCZuurmond** [comment]
@tobymao: of which issue is it a duplicate? The issue I linked is about the LAG keyword
