### ISSUE TITLE
[databricks] `show tables like '*__splink__*'` triggers `contains unsupported syntax`

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3825]
**Fully reproducible code snippet**
```
def test_x():
    import sqlglot
    q = "show tables like '*__splink__*'"
    x = sqlglot.parse(q, dialect='databricks')
    assert x
```

> WARN [sqlglot] 'show tables like '*__splink__*'' contains unsupported syntax. Falling back to parsing as a 'Command'.

relevant error:

> 07:07:26  WARN [sqlglot] 'SHOW TABLES' contains unsupported syntax. Falling back to parsing as a 'Command'.

**Official Documentation**

https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-aux-show-tables.html

**Comment by tobymao** [comment]
not planned, pr's welcome
