### ISSUE TITLE
[databricks] 'SHOW CATALOGS' contains unsupported syntax

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3827]
```
def test_x():
    import sqlglot
    q = "show catalogs like 'main'"
    x = sqlglot.parse(q, dialect='databricks')
    assert x
```

> 07:07:29  WARN [sqlglot] 'SHOW CATALOGS' contains unsupported syntax. Falling back to parsing as a 'Command'.

https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-aux-show-catalogs.html

**Comment by tobymao** [comment]
not planned, pr's welcome
