### ISSUE TITLE
[databricks] `create catalog if not exists main` contains unsupported syntax

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3828]
```
def test_x():
    import sqlglot
    q = "create catalog if not exists main"
    x = sqlglot.parse(q, dialect='databricks')
    assert x
```

> 07:07:29  WARN [sqlglot] 'create catalog if not exists main' contains unsupported syntax. Falling back to parsing as a 'Command'.

https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-catalog.html

**Comment by tobymao** [comment]
not high priority, pr's welcome
