### ISSUE TITLE
[databricks] `show databases in main like ...` contains unsupported syntax

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3829]
```
def test_x():
    import sqlglot
    q = "show databases in main like 'main.pixels_solacc'"
    x = sqlglot.parse(q, dialect='databricks')
    assert x
```

> 07:07:29  WARN [sqlglot] 'show databases in main like 'main.pixels_solacc'' contains unsupported syntax. Falling back to parsing as a 'Command'.

https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-aux-show-databases.html

**Comment by tobymao** [comment]
not planned, pr's welcome
