### ISSUE TITLE
[databricks] `show volumes in ... like ...` contains unsupported syntax

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3830]
```
def test_x():
    import sqlglot
    q = "show volumes in main.pixels_solacc like 'main.pixels_solacc.pixels_volume'"
    x = sqlglot.parse(q, dialect='databricks')
    assert x
```

> 07:07:29  WARN [sqlglot] 'show volumes in main.pixels_solacc like 'main.pixels_solacc.pixels_volume'' contains unsupported syntax. Falling back to parsing as a 'Command'.

https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-aux-show-volumes.html

**Comment by tobymao** [comment]
not planned, pr's welcome
