### ISSUE TITLE
[databricks] `create volume if not exists ...` contains unsupported syntax

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3831]
```
def test_x():
    import sqlglot
    q = "create volume if not exists main.pixels_solacc.pixels_volume"
    x = sqlglot.parse(q, dialect='databricks')
    assert x
```

> 07:07:29  WARN [sqlglot] 'create volume if not exists main.pixels_solacc.pixels_volume' contains unsupported syntax. Falling back to parsing as a 'Command'.

https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-volume.html

**Comment by tobymao** [comment]
not high priority, pr's welcome
