### ISSUE TITLE
[databricks] `show partitions ...` contains unsupported syntax

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3833]
```
def test_x():
    import sqlglot
    q = "show partitions hive_metastore.default.ndlda_trades_prod"
    x = sqlglot.parse(q, dialect='databricks')
    assert x
```

> 07:12:38  WARN [sqlglot] 'show partitions hive_metastore.default.ndlda_trades_prod' contains unsupported syntax. Falling back to parsing as a 'Command'.

https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-aux-show-partitions.html

**Comment by tobymao** [comment]
not planned, pr's welcome
