### ISSUE TITLE
[databricks] `drop volume if exists` contains unsupported syntax

### ISSUE THREAD

**Issue by nfx** [tobymao/sqlglot#3834]
```
def test_x():
    import sqlglot
    q = """drop volume if exists"""
    x = sqlglot.parse(q, dialect='databricks')
    assert x
```

> WARN [sqlglot] 'drop volume if exists' contains unsupported syntax. Falling back to parsing as a 'Command'.

https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-drop-volume.html

**Comment by tobymao** [comment]
not high priority, pr's welcome
