### ISSUE TITLE
Converting TO_DATE() from postgres to clickhouse  cannot be converted to toDate()

### ISSUE THREAD

**Issue by ace-xc** [tobymao/sqlglot#3837]
Hello, 
When converting TO_DATE() from postgres to clickhouse  cannot be converted to toDate(), it  doesn't look like he can make the switch.
Fully reproducible code snippet
with sqlglot 25.7.1 or 25.3.1
`sqlglot.transpile("SELECT TO_DATE(date) AS date", read="postgres", write="clickhouse")`
output:
`['SELECT TO_DATE(date) AS date']`

**Comment by georgesittas** [comment]
I can't reproduce what you're seeing. On latest sqlglot:

```python
>>> import sqlglot
>>> sqlglot.transpile("select to_date('05 12 2000', 'DD MM YYYY')", read="postgres", write="clickhouse")
["SELECT STR_TO_DATE('05 12 2000', '%d %m %Y')"]
```

The resulting SQL works fine in Clickhouse, albeit returning a datetime instead of a date (postgres). I'll address this type mismatch in a PR soon.

**Comment by georgesittas** [comment]
Your input query is not valid postgres, you need to quote the date string otherwise it's an integer subtraction.

```
georgesittas=# SELECT TO_DATE(2024-7-26) AS date;
ERROR:  function to_date(integer) does not exist
LINE 1: SELECT TO_DATE(2024-7-26) AS date;
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

`STR_TO_DATE` exists is supported in clickhouse, see https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions#parsedatetimeornull.
