### ISSUE TITLE
MySQL: support for `convert … using`

### ISSUE THREAD

**Issue by rolandwalker** [tobymao/sqlglot#384]
Hello new friends.  My report for the day is that

```
python -c 'import sqlglot; print(sqlglot.parse_one("""select convert(column using latin1) from table where id = 1""", read="mysql").sql(dialect="mysql"))'
```

raises a `ParseError`
```
Invalid expression / Unexpected token. Line 1, Col: 23.
  select convert(column using latin1) from table where id = 1
```
with the word "using" underlined.

Maybe I can learn more about how `sqlglot/dialects/mysql.py` works.

We released the prettifier in https://github.com/dbcli/mycli and it's glorious.

**Comment by tobymao** [comment]
looking

**Comment by tobymao** [comment]
this is pretty strange stuff, but i'm thinking about converting CONVERT(x using latin1) to be CAST(x AS CHAR CHARACTER SET latin1)

**Comment by tobymao** [comment]
v5.3.0
