### ISSUE TITLE
PARTITION BY keyword not recognized in SESSION function

### ISSUE THREAD

**Issue by faisal-ksolves** [tobymao/sqlglot#3845]
I'm experiencing an issue with the sqlglot library where the PARTITION BY keyword is not being recognized in the SESSION function. Specifically, when I try to parse a SQL query that includes a SESSION function with a PARTITION BY clause, the parser raises a ParseError exception.

**Reproduction steps:**

- Create a FlinkDialect instance
- Define a SQL query that includes a SESSION function with a PARTITION BY clause, e.g. SELECT * FROM SESSION(my_table PARTITION BY my_column, my_time_column, 10)
- Call parse_one with the SQL query and the FlinkDialect instance
- Observe the ParseError exception being raised

**Expected behavior:**

The parser should recognize the PARTITION BY keyword and parse the SESSION function correctly.

**Actual behavior:**

The parser raises a ParseError exception with the message "Expecting )".

**Comment by tobymao** [comment]
flink isn't supported by sqlglot at the moment so i'm not really sure i understand this issue

**Comment by faisal-ksolves** [comment]
Actually i have created the a custom dialect for apache Flink i have used Hive dialect to inherit. 
For example :- 
`from sqlglot import exp
from sqlglot.dialects.hive import Hive
from sqlglot.generator import Generator
from sqlglot.tokens import Tokenizer, TokenType
from sqlglot.parser import Parser
from utility.custom import Tumble, Hop, Cumulate
from sqlglot import exp, generator, parser, tokens, transforms
class Flink(Hive):
    class Tokenizer(Tokenizer):
        # Inherit Hive's tokenizer and add TUMBLE and HOP as a keyword
        KEYWORDS = {
            **Hive.Tokenizer.KEYWORDS,
            "TUMBLE": TokenType.FUNCTION,
            "HOP": TokenType.FUNCTION,
            "CUMULATE": TokenType.FUNCTION,
            "REMOVE JAR" : TokenType.COMMAND, # custom added keyword
            "RESET" : TokenType.COMMAND,    # custom added keyword
            "DESCRIBE CATALOG" : TokenType.COMMAND, #custom added keyword
            "DESC CATALOG" : TokenType.COMMAND, #custom added keyword
            "GROUPING SET" : TokenType.GROUPING_SETS, #custom added keyword
            "UNLOAD MODULE" : TokenType.COMMAND, #custom added keyword
            "STOP JOB" : TokenType.COMMAND, # custom added keyword
            "USE MODULES": TokenType.COMMAND, #custom added keyword
            "ROW": TokenType.STRUCT, #custom added keyword
            "FOR SYSTEM_TIME" : TokenType.TIMESTAMP_SNAPSHOT, #custom added keyword
            "MATCH_RECOGNIZE": TokenType.MATCH_RECOGNIZE, #custom added keyword
            "RETURNING": TokenType.RETURNING, #custom added keyword
            "OVERWRITE" : TokenType.OVERWRITE, #custom added keyword
            "REPLACE" : TokenType.COMMAND, #custom added keyword

          
        }

    class Generator(Generator):
        # Inherit Hive's generator and add special handling for TUMBLE function
        TYPE_MAPPING = {
              **generator.Generator.TYPE_MAPPING,
        }
        TRANSFORMS = {
            **Hive.Generator.TRANSFORMS,
            Tumble: lambda self, e: self.tumble(e),
            Hop: lambda self, e: self.hop(e),
            Cumulate: lambda self, e: self.cumulate(e),
            exp.AlterTable: lambda self, e: self.alter_table(e),
        }
        def alter_table(self, e):
            return f"ALTER TABLE {self.sql(e.this)} ADD COLUMNS ({', '.join(self.sql(c) for c in e.expressions)}) {e.args.get('cascade', '')}"

        def tumble(self, e: Tumble) -> str:
            args = [self.sql(e.this), self.sql(e.timecol), self.sql(e.size)]
            if e.offset:
                args.append(self.sql(e.offset))
            return f"TUMBLE({', '.join(args)})"
        

        def hop(self, e: Hop) -> str:
            args = [self.sql(e.this), self.sql(e.timecol), self.sql(e.slide), self.sql(e.size)]
            if e.offset:
                args.append(self.sql(e.offset))
            return f"HOP({', '.join(args)})"
        

        def cumulate(self, e: Cumulate) -> str:
            args = [self.sql(e.this), self.sql(e.timecol), self.sql(e.step), self.sql(e.size)]
            if e.offset:
                args.append(self.sql(e.offset))
            return f"CUMULATE({', '.join(args)})"

        # Add support for TUMBLE and HOP function in the SQL generator
        def sql(self, e: exp.Expression) -> str:
            if isinstance(e, Tumble):
                return self.tumble(e)
            elif isinstance(e, Hop):
                return self.hop(e)
            elif isinstance(e, Cumulate):
                return self.cumulate(e)
            return super().sql(e)

    class Parser(Parser):
        # Inherit Hive's parser and add special handling for TUMBLE function
        FUNCTIONS = {
            **Hive.Parser.FUNCTIONS,
            "TUMBLE": Tumble,
            "HOP": Hop,
            "CUMULATE": Cumulate,
        }

        def _parse_function(self, optional_parens=False, anonymous=False, any_token=False):
            if self._match(TokenType.FUNCTION, "TUMBLE"):
                self._match(TokenType.L_PAREN)
                this = self._parse_table()
                self._match(TokenType.COMMA)
                timecol = self._parse_column()
                self._match(TokenType.COMMA)
                size = self._parse_interval()
                offset = None
                if self._match(TokenType.COMMA):
                    offset = self._parse_interval()
                self._match(TokenType.R_PAREN)
                return Tumble(this, timecol, size, offset)
            elif self._match(TokenType.FUNCTION, "HOP"):
                self._match(TokenType.L_PAREN)
                this = self._parse_table()
                self._match(TokenType.COMMA)
                timecol = self._parse_column()
                self._match(TokenType.COMMA)
                slide = self._parse_interval()
                self._match(TokenType.COMMA)
                size = self._parse_interval()
                offset = None
                if self._match(TokenType.COMMA):
                    offset = self._parse_interval()
                self._match(TokenType.R_PAREN)
                return Hop(this, timecol, slide, size, offset)
            elif self._match(TokenType.FUNCTION, "CUMULATE"):
                self._match(TokenType.L_PAREN)
                this = self._parse_table()
                self._match(TokenType.COMMA)
                timecol = self._parse_column()
                self._match(TokenType.COMMA)
                step = self._parse_interval()
                self._match(TokenType.COMMA)
                size = self._parse_interval()
                offset = None
                if self._match(TokenType.COMMA):
                    offset = self._parse_interval()
                self._match(TokenType.R_PAREN)
                return Cumulate(this, timecol, step, size, offset)
            return super()._parse_function(optional_parens=optional_parens, anonymous=anonymous, any_token=any_token)

` 
there is another class custom.py which has the following code.
`from sqlglot import exp

class Tumble(exp.Expression):
    def __init__(self, this, timecol, size, offset=None):
        self.timecol = timecol
        self.size = size
        self.offset = offset
        self.args = {"this": this, "timecol": timecol, "size": size, "offset": offset}  # Set the args attribute as a dictionary
        self._type = "TUMBLE"  # Define the _type attribute
        self.comments = []  # Define the comments attribute
        self._id = id(self)  # Define the _id attribute

    def __repr__(self):
        args_str = ", ".join(f"{k}={v}" for k, v in self.args.items())
        return f"Tumble({args_str})"
    


class Hop(exp.Expression):
    def __init__(self, this, timecol, slide, size, offset=None):
        self.timecol = timecol
        self.slide = slide
        self.size = size
        self.offset = offset
        self.args = {"this": this, "timecol": timecol, "slide": slide, "size": size, "offset": offset}  
        self._type = "HOP"  
        self.comments = []  
        self._id = id(self)  

    def __repr__(self):
        args_str = ", ".join(f"{k}={v}" for k, v in self.args.items())
        return f"Hop({args_str})"
    


class Cumulate(exp.Expression):
    def __init__(self, this, timecol, step, size, offset=None):
        self.timecol = timecol
        self.step = step
        self.size = size
        self.offset = offset
        self.args = {"this": this, "timecol": timecol, "step": step, "size": size, "offset": offset}  
        self._type = "CUMULATE"  
        self.comments = []  
        self._id = id(self)  

    def __repr__(self):
        args_str = ", ".join(f"{k}={v}" for k, v in self.args.items())
        return f"Cumulate({args_str})"

def parse_one(sql, read):
    return read.parse(sql)`
So basically i have added functions like TUMBLE and HOP but i am phase too many errors while writing code changes for SESSION function.
I will really appreciate your help.
Thanks in advance.


here are some more details about the function.

SESSION takes three required parameters and one optional parameter:

SESSION(TABLE data [PARTITION BY(keycols, ...)], DESCRIPTOR(timecol), gap)
data: is a table parameter that can be any relation with an time attribute column.
keycols: is a column descriptor indicating which columns should be used to partition the data prior to session windows.
timecol: is a column descriptor indicating which time attributes column of data should be mapped to session windows.
gap: is the maximum interval in timestamp for two events to be considered part of the same session window.
