### ISSUE TITLE
sqlite to tsql translate same error

### ISSUE THREAD

**Issue by SophieGarden** [tobymao/sqlglot#3860]
sqlglot.transpile(sqlite_query, read="sqlite", write="tsql")[0]
a lot of these errors
 
     "gold": {
            "query": "SELECT T2.name, COUNT(*) FROM concert_singer.singer_in_concert AS T1 JOIN concert_singer.singer AS T2 ON T1.singer_id = T2.singer_id GROUP BY T2.singer_id",
            "exec_time": null,
            "error": "('42000', \"[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Column 'concert_singer.singer.Name' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. (8120) (SQLExecDirectW)\")",
            "res": null
        },
The error message indicates that the column concert_singer.singer.Name is not included in the GROUP BY clause, which is required in SQL Server when using non-aggregated columns in a SELECT statement with GROUP BY.
To fix this, you need to include T2.name in the GROUP BY clause. Here is the corrected query:
 
 
SELECT T2.name, COUNT(*) 
FROM concert_singer.singer_in_concert AS T1 
JOIN concert_singer.singer AS T2 
ON T1.singer_id = T2.singer_id 
GROUP BY T2.singer_id, T2.name
 
 
 
 
This ensures that all non-aggregated columns in the SELECT statement are included in the GROUP BY clause, which should resolve the error.

**Comment by georgesittas** [comment]
Hey, thank you for the report. This looks out of scope for us right now, but we'll be happy to accept a well-tested & documented PR if you want to take a stab at it. My gut feeling is that this may not be a trivial transformation to implement.
