### ISSUE TITLE
Duplicate Aliases Don't Have Their Lineage Traced Correctly

### ISSUE THREAD

**Issue by johnpawleylr** [tobymao/sqlglot#3862]
**Before you file an issue**
I am using the latest version of sqlglot at time of writing, `25.8.1`, and i am running for all dialects except Oracle, PRQL, & Snowflake. 

**Fully reproducible code snippet**
```python
import unittest
from sqlglot import parse_one, MappingSchema, Dialects
from sqlglot.expressions import DataType
from sqlglot.lineage import lineage


class TestSqlGlotLineage(unittest.TestCase):
    simple_schema = MappingSchema()
    simple_schema.add_table('table', {'field': DataType.Type.VARCHAR})
    simple_schema.add_table('table2', {'field': DataType.Type.VARCHAR})

    # Some dialects are excluded because the fail on qualifying the duplicate field aliases.
    dialect_params = [dialect for dialect in Dialects if
                      dialect not in [Dialects.ORACLE, Dialects.PRQL, Dialects.SNOWFLAKE]]

    def test_columns_with_the_same_name_which_are_aliased_by_sqlglot(self):
        """Both expressions have identical values but different lineages. They are both aliased as "field" by the
         optimizer. The lineage should be traced to the correct table."""

        for dialect in self.dialect_params:
            with self.subTest(msg=f"Testing dialect {dialect} with aliases", dialect=dialect):
                parsed_sql = parse_one(
                    'select table.field, table2.field from table join table2 on table.field = table2.field',
                    dialect=dialect
                )

                table2_field = parsed_sql.expressions[1]
                derived_lineage = lineage(
                    table2_field,
                    parsed_sql,
                    self.simple_schema,
                    dialect=dialect
                )

                self.assertEqual(table2_field.table, 'table2')
                self.assertEqual(derived_lineage.downstream[0].expression.alias_or_name, 'table2')

    def test_columns_with_the_same_name_without_aliasing_by_optimiser(self):
        """Both expressions have identical values but different lineages. They are not aliased by the optimizer. The
        lineage should be traced to the correct table."""
        for dialect in self.dialect_params:
            with self.subTest(msg=f"Testing dialect {dialect} without aliases", dialect=dialect):
                parsed_sql = parse_one(
                    'select table.field, table2.field from table join table2 on table.field = table2.field',
                    dialect=Dialects.BIGQUERY
                )

                table2_field = parsed_sql.expressions[1]
                derived_lineage = lineage(
                    table2_field,
                    parsed_sql,
                    self.simple_schema,
                    dialect=Dialects.BIGQUERY,
                    qualify_columns=False
                )

                self.assertEqual(table2_field.table, 'table2')
                self.assertEqual(derived_lineage.downstream[0].expression.alias_or_name, 'table2')
```

**Official Documentation**
I was originally investigating this for BigQuery, and [this is the documentation for duplicate aliases](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#duplicate_aliases). I included the rest of the dialects in the tests out of curiosity, but based on their behaviour I presume they all allow duplicate aliases aside from the 3 I have excluded.

**Thoughts**
Although the value of both fields in the query is necessarily the same, given the join expression, their lineage is different. This is important for me in my current application as they may have different configuration placed on each table, and so behaviour related to each column is not identical.

I think the source of the issue is here https://github.com/tobymao/sqlglot/blob/64e187c52cd9725ba79e6afbd444382eba9e5827/sqlglot/lineage.py#L95, where just the name is used to determine the column that we want the lineage for. In both test cases this is identical between the two projected expressions. If this was the fully qualified name then i think, with other changes in `to_node`, the lineage could be traced to source correctly.

**Comment by johnpawleylr** [comment]
alternatively, an option in the qualifier to alias fields with their fully qualified names, or ensure there's no duplicates, would also prevent this i think

**Comment by georgesittas** [comment]
Hey, I'm not sure if handling duplicate aliases is in scope for the lineage module, it seems like a niche use case to justify a refactor. @tobymao what's your take on this?

As a simple workaround, I'd suggest eliminating these duplicates by specifying explicit aliases in the source query.

**Comment by johnpawleylr** [comment]
fair enough, yes a pre-processing step on my part to scan Selects in the AST and de-duplicate aliases would likely fix the issue as well 👍 

though given i am working with user input queries, I'm loath to change them too much if i can avoid it, as it'll make the results seem disconnected from their input
