### ISSUE TITLE
TSQL Dialect failing with multiple DECLARE statements

### ISSUE THREAD

**Issue by sumanth-manchala** [tobymao/sqlglot#3874]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

```
from sqlglot import parse_one
parse_one("""
DECLARE @DWH_DateCreated date ='2024-10-01'
DECLARE @DWH_DateUpdated date ='2024-10-01'
""", dialect='tsql')
```
The above code results in below warning

```
WARNING:sqlglot:'DECLARE @DWH_DateCreated date ='2024-10-01'
            DECLARE @DWH_DateUpdated date ='2024-10-01'' contains unsupported syntax. Falling back to parsing as a 'Command'.
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.
SQL Server executes the above statements without an error

**Comment by georgesittas** [comment]
This is out of scope, SQLGlot can't handle multiple T-SQL statements that are implicitly separated using newlines -- try separating your statements using `;` instead.

By the way, you need to use `parse`, not `parse_one`, since there are >1 statements.
