### ISSUE TITLE
sqlglot does not support databricks SQL streaming syntax

### ISSUE THREAD

**Issue by ericvergnaud** [tobymao/sqlglot#3876]
**Fully reproducible code snippet**
sqlglot doesn't properly parse the following Databricks SQL statement:
`CREATE OR REFRESH STREAMING LIVE TABLE some_table AS SELECT * FROM some_source`

**Official Documentation**
[Docs](https://docs.databricks.com/en/tables/streaming.html)

**Comment by VaggelisD** [comment]
Hey @ericvergnaud,

Thanks for reporting this, I'll try to address any missing functionality. 

In the meantime, could you please point to any docs showcasing the `LIVE` specifier? I couldn't find it on various docs & tutorial pages, also not on the [CREATE STREAMING TABLE docs](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-streaming-table.html).

**Comment by ericvergnaud** [comment]
> Hey @ericvergnaud,
> 
> Thanks for reporting this, I'll try to address any missing functionality.
> 
> In the meantime, could you please point to any docs showcasing the `LIVE` specifier? I couldn't find it on various docs & tutorial pages, also not on the [CREATE STREAMING TABLE docs](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-streaming-table.html).

Looks like it's deprecated, but still largely in use. See https://docs.databricks.com/en/delta-live-tables/sql-ref.html

**Comment by ericvergnaud** [comment]
@VaggelisD @georgesittas with the `delta` docs link above, I believe this should be reopened ? Or should I create a new issue ?

**Comment by georgesittas** [comment]
This isn't a high priority item for us right now, but we'd be happy to accept a PR. Look into vaggelis' work related to the other properties, it should be similar.
