### ISSUE TITLE
DuckDB: Optimizer recommends `EXPLODE` function but it does not exist

### ISSUE THREAD

**Issue by NielsKorschinsky** [tobymao/sqlglot#3889]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`: Yes
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`: Yes
- Check if the issue still exists on main: Dont see a commit fixing it

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

```
print(
    optimize(
        sqlglot.parse_one(
            """
            SELECT
        UNNEST(e_account_roles)
    FROM TEST_TABLE
    """,
            read="duckdb",
        ),
        schema={
            "TEST_TABLE": {
                "e_account_roles": "STRUCT(a INT, b BOOLEAN)[])",
                "_id": "INT",
            },
        },
        dialect="duckdb",
    ).sql(pretty=True)
)
```

Output:
```
SELECT
  EXPLODE("test_table"."e_account_roles") AS "_col_1"
FROM "test_table" AS "test_table"
```

Expected Output:
```
SELECT
  UNNEST("test_table"."e_account_roles")
FROM "test_table" AS "test_table"
```

Error message from duckdb:
```
duckdb.duckdb.CatalogException: Catalog Error: Scalar Function with name explode does not exist!
Did you mean "exp"?
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

The explode function does not exist in duckdb.
Unnest can be applied to both a struct or a list.
In this case here, it is applied to a list.
Therefore it should:
1. Not have an alias, as it just moves the sub-rows to the main row
2. use Unnest and not explode

https://duckdb.org/docs/sql/query_syntax/unnest.html#unnesting-lists

Thanks!

Ps: great tool!

**Comment by georgesittas** [comment]
Hey 👋 

You need to specify the output dialect:

```python
>>> print(
...     optimize(
...         sqlglot.parse_one(
...             """
...             SELECT
...         UNNEST(e_account_roles)
...     FROM TEST_TABLE
...     """,
...             read="duckdb",
...         ),
...         schema={
...             "TEST_TABLE": {
...                 "e_account_roles": "STRUCT(a INT, b BOOLEAN)[])",
...                 "_id": "INT",
...             },
...         },
...         dialect="duckdb",
...     ).sql(dialect="duckdb", pretty=True)
... )
SELECT
  UNNEST("test_table"."e_account_roles") AS "_col_0"
FROM "test_table" AS "test_table"
```

**Comment by NielsKorschinsky** [comment]
Ooups, thanks! I though I got them all
