### ISSUE TITLE
CHECK constraint support missing

### ISSUE THREAD

**Issue by mpf82** [tobymao/sqlglot#389]
Similar to the [UNIQUE constraint](https://github.com/tobymao/sqlglot/issues/387), there seem to be several ways to define a CHECK constraint - either as a column constraint or as a table constraint.

The following statement is valid Postgres and contains a column check constraint, a named column check constraint, a table check constraint and a named table check constraint:

```sql
CREATE TABLE products (
    product_no INTEGER,
    name TEXT,
    price NUMERIC CHECK (price > 0),
    discounted_price NUMERIC CONSTRAINT positive_discount CHECK (discounted_price > 0), 
    CHECK (product_no > 1),
    CONSTRAINT valid_discount CHECK (price > discounted_price)
);
```

References:
* https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS
* https://sqlite.org/syntax/table-constraint.html
* https://sqlite.org/syntax/column-constraint.html

**Comment by tobymao** [comment]
low priority, happy to help you accomplish this in a PR, or may take a week
