### ISSUE TITLE
Support Athena UNLOAD...TO

### ISSUE THREAD

**Issue by symroe** [tobymao/sqlglot#3896]
Thanks for this library, it's really useful. 

I'm using the Athena dialect to validate some queries I have in a repo. Some of the queries use `UNLOAD...TO`, as documented here:

https://docs.aws.amazon.com/athena/latest/ug/unload.html

I think the Athena dialect should support this, but I also can't find a related dialect that supports it (e.g Redshift of Hive). 

<details><summary>Test code</summary>

```python
import sqlglot

# SQL example taken from the Athena docs
sql = """
UNLOAD (SELECT name1, address1, comment1, key1 FROM table1) 
TO 's3://amzn-s3-demo-bucket/ partitioned/' 
WITH (format = 'TEXTFILE', partitioned_by = ARRAY['key1'])
"""

sqlglot.parse_one(sql, dialect="athena")

```

```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 3, Col: 43.

```

</details> 

Please let me know if I've made a mistake in the way I'm using this library / or if this is out of scope, but I suspect this is a missing feature.

**Comment by symroe** [comment]
Thanks for the speedy fix! Tested on a more complex query and it's working fine :+1: 

I don't mind working on a PR for full parsing support...can you point me to some sort of starting point I can crib from? Maybe a PR that does similar?

**Comment by georgesittas** [comment]
> Thanks for the speedy fix! Tested on a more complex query and it's working fine 👍
> 
> I don't mind working on a PR for full parsing support...can you point me to some sort of starting point I can crib from? Maybe a PR that does similar?

I can't think of a good example right now, but perhaps you can use git blame to see how other [statement parsers](https://github.com/tobymao/sqlglot/blob/main/sqlglot/parser.py#L740-L770) were implemented in the past. It shouldn't be a big lift. 

But just to be clear, if you don't care about analyzing this statement (e.g. extracting info from the AST), or pretty-printing the AST, then you won't really need this right now.

**Comment by georgesittas** [comment]
I just noticed that you say the following in the issue description, btw:

> I'm using the Athena dialect to validate some queries I have in a repo. Some of the queries use UNLOAD...TO, as documented here [...]

I'm not sure what you mean by "validate" here, but please note that SQLGlot is not a syntax validator, i.e. it doesn't aim to catch all syntax/semantic errors. If you're writing manual code to do this, then perhaps you _will_ need to parse this into an AST and analyze it (see above reply).
