### ISSUE TITLE
MOD function is replaced by % in ORACLE. It shouldn't be.

### ISSUE THREAD

**Issue by Hal-H2Apps** [tobymao/sqlglot#3897]
**Before you file an issue**
SQLGlot 25.10.0

**Fully reproducible code snippet**
`sql = sqlglot.parse_one(sql='SELECT * FROM test WHERE MOD(col1, 4) = 3', read='oracle')
print(sql.sql('oracle'))`
--> SELECT * FROM Test WHERE col1 % 4 = 3
-->  ORA-00911: invalid character

It should stay as MOD. % is not valid in Oracle.

**Official Documentation**

https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/MOD.html

**Comment by georgesittas** [comment]
Closed by mistake, will take a look shortly
