### ISSUE TITLE
MySQL: literal "introducers"

### ISSUE THREAD

**Issue by rolandwalker** [tobymao/sqlglot#391]
https://github.com/tobymao/sqlglot/issues/384#issuecomment-1234852951
> this is pretty strange stuff

Oh it can get stranger.  Let's get weird!

MySQL has the construct of ["introducers"](https://dev.mysql.com/doc/refman/8.0/en/charset-introducer.html), which are prefix operators on literals.  One can imagine that they are a special form of quoting.

Introducers take the form of `_charsetname` like this:

```
select _utf8mb4 '¡Hola!';
```

When the literal is quoted the space after the introducer is optional:

```
select _utf8mb4'¡Hola!';
```

When the literal is not quoted or uses special quoting, the space after the introducer is required:

```
select _utf8mb4 0xC3A9;
select _utf8mb4 0b1100001110101001;
select _utf8mb4 b'1100001110101001';
```

There are about 40 introducers, for different character sets.

This is not a huge need for the mycli application.  I use this construct much more in generated SQL than interactively-edited queries.  Still I thought to take a look at what would have to be done to add it.  The attached patch seems like one place to start.  At least the errors start to make sense, assuming the space is maintained between the introducer and the literal.

The next step wasn't so clear.  There don't seem to be other prefix operators in the parser from which to copy.  And this construct must be MySQL-specific, and probably dropped when translating to another dialect.  The optional space might be a dealbreaker.

Maybe this was not the easiest spot to dig in.

[mysql_introducer_tokens.patch.txt](https://github.com/tobymao/sqlglot/files/9480707/mysql_introducer_tokens.patch.txt)

**Comment by tobymao** [comment]
i'll make a starter commit for you to start on and we can discuss how to implement this in the discussions
