### ISSUE TITLE
NULL LAST DESC gives error - invalid expression in parse_one using read = postgres

### ISSUE THREAD

**Issue by vishaldas-datafacade** [tobymao/sqlglot#3914]
Example sql:

```
SELECT "a", "b", "c"
FROM "schema"."table"
ORDER BY "c" NULLS LAST DESC
```

If i used `parse_one(sql_code, read="postgres")` I get the following error:

`Invalid expression / Unexpected token. Line 3, Col: 40.`

This is a valid expression in postgres.

**Comment by georgesittas** [comment]
I don't think this is a valid postgres query: `DESC` needs to go right after the column ([docs](https://www.postgresql.org/docs/current/sql-select.html)):

```
georgesittas=# select 1 as c order by c desc;
 c
---
 1
(1 row)

georgesittas=# select 1 as c order by c nulls last desc;
ERROR:  syntax error at or near "desc"
LINE 1: select 1 as c order by c nulls last desc;
                                            ^
```

Closing this, happy to reopen if proven wrong.

**Comment by vishaldas-datafacade** [comment]
Spot on. thanks!
