### ISSUE TITLE
Null order in union seems to affect data type inference

### ISSUE THREAD

**Issue by racevedoo** [tobymao/sqlglot#3916]
The resulting data type seems to be affected by the order of the `UNION` clauses. If a null alias `NULL as col` comes in the first clause, type annotators do not recognize the type properly. Am I missing something?

**Fully reproducible code snippet**
```python
>>> import sqlglot
>>> from sqlglot.optimizer import optimize
>>> optimize(sqlglot.parse_one("select col from (SELECT col FROM tbl UNION ALL SELECT null as col from tbl)",read='spark'),schema={"tbl": {"col": "INT"}}).expressions[0].type
DataType(this=Type.INT, nested=False)
>>> optimize(sqlglot.parse_one("select col from (SELECT null as col FROM tbl UNION ALL SELECT col from tbl)",read='spark'),schema={"tbl": {"col": "INT"}}).expressions[0].type
DataType(this=Type.NULL)
>>> import sqlglot
>>> sqlglot.__version__
'25.12.0'
```

From my understanding, both statements should return `DataType(this=Type.INT, nested=False)`

**Comment by georgesittas** [comment]
Interesting, good catch - thanks for the report! I'll take a look soon.
