### ISSUE TITLE
Is Splunk SPL a dialcect that might be added soon?

### ISSUE THREAD

**Issue by anirbans403** [tobymao/sqlglot#3922]
**Is your feature request related to a problem? Please describe.**
Converting between SQL and SPL. 

**Describe the solution you'd like**
Similar to the other dialect conversions, a support for Splunk SPL. 

**Describe alternatives you've considered**
Right now, using LLMs seem to be an easy way. 

**Additional context**
References - 
1. https://docs.splunk.com/Documentation/Splunk/latest/SearchReference/SQLtoSplunk

**Comment by tobymao** [comment]
no plans
