### ISSUE TITLE
Simplify the lineage output in case of cte

### ISSUE THREAD

**Issue by ludo9511** [tobymao/sqlglot#3928]
Hi, 
I have a t-sql query like this one:
```
WITH cte AS (
SELECT 
   t.col1 + t.col2 as col,
   t2.col3
   t.id
FROM 
   Table t LEFT JOIN Table2 t2 ON t.id = t2.id
)
SELECT 
   t.id,
   t.col1,
   cte.col
FROM
   Table t JOIN cte ON t.id = cte.id
```

I try to get the lineage of the column 'col'
The leaf-level  works fine in the expression, when I check the node.source value I can see that it returns the `col1+col2 as col` column and ignores the id and col3 columns. This is the output:
**SELECT 
   t.col1 + t.col2 as col**
**FROM 
   Table t** LEFT JOIN Table2 t2 ON t.id = t2.id

* why is the LEFT JOIN Table2 included in the node.source value? Is there a way to ignore the joins that do not contribute to the column logic and keep only the bolded script?

When I check the parent level of the tree, I can see that node.source correctly ignores the id and col1 columns, but it returns the full cte script and not only the part related to 'col'. For example, I get
```
WITH cte AS (
SELECT 
   t.col1 + t.col2 as col,
   t2.col3,
   t.id
FROM 
   Table t LEFT JOIN Table2 t2 
      ON t.id = t.id
)
SELECT 
   cte.col
FROM
   Table t JOIN cte ON t.id = cte.id
```

* Again, is there a way to include only the part of the cte that forms the selected lineage? 

I would like to have only the bolded script as a result:
**WITH cte AS (
SELECT 
   t.col1 + t.col2 as col**,
   t2.col3,
   t.id
**FROM 
   Table t** LEFT JOIN Table2 t2 
      ON t.id = t2.id
)
**SELECT 
   cte.col
FROM**
   Table t JOIN **cte** ON t.id = cte.id

I hope that makes sense. 
Thanks!

**Comment by ludo9511** [comment]
> We currently don't have plans to implement this simplification; it's out of scope for the lineage module.

Any idea how could I achieve that?

**Comment by georgesittas** [comment]
You'd have to further analyze the AST and transform it in a way that doesn't drop required information. This varies per use case, so I can't really expand without digging deeper into a specific example.
