### ISSUE TITLE
Failed to parse a statement with desc partition

### ISSUE THREAD

**Issue by gp1105739** [tobymao/sqlglot#3941]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
It fails to parse the simple statement below.
```
sqlglot.parse("desc schema.test partition (ds='2024-08-16')", read="spark")
```
**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by tobymao** [comment]
low priority, feel free to make a pr
