### ISSUE TITLE
Column Lineage Analysis

### ISSUE THREAD

**Issue by bkleck** [tobymao/sqlglot#3953]
Hi developers,

I currently have a use case where I would like to analyze column lineage of code in this format:
'''
SELECT id,
       app_id,
       click_cnt,
       publish_cnt
FROM
  (SELECT id,
          app_id,
          action_region_code,
          sum(click_cnt) AS click_cnt,
          sum(publish_cnt) AS publish_cnt
   FROM
     (SELECT id,
             app_id,
             sum(CASE WHEN event = 'click' THEN 1 END) AS click_cnt,
             sum(CASE WHEN event = 'publish' THEN 1 END) AS publish_cnt
      FROM db.event_log_hourly
      WHERE date = '${date}'
        AND event IN ('click', 'publish')
      GROUP BY id,
               app_id) x1
   GROUP BY id,
            app_id) x1

'''

Is there any way I can link the output column (click_cnt, publish_cnt) to the input table (event_log_hourly) as well as the events which was used for the columns (click, publish)? 
I have tried the find_all function but it may not be sufficient for this case. Is there any work-around that could be done?
I am also not too sure about the lineage function, is there any example you could provide?

Thank you very much in advance!

**Comment by georgesittas** [comment]
Based on your description, it looks like the `lineage` function is your best bet here. You can find examples in the [test suite](https://github.com/tobymao/sqlglot/blob/main/tests/test_lineage.py). Also, check out the [onboarding doc](https://github.com/tobymao/sqlglot/blob/main/posts/onboarding.md#column-level-lineage).

**Comment by bkleck** [comment]
@georgesittas thank you so much! 
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/b5c3f366-4191-4fa4-82da-6724410f4908">
Regarding this step to prepare SQL query for the lineage function, can qualifying all column references with the corresponding source tables be done using the optimizer without schema input?

**Comment by georgesittas** [comment]
Yeah, but there are not many guarantees when you don't have a schema, so it's gonna be best-effort. You can try.

**Comment by bkleck** [comment]
@georgesittas Yeah i did a small test and it didn't really work haha, maybe I can try with schema tomorrow. Would CTEs and sub-queries require schema too? I believe that will be a tricky scenario to tackle.

**Comment by bkleck** [comment]
@georgesittas I wrote a small qualifying function and ran it on my SQL:

```python
def qualify_columns(expression, schema):
    try:      
        expression = optimizer.qualify_tables.qualify_tables(expression)
        expression = optimizer.isolate_table_selects.isolate_table_selects(expression)
        expression = optimizer.qualify_columns.qualify_columns(expression, schema)

    except (OptimizeError) as e:
        pass  
 
    return expression

qualified_sql = qualify_columns(sql, schema=None)
```

**Comment by georgesittas** [comment]
You shouldn't have to do something manually, `lineage` [will qualify](https://github.com/tobymao/sqlglot/blob/main/sqlglot/lineage.py#L105-L110) your input query by default.

**Comment by bkleck** [comment]
@georgesittas Ah I see, let me try to input the table schema into the lineage function to see if it is better. Thank you so much for your help!

**Comment by bkleck** [comment]
Hello @georgesittas , is the "column" argument required for lineage to work? If so, may I know the input format for it?

**Comment by bkleck** [comment]
@georgesittas Hello, I have successfully converted my SQL code into an AST.

```python
ast = parse_one(sql_query)
for scope in traverse_scope(ast):
      for col in scope.columns:
                print(col)
```  

**The output is this:**
event_log_hour.app_id
event_log_hour.event
event_log_hour.event

**The input SQL looks like this:**
SELECT
event_log_hour.app_id AS app_id
SUM(CASE WHEN stg_app_event_log_hour.event = 'click' THEN 1 ELSE 0 END) AS click_cnt
SUM(CASE WHEN stg_app_event_log_hour.event = 'publish' THEN 1 ELSE 0 END) AS publish_cnt

**How do I get the relevant logic and alias for each column? Maybe an output like this:**
[event_log_hour.app_id, app_id, app_id]
[event_log_hour.event, SUM(CASE WHEN stg_app_event_log_hour.event = 'click' THEN 1 ELSE 0 END), click_cnt]
[event_log_hour.event, SUM(CASE WHEN stg_app_event_log_hour.event = 'publish' THEN 1 ELSE 0 END), publish_cnt]
