### ISSUE TITLE
Oracle root select surrounded in () been transpiled to CH causes an error

### ISSUE THREAD

**Issue by sleshJdev** [tobymao/sqlglot#3959]
**Fully reproducible code snippet**
```
from sqlglot.dialects import Oracle, ClickHouse
sqlglot.transpile("with core_sql as (select 1) (select 1)", read=Oracle, write=ClickHouse, comments=False)
['WITH core_sql AS (SELECT 1) (SELECT 1)']
```

Produces an error when running in CH:

```
Code: 62. DB::Exception: Syntax error: failed at position 29 ('('): (SELECT 1). Expected one of: token, Comma, FROM, SELECT. (SYNTAX_ERROR) (version 23.12.2.59 (official build)) , server ClickHouseNode
```

Works fine with `container-registry.oracle.com/database/free:latest`

Expected result: `WITH core_sql AS (SELECT 1) SELECT 1`. CH runs it successfully

**Comment by sleshJdev** [comment]
Would be appreciated for a hint where to start from since I'm not quite familiar with design/architecture of sqlglot.

**Comment by tobymao** [comment]
in the generator of clickhouse, probably need to remove the extra parenthesis, look at the ast and alter it
