### ISSUE TITLE
Add INTERPOLATE

### ISSUE THREAD

**Issue by alippai** [tobymao/sqlglot#396]
How can I add Vertica's `INTERPOLATE PREVIOUS VALUE`? https://www.vertica.com/docs/12.0.x/HTML/Content/Authoring/SQLReferenceManual/LanguageElements/Predicates/INTERPOLATE.htm

I didn't find it in the Customization / Dialects. I guess it's not enough to add it to KEYWORDS as there is no available TokenType?

**Comment by tobymao** [comment]
you'd have to add it to the join parser, look at how we're join using is implemented

https://github.com/tobymao/sqlglot/blob/81137e43d7163c5fed3e154eca406ccfb5f8a40c/sqlglot/parser.py#L1094

**Comment by alippai** [comment]
The format is `SELECT FROM a JOIN b ON a.x=b.x AND a.t INTERPOLATE PREVIOUS VALUE b.t`. So while it's a "Single expression allowed per JOIN" type, it's still within `ON` and used in the conjunction `AND` (and `OR`, `NOT` is not supported) and only equality supported.

I ended up adding it as RANGE_PARSER (also `KEYWORDS` and `TRANSFORM`), which means the restrictions won't be considered but at least the parse/transform works.

**Comment by tobymao** [comment]
are you planning to make a PR or only doing this for personal use?

**Comment by tobymao** [comment]
i guess it can all be done, the ast format is just python dictionaries. i have no plans right now to implement that myself, but i'm open to it
