### ISSUE TITLE
Incorrect Parsing Between Spark SQL and DuckDB

### ISSUE THREAD

**Issue by dor-bernstein** [tobymao/sqlglot#3972]
There are a couple of mistakes when translating from Spark to DuckDB

**Fully reproducible code snippet**
```python
from sqlglot import parse_one
 query = """SELECT SHA2(str, 256), ANY_VALUE(str2, true), FIRST(str3, true), LAST(str4, true), TRANSFORM(array_col)
FROM table 
GROUP BY group_col"""
 parse_one(query, dialect="spark").sql(dialect="duckdb")

``` 
The output is:
```python
SELECT SHA2(str, 256), ANY_VALUE(str2 IGNORE NULLS), FIRST(str3 IGNORE NULLS), LAST(str4 IGNORE NULLS), TRANSFORM(array_col) FROM "table" GROUP BY group_col
``` 
Which fails for three different reasons:
1. SHA2 is not a function in duckdb - the relevant function is sha256 
2. TRANSFORM should be LIST_TRANSFORM
3. When using non-window function, duckdb doesn't support RESPECT/IGNORE NULLS. The default behavior is without NULLs 
The expected output
**Official Documentation**
1. https://duckdb.org/docs/sql/functions/utility.html - SHA256
2. https://duckdb.org/docs/sql/functions/list.html - LIST_TRANSFORM
3. https://duckdb.org/docs/sql/functions/aggregates.html - aggregate functions

**Comment by dor-bernstein** [comment]
@VaggelisD The signature for transforming lists is LIST_TRANSFORM (https://duckdb.org/docs/sql/functions/lambda), while parse_one returns just TRANSFORM.

Many Thanks!

**Comment by VaggelisD** [comment]
Sorry for the confusion, I meant that your example is showcasing an invalid use of Spark's `TRANSFORM(expr, func)` as it doesn't have a lambda defined; Is this a typo?

**Comment by dor-bernstein** [comment]
Yes, sorry. I'm using TRANSFORM(expr, func) and parse_one returns TRANFORM(expr, translated_func), while it should be LIST_TRANSFORM(expr, translated_func)
