### ISSUE TITLE
Missing support for the SELECT-FOR clause in T-SQL

### ISSUE THREAD

**Issue by JaFigueroa-xt** [tobymao/sqlglot#3982]
The SELECT-FOR clause is used in T-SQL to format query results as XML or JSON. 
Currently, calling the `parse_one` function  in the following manner:
```python
sqlglot.parse_one("select 'Hello, World!' as Greeting for xml path('')", read='tsql')
```
Produces the following error:
```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 37.
  select 'Hello World!' as Greeting for xml path('')
```
I would expect the AST for the previous query to look something like the following:
```python
Select(
  expressions=[
    Alias(
      this=Literal(this=Hello World!, is_string=True),
      alias=Identifier(this=Greeting, quoted=False))],
  for=For(
    format=XMLFormat(
        path=Path(
            this=Literal=(this='', is_string=True))))
```
The previous AST does not use existing `Expression` classes. It is meant to illustrate a possible AST.

Detailed documentation about the SELECT-FOR clause can be found at 
https://learn.microsoft.com/en-us/sql/t-sql/queries/select-for-clause-transact-sql?view=sql-server-ver16

**Comment by georgesittas** [comment]
Not a high priority right now, happy to accept a well-crafted & tested PR for this.
