### ISSUE TITLE
Incorect tranformation of CAST(... as DATE) using SQLite 

### ISSUE THREAD

**Issue by focafull** [tobymao/sqlglot#3990]
**Fully reproducible code snippet**
When I try to explicitly cast a string to ```DATE``` using ```CAST(... as DATE)``` it will be replaced by ```DATE(...)```. Unfortunately, this will result in an incorrect output. 
```py
from sqlglot import parse_one

ast = parse_one("SELECT CAST('1990-01-01' as DATE)", read="sqlite")
ast.sql(dialect="sqlite") # "SELECT DATE('1990-01-01')"
```
When executing the original query (```SELECT CAST('1990-01-01' as DATE)```) in SQLite this is the output:
```sql
CAST('1990-01-01' as DATE)
1990
```
But when using the parsed query (```SELECT DATE('1990-01-01') ```) I get this output:
```sql
DATE('1990-01-01')    
1990-01-01
```

**Official Documentation**
I could not find anything in the SQLite documentation regarding CAST(... as DATE) but it seems to be valid syntax.

**Comment by georgesittas** [comment]
This is low priority for us, but we'll consider a well-crafted & tested PR. I'm curious, is this an issue that you actually came across in an application where SQLGlot is used, or just playing around? It seems pretty obscure.

**Comment by focafull** [comment]
I'm writing a tool for text-to-SQL tasks. Therefore, I use the BIRD dataset, which contains a few queries that use this syntax.
