### ISSUE TITLE
Support for `COUNT_BIG` in T-SQL

### ISSUE THREAD

**Issue by colin-ho** [tobymao/sqlglot#3995]
I'm currently using SQLGlot to transpile into T-SQL queries, some of them are `COUNT` queries. However, I'm having integer overflow issues because my table count exceeds int bounds. This is because `COUNT` in T-SQL returns an int, instead I would like to be using `COUNT_BIG` which returns a big-int. See: https://learn.microsoft.com/en-us/sql/t-sql/functions/count-big-transact-sql?view=sql-server-ver16

In other dialects like postgres, `COUNT` returns a big-int. https://www.postgresql.org/docs/8.2/functions-aggregate.html

Is it possible to modify the T-SQL dialect to use `COUNT_BIG`, or add an option to use this? 

Example current behaviour:
```
query = "SELECT COUNT(*) FROM big_table"
t_sql_query = sqlglot.transpile(query, "tsql")
print(t_sql_query)
['SELECT COUNT(*) FROM big_table']
```

**Comment by tobymao** [comment]
low priority for us, feel free to add a PR, we're happy to work with you on getting it in.

**Comment by colin-ho** [comment]
Gotcha, just made a PR
