### ISSUE TITLE
Token AT TIME ZONE can be followed by a column

### ISSUE THREAD

**Issue by jdclarke5** [tobymao/sqlglot#400]
Instead of specifying a string for an `AT TIME ZONE` zone, a column which contains that string can be referenced to create a valid query (at least this works in PostgreSQL).

For example, instead of `SELECT datetime_column AT TIME ZONE 'America/Denver' FROM table` it is also valid to have `SELECT datetime_column AT TIME ZONE zone_column FROM table`

Suggested change to https://github.com/tobymao/sqlglot/blob/main/sqlglot/parser.py#L1535 is:

```python
        return self.expression(exp.AtTimeZone, this=this, zone=(self._parse_string() or self._parse_column()))
```

**Comment by alippai** [comment]
Also it can be followed by multiple timezones:
```sql
SELECT datetime_column AT TIME ZONE 'America/Denver' AT TIME ZONE 'Asia/Tokyo'
```
It means make it timezone aware as America/Denver, then convert it to Asia/Tokyo

**Comment by tobymao** [comment]
@alippai 0843a29

**Comment by jdclarke5** [comment]
Legendary response time, thank you for maintaining this excellent package @tobymao
