### ISSUE TITLE
MAP function enquiry

### ISSUE THREAD

**Issue by bkleck** [tobymao/sqlglot#4001]
Hello, I currently have SELECT statements in this form:
SELECT user_id,
to_json(map(
       'item_id', NVL (item_id, 0), 
       'publish_cnt', publish_cnt, 
       'view_cnt', view_cnt
)) AS value

Each variable in the map function is defined by a name in quotes (e.g. 'item_id'), followed by the field which could be any form of SQL DML (e.g. NVL (item_id, 0)). 
Is there any module in the optimizer then can handle such cases, or convert it into proper SQL syntax?

Example output:
SELECT user_id,
       NVL (item_id, 0) AS item_id,
       publish_cnt AS publish_cnt,
       view_cnt AS view_cnt

Thanks in advance!

**Comment by georgesittas** [comment]
There's no such thing in the optimizer today, but you can maybe do it using a custom transformation.
