### ISSUE TITLE
Presto does not support alias for CREATE VIEW

### ISSUE THREAD

**Issue by usmanovbf** [tobymao/sqlglot#4003]
Hi! 

I am trying to add new keywords to the presto parser, such as [SECURITY DEFINER](https://trino.io/docs/current/sql/create-view.html#synopsis), and if I create custom _parse_create() method in [presto.py ](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/presto.py) by the [example](https://github.com/tobymao/sqlglot/blob/fcaae87d50653600048917945652cdf463bcc3cf/sqlglot/parser.py#L1720) and implement parsing the [syntax](https://trino.io/docs/current/sql/create-view.html#synopsis), I get the error, because I don't neeed to obtain alias for CREATE VIEW - Presto does not support that, e.g. `(cola)`. So, I need to remove the failing test below. If you agree, let's delete it.

Otherwise, I will need to implement custom _parse_create() method in [presto.py ](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/presto.py) with non-existing alias processing - it will be strange  

Dialect - presto

**Fully reproducible code snippet**
[It](https://github.com/tobymao/sqlglot/blob/fcaae87d50653600048917945652cdf463bcc3cf/tests/dialects/test_presto.py#L509_515) should be deleted, right?

``` python
        self.validate_all(
            "CREATE OR REPLACE VIEW x (cola) SELECT 1 as cola",
            write={
                "spark": "CREATE OR REPLACE VIEW x (cola) AS SELECT 1 AS cola",
                "presto": "CREATE OR REPLACE VIEW x AS SELECT 1 AS cola",
            },
        )
```

**Official Documentation**
There is no alias for that https://trino.io/docs/current/sql/create-view.html#synopsis

**Comment by georgesittas** [comment]
Fixed by #4008
