### ISSUE TITLE
Mysql dialect's TIME_MAPPING incorrectly maps %W

### ISSUE THREAD

**Issue by hellozepp** [tobymao/sqlglot#4011]
**Before you file an issue**

%a in the query converted to %W.
E.g. `select date_format(timestamp('2024-08-22 14:53:12'), '%a')`
output is converted to:
`select date_format(timestamp('2024-08-22 14:53:12'), '%W')`

mysql> select date_format(timestamp('2024-08-22 14:53:12'), '%W');
+-----------------------------------------------------+
| date_format(timestamp('2024-08-22 14:53:12'), '%W') |
+-----------------------------------------------------+
| Thursday                                            |
+-----------------------------------------------------+
1 row in set (0.02 sec)

mysql> select date_format(timestamp('2024-08-22 14:53:12'), '%a');
+-----------------------------------------------------+
| date_format(timestamp('2024-08-22 14:53:12'), '%a') |
+-----------------------------------------------------+
| Thu                                                 |
+-----------------------------------------------------+
1 row in set (0.00 sec)

**Official Documentation**
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-format
https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior

According to the python `strftime` formats documentation:
%A is Weekday as locale’s full name.(Sunday, Monday...)
%a is `Weekday as locale’s abbreviated name` (Sun .. Sat)

Let’s look at mysql:
%W Weekday name (Sunday..Saturday)
%a:Abbreviated weekday name (Sun .. Sat)

So, it is expected that the date_format output in presto or mysql should map %W to %A, as follows:
`mysql.py`
```
time_mapping = {
"%M": "%B",
"%c": "%-m",
"%e": "%-d",
"%h": "%I",
"%i": "%M",
"%s": "%S",
"%S": "%S",
"%u": "%W",
"%k": "%-H",
"%l": "%-I",
"%T": "%H:%M:%S",
- "%W": "%a",
+ "%W": "%A",
}
```
I observed that several other mappings worked well. If applied, I noticed that mysql and snowflack were affected in the single test. Then this may affect more, such as drill, hive, oracle, teradata, which also use %a to represent the pattern of Weekday as locale’s full name.

Why is this the case?

In addition, there is a PR #3855 in presto that does the conversion. Is this a workaround?
@VaggelisD PTAL

**Comment by VaggelisD** [comment]
Thanks for the detailed explanation, will look into this.
