### ISSUE TITLE
Invalid expression / Unexpected token

### ISSUE THREAD

**Issue by bkleck** [tobymao/sqlglot#4012]
I have cases of fields in my HiveQL query that starts with integers.
Example: 1min_publish_cnt

These cases result in the parse_one function throwing the following error:
ParseError: Invalid expression / Unexpected token.

Is there any way to ignore this and continue parsing it normally?
Thank you!

**Comment by georgesittas** [comment]
Can't repro, make sure to specify the dialect:


```python
>>> import sqlglot
>>> sqlglot.parse_one("1min_publish_cnt", "hive")
Column(
  this=Identifier(this=1min_publish_cnt, quoted=False))
```

**Comment by bkleck** [comment]
@georgesittas Is there any way to merge complex CTEs into the SQL expression?

Does not seem to work when i used optimizer.merge_subqueries.merge_subqueries
