### ISSUE TITLE
exp.JsonExtract will got a warning log in Starrocks

### ISSUE THREAD

**Issue by hellozepp** [tobymao/sqlglot#4013]
Ways to use:
sqlglot.transpile(sql, read="starrocks", write="starrocks")

**Fully reproducible code snippet**
```
select cast(parse_json(fieldvalue) -> '00000000-0000-0000-0000-00000000' as varchar ) as `code` from values('{"00000000-0000-0000-0000-00000000":"code01"}') as t(fieldvalue)
```
It will got a warnning log as following:
Invalid JSON path syntax. Unexpected TokenType.NUMBER at index 0: 00000000-0000-0000-0000-00000000

Then I tried to transpile spark to spark, which worked fine:
> sqlglot.transpile(sql, read="spark", write="spark")
```
SELECT CAST(PARSE_JSON(fieldvalue)['00000000-0000-0000-0000-00000000'] AS STRING) AS `code` FROM VALUES ('{"00000000-0000-0000-0000-00000000":"code01"}') AS t(fieldvalue)
```
It doesn't look like normal behavior, please help me.
Thank you!

**Comment by VaggelisD** [comment]
This query doesn't work for me in either engine (Spark 3.5, Starrocks).

**Comment by hellozepp** [comment]
@VaggelisD Sorry, I thought `from values` ​​was a universal paradigm. 
This is the paradigm of MySQL, thanks for correcting me.
I didn't verify it after rewriting the SQL in the production environment. I edit it in the first issue to avoid misunderstanding.

**Comment by hellozepp** [comment]
@VaggelisD This PR worked for me, thanks =)
