### ISSUE TITLE
Window clause improvements

### ISSUE THREAD

**Issue by alippai** [tobymao/sqlglot#402]
Two edge cases are not parsed well:
```sql
SELECT SUM(x) OVER (PARTITION BY a ORDER BY d ROWS 1 PRECEDING)
```
and 
```sql
SELECT SUM(x) OVER (PARTITION BY a ORDER BY date ROWS BETWEEN 1 PRECEDING 1 FOLLOWING)
```

The first will transpile assuming `BETWEEN`, the second throws parse error because `date` is parsed as keyword instead of column name.

https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS

**Comment by alippai** [comment]
The first one is interesting, if translating between languages, could the `ROWS 1 PRECEDING` be parsed as `ROWS BETWEEN 1 PRECEDING AND CURRENT ROW`?! Maybe handing the defaults is out of scope of this lib.

**Comment by tobymao** [comment]
what is the intended behavior of the first one?

**Comment by tobymao** [comment]
am i just missing CURRENT ROW?

**Comment by alippai** [comment]
I guess you are right, from behavior perspective it should be the same as specifying `CURRENT ROW` for `frame_end` (at least in PostgreSQL)

**Comment by alippai** [comment]
If I'm right you have `sql == transpile(sql)` identity checks only, but `transpile(sql) == transpile(transpile(sql))` should be always true for any query in a given dialect, that could be an another set of fixtures? (the first example wouldn't pass this)

**Comment by tobymao** [comment]
the issue with the second one is that date is a special keyword that can cast things to a date so it's sort of ambiguous, a quick workaround is to identify date as a column "date" ROWS ...

**Comment by alippai** [comment]
I know, your lib is the first which gets `date` column vs `date` keyword right most of the time. Thanks for handling it _very nicely_

**Comment by tobymao** [comment]
i've pushed a fix for the first issue, now sqlglot will put in AND CURRENT ROW,

the other issue which is ORDER BY DATE ROW is tricky to handle, if you can, please identify your columns for now or change the name of the column. 

thanks for reporting these issues!

**Comment by alippai** [comment]
Already did that on my side. Thanks for helping with the workaround.
Also managed to find the minimal case producing wrong output for you (in case you need it):
```sql
select * from a order by date desc limit 1
```

**Comment by alippai** [comment]
Is this also fixed on v6.0.0?

**Comment by tobymao** [comment]
it's in main

**Comment by alippai** [comment]
Sorry, I meant the
```sql
select * from a order by date desc limit 1
```
example. It's somewhat better on v6.0.0 in some cases (but not all)

**Comment by tobymao** [comment]
order by date desc works but not order by date row

**Comment by tobymao** [comment]
@alippai this is finally fixed, i realized this is easier than expected because date '2022-01-01' only works with literals

**Comment by alippai** [comment]
@tobymao very cool, no more regex for quotes needed. Thank you!
