### ISSUE TITLE
Snowflake dialect incorrectly writes DATEDIFF

### ISSUE THREAD

**Issue by sfc-gh-ybsat** [tobymao/sqlglot#4020]
**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

```python
import sqlglot
print(sqlglot.parse_one("select DATEDIFF(year, '2024-12-12', '2024-12-12') from table1", read="snowflake", dialect="snowflake"))
```

returns:
```
SELECT DATEDIFF('2024-12-12', '2024-12-12', YEAR) FROM table1
```

From the official docs, the syntax should be:
DATEDIFF( <date_or_time_part>, <date_or_time_expr1>, <date_or_time_expr2> )

But sqlglot is not abiding by the syntax, returning the date or time part last.

**Official Documentation**
Please include links to official SQL documentation related to your issue.

https://docs.snowflake.com/en/sql-reference/functions/datediff#syntax

**Comment by tobymao** [comment]
try to specify the output dialect
