### ISSUE TITLE
Incorrect transpilation of ALTER TABLE ADD COLUMN with parentheses in MySQL Dialect

### ISSUE THREAD

**Issue by GaoYusong** [tobymao/sqlglot#4021]
**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

```python
import sqlglot
sqlglot.transpile("alter table t0 add column (a int)", read="mysql", write="duckdb")
```
```python
['ALTER TABLE t0 (a AS int)']
```
expected output
```python
['ALTER TABLE t0 ADD COLUMN a INT']
```

`alter table t0 add column a int` without parentheses works fine, but `alter table t0 add column (a int)` is also valid in the MySQL dialect.

**Official Documentation**
Please include links to official SQL documentation related to your issue.
[MySQL ALTER TABLE](https://dev.mysql.com/doc/refman/8.4/en/alter-table.html) `| ADD [COLUMN] (col_name column_definition,...)`
[DUCKDB ALTER TABLE](https://duckdb.org/docs/sql/statements/alter_table.html)

**Comment by tobymao** [comment]
low priority feel to submit a pr
