### ISSUE TITLE
Request for support of RENAME TABLE in MySQL Dialect

### ISSUE THREAD

**Issue by GaoYusong** [tobymao/sqlglot#4022]
**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```python
import sqlglot
sqlglot.transpile("rename table a to b", read="mysql", write="duckdb")
```
```python
'rename table a to b' contains unsupported syntax. Falling back to parsing as a 'Command'.
['RENAME table a to b']
```
expected output
```python
['ALTER TABLE a RENAME to b']
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.
[MySQL RENAME TABLE](https://dev.mysql.com/doc/refman/8.4/en/rename-table.html)
[DuckDB RENAME TABLE](https://duckdb.org/docs/sql/statements/alter_table.html)

**Comment by tobymao** [comment]
low priority feel to submit a pr
