### ISSUE TITLE
Missing Support for JSONQuery in Oracle 

### ISSUE THREAD

**Issue by ashishshukla19** [tobymao/sqlglot#4027]
**Description**
I'm encountering an issue with the Oracle dialect in SQLGlot where it fails to parse queries containing JSON functions like JSON_QUERY. The expected behavior is to convert the Oracle query to an AST, but SQLGlot does not currently support this function, resulting in a parse failure.

**Details**
Oracle supports JSON functions such as JSON_QUERY, which allow retrieving JSON values from a JSON document. However, SQLGlot's Oracle dialect currently does not recognize this syntax, leading to a parsing error.

The specific functions and syntax that are not supported include:

**JSON_QUERY() Function
Syntax:**
`JSON_QUERY(expr, json_basic_path_expression [RETURNING data_type] [PRETTY] [ASCII] [WRAPPER] [ON ERROR])
`
**Parameters:**

- expr: The SQL expression that returns JSON data. This could be a table or view column value, a PL/SQL variable, or a bind variable.
- json_basic_path_expression: A SQL/JSON path expression used to evaluate expr and find JSON values that match the path.
- RETURNING: Specifies the data type of the returned instance, which can be VARCHAR2, CLOB, or BLOB.
- PRETTY: Pretty-prints the return character string by inserting newline characters and indenting.
- ASCII: Escapes any non-ASCII Unicode characters in the return character string.
- WRAPPER: Controls whether this function wraps the values matched by the path expression in an array wrapper.
- ON ERROR: Specifies the value returned by this function when errors occur (e.g., invalid JSON data, unmatched path expressions).
**Example**
The following code demonstrates the issue:

```from sqlglot.dialects.oracle import Oracle
from sqlglot import parse_one

sql = """
SELECT JSON_QUERY('{a:100, b:200, c:300}', '$.a' WITH WRAPPER) AS value
FROM DUAL;
"""

ast = parse_one(sql, dialect=Oracle)
print(repr(ast))
```
**Error Encountered**
When executing the code above, the following error is encountered:
`sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 2, Col: 39.
`
[link](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/JSON_QUERY.html) for the document

**Comment by georgesittas** [comment]
This is out of scope, well-tested PRs are welcome.
