### ISSUE TITLE
Get root table as alias

### ISSUE THREAD

**Issue by bkleck** [tobymao/sqlglot#4028]
Hello, I have utilized the following code:
```python
expression = optimizer.qualify_tables.qualify_tables(expression)
``` 

However, I realise that in the case of subqueries or CTEs, they are used as an alias instead of the actual derived table.
Example:
SELECT SUM(CASE WHEN t1.event THEN 1 END) AS event_count
FROM (
   SELECT event_log.event
   FROM event_log
) AS t1

Is there any function I can use to have the output in this format instead?
SELECT SUM(CASE WHEN event_log.event THEN 1 END) AS event_count
FROM (
   SELECT event_log.event
   FROM event_log
) AS t1

**Comment by georgesittas** [comment]
This isn't valid SQL, right? You're shadowing `event_log` using `t1`. This isn't supported today, the optimizer preserves aliases, you'll have to manually transform your AST.
