### ISSUE TITLE
Transpile Tino SQL to BigQuery SQL with `AT TIME ZONE` incorrectly.

### ISSUE THREAD

**Issue by grieve54706** [tobymao/sqlglot#4038]
## Descirption
I found an issue when converting Trino SQL to BigQuery SQL with `AT TIME ZONE`.

### Reproducible code
```python
import sqlglot

sql = sqlglot.transpile(
  """
  SELECT "PruchaseTimestamp" FROM "Orders"
  WHERE ("PruchaseTimestamp" = TIMESTAMP '2022-08-30 16:00:00.000' AT TIME ZONE 'America/Bahia_Banderas')
  """,
  read="trino", 
  write="bigquery"
)[0]
# SELECT `PruchaseTimestamp` FROM `Orders` 
# WHERE (`PruchaseTimestamp` = TIMESTAMP(DATETIME(CAST('2022-08-30 16:00:00.000' AS DATETIME), 'America/Bahia_Banderas')))
```

The `TIMESTAMP(DATETIME(CAST('2022-08-30 16:00:00.000' AS DATETIME), 'America/Bahia_Banderas'))` seem to be a wrong value.
It should be `TIMESTAMP('2022-08-30 16:00:00.000', 'America/Bahia_Banderas')`.

In BigQuery, if I fix the wrong type,
```sql
SELECT TIMESTAMP('2022-08-30 16:00:00.000', 'America/Bahia_Banderas'); -- 2022-08-30 21:00:00 UTC
SELECT TIMESTAMP(DATETIME(CAST('2022-08-30 16:00:00.000' AS TIMESTAMP), 'America/Bahia_Banderas')); -- 2022-08-30 11:00:00 UTC
```

**Comment by VaggelisD** [comment]
Hey @grieve54706, thanks for reporting this.

Although I attempted to fix this issue in the PR, by double checking the expected result I'm now not sure if it's actually correct; Could you explain your reasoning behind it?


For context, on my local setup in Presto this is the (partial) result of your query (Note that `America/Bahia_Banderas` is -05:00 for Aug 2022):

```SQL
presto> select TIMESTAMP '2022-08-30 16:00:00.000' AT TIME ZONE 'America/Bahia_Banderas';
                     _col0
------------------------------------------------
 2022-08-30 11:00:00.000 America/Bahia_Banderas
(1 row)
```

For BigQuery, this is the expected result as you mention:

```SQL
SELECT TIMESTAMP('2022-08-30 16:00:00.000', 'America/Bahia_Banderas');
2022-08-30 21:00:00 UTC
```

From my understanding, Presto converts the timestamp from session time (UTC) to the selected zone, while BQ seems to merge the datetime value with the selected zone and then converts that to UTC so the result can't deviate from that.

**Comment by grieve54706** [comment]
Hi @VaggelisD,

Yes, you're right. I made a mistake about the meaning of AT TIME ZONE in Trino. The behavior of the SQLglot translation was correct all along. I apologize for wasting your time. Thanks for your help.

**Comment by VaggelisD** [comment]
Thank you for confirming! Bridging the gap between Presto/Trino's `AT TIME ZONE` and BQ does seems awkward; Maybe the BQ result could be casted to `DATETIME` to remove the `UTC` part too (?)

Will go ahead and close this for now.
