### ISSUE TITLE
Spark exp.RegexpExtract transpile is incorrect

### ISSUE THREAD

**Issue by hellozepp** [tobymao/sqlglot#4039]
**Before you file an issue**
sqlglot.transpile(sql, read="presto", write="spark")

**Fully reproducible code snippet**
The default value of the group parameter of REGEXP_EXTRACT is different between presto and spark:
- Presto defaults to 0
- Spark defaults to 1

presto sql as following:
```
select regexp_extract('aaaa', 'a|b|c')
```

The sql transpile to spark is as follows:
```
select regexp_extract('aaaa', 'a|b|c')
```

Expected result:
```
select regexp_extract('aaaa', 'a|b|c', 0)
```

## Environmental Verification

When execute in spark sql, output as following:
`SELECT regexp_extract('1a 2b 14m', '(\\d+)([a-z]+)') limit 100`
```
+-------------------------------------------+
|regexp_extract(1a 2b 14m, (\d+)([a-z]+), 1)|
+-------------------------------------------+
| 1|
+-------------------------------------------+

24/09/03 11:43:36 INFO SparkUI: Stopped Spark web UI at http://192.168.15.150:4040
```

And the result of presto execution is:
`SELECT regexp_extract('1a 2b 14m', '(\d+)([a-z]+)') limit 100`
![image](https://github.com/user-attachments/assets/5cad3a5f-c0e5-41be-a65b-c25e623b14b8)

## Doc
[Spark regexp_extract](https://spark.apache.org/docs/latest/api/sql/#regexp_extract) | [Presto](https://prestodb.io/docs/current/functions/regexp.html#regexp_extract-string-pattern-varchar)

**Comment by hellozepp** [comment]
Should Presto Parser add a 0 to the `group`?

**Comment by VaggelisD** [comment]
I think this sounds right, we can canonicalize the default value @ parse time for each dialect; I'll also do a pass over other dialects to document their behavior.

**Comment by hellozepp** [comment]
@VaggelisD Thanks for the quick fix!
