### ISSUE TITLE
DATE_ADD func should be exp.TsOrDsAdd

### ISSUE THREAD

**Issue by hellozepp** [tobymao/sqlglot#4046]
**Before you file an issue**

parse_one(sql, read="presto")

```
Select(
  expressions=[
    DateAdd(
      this=Cast(
        this=Literal(this=2001-08-22, is_string=True),
        to=DataType(this=Type.DATE, nested=False)),
      expression=Literal(this=1, is_string=False),
      unit=Var(this=DAY)),
    DateAdd(
      this=Column(
        this=Identifier(this=current, quoted=False)),
      expression=Literal(this=1, is_string=False),
      unit=Var(this=DAY))])
```

expected output:
```
Select(
  expressions=[
    TsOrDsAdd(
      this=Cast(
        this=Literal(this=2001-08-22, is_string=True),
        to=DataType(this=Type.DATE, nested=False)),
      expression=Literal(this=1, is_string=False),
      unit=Var(this=DAY)),
    TsOrDsAdd(
      this=Column(
        this=Identifier(this=current, quoted=False)),
      expression=Literal(this=1, is_string=False),
      unit=Var(this=DAY))])
```

**Official Documentation**
https://prestodb.io/docs/current/functions/datetime.html#date_add-unit-value-timestamp-same-as-input

As shown in the screenshot below, presto's DATE_ADD can return different types based on date or timestamp. This should be exp.TsOrDsAdd, otherwise it will affect the use of the AST.
![img_v3_02ec_8cdfa3db-a3df-480e-8297-7ca35c5fd7bg](https://github.com/user-attachments/assets/e3470dad-af63-4cf6-a7b7-6dcf8e43b003)

**Comment by georgesittas** [comment]
Can you share an example where this AST actually causes issues?

**Comment by tobymao** [comment]
i don't think this is right, in presto, you can't date_add a string

**Comment by hellozepp** [comment]
Hi~ @tobymao . Sorry, I misunderstood the meaning of tsOrDs, it was: timestring or datestring. I thought it was: timestamp or date add.

Maybe I can clarify, I want DateAdd to tell me its return_type like TsOrDsAdd, otherwise presto can return both date and timestamp type, while hive and spark can only return date. At the AST, I can't get more information to determine whether I should use our commercial version of the engine's date_add (return dateType) or TIMESTAMP_OR_DATE_ADD (return timestamp or date)
![image](https://github.com/user-attachments/assets/5dffe9bb-7469-4873-a6bd-c54733e19456)

**Comment by tobymao** [comment]
you'd use the optimizer annotate_types for this cc @VaggelisD

**Comment by VaggelisD** [comment]
Right, this can also be solved by extending Presto's annotator such that `exp.DateAdd` is annotated by the type of it's input. 

We have plans to start working more on that, but if you wish to use it (or contribute it) in the meantime, here's a relevant PR for Spark's SUBSTR annotation: https://github.com/tobymao/sqlglot/pull/4004

**Comment by hellozepp** [comment]
@VaggelisD I understand.
```
optimizer.optimize(ast, schema={"tbl": {"col": type}}, dialect=dialect)
```
When I static transpile a sql to other dialect`s sql, I have no way of knowing the schema, so I may not be able to use this feature.

Alternatively, can we carry a read_dialect to the target generator during sqlglot.parser.Parser._parse_select, so that if the generator knows it is presto, it will be transpiled into `TIMESTAMP_OR_DATE_ADD` sql function, and if it is `spark`, it will be `date_add` (The AST is intentionally dialect-agnostic, but it is really needed in some cases)

Another idea is to add a return_types of date in the arg_types of spark's `exp.DateAdd`. If None, I will use TIMESTAMP_OR_DATE_ADD to let the engine guess the output type.
