### ISSUE TITLE
ClickHouse to support Oracle TRUNC/SYSDATE functions

### ISSUE THREAD

**Issue by sleshJdev** [tobymao/sqlglot#4054]
Oracle
```
select trunc(SYSDATE, 'YEAR') from dual;
```

needs to be converted to ClickHouse
```
SELECT dateTrunc('YEAR', now())
```

**Comment by georgesittas** [comment]
Getting rid of `FROM DUAL` is out of scope for us right now, you can remove it using a custom transformation.

**Comment by sleshJdev** [comment]
The issue is about `TRUNC/SYSDATE`, not getting rid of `FROM DUAL`

**Comment by georgesittas** [comment]
Yep, I fixed that in https://github.com/tobymao/sqlglot/commit/d3ee5ea6abd0dfb6e5216bf212e9e737c163eeb9.
