### ISSUE TITLE
CREATE/DROP COLLATION Support

### ISSUE THREAD

**Issue by s1101010110** [tobymao/sqlglot#4055]
For PostgreSQL dialect, when parsing some scripts that contains CREATE/DROP COLLATION sqlglot says: 

```
'CREATE COLLATION IF NOT EXISTS "my-case-insensitive-collation" (LC_COLLATE = 'en-u-ks-primary', LC_CTYPE = 'en-u-' contains unsupported syntax. Falling back to parsing as a 'Command'.

'DROP COLLATION "my-case-insensitive-collation"' contains unsupported syntax. Falling back to parsing as a 'Command'.
```

Is it possible to add a feature that brings support to parsing create/drop collation more structured like other create/drop object operations, like

```
Create(
  this=Collation(
    this=Identifier(this=my-case-insensitive-collation, quoted=False),
    params....)
```

**Comment by georgesittas** [comment]
Hey, thanks for the report. This isn't a high priority for us right now, but we're happy to accept well-tested/documented PRs.
