### ISSUE TITLE
ClickHouse uppercases the first literal for date_trunc() function

### ISSUE THREAD

**Issue by EugeneTorap** [tobymao/sqlglot#4058]
I found an issue when uppercases the first string literal for date_trunc() but ClickHouse only supports lowercase letters for the first argument.
https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#date_trunc

```python
from sqlglot import parse_one, Dialects

sql = "SELECT date_trunc('hour', now())"
print(parse_one(sql, read=Dialects.CLICKHOUSE).sql(dialect=Dialects.CLICKHOUSE))
```

We got the such output:
```
SELECT date_trunc('HOUR', now())
```

But I expect  `SELECT date_trunc('hour', now())`

**Comment by georgesittas** [comment]
The example shared works fine for me, can you show the error you encountered?

**Comment by EugeneTorap** [comment]
@georgesittas This is ClickHouse server error:
```
Code: 36. DB::Exception: HOUR doesn't look like datepart name in dateTrunc: While processing dateTrunc('HOUR', now()).
(BAD_ARGUMENTS) (version 23.8.16.16 (official build))
```

**Comment by georgesittas** [comment]
I'm not seeing this:

```
(.venv) ➜  clickhouse
ClickHouse local version 24.2.1.187 (official build).

georges-mbp.home :) SELECT date_trunc('HOUR', now());

SELECT date_trunc('HOUR', now())

Query id: 6ec59eb8-592c-46b4-a890-4f33208c44a1

┌─dateTrunc('HOUR', now())─┐
│      2024-09-05 12:00:00 │
└──────────────────────────┘

1 row in set. Elapsed: 0.003 sec.
```

**Comment by georgesittas** [comment]
The [docs](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#date_trunc) explicitly say:

> `unit` argument is case-insensitive.

So I see no issue here.

**Comment by georgesittas** [comment]
I see. Fixing this isn't a high priority for us right now, but feel free to take a stab at it if you want. The unit is canonicalized inside `DateTrunc`'s constructor.
