### ISSUE TITLE
Can't extract MAP expressions

### ISSUE THREAD

**Issue by bkleck** [tobymao/sqlglot#4059]
Hello, good day!
I have successfully parsed a sample SQL using the following code, with the format of the output AST displayed below:
```python
ast = parse_one(trial_sql, 'hive')
``` 
**Output AST:**
SELECT MAP(ARRAY('id', 'user_id'), ARRAY(TRY_CAST(id AS TEXT), user_id)) AS KEY, MAP(ARRAY('click_cnt', 'publish_cnt', ARRAY(TRY_CAST(COUNT(1) AS TEXT), TRY_CAST(COUNT(CASE WHEN is_success = 1 THEN 1 ELSE NULL END) AS TEXT))) AS value FROM table

However, when I iterate through the AST above to get the MAP functions, I got nothing.
```python
for map in ast.find_all(exp.Map):
   print(map)
``` 

How do I get the contents within the MAP functions? In this case, I would like to return the following:

MAP(ARRAY('id', 'user_id'), ARRAY(TRY_CAST(id AS TEXT), user_id)) 
MAP(ARRAY('click_cnt', 'publish_cnt', ARRAY(TRY_CAST(COUNT(1) AS TEXT), TRY_CAST(COUNT(CASE WHEN is_success = 1 THEN 1 ELSE NULL END) AS TEXT)))

**Comment by tobymao** [comment]
please read this guide so you can learn more about how to use the library https://github.com/tobymao/sqlglot/blob/main/posts/ast_primer.md

if you print the ast, you'll see that the relevant expression is a VarMap, not a Map
