### ISSUE TITLE
Transpile UNION (ALL) BY NAME

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#4100]
**Is your feature request related to a problem? Please describe.**
Some dialects don't support `UNION ALL BY NAME` - which is of course a pity. But it would be possible to transpile it I think.

**Describe the solution you'd like**
```python
import sqlglot as sg


print(
    sqlglot.parse_one(
        """select 1 as a  union all by name select 2 as b""",
        dialect="duckdb",
    ).sql("tsql")
)
# should output:
# SELECT 1 AS a, null as b UNION ALL SELECT null, 2 AS b
```

**Describe alternatives you've considered**
Well, I could write some transformer on my own. Which I'll do in case this is rejected :)

**Additional context**

**Comment by VaggelisD** [comment]
To add to this, I think the transpilation is not always possible, for instance consider this query [from the docs](https://duckdb.org/docs/sql/query_syntax/setops.html#union-all-by-name):

```SQL
SELECT * FROM capitals
UNION BY NAME
SELECT * FROM weather;
```

SQLGlot can't always know the number & names of columns from each relation to fill in with nulls. 

Not only that, but you must also consider the fact that the projection list might not always match the columns 1:1, e.g. one side could select from a table function which explodes into multiple columns and so on.

Of course, if you manage to prototype it we can happily take a look at merging it.

**Comment by aersam** [comment]
Yep I would say that anything containing a star would just raise a warning and not be transpiled. there's a qualify columns function in the optimize module that can help

**Comment by aersam** [comment]
Hi Guys!

I had to implement this, and it was straightforward to do. If does not support Star Expressions, but the output of `sqlglot.optimizer.qualify.qualify` works perfectly. 

```python


def _is_star(expr: exp.Expression) -> bool:
    if isinstance(expr, exp.Star):
        return True
    if isinstance(expr, exp.Column):
        return isinstance(expr.this, exp.Star)
    return False

def _transpile_all_by_name(thing: exp.Expression):
    if isinstance(thing, exp.Union) and thing.args.get("by_name"):
        q1 = thing.expression
        q1_exprs = q1.expressions
        q2 = thing.expression
        q2_exprs = q2.expressions
        q1_names = list()
        q1_expr_dict = dict()
        for expr in q1_exprs:
            if _is_star(expr) or not expr.alias_or_name:
                return thing  # cannot transpile, maybe log some warning?            
            q1_names.append(expr.alias_or_name)
            q1_expr_dict[expr.alias_or_name] = expr
        q2_names = list()
        q2_expr_dict = dict()
        for expr in q2_exprs:
            if _is_star(expr) or not expr.alias_or_name:
                return thing  # cannot transpile, maybe log some warning?
            q2_names.append(expr.alias_or_name)
            q2_expr_dict[expr.alias_or_name] = expr
        if q1_names == q2_names:
            return exp.Union(  # yay, we can just use the same names and order!
                this=q1,
                expression=q2,
                distinct=thing.args.get("distinct", False),
            )

        all_cols = q1_names + list(
            set(q2_names) - set(q1_names)
        )  # try preserve order somehow, at least for everything in query 1
        new_q1_exprs = []
        new_q2_exprs = []

        for ac in all_cols:
            if ac in q1_expr_dict:
                new_q1_exprs.append(q1_expr_dict[ac])
            else:
                new_q1_exprs.append(exp.null().as_(ac))
            if ac in q2_expr_dict:
                new_q2_exprs.append(q2_expr_dict[ac])
            else:
                new_q2_exprs.append(exp.null().as_(ac))
        q1 = q1.copy()  # we do not want to modify the original  object
        q2 = q2.copy()
        q1.set("expressions", new_q1_exprs)
        q2.set("expressions", new_q2_exprs)
        return exp.Union(
            this=q1,
            expression=q2,
            distinct=thing.args.get("distinct", False),
        )
    return thing
```

The implementation works for simple selects, and should probably cover 90% of the use cases at least. I did not test pivot and stuff like that, but needs some more testing

@VaggelisD : Is this something you would add somehow? I think most dialects do not support `union all by name` (which is sad, they really should support it! )

**Comment by georgesittas** [comment]
Hey @aersam 👋

Appreciate you sharing this solution, but I think we'll hold off introducing `UNION BY NAME` logic in the optimizer for now. It's a good idea, especially if applied after star expansion, but it's low priority for the core team and I'm worried about the maintenance burden it may incur.
