### ISSUE TITLE
 Add Support for AS OF TIMESTAMP Syntax in Oracle Flashback Queries

### ISSUE THREAD

**Issue by ashishshukla19** [tobymao/sqlglot#4103]
**Description**: I am currently working on parsing Oracle SQL queries using SQLGlot and encountered an issue when trying to parse the AS OF clause, specifically used in Oracle Flashback queries. The parser throws an error when encountering the AS OF TIMESTAMP syntax, which is used to query data at a previous point in time.

**Example Query**
```
SELECT COUNT(*)
FROM flashback_query_test AS OF TIMESTAMP TO_TIMESTAMP('2004-03-29 13:34:12', 'YYYY-MM-DD HH24:MI:SS');

```
**Error**: The error produced is:
`sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 3, Col: 43.
`
**Steps to Reproduce:**

> Use the following code snippet to try and parse the above SQL query with the Oracle dialec
```
from sqlglot import parse_one

sql = """
SELECT COUNT(*)
FROM flashback_query_test AS OF TIMESTAMP TO_TIMESTAMP('2004-03-29 13:34:12', 'YYYY-MM-DD HH24:MI:SS');
"""
print(repr(parse_one(sql, read='oracle')))

```

> The parser raises a ParseError indicating an unexpected token at the AS OF part of the query.

**Proposed Solutio**n: It would be helpful to have SQLGlot support for parsing AS OF in Oracle queries, as it’s an important feature for flashback queries, allowing users to query historical data.

**Reference**: The AS OF syntax is a key feature in Oracle Flashback queries, as documented [here](https://oracle-base.com/articles/10g/flashback-query-10g).

**Comment by georgesittas** [comment]
Hi, this is not high priority for us, happy to accept a well-tested PR.
