### ISSUE TITLE
Add support for EXECUTE IMMEDIATE in Trino

### ISSUE THREAD

**Issue by usmanovbf** [tobymao/sqlglot#4118]
**Is your feature request related to a problem? Please describe.**
For now, there is no way to parse `EXECUTE IMMEDIATE` [statement](https://trino.io/docs/current/sql/execute-immediate.html) in Trino, since there is an error for

```
self.validate_identity(
            """EXECUTE IMMEDIATE 'INSERT INTO a (b, c, d) VALUES (?, ?, ?)' USING DATE '2024-08-23', TIMESTAMP '2024-08-23 09:28:42.000000 UTC', DOUBLE '0.0', 'test'"""
        )
```
```
'EXECUTE IMMEDIATE 'INSERT INTO a (b, c, d) VALUES (?, ?, ?)' USING DATE '2024-08-23', TIMESTAMP '202' contains unsupported syntax. Falling back to parsing as a 'Command'.
```

**Describe the solution you'd like**
Add parser for the  `EXECUTE IMMEDIATE` statement

**Describe alternatives you've considered**
-
**Additional context**
I was confused how to do it since it clashes with the existing TokenType.EXECUTE - see the [discussion](https://github.com/tobymao/sqlglot/discussions/4114#discussioncomment-10640275)

**Comment by tobymao** [comment]
low priority. feel free to submit a well crafted pr but this will not be prioritized by the core team
