### ISSUE TITLE
"CURRENT_TIMESTAMP()" for presto DB 

### ISSUE THREAD

**Issue by caolf** [tobymao/sqlglot#4120]
##  code: 
`
sql_str = 'SELECT * FROM "user"  WHERE created_at <= now()' 

parsed_sql = parse_one(sql_str, dialect="presto")

.......

parsed_sql.sql() //  result: 'SELECT * FROM "user" AS u WHERE created_at <= CURRENT_TIMESTAMP()'
`
## version
"sqlglot>=25.21.1"

CURRENT_TIMESTAMP or now() is support for postgresql , but not " CURRENT_TIMESTAMP() ", maybe this is a issue! 

need your help , thanks!

**Comment by caolf** [comment]
@tobymao need your help , thanks!

**Comment by tobymao** [comment]
specify the output dialect

**Comment by caolf** [comment]
parsed_sql = parse_one(sql_str, dialect="presto")

yes, i do , but The result is still “ CURRENT_TIMESTAMP()” 


> specify the output dialect

**Comment by caolf** [comment]
@tobymao

**Comment by caolf** [comment]
“now()” will be replaced by " CURRENT_TIMESTAMP() " for "presto"

**Comment by caolf** [comment]
> specify the output dialect


parsed_sql.sql(dialect=Dialects.POSTGRES)

ok, thanks
