### ISSUE TITLE
Table expression found from `CREATE|DROP DATABASE` statement

### ISSUE THREAD

**Issue by wonderbeyond** [tobymao/sqlglot#4121]
I need to extract table references from SQL statements, however I found that CREATE|DROP DATABASE statements also yield table expressions, demo below:

```
>>> from sqlglot import parse_one, exp
>>> for t in parse_one("CREATE DATABASE foo").find_all(exp.Table):
...     print(t)
foo
>>> for t in parse_one("DROP DATABASE foo").find_all(exp.Table):
...     print(t)
foo
```

This behavior make me confused, is it a bug?

**Comment by georgesittas** [comment]
This is expected, `exp.Table` is currently used to represent a qualified database object, so it's used for tables, schemas, catalogs etc. You'll need to use additional context (e.g. the `Create` node's `kind` arg) to only keep tables.
