### ISSUE TITLE
Incorrect transpile from TSQL to Snowflake

### ISSUE THREAD

**Issue by dluo-sig** [tobymao/sqlglot#4134]
Issues
- CHARINDEX is being incorrectly converted to STR_POSITION with the parameters flipped.  However, you can actually leave it directly as-is, or use the snowflake function [POSITION](https://docs.snowflake.com/en/sql-reference/functions/position), which is equivalent to CHARINDEX with additional syntax options.
- IIF can be directly converted to [IFF](https://docs.snowflake.com/en/sql-reference/functions/iff) instead of CASE statement

```python
snowflake_content = transpile(content, read='tsql', write='snowflake',
                                  pretty=True, normalize_functions=False)[0]
```

Input
```sql
SELECT IIF(charindex('Search',ColumnName)>0,'',' Value') FROM TableName
```

Output
```sql
SELECT CASE WHEN STR_POSITION(ColumnName, 'Search') > 0 THEN '' ELSE ' Value' END FROM TableName
```

Expected
```sql
SELECT IFF(POSITION('Search',ColumnName)>0,'',' Value') FROM TableName
```

**Comment by tobymao** [comment]
low priority, please feel to file a well tested PR

**Comment by dluo-sig** [comment]
Couple of questions.

- Why is this closed if it's an outstanding issue?
- Do you mind pointing me to the right place to start looking to resolve this?  I checked in `sqlglot/dialects/snowflake.py` and there's no reference to those function names.

**Comment by tobymao** [comment]
we only keep issues open for things that the core team is actively going to fix. take a look at dialects and see how various overrides are performed, also take a look at tests/dialects/snowflake to see existing test cases and scenariors.

feel free to join tobikodata.com/slack if you want to chat with us for help on implementing this pr

**Comment by dluo-sig** [comment]
Got it, thanks
