### ISSUE TITLE
T-SQL PARSENAME function support

### ISSUE THREAD

**Issue by daihuynh** [tobymao/sqlglot#4154]
I'm using sqlglot to transpile T-SQL scripts to DataBricks dialect. However, PARSENAME function is not supported and kept after transpiling.

```
sqlglot.transpile("SELECT PARSENAME('1.0.0', 3) AS MajorVersion", 
                  read=sqlglot.Dialects.TSQL, 
                  write=sqlglot.Dialects.DATABRICKS)
```

Expectation in DataBricks/Spark dialect

```
SELECT SPLIT_PART('1.0.0', '.', 1) AS MajorVersion
```

Note that, PARSENAME use a reversed index counting from right to left instead of left to right like in SPLIT_PART.

Could this be supported?

**Comment by tobymao** [comment]
yes, it can be done, but this is low priority for us, feel free to submit a well tested PR if you want this feature.
