### ISSUE TITLE
PostgreSQL alter table with multiple actions not supported

### ISSUE THREAD

**Issue by wonderbeyond** [tobymao/sqlglot#4155]
PostgreSQL's alter table statement can have multiple actions as documented under https://www.postgresql.org/docs/current/sql-altertable.html

However I have the following SQL valid for execution but parsed by sqlglot as a 'Command'.

```
alter table ab add column remark text, drop column a
```

**Comment by VaggelisD** [comment]
This is currently out of scope for us as it'll require a non-trivial refactor in how `ALTER` statements are parsed. 

Well-crafted & tested contributions are always welcome if you want to go for it.
