### ISSUE TITLE
split with `\\Q` is invalid on databricks

### ISSUE THREAD

**Issue by cpcloud** [tobymao/sqlglot#4158]
![image](https://github.com/user-attachments/assets/25f375b9-019a-4ba6-8f98-a0894540bf58)

**Comment by georgesittas** [comment]
Hi Phillip 👋 
Can you provide some more context on this?

**Comment by cpcloud** [comment]
Sure!

Sorry, I was being a bit lazy 😅 

Here's the sqlglot that produced the query:

```
In [1]: import sqlglot as sg, sqlglot.expressions as sge

In [2]: sg.parse_one("select split(a, '/')", read="duckdb").sql("databricks")
Out[2]: "SELECT SPLIT(a, CONCAT('\\\\Q', '/'))"

In [3]: sg.__version__
Out[3]: '25.22.0'
```

**Comment by georgesittas** [comment]
I see, this conversion is [pretty old](https://github.com/tobymao/sqlglot/commit/c2706ed4d9e64e156b9c4bfb1d29f715d5f3624), so most likely a bug. @VaggelisD could you take a look?

**Comment by cpcloud** [comment]
FWIW this is working as expected with Spark SQL running through PySpark, it's **just** Databricks that exhibits the problem.

**Comment by VaggelisD** [comment]
From a quick search I can't find any context for that transformation, still looking..

@cpcloud Small clarification regarding Spark, do you mean that `CONCAT` is working as expected because it's required for the split pattern or that it's producing the proper results? Would the same `SPLIT(a, '/')` work too?

**Comment by cpcloud** [comment]
> that it's just producing a proper result?

this

> Would the simple SPLIT(a, '/') work too?

Not sure, lemme try.

**Comment by cpcloud** [comment]
`SPLIT(a, '/')` seems to do the job 🎉

**Comment by VaggelisD** [comment]
I think this transformation is more nuanced than expected, and it might be needed in the end. From what I could piece together:

- In [Presto](https://prestodb.io/docs/current/functions/string.html#split), `SPLIT` is done on a delimiter / string literal
- In [Databricks](https://docs.databricks.com/en/sql/language-manual/functions/split.html), `SPLIT` is done on a regex

So to transpile from a literal-based split (`exp.Split`) to a regex-based split (`exp.RegexpSplit`) we must make sure that the string is not treated as a pattern. Afaict, one way to achieve this is by enclosing it in `\Q \E`, as is [showcased here](https://stackoverflow.com/questions/30776860/regular-expression-q-e).

I also tried a few queries on Databricks, this pattern didn't seem to bother execution:

```
SELECT SPLIT('ab/c', CONCAT('\\Q', '/'));

split(ab/c, concat(\Q, /), -1)
["ab","c"]
```

And 

```
SELECT SPLIT('ab/c', '\\Q/');

split(ab/c, \Q/, -1)
["ab","c"]
```

Do you have more context on why this breaks at your end?

Side note: If that's the case, I'm not sure why `\E` is not added by SQLGlot and not required (?) in Databricks, maybe it's optional or `\Q` on it's own is a no-op.

**Comment by cpcloud** [comment]
Note the `\\\\Q`

**Comment by georgesittas** [comment]
Yep, I can verify that this indeed works in databricks, sot sure if there's an issue here.

**Comment by cpcloud** [comment]
When I run this with a column and not a literal, then things start to fail.

**Comment by georgesittas** [comment]
Can't repro this using a CTE:

<img width="360" alt="Screenshot 2024-09-25 at 7 46 37 PM" src="https://github.com/user-attachments/assets/8471c01a-7117-47bd-a4f7-7ccf5a1f89c9">

**Comment by cpcloud** [comment]
This fails for me

```sql
CREATE OR REPLACE TABLE x AS SELECT '11/10/01' as date_string_col;

SELECT SPLIT(date_string_col, CONCAT('\\Q', '/'))
FROM x;
```

**Comment by cpcloud** [comment]
If I inline the value, it works. No clue what's going on.

![image](https://github.com/user-attachments/assets/c1f694cc-1548-4e3e-a7d3-74765430b4a2)

**Comment by georgesittas** [comment]
Yep, this does look weird. I wonder if it's a databricks bug?

**Comment by cpcloud** [comment]
Slapping `'\\E'` on the end "fixes" it.

![image](https://github.com/user-attachments/assets/4afcfb81-208d-481e-b61f-c41cddeb4b5c)

**Comment by georgesittas** [comment]
Yep, I can repro this after all:

```
-- CREATE OR REPLACE TABLE george.default.x AS SELECT '11/10/01' as date_string_col;

-- The given pattern is invalid for SPLIT.
SELECT SPLIT(date_string_col, CONCAT('\\Q', '/')) FROM george.default.x;
```

**Comment by VaggelisD** [comment]
I think adding `\\\\E` to the `CONCAT` transformation then makes sense, both to satisfy the regex specs and to fix this edge case
