### ISSUE TITLE
Databricks DDL parsing fails if there is schema binding specified

### ISSUE THREAD

**Issue by turntable-justin** [tobymao/sqlglot#4160]
**Before you file an issue** ✅ 
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

# works
```
from sqlglot import parse
sql = "CREATE view x (a, b) as (select * from y)"
parse(sql, dialect="databricks")
```

# fails

```
from sqlglot import parse
sql = "create view x (a, b) WITH SCHEMA BINDING as (with a as b select * from y)"
parse(sql, dialect="databricks")
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

[Databricks ddl syntax](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-view.html)

Per link above, the four main keywords for this are: `WITH SCHEMA BINDING`, `WITH SCHEMA COMPENSATION`, `WITH SCHEMA TYPE EVOLUTION`, `WITH SCHEMA EVOLUTION`

**Comment by VaggelisD** [comment]
Hey,

As a heads up, it shouldn't be the `SCHEMA` options that fail, their support was introduced here https://github.com/tobymao/sqlglot/pull/3739. 

As far as I can tell, it's the `WITH a AS b ...` syntax that's not properly parsed, will take a look.

**Comment by VaggelisD** [comment]
@turntable-justin Have you verified if the subquery works? More specifically, the `with a as b` part.

It seems like Databricks is not able to parse that either:

```
create or replace view db.default.test (a, b) WITH SCHEMA BINDING as (with a as b select 1, 2);

[PARSE_SYNTAX_ERROR] Syntax error at or near 'b'. SQLSTATE: 42601 line 2, pos 86
```

**Comment by turntable-justin** [comment]
sorry I miswrote the example. Try this:

```
from sqlglot import parse
sql = "create view x (a, b) WITH SCHEMA BINDING as (select * from y)"
parse(sql, dialect="databricks")
```

I have verified this on a real databricks query yes. Just trying to create a reproducible example and made a typo.

**Comment by VaggelisD** [comment]
What SQLGlot version are you on? I can't reproduce this on the latest:

```
>>> parse_one("CREATE VIEW x (a, b) WITH SCHEMA BINDING AS (SELECT * FROM y)", read="databricks")
Create(
  this=Schema(
    this=Table(
      this=Identifier(this=x, quoted=False)),
    expressions=[
      Identifier(this=a, quoted=False),
      Identifier(this=b, quoted=False)]),
  kind=VIEW,
  expression=Subquery(
    this=Select(
      expressions=[
        Star()],
      from=From(
        this=Table(
          this=Identifier(this=y, quoted=False))))),
  properties=Properties(
    expressions=[
      WithSchemaBindingProperty(
        this=Var(this=BINDING))]))

>>> parse_one("CREATE VIEW x (a, b) WITH SCHEMA BINDING AS (SELECT * FROM y)", read="databricks").sql("databricks")
'CREATE VIEW x (a, b) WITH SCHEMA BINDING AS (SELECT * FROM y)'
```
