### ISSUE TITLE
Getting WARNING when parsing Postgres CREATE TYPE sql queries

### ISSUE THREAD

**Issue by tushar-amrit-6** [tobymao/sqlglot#4166]
When trying to run simple test of parsing sql queries containing Type keyword returns `WARNING  sqlglot:parser.py:1449 'CREATE TYPE compfoo AS (f1 int, f2 text)' contains unsupported syntax. Falling back to parsing as a 'Command'.` Is the CREATE Type queries not supported by sqlGlot the same way like CREATE Tables or CREATE Functions queries?
**Fully reproducible code snippet**
`def test_types():
    sql = """
        CREATE TYPE compfoo AS (f1 int, f2 text);
    """
    query = sqlglot.parse(sql, read="postgres")
    print(query)`

**Comment by georgesittas** [comment]
That's right, `CREATE TYPE` is not "supported" today; SQLGlot simply stores it as a string within the `Command` node so that it doesn't crash. Not a high priority for us, but happy to accept well-tested PRs if you want to take a stab at it.
