### ISSUE TITLE
incorrect transpilation of unnest for redshift

### ISSUE THREAD

**Issue by bjabes** [tobymao/sqlglot#4169]
running:
`sqlglot.transpile("select unnest({\"a\": 123}) as x;", read="duckdb", write="redshift")[0]`

actual:
`'SELECT UNNEST(STRUCT(123 AS a)) AS x'`
however redshift doesn't support unnest. there is no perfect equivalent in redshift so i'm curious if this is a situation where sqlglot should do the full surgery into multiple stages of queries or just throw its hands up.

the equivalent output to tsql does the right thing.
` sqlglot.transpile("select unnest({\"a\": 123}) as x;", read="duckdb", write="tsql")[0]`
returns:
`'SELECT EXPLODE(STRUCT(123 AS a)) AS x'`

**Comment by georgesittas** [comment]
I think the highest ROI for now is to use `self.unsupported` if `UNNEST` is being used as a projection or something, @VaggelisD could you take a look?

@bjabes how complicated would it be to convert the DuckDB query into an equivalent Redshift one?

**Comment by bjabes** [comment]
Yeah this isn't blocking anything on my side, it was an exploration for now!

**Comment by bjabes** [comment]
if your question is "what is the equivalent of this in redshift" – i'll form the best version for you i can. it's going to be not perfectly the same.

oh and i'm not sure that struct syntax is appropriate for redshift either

**Comment by bjabes** [comment]
ok i think there's 2 issues here. first is that json literals should probably be converted into `json_parse('<literal>')` and the second is converting unnest. i'll create the other issue unless you prefer to keep it all together here.

**Comment by tobymao** [comment]
let's keep this here, but we may not address this because it's not super high priority for us

**Comment by bjabes** [comment]
i nerded out on this some more. it's basically a nightmare to clone "unnest" in redshift (requires a stored proc because no dynamic sql possible). i would mark that as `unsupported` in redshift.

i _would_ fix the json -> struct to convert a json literal to `json_parse('<literal>')`

**Comment by VaggelisD** [comment]
Hey @bjabes, really appreciate the analysis, I'll add the unsupported warning to `UNNEST`.

Regarding the JSON literals, do you mind providing more context and possibly some examples? From what I understood at first, in DuckDB we e.g. extract values from string literals but in Redshift they have to be wrapped in `JSON_PARSE(...)`, is that an JSON -> STRUCT operation somehow?

**Comment by bjabes** [comment]
redshift doesn't support STRUCT. it does have a SUPER data type for semi-structured data. when you write `JSON_PARSE(...)` it creates a SUPER instance

**Comment by VaggelisD** [comment]
That makes sense, thanks. From what I understand, Redshift has 2 modes:
1. [Text-based JSON functions](https://docs.aws.amazon.com/redshift/latest/dg/text-json-functions.html), which operate on string literals
2. [SUPER-based functions/operators](https://docs.aws.amazon.com/redshift/latest/dg/query-super.html), which require `JSON_PARSE(...)` to be applied first

The main advantage of (2) is mostly the processing speed, right? SQLGlot uses (1) which is simpler to transpile between other dialects, so to shift to (2) it'd require a non trivial refactor, to name a couple points:
- We'd have to group up all JSON expressions and wrap their string literal operands with `JSON_PARSE(...)`; Sometimes this is not detectable as these literals could be "hidden" behind column names
- We'd have to replace all existing transpilations/roundtrips to the (2) mode, e.g. `exp.JSONExtract` would not generate `JSON_EXTRACT_PATH_TEXT(...)` anymore but the dot/bracket notation

If there's not a compelling reason to switch to (2) I'd personally let it be for now, will let others chime in as well.

Of course we will be happy to accept well-crafted & tested PRs if you want to add it.
