### ISSUE TITLE
[Oracle] ParseError when using DBLINK with case-sensitive identifiers

### ISSUE THREAD

**Issue by Pizzi95** [tobymao/sqlglot#4177]
When attempting to parse an Oracle SQL query that includes a DBLINK with a case-sensitive identifier (using double quotes), a ParseError is encountered. 

**Fully reproducible code snippet**
```
sql_query = """select 1 from "table"@hq.acme.com"""
parse_one(sql_query, read='oracle')
```

**Error**
```
ParseError: Invalid expression / Unexpected token. Line 1, Col: 25.
  select 1 from "table"@hq.acme.com
```

**Official Documentation**

- [Database Object Naming Rules](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Database-Object-Names-and-Qualifiers.html#GUID-75337742-67FD-4EC0-985F-741C93D918DA)
- [Create dblink](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-DATABASE-LINK.html)

**Comment by tobymao** [comment]
low priority issue for us, feel free to make a pr
