### ISSUE TITLE
Oracle specific BULK COLLECT INTO token not supported

### ISSUE THREAD

**Issue by mkmoisen** [tobymao/sqlglot#4180]
The Oracle specific `BULK COLLECT INTO` syntax is not supported.

Would it be possible to add this token?

This is for all intents and purposes essentially the same as the `INTO` token when it comes to parsing.

```
import sqlglot

parsed = sqlglot.parse_one(
    '''
        SELECT foo, bar
        BULK COLLECT INTO l_rows
        FROM baz
    ''', 
    dialect='oracle'
)
```

Results in:

    sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 3, Col: 13.
    
The INTO token works fine:

```
import sqlglot

parsed = sqlglot.parse_one(
    '''
        SELECT foo
        INTO l_foo
        FROM baz
    ''', 
    dialect='oracle'
)
```

**Comment by tobymao** [comment]
low priority, feel free to make a PR if you'd like to see this, we're happy to review

**Comment by mkmoisen** [comment]
@tobymao I've raise a pull request here, please take a look when you have a moment:

https://github.com/tobymao/sqlglot/pull/4181
