### ISSUE TITLE
 Incorrect `SHA` Function Mapping for DuckDB Dialect in SQLGlot

### ISSUE THREAD

**Issue by rustyconover** [tobymao/sqlglot#4185]
When testing SQLGlot with DuckDB, the `SHA` function is incorrectly translated. The expected function name in DuckDB is `SHA1`, but it gets mapped to `SHA` instead.

#### Original Query:

```sql
SELECT sha1(?::VARCHAR) LIMIT 1
```

#### SQLGlot Output (DuckDB Dialect):

```sql
SELECT SHA(CAST(? AS TEXT)) LIMIT 1
```

#### Expected Behavior:
The function should be translated as `SHA1` in DuckDB, matching the original query.

**Comment by georgesittas** [comment]
Fixed by #4191 -- thanks!
