### ISSUE TITLE
Incorrect handling of the `~~` operator in DuckDB

### ISSUE THREAD

**Issue by rustyconover** [tobymao/sqlglot#4188]
When testing SQLGlot with DuckDB, the `~~` operator is incorrectly handled. This operator, which functions similarly to the SQL `LIKE` pattern matching, is being translated into an invalid SQL expression.

#### Original Query:

```sql
SELECT ?::VARCHAR ~~ ?::VARCHAR LIMIT 1
```

#### SQLGlot Output:

```sql
SELECT REGEXP_MATCHES(CAST(? AS TEXT), ~CAST(? AS TEXT)) LIMIT 1
```

#### Expected Behavior:
SQLGlot should retain the `~~` operator for pattern matching in DuckDB, as it is equivalent to `LIKE`. The correct output should be:

```sql
SELECT ?::VARCHAR ~~ ?::VARCHAR LIMIT 1
```

**Comment by georgesittas** [comment]
Appreciate the reports @rustyconover, PRs are also welcome if you wanna take a stab at them. Just let us know so we don't do overlapping work.
