### ISSUE TITLE
DuckDB `!~~`, `!~~*`, `&&`, `**`, `<@`, `@>`,  `^@` operators are not parsed

### ISSUE THREAD

**Issue by rustyconover** [tobymao/sqlglot#4189]
When using SQLGlot's DuckDB dialect, it fails to parse several valid SQL statements containing operators that are supported by DuckDB. The issue appears to stem from SQLGlot not recognizing these operators.

#### Example Queries (Valid in DuckDB but Failing in SQLGlot):

```sql
SELECT ?::VARCHAR !~~ ?::VARCHAR LIMIT 1
SELECT ?::VARCHAR !~~* ?::VARCHAR LIMIT 1
SELECT ?::VARCHAR[] && ?::VARCHAR[] LIMIT 1
SELECT ?::DOUBLE ** ?::DOUBLE LIMIT 1
SELECT ?::VARCHAR[] <@ ?::VARCHAR[] LIMIT 1
SELECT ?::VARCHAR ^@ ?::VARCHAR LIMIT 1
```

#### Issue:
SQLGlot does not recognize these operators, which results in a parsing failure when using the DuckDB dialect

#### DuckDB Function Definitions:
The operators are defined as follows in DuckDB:

```sql
SELECT function_name, description 
FROM duckdb_functions() 
WHERE function_name IN ('!~~', '!~~*', '&&', '**', '<@', '@>',  '^@');
```

| Function Name | Description                                                                 |
|---------------|-----------------------------------------------------------------------------|
| !~~           |                                                                             |
| !~~*          |                                                                             |
| &&            | Returns true if the lists have any element in common. NULLs are ignored.    |
| **            | Computes x to the power of y                                                |
| <@            | Returns true if all elements of l2 are in l1. NULLs are ignored.            |
| @>            | Returns true if all elements of l2 are in l1. NULLs are ignored.            |
| ^@            | Returns true if string begins with search_string                            |

**Comment by VaggelisD** [comment]
Hey @rustyconover,

Thanks once again for these issues, they really help increase coverage. You mentioned that these tests were done automatically, do you think these specific operators are widely used? I personally haven't come across these before, and the first two do not seem documented with a description yet.

The pain point is that each of these will probably require a new token, a new AST node, their precedence level figured out etc so if they're not particularly famous and/or properly documented, I'd be inclined to close this as not planned.

It will really help if we can map these to an existing DuckDB function, which will remove most of the burden as with the other operators.

**Comment by VaggelisD** [comment]
Thanks for your kind words, they truly mean a lot! Well written issues help with the prompt replies.

Indeed, most of these operators come from Postgres and we already support a few of them so their DuckDB extension will not take long; I'll hopefully have them all supported by tomorrow.
