### ISSUE TITLE
Incorrect StrPosition Code Generation for SQLite

### ISSUE THREAD

**Issue by pruzko** [tobymao/sqlglot#4196]
Hi,

Sqlglot parses string position functions into `exp.StrPosition` expressions that can be compiled to target dialects via `sql()`. I believe that both parsing and generation does not work for SQLite. The code assumes SQLite's string position function is `STR_POSITION(...)`, but in reality it is `INSTR(...)`. Is this the expected behavior?

MVE:
```python
import sqlglot

x = parse_one("select instr('asd', 's')", read='sqlite')
print(repr(x)) # parsed as Anonymous

x = parse_one("select str_position('asd', 's')", read='sqlite')
print(repr(x)) # parsed as StrPosition

x = parse_one("select instr('asd', 's')", read='mysql')
print(repr(x)) # parsed as StrPosition

print(x.sql(dialect='sqlite')) # compiled as STR_POSITION
```

Fix:
Adding `INSTR` to SQLite's [function list](https://github.com/tobymao/sqlglot/blob/9eba00dca517efe7df171b09ed916af3ea5e350d/sqlglot/dialects/sqlite.py#L113) just like it is done for [MySQL](https://github.com/tobymao/sqlglot/blob/9eba00dca517efe7df171b09ed916af3ea5e350d/sqlglot/dialects/mysql.py#L303C14-L303C19) should do the trick.

**Comment by georgesittas** [comment]
This transpilation path hasn't been covered yet, so I'd say it's "expected" as in "missing functionality". We welcome PRs if you wanna take a stab at it. Your suggestion makes sense 👍

**Comment by pruzko** [comment]
I made a [PR](https://github.com/tobymao/sqlglot/pull/4198).

Also, I'm new to the library and it's absolutely amazing.
