### ISSUE TITLE
sqlglot.diff False positive warning "Locking reads using 'FOR UPDATE/SHARE' are not supported"

### ISSUE THREAD

**Issue by mkmoisen** [tobymao/sqlglot#4203]
```
import sqlglot

parsed = sqlglot.parse_one(
    '''
        SELECT foo
        FROM bar
        FOR UPDATE
    ''',
    dialect='oracle'
)

parsed2 = parsed.copy()

sqlglot.diff(parsed, parsed2)
```

This emits the following warning, which is a false positive in my case.

    Locking reads using 'FOR UPDATE/SHARE' are not supported

The root cause of this is that the `ChangeDistiller` uses a default `Dialect`:

    `self._sql_generator = Dialect().generator()

I'm not sure what a good solution to this issue is.

sqlglot.diff could take in a `dialect` parameter, which could be used to to set the `_sql_generator`. This is fine in my case because I am only diffing two parsed statements from Oracle. But this won't help solve the case where you are diffing two statements from different databases.

**Comment by georgesittas** [comment]
Thanks for the report, we'll look into this soon.
