### ISSUE TITLE
Add support for TSQL stored procedure options

### ISSUE THREAD

**Issue by rsanchez-xtillion** [tobymao/sqlglot#4204]
SQLGlot currently does not have support for parsing TSQL stored procedure options like:
```
CREATE PROCEDURE dbo.usp_add_kitchen @dept_id INT, @kitchen_count INT NOT NULL
WITH EXECUTE AS OWNER, SCHEMABINDING, NATIVE_COMPILATION # <- This right here
AS
BEGIN...
```

I already made a fork and have made some progress adding support in my own branch. Is there anyone else working on this or should I make a PR?

**Comment by georgesittas** [comment]
We're not working on this and it's relatively low priority for the core team, so I'm closing this for now. We'll be happy to help you get a PR in.
