### ISSUE TITLE
foo IS NOT NULL becomes NOT FOO IS NULL

### ISSUE THREAD

**Issue by mkmoisen** [tobymao/sqlglot#4209]
```
import sqlglot

parsed = sqlglot.parse_one('''
    select a
    from b
    where c is not null
''', dialect='mysql')

print(parsed.sql(dialect='mysql', pretty=True))
```

This outputs:

```
SELECT
  a
FROM b
WHERE
  NOT c IS NULL
```

Is this the expected behavior? I would have thought that `c IS NOT NULL` is the preferred output.

If you agree, I think the following change would work:

    def not_sql(self, expression: exp.Not) -> str:
        if isinstance(expression.this, exp.Is) and isinstance(expression.this.expression, exp.Null):
            return f"{self.sql(expression.this.this)} IS NOT NULL"
        return f"NOT {self.sql(expression, 'this')}"

**Comment by georgesittas** [comment]
Yep, this is expected behavior. See https://github.com/tobymao/sqlglot/discussions/274 for additional context.
