### ISSUE TITLE
De-Qualification

### ISSUE THREAD

**Issue by bkleck** [tobymao/sqlglot#4210]
Hi developers,

I have utilized the optimizer.optimize function on my SQL code. I understand that the first step is to qualify all columns and tables such that the other optimization techniques can be utilized. 

The optimization works great, however the resulting code output is a little difficult to read with the human eye due to the numerous qualifying prefixes before each table and column. Is there any function for me to **de-qualify** the output for readability?

Thanks in advance!

**Comment by tobymao** [comment]
there isn't but you can write your own transformation that does this, but it could be tricky when things are ambiguous

**Comment by bkleck** [comment]
@tobymao any reference that i could follow?

**Comment by tobymao** [comment]
check out the transformations in the optimizer or transforms.py
