### ISSUE TITLE
Postgres prepared statement parameter token $ is overwritten to @

### ISSUE THREAD

**Issue by bjstarosta** [tobymao/sqlglot#4215]
Hello,

I recently found this project and have been testing it, it is exactly what I've been looking for for purposes of SQL query analysis and editing. My use case involves postgres prepared statements which means setting up queries of the form:

```sql
SELECT x, y, z FROM table_name WHERE x = $1
```

where `$1` is the prepared statement param as outlined [here](https://www.postgresql.org/docs/current/sql-prepare.html).

My test code:
```py
from sqlglot import condition, select
from sqlglot.optimizer import optimize

sql = select('x', 'y', 'z')
sql = sql.from_('table_name')
sql = sql.where(condition('x = $1', dialect='postgres'))
print(sql.sql())
# result: SELECT x, y, z FROM table_name WHERE x = @1
# parameter is changed to @ token
print(sql.sql(dialect='postgres'))
# result: SELECT x, y, z FROM table_name WHERE x = $1
# parameter stays the same as expected
print(optimize(sql, dialect='postgres'))
# result: SELECT "table_name"."x" AS "x", "table_name"."y" AS "y", "table_name"."z" AS "z" FROM "table_name" AS "table_name"
# WHERE "table_name"."x" = @1
# parameter is changed to @ token
print(optimize(sql.sql(dialect='postgres'), dialect='postgres'))
# same result as above
```
The first print statement delivers a bad result, but that's fine - I just need to specify the dialect. However, the `optimize()` call always changes the parameter token to the incorrect result.

If I remove the `dialect='postgres'` parameter from the condition object, it gets weirder:
```py
from sqlglot import condition, select
from sqlglot.optimizer import optimize

sql = select('x', 'y', 'z')
sql = sql.from_('table_name')
sql = sql.where(condition('x = $1'))
print(sql.sql())
# result: SELECT x, y, z FROM table_name WHERE x = $1
print(sql.sql(dialect='postgres'))
# result: SELECT x, y, z FROM table_name WHERE x = $1
print(optimize(sql, dialect='postgres'))
# result: SELECT "table_name"."x" AS "x", "table_name"."y" AS "y", "table_name"."z" AS "z" FROM "table_name" AS "table_name"
# WHERE "table_name"."$1" = "table_name"."x"
```
The first two queries deliver the correct result, but I imagine for incorrect reasons. The `optimize()` call delivers an unexpected result.

I have ran the queries through the tokeniser, and in the "correct" case (`$` token is not changed) it seems to simply not be able to recognise the token, showing it as `TokenType.VAR`. When the token is changed to `@`, the tokeniser reports it as `TokenType.PARAMETER` followed by `TokenType.NUMBER`.

Is this an issue with the dialect definition, or am I doing something wrong here? Thanks in advance.

**Comment by VaggelisD** [comment]
Hey @bjstarosta, glad to hear that you like SQLGlot!

You need to specify the dialect wherever possible; This is because each component (tokenizer, parser, optimizer etc) needs it to understand the surrounding context e.g. `$` being the symbol of a parameter.

For example, this is the AST node of the `WHERE` builder you used without dialect:

```SQL
sql.where(condition('x = $1'))

where=Where(
    this=EQ(
      this=Column(
        this=Identifier(this=x, quoted=False)),
      expression=Column(
        this=Identifier(this=$1, quoted=False)))))
```

And this is with the dialect specified:

```SQL
sql.where(condition('x = $1', dialect="postgres"))

  where=Where(
    this=EQ(
      this=Column(
        this=Identifier(this=x, quoted=False)),
      expression=Parameter(
        this=Literal(this=1, is_string=False)))))
```

Note the difference between `exp.Column` and `exp.Parameter` for `$1`. The same goes for the optimizer and the generator (i.e the `.sql(...)` call), where the dialect fixes the result:

```
...
sql.where(condition('x = $1', dialect="postgres"))
print(optimize(sql, dialect="postgres").sql(dialect="postgres"))


SELECT "table_name"."x" AS "x", "table_name"."y" AS "y", "table_name"."z" AS "z" FROM "table_name" AS "table_name" WHERE "table_name"."x" = $1
```

Note that the `optimize(...)` call produces an _optimized AST_, but to _generate_ the query back from an AST we must do through `.sql(...)`. If only a `print(...)` is used, the AST will be generated back in the "base" (or SQLGlot) dialect.

**Comment by bjstarosta** [comment]
Thanks for the in-depth explanation, I suppose my source of confusion was whether the dialect had to be explicitly specified on each method call, or whether the objects actually held it as a state after definition. In retrospect I could've simply looked at the source to find out. I amended my test code, and it does indeed deliver the expected result when dialect is explicitly set on each call that takes it as a parameter.

Thanks again!

As an aside: I thought about this problem for a bit, and it might be interesting for a future release to allow users to use the Dialect object as a proxy for the SQL expression objects, to be able to explicitly pass state when constructing a full query in this case.

Example API:

```py
from sqlglot.dialects import Postgres

dialect = Postgres()
sql = dialect.select('x', 'y', 'z')
sql = sql.from_('table_name')  # state is passed in 'sql', so this again assumes dialect='postgres' is set
sql = sql.where(dialect.condition('x = $1'))  # condition is a separate object, so it must be taken from 'dialect' again
print(sql.sql())  # again assumes dialect='postgres' is set
```
