### ISSUE TITLE
Dropping and reordering comments when using CTEs

### ISSUE THREAD

**Issue by ajfriend** [tobymao/sqlglot#4216]
I think I've found some corner cases where:

1. Comments are dropped
2. Comments before the final select statement after a sequence of CTEs gets moved to the top of the query
3. Some of the comments are reproduced out of order

## Example

Here's an example:

```python
import sqlglot
def foo(s):
    print(sqlglot.transpile(s, read='presto', write='spark', pretty=True)[0])

s1 = """
-- comment at the top
with
-- comment for tbl1
tbl1 as (select 1)

-- comment for tbl2
, tb12 as (select 2)

-- comment for tbl3
, tb13 as (select 3)

-- comment for final select
select * from tbl1
"""
foo(s1)
```

gives me the output:

```sql
/* comment for final select */
/* comment at the top */
WITH tbl1 /* comment for tbl1 */ AS (
  SELECT
    1
), tb12 AS (
  SELECT
    2
), tb13 AS (
  SELECT
    3
)
SELECT
  *
FROM tbl1
```

## Expected behavior

1. Preserve comments for `tbl2` and `tbl3` (they are missing in the example above)
2. If possible, keep the comment for the final select closer to where it was in the original query
4. Even if it can't be kept closer, the comments are out of order, as the "comment at the top" should be first.

## Alternative inputs

I played with the example a bit, and it seems that the dropped comments have to do with the comma placement. I can preserve the comments if I do something like the example below, but, ideally, they would also be preserved in the example above. With the example below, we still have the issue of the comment at the top and the final select comment showing up out of order, and the final select comment being moved to the top of the output (rather than near the final select statement).

```python
s2 = """
-- comment at the top
with
-- comment for tbl1
tbl1 as (select 1),

-- comment for tbl2
tb12 as (select 2),

-- comment for tbl3
tb13 as (select 3)

-- comment for final select
select * from tbl1
"""
foo(s2)
```

gives the output:

```sql
/* comment for final select */
/* comment at the top */
WITH tbl1 /* comment for tbl1 */ AS (
  SELECT
    1
), tb12 /* comment for tbl2 */ AS (
  SELECT
    2
), tb13 /* comment for tbl3 */ AS (
  SELECT
    3
)
SELECT
  *
FROM tbl1
```

## Version

This behavior is happening on the main branch. I ran the example using `sqlglot.__version__='25.24.5.dev2'`

**Comment by VaggelisD** [comment]
Hey @ajfriend, thanks for reporting this. 

Note that preserving the comments exactly as they come is not always possible, our attempts are on a best-effort basis as is documented [here](https://github.com/tobymao/sqlglot?tab=readme-ov-file#examples). 

The issue you describe regarding the comma placement is precisely what happens; The comments are attached to nearby AST nodes but commas are not added to the AST, so it might be that their surrounding comments are either dropped or attached to other nodes (thus, appearing out of order in the result query).
