### ISSUE TITLE
[Postgres 14.4] Parser does not understand inline join in from clause

### ISSUE THREAD

**Issue by g-u-t-h-m-a-n** [tobymao/sqlglot#423]
Example (valid sql):

```
select * from (table1 left join table2 on 1 = 1);
```
Result:
```
ParseError: Expecting ). Line 1, Col: 23.
  select * from (table1 left join table2 on 1 = 1);

Invalid expression / Unexpected token. Line 1, Col: 48.
  select * from (table1 left join table2 on 1 = 1);
```

**Comment by barakalon** [comment]
Is this syntax documented anywhere? I don't see it [here](https://www.postgresql.org/docs/current/sql-select.html).

**Comment by alippai** [comment]
I believe it's called a "join construct"

**Comment by alippai** [comment]
https://www.postgresql.org/docs/current/queries-table-expressions.html joined tables

**Comment by GeorgeSittas** [comment]
MySQL join clause syntax can also derive this form: https://dev.mysql.com/doc/refman/8.0/en/join.html
