### ISSUE TITLE
clickhouse `Bool` type name is changed to `BOOLEAN`

### ISSUE THREAD

**Issue by obazna** [tobymao/sqlglot#4230]
```python
import sqlglot
from sqlglot.expressions import ColumnDef, DataType

exp = sqlglot.parse_one('Bool', read="clickhouse", into=DataType)

print(exp.sql(dialect="clickhouse"))
```

Actual output: `BOOLEAN`
Expected output: `Bool`

**Comment by georgesittas** [comment]
`BOOLEAN` is an alias to `Bool`, so this should be fine ([docs)](https://clickhouse.com/docs/en/sql-reference/data-types))

<img width="1508" alt="Screenshot 2024-10-09 at 3 40 18 PM" src="https://github.com/user-attachments/assets/c5c9268e-9dd5-4e53-9dec-4b8b105053ea">

**Comment by obazna** [comment]
@georgesittas Yes it will work, but I'm in doubt it's fine. Behavior is not consistent.

if you specify alias `BIGINT` it will be converted to Clickhouse type `Int64`.
But if you specify `BOOLEAN` it's not converted to CH type name `Bool`. Moreover for some reasons we do completely opposite converting `Bool` to the alias `BOOLEAN`.

It creates a lot of inconsistency. For example, if you create a table with `BOOLEAN` and then run `DESC your_table_name` in Clickhouse, it will return `Bool`, not `BOOLEAN`.

**Comment by georgesittas** [comment]
I see, I was under the impression `BIGINT` wasn't supported, so that conversion didn't struck me as weird. I'll fix this mapping, thanks for clarifying.

**Comment by georgesittas** [comment]
Feel free to make PRs for any other similar issues, the fixes are pretty straightforward.

**Comment by georgesittas** [comment]
fixed in https://github.com/tobymao/sqlglot/commit/79caf519987718390a086bee19fdc89f6094496c.
