### ISSUE TITLE
Incorrect recognized ARRAY JOIN (Clickhouse)

### ISSUE THREAD

**Issue by xtess16** [tobymao/sqlglot#4254]
I'm trying to get a list of all the tables
```python
sql = """
    SELECT s, arr FROM arrays_test 
    LEFT ARRAY JOIN arr
"""
expression = parse_one(sql, dialect=Dialects.CLICKHOUSE)
print(list(expression.find_all(exp.Table)))
```
Output:
```python
[Table(
   this=Identifier(this=arrays_test, quoted=False)),
 Table(
   this=Identifier(this=arr, quoted=False))]
   ```
But `arr` is a column name
Docs: https://clickhouse.com/docs/en/sql-reference/statements/select/array-join#basic-array-join-examples

**Comment by georgesittas** [comment]
This isn't possible to disambiguate without a schema. You can try using `qualify` and see if it works, as we already handle some similar cases there.

**Comment by georgesittas** [comment]
Ah, my bad, it seems like ClickHouse constrains
