### ISSUE TITLE
Why does `from_` parameter on `Select` not work, but `from_` method does?

### ISSUE THREAD

**Issue by zjost** [tobymao/sqlglot#4270]
I'm not sure if I misunderstand something, or if there's a bug.  In a nutshell, if I do `exp.Select(from_=from_obj)`, I get unexpected behavior, but if I do `exp.Select().from_(from_obj)`, I get expected behavior.  

**Fully reproducible code snippet**
```python
from sqlglot import exp, diff

# Shared component
values = [exp.Tuple(expressions=[exp.Literal.number(b)]) for b in [1, 2, 3]]
values_exp = exp.Values(
    expressions=values,
    alias=exp.TableAlias(
        this=exp.Identifier(this='t'),
        columns=[exp.Identifier(this='my_col')]
    )
)

# using from_ parameter of constructor
q1 = exp.Select(
    expressions=[exp.Star()],
    from_=exp.From(this=values_exp)
)

# using from_ method
q2 = exp.Select(
    expressions=[exp.Star()],
).from_(exp.From(this=values_exp))
```

If I print the strings of these ASTs, I get:
```
q1 == 'SELECT *'
```

and
```
q2 == 'SELECT * FROM (VALUES (1), (2), (3)) AS t(my_col)'
```

When I print the repr of the ASTs, the only difference I see is `from_=From` and `from=From` (no underscore). 

Is this a bug, or are we not supposed to use the `from_` parameter in `Select`?

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by zjost** [comment]
I'm seeing now that all the examples use `Select().from_`, and the source code shows this method as calling `_apply_builder`, which seems important :).  

An FYI that I got this `Select(from_=...)` from Co-pilot, so maybe this issue will help someone in the future.

**Comment by tobymao** [comment]
because the ast node doesn't have "from_", it has "from". in general you should try not to build ast by hand, or listen blindly to co-pilot :D
