### ISSUE TITLE
Add line number and column to the Expreesion

### ISSUE THREAD

**Issue by GaryLiuGTA** [tobymao/sqlglot#4272]
**Is your feature request related to a problem? Please describe.**

I am current trying to make a SQL linting tool, leveraging the powerful AST generated by sqlglot. Both the AST structure and the utility functions work great for me, the only missing part is when I captured an issue, such as unused CTE, I cannot locate it with line and column number. I noticed that the input tokens have the line/column properties. Wondering if these properties can be carried over Expression? 

**Describe the solution you'd like**

If each Expression object can have line/column properties, that will great. If one expression evolved multiple tokens, it should be the line/column of the first token. 

**Describe alternatives you've considered**

Maybe it can be added in to the `comment` part? 

**Additional context**

Thank you very much to create such a good tool for SQL parsing while accommodate all different dialects!

**Comment by tobymao** [comment]
duplicate. no plans to do this since tokens don’t map to expressions
