### ISSUE TITLE
SqlGlot does not recognize "EXECUTE IMMEDIATE" as a Command

### ISSUE THREAD

**Issue by baruchoxman** [tobymao/sqlglot#4273]
**Fully reproducible code snippet**
>>> x = sqlglot.parse_one("EXECUTE IMMEDIATE DESCRIBE tpch", "trino")
'EXECUTE IMMEDIATE DESCRIBE tpch' contains unsupported syntax. Falling back to parsing as a 'Command'.
>>> x
Command(
  this=EXECUTE,
  expression=Literal(this=IMMEDIATE DESCRIBE tpch, is_string=True))

Ideally, sqlglot shoud recognize the command as "EXECUTE IMMEDIATE" in this case, and not put `IMMEDIATE` as part of the expression.

**Official Documentation**
https://trino.io/docs/current/sql/execute-immediate.html

**Comment by georgesittas** [comment]
This is not a high priority for the core team, feel free to open a PR if you need this.
