### ISSUE TITLE
Lineage information for a create statement seem to be incorrect

### ISSUE THREAD

**Issue by diwu-sf** [tobymao/sqlglot#4289]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```
# snowflake create dynamic table CTAS
sql = '''
CREATE DYNAMIC TABLE product (pre_tax_profit COMMENT 'revenue minus cost',
                taxes COMMENT 'assumes taxes are a fixed percentage of profit',
                after_tax_profit)
  TARGET_LAG = '20 minutes'
    WAREHOUSE = mywh
    AS
      SELECT revenue - cost, (revenue - cost) * tax_rate, (revenue - cost) * (1.0 - tax_rate)
      FROM staging_table;
'''
parsed = sqlglot.parse_one(sql, dialect='snowflake')
qualified = sqlglot.optimizer.qualify.qualify(
        parsed, quote_identifiers=False, dialect='snowflake'
    )
sqlglot_lineage(
        'PRE_TAX_PROFIT', sql=qualified, dialect='snowflake', trim_selects=True
)
```
This will throw error:
```
sqlglot.errors.SqlglotError: Cannot find column 'PRE_TAX_PROFIT' in query
```

If you ask for column name `_COL_0` it will give lineage information.
I think the problem might be in `build_scope()` where the `CREATE` statement is part of a DDL, but not a QUERY, so the scope's `outer_columns` isn't being set correctly.

Ideally, I think the scope should take the `ColumnDef` from the `Create` and rename the anonymous inner `_col_#` with the corresponding column def name

**Official Documentation**
Please include links to official SQL documentation related to your issue.
https://sqlglot.com/sqlglot/lineage.html

**Comment by tobymao** [comment]
lineage is really meant for select queries and not ddl

**Comment by diwu-sf** [comment]
Is the right solution for me to just build my own scope and set the "outer_columns"? Or is there a better way to handle this? 

And is "outer_columns" the right way to pass the names through?
