### ISSUE TITLE
Clickhouse dialect capitalizes proprietary functions

### ISSUE THREAD

**Issue by scottpersinger** [tobymao/sqlglot#429]
I have a little function which attempts to qualify table names in the FROM clause of my statement:

    froms = ["schema1.table1"]
    sqlglot.parse_one(query,` read="clickhouse").from_(froms, append=False).sql()

but when I feed it SQL that uses proprietary Clickhouse functions it capitalizes them, so:

`SELECT arrayElement(cast(Keys as Array(String)),1) as service`

becomes

`SELECT ARRAYELEMENT(CAST(Keys AS ARRAY<TEXT>), 1) AS service`

but `arrayElement` cannot be capitalized, per special Clickhouse rules: https://clickhouse.com/docs/en/sql-reference/syntax/

(Also I'm not sure the array type syntax will work either, but...)

**Comment by tobymao** [comment]
you need to do sql(dialect="clickhouse") to not capitalize the functions

**Comment by scottpersinger** [comment]
oh, awesome! Except even with that the cast part "cast(Keys as Array(String))" still capitalizes the "ARRAY" keyword, which Clickhouse does not seem to like:

`SELECT arrayElement(CAST(Keys AS ARRAY(TEXT)), 1) AS service`

`DB::Exception: Unknown data type family: ARRAY. Maybe you meant: ['Array']`
