### ISSUE TITLE
Incorrect Error for Ambiguous Column

### ISSUE THREAD

**Issue by kidanekal** [tobymao/sqlglot#4296]
When parsing an SQL statement with an ambiguous column, sqlglot throws an incorrect error. Instead of identifying the column as ambiguous, the error message states: `Column '"a"' could not be resolved`.  

 To repro the issue, use the following statement.

```
>>> import sqlglot
>>> from sqlglot.optimizer.qualify import qualify
>>> 
>>> qualify(sqlglot.parse_one(''' 
...    select a
...      from (select 1 AS "a", 1 AS t1) t1
...    JOIN
...     (select 1 as a, 1 as t2) t2 ON t1.t1=t2.t2''')).sql()
```
**Result**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sqlglot/optimizer/qualify.py", line 102, in qualify
    validate_qualify_columns_func(expression)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sqlglot/optimizer/qualify_columns.py", line 108, in validate_qualify_columns
    raise OptimizeError(f"Column '{column}' could not be resolved{for_table}")
sqlglot.errors.OptimizeError: Column '"a"' could not be resolved
```
**Expected**

`Ambiguous column` [exception](https://github.com/tobymao/sqlglot/blob/main/sqlglot/optimizer/qualify_columns.py#L120) should be thrown. An Ambiguous column error would better inform users of the actual issue.

**Comment by VaggelisD** [comment]
Hey @kidanekal, thanks for reporting this.

What you're saying makes sense; However, the validation step (`validate_qualify_columns`) happens at the end of the qualification logic, so the context/state that would allow us to distinguish between unresolved vs ambiguous at that particular scope is lost.

Will close this for now as making this accurate would require either keeping that state alive (refactor) or rebuilding it during validation (additional overhead).
