### ISSUE TITLE
Bug with JSONB_EXIST function translation from Postgresql to DuckDB

### ISSUE THREAD

**Issue by dor-bernstein** [tobymao/sqlglot#4299]
**Fully reproducible code snippet**
```python
from sqlglot import parse_one
query = "SELECT JSONB_EXISTS(col, path) from table"
parse_one(query, dialect='postgres').sql(dialect='duckdb')
``` 
the output is: 'SELECT JSONB_EXISTS(col, path) FROM "table"'
while the expected output is: 'SELECT JSON_EXISTS(col, path) FROM "table"'

**Official Documentation**
1. DuckDB json docs: https://duckdb.org/docs/data/json/json_functions
2. Postgres Docs: https://www.postgresql.org/docs/current/functions-json.html. JSONB_EXISTS is mapped to the question mark operator

Thanks!

**Comment by VaggelisD** [comment]
Hey @dor-bernstein,

Did you mean to write `JSONB_PATH_EXISTS`? I couldn't find `JSONB_EXISTS` in the Postgres docs.

**Comment by dor-bernstein** [comment]
@VaggelisD nope, meant JSONB_EXISTS is equal to the ? operator. https://stackoverflow.com/questions/43862936/postgresql-where-in-jsonb
