### ISSUE TITLE
Implement view resolution 

### ISSUE THREAD

**Issue by erfanium** [tobymao/sqlglot#4308]
I'm looking for an sql transpiler tool that implements view resolution logic. I want to be able to create custom isolated sql interfaces.

example code:
```py
input_query = "SELECT * FROM my_view WHERE my_view.id = 1"

views = {
  "my_view": "SELECT * FROM items WHERE items.tenant_id = '1234' "
}

final_query = resolve_views(input_query, view)

print(final_query); // output: SELECT * FROM items WHERE  items.tenant_id = '1234' and  items.id = 1
```

can i do it using this library? or if no, is there any alternatives? thanks!

**Comment by georgesittas** [comment]
you can do it with sqlglot, look into https://github.com/tobymao/sqlglot/blob/main/sqlglot/expressions.py#L8145-L8182

**Comment by georgesittas** [comment]
Ah, nvm, I misread your question. This is a different thing. Not sure if this resolution is possible with the existing tools, you may have to implement some logic manually for this.
