### ISSUE TITLE
Add support for MonetDB

### ISSUE THREAD

**Issue by simonaubertbd** [tobymao/sqlglot#4314]
**Is your feature request related to a problem? Please describe.**
MonetDB is a very light, fast, open-source database available here :
https://www.monetdb.org/

Really enjoy it, works pretty well with Tableau and it's a good introduction to column-store concepts and analytics with SQL.

It has also gained a lot of popularity these last years :
https://db-engines.com/en/ranking_trend/system/MonetDB

-it's free
-it's open-source
-it's fast
-it's easy to install on linux, mac and windows.
-it cares about SQL norm

The only thing it lacks is the support by other tools.

**Describe the solution you'd like**
I would like to have the support for MonetDB dialect.

**Describe alternatives you've considered**
N/A

**Additional context**
sqlglot is now a successful package, used by a lot of product so a new dialect would open great perspectives for MonetDB

Best regards,

Simon

**Comment by georgesittas** [comment]
Hey, thanks for raising the issue.
This is low priority for the core team, but we'll consider accepting a well-crafted, tested & documented PR.
