### ISSUE TITLE
Issue with CURRENT_TIME in Trino dialect

### ISSUE THREAD

**Issue by npochhi** [tobymao/sqlglot#4342]
If we have a Trino SQL such as -

```
SELECT CURRENT_TIME
            FROM table_a "tbl1_1"
```
when we parse it and convert it back to SQL, the SQL being returned is (instead of the original one) -

```
SELECT CURRENT_TIME() FROM table_a AS "tbl1_1"
```
The documentation for `CURRENT_TIME` is [here](https://trino.io/docs/current/functions/datetime.html#current_time).

Snippet for reproducing the issue -
```
from sqlglot import parse

if __name__ == '__main__':
    sql_str = """
    SELECT CURRENT_TIME
            FROM table_a "tbl1_1"
    """
    expression_tree = parse(sql_str, read="trino")
    print(repr(expression_tree))
    print(expression_tree[0].sql(dialect="trino"))
```

**Comment by tobymao** [comment]
closed by c1456d0
