### ISSUE TITLE
Error when using date_add in starrocks

### ISSUE THREAD

**Issue by hellozepp** [tobymao/sqlglot#4345]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

`sqlglot.transpile(sql, read="starrocks", write="spark")`

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

starrocks SQL as following:
```
select date_add(current_date(),-1)
```

When I use date_add with a second parameter of -1, I get the following error:
```
Failed to parse test.sql, reason: INTERVAL expression expected but got '-1'

    func = function(args)
  File "/Users/zhanglin/PycharmProjects/sqlglot_master/sqlglot/dialects/dialect.py", line 1167, in _builder
    raise ParseError(f"INTERVAL expression expected but got '{interval}'")
sqlglot.errors.ParseError: INTERVAL expression expected but got '-1'
```
I excepted is：
```
SELECT date_add(current_date(),-1)
```

INTERVAL -1 DAY can be abbreviated to -1, and the result is as follows on starrocks:
```
StarRocks > select date_add(current_date(),-1)
    -> ;
+-------------------------------------------+
| date_add(current_date(), INTERVAL -1 DAY) |
+-------------------------------------------+
| 2024-11-04 00:00:00                       |
+-------------------------------------------+
1 row in set (0.07 sec)
```

Please help me, TKS

**Comment by hellozepp** [comment]
date_sub also has the same problem: 
```
select date_sub(current_date(),1)

  File "/Users/zhanglin/PycharmProjects/sqlglot_master/sqlglot/dialects/dialect.py", line 1167, in _builder
    raise ParseError(f"INTERVAL expression expected but got '{interval}'")
sqlglot.errors.ParseError: INTERVAL expression expected but got '1'

**Comment by hellozepp** [comment]
I saw this, [Commit 5436f53 Make date_add with incorrect expression more clear]
 maybe we can let go of numeric type interval:
```
if not isinstance(interval, exp.Interval):
if isinstance(interval, exp.Literal) and not interval.is_string:
pass
else:
raise ParseError(f"INTERVAL expression expected but got '{interval}'")
```

**Comment by georgesittas** [comment]
This is relatively low priority for us, StarRocks' [documentation page](https://docs.starrocks.io/docs/sql-reference/sql-functions/date-time-functions/date_add/) omits this syntax in favor of the `INTERVAL value unit` one, so you can use that for now.
