### ISSUE TITLE
Bugs in parsing `CURRENT_DATE` function in BigQuery

### ISSUE THREAD

**Issue by CYFish** [tobymao/sqlglot#4352]
It fails to parse [`CURRENT_DATE()`](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#current_date) without a timezone argument in BigQuery.

For example:
```python
sql = "SELECT CURRENT_DATE()"
ast = parse_one(sql, dialect="bigquery")
print(ast.sql(dialect="bigquery"))
# output: SELECT CURRENT_DATE
```
The parentheses are missing.

`CURRENT_DATE()` is parsed as an expression, and can't be formatted with parentheses.
![image](https://github.com/user-attachments/assets/f09dec3d-9d0e-42a7-856b-d58dd8cc3335)

**Comment by VaggelisD** [comment]
Seems like they're equivalent:

```SQL
SELECT CURRENT_DATE(), CURRENT_DATE;
2024-11-06 | 2024-11-06
```

The docs indicate that as well:

```
Description

Returns the current date as a DATE object. Parentheses are optional when called with no arguments.
```

Will go ahead and close this for now unless I'm missing the issue.

**Comment by CYFish** [comment]
Got it. Thank you a lot for the rapid response 🫡
