### ISSUE TITLE
Comment are not parsed properly on certain condition.

### ISSUE THREAD

**Issue by youngsol** [tobymao/sqlglot#4353]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```
sql = """
    create table test as 
    select a.column_name --# Comment 1
           ,b.column_name2, --# Comment 2
           b.column_name3 AS NAME3 --# Comment 3
    from table_name a
    join table_name2 b on a.column_name = b.column_name
    
"""
asts = parse(sql, dialect="spark")

for ast in asts:
    for col in ast.find(exp.Select):
        print(f"[{col.alias_or_name}] - {col.comments}")
        
        
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.
https://sqlglot.com/sqlglot.html#faq

Expected result
```
[column_name] - ['# Comment 1']
[column_name2] - ['# Comment 2']
[NAME3] - ['# Comment 3']
```

Actual result
```
[column_name] - None
[column_name2] - ['# Comment 2']
[NAME3] - ['# Comment 3']
```

Problem I found, If comma is located in front of  expression. comment is ignored. The official document states comments are kept in best effort. If this is the case, please ignore the issue.

**Comment by youngsol** [comment]
dialect doesn't matter. It occurs in multiple dialect. Tested on spar,  trino, and  mysql

**Comment by georgesittas** [comment]
The comment isn't ignored, but it's simply attached in the `Identifier` under the `Column`.

```
>>> sql = """
...     create table test as
...     select a.column_name --# Comment 1
...            ,b.column_name2, --# Comment 2
...            b.column_name3 AS NAME3 --# Comment 3
...     from table_name a
...     join table_name2 b on a.column_name = b.column_name
...
... """
>>> import sqlglot
>>> print(sqlglot.transpile(sql, pretty=True)[0])
CREATE TABLE test AS
SELECT
  a.column_name /* # Comment 1 */,
  b.column_name2, /* # Comment 2 */
  b.column_name3 AS NAME3 /* # Comment 3 */
FROM table_name AS a
JOIN table_name2 AS b
  ON a.column_name = b.column_name
```

However, the intention is to bubble up those comments to the `Comment` instance, so I fixed it.
