### ISSUE TITLE
[Reopen issue 4362] Excessive Recursion in Query Optimization with Multiple OR Clauses

### ISSUE THREAD

**Issue by gabrielteotonio** [tobymao/sqlglot#4367]
## Context  
**Sorry for reopening https://github.com/tobymao/sqlglot/issues/4362, but the proposed solution had no effect.**  

Even using `.sql()` instead of `.to_s`, we have hit the same stack limit issue. **It starts to reach the depth limit (1000) at 165 elements in the clause**:
```
is_equal.sql()
# throws
File "sqlglot/generator.py", line 3067, in or_sql
    return self.connector_sql(expression, "OR", stack)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sqlglot/generator.py", line 3084, in connector_sql
    stack.append(expression.right)
                 ^^^^^^^^^^^^^^^^
  File "sqlglot/expressions.py", line 4675, in right
    return self.expression
           ^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```
I'm not sure if the project wants to fix this, but it seems reasonable to think that SQLGlot Programatically builds queries, and this doesn't seem like an uncommon use case.

**Comment by georgesittas** [comment]
I think this is a legit issue, the problem is related to the `or_` builder: it always wraps the new condition with a `Paren`, which makes the iterative generation logic useless since you have to traverse the interleaved `Paren`s for each `OR`. This should work fine:

```
>>> from sqlglot import exp
>>>
>>>
>>> is_equal_list = ['a'] * 500
>>> is_equal = exp.false()
>>>
>>> for value in is_equal_list:
...     is_equal = exp.Or(this=is_equal, expression=exp.column("a_column").eq(value))
...
>>> is_equal.sql()
"FALSE OR a_column = 'a' OR a_column = 'a' OR a_
