### ISSUE TITLE
Invalid code example in ast_primer.md?

### ISSUE THREAD

**Issue by RedTailedHawk** [tobymao/sqlglot#4381]
On the `ast_primer.md` page, there's some code that I'm not quite following.  Seems like it's not valid Python code?

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/76daeb01-2dc1-4c51-8de3-81b7f3d47c4d">

**Comment by georgesittas** [comment]
It's valid in context, there are some snippets before it it's build on top of. You need some imports (`exp`, `parse_one`) and the scope built.

**Comment by RedTailedHawk** [comment]
Ah ok, it's a list comprehension.  Didn't see that the first time, thanks.
