### ISSUE TITLE
Visitor Pattern

### ISSUE THREAD

**Issue by RedTailedHawk** [tobymao/sqlglot#4382]
Is the visitor pattern supported with SqlGlot?  I'm coming from an ANTLR background, but not seeing any examples of this.

Thanks.

**Comment by tobymao** [comment]
not sure what this is but you can traverse the ast

**Comment by georgesittas** [comment]
No, SQLGlot does not leverage this pattern. Its parser is a typical recursive-descent one, and the generator (and other modules) relies on metaprogramming & recursion to walk the AST.

**Comment by RedTailedHawk** [comment]
Any plans on supporting this?  Would be nice to visit a node and then visit its children on down.

When I use `traverse_scope()`, it seems like it's traversing starting at the terminal nodes and going out from there.

**Comment by georgesittas** [comment]
No plans, you don't really need the visitor pattern. You can traverse an AST either using helpers like `walk` on its nodes, or by directly accessing its children using the `args` attribute.

**Comment by RedTailedHawk** [comment]
OK thanks.  Probably just need to get used to this paradigm shift, but visitor pattern would be great at some point in the future.

I'm curious why you didn't use ANTLR for your parser?

**Comment by RedTailedHawk** [comment]
Looks like you can do `reversed()` on a generator, but this seems to work:  `reversed(list(root_scope.traverse()))`

**Comment by georgesittas** [comment]
> I'm curious why you didn't use ANTLR for your parser?

From https://github.com/tobymao/sqlglot/blob/main/posts/python_sql_engine.md#why:

> Why did I do this? Isn't a Python SQL engine going to be extremely slow?
>
> The main reason why I ended up building a SQL engine was...just for **entertainment.** It's been fun learning about all the things required to actually run a SQL query, and seeing it actually work is extremely rewarding. Before SQLGlot, I had zero experience with lexers, parsers, or compilers.

**Comment by RedTailedHawk** [comment]
I'm sure you learned quite a bit more about lexers and parsers by not using ANTLR than I did by using it! :-).  But it's a great tool to _generate_ a parser for you (from a grammar).
