### ISSUE TITLE
Ordered expression NULLS LAST for BigQuery?

### ISSUE THREAD

**Issue by RedTailedHawk** [tobymao/sqlglot#4386]
My expression doesn't specify the `nulls_first` arg, but when I generate the SQL for the `bigquery` dialect, I'm getting `NULLS LAST` in the SQL.

`ordered_expr = exp.Ordered(this=dim_expr)`

I can turn it off with `nulls_first=True`, but then the SQL for the `redshift` dialect has `NULLS FIRST`.

Would like to emit SQL without `NULLS FIRST` or `NULLS LAST` in it, and just let the db provider decide on its default.

Seems like when I omit the `nulls_first` arg, it should do this.  Bug?

**Comment by georgesittas** [comment]
This behavior is expected, you need to respect the AST produced by the parser for bigquery:

```python
>>> import sqlglot
>>> sqlglot.parse_one("select * from t order by x", "bigquery")
Select(
  expressions=[
    Star()],
  from=From(
    this=Table(
      this=Identifier(this=t, quoted=False))),
  order=Order(
    expressions=[
      Ordered(
        this=Column(
          this=Identifier(this=x, quoted=False)),
        nulls_first=True)]))
```

SQLGlot understands the dialects' defaults and produces ASTs accordingly to facilitate both SQL roundtripping (*) for a given dialect, and transpilation towards other dialects. So I don't see a bug here. If you construct the AST manually, you need to understand what each argument means, and as I said, basically match what the parser would produce for the given dialect

(*) When an input doesn't roundtrip, the expectation is still that the semantics are preserved.
