### ISSUE TITLE
Oracle MINUS is converted to EXCEPT which doesn't work before Oracle 21c.

### ISSUE THREAD

**Issue by mkmoisen** [tobymao/sqlglot#4396]
Oracle [does not have an EXCEPT set operator prior to Oracle 21c](https://oracle-base.com/articles/21c/sql-set-operator-enhancements-21c).

[Oracle 19c set operators](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Set-Operators.html)

[Oracle 21c set operators](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Set-Operators.html)

In Oracle we use MINUS instead of EXCEPT.

sqlglot will default to using EXCEPT [here](https://github.com/tobymao/sqlglot/blob/main/sqlglot/generator.py#L1377) in generator.py::set_operation:

```
def set_operation(self, expression: exp.SetOperation) -> str:
        op_type = type(expression)
        op_name = op_type.key.upper()
        ...
```

----

I think that for Oracle, sqlglot should always use MINUS instead of EXCEPT, even in Oracle 21c or later. Unless sqlglot wanted to support different dialects for different versions which I assume we wouldn't want to do.

I would be happy to make a pull request for this unless you wanted to take care.

The approach that I would take is to simply override set_operations in the Oracle dialect and replace the first EXCEPT with MINUS:

```
def set_operation(self, expression: exp.SetOperation) -> str:
    sql = super().set_operation(expression)
    return re.sub(r'^EXCEPT', 'MINUS', sql, count=1)
```

Please let me know if you have a better approach.

----

Here is the current behavior which uses EXCEPT instead of MINUS.

```
import sqlglot

parsed = sqlglot.parse_one(
    '''
        select foo from a
        minus
        select bar from b
    ''',
    dialect='oracle'
)

print(parsed.sql(dialect='oracle', pretty=True))
```

```
SELECT
  foo
FROM a
EXCEPT
SELECT
  bar
FROM 
```

**Comment by georgesittas** [comment]
Is `MINUS` supported across all Oracle versions?

**Comment by tobymao** [comment]
@mkmoisen please don't use regex, you should either override op_type in set_operation, or probably make it a constant flag to change except to minus

**Comment by mkmoisen** [comment]
@georgesittas 

Yes MINUS is supported for all versions, whereas EXCEPT is an alias for MINUS and is only supported after 21c

Here is the earliest documentation I have found for Oracle 10.1:

https://docs.oracle.com/cd/B14117_01/server.101/b10759/queries004.htm

**Comment by georgesittas** [comment]
I see, yeah I second Toby's suggestion then. Something like

```python
    def set_operation(self, expression: exp.SetOperation) -> str:
        op_type = type(expression)
        op_name = self.SET_OP_NAME.get(op_type) or op_type.key.upper()
```
