### ISSUE TITLE
NOT LIKE not preserved

### ISSUE THREAD

**Issue by RedTailedHawk** [tobymao/sqlglot#4397]
```
dialect = "redshift"

sql = """
SELECT "brand" AS brand, SUM("sales") AS sales
FROM pasta
WHERE (LOWER("segment") NOT LIKE '%cut%')
GROUP BY "brand"
ORDER BY "brand"        
"""

parse_tree = parse_one(sql, dialect=dialect)

print(parse_tree.sql(dialect, pretty = True, pad = 4))
```

This bit:

```
  where=Where(
    this=Paren(
      this=Not(       <-- wraps the Like()
        this=Like(
          this=Lower(
            this=Column(
              this=Identifier(this=segment, quoted=True))),
          expression=Literal(this=%cut%, is_string=True))))),
```

Generated SQL has `NOT LOWER("segment") LIKE '%cut%'`.  Any way to preserve `NOT LIKE`?

Guess you could add a `NotLike` expression class, similar to `NEQ`?

**Comment by RedTailedHawk** [comment]
Interestingly, I get slightly different results between the two SQL queries when I execute on Redshift.  Looks like a small rounding issue, but not great that the results aren't identical.

<img width="847" alt="image" src="https://github.com/user-attachments/assets/00a68a1d-58d6-459f-8640-25210921c78f">

**Comment by georgesittas** [comment]
This is indeed interesting. Can you produce a minimally reproducible example so I can test this out? If there's a discrepancy between the two, we'll look into fixing that. But in general the semantics should be the same.

**Comment by RedTailedHawk** [comment]
And I guess if you wanted to be consistent, you would remove `NEQ` and emit something like `WHERE NOT x = 123`.  But that would probably not be great SQL, so why not do it for the other operators?

**Comment by RedTailedHawk** [comment]
Probably not easy for me to reproduce since the other buckets in my query (against a large table) were dead on.  But for some reason, this one bucket has a small discrepancy.

**Comment by georgesittas** [comment]
Could this be unrelated to the `NOT` switch? Like some other Redshift server-side issue? Do you get consistent results for both query variants?

> so why not do it for the other operators?

Because `<>` and `!=` are usually treated as a single token token, so it makes sense to have a `NEQ` expression. On the other hand, `NOT` is a unary operator that can be applied to other operators like `IS`, `LIKE`, etc. So they're not quite the same. It's simpler, from a parsing perspective, to wrap the condition in the `Not` node.

**Comment by RedTailedHawk** [comment]
It's consistent.  I just ran both queries 10 times each, and consistent for each set, and that one bucket is always (slightly different).

**Comment by georgesittas** [comment]
I don't really understand how that change would affect your calculations, given that it's in a `WHERE` filter (unless your actual query contains additional useful context). I'll go ahead and treat this as a non-issue until proven otherwise.

**Comment by RedTailedHawk** [comment]
Probably some subtle Redshift bug.
