### ISSUE TITLE
Parens Question

### ISSUE THREAD

**Issue by RedTailedHawk** [tobymao/sqlglot#4398]
I'm seeing SQL like this when I do `exp.Paren()`:

```
WHERE
    (
        LOWER("segment") = 'baking'
    )
```

Is it possible to emit the predicate on a single line?

```
WHERE
    (LOWER("segment") = 'baking')
```

**Comment by RedTailedHawk** [comment]
For multiple predicates, I'm getting this:

```
WHERE
    (
        LOWER("segment") IN ('long cut', 'short cut')
    )
    AND (
        EXTRACT(YEAR FROM month) BETWEEN 2020 AND 2022
    )
```

Hoping I can get the SQL generated like this:

```
WHERE
    (LOWER("segment") IN ('long cut', 'short cut'))
    AND (EXTRACT(YEAR FROM month) BETWEEN 2020 AND 2022)
```

Is there a formatting option, or will I need to implement some custom code for this?

**Comment by georgesittas** [comment]
There's no such option today, no. Custom code it is, you can override/patch `paren_sql`.
