### ISSUE TITLE
Tracing Source Tables for Top-Level SELECT Columns in Complex SQL Queries with Nested Subqueries and Unions

### ISSUE THREAD

**Issue by nipilii** [tobymao/sqlglot#4411]
Thank you for your previous response! It was really helpful 

**Follow-Up Question:**

I have another question related to tracing column sources in complex queries.

Specifically, I want to identify the source tables for a column appearing in the top-level SELECT. For instance, in the following query:

SELECT xx.this_col
FROM (
    (SELECT A.this_col FROM tableA A)
    UNION ALL
    (SELECT B.this_col FROM tableB B)
    UNION ALL
    (SELECT C.this_col FROM tableC C)
) xx
For the column this_col, the source tables would be tableA, tableB, and tableC.

**Another example involves a more complex query:**

SELECT a.id, sub_query.name
FROM 
     ( 
         SELECT b.id, 
                (
                    SELECT d.name
                    FROM table_d d
                    WHERE d.id = b.id
                ) AS name
         FROM table_b b
     ) AS sub_query,
     table_a a
WHERE a.id = sub_query.id
ORDER BY sub_query.name;

Here, the name column in the top-level SELECT originates from a nested subquery within sub_query. That subquery references the name column from table_d through its subquery (SELECT d.name FROM table_d d WHERE d.id = b.id) AS name.

In both examples, I'd like to identify the ultimate source table(s) for the top-level columns, considering cases like unions and deeply nested subqueries.

Do you have any suggestions or approaches for this?

**Comment by georgesittas** [comment]
Check out the `qualify` and `scope` modules. There's an article on this as well here - https://medium.com/@pizzini.alessandro/monitoring-column-usage-with-sqlglot-a-journey-towards-data-warehouse-optimization-299667aa44dc.

It'd be better if you joined the Slack community to post these questions.
