### ISSUE TITLE
Must "In" expressions be strings?

### ISSUE THREAD

**Issue by RedTailedHawk** [tobymao/sqlglot#4418]
I had to add this logic to my code:

```
in_expr = exp.In(this=left_expr, expressions=[exp.Literal(this=x.lower(), is_string=True) if isinstance(x, str) else exp.Literal(this=str(x), is_string=False) for x in membership_values])
```

i.e. `exp.Literal(this=str(x), is_string=False)` was necessary to prevent a runtime error here:

<img width="722" alt="image" src="https://github.com/user-attachments/assets/4d6fa344-81fe-4252-8f16-6d8263567a4d">

Would be nice if I could just do this in my code:

```
in_expr = exp.In(this=left_expr, expressions=[exp.Literal(this=x.lower(), is_string=True) if isinstance(x, str) else exp.Literal(this=x) for x in membership_values])
```

**Comment by georgesittas** [comment]
When you're manually constructing AST nodes, you need to respect the structure that the Parser produces. In this case, `is_string` is important for the `Literal` node, otherwise SQLGlot won't know how to generate that.

**Comment by RedTailedHawk** [comment]
If I indicate that it's not a string, I get another error:

```
in_expr = exp.In(this=left_expr, expressions=[exp.Literal(this=x.lower(), is_string=True) if isinstance(x, str) else exp.Literal(this=x, is_string=False) for x in membership_values])
```

<img width="741" alt="image" src="https://github.com/user-attachments/assets/a0dd0c33-d2ec-4c69-9246-75caa891d5ed">

I guess because the `join` only operates on strings?

**Comment by georgesittas** [comment]
You need to store the string representation of the number in the `Literal` node.

**Comment by RedTailedHawk** [comment]
But `Literal` can take a number, so seems like `In()` could be aware of that and do the string conversion as needed.
