### ISSUE TITLE
[Postgres] Parser does not support string concatenation operator inside substring function

### ISSUE THREAD

**Issue by g-u-t-h-m-a-n** [tobymao/sqlglot#442]
Example (valid sql):
```
select substring(2022::char(4) || lpad(3::char(2), 2, '0') from 3 for 4)
```
Result:
```
ParseError: Expecting ). Line 1, Col: 31.
  select substring(2022::char(4)||lpad(3::char(2), 2, '0') from 3 for 4)

Expected table name. Line 1, Col: 63.
  select substring(2022::char(4)||lpad(3::char(2), 2, '0') from 3 for 4)

Required keyword: 'this' missing for <class 'sqlglot.expressions.Table'>. Line 1, Col: 63.
  select substring(2022::char(4)||lpad(3::char(2), 2, '0') from 3 for 4)
```

And it seems like https://github.com/tobymao/sqlglot/issues/421 is still an issue here (I'm using sqlglot 6.0.7).

**Comment by GeorgeSittas** [comment]
Fixing the concatenation issue is no big deal, but are you sure your example is valid? With a quick check using [EverSQL](https://www.eversql.com/sql-syntax-check-validator/), it seems like it's not.

> And it seems like https://github.com/tobymao/sqlglot/issues/421 is still an issue here (I'm using sqlglot 6.0.7).

I'm not sure what you mean here -- if you use `read='postgres'` in parse_one, sqlglot recognizes the from..for.. syntax.
