### ISSUE TITLE
Azure SQL parses but does not execute

### ISSUE THREAD

**Issue by RedTailedHawk** [tobymao/sqlglot#4420]
The following SQL parses ok for the `tsql` dialect:

```
dialect = "tsql"

sql = """
SELECT *
FROM
(
    SELECT *
    FROM dim_region
)
"""

parse_tree = parse_one(sql, dialect=dialect)

print(repr(parse_tree))
```

But it does not run on Azure unless you have an alias (even if your query doesn't need to explicitly reference it).

<img width="624" alt="image" src="https://github.com/user-attachments/assets/6f5fbfc8-4f93-4f21-ba8b-49f6af849480">

This does work:

<img width="492" alt="image" src="https://github.com/user-attachments/assets/e60a57aa-9fde-4554-96a3-a8d3215245be">

Could you change your parser to throw an exception if the alias is missing from the derived table for `tsql`?

**Comment by tobymao** [comment]
sqlglot is not a full fledged validator
