### ISSUE TITLE
REVOKE ParseError in presto

### ISSUE THREAD

**Issue by IrisesD** [tobymao/sqlglot#4424]
**Before you file an issue**
- [x] Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- [x] Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`

**Fully reproducible code snippet**

```Python
import sqlglot

sql = "REVOKE INSERT, SELECT ON orders FROM alice;"
ast = sqlglot.parse(sql, "presto")
```

```bash
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 13.
  REVOKE INSERT, SELECT ON orders FROM alice;
```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

https://prestodb.io/docs/current/sql/revoke.html

**Comment by tobymao** [comment]
closed by #e3c45d
