### ISSUE TITLE
Missing Support : Google BigQuery ML functions 

### ISSUE THREAD

**Issue by YuvrajSoni-Ksolves** [tobymao/sqlglot#4428]
# Description
 I'm encountering an issue with the BigQuery dialect in SQLGlot where it fails to parse queries containing BigQuery ML functions like ML.FEATURES_AT_TIME. The expected behavior is to convert the BigQuery query to an AST, but SQLGlot does not currently support these functions, resulting in a parse failure.

## Details
BigQuery ML provides specialized functions to interact with machine learning models and feature tables. One such function, ML.FEATURES_AT_TIME, is used to retrieve the values of features for entities at a given point in time. However, the BigQuery dialect in SQLGlot does not currently recognize or support this function's syntax, leading to parsing errors.

The specific functions and syntax that are not supported include:

``` ML.FEATURES_AT_TIME Function ```
Syntax:

``` 
ML.FEATURES_AT_TIME(
  TABLE feature_table_name,
  time => timestamp_expression,
  [num_rows => int_expression],
  [ignore_feature_nulls => boolean_expression]
)
```
Parameters:
#### ignore_feature_nulls (Optional): A flag to determine if rows with null feature values should be ignored.
Example Query:
```
WITH
  feature_table AS (
    SELECT * FROM UNNEST(
      ARRAY<STRUCT<entity_id STRING, f_1 FLOAT64, f_2 FLOAT64, feature_timestamp TIMESTAMP>>[
        ('id1', 1.0, 1.0, TIMESTAMP '2022-06-10 12:00:00+00'),
        ('id2', 12.0, 24.0, TIMESTAMP '2022-06-11 12:00:00+00'),
        ('id1', 11.0, NULL, TIMESTAMP '2022-06-11 12:00:00+00'),
        ('id1', 6.0, 12.0, TIMESTAMP '2022-06-11 10:00:00+00'),
        ('id2', 2.0, 4.0, TIMESTAMP '2022-06-10 12:00:00+00'),
        ('id2', 7.0, NULL, TIMESTAMP '2022-06-11 10:00:00+00')])
  )
SELECT *
FROM
  ML.FEATURES_AT_TIME(
    TABLE feature_table,
    time => '2022-06-12 10:00:00+00',
    num_rows => 1,
    ignore_feature_nulls => TRUE);
```
#### Update the generator to ensure proper SQL generation from the AST.

**Comment by VaggelisD** [comment]
Hey @YuvrajSoni-Ksolves,

Thank you for reporting this. Sadly some functions such as `FEATURES_AT_TIME()` require more nuanced parsing and if they're not manually added to SQLGlot their parsing can fail.

I went ahead and implemented `FEATURES_AT_TIME()` but our bandwidth is limited so we'd not be able to support all other ML functions right away. 

If possible, consider taking a look at my approach and contributing any other problematic function you come across, we accept well-crafted PRs.
