### ISSUE TITLE
[Postgres] Parser does not support operators inside extract() function

### ISSUE THREAD

**Issue by g-u-t-h-m-a-n** [tobymao/sqlglot#443]
Example (valid sql):
```
select extract(week from current_date + 2);
```

Result:
```
ParseError: Expecting ). Line 1, Col: 39.
  select extract(week from current_date + 2);

Invalid expression / Unexpected token. Line 1, Col: 42.
  select extract(week from current_date + 2);
```

The addition operator can be substituted for other operators, yielding the same exception.

**Comment by GeorgeSittas** [comment]
This has been documented [here](https://github.com/tobymao/sqlglot/discussions/436) as well. I will open a PR to fix it later if yuchaofan13 hasn't done so already.
