### ISSUE TITLE
Incorrect translation of  function PERCENTILE between Spark and Starrocks

### ISSUE THREAD

**Issue by fred-yan** [tobymao/sqlglot#4443]
When I use the following code want to translate spark sql  to starocks code:
```
>>> sql = 'select percentile(id, array(0.2, 0.3, 0.5)) from bak_work_test.aaa;select percentile_approx(id, array(0.2, 0.3, 0.5), 5) from bak_work_test.aaa;'

>>> formatted_sql = sqlglot.transpile(sql, read='hive', write='starrocks')
>>> print(formatted_sql)
['SELECT QUANTILE(id, [0.2, 0.3, 0.5]) FROM bak_work_test.aaa', 'SELECT APPROX_QUANTILE(id, [0.2, 0.3, 0.5], 5) FROM bak_work_test.aaa']

>>> formatted_sql = sqlglot.transpile(sql, read='spark', write='starrocks')
>>> print(formatted_sql)
['SELECT QUANTILE(id, [0.2, 0.3, 0.5]) FROM bak_work_test.aaa', 'SELECT APPROX_QUANTILE(id, [0.2, 0.3, 0.5], 5) FROM bak_work_test.aaa']
```

the output result will translate  keyword **percentile** and **percentile_approx** to **QUANTILE** and **APPROX_QUANTILE**,
but we refer the starrocks official documentation https://docs.starrocks.io/docs/sql-reference/sql-statements/keywords/#q,
it does not exist keyword QUANTILE ， however have the keyword Percentile.
maybe it need to optimize this sql code translation?  
thanks!

**Comment by tobymao** [comment]
feel free to submit a pr, but closing as this is not high priority for the core team.
