### ISSUE TITLE
Removing comments from SQL

### ISSUE THREAD

**Issue by mrcolumbia** [tobymao/sqlglot#4444]
sqlparse offers the following to strip comments from SQL:

`sqlparse.format(sql_example, strip_comments=True).strip()`

Does sqlglot offer a similar functionality? Would like to use one library instead of two.

**Comment by VaggelisD** [comment]
Actually, this is supported out of the box.  You can pass `comments=False` on the `sql` call, i.e:

```Python3
ast = sqlglot.parse_one(..., dialect=...)

ast.sql(dialect, comments=False)
```

Try these out and let us know if that worked.
