### ISSUE TITLE
Incorrect translation of CONCAT_WS from Snowflake to Mysql (and likely others)

### ISSUE THREAD

**Issue by martimlobao** [tobymao/sqlglot#4452]
`CONCAT_WS` behaves differently on Snowflake and Mysql: nulls are skipped in Mysql, but any null expression in Snowflake causes the entire return value to be null as well.

**Fully reproducible code snippet**
```python
>>> transpile(
...     "select CONCAT_WS(', ', col1, col2, col3) as foo from table",
...     read='mysql',
...     write='snowflake',
... )[0]
"SELECT CONCAT_WS(', ', col1, col2, col3) AS foo FROM table"
```
Translating this query from Mysql to Snowflake requires skipping any null values in col1, col2, col3. Conversely, translating `CONCAT_WS` from Snowflake to Mysql requires setting the output to null if any of col1, col2, col3 are null.

**Official Documentation**
[Mysql](https://www.w3schools.com/sql/func_mysql_concat_ws.asp#:~:text=required.%20the%20expressions%20to%20add%20together.%20an%20expression%20with%20a%20null%20value%20will%20be%20skipped)
[Snowflake](https://docs.snowflake.com/en/sql-reference/functions/concat_ws#:~:text=concatenates%20two%20or%20more%20strings%2C%20or%20concatenates%20two%20or%20more%20binary%20values.%20if%20any%20of%20the%20values%20is%20null%2C%20the%20result%20is%20also%20null.)

**Comment by tobymao** [comment]
feel free to submit a well crafted and tested pr, closing for now as this is not a priority for the core team
