### ISSUE TITLE
BigQuery function `CONTAINS_SUBSTRING` should be `CONTAINS_SUBSTR`

### ISSUE THREAD

**Issue by romanhaa** [tobymao/sqlglot#4456]
I believe there is an issue in the BigQuery dialect. sqlglot identifies and correctly transpiles a function called `CONTAINS_SUBSTRING`, but it appears the function is actually called `CONTAINS_SUBSTR` (see [docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#contains_substr)). The function `CONTAINS_SUBSTRING` results in an error as the function is not recognized by BigQuery.

https://github.com/tobymao/sqlglot/blob/73825d2d11cefaabd2ed73c3dcb9184393b6c042/sqlglot/dialects/bigquery.py#L320

It would be great if someone could independently verify and potentially fix this.

**Comment by VaggelisD** [comment]
Hey @romanhaa, thank you for reporting this, it does look like a mistake on our end.
