### ISSUE TITLE
Trino CURRENT_USER does not allow parenthesis

### ISSUE THREAD

**Issue by MikeWallis42** [tobymao/sqlglot#4458]
```python
from sqlglot import parse_one
from sqlglot.dialects import Trino

sql_in = parse_one("SELECT CURRENT_USER", dialect=Trino)
print(sql_in.sql(dialect=Trino))
```
```bash
SELECT CURRENT_USER()
```

https://prestodb.io/docs/current/functions/session.html
https://trino.io/docs/current/functions/session.html

I believe that the Postgres dialect already implements the desired workaround for this function
https://github.com/tobymao/sqlglot/blob/v25.32.1/sqlglot/dialects/postgres.py#L527

**Comment by MikeWallis42** [comment]
If I may, I would like to submit the solution for this given that it's an easier entry point in to contributing

**Comment by VaggelisD** [comment]
Sure, please go for it @MikeWallis42! Thank you.
