### ISSUE TITLE
collect_set translated to set_agg in trino from spark sql

### ISSUE THREAD

**Issue by ankurchavda** [tobymao/sqlglot#4460]
**Before you file an issue**
- Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
- Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.

Input:

```sql
SELECT CONCAT_WS(',', COLLECT_SET(GET_JSON_OBJECT(data,'$.result_reasons')))
```

Output:

```sql
SELECT
  CONCAT_WS(',', CAST(SET_AGG(JSON_EXTRACT_SCALAR(data, '$.result_reasons')) AS VARCHAR))
  ```

**Official Documentation**
Please include links to official SQL documentation related to your issue.

**Comment by VaggelisD** [comment]
Hey @ankurchavda, thank you for reporting this. Looks like this is a valid Presto function but not a Trino one, right?

I came across this [article](https://www.sqlines.com/hive-to-trino/collect_set) that claims `COLLECT_SET(x) -> ARRAY_AGG(DISTINCT x)` should be the proper transpilation in this case, could you verify if that'd work properly for your case too?

**Comment by ankurchavda** [comment]
@VaggelisD yes `ARRAY_AGG(DISTINCT x)` works in trino.
