### ISSUE TITLE
Parse Exception for Teradata DDL Statements with MAP Keyword

### ISSUE THREAD

**Issue by sriram251-code** [tobymao/sqlglot#4461]
I am trying to parse Teradata DDL statement using teradata dialects, I am getting parse exception if a DDL statement has MAP keyword. EX:
CREATE SET TABLE TABLEA ,NO FALLBACK ,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
    MAP = TD_MAP1
     (
      COL1 DECIMAL(14,0) )

**Comment by tobymao** [comment]
not huh priority
