### ISSUE TITLE
How to handle alias when using diff

### ISSUE THREAD

**Issue by LJHzju** [tobymao/sqlglot#4464]
During the process of using `diff` to compare the differences between two queries, it was found that the results were highly influenced by the aliases. For example, consider the following two queries:
```
"SELECT DISTINCT cc.kind FROM comp_cast_type cc WHERE cc.kind = 'complete';"
"SELECT DISTINCT cd.kind FROM comp_cast_type cd WHERE cd.kind = 'complete';"
```
These two queries are almost identical, yet the result from diff shows that the proportion of `Keep` is only 35%.

Here is the specific code:
```
sql1 = "SELECT DISTINCT cc.kind FROM comp_cast_type cc WHERE cc.kind = 'complete';"
sql2 = "SELECT DISTINCT cd.kind FROM comp_cast_type cd WHERE cd.kind = 'complete';"
total_list = diff(optimize(parse_one(sql1)), optimize(parse_one(sql2)))
np.mean([1 if isinstance(e, Keep) else 0 for e in edit_script])

output: 0.35
```

**Comment by tobymao** [comment]
you’ll have to explore the nodes to weight different kinds as you wanr
