### ISSUE TITLE
MySQL to DuckDB: UPDATE ... JOIN translation

### ISSUE THREAD

**Issue by iloupv** [tobymao/sqlglot#4469]
Hey! I got this issue trying to translate a MySQL query into DuckDB so I can run my database queries locally using Pandas dataframes as the tables.
The query is similar to this:

`UPDATE
  favorites 
INNER JOIN
  images
ON
  favorites.image_id = images.id
SET
  favorites.archive = 1
WHERE
  favorites.user_id = '1'`
  
However, during `transpile` operation, the resulting query seems to be the same, and I was questioning myself if this translation is supported.

Any insight regarding this would be appreciated.

**Comment by tobymao** [comment]
not all transpilations work out of the box. feel free to make a well tested and documented PR to address these.
