### ISSUE TITLE
Problems transpiling timestamp expressions between risingwave and trino

### ISSUE THREAD

**Issue by blecourt-private** [tobymao/sqlglot#4470]
I have found various issues related to transpiling the expression `SELECT TO_TIMESTAMP(CAST(1733232066 AS DOUBLE PRECISION)) AT TIME ZONE 'UTC'` in the risingwave dialect to the trino dialect.

- Transpiling from risingwave to trino and then back to risingwave results in a SQL expression that is not valid in risingwave
- Casting to varchar using the postgres `x::varchar` syntax produces different results on a RisingWave and Trino engine
- Time zone conversion is wrong in trino after transpiling from a risingwave query
- SQLGlot seems to be sensitive to grouping

## Fully reproducible code snippets

**Transpiling back and forth results in invalid expression**

SQL expression in the risingwave dialect:

```
SELECT TO_TIMESTAMP(CAST(1733232066 AS DOUBLE PRECISION)) AT TIME ZONE 'UTC'
```

Transpiling to trino and back again:

```
sqlglot.transpile("SELECT TO_TIMESTAMP(CAST(1733232066 AS DOUBLE PRECISION)) AT TIME ZONE 'UTC'", read="risingwave", write="trino")
```

Result: `["SELECT AT_TIMEZONE(FROM_UNIXTIME(CAST(1733232066 AS DOUBLE) / 1000000.), 'UTC')"]`

Going the other way:

```
sqlglot.transpile("SELECT AT_TIMEZONE(FROM_UNIXTIME(CAST(1733232066 AS DOUBLE)), 'UTC')", read="trino", write="risingwave")
```

Result: `["SELECT AT_TIMEZONE(TO_TIMESTAMP(CAST(1733232066 AS DOUBLE PRECISION)), 'UTC')"]`

The function `AT_TIMEZONE()` doesn't exist in risingwave. Instead one should use the `AT TIME ZONE` operator. The expected result is `["SELECT TO_TIMESTAMP(CAST(1733232066 AS DOUBLE PRECISION)) AT TIME ZONE 'UTC'"]`, which was also our starting point.

**Casting to varchar:**

```
sqlglot.transpile("SELECT (TO_TIMESTAMP(CAST(1733232066 AS DOUBLE PRECISION)) AT TIME ZONE 'UTC')::varchar", read="risingwave", write="risingwave")
```

Result: `["SELECT CAST((TO_TIMESTAMP(CAST(1733232066 AS DOUBLE PRECISION)) AT TIME ZONE 'UTC') AS VARCHAR)"]`

Running this select statement on a RisingWave engine results in `2024-12-03 13:21:06`.

```
sqlglot.transpile("SELECT (TO_TIMESTAMP(CAST(1733232066 AS DOUBLE PRECISION)) AT TIME ZONE 'UTC')::varchar", read="risingwave", write="trino")
```

Result: `["SELECT CAST((AT_TIMEZONE(FROM_UNIXTIME(CAST(1733232066 AS DOUBLE)), 'UTC')) AS VARCHAR)"]`

Running this select statement on a Trino engine results in `2024-12-03 13:21:06.000 UTC`, which is formatted in a completely different way than the result from the RisingWave engine. 

**Time zone conversion:**

The risingwave select statement `SELECT CAST(TO_CHAR((CAST('2024-12-03 13:21:06.000000' AS TIMESTAMP) AT TIME ZONE 'Europe/Copenhagen') AT TIME ZONE 'UTC','YYYY-MM-DDTHH24:MI:SS.USZ') AS VARCHAR)` results in `2024-12-03T12:21:06.000000Z` when run on a RisingWave engine.

Transpiling to trino:

```
 sqlglot.transpile("SELECT CAST(TO_CHAR((CAST('2024-12-03 13:21:06.000000' AS TIMESTAMP) AT TIME ZONE 'Europe/Copenhagen') AT TIME ZONE 'UTC','YYYY-MM-DDTHH24:MI:SS.USZ') AS VARCHAR)", read="risingwave", write="trino")
```

Result: `["SELECT CAST(DATE_FORMAT(AT_TIMEZONE((AT_TIMEZONE(CAST('2024-12-03 13:21:06.000000' AS TIMESTAMP), 'Europe/Copenhagen')), 'UTC'), '%Y-%m-%dT%T.%fZ') AS VARCHAR)"]`

Running this on a Trino engine results in `2024-12-03T13:21:06.000000Z` which is an hour off compared to the result in RisingWave.

The following Trino query gives the correct result:  

```
SELECT CAST(DATE_FORMAT(AT_TIMEZONE((WITH_TIMEZONE(CAST('2024-12-03 13:21:06.000000' AS TIMESTAMP), 'Europe/Copenhagen')), 'UTC'), '%Y-%m-%dT%T.%fZ') AS VARCHAR)
```

Running this on a Trino engine results in `2024-12-03T12:21:06.000000Z`

**Finally, sqlglot is sensitive to grouping.**

The risingwave query `SELECT CAST(TO_CHAR(CAST('2024-12-03 13:21:06.000000' AS TIMESTAMP) AT TIME ZONE 'Europe/Copenhagen' AT TIME ZONE 'UTC','YYYY-MM-DDTHH24:MI:SS.USZ') AS VARCHAR)` is valid and when run on RisingWave produces `2024-12-03T12:21:06.000000Z`. 

Transpiling to trino:

```
sqlglot.transpile("SELECT CAST(TO_CHAR(CAST('2024-12-03 13:21:06.000000' AS TIMESTAMP) AT TIME ZONE 'Europe/Copenhagen' AT TIME ZONE 'UTC','YYYY-MM-DDTHH24:MI:SS.USZ') AS VARCHAR)", read="risingwave", write="trino")
```

Result: `["SELECT CAST(DATE_FORMAT(AT_TIMEZONE(CAST('2024-12-03 13:21:06.000000' AS TIMESTAMP), AT_TIMEZONE('Europe/Copenhagen', 'UTC')), '%Y-%m-%dT%T.%fZ') AS VARCHAR)"]`

The part **AT_TIMEZONE('Europe/Copenhagen', 'UTC')** is not valid.

Trino error:
```
trino error: TrinoUserError(type=USER_ERROR, name=FUNCTION_NOT_FOUND, message="line 1:86: Unexpected parameters (varchar(17), varchar(3)) for function at_timezone. Expected: at_timezone(timestamp(p) with time zone, interval day to second), at_timezone(timestamp(p) with time zone, varchar(x))",
```

**Official Documentation**

Risingwave date and time functions and operators: https://docs.risingwave.com/sql/functions/datetime

Risingwave timestamp with time zone operators: https://docs.risingwave.com/sql/functions/datetime#timestamp-with-time-zone-operators

Risingwave to_timestamp syntax: https://docs.risingwave.com/sql/functions/datetime#to-timestamp-string-timestamp-format

Trino Date and time functions and operators: https://trino.io/docs/current/functions/datetime.html

Trino with_timezone function: https://trino.io/docs/current/functions/datetime.html#with_timezone
Trino timestamp data type: https://trino.io/docs/current/language/types.html#timestamp

**Comment by georgesittas** [comment]
Transpilation is best-effort, and Risingwave in particular is not as mature as other dialects, because it was a 3rd-party contribution. We're not planning to prioritize fixes for it ourselves, but will happily accept well-crafted & tested PRs if you want to contribute.

**Comment by blecourt-private** [comment]
Fair enough, but since we have these problems transpiling from the risingwave dialect to trino made me wonder if we have similar problems when transpiling from postgres to trino. And the same issues arise there. Should I modify the issue to reflect the Postgres -> Trino scenario, or should I create a separate issue for it?

PS. The RisingWave dialect class in sqlglot inherits from the Postgres class - does this mean that fixing the problems for Postgres will improve the situation for RisingWave as well?

**Comment by georgesittas** [comment]
> does this mean that fixing the problems for Postgres will improve the situation for RisingWave as well?

Yes, most likely, unless the two diverge for the relevant features.

> Should I modify the issue to reflect the Postgres -> Trino scenario, or should I create a separate issue for it?

I think this is still relatively low priority for the core team, even for the Postgres <-> Trino case, but again, we'll welcome any well-crafted contributions. Otherwise we may pick it up sometime in the future. If you do end up working on this, feel free to reach out in Slack and we can help / guide as needed.
