### ISSUE TITLE
Extend Teradata TRANSLATE function to support Implicit Character Data Type Conversion

### ISSUE THREAD

**Issue by wajdi-db** [tobymao/sqlglot#4481]
**Is your feature request related to a problem? Please describe.**
The current parsing function for [TRANSLATE](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/teradata.py#L177-L189) supports basic syntax such as `TRANSLATE('abc' USING UNICODE_TO_LATIN)`, however it uses a cast expression and doesn't support implicit character replacement in case of error using this syntax `TRANSLATE('abc ' USING UNICODE_TO_LATIN WITH ERROR)`

```py
>>> from sqlglot import parse_one
>>> parse_one("select TRANSLATE('abc ' USING UNICODE_TO_LATIN)", dialect='teradata').sql() 
"SELECT CAST('abc ' AS CHAR CHARACTER SET LATIN)"
>>> parse_one("select TRANSLATE('abc ' USING UNICODE_TO_LATIN WITH ERROR)", dialect='teradata').sql()
...
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 51.
  select TRANSLATE('abc ' USING UNICODE_TO_LATIN **WITH** ERROR)
```

**Describe the solution you'd like**
I would like the parser to actually use TRANSLATE syntax in SQL when dialect permits instead of cast and support `WITH ERROR` option.

**Describe alternatives you've considered**
No alternatives found within the framework.

**Additional context**
Teradata documentation: https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Functions-Expressions-and-Predicates/String-Operators-and-Functions/TRANSLATE/TRANSLATE-Usage-Notes/Implicit-Character-Data-Type-Conversion

**Comment by georgesittas** [comment]
Hey, appreciate the report but this is low priority for the core team. We'll be happy to accept a well-crafted & tested PR.
