### ISSUE TITLE
MAX in GROUP BY Clause in Optimized script

### ISSUE THREAD

**Issue by dotanentin** [tobymao/sqlglot#4484]
Hello,

I am starting to use the code as an SQL Optimizer to use in my organization.
It seems to work well but I have recently while testing my code, I went into a problem with a specific query.

Some pointers:
1. I am always providing a schema, as full as I possibly can. In this occasion - a full schema was provided.
2. Read dialect is spark and write dialect is databricks
3. I transpile the query, Parse and then run Optimize on the query.
4. The code provided here was adjusted to remove any column and table names but provides the same problem I face.
5. I use python 3.11.9 and sqlglot 24.3.1

My code for the bug is simple as follows:
```
sql_query = """
SELECT
  column1,
  SUM(column2) AS column3,
  SUM(column4) AS column5,
  MAX(column6) * -1 AS column7
FROM
  schema_name.table_name
WHERE
  TO_DATE(column8) IN (
    SELECT
      MAX(TO_DATE(column8)) AS column8
    FROM
      schema_name.table_name
  )
GROUP BY
  column1
"""
sql_schema = {
  "table_name": {
    "column1": "VARCHAR",
    "column2": "DECIMAL",
    "column3": "DECIMAL",
    "column4": "INTEGER",
    "column5": "INTEGER",
    "column6": "INTEGER",
    "column7": "INTEGER",
    "column8": "DATE"
  }
}

transpiled_query = transpile(sql_query, read=read_dialect, write=write_dialect,)[0]
parsed_query = parse_one(transpiled_query, read=read_dialect)
print(optimize(parsed_query, schema=sql_schema).sql(pretty=False, dialect='databricks'))
```

This provides an optimized query that has a MAX function in GROUP BY clause, which is causing the run to fail.

Output Optimized query:
```
WITH `_u_0` AS (SELECT MAX(`table_name`.`column8`) AS `column8` FROM `schema_name`.`table_name` AS `table_name` GROUP BY MAX(`table_name`.`column8`)) SELECT `table_name`.`column1` AS `column1`, SUM(`table_name`.`column2`) AS `column3`, SUM(`table_name`.`column4`) AS `column5`, MAX(`table_name`.`column6`) * -1 AS `column7` FROM `schema_name`.`table_name` AS `table_name` LEFT JOIN `_u_0` AS `_u_0` ON `_u_0`.`column8` = `table_name`.`column8` WHERE NOT `_u_0`.`column8` IS NULL GROUP BY `table_name`.`column1`
```

Please let me know if anything else is needed.

Thank you for your help!

**Comment by tobymao** [comment]
the optimize function is not super high priority for us, but we're willing to accept high quality PRs. additionally, we offer enterprise level support if this is something you'd like to get prioritized.

**Comment by D2Bull** [comment]
it seems like the bug is related to **unnest_subqueries**.
in the above use case the value of the subquery is an agg, but it's MAX.
so it's overwrite by MAX again, which is incorrect.

**The subquery  from above -**
IN (
    SELECT
      MAX(TO_DATE(column8)) AS column8
    FROM
      schema_name.table_name
  )

**Original code -** (https://github.com/tobymao/sqlglot/blob/main/sqlglot/optimizer/unnest_subqueries.py)
    # if the value of the subquery is not an agg or a key, we need to collect it into an array
    # so that it can be grouped. For subquery projections, we use a MAX aggregation instead.
    agg_func = exp.Max if is_subquery_projection else exp.ArrayAgg
    if not value.find(exp.AggFunc) and value.this not in group_by:
        select.select(
            exp.alias_(agg_func(this=value.this), value.alias, quoted=False),
            append=False,
            copy=False,
        )
