### ISSUE TITLE
Comma at the end of FROM token list is legal in SNOWFLAKE, but causes parse error in sqlglot

### ISSUE THREAD

**Issue by kosta-foundational** [tobymao/sqlglot#4487]
sqlglot version 25.32.0

**Fully reproducible code snippet**
Example 1:
```
    q = """
SELECT
    id
FROM import_chat_sessions,
LATERAL FLATTEN(input => history) prs_history,
"""
sqlglot.parse(sql=q, dialect=sqlglot.Dialects.SNOWFLAKE)
```

Example 2:
```
    q = """
SELECT
    id
FROM import_chat_sessions,
WHERE id > 2
"""
sqlglot.parse(sql=q, dialect=sqlglot.Dialects.SNOWFLAKE)
```

**Comment by georgesittas** [comment]
Thanks for the report. I took a quick stab at it and the fix didn't seem trivial, so I'd say this one's out of scope for the time being.

**Comment by kosta-foundational** [comment]
@georgesittas , Note that parsing succeeds if there is extra comma in SELECT list.

**Comment by georgesittas** [comment]
Yeah, I'm aware. Trailing commas are generally non-standard, but SQLGlot will go ahead and parse them anyway in many cases. The `FROM` clause is an exception in this case because the parsing logic that deals with joins is more complicated.

**Comment by georgesittas** [comment]
Fixed in https://github.com/tobymao/sqlglot/commit/b7a0df1b9a9cff2cd57db77ac0095c189b9d67ab thanks to @omerhadari!
