### ISSUE TITLE
interval parsing for postgresql

### ISSUE THREAD

**Issue by fuglaeff** [tobymao/sqlglot#4490]
Hi! I have some problems with parsing postgresql statements that has more that one date units in intervals...
lib version 25.34.0
```python3
import sqlglot

sql = """
select *
from table
where 
    some_column >= (current_date + interval '1 day 1 hour')
    and some_another_column is True;
"""

parsed = sqlglot.parse_one(sql, dialect="postgres")
```
This works fine and we have
```
expression=Paren(
    this=Add(
        this=CurrentDate(),
        expression=Interval(this=Literal(this=1 day 1 hour, is_string=True))
    )
)
```
But if we drop brackets in where statement
```sql
select *
from table
where 
    some_column >= current_date + interval '1 day 1 hour'
    and some_another_column is True;
```
parser throw exception `sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 6, Col: 24.`
```
expression=Add(
    this=CurrentDate(),
    expression=Interval(
        this=Literal(this=1 day 1 hour, is_string=True),
        unit=Var(this=AND)
    )
)
```

**Official Documentation**
https://www.postgresql.org/docs/current/functions-datetime.html

**Comment by fuglaeff** [comment]
One more example that has the expected result, but strange (for postgres) syntax
```sql
select *
from table
where 
    some_column >= current_date + (interval '1 day 1 hour')
    and some_another_column is True;
```

**Comment by VaggelisD** [comment]
@ankur334 Feel free to take a stab at it if that's what you mean, thank you!

**Comment by ankur334** [comment]
Sure @georgesittas and @VaggelisD I am looking into this. I hope to solve it. I will inform the team if I get stuck somewhere

**Comment by VaggelisD** [comment]
Really appreciate it @ankur334, don't hesitate to ping us on slack for quicker iterations.
