### ISSUE TITLE
Parsing DuckDB escape string literals throws error

### ISSUE THREAD

**Issue by LennartH** [tobymao/sqlglot#4496]
Trying to parse escape string literals like `E'\n'` fails with `sqlglot.errors.ParseError: Invalid expression / Unexpected token`. Can be worked around by using character codes and string concatenation.

**Fully reproducible code snippet**
```python
import sqlglot

sql = r"SELECT E'\n'"
ast = sqlglot.parse_one(sql, dialect="duckdb")
print(repr(ast))
```

**Official Documentation**
- Docs for escape string literals: https://duckdb.org/docs/sql/data_types/literal_types.html#escape-string-literals
- General info about how to handle special characters: https://duckdb.org/docs/sql/data_types/text#strings-with-special-characters

**Comment by georgesittas** [comment]
@VaggelisD we probably need to add `BYTE_STRINGS` in DuckDB too, similar to Postgres.
