### ISSUE TITLE
[Snowflake] `sqlglot.optimizer.qualify.qualify` does not resolve SELECT columns inside JOINs

### ISSUE THREAD

**Issue by florian-ernst-alan** [tobymao/sqlglot#4502]
Snowflake has a feature that allows using aliases anywhere in a query, including inside JOIN statements:
```sql
-- Here, we use the aliased "birth_year" in the JOIN clause!
SELECT u.id
  , u.birth_date
  , YEAR(u.birth_date) AS birth_year
  , ly.is_leap AS birth_year_is_leap
FROM users u
JOIN leap_years ly ON birth_year = ly.year

```

This is a [well-known feature](https://sqlkover.com/cool-stuff-in-snowflake-part-4-aliasing-all-the-things/).

However, `sqlglot.optimizer.qualify.qualify` fails to resolve the `birth_year` column in the `ON` clause, causing `sqlglot.optimizer.optimize` to fail entirely.

**Fully reproducible code snippet**
```py
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify

qualify(parse_one(sql = """
SELECT u.id
     , u.birth_date
     , YEAR(u.birth_date) AS birth_year
     , ly.is_leap AS birth_year_is_leap
FROM users u
JOIN leap_years ly ON birth_year = ly.year
""", dialect="snowflake"), schema=None)

# > sqlglot.errors.OptimizeError: Column '"birth_year"' could not be resolved
```

**Official Documentation**

I didn't find any official documentation, but it's a well-known feature. My Account Manager confirmed it's supported, I asked him for official links - he didn't come back to me yet.

**Comment by tobymao** [comment]
@florian-ernst-alan i don't know if one blog post means it's a "well-known feature". a well-known feature generally has readily available docs as well. no one else has commented on this particular use case and it's pretty non-standard. so this seems more niche than "well-known".

happy to accept a PR for this but we won't be prioritizing this for now

**Comment by florian-ernst-alan** [comment]
@tobymao While I understand challenging the "well-known" part of my issue, it's still a supported feature.

I found the documentation [here](https://docs.snowflake.com/en/sql-reference/sql/select#usage-notes):
> In many cases, when you use a column alias for an expression (i.e. expr AS col_alias) in other parts of the same query (in JOIN, FROM, WHERE, GROUP BY, other column expressions, etc.), the expression is evaluated only once.

> However, note that in some cases, the expression can be evaluated multiple times, which can result in different values for the alias used in different parts of the same query.

It clearly state column aliases can be used in any part of the query.

I'll see if I can open a PR.
