### ISSUE TITLE
simplify_parens fails to remove unnecessary parentheses

### ISSUE THREAD

**Issue by mrdkucher** [tobymao/sqlglot#4507]
Simplify parens does not remove redundant parentheses inside an aggregation, see below for the example:

**Before you file an issue**
-  [x] Make sure you specify the "read" dialect eg. `parse_one(sql, read="spark")`
-  [x] Make sure you specify the "write" dialect eg. `ast.sql(dialect="duckdb")`
- [x] Check if the issue still exists on main

**Fully reproducible code snippet**
Please include a fully reproducible code snippet or the input sql, dialect, and expected output.
```python
import sqlglot
from sqlglot.optimizer import simplify

a = sqlglot.parse_one("SELECT SUM((x)) from table", dialect="snowflake")
b = sqlglot.parse_one("SELECT SUM(x) from table", dialect="snowflake")
simple_a = simplify.simplify_parens(a).sql(dialect="snowflake")
simple_b = simplify.simplify_parens(b).sql(dialect="snowflake")

if simple_a != simple_b:
    print(simple_a)
    print(simple_b)
    raise ValueError
```
Output:
```
SELECT SUM((x)) FROM table
SELECT SUM(x) FROM table
```

**Official Documentation**
[simplify_parens](https://sqlglot.com/sqlglot/optimizer/simplify.html#simplify_parens)

**Comment by tobymao** [comment]
you are only supposed to use the top level method, simplify, otherwise there's no traversal

**Comment by tobymao** [comment]
this is an edge case done for safety reasons to make sure that any references in the group by are not optimized

**Comment by mrdkucher** [comment]
Ok thanks for clarifying, I'll work around the edge case on my own.
