### ISSUE TITLE
Invalid syntax for Redshift:  AS REAL(8)

### ISSUE THREAD

**Issue by RedTailedHawk** [tobymao/sqlglot#4508]
I'm building a parse tree that includes selecting from a derived table that has its own SQL, which I then just include natively in the parse tree.

```
SELECT
    b.proud_to_order_by_name::float(8)
```

When SQLGlot then generates the SQL for Redshift, it's doing this:

```
SELECT
    CAST(b.proud_to_order_by_name AS REAL(8)),
```

But Redshift throws an exception:  `com.amazon.redshift.util.RedshiftException: ERROR: syntax error at or near "(" in context "proud_to_order_by_name AS REAL("`

It seems to be happy when I run the SQL manually with just `AS REAL`.

Let me know, thanks.

**Comment by georgesittas** [comment]
@VaggelisD looks like `REAL` and `DOUBLE PRECISION` can't have a precision specified for them.

**Comment by RedTailedHawk** [comment]
Thanks for fixing.  Should I look for it in the next release on pypi.org?

**Comment by georgesittas** [comment]
Yep

**Comment by RedTailedHawk** [comment]
Looks like it's not fixed in `sqlglot 26.0.1`.  Can you please confirm?

**Comment by RedTailedHawk** [comment]
Looks like it's not fixed in `26.2.1` either.  Any plans to fix?

**Comment by georgesittas** [comment]
Hey @RedTailedHawk, can you share the exact code you're running?

**Comment by RedTailedHawk** [comment]
```
from sqlglot import parse_one

dialect = "redshift"

sql = """
SELECT proud_to_order_by_name::float(8)
FROM test 
"""

parse_tree = parse_one(sql, dialect=dialect)

# print(repr(parse_tree))

sql = parse_tree.sql(dialect, pretty = True, pad = 4)

print(sql)
```

Prints:

```
SELECT
    CAST(proud_to_order_by_name AS DOUBLE PRECISION(8))
FROM test
```

**Comment by RedTailedHawk** [comment]
So it was fixed on `main`?  If so, great!  I'll wait for the next release.

**Comment by georgesittas** [comment]
This should've been fixed for quite some time now. Maybe you're using an outdated installation, make sure to clear caches etc.

**Comment by RedTailedHawk** [comment]
But `FLOAT(8)` is incorrect, as I posted out originally.  So was not fixed?

**Comment by RedTailedHawk** [comment]
It's working, thank you.
