### ISSUE TITLE
Tokenizer error on Jinja code (from a dbt project) with escape

### ISSUE THREAD

**Issue by github-christophe-oudar** [tobymao/sqlglot#4521]
The issue failed through `sqlmesh plan` using BigQuery dialect.

Snippet:

Here's the macro that fails tokenization
```
{#-- retrieve the projects list --#}
{% macro project_list() %}
  {% set projects = var('input_gcp_projects', []) %}
  {% if projects is iterable and projects is not string %}
     {{ return(projects) }}
  {#-- check if it's the string and it contains a "," --#}
  {% elif projects is string %}
     {% set projects_replaced = projects | replace("'", "\"") %}
     {% set json = fromjson('{"v":' ~ projects_replaced ~ '}') %}
    {{ return (json['v']) }}
  {% else %}
    {{ exceptions.raise_compiler_error("Invalid `input_gcp_projects` variables. Got: " ~ input_gcp_projects) }}
  {% endif %}
{% endmacro %}
```

The `replace("'", "\"")` is failing as it fails to identify the escape on `"` thus thinking then that there is no closing `"`.

The workaround so far is to use:  `replace("'", '"')` but previous version works fine with Jinja.

For reference the "fix" PR on my end:
https://github.com/bqbooster/dbt-bigquery-monitoring/pull/89/files#diff-e494487d702fa3787150d12301718ac3c0cfd54ab9b5480b8c394472fda7c21d

**Comment by georgesittas** [comment]
I think this is more of a SQLMesh issue, SQLGlot doesn't handle jinja delimiters. Would you mind replicating it over there? We'll take a look soon.

**Comment by github-christophe-oudar** [comment]
Sorry for misunderstanding that the error was on SQLGlot end!
I thought it was the library taking care of the Jinja part as well.

Thanks a lot for the swift fix 👏
