### ISSUE TITLE
BigQuery parser mistakes `YEAR` UDFs for a standard function in `Standard SQL`

### ISSUE THREAD

**Issue by github-christophe-oudar** [tobymao/sqlglot#4522]
I wrote few SQL UDFs that are named YEAR/MONTH/DAY/HOUR/MINUTE in BigQuery and the parser failed as the number of arguments didn't fit the expected ones.

I checked those functions don't in BigQuery standard SQL. Then I had to rename my functions to ensure it doesn't collide with existing parser.
What's tricky is that [the functions **exist in BigQuery Legacy SQL**](https://cloud.google.com/bigquery/docs/reference/legacy-sql#hour) and I think it's why it was implemented like this.
However the code is still valid for Standard SQL so I guess you would have to accept any parameter for those functions to avoid parser error even if it makes it less precise for Legacy SQL (which is meant to disappear).

Here's my workaround change:
https://github.com/bqbooster/dbt-bigquery-monitoring/pull/89/files#diff-27c7e17690300b0dfe5ac5ff29acdb74cf6a7fa2a98aa8b48ed63104997fa9a8

**Comment by georgesittas** [comment]
@tobymao I think this exposes a more general issue: UDFs can clash with `Func`s, e.g. if the number of arguments is different (as Christophe shows here). Perhaps a workaround is to be more lenient when parsing functions, so that if the function's `arg_types` & `_is_var_len_args` doesn't match what we have in `args`, we'll instantiate an `Anonymous`.

Thoughts?

**Comment by tobymao** [comment]
perhaps we could make a meta argument for it, but def wouldn't make the parser more lenient generically. if these exist in bigquery legacy, should we add support for it?

**Comment by tobymao** [comment]
that's the whole point of of the argument check, to raise an error, otherwise you could do error_level ignore

**Comment by georgesittas** [comment]
Yep, but e.g. sqlmesh users can't control that option today. Additionally, and most importantly, if a function is "known", i.e. we have a builder for it in `FUNCTIONS`, then that may drop additional arguments that it is not expecting (see `from_arg_list`). So UDF calls would break in that case, regardless of the error level.

**Comment by github-christophe-oudar** [comment]
Thanks for the progress on the issue! (I missed the notifications)
I think the path you took is pretty good!
I also think that Google legacy SQL is meant to die so that argument checking it has little value for most users.
What I would suggest would be parse it as an anonymous function unless there's a `#legacySQL` at the top of the query for the context (see https://cloud.google.com/bigquery/docs/reference/legacy-sql).
