### ISSUE TITLE
DATETRUNC not supported for dialect="tsql"

### ISSUE THREAD

**Issue by rajat-wisdom** [tobymao/sqlglot#4531]
**Description**
The issue exists in the latest version 26.0.0. DATETRUNC is an allowed function in T-SQL. Please see link below. However, it is not supported in sqlglot. Please see snippet below.

**Fully reproducible code snippet**
```python
parse_one("DATETRUNC(month, closed_date)", dialect="tsql")
Anonymous(
  this=DATETRUNC,
  expressions=[
    Column(
      this=Identifier(this=month, quoted=False)),
    Column(
      this=Identifier(this=closed_date, quoted=False))])`
``` 
**Expected output**
A parse tree similar to what we get for other dialects like redshift.
```python
parse_one("DATE_TRUNC(month, closed_date)", dialect="redshift")
TimestampTrunc(
  this=Column(
    this=Identifier(this=closed_date, quoted=False)),
  unit=Var(this=MONTH))
``` 
**Official Documentation**
[DATETRUNC in T-SQL](https://learn.microsoft.com/en-us/sql/t-sql/functions/datetrunc-transact-sql?view=sql-server-ver16)

**Comment by geooo109** [comment]
Thank you @rajat-wisdom for pointing it out.
I am working on it.
