### ISSUE TITLE
merge function broken in sqlglot v26.0.0.

### ISSUE THREAD

**Issue by zerodarkzone** [tobymao/sqlglot#4541]
Hi,

The latest release of sqlglot (0.26) broke the [merge](https://sqlglot.com/sqlglot/expressions.html#merge) function.

When using `sqlglot==25.34.1` the following code snippet worked as expected:
``` python
import sqlglot
from sqlglot import exp

target = exp.to_table("foo")
src = exp.to_table("bar")

merge_expr = exp.merge(
    exp.When(
        matched=True,
        source=False,
        condition="foo.id = bar.id",
        then=exp.Update(expressions=[exp.EQ(this=exp.column("foo.id"), expression=exp.column("bar.id"))]),
    ),
    into=target,
    using=src,
    on=exp.EQ(this=exp.column("foo.id"), expression=exp.column("bar.id")), 
)
```
When printing the result i'm getting:
``` python
Merge(
  this=Table(
    this=Identifier(this=foo, quoted=False)),
  using=Table(
    this=Identifier(this=bar, quoted=False)),
  on=EQ(
    this=Column(
      this=Identifier(this=foo.id, quoted=True)),
    expression=Column(
      this=Identifier(this=bar.id, quoted=True))),
  expressions=[
    When(
      matched=True,
      source=False,
      condition=foo.id = bar.id,
      then=Update(
        expressions=[
          EQ(
            this=Column(
              this=Identifier(this=foo.id, quoted=True)),
            expression=Column(
              this=Identifier(this=bar.id, quoted=True)))]))])
```
Which translates to the following sql code:
``` sql
MERGE INTO foo
USING bar
ON "foo.id" = "bar.id"
WHEN MATCHED AND foo.id = bar.id THEN UPDATE SET "foo.id" = "bar.id"

```

Now when using `sqlglot==26.0.0`
I'm getting the following:
``` python
Merge(
  this=Table(
    this=Identifier(this=foo, quoted=False)),
  using=Table(
    this=Identifier(this=bar, quoted=False)),
  on=EQ(
    this=Column(
      this=Identifier(this=foo.id, quoted=True)),
    expression=Column(
      this=Identifier(this=bar.id, quoted=True))),
  whens=Whens(
    ))
```

Which translates to the following sql code:
``` sql
MERGE INTO foo
USING bar
ON "foo.id" = "bar.id"
```
As you see, the generated SQL code is incorrect.

The issue is related to the following code:
![image](https://github.com/user-attachments/assets/75a82c6e-d57c-458a-8a51-7ac11d54d3a8)
The expressions list is left empty when you pass a list of `When` expressions instead of a string. This can be solved by wrapping the list of `When` expressions inside a `Whens` but this is a _breaking_ change and it is not explained anywhere in the documentation.

**Official Documentation**
[Please include links to official SQL documentation related to your issue.](https://sqlglot.com/sqlglot/expressions.html#merge)

**Comment by georgesittas** [comment]
This change was [intentional](https://github.com/tobymao/sqlglot/commit/051c6f085e426dbcdda3fbc324a180ada268355f). We have a changelog, but it looks like the commit title was misformed and unfortunately it wasn't picked up for that release.
