### ISSUE TITLE
merge function broken

### ISSUE THREAD

**Issue by zerodarkzone** [tobymao/sqlglot#4543]
Hi, 
I'm re opening this issue https://github.com/tobymao/sqlglot/issues/4541 because it was closed without discussion.

This is the function definition in the docs.

![Screenshot_2024-12-22-11-36-16-804_com android chrome](https://github.com/user-attachments/assets/09886e72-9a0a-4aa0-bc1d-9cf115f55c75)

That API is broken, You cannot pass several `when` expressions but the docs says you should.

I know the change to the `Merge` class was intentional but according to the docs and the function definition the `merge` function is in fact broken.

**Comment by georgesittas** [comment]
Thanks for following up, I replied hastily and missed this.
