### ISSUE TITLE
Snowflake Dialect doubles backslashes when executing REGEXP_LIKE query

### ISSUE THREAD

**Issue by danielvaisman** [tobymao/sqlglot#4548]
Hi! 🙂

I upgraded SQLGlot version from 20.1.0 to 26.0.1.
It seems that when using REGEXP_LIKE with Snowflake dialect it escapes backslashes, so I get Snowflake Programming error when I try to execute it.

Using 26.0.1 :
```
from sqlglot import parse_one, Dialects
query = "SELECT * FROM table WHERE REGEXP_LIKE(CAST(field_name AS TEXT), '.*(\\b|_)(\file_name.exe)(\\b|_).*', 'i')"
parsed_query = parse_one(query, read=Dialects.SNOWFLAKE.value)
print(parsed_query.sql(dialect=Dialects.SNOWFLAKE.value))
```

![image](https://github.com/user-attachments/assets/70bde3df-17bd-4f93-8271-7d3a0f05ffe0)
Using 20.1.0 :
<img width="977" alt="Screenshot 2024-12-26 at 9 40 06" src="https://github.com/user-attachments/assets/e81dd1dc-b107-4e75-84fb-96382f7f2c80" />

I would appreciate any help, thank you!

**Comment by georgesittas** [comment]
Hey, can you share the exact query you're trying to execute against Snowflake? The query you shared contains `\file_name.exe` within a python string, which makes me believe this is a user error, i.e. the backslashes haven't been encoded properly.

**Comment by georgesittas** [comment]
Closing this until more details are provided.

**Comment by danielvaisman** [comment]
Sorry for the late response.

The query I am trying to execute against Snowflake does contain backslashes. Previously, when using SQLGlot 20.1.0, we sent the user’s input with backslashes and used REGEXP_LIKE on it with a specific structure
('.*(\\b|_)(<USER_INPUT>)(\\b|_).*')
This worked well with SQLGlot 20.1.0.

However, it seems that the escape value has been removed. Now, the raw query includes additional escaping, which in our example causes the error:
Invalid regular expression: '.*(\b|_)(\file_name.exe)(\b|_).*', invalid escape sequence: \f.

This issue occurs with every backslash-like expression.

**Comment by georgesittas** [comment]
Hey, thanks for the follow-up. Can you format the query you shared above using backticks so I don't miss any characters? I'll try to reproduce this. Feel free to edit the message if you want.

**Comment by georgesittas** [comment]
@danielvaisman I meant sharing the exacty SQL `like this` so the text is not formatted in italics like in the above [message](https://github.com/tobymao/sqlglot/issues/4548#issuecomment-2565369713).

**Comment by danielvaisman** [comment]
Thank you! I found our problem.
<img width="927" alt="Screenshot 2024-12-31 at 11 42 04" src="https://github.com/user-attachments/assets/92a1a6a9-b6cb-40ec-a6ee-6229b6efc52a" />
It is regarding to Snowflake escaping.
Thank you again!
