### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by jonathanstegall** [tobymao/sqlglot#457]
Just wondering about a changelog. I've seen a lot of new tags lately, but it's not clear to me what backward-compatible changes there might be, if any; or really what any of the changes are.

**Comment by tobymao** [comment]
usually the changes won't affect 99% of users, only if you're digging into the internals of sqlglot or doing subclasses will the version bumps break your code.

i'll think about adding change logs for minor / major version bumps.

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/blob/main/CHANGELOG.md
