### ISSUE TITLE
Adding Trino parser

### ISSUE THREAD

**Issue by OneRaynyDay** [tobymao/sqlglot#48]
Trino and presto are now different and are likely to diverge in subsequent development: https://trino.io/blog/2020/12/27/announcing-trino.html. Is it possible to add Trino as a Dialect? I'm thinking since Trino's development cycle appears to be much faster (they are hosted by a startup called Starburst) compared to facebook, we should either copy the parser rules for Presto -> Trino and carry forward with Trino, or inherit from Presto. I think with the way the Dialect classes are designed it makes more sense to do a copy.

**Comment by tobymao** [comment]
do you have a list of differences?

**Comment by tobymao** [comment]
i've added trino dialect as a subclass of presto, please let me know what the differences are

**Comment by OneRaynyDay** [comment]
Hi Toby,

You can find the differences from their ANTLRv4 grammars at: https://raw.githubusercontent.com/prestodb/presto/master/presto-parser/src/main/antlr4/com/facebook/presto/sql/parser/SqlBase.g4 and https://raw.githubusercontent.com/trinodb/trino/a2ea77b6f4f0f208b00ca4c6d2e99eb6814538b8/core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4.

There is a nontrivial amount of grammar added to Trino (roughly 100 lines). One thing I can see is the following:

- `FETCH FIRST N ROWS`
- `WINDOW` expressions
