### ISSUE TITLE
BigQuery INFORMATION_SCHEMA views not parsed properly?

### ISSUE THREAD

**Issue by ehdr** [tobymao/sqlglot#489]
BigQuery has [INFORMATION_SCHEMA views](https://cloud.google.com/bigquery/docs/information-schema-intro#project_qualifier) that don't seem to parse properly using sqlglot?

For example: `sqlglot.parse_one("SELECT * FROM project.dataset.INFORMATION_SCHEMA.TABLES", read="bigquery")` gives:
```
(SELECT expressions:
  (STAR ), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: TABLES, quoted: False), db:
      (IDENTIFIER this: INFORMATION_SCHEMA, quoted: False), catalog:
      (IDENTIFIER this: dataset, quoted: False))))
```

which leaves out the `project` part completely. Not quite sure what the correct behavior would be though!

**Comment by GeorgeSittas** [comment]
Maybe, we could parse this into:

```
(SELECT expressions:
  (STAR ), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: TABLES, quoted: False), db:
      (IDENTIFIER this: dataset.INFORMATION_SCHEMA, quoted: False), catalog:
      (IDENTIFIER this: project, quoted: False))))
```

From what I understand, qualifying INFORMATION_SCHEMA with a db or region simply results in a new db, right? @tobymao

**Comment by barakalon** [comment]
Didn't we used to parse an arbitrary number of Dot expressions?

Something like...
```
(SELECT expressions:
  (STAR ), from:
  (FROM expressions:
    (DOT this:
      (IDENTIFIER this: project, quoted: False), expressions:
      (TABLE this:
        (IDENTIFIER this: TABLES, quoted: False), db:
        (IDENTIFIER this: INFORMATION_SCHEMA, quoted: False), catalog:
        (IDENTIFIER this: dataset, quoted: False))))
```

**Comment by tobymao** [comment]
that's done for columns but i don't think it's done for tables. so the fix here is to add the arbitrary dot modifier to table names as well

**Comment by GeorgeSittas** [comment]
So is the following syntax tree correct?

```python
>>> sqlglot.parse_one("SELECT INFORMATION_SCHEMA.TABLES.TABLE_NAME")
(SELECT expressions:
  (DOT this:
    (COLUMN this:
      (IDENTIFIER this: TABLES, quoted: False), table:
      (IDENTIFIER this: INFORMATION_SCHEMA, quoted: False)), expression:
    (IDENTIFIER this: TABLE_NAME, quoted: False)), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: TABLES, quoted: False), db:
      (IDENTIFIER this: INFORMATION_SCHEMA, quoted: False))))
```

The alternative form I had in mind given the context is:

```python
>>> sqlglot.parse_one("SELECT INFORMATION_SCHEMA.TABLES.TABLE_NAME")
(SELECT expressions:
  (COLUMN this:
    (IDENTIFIER this: TABLE_NAME, quoted: False), table:
    (IDENTIFIER this: TABLES, quoted: False), db:
    (IDENTIFIER this: INFORMATION_SCHEMA, quoted: False)), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: TABLES, quoted: False), db:
      (IDENTIFIER this: INFORMATION_SCHEMA, quoted: False))))
```

**Comment by barakalon** [comment]
I don't think it makes sense for a column to have a `db`.
Columns select from the tables available in the current scope. 

But I think the matter at hand is Table expressions, not Column expressions.

Tables allow for `catalog`, `db`, and `table`. Seems like Bigquery allows for further namespacing, which I don't think is standard. So we want to gracefully handle this case by nesting the table in an arbitrary number of Dot expressions.
