### ISSUE TITLE
What is the expected syntax tree for quoted table references in BigQuery?

### ISSUE THREAD

**Issue by ehdr** [tobymao/sqlglot#490]
Should quoted table references in BigQuery be parsed into their components or not? (More of a questions than an issue, since I don't know the intended behavior in general.)

Illustrating with some examples: `sqlglot.parse_one("SELECT * FROM project.dataset.table", read="bigquery")` gives:
```
(SELECT expressions:
  (STAR ), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: table, quoted: False), db:
      (IDENTIFIER this: dataset, quoted: False), catalog:
      (IDENTIFIER this: project, quoted: False))))
```

, but when the table reference is quoted like ```sqlglot.parse_one("SELECT * FROM `project.dataset.table`", read="bigquery")``` we get:
```
(SELECT expressions:
  (STAR ), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: project.dataset.table, quoted: True))))
```

i.e. no breakdown into `this`, `db` and `catalog` as above. I think I would have expected the following result instead (i.e. same breakdown, but each identifier `quoted: True` instead)?
```
(SELECT expressions:
  (STAR ), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: table, quoted: True), db:
      (IDENTIFIER this: dataset, quoted: True), catalog:
      (IDENTIFIER this: project, quoted: True))))
```

This can also give results that I think are arguably incorrect, like ```sqlglot.parse_one("SELECT * FROM `project.dataset`.table", read="bigquery")``` which gives:
```
(SELECT expressions:
  (STAR ), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: table, quoted: False), db:
      (IDENTIFIER this: project.dataset, quoted: True))))
```

and ```sqlglot.parse_one("SELECT * FROM project.`dataset.table`", read="bigquery")``` which gives:
```
(SELECT expressions:
  (STAR ), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: dataset.table, quoted: True), db:
      (IDENTIFIER this: project, quoted: False))))
```

etc.

**Comment by tobymao** [comment]
if you quote something the whole thing a single identifier. so “a.b”.c means table “a.b” column c

**Comment by ehdr** [comment]
Ok, got it. But BigQuery will still parse ```FROM `a.b`.c ``` as referring to the table `c`, living in the dataset `b` in project `a` (not table `c` living in dataset `a.b`). So the intention is not that sqlglot `db` should always correspond to the BigQuery "dataset" concept, and `catalog` to BigQuery "projects"?

(I'm new to sqlglot so may be misunderstanding the intentions - sorry in advance if that's the case!)

**Comment by tobymao** [comment]
we try to match the engine. but that bigquery syntax makes no sense, so i’m not inclined to match it.

**Comment by barakalon** [comment]
What if parsers had a post_transformer and generators a pre_transformer?
I think this would be simple to implement as a post_transformer of the Bigquery dialect.
