### ISSUE TITLE
TSQL-specific CONVERT() can't be parsed

### ISSUE THREAD

**Issue by alieh-rymasheuski** [tobymao/sqlglot#493]
Example:
```python
print(sqlglot.parse_one("SELECT convert([varchar](10),convert([datetime],[My Date],105),23)"))
```
According to [the docs](https://learn.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver16), this means the following: 
1. Convert `[My Date]` to datetime, using date format `dd-mm-yyyy`.
2. Convert the result to varchar of length 10, using date format `yyyy-mm-dd`.

This issue has multiple aspects:
- `sqlglot` doesn't seem to allow quoted type names but they appear to be accepted by real-world DBMSs (this example works in TSQL; `select '2022-09-27'::"date"` works in Postgres)
- the parser for `CONVERT()` expects [MySQL](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_convert) semantics (`convert(value, type)`), but TSQL inverts the order of parameters (`convert(type, value)`)
- `_parse_convert` always produces `exp.Cast`, but the semantics of the example actually mean `exp.StrToTime` and `exp.TimeToStr`.

**Comment by alieh-rymasheuski** [comment]
Thank you @tobymao!

**Comment by alieh-rymasheuski** [comment]
@tobymao, what about TSQL-specific third parameter of `CONVERT()`?
```tsql
-- CONVERT Syntax:  
CONVERT ( data_type [ ( length ) ] , expression [ , style ] )  
```
This parameter is the primary reason why I think we may want to produce `StrToTime` or `TimeToStr` when parsing the `CONVERT()` function.

**Comment by alieh-rymasheuski** [comment]
There is an exhaustive list linked in the docs above: https://learn.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver16

Some examples:


|Without century (yy) | With century (yyyy) | Standard | Input/Output (3)
|--|--|--|--
|1 | 101 | U.S. | 1 = mm/dd/yy 101 = mm/dd/yyyy
|4 | 104 | German | 4 = dd.mm.yy 104 = dd.mm.yyyy
|5 | 105 | Italian | 5 = dd-mm-yy 105 = dd-mm-yyyy
|- | 23 | ISO8601 | yyyy-mm-dd

**Comment by tobymao** [comment]
given that convert can do weird stuff like money and xml styles, i think for tsql it needs to stay convert, but i don't have the bandwidth to add this. again happy to help with a PR though.
