### ISSUE TITLE
add sqloxide benchmarks

### ISSUE THREAD

**Issue by wseaton** [tobymao/sqlglot#5]
From the README:

> It is currently the fastest Python SQL parser.

I have [python bindings to sqlparser-rs](https://github.com/wseaton/sqloxide), would you be open to adding these to the benchmark suite? I went ahead and added your library to [my benchmarks](https://github.com/wseaton/sqloxide#benchmarks) and it indeed compares favorably to the other pure-python implementations. 

Not to take away from your awesome project, it does a lot of other cool things that simple bindings cannot!

**Comment by tobymao** [comment]
this is great thank you so much, i didn't know this one existed

**Comment by brunorpinho** [comment]
@tobymao @wseaton Both your projects are awesome and I want to use both **sqlglot** for it's beautiful API and **sqloxide** for it's blazing fast parsing using rust. 

Does it makes sense to use **sqlglot** on top of a "sqloxide engine/parser"?

**Comment by tobymao** [comment]
sqlglot's core is a handwritten python based parser. we can't just use sqlparser-rs. you'd have to basically rewrite sqlglot in rust.

**Comment by wseaton** [comment]
To add to @tobymao's comment, while there is some very basic feature overlap, `sqlparser-rs` also has API stability properties that are not desirable for a transpiler/formatter. Different projects with different design considerations and goals :)
