### ISSUE TITLE
Clickhouse server accepts "ceil(x, y)" but sqlglot parsing fails

### ISSUE THREAD

**Issue by scottpersinger** [tobymao/sqlglot#505]
Another Clickhouse dialect question:

`sqlglot.parse_one("select ceil(1, 2)", read='clickhouse')`

throws:

`sqlglot.errors.ParseError: The number of provided arguments (2) is greater than the maximum number of supported arguments (1)`

But is accepted by actual Clickhouse:

    :) select ceil(1, 2)
    returns "1"

I guess because `ceil(x)` is part of the SQL standard. Is it possible to override this behavior or specialize it in the Clickhouse dialect?

**Comment by tobymao** [comment]
what does ceil(1,2) mean?

**Comment by scottpersinger** [comment]
Check out the docs: https://clickhouse.com/docs/en/sql-reference/functions/rounding-functions/#floorx-n

floor/ceil etc... take an optional N parameter. 

But it's sort of not the point - the point is that that SQL is valid for Clickhouse but won't be parsed by sqlglot.

**Comment by tobymao** [comment]
i understand that it can be parsed by clickhouse, but my question is relevant because i need to understand what to name the new parameter.

this is fixed now in the latest main
