### ISSUE TITLE
Are we really parsing CREATE statement the right way?

### ISSUE THREAD

**Issue by zeninpalm** [tobymao/sqlglot#52]
Hi Toby,

I'm trying to parse "CREATE OR REPLACE TEMPORARY VIEW ...", but I noticed that in generator.py, you wrote `CREATE{temporary}{replace}`. I think that's a typo because then the generated SQL will be "CREATE TEMPORARY OR REPLACE ...".

And in parser.py, you wrote
```python
def _parse_create(self):
    temporary = self._match(TokenType.TEMPORARY)
    replace = self._match(TokenType.OR) and self._match(TokenType.REPLACE)
```

I guess it should be 
```python
def _parse_create(self):
    replace = self._match(TokenType.OR) and self._match(TokenType.REPLACE)
    temporary = self._match(TokenType.TEMPORARY)
```

Please let me if I understand your code correctly 😄

**Comment by tobymao** [comment]
thanks for the report, fixed

**Comment by zeninpalm** [comment]
Great @tobymao
