### ISSUE TITLE
sqlglot seems stateful and not thread-safe

### ISSUE THREAD

**Issue by jarnoux** [tobymao/sqlglot#520]
When using sqlglot from multiple threads (like in a regular uwsgi server), surprises arise in from things like these: https://github.com/tobymao/sqlglot/blob/3e7bcc127dd744992ee3059fa280f5002ef19bc8/sqlglot/parser.py#L513

**Comment by barakalon** [comment]
Correct - a Parser instance is not thread-safe. They’re also very cheap to instantiate.

Can you give more details on how you’re invoking sqlglot? Perhaps you should call “parse” whenever you need it - that is, don’t share Parser instances across threads.

**Comment by jarnoux** [comment]
```
    transformed_tree = sqlglot.parse_one(query).transform(transformer)
    [transformed] = sqlglot.transpile(transformed_tree.sql(), write='postgres')
```

Undeterministically breaks on the second line with IndexErrors and unknown token issues.

Surrounding those lines with a `threading.Lock` solves the issue.

**Comment by tobymao** [comment]
are you running both of those statements in the same worker?

**Comment by jarnoux** [comment]
In the same process, in the same thread, yes. I run a single-worker multi-thread uwsgi server.

**Comment by tobymao** [comment]
what version of sqlglot are you running? can you try on the latest?

**Comment by jarnoux** [comment]
6.1.0. Ok, trying latest now

**Comment by tobymao** [comment]
this was fixed in v6.2.0, feel free to comment if it's not fixed once you've updated

**Comment by tobymao** [comment]
```python

from sqlglot import transpile
from concurrent.futures import ThreadPoolExecutor

sqls = [
    f"select {i} AS a_{i}"
    for i in range(0, 1000)
]

def parse(sql):
    return transpile(sql)[0]

with ThreadPoolExecutor() as pool:
    print(list(pool.map(parse, sqls))[0])
```

works no issues

**Comment by jarnoux** [comment]
Yes, looks like it's fixed. Thanks for the quick support!
