### ISSUE TITLE
[Hive] feature request - add support for Hive sql

### ISSUE THREAD

**Issue by bang-chuang** [tobymao/sqlglot#562]
It would be great to add support for load and insert directory in DML statements ([Hive doc](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DML#LanguageManualDML-Writingdataintothefilesystemfromqueries)). This is useful for specifying things like data flow info.

like
`insert overwrite local directory "/home/xxx" row format delimited fields terminated by "\001" select * from a;`
and
`load data local inpath '/home/xxx' overwrite into table a;`

**Comment by tobymao** [comment]
will look into this soon
