### ISSUE TITLE
Support for Spark SQL literals with postfix to indicate datatype (e.g. `2Y` or `123.08BD`)

### ISSUE THREAD

**Issue by RobinL** [tobymao/sqlglot#58]
`sqlglot` does not yet support Spark SQL queries that include literals that are specified with a postfix character to indicate the datatype.

I'd be open to trying to write a PR to implement this functionality. If you'd like me to attempt this, it'd be useful to have some high level pointers about how you think it would be best to implement. (I've not written a tokeniser or parser before, but stepping through your code, I think I have a reasonable understanding of how it works).

## Spark - syntax and example of problem

See [here](https://spark.apache.org/docs/latest/sql-ref-literals.html#numeric-literal) for the Spark language reference. For example a postfix of 'Y' is a shorthand way of indicating a `TINYINT` literal, so you can write `2Y` rather than `cast(2 as tinyint)`

```
import sqlglot
sql = '2Y'
sqlglot.parse_one(sql, read="spark").sql(dialect="spark")
```

Results in:

```
'2 as Y'
```

When it should result in either:

- `CAST(2 AS TINYINT) ` or
- `CAST(2 AS BYTE) ` or
- `2Y`

To give an example of how this can affect the result:

```

from pyspark.context import SparkContext
from pyspark.sql import SparkSession
sc = SparkContext.getOrCreate()
spark_session = SparkSession(sc)
sql = "select 2Y"
print(spark_session.sql(sql).schema)
sql_parsed = sqlglot.parse_one(sql, read="spark").sql(dialect="spark")
print(spark_session.sql(sql_parsed).schema)
```

Results in:

```
StructType(List(StructField(2,ByteType,false)))
StructType(List(StructField(Y,IntegerType,false)))
```

### Where this appears in the Spark codebase

I've also looked in the Spark codebase. I believe [this](https://github.com/apache/spark/blob/4c58f12132bf10963102c7f3454e6ac886bbe966/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4) may be the code to parse the literal syntax, and the syntax is also referenced [here](https://github.com/apache/spark/blob/e8e5785f02ae7d44e0553b82c742e1eba4ca2082/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/literals.scala#L449), as well as in various parts of the test suite like [here](https://github.com/apache/spark/blob/0494dc90af48ce7da0625485a4dc6917a244d580/sql/core/src/test/resources/sql-tests/inputs/literals.sql).

## Literals in other SQL flavours

I've done some research to understand how widespread the postfix syntax is, and to get a sense of what approach may be best to tokenising/parsing these queries. I recognise some of these flavours are not supported by `sqlglot`. The intention is to provide some examples that may help decide the most sensible appraoch to tokenising/parsing.

### DuckDB

I don't think DuckDB supports postfixes. In fact, it parses postfixes in a surprising way;

DuckDB evaluates syntax like:
`select 0.1d`
to the table:

| d   |
| --- |
| 0.1 |

i.e. the result is the same as `select 0.1 as d`

Note that the same query in PostGres results in the same result (a column named d with value 0.1). Whereas MySQL and MS SQL Server, and SQLite all give you a syntax error.

### Hive

In Hive, a postfix can be used, much like Spark, documented [here](<https://cwiki.apache.org/confluence/display/hive/languagemanual+types#:~:text=Column%20Types-,Integral%20Types%20(TINYINT%2C%C2%A0SMALLINT%2C%C2%A0INT/INTEGER%2C%C2%A0BIGINT),-Integral%20literals%20are>)

### Postgres

In postgres, the `::` operator is a 'PostgreSQL-style typecast'. This means that you can write things like `select 123::smallint`.

More info in the [docs](https://www.postgresql.org/docs/7.3/sql-syntax.html#:~:text=1.1.2.4.%20Constants%20of%20Other%20Types).

### Oracle

In Oracle it is possible to use postfixes, see [here](https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements003.htm#:~:text=Here%20are%20some%20valid%20floating%2Dpoint%20number%20literals%3A)

### SQLite

Postfixes are not allowed:

```
import sqlite3
conn = sqlite3.connect(':memory:')
c = conn.cursor()
c.execute("select 2Y")
```

### p.s.

Thanks so much for the library.  I'm using it as part of [splink](https://github.com/moj-analytical-services/splink), a FOSS record linkage tool.  At the moment Splink uses Spark as a backend, but I'd like it to be able to support both DuckDB and Spark - `sqlglot` looks pretty ideal for this purpose!!

**Comment by tobymao** [comment]
i think this can b e done having tokens accept a dictionary of postfix -> cast mappings, and then in scan number, we add it in

**Comment by RobinL** [comment]
If you don't mind doing it, yes please (and thank you!).  I think it'd take me quite a long time to figure out and implement in a way that's consistent with the rest of the code base.  

But v. happy to give it a go if you'd prefer!

**Comment by tobymao** [comment]
ok i’ll do it within a couple days

**Comment by RobinL** [comment]
Thanks so much!

**Comment by tobymao** [comment]
@RobinL it's in v1.17.0, try it out
