### ISSUE TITLE
Please package the test suite to the tarball

### ISSUE THREAD

**Issue by mcepl** [tobymao/sqlglot#585]
I would like to fix packaging for OpenSUSE, but your release tarball does not contain the tests directory. Could you please distribute them as well?

**Comment by tobymao** [comment]
why would we include the test suite? it’s not needed and it’s quite large due to test data?

**Comment by tobymao** [comment]
it's not really standard practice to package the test suite. closing this for now. happy to discuss further though or find another solution

**Comment by alippai** [comment]
@mcepl are you looking for this? https://github.com/tobymao/sqlglot/tags
It has the tarballs for the releases with tests included

**Comment by mcepl** [comment]
> @mcepl are you looking for this? https://github.com/tobymao/sqlglot/tags It has the tarballs for the releases with tests included

Yes, that’s what I am using right now, but I thought it would be better to make it official.

And yes, @tobymao, I will send you PR.
