### ISSUE TITLE
DataFrame API Automated Testing for New Expressions

### ISSUE THREAD

**Issue by eakmanrq** [tobymao/sqlglot#597]
We want a way to make sure that as new expressions get added to sqlglot that the DataFrame API is also updated to use that expression instead of Anonymous functions. If we had a script that would be part of the test suit that would compare known expressions with currently anonymous functions then it could fail when there is a function that needs to be added to the DataFrame API.

**Comment by tobymao** [comment]
we can probably parse the function and detect if you call invoke anonomyous on it, either that or you'll have to manually decorate each function with a custom decorator
