### ISSUE TITLE
[Postgres[ Parser does not understand table aliases inside join construct

### ISSUE THREAD

**Issue by g-u-t-h-m-a-n** [tobymao/sqlglot#612]
Related to: https://github.com/tobymao/sqlglot/issues/423

The same error occurs as in the issue above when using table aliases inside the parentheses.

So this works (fixed in previous issue):
```
select * from (table1 left join table2 on 1 = 1);
```

But this doesn't:
```
select * from (table1 t1 left join table2 t2 on 1 = 1);
```

```
ParseError: Expecting ). Line 1, Col: 26.
  select * from (table1 t1 left join table2 t2 on 1 = 1)

Invalid expression / Unexpected token. Line 1, Col: 54.
  select * from (table1 t1 left join table2 t2 on 1 = 1)
```

Using sqlglot 8.0.2.

**Comment by GeorgeSittas** [comment]
Sigh, this one's annoying. The parser currently handles these parenthesized [join constructs](https://www.postgresql.org/docs/current/queries-table-expressions.html) by creating a Subquery node with "this" set to the first table in the join chain. I could try handling the case for Alias [here](https://github.com/tobymao/sqlglot/blob/main/sqlglot/parser.py#L1122), but then it'd apply to the whole subquery. The problem only arises when aliasing the first table -- the following works just fine:

```sql
select * from (table1 left join table2 t2 on 1 = 1);
```

One idea is to convert `(table1 t1 left join table2 t2 on 1 = 1)` into a SELECT * expression, but I'm not sure if that's the best way to handle it...

@tobymao any thoughts on this?
