### ISSUE TITLE
Add Support for Filling in Placeholders

### ISSUE THREAD

**Issue by fny** [tobymao/sqlglot#623]
It would be great to be able to perform substitutions on placeholders.

**Comment by fny** [comment]
Just hacked this together for my own project. `#clone()` would also be good addition.

```
    def bindparams(self, **bindparams):
        cloned_expression = sg.parse_one(self.expression.sql()) # clone hack

        for placeholder in cloned_expression.find_all(sg.expressions.Placeholder):
            if placeholder.name in bindparams:
                placeholder.replace(sg.parse_one(str(bindparams[placeholder.name])))

        return Query(self.db,
            cloned_expression
        )
```

**Comment by GeorgeSittas** [comment]
> #clone() would also be good addition.

If I understand correctly what you're suggesting, I think we already have this functionality. You can do `expression.copy()`.

**Comment by fny** [comment]
Truth. Thanks!
