### ISSUE TITLE
TSQL DATEADD function

### ISSUE THREAD

**Issue by jp3477** [tobymao/sqlglot#626]
Hi,
First, I want to say this library is incredible! It will definitely be in my toolbox for years to come.

Is there currently support for transpiling the `DATEADD` function in the TSQL dialect to and from other dialects? I'm currently trying to transpile TSQL code to BigQuery but the output date add function is in the TSQL form `DATEADD (datepart , number , date )` rather than the BigQuery form `DATE_ADD(date_expression, INTERVAL int64_expression date_part)` as I would expect. I attempted to extend the TSQL dialect myself, but have had a bit of trouble. Much help would be appreciated!

**Comment by jp3477** [comment]
Thanks very much for this change @tobymao! That worked like a charm.

There is one more thing that I would like to see added if it's not too much trouble. A mapping from the `GETDATE()` TSQL function to the `CURRENT_DATE()` BigQuery function would be helpful as well. I can open up a new issue ticket if necessary.

**Comment by tobymao** [comment]
added, feel free to make pr's for other issues like this
