### ISSUE TITLE
Updating JSON path 

### ISSUE THREAD

**Issue by anya004** [tobymao/sqlglot#631]
Is there a way to update/replace the json path value  in sqlglot.exp.JSONExtractScalar?

Example, trying to modify the maxSupply:
(JSONEXTRACTSCALAR this:
  (COLUMN this:
    (IDENTIFIER this: lot, quoted: True)), path:
  (LITERAL this: **maxSupply**, is_string: True))

**Comment by GeorgeSittas** [comment]
Yes, for example you can do:
```python
>>> expr
(JSONEXTRACTSCALAR this:
  (COLUMN this:
    (IDENTIFIER this: lot, quoted: True)), path:
  (LITERAL this: maxSupply, is_string: True))
>>>
>>> expr.this.path.replace(exp.Literal.string("foo"))
>>> expr
(JSONEXTRACTSCALAR this:
  (COLUMN this:
    (IDENTIFIER this: lot, quoted: True)), path:
  (LITERAL this: foo, is_string: True))
```
