### ISSUE TITLE
Issue when parsing t-sql query

### ISSUE THREAD

**Issue by arnovkh** [tobymao/sqlglot#640]
trying to extract columns from query
`select 
CONVERT(varchar(10),dt,120)
a from dbo.test` causes an error 
sqlglot.errors.ParseError: Required keyword: 'to' missing for <class 'sqlglot.expressions.Cast'>. Line 3, Col: 21.

**Comment by GeorgeSittas** [comment]
You're probably not specifying the input dialect to be T-SQL:
```python
>>> import sqlglot
>>> sqlglot.parse_one("select CONVERT(varchar(10),dt,120) a from dbo.test", read='tsql').sql(dialect='tsql')
"SELECT CAST(TIME_TO_STR(dt, '%Y-%m-%d %H:%M:%S') AS VARCHAR(10)) AS a FROM dbo.test"
```
