### ISSUE TITLE
Don't use uppercase ClickHouse functions in string representation

### ISSUE THREAD

**Issue by EugeneTorap** [tobymao/sqlglot#643]
Hi everyone, as I wrote in #320 - `DICTGET, INDEXOF and CH throws error because there's no such functions in CH`

We use a such ClickHouse query:
```sql
SELECT value[indexOf(name, 'pills')] AS "pills"
FROM data
```
![image](https://user-images.githubusercontent.com/29536522/198120724-395d900e-fecc-47e4-aa8c-ad0e9b0ac4a3.png)

I need to retrieve `value[indexOf(name, 'pills')] AS "pills"`, customize it and then replace it in the sql query.
And there's a problem when I retrieve it like this: `str(field.parent)` I got: `value[INDEXOF(name, 'pills')] AS "pills"`
indexOf -> INDEXOF

Can we fix uppercase CH functions in string representation?

**Comment by tobymao** [comment]
the issue is that you're using str() which convert it to the generic dialect. you need to do instead

field.parent.sql(dialect="clickhouse")

```python
>>> parse_one("indexOf(name)", read="clickhouse").sql(dialect="clickhouse")
'indexOf(name)'
```
