### ISSUE TITLE
sqlite valid syntax not parsed

### ISSUE THREAD

**Issue by earonesty** [tobymao/sqlglot#651]
sqlite is very forgiving:

``` create table "foo"("auto" integer not null primary key autoincrement,"inty" integer not null default(4),"blob" blob,"blob3" binary(3),"blob4" varbinary(4));```

sqlglot gets confused by the "varbinary" type

technically: *every* type is valid in sqlite

not a big deal tho, sqlglot is amazing.  best parser out there

**Comment by tobymao** [comment]
thanks for the high praise @earonesty
