### ISSUE TITLE
transpile sqlite->mysql

### ISSUE THREAD

**Issue by earonesty** [tobymao/sqlglot#656]
transpile should probably just quote all columns:

for example:
```
 sqlglot.transpile("create table foo (auto integer primary key, inty integer default 4, blob blob, tex text, flt float default 1.1, dbl double default 1.2);", read="sqlite", write="mysql")
```

.. this results in invalid SQL, because the column names are not quoted properly for myql, but work fine in sqlite.   because "blob" is a valid column name in sqlite, but not mysql

```
CREATE TABLE foo (auto INT PRIMARY KEY, inty INT DEFAULT 4, blob BINARY, tex TEXT, flt FLOAT DEFAULT 1.1, dbl DOUBLE DEFAULT 1.2)'
```

easier just to quote all columns

**Comment by tobymao** [comment]
this already exists, sqlglot.transpile(..., identify=True)
