### ISSUE TITLE
Sqlglot removes/truncates queries

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#670]
I have a query (invalid query) 

```
with v as (
  select * from auth_test_99_test
)
with q as (
  select * from test_db_171_table4
)
select * from v
```

when I parse it using sqlglot my expression changes to 

```
with v as (
  select * from auth_test_99_test
)
select * from v
```

This is not the behaviour I expected. Is there a way to throw an error instead?

**Comment by tobymao** [comment]
i think we may be able to convert that into the correct query

**Comment by SudarshanVS** [comment]
Thank you for the response. Our use case has users writing out their sql queries and saving it to the database (similar to a notebook). We want to run some backend validation (syntax checker) before saving it. 

Since, it's not possible to know what is the correct query in this context (should the first with statement be removed or the second, in the above example), I was wondering if it would be possible to raise an exception from sqlglot, handle it in the backend and send the appropriate response to the front end.
