### ISSUE TITLE
No error for invalid select statement

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#671]
Hi tobymao,

Thanks for helping with the previous [issue](https://github.com/tobymao/sqlglot/issues/671). :)

The transpiler doesn't throw an error for the following statement,

```
Select from table_a
```

is this the expected behaviour?

**Comment by tobymao** [comment]
yes. this is expected, sqlglot is not a validator. it's meant to take in very flexible inputs. the best validator would be to run it against your actual engine.
