### ISSUE TITLE
VARBINARY vs BINARY

### ISSUE THREAD

**Issue by earonesty** [tobymao/sqlglot#672]
mysql and postrgresql supports the difference between varbinary and binary

varbinary is trimmed to the size inserted
binary requires exact size inserts

mysql the syntax is `BINARY(3)` and `VARBINARY(3)`
postgres the syntax is `bit(3)` and `bit varying(3)`

probably need a new `TokenType.VARBINARY` for mysql

easy to fix mysql

but the tokenizer fails when there is a space after the column type for postgres

**Comment by tobymao** [comment]
we use postgres bytea to represent binary, i'm trying to understand the difference between bit, bit varying and bytea...

**Comment by tobymao** [comment]
so it seems like mysql binary and varbinary store binary strings and are the same as bytea.

**Comment by earonesty** [comment]
yes, bytea is better than "bit varying" for most postgres uses, and it is most similar to varbinary
