### ISSUE TITLE
[QUESTION]:  Rules for FROM clause in Custom Dialect

### ISSUE THREAD

**Issue by cgivre** [tobymao/sqlglot#681]
Hello all,
First of all, thank you very much for this really amazing module!!

I am interested in writing (and contributing) a dialect for Apache Drill.  Drill uses ANSI SQL (2003) with some additions so this looks fairly straightforward.  However, there is one piece which I'm not quite sure how to handle.

Drill allows the user to change certain options at query time.  For example, if you are querying an Excel file and want to query something other than the default sheet, you could write a query like this:

```sql
SELECT <fields>
FROM table( dfs.`test_data.xlsx` (type => 'excel', sheetName => 'secondSheet'))
```

My goal here is to get the Drill dialect to recognize this as valid SQL and basically leave it alone.  Are there any examples of something similar or do you have any suggestions?  
Thanks!!

**Comment by tobymao** [comment]
this is an easy change, you just need to make drill accept lambda / kwargs

```
python -m sqlglot "select * from y(w(x -> 'z'))"
SELECT
  *
FROM Y(W("x" -> 'z'))
```

already works, so it's just a matter of adding a mapping of => to -> or a new thing
