### ISSUE TITLE
Semantic Parsing Errors

### ISSUE THREAD

**Issue by danfrankj** [tobymao/sqlglot#690]
While it makes sense that sqlglot definitely shouldn't require an actual DB schema to validate agains ... sometimes semantic errors are detectable just from the query e.g. 

<img width="475" alt="image" src="https://user-images.githubusercontent.com/616139/201236017-07d89d78-8e35-4291-9e55-f933814e8b83.png">

Curious if this SQL _should_ parse and whether it should keep track of these kinds of errors. 

If we could catch this kind of thing this would help a lot for using sqlglot as a SQL validator.

**Comment by tobymao** [comment]
this exists with the optimizer

```
>>> from sqlglot import parse_one
>>> from sqlglot.optimizer import optimize
>>> node = parse_one("SELECT b from (select 1 as a)")
>>> optimize(node, schema = {"a": {}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/toby/dev/sqlglot/sqlglot/optimizer/optimizer.py", line 64, in optimize
    expression = rule(expression, **rule_kwargs)
  File "/home/toby/dev/sqlglot/sqlglot/optimizer/qualify_columns.py", line 34, in qualify_columns
    _qualify_columns(scope, resolver)
  File "/home/toby/dev/sqlglot/sqlglot/optimizer/qualify_columns.py", line 205, in _qualify_columns
    raise OptimizeError(f"Unknown column: {column_name}")
sqlglot.errors.OptimizeError: Unknown column: b
```

**Comment by tobymao** [comment]
this sql should parse, it's valid sql. the role of erroring out here is the optimizer.
