### ISSUE TITLE
DELETE USING + alias not supported

### ISSUE THREAD

**Issue by borismo** [tobymao/sqlglot#693]
Following up on https://github.com/tobymao/sqlglot/issues/594 (thanks by the way!):

The parser fails with:
```
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 31.
```
when parsing
```sql
delete from event using sales as s where event.eventid=s.eventid;
```
I verified that using an alias is allowed by executing the following:
```sql
create TEMPORARY table event (eventid int);
create TEMPORARY table sales (eventid int);
delete from event using sales as s where event.eventid=s.eventid;
```
in Redshift.

**Comment by GeorgeSittas** [comment]
Oops, I think I made a mistake there in the call to parse table. Fixing it right now.
