### ISSUE TITLE
Use of reserved name ("current_time") as an alias cause a parse error in BigQuery

### ISSUE THREAD

**Issue by sh0oki** [tobymao/sqlglot#699]
Hey there, and thanks for this awesome project!

I've started using sqlglot recently, and noticed a possible bug, when using a reserved keyword as an alias. This is clearly a bad alias name, but I did get more than a handful of automatic systems creating queries with reserved aliases; `row` and `current_time` seemed quite popular.

I've done some testing, and found this query syntax to be valid in Postgres (15.1) and BigQuery, but not valid in MySQL. 

```
postgres=# select 1 current_time;
 current_time
--------------
            1
(1 row)
```

Parsing such a query with Postgres dialect is done correctly, but fails for BigQuery:

```
>>> sqlglot.parse("SELECT 1 current_time", sqlglot.Dialects.BIGQUERY)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elisha/.local/lib/python3.9/site-packages/sqlglot/__init__.py", line 55, in parse
    return dialect.parse(sql, **opts)
  File "/home/elisha/.local/lib/python3.9/site-packages/sqlglot/dialects/dialect.py", line 149, in parse
    return self.parser(**opts).parse(self.tokenizer.tokenize(sql), sql)
  File "/home/elisha/.local/lib/python3.9/site-packages/sqlglot/parser.py", line 591, in parse
    return self._parse(
  File "/home/elisha/.local/lib/python3.9/site-packages/sqlglot/parser.py", line 627, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "/home/elisha/.local/lib/python3.9/site-packages/sqlglot/parser.py", line 652, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 10.
  SELECT 1 current_time



>>> sqlglot.parse("SELECT 1 current_time", sqlglot.Dialects.POSTGRES)
[(SELECT expressions:
  (ALIAS this:
    (LITERAL this: 1, is_string: False), alias:
    (IDENTIFIER this: current_time, quoted: False)))]
```

I would love to hear your thoughts about this, or possibly help implementing it, if you could point me in the right direction. 

Thanks!

**Comment by GeorgeSittas** [comment]
Hello, I made a [PR](https://github.com/tobymao/sqlglot/pull/700) addressing your issue. The methods of interest in this particular example were `_parse_alias` and `_parse_id_var`. If you inspect the latter, you can see that augmenting the `ID_VAR_TOKENS` set with the target keyword suffices in this case.

**Comment by sh0oki** [comment]
Amazing, thanks a lot!
________________________________
