### ISSUE TITLE
execute(): Exception when aggregating without GROUP BY

### ISSUE THREAD

**Issue by amachanic** [tobymao/sqlglot#703]
sqlglot 10.0.2, Python 3.8.4

`>>> execute('select sum(x) from t', tables={'t': [{'x': 1}, {'x': 2}]})`

Result:

`sqlglot.errors.ExecuteError: Step 'Scan: t (140100782263984)' failed: '_col_0'`

If I add column 'y' above, with the same value for every row, and group by that column, the execute returns as expected.

**Comment by tobymao** [comment]
this isn't supported yet but we can add it soon

**Comment by GeorgeSittas** [comment]
Note: I'm planning to tackle this issue soon, just spending some time understanding the executor's logic since I haven't played around with it much yet.
