### ISSUE TITLE
Prettifying has unintended side effects

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#714]
prettifying the below query has unintended side effects.
```
WITH v AS (
  SELECT
    * /*comment 
  after
  select */
  FROM hubspot_hubspot_249.hubspot.contacts -- test two
  /*comment after
  from
  */
), v1 AS (
  SELECT
    *
  FROM hubspot_hubspot_249.hubspot.companies
) /* text */, v2 AS (
  SELECT
    * -- hey there
  FROM v /* test */
  JOIN v1 /*comment after
  join */
  --asdhkj
    ON v1.companyId = v.companyId /* test */
)
SELECT
  *
FROM v
```

**PRETTIFIED**
```
WITH /*comment after
  from
  */
v AS (
  SELECT
    */*comment 
  after
  select */
    
  FROM hubspot_hubspot_249.hubspot.contacts /* test two */
), v1 AS (
  SELECT
    *
  FROM hubspot_hubspot_249.hubspot.companies
) /* text */, v2 AS (
  SELECT
    * -- hey there
  FROM v /* test */
  JOIN /* comment after
    join */
  v1
    ON v1.companyId = v.companyId /* test */
)
SELECT
  *
FROM v
```
The prettified query will fail to execute because the first select statement has a `*/*` sequence that represents an orphaned comment closing tag.

Also,
```
/*comment after
  from
  */
```

got moved to the top.

**Comment by GeorgeSittas** [comment]
I'll take a look; seems like there are multiple parts broken here 😄.

Thanks for the report!

**Comment by GeorgeSittas** [comment]
> The prettified query will fail to execute because the first select statement has a */* sequence that represents an orphaned comment closing tag.

I don't get where the issue is here. For example, the following is valid SQL and resembles the part you're referring to:
```sql
SELECT */* comment */ FROM foo```

**Comment by SudarshanVS** [comment]
Hi George,

Running,
```
q = SELECT */* comment */ FROM foo
parse_one(q)
```
through the parser seems to fail!

I get the following error,
```
sqlglot.errors.ParseError: Expected */ after HINT. Line 1, Col: 10.
  Select */*comment*/ from foo
```
