### ISSUE TITLE
Parser mutates `Not Equal To`  symbol in query

### ISSUE THREAD

**Issue by SudarshanVS** [tobymao/sqlglot#731]
Hi,

Thanks for addressing all my issues so far. :)

I have noticed that the parser changes the below query,
```
Select * from Table where x != 2
```

to 

```
Select * from Table where x <> 2 
```

While both are valid syntax, I was wondering if this is the intended behaviour and the rationale behind it.
Also, is there a way to preserve the original syntax?

**Comment by GeorgeSittas** [comment]
This isn't actually related to the parser, observe;
```python
>>> sqlglot.parse_one("Select * from Table where x != 2")
(SELECT expressions:
  (STAR ), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: Table, quoted: False))), where:
  (WHERE this:
    (NEQ this:
      (COLUMN this:
        (IDENTIFIER this: x, quoted: False)), expression:
      (LITERAL this: 2, is_string: False))))
```
The reason `!=` is converted to `<>` is that the latter is ANSI SQL and SQLGlot aims to cover as many dialects as possible.
