### ISSUE TITLE
sqlglot doesn't recognize postgres hstore or jsonb types

### ISSUE THREAD

**Issue by rbrooks-hubble** [tobymao/sqlglot#745]
hstore example:
```
print(sqlglot.transpile("create table test(foo hstore)", read="postgres", pretty=True)[0])
```

```
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 23.
  create table test(foo hstore)
```

jsonb example:
```
print(sqlglot.transpile("create table test(foo jsonb)", read="postgres", pretty=True)[0])
```

```
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 23.
  create table test(foo jsonb)
```

Also I think array types aren't supported in some cases
```
print(sqlglot.transpile("create table test(foo varchar(64)[])", read="postgres", pretty=True)[0])
```

```
sqlglot.errors.ParseError: Expecting ). Line 1, Col: 34.
  create table test(foo varchar(64)[])
```

It does work if with simpler types like `foo int[]` etc but if the type has parens in it like this, it gives an error

Ideally it would recognize/handle these like other types - I know postgres has some non-standard types and it's something of a moving target, but of all the formtters I tried, sqlglot seems the nicest and it would be great if I could format all the create statements I have.

This is sqlglot==10.0.10 on python 3.10 if that matters

**Comment by tobymao** [comment]
yep, not supported yet, but we'll get this in soon. thanks
