### ISSUE TITLE
Redshift COPY command not supported

### ISSUE THREAD

**Issue by borismo** [tobymao/sqlglot#763]
Parsing a COPY command fails. Example:
```sql
copy customer from 's3://mybucket/customer' iam_role 'arn:aws:iam::0123456789012:role/MyRedshiftRole';
```
taken from https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-source-s3.html#copy-parameters-data-source-s3-examples fails with
```
Invalid expression / Unexpected token. Line 1, Col: 15.
```
It would be useful for my use case that it is supported but I don't know whether if SQLGlot is meant to be able to parse non-standard SQL like this.

**Comment by GeorgeSittas** [comment]
I'll take a look, thanks for all the reports!

> It would be useful for my use case that it is supported but I don't know whether if SQLGlot is meant to be able to parse non-standard SQL like this.

SQLGlot currently parses many non-standard syntax forms, and It's not a big deal to support them usually. :-)
