### ISSUE TITLE
Stale Syntax Tree Transformation example

### ISSUE THREAD

**Issue by shearerpmm** [tobymao/sqlglot#77]
This is the Syntax Tree Transformation example in the README:

```
import sqlglot
import sqlglot.expressions as exp

expression_tree = sqlglot.parse_one("SELECT a FROM x")

def transformer(node):
    if isinstance(node, exp.Column) and node.args["this"].text == "a":
        return sqlglot.parse_one("FUN(a)")
    return node

transformed_tree = expression_tree.transform(transformer)
transformed_tree.sql()
```

When I run it, the transformed_tree isn't changed, the SQL is still `SELECT a FROM x`.

I played with it a bit and found it worked to change the `.text` to `.args["this"]`.

**Comment by tobymao** [comment]
thanks, will fix

**Comment by tobymao** [comment]
ac904a637eb322d8936442ce22b9710c30697b1d
