### ISSUE TITLE
Redshift DECODE

### ISSUE THREAD

**Issue by yuchaofan13** [tobymao/sqlglot#789]
Current parsing for Redshift DECODE leads to a parsing error: https://docs.aws.amazon.com/redshift/latest/dg/r_DECODE_expression.html
e.g. SELECT DECODE(COL1, 'replace_this', 'with_this', 'replace_that', 'with_that') 

Redshift DECODE is essentially REPLACE but allows unlimited arguments. 

However, mapping DECODE to REPLACE in the tokenizer didn't work and I realised this was the wrong approach. I then tried adding DECODE to FUNC_TOKENS in redshift.py but that still didn't work. Not sure how to override DECODE in expressions.

**Comment by GeorgeSittas** [comment]
@yuchaofan13 take a look.
