### ISSUE TITLE
How can I access to the sqlglot.diff dataclasses? (`Insert`, `Keep`, `Move`, etc.)

### ISSUE THREAD

**Issue by roykoand** [tobymao/sqlglot#791]
Thank you for the outstanding library!
I want to do some manipulations with the `sqlglot.diff` function output. Am I able to import `Insert`, `Keep`, `Update`, etc. dataclasses?
They seem inaccessible on the package level. Obviously I can do some hardcode like `"Insert" in str(operation.__class__)` but wonder if I missed something

**Comment by tobymao** [comment]
what happens when you try to import them? can you show me the code and error?

**Comment by roykoand** [comment]
@tobymao I'm not seeing how I can import them at all. `sqlglot.diff` is a function, not a module. Something like `sqlglot.diff.Insert` will obviously fail

**Comment by roykoand** [comment]
Omg, sorry, my bad I'm blind! thanks for the fast response
