### ISSUE TITLE
Functions transpiled incorrectly from MySQL to BigQuery

### ISSUE THREAD

**Issue by phdowling** [tobymao/sqlglot#802]
```python
import sqlglot
print(sqlglot.transpile("SELECT 'foo' regexp '.*';", read="mysql", write="bigquery"))
```
This currently transpiles to `SELECT REGEXP_LIKE('foo', '.*')` which is not valid for BigQuery (I guess the correct function would be `REGEXP_CONTAINS`).

Overall, how robust should I expect transpilation to be? Are certain language pairs better supported than others? Are functions more problematic than other constructs?

**Comment by tobymao** [comment]
transpilation is most robust in presto -> spark -> duckdb. these dialects are used in production systems at companies i've worked at.
