### ISSUE TITLE
Column constraint order broken

### ISSUE THREAD

**Issue by mpf82** [tobymao/sqlglot#818]
Column constraint don't have to be in a specific order in a create table statement.

In the current version 10.2.9 the following sql results in

``create table t2(n int not null default 0)`` -> ``CREATE TABLE t2 (n INT NOT NULL DEFAULT 0)``

which is correct.

However this one is broken:

``create table t2(n int default 0 not null)`` -> ``CREATE TABLE t2 (n INT DEFAULT NOT 0 NULL)``

Notice the **DEFAULT NOT 0 NULL** part, which is invalid SQL.

In sqlglot version 10.0.0 the result was still correct ``CREATE TABLE t2 (n INT DEFAULT 0 NOT NULL)``, so a change between 10.0.0 and the current version must have introduced this.

**Comment by GeorgeSittas** [comment]
The parsing was broken in this one, and still is if we try to evaluate a plain `0 not` expression:

```python
>>> import sqlglot
>>> sqlglot.parse_one("0 not")
(NOT this:
  (LITERAL this: 0, is_string: False))
```
