### ISSUE TITLE
merge_subqueries bug

### ISSUE THREAD

**Issue by izulin** [tobymao/sqlglot#825]
I'm having a following issue:

`merge_subqueries(parse_one(" WITH foo AS (SELECT a + 1 AS a, b + 1 AS b FROM tab) SELECT a + 1 AS a, b + 1 AS b FROM foo")).sql()`

produces

"SELECT a + 1 AS a, b + 1 AS b FROM tab"

**Comment by barakalon** [comment]
`merge_subqueries` depends on `qualify_columns`. Do you have access to the schema of `tab`?

**Comment by izulin** [comment]
> `merge_subqueries` depends on `qualify_columns`. Do you have access to the schema of `tab`?

no, not really, I'm writing a generic sql transformer. Is there a way to use both in tandem, generically?

**Comment by barakalon** [comment]
Optimization without qualified columns is really tough. So a lot of the rules have an implicit dependency on `qualify_columns`.

There are things we can do to make `qualify_columns` more forgiving in absence of the schema. E.g. automatically assume that `a` and `b` are columns of `tab` in that CTE. That'd be a sweet contribution.

We can also make this dependency more explicit in rules like `merge_subqueries`. E.g. add this dependency to the doc string and throw an error when it encounters an unqualified scope. That'd be another sweet contribution.

But as it stands today, not all rules can be used independently.

**Comment by izulin** [comment]
@barakalon is there a way to deduce which rules can be applied as a standalone? Even looking at the sourcecode of rules, it is not obvious.

**Comment by tobymao** [comment]
not right now no. but in general, you always need to run qualify_(tables/columns)
