### ISSUE TITLE
BUG: can not parse presto sql

### ISSUE THREAD

**Issue by evyasonov** [tobymao/sqlglot#827]
Hi

Below is valid presto sql which sqlglot can not parse. Can you please fix it.

```
WITH
    A(filter) AS (
        VALUES 1, 2, 3
    )

SELECT
    *
FROM
    A
WHERE
    filter >= 2
```

**Comment by GeorgeSittas** [comment]
Hello,

Can you please provide some documentation for this form? It seems non-standard and with a quick search I can't seem to find it.
