### ISSUE TITLE
Create table - parser errors

### ISSUE THREAD

**Issue by mpf82** [tobymao/sqlglot#83]
I've run into some create table statements that throw parser errors:

### PostgreSQL

* create table t1(a int primary key)
* create table t1(s bytea)
* create table t1(n uuid)
* create table t1(n int generated always as identity primary key)

### Oracle

* create table t1(n number)
* create table t1(s long raw)
* create table t1(s long varchar)
* create table t1(c1 NUMBER GENERATED by default on null as IDENTITY)

The error is basically always ``Error: Expecting )``

**Comment by tobymao** [comment]
i can fix postgres parsing but oracle is not supported yet, i have no plans to add it because i've never used oracle, but happy to accept a PR

**Comment by tobymao** [comment]
i added support for primary key, bytea and uuid in postgres, i'm not going to address the others but happy to accept a PR
