### ISSUE TITLE
a IS NOT NULL is transformed into NOT a IS NULL

### ISSUE THREAD

**Issue by evyasonov** [tobymao/sqlglot#830]
Hi

sqlglot transforms `a IS NOT NULL` into `NOT a IS NULL` (presto dialect). On one hand presto returns the same result, so the code is correct, but on other hand it's much harder to read this code, because it confuses a reader. Usually a person will not be able to tell for sure regarding priority of NOT vs IS NULL.

Can you please fix it the way presto dialect transforms `a IS NOT NULL` into `a IS NOT NULL` or into `NOT(a IS NULL)`. The first option is preferable.

**Comment by GeorgeSittas** [comment]
Hello,

There is a [related discussion](https://github.com/tobymao/sqlglot/discussions/274) where you can see the motivation behind this (rather opinionated) transformation. I don't see why this change would only apply in Presto, and at the same time I'm not sure if it's worth doing globally.

Maybe it'd be useful to have an option that determines the order at generation time.

**Comment by evyasonov** [comment]
The option would be perfect

**Comment by tobymao** [comment]
as stated in the previous discussion, sqlglot is producing canonical sql, so there's no intention of changing this behavior
