### ISSUE TITLE
hive -> presto bad case

### ISSUE THREAD

**Issue by alingse** [tobymao/sqlglot#831]
hive
```SQL
select
  date_format(from_unixtime(1671770481), 'yyyy-MM-dd')
```

translate got
```SQL
SELECT DATE_FORMAT(DATE_FORMAT(FROM_UNIXTIME(1671770481), '%Y-%m-%d %H:%i:%S'), '%Y-%m-%d')
```

it not works, should be

```SQL
SELECT DATE_FORMAT(FROM_UNIXTIME(1671770481), '%Y-%m-%d')
```

**Comment by tobymao** [comment]
hive from_unixtime returns a time stamp formatted string, that means the equivalent function in presto is 

DATE_FORMAT(FROM_UNIXTIME(1671770481), '%Y-%m-%d %H:%i:%S')

**Comment by tobymao** [comment]
@alingse does this code crash in presto?

**Comment by tobymao** [comment]
i guess it does because date_format expects a timestamp

i can turn it into

DATE_FORMAT(DATE_PARSE(DATE_FORMAT(FROM_UNIXTIME(1671770481), '%Y-%m-%d %H:%i:%S'), '%Y-%m-%d %H:%i:%s'), '%Y')

**Comment by alingse** [comment]
Error Message: line 2:3: Unexpected parameters (varchar, varchar(8)) for function date_format. Expected: date_format(timestamp(p), varchar(x)) , date_format(timestamp(p) with time zone, varchar(x))

**Comment by alingse** [comment]
```SQL
select
  DATE_FORMAT(
    DATE_PARSE(
      DATE_FORMAT(FROM_UNIXTIME(1671770481), '%Y-%m-%d %H:%i:%S'),
      '%Y-%m-%d %H:%i:%s'
    ),
    '%Y-%m-%d'
  )
```

is correct and get same result

**Comment by tobymao** [comment]
try this

```DATE_FORMAT(CAST(DATE_FORMAT(FROM_UNIXTIME(1671770481), '%Y-%m-%d %H:%i:%S') AS TIMESTAMP), '%Y-%m-%d')
```

**Comment by tobymao** [comment]
in order to transpile, you have to understand the meaning of hive, although it's not efficient, it keeps the same original intent

**Comment by alingse** [comment]
> try this
> 
> ```sql
> DATE_FORMAT(CAST(DATE_FORMAT(FROM_UNIXTIME(1671770481), '%Y-%m-%d %H:%i:%S') AS TIMESTAMP), '%Y-%m-%d')
> ```

this is also correct result.

**Comment by tobymao** [comment]
i'll have a fix soon with that version
