### ISSUE TITLE
Any suggestions for adding a new creatable type in a custom dialect

### ISSUE THREAD

**Issue by nikhilk** [tobymao/sqlglot#832]
I hope it is reasonable to use the issues list to ask a Q. I've been trying to make this work for sometime and haven't gotten my use-case to work.

I am trying to extend an existing dialect (BigQuery in particular) and extending it to add a new creatable type - "session". Specifically to enable this SQL.

```
create session if not exists aaa options(location="xyz");
```

Any chance you could suggest some. pointers?

I tried adding to the list of tokens, creatables, using the same token type as an existing creatable as a stop-gap, but running into several errors including unexpected creatable type, unexpected token for "options". So I suspect I am missing something fairly basic for how to go about adding custom dialects.

Would appreciate any pointers you could offer. Thanks!

**Comment by tobymao** [comment]
as a stop gap, i've added CREATE SESSION in the bigquery dialect as a command, so it can effectively parse any create session as a string.

if you want real AST parsing, you're going to have to implement a full create session parser

take a look at def _parse_create in parser.py

**Comment by nikhilk** [comment]
Thanks much for such quick response/update.

Sorry if I wasn't super clear, but this isn't a construct supported within BigQuery DDL. I am prototyping something and extending the SQL syntax. I just wanted to clarify in case you didn't want to add this to the actual BigQuery dialect.

Let me look at the steps you have listed above and try again.

I think I also need to add support for the OPTIONS block which BQ does support for creatables such as SCHEMA, TABLE etc.

**Comment by tobymao** [comment]
oh, i thought this was a part of the bigquery dialect. i'm going to revert this commit then.

you can make a custom bigquery commit for this use case then.

in the future, these kind of questions can go in the discussions section

**Comment by nikhilk** [comment]
Sounds good, and once again, thanks.
