### ISSUE TITLE
Postgres POSIX Regular Expressions parse error

### ISSUE THREAD

**Issue by alexandermalyga** [tobymao/sqlglot#844]
The following valid Postgtres Postgres POSIX Regular Expression raises a parsing error:

```
import sqlglot

sql = """
SELECT * FROM t WHERE id ~* 'abc'
"""

sqlglot.parse_one(sql, read="postgres")
```

Thank you for your amazing work!

**Comment by tobymao** [comment]
@alexandermalyga thanks for all the issues, in the future can you please make the title a bit more specific?

**Comment by alexandermalyga** [comment]
> @alexandermalyga thanks for all the issues, in the future can you please make the title a bit more specific?

Absolutely, my bad. Thanks for the great work
