### ISSUE TITLE
Postgres parse error on pseudo-type cast

### ISSUE THREAD

**Issue by alexandermalyga** [tobymao/sqlglot#848]
The following valid SQL raises a parse error:
```
sql = """
SELECT 'abc'::CSTRING
"""

sqlglot.parse_one(sql, read="postgres")
```

This also applies to other Postgres-specific special types like `regclass`

https://www.postgresql.org/docs/15/datatype-pseudo.html

**Comment by tobymao** [comment]
i'm only going to do one of these, can you make a PR for the rest that you need?

**Comment by alexandermalyga** [comment]
Sure no problem, I could do that using your PR as reference. 
Also, sorry for the spam on these Postgres issues, I will try to submit more PRs with them, but the codebase is a little unfamiliar/intimidating.

**Comment by tobymao** [comment]
no problem.

https://github.com/tobymao/sqlglot/commit/58737ea251d9c874ef19f7179d31040f8edf29ff#diff-7fe5bd723cf2d072429f107bc81b4809e43e254b7bc2ef0116698721f0fd3661R230

add the rest to this list of key word mappings and then add tests like i did with CSTRING
