### ISSUE TITLE
Postgres parse error on window alias

### ISSUE THREAD

**Issue by alexandermalyga** [tobymao/sqlglot#849]
The following valid SQL raises a parse error:
```
sql = """
WITH t AS (SELECT 1 AS id UNION ALL SELECT 2)
SELECT SUM(id) OVER w FROM t WINDOW w AS (ORDER BY id)
"""

sqlglot.parse_one(sql, read="postgres")
```

**Comment by voberoi** [comment]
This is also a valid query in DuckDB and raises a parse error.

**Comment by tobymao** [comment]
https://github.com/tobymao/sqlglot/commit/b423413ebd4dd2cd413e45354ef386e8e91ca26b

@voberoi

**Comment by voberoi** [comment]
Thank you! I'll submit PRs for the others. Thanks.
