### ISSUE TITLE
Postgres parse error on CTE with "values" alias

### ISSUE THREAD

**Issue by alexandermalyga** [tobymao/sqlglot#850]
The following valid SQL raises a parse error:
```
sql = """
WITH values AS (SELECT 1 AS id UNION ALL SELECT 2)
SELECT * FROM values
"""

sqlglot.parse_one(sql, read="postgres")
```

This is a bad practice that unfortunately happens all the time.

**Comment by tobymao** [comment]
@alexandermalyga feel free to join my slack channel to chat more in depth about things

https://join.slack.com/t/tobiko-data/shared_invite/zt-1ma66d79v-a4dbf4DUpLAQJ8ptQrJygg

**Comment by tobymao** [comment]
i'm not planning to fix this one. you can just change these queries to quote "valueS"
