### ISSUE TITLE
Not removing redundant joins

### ISSUE THREAD

**Issue by michaeljstevens** [tobymao/sqlglot#854]
Hello, unsure if this is not implemented yet or a bug, let me know. I'm trying to use the optimizer to rewrite the following query:

```sql
  SELECT
      a.id
  FROM
      (
          SELECT
          id
          FROM location
          WHERE
          country IN ('United States', 'Canada')
      ) a
      join 
	   (
	      SELECT
	      id
	      FROM location
	      WHERE
	      state IN ('Utah', 'California')
	  ) b on a.id = b.id
```

```python
RULES = (
    unnest_subqueries,
    optimize_joins,
    merge_subqueries,
    eliminate_joins
)

sql = """
  SELECT
      a.id
  FROM
      (
          SELECT
          id
          FROM location
          WHERE
          country IN ('United States', 'Canada')
      ) a
      join 
	   (
	      SELECT
	      id
	      FROM location
	      WHERE
	      state IN ('Utah', 'California')
	  ) b on a.id = b.id
    """
sql = sqlglot.parse_one(sql)


sql = optimize(
        expression=sql,
        schema={
            "location": { "id": "STRING", "country": "STRING", "state": "STRING"},
        },
        rules=RULES
    )
print(sql.sql(pretty=True))
```

I would expect the output to be:

```sql
SELECT
  id
FROM location
WHERE
  country IN ('United States', 'Canada') AND state IN ('Utah', 'California')
```

but the actual output is

```sql
SELECT
  id
FROM location
JOIN location AS location_2
  ON id = id AND state IN ('Utah', 'California')
WHERE
  country IN ('United States', 'Canada')
```

As you can see, it has preserved the self join, but it's actually redundant. Ideally, the `join` could be and `intersect` and I would see the same result, but that's another story. Let me know if this is expected, actually happy to contribute some code to this project as I have a lot of query rewriting I need to do and seeing several issues. Thanks!

**Comment by barakalon** [comment]
This join can only be removed if it’s a LEFT join. 

An INNER join (what’s shown here) might remove columns from the result set, so we can’t remove it without know more about the constraints of the underlying data.

I’d also be careful overriding rules without qualify_columns/tables. Some of the other rules have an implicit dependency on those.

Happy to help you get more familiar with the code - contributions would be very welcome :)

**Comment by tobymao** [comment]
to add to this, inner joins are not safe to remove either because if ID is not unique, it will be a many to many join.

**Comment by michaeljstevens** [comment]
> I’d also be careful overriding rules without qualify_columns/tables. Some of the other rules have an implicit dependency on those.

This makes sense. Is there a way to specify a `pk` column in the schema? Interestingly, if I make it a left join I get this 
```sql
SELECT
  id
FROM location
LEFT JOIN (
  SELECT
    id
  FROM location
  WHERE
    state IN ('Utah', 'California')
) AS b
  ON id = b.id
WHERE
  country IN ('United States', 'Canada')
```

**Comment by barakalon** [comment]
@tobymao i think you mean left join. And ah! Good point - we only remove left joins when we know the query is joined on unique columns (e.g. because of a GROUP BY clause)

**Comment by michaeljstevens** [comment]
With table/col qualifications, left join, and group by on outer query
```sql
    SELECT
        a.id
    FROM
        (
            SELECT
            f1.id
            FROM location f1
            WHERE
            country IN ('United States', 'Canada')
        ) a
        left join 
	     (
	        SELECT
	        f2.id
	        FROM location f2
	        WHERE
	        state IN ('Utah', 'California')
	    ) b on a.id = b.id
    group by id
    
 results in 
SELECT
  f1.id AS id
FROM location AS f1
LEFT JOIN (
  SELECT
    f2.id AS id
  FROM location AS f2
  WHERE
    f2.state IN ('Utah', 'California')
) AS b
  ON f1.id = b.id
WHERE
  f1.country IN ('United States', 'Canada')
GROUP BY
  f1.id
```

with group bys everywhere 
```sql
    SELECT
        a.id
    FROM
        (
            SELECT
            f1.id
            FROM location f1
            WHERE
            country IN ('United States', 'Canada')
            group by f1.id
        ) a
        left join 
	     (
	        SELECT
	        f2.id
	        FROM location f2
	        WHERE
	        state IN ('Utah', 'California')
            group by f2.id
	    ) b on a.id = b.id
    group by id

results in:

SELECT
  a.id AS id
FROM (
  SELECT
    f1.id AS id
  FROM location AS f1
  WHERE
    f1.country IN ('United States', 'Canada')
  GROUP BY
    f1.id
) AS a
LEFT JOIN (
  SELECT
    f2.id AS id
  FROM location AS f2
  WHERE
    f2.state IN ('Utah', 'California')
  GROUP BY
    f2.id
) AS b
  ON a.id = b.id
GROUP BY
  a.id

```

**Comment by tobymao** [comment]
try using the full optimizer, i think if you use the isolate_table_selects, it could pull it out

**Comment by michaeljstevens** [comment]
> try using the full optimizer, i think if you use the isolate_table_selects, it could pull it out

Looks like it just dropped the state selection 
```sql
WITH "a" AS (
  SELECT
    "f1"."id" AS "id"
  FROM "location" AS "f1"
  WHERE
    "f1"."country" IN ('United States', 'Canada')
  GROUP BY
    "f1"."id"
)
SELECT
  "a"."id" AS "id"
FROM "a" AS "a"
GROUP BY
  "a"."id"

```

**Comment by tobymao** [comment]
that's because you don't use the right hand side. so the left join is unused and gets removed

**Comment by barakalon** [comment]
> Is there a way to specify a pk column in the schema?

not yet, but we’ve talked about it. I imagine we’d mimic a CREATE TABLE statement:
`schema = {“location”: {“id”: “STRING PRIMARY KEY”}}`

**Comment by tobymao** [comment]
the optimization in particular that you're looking for which is combining predicates on subqueries isn't implemented yet. but given your use case of joins, it wouldn't work anyways because it's unsafe

**Comment by michaeljstevens** [comment]
> the optimization in particular that you're looking for which is combining predicates on subqueries isn't implemented yet. but given your use case of joins, it wouldn't work anyways because it's unsafe

Okay thanks. And that's because of the potential many to many join right?

**Comment by barakalon** [comment]
I think you’re looking for a rule like this:
If inner joining a table to itself on a unique column, merge the two statements.

I think that makes sense. Might be a slew of other constraints.

**Comment by tobymao** [comment]
@michaeljstevens yes, cardinality changes which are side effects of joins

**Comment by michaeljstevens** [comment]
Got it, thanks for the help guys. I may play around with adding the pk stuff.
