### ISSUE TITLE
Support for recursive CTEs self-reference in their scope.

### ISSUE THREAD

**Issue by alexandermalyga** [tobymao/sqlglot#856]
[Recursive CTEs](https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-RECURSIVE) do not contain themselves as a CTE source when inspecting their scope.

The following CTE does not contain `t` in the `SELECT * FROM t` scope when inspecting it using `sqlglot.optimizer.scope.traverse_scope`:

```sql
WITH RECURSIVE t AS (
    SELECT * FROM t
)
SELECT 1
```

Also:

> [The RECURSIVE keyword is not usually needed after WITH in systems other than PostgreSQL](https://en.wikipedia.org/wiki/Hierarchical_and_recursive_queries_in_SQL#Common_table_expression).

**Comment by barakalon** [comment]
Recursive CTEs aren’t supported yet.

I also think your query isn’t valid? I think you need a non-recursive term, followed by a UNION, followed by a recursive term.

I can take a look at this next week. Contributions welcomed though :)

**Comment by tobymao** [comment]
@barakalon i have a diff for this

**Comment by alexandermalyga** [comment]
This is great. Thanks a lot!
