### ISSUE TITLE
How to represent empty input tables?

### ISSUE THREAD

**Issue by DavidPratten** [tobymao/sqlglot#863]
I have a use-case where it is expected that with an empty input table e.g. ```products```

| product_id | price |
| ---- | ---- |

the query

```
execute("select * from products", tables=products) 
```
would return
```
(("product_id", "price"), [])
```
What do I need to do to represent an empty input table?

Thanks

David

**Comment by tobymao** [comment]
I believe this works as expected

```python
from sqlglot.executor import execute

execute(
    "select * from products",
    schema={"products": {"product_id": "int", "price": "double"}}, 
    tables={"products": []},
)
```

**Comment by DavidPratten** [comment]
Nice.
