### ISSUE TITLE
BigQuery implicit UNNEST not recognized?

### ISSUE THREAD

**Issue by ehdr** [tobymao/sqlglot#877]
BigQuery allows [implicit `UNNEST`ing](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#explicit_and_implicit_unnest), so the following give the same result:

```
WITH list_table AS (
  SELECT ['a1', 'b1', 'c1'] AS list_col UNION ALL 
  SELECT ['a2', 'b2', 'c2'] AS list_col
)
SELECT x
FROM list_table,
  UNNEST(list_table.list_col) AS x;
```

and 

```
WITH list_table AS (
  SELECT ['a1', 'b1', 'c1'] AS list_col UNION ALL 
  SELECT ['a2', 'b2', 'c2'] AS list_col
)
SELECT x
FROM list_table,
  list_table.list_col AS x;
```
(without the explicit `UNNEST`).

sqlglot correctly parses the first one with the explicit `UNNEST` to have `UNNEST expressions`, but the second one with implicit `UNNEST` as:

```
(SELECT expressions:
  (COLUMN this:
    (IDENTIFIER this: x, quoted: False)), from:
  (FROM expressions:
    (TABLE this:
      (IDENTIFIER this: list_table, quoted: False)),
    (TABLE this:
      (IDENTIFIER this: list_col, quoted: False), db:
      (IDENTIFIER this: list_table, quoted: False), alias:
      (TABLEALIAS this:
        (IDENTIFIER this: x, quoted: False)))), with:
...
```

which I believe is not correct, since `list_col` is not a table?

Is it possible to have sqlglot recognize the implicit `UNNEST`s?

**Comment by tobymao** [comment]
this seems out of scope of the parser, and perhaps something that would go into a custom bigquery transform
