### ISSUE TITLE
Transpiling / Parsing INSERT INTO with columns

### ISSUE THREAD

**Issue by mpf82** [tobymao/sqlglot#88]
``INSERT INTO table2 (column1, column2, column3) SELECT column1, column2, column3 FROM table1 WHERE condition``

transpiles to 

``INSERT INTO TABLE2(column1, column2, column3) SELECT column1, column2, column3 FROM table1 WHERE condition``

Note the uppercase TABLE2 and the "missing" space.

I would expect the transpiled SQL to look the same as the initial string.

---

Comparing to INSERT INTO w/o columns:

``INSERT INTO table2 SELECT column1, column2, column3 FROM table1 WHERE condition`` which parses "table2" as IDENTIFIER:

```
(INSERT this:
  (TABLE this:
    (IDENTIFIER this: table2, quoted: False)), expression:
  (SELECT expressions:
  ...
```

but with columns it parses "table2" as ANONYMOUS:

```
(INSERT this:
  (TABLE this:
    (ANONYMOUS this: table2, expressions:
      (COLUMN this:
        (IDENTIFIER this: column1, quoted: False)),
      (COLUMN this:
        (IDENTIFIER this: column2, quoted: False)),
      (COLUMN this:
        (IDENTIFIER this: column3, quoted: False)))), expression:
  (SELECT expressions:
  ...
```

**Comment by tobymao** [comment]
```python -m sqlglot "insert into x(y , z) select 1" --parse
(INSERT this:
  (SCHEMA this:
    (TABLE this:
      (IDENTIFIER this: x, quoted: False)), expressions:
    (IDENTIFIER this: y, quoted: False),
    (IDENTIFIER this: z, quoted: False)), expression:
  (SELECT expressions:
    (LITERAL this: 1, is_string: False)))
```
