### ISSUE TITLE
Missing support for temp table in SQLServer(tsql)

### ISSUE THREAD

**Issue by posutsai** [tobymao/sqlglot#895]
In SQLServer, according to the [official Microsoft doc](https://learn.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-tables-temporary#create-a-temporary-table), the naming temp table includes a prefix pound sign '#'. Current implementation of tsql dialect seems fail to parse simple query from temp table.

```python
# sqlglot.errors.ParseError: Expected table name but got <Token token_type: TokenType.HASH
sqlglot.parse('select * from #TempTable', read='tsql')
```

Btw, I would like to send a PR for fixing the issue. However, I have no idea where to start. It would be great if someone can give me several hints. Thank you very much.

**Comment by tobymao** [comment]
this one is not easy to do, so i'll do it and tag you for next time.

**Comment by tobymao** [comment]
it was a bit easier than i thought because i only implemented parsing
