### ISSUE TITLE
Parse Postgres style "::" casts

### ISSUE THREAD

**Issue by JPricey** [tobymao/sqlglot#9]
Hey, amazing work on this library so far.
Are there plans to support "::" style type casts, as seen in postgres & redshift?
https://www.postgresqltutorial.com/postgresql-cast/

Here are some example scenarios I've tested in the 1.2.0 release.

```
import sqlglot
sqlglot.transpile("select foo::INTEGER from bar", read='postgres')
```
results in:
`['SELECT CAST(foo AS ) AS INT FROM bar']`

where I would expect:
`['SELECT CAST(foo AS INT) FROM bar']`

Another edge-case is combining the cast with an alias (which is what sqlglot currently interprets the :: as):
```
import sqlglot
sqlglot.transpile("select foo::INTEGER as baz from bar", read='postgres')
```
results in:
```
ParseError: Invalid expression / Unexpected token. Line 0, Col: 20.
select foo::INTEGER as baz from bar
```

where I would expect:
`['SELECT CAST(foo AS INT) AS baz FROM bar']`

Thanks!

**Comment by tobymao** [comment]
v1.2.2

**Comment by JPricey** [comment]
Wow, thanks for the quick fix!

**Comment by tobymao** [comment]
@JPricey just curious, what is your use case?

**Comment by JPricey** [comment]
I'm looking for a sql parser for redshift syntax.
I have a bunch of create table statements as part of a redshift ELT. My goal is to parse all of those statements, pull out the table references within them, and construct a dependency graph to execute those statements within an airflow dag.

Unfortunately I've now run into a few other examples of special redshift syntax that this library does not support.
Is redshift support considered a goal of this project?

**Comment by tobymao** [comment]
Yes -- redshift is a goal, but i don't have access to redshift and don't use it. Happy to accept your contributions, or if you file issues with statements that fail, I will add them.
