### ISSUE TITLE
Rewrite queries to remove nested queries in WHERE clause

### ISSUE THREAD

**Issue by marsupialtail** [tobymao/sqlglot#91]
It would be great if SQLGlot can "flatten" a nested SQL query such that the only nested subqueries are operands of the FROM clause and are independent from each other. This mostly involves taking care of subqueries inside the WHERE clause.

There are a couple cases here. The first case is this subquery is independent of the outer query. In this case this subquery should just be evaluated as a separate SQL query and its result can be used in the original query. 

The second case is a bit more complicated, and occurs when the subquery depends on the outer query. For example in TPCH 2 and 4: https://github.com/marsupialtail/nest-query-rewrites. In this case we need to also reflect the dependency between the outer query and the nested query in the rewrite.

I think taking care of the first case will go a long way already.

**Comment by tobymao** [comment]
After trying this out, I believe that this functionality might not belong in SQLGlot core because there is no way to rewrite SELECT x > (Select SUM(y)), doing something like SELECT x > :z is not valid sql. However, the first case is easy enough to accomplish.

```python
import sqlglot
import sqlglot.expressions as exp


node = sqlglot.parse_one(
    """
    SELECT (select 1) a, (select 2) b
    FROM foo, (select * from baz) baz
    JOIN (
        SELECT *
        FROM bar
    )
    WHERE y > (SELECT 1)
    """
)

independent_subqueries = {}

def extract_independent_subqueries(node):
    if isinstance(node.parent, exp.Paren):
        key = f"__{node.__hash__()}__"
        independent_subqueries[key] = node.sql(pretty=True)
        return exp.Literal.string(key)
    return node
  
print(node.transform(extract_independent_subqueries).sql(pretty=True))
print("***********")
print(independent_subqueries) 
```
