### ISSUE TITLE
Bug: excessive alias parsing in presto dialect

### ISSUE THREAD

**Issue by evyasonov** [tobymao/sqlglot#912]
Input
```
SELECT 1a
```
Current behaviour: parse `a` as alias
Expected behaviour: should rise an error, the query is not valid

**Comment by GeorgeSittas** [comment]
SQLGlot is very lenient when it comes to parsing errors by design. This is so that it can easily parse as much _valid_ SQL as possible, so this isn't really a "bug".

**Comment by evyasonov** [comment]
@GeorgeSittas I believe that this is bug, because SQLGlot in this scenario does not return equivalent code.

`sqlglot.transpile("SELECT 1a", read="presto", write="presto")[0]` returns `SELECT 1 AS a` which is not equivalent. This is if I run  `SELECT 1a` and  `SELECT 1 AS a`, presto will return different outputs. While it should return the same.

This is behaviour that a user of SQLGlot does not expect.

So this is the bug that is needed to be fixed.

**Comment by GeorgeSittas** [comment]
Hey,

> presto will return different outputs.

It's still invalid SQL in Presto though, correct? What I meant is that we don't generally prioritize being robust when it comes to detecting errors, because being lenient means that the codebase is more comprehensive and _does_ parse correct SQL.

Alternatively: SQLGlot's contract is that it will try its best to parse / transpile everything that's valid SQL, but doesn't promise anything about invalid inputs.

I may be wrong here, but fixing this will probably entail changing a core part of the tokenizer's logic, and I'm not sure if it's something worth doing at the moment. I'm happy to tackle this if Toby agrees, though.

**Comment by evyasonov** [comment]
Hey,

> It's still invalid SQL in Presto though, correct?

Yes, it's correct. And currently SQLGlot changes invalid sql into valid, but different sql. Which is unexpected and might cause problems on users' side. Because users use such a great tool as SQLGlot in a different ways as it's written in the documentation:

> SQLGlot is a no dependency Python SQL **parser, transpiler, optimizer, and engine**. It can be used **to format SQL** or translate between [18 different dialects](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/__init__.py) like [DuckDB](https://duckdb.org/), [Presto](https://prestodb.io/), [Spark](https://spark.apache.org/), [Snowflake](https://www.snowflake.com/en/), and [BigQuery](https://cloud.google.com/bigquery/). It aims to read a wide variety of SQL inputs and output syntactically correct SQL in the targeted dialects.

I use it to format sql which might contain errors and in case of incorrect sql I want to show an error and not change user's input...

Regarding the contract -- it's one of the possible option, but in this case the contract should be written in the header of documentation formatted with capslock and red bold font, so users expect unexpected behaviour in case of invalid sql.

@tobymao , what do you think

**Comment by GeorgeSittas** [comment]
Yes, I see your point. Maybe we should emphasize the point about errors more in the README.

By the way, for what it's worth, doing `SELECT 1s` is valid in both DuckDB and SparkSQL.

**Comment by evyasonov** [comment]
Should the issue be reopened? Because it's not completed and no actions were done yet. I don't want it to be lost

**Comment by tobymao** [comment]
no it won’t be fixed

**Comment by evyasonov** [comment]
@tobymao 
Okay... And what about telling that "sqlglot might change behaviour of your code in case sql is not valid" with red bold capslock in documentation?
