### ISSUE TITLE
Support catalog for Trino SQL

### ISSUE THREAD

**Issue by MikeWallis42** [tobymao/sqlglot#93]
At the moment we get an unexpected token error when we write a query with a fully qualified name `catalog.schema.table`

**Comment by tobymao** [comment]
can you show me an example?

**Comment by MikeWallis42** [comment]
Of course, apologies for not providing this upfront. Tested with the current latest version.

```python
import sqlglot

sql = "SELECT * FROM some_catalog.some_schema.some_table"
sqlglot.parse(sql, "presto")
```
`sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 39.`
