### ISSUE TITLE
Execution: correlated subquery where clause

### ISSUE THREAD

**Issue by amacfie** [tobymao/sqlglot#935]
This gives incorrect results:
```python
execute("""
select *
from parts
where parts.qoh = (
    select count(supplies.shipdate)
    from supplies
    where supplies.pnum = parts.pnum and supplies.shipdate < 10
)
""",
    tables=dict(parts=[dict(pnum=0, qoh=0)], supplies=[]),
    schema=dict(
        parts=dict(pnum="int", qoh="int"),
        supplies=dict(pnum="int", shipdate="int"),
    ),
).rows  # ->> []
```

[SQL Fiddle](http://sqlfiddle.com/#!17/6eb89/3)

This is correct (where clause removed):
```python
execute("""
select *
from parts
where parts.qoh = (
    select count(supplies.shipdate)
    from supplies
)
""",
    tables=dict(parts=[dict(pnum=0, qoh=0)], supplies=[]),
    schema=dict(
        parts=dict(pnum="int", qoh="int"),
        supplies=dict(pnum="int", shipdate="int"),
    ),
).rows  # ->> [(0, 0)]
```

**Comment by tobymao** [comment]
this is quite tricky, since we optimize correlated subqueries as joins, it ends up converted to a left join. but the semantics of count() are strange with empty rows. i'm on the verge of giving up on this but there may be a way by always joining an empty table

**Comment by barakalon** [comment]
Can we check if the subquery is an aggregate, and if it is, we coalesce the output column to an inferred default value of the aggregate function? E.g. 0 for COUNT

**Comment by tobymao** [comment]
no because 

count(*) + 1

count(*) on an empty data set is 0, and + 1 returns 1, so the coalesce won't work.

my ideas was to do an additional left join on a 

SELECT FROM SUBQUERY WHERE FALSE

and then doing ... OR ( JOIN KEY IS NULL AND DUMMY_TABLE = value)

**Comment by barakalon** [comment]
What if you took the output expression of the subquery, replaced all aggregate functions with their default, ran ‘simplify’ on it, and used the result as the default value?

Not sure if that’s any better than what you described. Might be a prettier result though.

**Comment by tobymao** [comment]
that seems easier than what i describes

**Comment by tobymao** [comment]
@barakalon this is problematic because you can’t coalesce the join key

**Comment by barakalon** [comment]
Here's what I was imagining:
```sql
WITH "_u_0" AS (
  SELECT
    COUNT("supplies"."shipdate") AS "_col_0",
    "supplies"."pnum" AS "_u_1"
  FROM "supplies" AS "supplies"
  WHERE
    "supplies"."shipdate" < 10
  GROUP BY
    "supplies"."pnum"
)
SELECT
  "parts"."pnum" AS "pnum",
  "parts"."qoh" AS "qoh"
FROM "parts" AS "parts"
LEFT JOIN "_u_0" AS "_u_0"
  ON "_u_0"."_u_1" = "parts"."pnum"
WHERE
  "parts"."qoh" = COALESCE("_u_0"."_col_0", 0)
```

So we don't coalesce the join key - just the column in the predicate

**Comment by tobymao** [comment]
thanks @barakalon take a look at 6c7bf44
