### ISSUE TITLE
values does not work correctly

### ISSUE THREAD

**Issue by evyasonov** [tobymao/sqlglot#946]
valid presto input
```
SELECT bool_or(a> 10) FROM (values 1, 2, 15) AS T(a);
```

return parsing error

P.S. documentation is waiting red capslock telling that sqlglot changes engine behaviour in cases of `SELECT 1s` or `SELECT 1e`

**Comment by tobymao** [comment]
spamming about select 1s is considered very rude. the decision has been made. stop spamming. open up a discussion if you want to have a civil productive conversation.
