### ISSUE TITLE
Crashes when parsing escape sequences

### ISSUE THREAD

**Issue by williame** [tobymao/sqlglot#952]
`SELECT '\\'` is valid in bigquery, and returns `\`

Sqlglot raises a RuntimeError (not ParseError 👎 ) in _extract_string.

A variation, `SELECT '\\', b` crashes with an IndexError in _advance instead.

Another variation, ``SET q="\";"``, also crashes with an IndexError in _advance.

Yet another variation that might be related is an IndexError crash in _find_token:

    SET
    q = "\";\""

(the new-line after SET and the semi-colon between the quotes are necessary to trigger the exact crash)

(Using sqlglot-10.5.0 from pip install defaults)

**Comment by GeorgeSittas** [comment]
I'll take a look, thanks for the reports.
