### ISSUE TITLE
Using reserved words as identifiers

### ISSUE THREAD

**Issue by williame** [tobymao/sqlglot#954]
In Bigquery, various reserved words and builtin function names can be used as unquoted identifiers.

E.g. `WITH view AS (SELECT 1 AS x) SELECT * FROM view` is valid in BQ but raises a ParseError "Expected CTE to have alias".  Renaming the CTE to something else stops the error.

Another example is `WITH q AS (SELECT 'A' as a, 51 as b, 23 as c UNION ALL SELECT 'B', 77, 0) SELECT * FROM q UNPIVOT(values FOR quarter IN (b, c))` which fails with ParseError "Expecting FOR" because the unpivot of `values`; another identifier parses ok.

Another example is `SELECT CAST(time*1000 AS INT64) FROM (SELECT 0.1 AS time)` where `time` is used as a column name; sqlglot raises ParseError "Expected AS after CAST".  Naming the column something else stops the error.

**Comment by GeorgeSittas** [comment]
I'll take a look. I think you just need to add the tokens of interest to `ID_VAR_TOKENS` for this to be resolved.
