### ISSUE TITLE
Add support for Microsoft SQL Server Temporary Tables

### ISSUE THREAD

**Issue by alanrothschild** [tobymao/sqlglot#956]
Greetings and thank you for this excellent library!!!

I would like to request the addition of support for temporary tables in "tsql"

`
CREATE TABLE #MyTempTable (
    col1 INT PRIMARY KEY
);

INSERT INTO #MyTempTable
VALUES (1);
`
I get this error...

Expected table name but got <Token token_type: TokenType.HASH

Below is link to Microsoft SQL Server documentation

https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16#temporary-tables

Note that a single hash is for a local temp table and double hash for global temp table

Thank you thank you thank you:)

**Comment by GeorgeSittas** [comment]
I think this is already supported. Observe:

```python
>>> import sqlglot
>>>
>>> sqlglot.__version__
'10.5.2'
>>>
>>> sql = """
... CREATE TABLE #MyTempTable (
... col1 INT PRIMARY KEY
... );
...
... INSERT INTO #MyTempTable
... VALUES (1);
... """
>>>
>>> print(";\n".join(sqlglot.transpile(sql, read='tsql', pretty=True)))
CREATE TABLE #MyTempTable (
  col1 INTEGER PRIMARY KEY
);
INSERT INTO #MyTempTable VALUES
  (1)
```
