### ISSUE TITLE
Generator.values_sql should always wrap values if WRAP_DERIVED_VALUES

### ISSUE THREAD

**Issue by evyasonov** [tobymao/sqlglot#967]
`SELECT * FROM (VALUES 1, 2, 3)` is transpiled into `SELECT * FROM VALUES (1), (2), (3)` which is non-equivalent code in presto

P.S. How can I configure my custom presto dialect the way it transpiles `date '2022-01-01'` into `date '2022-01-01'` and not into `cast('2022-01-01' as date)`? Is it possible?

**Comment by tobymao** [comment]
you can ask your questions in discussions, but you can override the generator for cast

**Comment by tobymao** [comment]
the code looks equivalent to me

**Comment by tobymao** [comment]
![Screenshot_2023-01-18_21 18 57](https://user-images.githubusercontent.com/8205034/213361523-4bc382da-a624-4df0-9c1f-27818c45a8b5.png)

**Comment by evyasonov** [comment]
@tobymao 
![image](https://user-images.githubusercontent.com/8870922/213394767-e164acde-0673-4258-85db-c205353dc109.png)

Please try to execute
`SELECT * FROM (VALUES 1, 2, 3)`
VS
`SELECT * FROM VALUES (1), (2), (3)`

**Comment by evyasonov** [comment]
@tobymao 
Can you reopen this issue?

**Comment by evyasonov** [comment]
@tobymao 
Please read careful what I wrote and pay attention to the brackets. You executed wrong code.

If if transpile
`SELECT * FROM (VALUES 1, 2, 3)`
which is valid sql and it works in presto, then the result is
`SELECT * FROM VALUES (1), (2), (3)`
which is NOT valid sql and it doesn't work in presto.

To make sure, execute `SELECT * FROM VALUES (1), (2), (3)` and not ``SELECT * FROM (VALUES (1), (2), (3))`

**Comment by tobymao** [comment]
thanks missed it. will fix

**Comment by tobymao** [comment]
d82820e
