### ISSUE TITLE
to_utf8(a, b) is transpiled in to_utf8(a) in presto

### ISSUE THREAD

**Issue by evyasonov** [tobymao/sqlglot#968]
`select to_utf8(a, b)` removes arguments, which is not expected

**Comment by evyasonov** [comment]
Checked the latest version 10.5.4 -- it still removes arguments:
- `SELECT to_utf8(a, b)` is transpiled into `SELECT to_utf8(a)`
- `SELECT to_utf8(a, b, c)` is transpiled into `SELECT to_utf8(a)`

In presto `to_utf8` has just 1 argument, so it makes sense to raise an error in case it's more than 1 argument. Currently it rases the error in case of 4 arguments.

**Comment by evyasonov** [comment]
@tobymao 

Now it don't removes the second argument. But I don't know if it worth to fix -- now it removes the third argument, lol. I.e. `select to_utf8(a, b, c)` is transpiled into `select to_utf8(a, b)`.

When it's 4 arguments, then it fails with `The number of provided arguments (4) is greater than the maximum number of supported arguments (3)` error.

According to documentation `to_utf8` passes just 1 argument, other arguments are not possible.

Maybe it worth to throw the error in case of more than 1 argument.

**Comment by tobymao** [comment]
so utf8 only takes one argument? why did you file the initial issue then?

**Comment by evyasonov** [comment]
Yes, doublecheck the documentation - just 1 argument.

I opened the issue because deleting anything from the code is not good from my point of view. It's better not to parse or to leave code as it is, but not try to fix for the user.

**Comment by tobymao** [comment]
sqlglot is not a validation library. i’ll revert the previous change. don’t file issues like this in the future as they won’t be fixed
