### ISSUE TITLE
SQL Server Procedures and Variables

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#970]
Seems sqlglot cannot parse such stuff:

```sql
CREATE procedure [TRANSF].[SP_Merge_Sales_Real]

   @Loadid INT
  --,@YearMonth int=0
  ,@NumberOfRows INT = NULL OUT

AS
BEGIN
        SET XACT_ABORT ON;

        DECLARE     @DWH_DateCreated    DATETIME                = CONVERT(DATETIME, getdate(), 104);
        DECLARE     @DWH_DateModified   DATETIME                = CONVERT(DATETIME, getdate(), 104);
        DECLARE     @DWH_IdUserCreated  int                             = SUSER_ID (SYSTEM_USER);
        DECLARE         @DWH_IdUserModified int                         = SUSER_ID (SYSTEM_USER)

                         DECLARE @SalesAmountBefore float
                         SELECT @SalesAmountBefore=SUM(SalesAmount) FROM TRANSF.[Pre_Merge_Sales_Real] S

        --ALTER INDEX ALL on [TRANSF].[SP_Merge_Sales_Real] rebuild WITH (DATA_COMPRESSION = ROW)

--      DBCC SHRINKFILE(CORE_log, 1)

END
```

**Comment by aersam** [comment]
seems to be the declare statement as well as the parameters of the procedure. see my draft PR: https://github.com/tobymao/sqlglot/pull/971

**Comment by GeorgeSittas** [comment]
Thanks for the PR. If you like, we could get that in first and then I can look into the rest of this issue.

**Comment by aersam** [comment]
Oh then I was too fast. I added some code to the test that break it. it seems the issue is that for SQL Server an identifier can actually be a variable as well, so maybe t-sql parser should overwrite _parse_identifier

**Comment by aersam** [comment]
there is the concept of TABLE_PREFIX_TOKENS, I should t-sql should also have a concept of PARAMETER_PREFIX_TOKENS

**Comment by aersam** [comment]
next issue seems to be BEGIN/END as used in t-sql function/procedure bodies

**Comment by GeorgeSittas** [comment]
@aersam https://github.com/tobymao/sqlglot/pull/1000

This isn't a complete fix for this issue. T-SQL differs in some parts from other dialects, so it's not always easy to reuse parsing and/or sql generating logic for some of its syntax forms.

The idea behind my fixes is to handle the UDF syntax by parsing it in chunks, separated by `;`. When the fixes are completed, a user should be able to iterate over the parsed chunks (produced by `parse`), and call `.sql` to each of them. This might not be the best / most robust solution to the problem, but it should work for the time being and it's simpler compared to altering `_parse`.

**Comment by GeorgeSittas** [comment]
Fixing the remaining tasks for this issue is not high priority, so I'm closing it for now. May revisit this in the future.

**Comment by aersam** [comment]
Fine for me, I can work around the limitations. Thanks a lot!

**Comment by GeorgeSittas** [comment]
@aersam https://github.com/tobymao/sqlglot/commit/51f440d3f55fb10647ec30f6db415a2af173d785
