### ISSUE TITLE
Using date functions on a dataframe generates invalid SQLite, Snowflake SQL 

### ISSUE THREAD

**Issue by kgdiem** [tobymao/sqlglot#974]
I am using the dataframes library to generate a SQL statement. 

It largely works but I'm having some trouble with the date functions from `sqlglot.dataframe.sql.functions`. 

For example, this code will generate the following SQL for Snowflake and SQLite respectively: 

```
import sqlglot
from sqlglot.dataframe.sql.session import SparkSession
from sqlglot.dataframe.sql.functions import (
    col,
    date_add,
    current_date,
)

sqlglot.schema.add_table(
    "test",
    {
        "id": "INTEGER",
        "date_added": "TIMESTAMP",
    },
)

df = SparkSession().table("test")

df = df.select(col('date_added')).filter(col('date_added').__gt__(date_add(current_date(), -2)))

print(df.sql(dialect='snowflake'))
print(df.sql(dialect='sqlite'))
```

```
['SELECT "test"."date_added" AS "date_added" FROM "test" AS "test" WHERE CAST("test"."date_added" AS DATE) > DATE_ADD(CURRENT_DATE, -2)']

['SELECT "test"."date_added" AS "date_added" FROM "test" AS "test" WHERE CAST("test"."date_added" AS DATE) > DATE_ADD(CURRENT_DATE, -2)']
```

For Snowflake this should be `DATEADD` not `DATE_ADD`.

For SQLite this should be `DATE(..., '-2')`

**Comment by tobymao** [comment]
does sqlite support conversion of a string to a time? i don't know if sqlite even has a date type?

feel free to make a PR

**Comment by tobymao** [comment]
i think it's just a noop, i'll fill this in for you and you can look at it and make a PR next issue you have :)

**Comment by tobymao** [comment]
918ec25
