### ISSUE TITLE
Swaps attributes in function position Clickhouse

### ISSUE THREAD

**Issue by kizimenko** [tobymao/sqlglot#976]
Before sqllot

```
SELECT
  sess_id,
  timestamp,
  name
FROM stats.events
WHERE
  position(name,'popup')>0
  AND date >= '2023-01-16'
GROUP BY
  sess_id,
  timestamp,
  name
ORDER BY
  sess_id,
  timestamp
```

after 

```
SELECT
  sess_id,
  timestamp,
  name
FROM stats.events
WHERE
  position('popup', name) > 0 AND date >= '2023-01-16'
GROUP BY
  sess_id,
  timestamp,
  name
ORDER BY
  sess_id,
  timestamp
```

it swaps attributes in function position

**Comment by cpcloud** [comment]
The swap is intentional: https://clickhouse.com/docs/en/sql-reference/functions/string-search-functions/#positionhaystack-needle-locatehaystack-needle

![image](https://user-images.githubusercontent.com/417981/214372421-98c077d7-475f-4615-80b2-d460417a6345.png)
