### ISSUE TITLE
Unexpected parse result for column w/ no data type [sqlite]

### ISSUE THREAD

**Issue by andrewdoss-bit** [tobymao/sqlglot#984]
When outside of strict mode, sqlite allows column definitions without data types. 

```sql
CREATE TABLE  foo (
    bar INTEGER,
    boo,
    baz INTEGER
);
```

This is parsed as follows:
```python
from sqlglot import parse_one
parse_one(sql, read="sqlite")
```

```shell
(CREATE this: 
  (SCHEMA this: 
    (TABLE this: 
      (IDENTIFIER this: foo, quoted: False)), expressions: 
    (COLUMNDEF this: 
      (IDENTIFIER this: bar, quoted: False), kind: 
      (DATATYPE this: Type.INT, nested: False)), 
    (IDENTIFIER this: boo, quoted: False), 
    (COLUMNDEF this: 
      (IDENTIFIER this: baz, quoted: False), kind: 
      (DATATYPE this: Type.INT, nested: False))), kind: TABLE, transient: False, external: False, no_primary_index: False)
```

`sqlite` [does not allow](https://www.sqlite.org/lang_createtable.html) identifiers between columndef's. 

From there, this expression can be used to generate erroneous SQL for other dialects. 

Should parsing this schema instead result in a parse error, or if not, a special `COLUMNDEF` with no data type?

**Comment by tobymao** [comment]
i don’t understand your proposal, how is an empty column def different from an identifier?

**Comment by tobymao** [comment]
closing this for now. happy to reopen if we figure out an action item.

**Comment by andrewdoss-bit** [comment]
ah, thanks for explaining. 

Here is sqlite's column def syntax — as you point out, without a type or constraint, it's only differentiated from an identifier by surrounding context.

![image](https://user-images.githubusercontent.com/83613318/213791995-11b56188-f774-40ab-a777-62acdbf3d911.png)

Now that I better understand that sqlglot is not trying to validate this type of syntax, especially when transpiling,  I see that this validation scenario can/should be handled by the sqlglot client/user. Given that, no proposal on my end for reopening.
