### ISSUE TITLE
ParseError with Databricks IDENTITY columns

### ISSUE THREAD

**Issue by mkab** [tobymao/sqlglot#987]
When executing `sqlglot.transpile` on a Databricks create statement that contains an [identity column](https://www.databricks.com/blog/2022/08/08/identity-columns-to-generate-surrogate-keys-are-now-available-in-a-lakehouse-near-you.html), a `ParseError` is raised. It seems like sqlglot does not recognise identity columns.

Example: 
Given a databricks sql query:
```sql
CREATE TABLE IF NOT EXISTS customer (
pk BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1),
name string,
age int,
);
```

Transpiling it with sqlglot
```python
import sqlglot
sqlglot.transpile(query, read="databricks")
```

Gives this error:
```bash
ParseError: Expecting ). Line 2, Col: 11.
CREATE TABLE IF NOT EXISTS customer (
pk BIGINT **_GENERATED_** ALWAYS AS IDENTITY (INCREMENT BY 1),
name string,
age int,
);
```

If I ignore the errors, sqlglot truncates the query

```python
import sqlglot
from sqlglot.errors import ErrorLevel
sqlglot.transpile(query, read="databricks", errorlevel=ErrorLevel.IGNORE)

>> ['CREATE TABLE IF NOT EXISTS customer (pk LONG)']
```
Everything after `GENERATED` got deleted.

1. Is it possible to add support for identity columns?
2. How can I ignore the errors without sqlglot truncating the query?
3. Any other solution would be much appreciated

**Comment by GeorgeSittas** [comment]
Thanks, I'll take a look soon.
