### ISSUE TITLE
Make Tokenizer's Tokens printable

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#992]
Hi there

I have some SQL that I cannot sucessfully parse, but still the tokenizer would be great to apply some simple transformations. sadly a token does not store the whitespace that belongs to it, therefore it's hard to generate SQL out of a list of tokens. I think that could be added easily to the tokenizer and could be a quick win?

Thanks for this great library!

**Comment by GeorgeSittas** [comment]
Hey, can you provide an example of what you mean?

**Comment by tobymao** [comment]
tokenization does not include white spaces on purpose to make things easier, closing this for now

**Comment by aersam** [comment]
I have a whole lot of complicated T-SQL Procedure containing all exotic SQL Features and I have some patterns I want to rewrite.  That pattern looks for example like this:
```sql

select    COALESCE(S.[SomeIdField],  @DummyIdDwh)	AS [SomeIdField]
		,COALESCE(S.[OtherField], @DummyIdDwh)	AS [OtherField]
		 ,COALESCE([NextField],@DummyName)	    AS [NextField]
```
I want to get rid of those repetitive COALESCE's , I don't need them anymore
Now I wrote some little code that just removes them in the token list. was straigtforward :) If I only could print them ;)

**Comment by aersam** [comment]
> tokenization does not include white spaces on purpose to make things easier, closing this for now

I understand that decision, but I think adding it is a whole lot easier then to support all sql features in the parser as I think every SQL Dialect has 100's of keywords (ok maybe a bit less ;) ). And it would cover some simple use cases like mine

**Comment by tobymao** [comment]
you can just extract out the tokens you care about and then pass only those to the parser
