### ISSUE TITLE
Parsing of t-sql FOR SYSTEM_TIME 

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#993]
T-SQL FOR SYSTEM_TIME Syntax is not supported
https://learn.microsoft.com/en-us/sql/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table?view=sql-server-ver16

Spark knows something similar: https://issues.apache.org/jira/browse/SPARK-37219

**Comment by GeorgeSittas** [comment]
Thanks for the report, I'll take a look soon.

**Comment by aersam** [comment]
Great, you're fast! For me, FOR SYSTEM_TIME ALL is enough; I dont need the other options for now

**Comment by GeorgeSittas** [comment]
I added them anyway :)

**Comment by aersam** [comment]
Thanks a lot! That will help me!
