### ISSUE TITLE
approx_percentile & percentile_cont are not parsed as Aggregate Functions

### ISSUE THREAD

**Issue by svikas** [tobymao/sqlglot#996]
I've noticed an issue with parsing `approx_percentile` (as a presto query) and `percentile_cont` (as a postgres query). I'm on version `10.5.6` 

1.) neither function is parsed as an `AggFunc` 

To replicate: 
```
import sqlglot 

presto_percentile_query = "SELECT approx_percentile(val1, 0.5) AS value FROM table1"
parsed_presto_query = sqlglot.parse_one(presto_percentile_query)
for agg_func in parsed_presto_query.find_all(sqlglot.exp.AggFunc):
    print(agg_func) 

pg_percentile_query = "SELECT percentile_cont(val1, 0.5) AS value FROM table2" 
parsed_pg_query = sqlglot.parse_one(pg_percentile_query)
for agg_func in parsed_pg_query.find_all(sqlglot.exp.AggFunc):
    print(agg_func) 
```

I would expect the percentile functions to be parsed as AggFunc. 

2.) As a side note that might warrant it's own issue - I've found that when transpiling a Presto query with `approx_percentile`  into Postgres (and vice-versa) it doesn't seem to behave in the expected manner. 

```
import sqlglot
presto_percentile_query = "SELECT approx_percentile(val1, 0.5) AS value FROM table1"
pg_percentile_query = "SELECT percentile_cont(val1, 0.5) AS value FROM table2" 
sqlglot.transpile(presto_percentile_query,read="presto",write="postgres) # This yields SELECT APPROX_QUANTILE(val1, 0.5) AS value FROM table1

sqlglot.transpile(pg_percentile_query, read="postgres",write="presto") # This yields 'SELECT PERCENTILE_CONT(val1, 0.5) AS value FROM table2' 
```

I'm not sure exactly what expected behavior should be, as approx_percentile doesn't neatly map to either `percentile_cont` or `percentile_disc` but I'm not certain what `APPROX_QUANTILE` is in the postgres context. One of `percentile_cont` or `percentile_disc` is more apt. 

In the case of transpiling from Postgres to Presto, I would expect that either `PERCENTILE_CONT` or `PERCENTILE_DISC` get mapped into `APPROX_PERCENTILE` as that seems most apt. 

Please let me know if I can provide more context!

**Comment by tobymao** [comment]
you need to specify the read dialect

parse_one(sql, read=“presto”)

**Comment by tobymao** [comment]
transpilation is best effort, percentile_cont is quite different from approx_percentile because it operates over within_group as opposed to a basic agg function.

i've add the ability to parse `select percentile_disc(0.5) within group (order by x)`

the transpilation of this is more complex and not necessarily possible so i'll consider it as a won't fix for now

**Comment by svikas** [comment]
> you need to specify the read dialect
> 
> parse_one(sql, read=“presto”)

Thanks! I somehow seemed to have missed that the read dialect was necessary here. 

I understand why the transpilation doesn't map in this case, totally reasonable. Much appreciated.
