### ISSUE TITLE
Support for Merge

### ISSUE THREAD

**Issue by aersam** [tobymao/sqlglot#998]
Hi there!

I have a t-sql merge statement:

```sql
MERGE [CORE].[DIM_BusinessUnit] a
			USING [TRANSF].[Merge_BusinessUnit] b
			             ON a.[IdDWH] = b.[IdDWH]
			
			WHEN MATCHED AND EXISTS
			(
				SELECT a.[Name]
					   
				EXCEPT
			        
				SELECT b.[Name]
			
			)
			THEN 
			UPDATE SET     a.[Name]			 =  b.[Name]
						  ;
```

seems to be unparseable

Enough issues for a while now ;) sqlglot is great and already helping me a lot

**Comment by GeorgeSittas** [comment]
Thanks for the reports, I'll take a look. I'm currently tackling the UDF issue, which required a handful of additions in the end

**Comment by aersam** [comment]
Would you mind doing a release with that?
